### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/com.cmplay.cellconnect-1.1.2.apk (FP)

### ISSUE THREAD

**Issue by lon990109tim** [d4rken/sdmaid-public#1001]
### Target
Target: `/storage/emulated/0/Download/com.cmplay.cellconnect-1.1.2.apk`
Prefix-free: `Download/com.cmplay.cellconnect-1.1.2.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `null (0)`~~

Appname: `下載管理服務`
Packagename: `com.android.providers.downloads`
Version: `1.4.2 (142000)`

Appname: `Android 系統`
Packagename: `android`
Version: `1.1 (23)`

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `OPPO/CPH1605/CPH1605:6.0/MRA58K/1487939117:user/release-keys`

**Comment by d4rken** [comment]
That's not a valid change.
