### ISSUE TITLE
Clutterreport: /storage/sdcard0/Music (FP)

### ISSUE THREAD

**Issue by donahue714** [d4rken/sdmaid-public#1002]
### Target
Target: `/storage/sdcard0/Music`
Prefix-free: `Music`
Path-prefix: `/storage/sdcard0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `AT&T FamilyMap`
Packagename: `com.locationlabs.finder.tab.att`
Version: `1.3 (3)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `4.1.2-I497UCBMF2 (16)`

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `samsung/espresso10uc/espresso10att:4.1.2/JZO54K/I497UCBMF2:user/release-keys`

**Comment by d4rken** [comment]
How are these 2 relalted?

**Comment by d4rken** [comment]
Not enough info. Unlikely relation.
