### ISSUE TITLE
Select app for files which does not have extension

### ISSUE THREAD

**Issue by ya8sa** [d4rken/sdmaid-public#1007]
Google drive PDF app is default app for these files. It failes if file is image. Would like to select app such as image opening app.
It will apply for the case the files are listed.

**Comment by d4rken** [comment]
So add an option to the explorer file dialog that allows to choose an app to open a file, like on windows?

**Comment by ya8sa** [comment]
Yes, Attached is shown in Explorer. I like this dailog. please add "FORCE OPENINF AS IMAGE FILE" so that any image app could be selected.
Also please apply this for the listing in the Strage Analyzer, details list of CorpseFinder/ SystemClearner.

![screenshot_20170712-211038](https://user-images.githubusercontent.com/23994337/28188857-97a9d20a-685e-11e7-98ed-587ea7a01db8.png)

**Comment by ya8sa** [comment]
Recent update could show several apps including image viewer in both Storage analyzer and Explorer open menu. It is very easy to display image even it does not have extension such as jpg. Close this issue.
Thanks.
