### ISSUE TITLE
Clutterreport: /storage/emulated/0/.Audiomack/playlist.jpg (new)

### ISSUE THREAD

**Issue by sfarm3300** [d4rken/sdmaid-public#1010]
### Target
Target: `/storage/emulated/0/.Audiomack/playlist.jpg`
Prefix-free: `.Audiomack/playlist.jpg`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Gallery`
Packagename: `com.tct.gallery3d`
Version: `v6.0.1.1.0149.0 (62)`

### Current owners
None

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `TCL/A466BG/PIXI4_4TF:6.0/MRA58K/v6F29-0:user/release-keys`

**Comment by d4rken** [comment]
What is the relation between the app and file?

**Comment by d4rken** [comment]
Not enough information.
