### ISSUE TITLE
Include directories / files for delete

### ISSUE THREAD

**Issue by honsberg** [d4rken/sdmaid-public#1012]
Please make a User defined  list of Files and/or directories, which Always should bei deleted. 

For example:
a Game Downloads ad Videos which i want to delete
A App Always writes an logfile
File Manager creates thumb Cache in .../emumlated/0/.rhmsoft
Want to delete 3 of 5 WhatsApp Backups. 
....

**Comment by d4rken** [comment]
This is possible by defining custom SystemCleaner filter, see:
https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner

**Comment by honsberg** [comment]
Thanx.
