### ISSUE TITLE
Clutterreport: /data/user/0/flipfont (FP)

### ISSUE THREAD

**Issue by xtorker** [d4rken/sdmaid-public#1014]
### Target
Target: `/data/user/0/flipfont`
Prefix-free: `flipfont`
Path-prefix: `/data/user/0/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `愛字體 捐贈版`
Packagename: `com.kapp.ifont.donate`
Version: `5.7.6 (116)`

### Current owners
~~Appname: `?`~~
~~Packagename: `touchwiz`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `asus/WW_Phone/ASUS_Z012D:6.0.1/MMB29P/13.20.10.152-20161222:user/release-keys`

### Comment
`This is the custom fonts change data, should not be deleted, or the custom fonts setting will be failed.`

**Comment by d4rken** [comment]
Why did you delete the owner "touchwiz"?

**Comment by xtorker** [comment]
what's mean delete touchwiz?
I guess this "touchwiz" is created from the fonts change app. 
I use the "install mode" to change fonts, and the app description say that mode is used on Samsung phone etc.
I guess that's why it comes out with the touchwiz name.
I'm using ZenUI.
