### ISSUE TITLE
Clutterreport: /storage/emulated/0/backups

### ISSUE THREAD

**Issue by Uncle-Harry** [d4rken/sdmaid-public#1016]
### Target
Target: `/storage/emulated/0/backups`
Prefix-free: `backups`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `ccc71.at.free`~~
~~Version: `null (0)`~~

~~Appname: `?`~~
~~Packagename: `ccc71.at`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `com.estrongs.android.pop.app.shortcut`
Version: `null (0)`

Appname: `?`
Packagename: `com.estrongs.android.pop.pro`
Version: `null (0)`

Appname: `?`
Packagename: `com.estrongs.android.pop`
Version: `null (0)`

Appname: `?`
Packagename: `com.estrongs.android.pop.cupcake`
Version: `null (0)`

Appname: `?`
Packagename: `com.jrummy.app.managerfree`
Version: `null (0)`

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `kyocera/C6742A/C6742A:5.1.1/LMY47V/0506_2050:user/release-keys`

**Comment by Uncle-Harry** [comment]
Odd "stocking stuffer " storage trash is filling memory in this Kyocera device.

**Comment by d4rken** [comment]
That's not how the clutter report system is intended to be used.

You should report files that are unknown to SD Maid, if you know the owner.

This report suggests no new owners, deletes two existing owners and changes this directories state from "keeper" to "non-keeper" which seems incorrect for a folder named `backups`.

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/CorpseFinder#reporting-false-positives
