### ISSUE TITLE
CorpseFinder failed to recognize leftover data from uninstalled app

### ISSUE THREAD

**Issue by NinjaBoyLao** [d4rken/sdmaid-public#1017]
Device: Moto X Pure, Android 6.0, rooted with Magisk. SD Maid has permissions for superuser. 64GB SD card mounted as Portable storage (not adopted)

Issue: I tried the game Puzzle and Dragons for a few days and didn't like it due to a game mechanic, so I uninstalled it. Later, looking through my storage, I found the entire ~100MB storage directory it created when I selected the option to have it store it's update data on my SD card. Instead of trying a manual deletion through the crappy stock android file explorer (not sd maids), i decided to run CorpseFinder instead. Surprise surprise, it did not detect the directory at all. Possibly this is because the directory was not nested in any of the typical "app storage" paths and was just sitting at the root of the SD card. It was named "PAD". Why did SD maid fail to see this and what can i provide to help you diagnose this?

**Comment by d4rken** [comment]
Check in SD Maids Explorer, if the folder shows a `?` symbol as icon then it's just a definition issue. Automatic matching doesn't work very well on the root of the sdcard and we have to make due with a "clutter database".

The `?` icon should be pressable and take you to a report screen.

**Comment by d4rken** [comment]
Any update on this?

**Comment by NinjaBoyLao** [comment]
Yes i downloaded the game again and did the same stuff, it appears to be exactly as you described. im sorry for taking so long im scrambling to get prepped somewhat for fall semester

**Comment by d4rken** [comment]
Can you attach the necessary information?
Package name of the app and path of the folder SD Maid doesn't know?

Then I can patch this and close the ticket with v4.7.6 😁

**Comment by NinjaBoyLao** [comment]
package name of app: `jp.gungho.padEN`  

folder path: `(sdcardroot)\PAD\`  

The folder is at the root of the SD card, not the root of internal storage.
