### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/System (FP)

### ISSUE THREAD

**Issue by TheRedSpy115** [d4rken/sdmaid-public#1018]
### Target
Target: `/storage/emulated/0/Android/data/System`
Prefix-free: `System`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `7.0 (24)`

### Current owners
None

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `Verizon/hero2qltevzw/hero2qltevzw:7.0/NRD90M/G935VVRU4BQF2:user/release-keys`

**Comment by d4rken** [comment]
What makes you think the system owns this folder?
