### ISSUE TITLE
Clutterreport: /storage/emulated/0/root aces (new)

### ISSUE THREAD

**Issue by dima246** [d4rken/sdmaid-public#1019]
### Target
Target: `/storage/emulated/0/root aces`
Prefix-free: `root aces`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Automation Test`
Packagename: `com.sec.android.app.DataCreate`
Version: `1.0 (1)`

### Current owners
None

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `samsung/a5ltexx/a5lte:6.0.1/MMB29M/A500FXXS1CQC1:user/release-keys`

**Comment by d4rken** [comment]
What leads you to this conclusions?
