### ISSUE TITLE
Clutterreport: /storage/emulated/0/System Updater (new)

### ISSUE THREAD

**Issue by dima246** [d4rken/sdmaid-public#1020]
### Target
Target: `/storage/emulated/0/System Updater`
Prefix-free: `System Updater`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Application installer`
Packagename: `com.sec.android.preloadinstaller`
Version: `6.0.1 (23)`

### Current owners
None

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `samsung/a5ltexx/a5lte:6.0.1/MMB29M/A500FXXS1CQC1:user/release-keys`

**Comment by d4rken** [comment]
What makes you think they are related?
