### ISSUE TITLE
Clutterreport: /storage/emulated/0/ViPER4Android

### ISSUE THREAD

**Issue by Eldhopj** [d4rken/sdmaid-public#1026]
### Target
Target: `/storage/emulated/0/ViPER4Android`
Prefix-free: `ViPER4Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `ViPER4Arise`
Packagename: `com.pittvandewitt.viperfx`
Version: `2.5.0.5 (2505)`

### Current owners
Appname: `?`
Packagename: `com.vipercn.viper4android_v2`
Version: `null (0)`

Appname: `?`
Packagename: `com.vipercn.viper4android`
Version: `null (0)`

Appname: `?`
Packagename: `com.audlabs.viperfx`
Version: `null (0)`

Appname: `?`
Packagename: `com.vipercn.viper4android.xhifi`
Version: `null (0)`

Appname: `?`
Packagename: `com.vipercn.viper4android_v2_fx`
Version: `null (0)`

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `Xiaomi/kenzo/kenzo:6.0.1/MMB29M/V8.2.1.0.MHOCNDL:user/release-keys`

**Comment by d4rken** [comment]
#1009 

Just didn't have time yet for an update 😦

**Comment by Eldhopj** [comment]
Thanks for your response, it's  not a problem buddy 😊

Remind to include in next update, looking forward to it

On Jul 22, 2017 8:50 PM, "Matthias Urhahn" <notifications@github.com<mailto:notifications@github.com>> wrote:

#1009<https://github.com/d4rken/sdmaid-public/issues/1009>

Just didn't have time yet for an update 😦
