### ISSUE TITLE
ads tracker

### ISSUE THREAD

**Issue by igoivo** [d4rken/sdmaid-public#1037]
Hi. It would be nice to have info which app is responsible for ads trash when making system scan.

**Comment by d4rken** [comment]
Ad related files that have a known owner should already be matched by AppCleaners "Advertisement" filter.

Is that what you are looking for? Otherwise please elaborate.

**Comment by igoivo** [comment]
Dear Matthias. I meant that it would be good to know which app is responsible for the particular advertisement files. For instance, I dream to get rid of app, which shows me ads every time when I unlock my phone.

**Comment by d4rken** [comment]
Detecting which apps shows you the ads on your lockscreen is not within SD Maids scope, sorry.

**Comment by igoivo** [comment]
Dear Matthias. It was only example. My question is which app has left the advertisement files reported by SD Maid?

**Comment by d4rken** [comment]
Ad files with known owners will be listed within the AppCleaner tool. To view only those files and it's apps, you could deactivate all but the advertisement filter. Note though that this will only list ad files that are outside of the normal cache folder.

The SystemCleaner also has an ad file filter but can't show who owns a file.

If you see any ad files that SD Maid does not recognize, you can make an issue ticket and I'll improve matching.

You can use the explorer to see recognized files.
