### ISSUE TITLE
Clutterreport: /storage/emulated/0/.a (new)

### ISSUE THREAD

**Issue by mario8413** [d4rken/sdmaid-public#1040]
### Target
Target: `/storage/emulated/0/.a`
Prefix-free: `.a`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Common Data Service`
Packagename: `com.mediatek.connectivity`
Version: `1.0 (1)`

### Current owners
None

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `lge/mk6p55_spr_us/mk6p55:6.0.1/MXB48T/17199190414b9:user/release-keys`

**Comment by jerry197751** [comment]
Jerry
