### ISSUE TITLE
add "INCLUDE" Options and also Add Webviews on App Cache Deleter

### ISSUE THREAD

**Issue by St3gm4** [d4rken/sdmaid-public#1042]
add include options... and i observed that you didnt include the webviews of all apps in the root/data/data storage.. disappointed because webview is the more eating storage than standard cache there.. i see it on my root/data/data ... theres no difference.. stray webviews are pure garbages .. please include it on app cleaner.. thats my only problem.. tnx.
 (i copy my Feedback here, Tnx anyway, waiting for update)

**Comment by St3gm4** [comment]
My email -> denzel_lucero@yahoo.com.. tnx bro.

**Comment by d4rken** [comment]
The AppCleaner already has a [webview filter](https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#default).
What files are being missed?

I need some examples.  Post some pathes, screenshots or pathdumps.

**Comment by d4rken** [comment]
Not enough info to work on this.
