### ISSUE TITLE
Clutterreport: /tombstones (FP)

### ISSUE THREAD

**Issue by bmksj5** [d4rken/sdmaid-public#1055]
### Target
Target: `/tombstones`
Prefix-free: `/tombstones`
Path-prefix: ``
Type: `SYMBOLIC LINK`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `MetroPCS/m209n_mpcs_us/m209n:7.0/NRD90U/1715609491de2:user/release-keys`

### Comment
`suspicious build date`

**Comment by d4rken** [comment]
Clutter reports are for reporting ownership relations.
