### ISSUE TITLE
Clutterreport: /storage/sdcard0/Download/base.apk (FP)

### ISSUE THREAD

**Issue by voravit505** [d4rken/sdmaid-public#1057]
### Target
Target: `/storage/sdcard0/Download/base.apk`
Prefix-free: `Download/base.apk`
Path-prefix: `/storage/sdcard0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `BLEManager`
Packagename: `com.mediatek.blemanager`
Version: `5.1-1457602794 (22)`

### Current owners
Appname: `ระบบ Android`
Packagename: `android`
Version: `5.1-1457600795 (22)`

Appname: `ดาวน์โหลด`
Packagename: `com.android.providers.downloads.ui`
Version: `5.1-1457602794 (22)`

Appname: `ตัวจัดการการดาวน์โหลด`
Packagename: `com.android.providers.downloads`
Version: `5.1-1457602794 (22)`

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `alps/full_n331b/n331b:5.1/LMY47D/1457600795:user/release-keys`

**Comment by d4rken** [comment]
Files within `/Download` belong to the parent.
