### ISSUE TITLE
Clutterreport: /data/user/0/minuhome.Metal_Black (FP)

### ISSUE THREAD

**Issue by vertalius** [d4rken/sdmaid-public#1061]
### Target
Target: `/data/user/0/minuhome.Metal_Black`
Prefix-free: `minuhome.Metal_Black`
Path-prefix: `/data/user/0/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Samsung Themes`
Packagename: `com.samsung.android.themestore`
Version: `3.0.95-70424 (309570424)`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `samsung/dream2ltexx/dream2lte:7.0/NRD90M/G955FXXU1AQF7:user/release-keys`

### Comment
`Samsung Themes`

**Comment by d4rken** [comment]
Is there a pattern to this? How are other themes named?

**Comment by vertalius** [comment]
No it doesn't. Just "authorname.themename". Sorry for disturbing, now I see that is useless to add themes 1by1 to excluded list. Don't bother)  пятница, 11 августа 2017, 11:34ДП +03:00 от Matthias Urhahn  notifications@github.com :

**Comment by d4rken** [comment]
If there is some pattern to it, possibly inside the folder or via group/owner then I could look further.

There was #989 which sound similar but no details were provided, I fixed some LG theme issues in #615 as there was a pattern to it.

Is this a Samsung ROM specific theming tool? Placing the themes in `/data/data` seems wrong.

**Comment by d4rken** [comment]
Could we maybe detect this by checking the files inside this folder?

**Comment by d4rken** [comment]
Lack of info to proceed on this.
