### ISSUE TITLE
Clutterreport: /storage/emulated/0/TouchPalv5/.info/identify_info

### ISSUE THREAD

**Issue by msibircev** [d4rken/sdmaid-public#1064]
### Target
Target: `/storage/emulated/0/TouchPalv5/.info/identify_info`
Prefix-free: `TouchPalv5/.info/identify_info`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
Appname: `?`
Packagename: `com.cootek.smartinputv5`
Version: `null (0)`

~~Appname: `?`~~
~~Packagename: `com.emoji.keyboard.touchpal`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `com.cootek.smartinputv5.oem`
Version: `null (0)`

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `Meizu/meizu_MX6/MX6:6.0/MRA58K/1482216814:user/release-keys`

Delete now?
Можно？

**Comment by d4rken** [comment]
This is not what clutter reports are for.
