### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/accs/accs_main/1/accs_election (FP)

### ISSUE THREAD

**Issue by Talon422** [d4rken/sdmaid-public#1069]
### Target
Target: `/storage/emulated/0/Download/accs/accs_main/1/accs_election`
Prefix-free: `Download/accs/accs_main/1/accs_election`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `7.0 (24)`~~

~~Appname: `Download manager`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `7.0 (24)`~~

~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `7.0 (24)`~~

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `samsung/j3popeltemtr/j3popeltemtr:7.0/NRD90M/J327T1UVU1AQG1:user/release-keys`

**Comment by Talon422** [comment]
We are mis-directed, access denied, our bank accounts, and payments messed with. Purchased apps will not work. Plus,  7 computers, and 5 cellphones destroyed.

**Comment by d4rken** [comment]
What does this have to do with SD Maid?
