### ISSUE TITLE
Clutterreport: /system/app/CertInstaller/CertInstaller.apk (FP)

### ISSUE THREAD

**Issue by oswaltalvaradolopez** [d4rken/sdmaid-public#1087]
### Target
Target: `/system/app/CertInstaller/CertInstaller.apk`
Prefix-free: `CertInstaller/CertInstaller.apk`
Path-prefix: `/system/app/`
Type: `FILE`
Location: `SYSTEM_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `A Faster Reader`
Packagename: `com.basetis.blinkingread.blinkingread`
Version: `4.2.3 (Super) (67)`

Appname: `9Apps`
Packagename: `com.mobile.indiapp`
Version: `3.3.0.01 (120)`

Appname: `Adblock Browser`
Packagename: `org.adblockplus.browser`
Version: `1.2.0 (2017081620)`

Appname: `Instalador de certificados`
Packagename: `com.android.certinstaller`
Version: `5.1.1-G530AZTUS4BQE2 (22)`

### Current owners
Appname: `Instalador de certificados`
Packagename: `com.android.certinstaller`
Version: `5.1.1-G530AZTUS4BQE2 (22)`

### SD Maid
Version: `4.7.5 (40705)`

### Device
Fingerprint: `samsung/grandprimeltetu/grandprimelteaio:5.1.1/LMY48B/G530AZTUS4BQE2:user/release-keys`

**Comment by d4rken** [comment]
These are all invalid reports, please don't use the report functionality if you don't know what your are doing.

**Comment by oswaltalvaradolopez** [comment]
#1633 @

- [ ]
