### ISSUE TITLE
i Need help ☺

### ISSUE THREAD

**Issue by iwillgo5777** [d4rken/sdmaid-public#1090]
Brauche jemand ...der davon was versteht. 
Ich verstehe nämlich nur Bahnhof 😓. 
Möchte einfach ...das mein Android System rund läuft... und das meine Privacy privat bleibt... das ich mir aussuchen kann ...wem ich eintritt gewähre. Wäre sehr dankbar für Unterstützung. 
LG

ONELOVE☝

**Comment by d4rken** [comment]
I'm not sure what specifically you are looking for.

SD Maids functions are explained here:
https://github.com/d4rken/sdmaid-public/wiki

Besides being privacy minded itself, SD Maid does not have any specific function to increase privacy (like firewalls etc).
