### ISSUE TITLE
Clutterreport: /data/user/0/com.lge.wernicke.nlp.overlay (FP)

### ISSUE THREAD

**Issue by salvaparalyzer** [d4rken/sdmaid-public#1096]
### Target
Target: `/data/user/0/com.lge.wernicke.nlp.overlay`
Prefix-free: `com.lge.wernicke.nlp.overlay`
Path-prefix: `/data/user/0/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `LG System Resources`
Packagename: `com.lge`
Version: `3.0.0 (300)`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `lge/elsa_global_com/elsa:7.0/NRD90M/1634917175efa:user/release-keys`

### Comment
`lg themes overlay`

**Comment by d4rken** [comment]
Any update on this?

**Comment by salvaparalyzer** [comment]
Sorry, didn't look this.
well, I excluded all the files that had com.lge. and had no problem
therefore.

2017-09-13 8:16 GMT-05:00 Matthias Urhahn <notifications@github.com>:
