### ISSUE TITLE
Cache partition missing under Storage Analyzer

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1110]
![screenshot_20170829-062438](https://user-images.githubusercontent.com/3611312/29816991-5204e2cc-8c84-11e7-9c27-4c00bf9d62d5.png)
![screenshot_20170829-062454](https://user-images.githubusercontent.com/3611312/29817006-6294b054-8c84-11e7-92fd-014284ae0605.png)
Reproducible on two devices, a Nexus 9 and 6P both running 7.1.2 OmniROM.  SD Maid v4.7.6, unlocked version 4.1.2. Using SuperSu 2.82. Make sure you select cache under Settings > Storage Analyzer and refresh Storage Analyzer. Notice the cache partition is missing, and it should be visible.

**Comment by d4rken** [comment]
Is the cache partitition path `/data/cache`?

**Comment by d4rken** [comment]
`/cache` exists, but the system uses `/data/cache` which is also returned by `Environment.getDownloadCacheDirectory`.

So not a bug, just confusing Android storage stuff (again).
