### ISSUE TITLE
Introduce UI for filing bug reports

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1111]
Make it aesthetically similar to the UI for filing clutter reports. Would save a lot of time on the user's end. Ensure this runs with with debugging on and is verbose

**Comment by d4rken** [comment]
And if it is a beta build, show a button in the navigation drawer for it.

**Comment by d4rken** [comment]
![2018-06-28 15 47 39](https://user-images.githubusercontent.com/1439229/42038383-154e9f2a-7aeb-11e8-84b3-d09a0aab86bf.png)
![2018-06-28 15 47 51](https://user-images.githubusercontent.com/1439229/42038389-17943a74-7aeb-11e8-83d1-e74a99445800.png)
