### ISSUE TITLE
Clutterreport: /data/app/com.creativemoh.mountainnight.wallpaperpack-1 (FP)

### ISSUE THREAD

**Issue by Zipzn** [d4rken/sdmaid-public#1115]
### Target
Target: `/data/app/com.creativemoh.mountainnight.wallpaperpack-1`
Prefix-free: `com.creativemoh.mountainnight.wallpaperpack-1`
Path-prefix: `/data/app/`
Type: `DIRECTORY`
Location: `APP_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Samsung Themes`
Packagename: `com.samsung.android.themestore`
Version: `3.1.08.70622 (310870622)`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQH3:user/release-keys`

**Comment by d4rken** [comment]
Is this a theme that was downloaded?

Do false positives happen for all downloaded themes?

**Comment by Zipzn** [comment]
The problem is that it deletes the active theme components, however the theme works fine. Only after a reboot the device reverts back to the default theme and I have to download and apply it again

**Comment by d4rken** [comment]
The issue is that it's infeasible to add ALL themes to the database, there needs to be a good way, a pattern to detect the relation ship between `com.creativemoh.mountainnight.wallpaperpack-1` and `com.samsung.android.themestore`.

Do you see any way to detect this?

**Comment by d4rken** [comment]
Did you find any pattern we could use to detect the themes?

We can't feasibly add all themes to SD Maids database, so currently I only see manual exclusions by the user as option. I don't have a recent Samsung device to reproduce this.
