### ISSUE TITLE
No manual cache cleaning through ApplCleaner on Oreo

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1121]
The cache section in settings is simply missing. You can't manually clear cache in Oreo. I know of no way to manually clear it, period. Was removed since one of the developer previews.

**Comment by d4rken** [comment]
What do you propose to do?

I checked and the warning in SD Maid takes you to a "free space" screen in Android Oreo's system, but you are right, there is no option to clear caches there, just "free space" which only seems to offer to wipe the `/Download` folder and uninstall seldomly used apps.

So we just remove this shortcut on Oreo?

**Comment by d4rken** [comment]
Removed it on Oreo.
