### ISSUE TITLE
Clutterreport: /storage/emulated/0/APK Extractor Pro/walmart_v17.14.1_com.walmart.android.xapk (new)

### ISSUE THREAD

**Issue by sixpac4sure** [d4rken/sdmaid-public#1122]
### Target
Target: `/storage/emulated/0/APK Extractor Pro/walmart_v17.14.1_com.walmart.android.xapk`
Prefix-free: `APK Extractor Pro/walmart_v17.14.1_com.walmart.android.xapk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true'
Suggested keeper state: `true`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `samsung/j7eltemtr/j7eltemtr:6.0.1/MMB29K/J700T1UVS3AQF1:user/release-keys`

### Comment
`My app and I use it alot,don't want it deleted.`

**Comment by d4rken** [comment]
What app?

You didn't select any owner app.
