### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/com.sonymobile.android.addoncamera.supervideo-1.0.B.1.10.apk (FP)

### ISSUE THREAD

**Issue by aysean1** [d4rken/sdmaid-public#1128]
### Target
Target: `/storage/emulated/0/Download/com.sonymobile.android.addoncamera.supervideo-1.0.B.1.10.apk`
Prefix-free: `Download/com.sonymobile.android.addoncamera.supervideo-1.0.B.1.10.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Camera`
Packagename: `com.sonyericsson.android.camera`
Version: `1.0.B.1.10 (2098186)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `6.0.1 (23)`

Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `6.0.1 (23)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `6.0.1 (23)`

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `Sony/D6633/D6633:6.0.1/23.5.A.1.291/2769308465:user/release-keys`

**Comment by d4rken** [comment]
The sony camera app does not own the contents of `/Download`.
