### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM/Camera/20170909_181745.jpg (FP)

### ISSUE THREAD

**Issue by thepoeit** [d4rken/sdmaid-public#1129]
### Target
Target: `/storage/emulated/0/DCIM/Camera/20170909_181745.jpg`
Prefix-free: `DCIM/Camera/20170909_181745.jpg`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `7.0 (24)`

Appname: `Android System WebView`
Packagename: `com.google.android.webview`
Version: `0.0.0.1 (100)`

Appname: `Authenticator`
Packagename: `com.google.android.apps.authenticator2`
Version: `4.74 (2000074)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `7.0 (24)`

~~Appname: `?`~~
~~Packagename: `com.google.android.GoogleCamera`~~
~~Version: `null (0)`~~

~~Appname: `?`~~
~~Packagename: `com.android.camera`~~
~~Version: `null (0)`~~

~~Appname: `?`~~
~~Packagename: `com.sec.android.app.camera`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `MetroPCS/lv517_mpcs_us/lv517:7.0/NRD90U/17075180090e7:user/release-keys`

**Comment by thepoeit** [comment]
Ive been hacked and the are changing permissions

**Comment by thepoeit** [comment]
Help

**Comment by d4rken** [comment]
You have not been hacked and this is not the place for help.
