### ISSUE TITLE
Keep game cache from Assassins Creed: Identity

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#1138]
I suggest keeping the game files under `/storage/emulated/0/Android/data/com.ubisoft.assassinscreed.identity/files/cache` for the game [Assassin's Creed Identity](https://play.google.com/store/apps/details?id=com.ubisoft.assassinscreed.identity) (it is paid) because it is needed to run the game and after a clean you would need to download the 2GB again. You should treat it like game data that is downloaded from other games like Heartstone but in a better named folder.

**Comment by d4rken** [comment]
I agree that this can be anoying, but these files would still fit the AppCleaners definition of "expendable files", as they can just be downloaded again if necessary.

I think the appropriate option here would be to turn off the "hidden caches" filter, or to add a manual exclusion. If someone desperately needs space, deleting these files would certainly be an easy way to gain space without loosing data permanently (it can be downloaded again).

Would you agree?

**Comment by SuperSandro2000** [comment]
I kinda agree with you. There is no good awnser for this problem I think. For now I added an exlusion for myself.
