### ISSUE TITLE
Clutterreport: /storage/emulated/0/linkmessages (new)

### ISSUE THREAD

**Issue by feistyone68** [d4rken/sdmaid-public#1141]
### Target
Target: `/storage/emulated/0/linkmessages`
Prefix-free: `linkmessages`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Messenger`
Packagename: `com.link.messages.sms`
Version: `1.7.9 (179)`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `samsung/j3xlteuc/j3xlteatt:6.0.1/MMB29K/J320AUCS3AQG1:user/release-keys`

**Comment by d4rken** [comment]
What kind of data does this contain? Backups?

**Comment by feistyone68** [comment]
Partially. I'm new to this so I could be wrong. 

Contains 2 folders. One named files that has 0 items and one named gif that has 359 items and both folders have drw permissions. 

It also contains 4 PNG images I use for custom backgrounds. The last 2 items are JPG images that I shared from Facebook. The 6 image files have rw permissions.

The only files I was concerned about losing were my custom backgrounds. 

Not sure how important the other are.

**Comment by d4rken** [comment]
You did everything correctly, if this contains things such as the custom backgrounds, that you want to keep even after removing the app, then it is correct to mark it as keeper.

The clutter report itself just teaches SD Maid about the connection, the "keeper" flag tells SD Maid whether the files are to be kept even without the app that created them.
