### ISSUE TITLE
Clutterreport: /storage/sdcard1/dload (new)

### ISSUE THREAD

**Issue by jaif51** [d4rken/sdmaid-public#1143]
### Target
Target: `/storage/sdcard1/dload`
Prefix-free: `dload`
Path-prefix: `/storage/sdcard1/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Actualizar software`
Packagename: `com.huawei.android.hwouc`
Version: `13.5.05 (13505)`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `HUAWEI/LISZT/hwliszt:5.1.1/HUAWEIM2-A01W/C100B007:user/release-keys`

**Comment by d4rken** [comment]
What kind of data does this contain?

**Comment by jaif51** [comment]
Hello, excuse me, I had a 7 year old son by my side and I left him just a
moment and something had to be done: I regret the confusion. I close
thread. Thanks and sorry.

**Comment by d4rken** [comment]
No problem.
