### ISSUE TITLE
Clutterreport: /storage/sdcard1/TWRP

### ISSUE THREAD

**Issue by Locash** [d4rken/sdmaid-public#1147]
One of the BEST file manager+plus apps out there!! It is an essential app when flashing a new ROM. imo

### Target
Target: `/storage/sdcard1/TWRP`
Prefix-free: `TWRP`
Path-prefix: `/storage/sdcard1/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.jmz.soft.twrpmanager`
Version: `null (0)`

Appname: `?`
Packagename: `com.jmz.soft.livebackuppaid`
Version: `null (0)`

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `lge/e7lte_att_us/e7lte:4.4.2/KOT49I.V41010d/V41010d.1406542706:user/release-keys`

### Comment
`Twrp Boot Recovery Manager/Firmware backups`

**Comment by d4rken** [comment]
I don't understand the report. What change are you suggesting?
