### ISSUE TITLE
Bug Notification Persistent

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1148]
Even with persistent notifications turned off, it continues to show quick notifications.
Version 4.8.0

**Comment by d4rken** [comment]
Hm I think i fucked this up, the setting for "Persistent notifications" shouldn't actually be there anymore. 

Which notifications are we talking about, the progress ones ("Working on....") or the result ones ("Task results:...") and how do you want them to behave?

**Comment by GabrielMGitHub** [comment]
The option exists in settings, comes as enabled, when disabled does not work immediately you have to close and open the program, however it returns to show the notifications randomly in almost all checks done manually.

**Comment by GabrielMGitHub** [comment]
If you open the settings or the options that exist in the scans, the notification returns to show, even though the persistent notifications are disabled.

**Comment by d4rken** [comment]
Yeah the results notification shouldn't show when entering the settings. I will look into that.

The "Persistent Notifications" option doesn't work because i forgot to remove the UI element. I rewrote the notification code and did not add this feature again. Do you need this option and if so, why?

**Comment by GabrielMGitHub** [comment]
These Notifications continue to show even by disabling persistent notifications.
![screenshot_20170922-161902](https://user-images.githubusercontent.com/8754997/30760765-dbfc372e-9fb1-11e7-8469-8493747eb72f.jpg)
![screenshot_20170922-161626](https://user-images.githubusercontent.com/8754997/30760768-dc015a06-9fb1-11e7-9034-573b3a047fd5.jpg)
![screenshot_20170922-161534](https://user-images.githubusercontent.com/8754997/30760766-dbfe28ae-9fb1-11e7-8b38-7ceee255a866.jpg)

**Comment by d4rken** [comment]
The notification on your 2nd screenshot is a bug. The notification on your last screenshot is normal.

**Comment by GabrielMGitHub** [comment]
Because it is very annoying to be showing notifications for every thing you do manually. And another notification is not fully functional, if you do an application scan is shown the notification, if you close the SD Maid and click the Notification is not directed to application scanning but to QuickAcess.

**Comment by d4rken** [comment]
> Because it is very annoying to be showing notifications for every thing you do manually. 

The bug is that it should only show when SD Maid is not open. Is it also a problem to show notifications without SD Maid being open? I would think that users want to know what SD Maid is doing in the background.

> And another notification is not fully functional, if you do an application scan is shown the notification, if you close the SD Maid and click the Notification is not directed to application scanning but to QuickAcess.

Yes that's something I can improve upon in a future update. If multiple tasks are running we open QuickAccess, if one task is running then we can show the specific tool.

**Comment by GabrielMGitHub** [comment]
These notifications are showing when SD Maid is open, for example, if you do Duplicate File Scan shows Notification, if you scan Application shows Notification, as you said this notification only showed when running in the background in case of scheduling.

**Comment by d4rken** [comment]
> These notifications are showing when SD Maid is open, for example, if you do Duplicate File Scan shows Notification, if you scan Application shows Notification, as you said this notification only showed when running in the background in case of scheduling.

Yes, we this is a bug. I think it's caused by entering the settings, if I don't open the settings after killing SD Maid, then it works as intended. Fixing it now.

The question is : After fixing this bug, is it still necessary to have the option "persistent notifications"? Is it okay to show notifications when SD Maid is not open?

**Comment by GabrielMGitHub** [comment]
I believe it's good to show Notification when you schedule something because by notifying you to know when the schedule has started and what it is running. Now it opens the program executes a task, and lets in background should show the notification, however when opening the program again the notification should disappear automatically. Having the option to disable persistent notifications I think is valid, but only if you leave the application running when doing another task on the phone, the only Notification that should be persistently active should be only the scheduled execution.

**Comment by d4rken** [comment]
Would you like to mail me (support@...), try a test version and give me feedback on this issue?

**Comment by GabrielMGitHub** [comment]
Example, opened the Maid SD performed a task, and opened another application, the notification should show what it is doing, when opening the SD Maid again the notification should disappear since the application is open.

However there has to be an option to disable this, many people have small screen mobiles, low cost mobiles and other people like me who do not like this notifications.

The only notification that has to be persistent is the one that is scheduled.

**Comment by GabrielMGitHub** [comment]
`Would you like to mail me (support@...), try a test version and give me feedback on this issue?`
I already use test version.

**Comment by GabrielMGitHub** [comment]
I sent you an email.

**Comment by GabrielMGitHub** [comment]
I sent you an email to contact, I just can not test all the options because I use Free version.

**Comment by d4rken** [comment]
Confirmed to be fixed. SD Maid misscounted the service bind references which prevent SD Maid from detecting whether we were executing from the background.

**Comment by GabrielMGitHub** [comment]
Hi

I just found another flaw in the notification, when executing an action or all the actions in Quick Access and then clicking on settings, the notifications start to appear, the application is understanding that when entering settings the application is in the background.

**Comment by d4rken** [comment]
Thanks, fixed it.

**Comment by GabrielMGitHub** [comment]
Could you forward me by email to test?

**Comment by d4rken** [comment]
It's part of v4.8.1.

**Comment by GabrielMGitHub** [comment]
I downloaded and tested, working perfectly. Thank you.
