### ISSUE TITLE
Implementing Functionality to Delete File .crdownload

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1154]
When you do file downloads on the internet using the Chrome browser it creates a temporary file in the Download folder called .crdownload, when finished downloading Chrome renames this file to the original name, however if the download does not end for some failure this file gets in the Downloads folder, until you manually delete it. You need to implement a System Cleanup function so that this file is deleted.
![screenshot_20170923-130256](https://user-images.githubusercontent.com/8754997/30774851-925d2566-a05f-11e7-9449-b06e329759f9.jpg)

**Comment by d4rken** [comment]
Confirmed. We could add this to Chrome in the AppCleaner.

**Comment by GabrielMGitHub** [comment]
SD_Maid-v4.8.1(40801)-RELEASE-7989c62.apk.part

**Comment by GabrielMGitHub** [comment]
I ended up closing the matter for my mistake, could you reopen?

**Comment by GabrielMGitHub** [comment]
I ended up closing the matter for my mistake, could you reopen?

**Comment by GabrielMGitHub** [comment]
I would request to include .part files from Firefox, but .part files are also used in torrent applications if putting a function to delete this file may end up excluding files being downloaded by the torrent application. So it would not be ideal to implement.

**Comment by d4rken** [comment]
> I would request to include .part files from Firefox, but .part files are also used in torrent applications if putting a function to delete this file may end up excluding files being downloaded by the torrent application. So it would not be ideal to implement.

Please create an extra ticket for this.

**Comment by SuperSandro2000** [comment]
@GabrielMGitHub they are also used in splitted zips so they shouldn't be deleted.

**Comment by GabrielMGitHub** [comment]
As I said you can not implement an exclude function for .part because it is used by other programs.

**Comment by d4rken** [comment]
Attributed `Download/*.crdownload` to `com.android.chrome` and the AppCleaner will them as part of the hidden caches filter.
