### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.scientificgames.jackpotparty.uuid (FP)

### ISSUE THREAD

**Issue by bobby11monahan** [d4rken/sdmaid-public#1156]
### Target
Target: `/storage/emulated/0/Android/data/com.scientificgames.jackpotparty.uuid`
Prefix-free: `com.scientificgames.jackpotparty.uuid`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Jackpot Party`
Packagename: `com.williamsinteractive.jackpotparty`
Version: `30.00 (69)`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `ZTE/P895T20_MPCS/urd:6.0.1/MMB29M/20170418.111425:user/release-keys`

### Comment
`I play all the time`

**Comment by bobby11monahan** [comment]
Yup

**Comment by d4rken** [comment]
It's a valid report as far as I see, no need to close this.
