### ISSUE TITLE
Video cache cleanup for FB Messenger

### ISSUE THREAD

**Issue by ErmanSayin** [d4rken/sdmaid-public#1159]
This is the same as #826, but for Facebook Messenger.
This folder contains hidden cache from Facebook Messenger:
`/data/data/com.facebook.orca/files/ExoPlayerCacheDir/`
101MB of cache for me.

**Comment by d4rken** [comment]
Could you do "Save directory structure" (Explorer option) on `/data/data/com.facebook.orca/files` and post the file here?

Should we strictly match `ExoPlayerCacheDir` or make it a bit fuzzy ala `*CacheDir`?

**Comment by ErmanSayin** [comment]
Here you go:

[pathdump#_data_data_com.facebook.orca_files#1506513549954.txt](https://github.com/d4rken/sdmaid-public/files/1336987/pathdump._data_data_com.facebook.orca_files.1506513549954.txt)

**Comment by d4rken** [comment]
Sorry this took so long to add.

Interestingly Instagram, also owned by facebook, places the `ExoPlayerCacheDir` correctly in `.../cache` 🤷‍♂️ A
