### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/.com.google.Chrome.AkO55y (FP)

### ISSUE THREAD

**Issue by Riptrip** [d4rken/sdmaid-public#1168]
### Target
Target: `/storage/emulated/0/Download/.com.google.Chrome.AkO55y`
Prefix-free: `Download/.com.google.Chrome.AkO55y`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Chrome`
Packagename: `com.android.chrome`
Version: `61.0.3163.98 (316309801)`

### Current owners
Appname: `Система Android`
Packagename: `android`
Version: `6.0-1488188848 (23)`

Appname: `Загрузки`
Packagename: `com.android.providers.downloads.ui`
Version: `6.0-1488188848 (23)`

Appname: `Диспетчер загрузки`
Packagename: `com.android.providers.downloads`
Version: `6.0-1488188848 (23)`

### SD Maid
Version: `4.8.3 (40803)`

### Device
Fingerprint: `Prestigio/PSP5530DUO/DW53B4G:6.0/MRA58K/1475908594:user/release-keys`

**Comment by d4rken** [comment]
What kind of file is this?

**Comment by Riptrip** [comment]
Pgp не сюда хотел
