### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1506761715968.log (FP)

### ISSUE THREAD

**Issue by zamiel2112** [d4rken/sdmaid-public#1170]
### Target
Target: `/storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1506761715968.log`
Prefix-free: `eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1506761715968.log`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `SD Maid`
Packagename: `eu.thedarken.sdm`
Version: `4.8.3 (40803)`

### SD Maid
Version: `4.8.3 (40803)`

### Device
Fingerprint: `lge/k6p_crk_us/k6p:6.0.1/MXB48T/171851624fb96:user/release-keys`

### Comment
`2fc921af-f5e1-478e-b45f-cbaf8191a409
LG X Power 6.0.1
not rooted
I don't know anything about computers or bugs but I know that my device is not working right so I need help.
often when I hit the back button when I'm in an app I get a message saying unfortunately app has stopped off to enable flash to rapidly Flash. also when I try to select something it will scroll away rapidly from my hand and sometimes when I choose something and I can't touch it for the first time nothing happens and then I have to get it a second time.
`

**Comment by d4rken** [comment]
This is not what clutter reports should be used for and SD Maid isn't general android support ☹️ .

**Comment by zamiel2112** [comment]
Sorry I just didn't know how else to do it.i am still having phone problems
please help.i am not tech savvy. Think of it as a challenge. Maybe?

Simon Alexander
