### ISSUE TITLE
SD Maid hangs "in queue" Forever

### ISSUE THREAD

**Issue by helakejr** [d4rken/sdmaid-public#1177]
SD Maid hangs on "rooted" devices. All commands, queue and hang forever.

OnePlus 5 rooted, 7.1.1, sd maid 4.7.6 Pro version (used to work before phone rooted)

**Comment by helakejr** [comment]
Problem was with SuperSU.....never granting su.

**Comment by d4rken** [comment]
Good to hear it's not a bug :).
