### ISSUE TITLE
Clutterreport: /storage/emulated/0/360

### ISSUE THREAD

**Issue by Jisu-Woniu** [d4rken/sdmaid-public#1179]
### Target
Target: `/storage/emulated/0/360`
Prefix-free: `360`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `360卫士极客版`
Packagename: `com.qihoo.antivirus`
Version: `2.4.0.1030 (30)`

Appname: `360手机助手`
Packagename: `com.qihoo.appstore`
Version: `7.1.9 (300070109)`

Appname: `360清理大师`
Packagename: `com.qihoo.cleandroid_cn`
Version: `6.0.0 (58)`

### Current owners
Appname: `?`
Packagename: `com.qihoo.yunpan`
Version: `null (0)`

Appname: `?`
Packagename: `com.qihoo.security.lite`
Version: `null (0)`

Appname: `?`
Packagename: `com.qihoo.security`
Version: `null (0)`

### SD Maid
Version: `4.8.3 (40803)`

### Device
Fingerprint: `xiaomi/mido/mido:6.0.1/MMB29M/V8.5.6.0.MCFCNED:user/release-keys`

**Comment by d4rken** [comment]
Added with regex match for `com.qihoo.*` and flagged as `COMMON`.
