### ISSUE TITLE
Overlapping statistics text

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1187]
From
> https://www.reddit.com/r/sdmaid/comments/73y02g/bug_overlappingdouble_text_for_percentage_in_stats/

Hm not easily fixable as the graph is drawn by a 3rd party library: https://github.com/PhilJay/MPAndroidChart

* https://github.com/PhilJay/MPAndroidChart/issues/1733
* https://github.com/PhilJay/MPAndroidChart/issues/1692
* https://github.com/PhilJay/MPAndroidChart/issues/535
* https://github.com/PhilJay/MPAndroidChart/issues/207

**Comment by oswaltalvaradolopez** [comment]
Oswaltalvarado33@gmail.com

**Comment by d4rken** [comment]
Rather cheap solution, we don't show any % labels < 5.
