### ISSUE TITLE
Clutterreport: /storage/emulated/0/Private (new)

### ISSUE THREAD

**Issue by dooleyhoop** [d4rken/sdmaid-public#1201]
### Target
Target: `/storage/emulated/0/Private`
Prefix-free: `Private`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Wi-Fi Direct share`
Packagename: `com.samsung.android.app.FileShareServer`
Version: `2.5 (19)`

Appname: `Wi-Fi Direct`
Packagename: `com.samsung.android.app.FileShareClient`
Version: `2.5 (19)`

Appname: `WallpaperPicker`
Packagename: `com.sec.android.app.wallpaperchooser`
Version: `3.0.16 (301600200)`

Appname: `My interests`
Packagename: `com.samsung.android.keyguardwallpaperupdator`
Version: `1.0.07 (100700100)`

Appname: `System UI`
Packagename: `com.android.systemui`
Version: `6.0.1 (23)`

Appname: `Sound detectors`
Packagename: `com.samsung.android.app.advsounddetector`
Version: `18.0.00-16 (1800016100)`

### Current owners
None

### SD Maid
Version: `4.7.6 (40706)`

### Device
Fingerprint: `samsung/trlteuc/trlteatt:6.0.1/MMB29M/N910AUCS2EQG1:user/release-keys`

**Comment by d4rken** [comment]
How do you know that these apps own that folder?
