### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.lonelycatgames.Xplore/cache/temp (FP)

### ISSUE THREAD

**Issue by nitwit1984** [d4rken/sdmaid-public#1236]
### Target
Target: `/storage/emulated/0/Android/data/com.lonelycatgames.Xplore/cache/temp`
Prefix-free: `com.lonelycatgames.Xplore/cache/temp`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Root Browser`
Packagename: `com.jrummyapps.rootbrowser.classic`
Version: `2.5.0.0 (25000)`

### Current owners
Appname: `X-plore`
Packagename: `com.lonelycatgames.Xplore`
Version: `3.97.03 (39703)`

### SD Maid
Version: `4.8.3 (40803)`

### Device
Fingerprint: `motorola/athene_f/athene_f:7.0/NPJS25.93-14-8/8:user/release-keys`

### Comment
`xplore cache`

**Comment by d4rken** [comment]
Root Browser isn't the owner
