### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/hack_android.apk (FP)

### ISSUE THREAD

**Issue by MLLHrMLLHr** [d4rken/sdmaid-public#1242]
### Target
Target: `/storage/emulated/0/Download/hack_android.apk`
Prefix-free: `Download/hack_android.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `6.0.1 (23)`

~~Appname: `?`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `null (0)`~~

Appname: `Download manager`
Packagename: `com.android.providers.downloads`
Version: `6.0.1 (23)`

### SD Maid
Version: `4.8.3 (40803)`

### Device
Fingerprint: `samsung/j1xlteuc/j1xlteatt:6.0.1/MMB29K/J120AUCS3AQE1:user/release-keys`

**Comment by Appinprover** [comment]
At path:'/storage/emulated/0' is deleting .apk files never a problem
