### ISSUE TITLE
Freeze icon

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1247]
By mail:

> When you select a frozen app, the top menu changes to select all and freeze icon.. The text for freeze icon, by select and hold, still freeze app: it should be unfreeze app.

**Comment by d4rken** [comment]
More complicated than I thought as we currently don't track the type of freeze action a task triggers, just that we invert the current state.

Maybe implement #36 which would require specific states for freeze tasks and then this.

**Comment by oswaltalvaradolopez** [comment]
#1276 # @d4rken 

- [ ] 

- 1.

**Comment by d4rken** [comment]
As good as it gets for now.
