### ISSUE TITLE
Adaptive Icons

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1249]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by d4rken** [comment]
https://medium.com/google-design/designing-adaptive-icons-515af294c783

**Comment by HAPPYSADPERSON** [comment]
I included 3 screenshots with the sdmaid icon.
First one is on the desktop, second one is in drawer, and third one is the icon reshaped using Nova Launcher's "Reshape legacy icons" setting.

https://imgur.com/a/JjB6k

**Comment by d4rken** [comment]
https://plus.google.com/u/0/b/116634499773478773276/+rodrigosowza/posts/5UTecpTCTVH
