### ISSUE TITLE
Clutterreport: /storage/0123-4567/Android/data/com.appgenix.bizcal (FP)

### ISSUE THREAD

**Issue by BlackPearl-sparrow** [d4rken/sdmaid-public#1250]
### Target
Target: `/storage/0123-4567/Android/data/com.appgenix.bizcal`
Prefix-free: `com.appgenix.bizcal`
Path-prefix: `/storage/0123-4567/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.8.3 (40803)`

### Device
Fingerprint: `samsung/trltedt/trlte:6.0.1/MMB29M/N910GDTS1DQH3:user/release-keys`

### Comment
`I can't figure out the owner of this data. But it came up as a corpse immediately after I uninstalled Samsung Side sync  : I found Side Sync was not useful for me and was a weak spot  for data breach from my phone. `

**Comment by d4rken** [comment]
The owner should be:
https://play.google.com/store/apps/details?id=com.appgenix.bizcal
