### ISSUE TITLE
Automatic cleanup of Empty folders 

### ISSUE THREAD

**Issue by daeks** [d4rken/sdmaid-public#1252]
Hi is there a way to automically clean the device from empty folders? If no, is it possible to add such a feature

**Comment by d4rken** [comment]
The system cleaner has a filter for empty directories.

See
https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner#filter

**Comment by daeks** [comment]
thank you very much - already searched for that option but didnt find it :)
