### ISSUE TITLE
Clutterreport: /storage/C706-0CF5/Android (FP)

### ISSUE THREAD

**Issue by ricardo172** [d4rken/sdmaid-public#1260]
### Target
Target: `/storage/C706-0CF5/Android`
Prefix-free: `Android`
Path-prefix: `/storage/C706-0CF5/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Sistema Android`~~
~~Packagename: `android`~~
~~Version: `7.1.1 (25)`~~

### SD Maid
Version: `4.3.8 (40308)`

### Device
Fingerprint: `motorola/nicklaus_f/nicklaus_f:7.1.1/NMA26.42-97/109:user/release-keys`

**Comment by d4rken** [comment]
Update SD Maid
