### ISSUE TITLE
Clutterreport: /storage/emulated/0/fuckView (new)

### ISSUE THREAD

**Issue by paulzzh** [d4rken/sdmaid-public#1262]
### Target
Target: `/storage/emulated/0/fuckView`
Prefix-free: `fuckView`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `去你大爷的内置浏览器`
Packagename: `com.xloger.exlink.app`
Version: `2.1.1 (16)`

### Current owners
None

### SD Maid
Version: `4.8.3 (40803)`

### Device
Fingerprint: `HUAWEI/NXT-TL00/HWNXT:7.0/HUAWEINXT-TL00/C01B589:user/release-keys`

### Comment
`A xposed module`

**Comment by d4rken** [comment]
I don't think this exposed module creates that folder, a quick google search didn't turn up anything.
