### ISSUE TITLE
SystemCleaner: Info. button hides under delete button

### ISSUE THREAD

**Issue by ya8sa** [d4rken/sdmaid-public#1278]
If 7 items are found by the system cleaner,  delete button of bottom right covers the info. button of the bottom item. So i can not see the detail of the files of last items.

**Comment by d4rken** [comment]
Can you post a screenshot?

**Comment by ya8sa** [comment]
![screenshot](https://user-images.githubusercontent.com/23994337/32128063-f691d024-bbb5-11e7-9dac-a74bfaca622c.png)

Please find the attached.
Delete button should be moved other area.

BTW, I do not know how I can upload any attachment by mobile phone.
This is uploaded by standard PC.
Thank you.
