### ISSUE TITLE
I've  paid for pro version 

### ISSUE THREAD

**Issue by BMF-INC** [d4rken/sdmaid-public#1280]
It's prompting me to buy again. Please resolve this issue. My email is ceargle88@gmail.com

**Comment by d4rken** [comment]
Your purchase is still valid, it's likely a Google Play syncronization issue.

See here for troubleshooting tips:
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#google-play-is-not-showing-the-purchase
