### ISSUE TITLE
Scan results from the UninstallWatcher are not consistently displayed

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1281]
If the UninstallWatcher triggers and finds results there is an inconsistence between the results displayed in the popup and the main app.

- [x] The QuickAccess entry can show a higher amount of corpses than the previous uninstall watcher results because the entry takes it's information from the scan progress information which are not filtered. The uninstall watcher filters out anything unrelated to the app uninstall that triggered the event.
- [x] Because the uninstall watcher scan triggers a different task than the default scan from the main UI, the worker still has `isNew=true` which causes the intro UI to show instead of the results.

**Comment by d4rken** [comment]
Best course of action is probably to remove the extra uninstallwatcher task and enhance the default scan task to take filter arguments, that way both events take the same route through the code and we prevent future issues like this.

**Comment by carlossnowden** [comment]
. What is this stuff is this my kitchen stuff forgot deleted
