### ISSUE TITLE
ctime instead of mtime

### ISSUE THREAD

**Issue by vojsat** [d4rken/sdmaid-public#1285]
SD Maid: 4.8.3 Pro Version
The documentation describes the "modification date/time" of the file. But I see the change time timestamp (ctime). Is this a bug or property?
See screenshots.

![sd_maid](https://user-images.githubusercontent.com/17676405/32169445-c9984e60-bd70-11e7-99cc-d54e9598cb6f.jpg)
![command_line](https://user-images.githubusercontent.com/17676405/32169457-d135870a-bd70-11e7-938c-f4b8c44a542e.jpg)

**Comment by d4rken** [comment]
The documentation is missleading, SD Maid is using `time of last status change, seconds since Epoch`, so `ctime`. I think switching to `mtime` might be a good idea though, from a users POV, `mtime` is usually more interesting than `ctime`.

**Comment by vojsat** [comment]
OK, thank you for quick response.

**Comment by d4rken** [comment]
Let's leave this open, currently think I'll make this change.
