### ISSUE TITLE
Clutterreport: /storage/emulated/0/Phone 2.0 (new)

### ISSUE THREAD

**Issue by lunim** [d4rken/sdmaid-public#1289]
### Target
Target: `/storage/emulated/0/Phone 2.0`
Prefix-free: `Phone 2.0`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `DIGITS`
Packagename: `com.tmobile.digits`
Version: `1.1.18 (1120011)`

### Current owners
None

### SD Maid
Version: `4.8.5 (40805)`

### Device
Fingerprint: `google/taimen/taimen:8.0.0/OPD1.170816.010/4311506:user/release-keys`

**Comment by d4rken** [comment]
Can you give me a link to the app?
What is inside the folder?

**Comment by lunim** [comment]
App: https://play.google.com/store/apps/details?id=com.tmobile.digits&hl=en

Contains database/temporary files, voicemails, etc.
