### ISSUE TITLE
Doubt - About Folder .aux

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1291]
I realized some time that the system has been creating a .aux name folder in several folders, in which is left of image residues like the thumbnails folder. I wonder if it can be deleted without damage to the system, if it can, can be implemented in SD Maid?

Device: Asus Zenfone 2 Laser
Android: 6.0.1

![screenshot_20171102-105525](https://user-images.githubusercontent.com/8754997/32327482-cca905aa-bfbd-11e7-82cd-91a71d55d841.jpg)
![screenshot_20171102-105509](https://user-images.githubusercontent.com/8754997/32327483-ccea8c82-bfbd-11e7-8251-25bc559d4602.jpg)

**Comment by d4rken** [comment]
Are the images exactly smaller versions of screenshots you took? Meaning are we sure these are thumbnails?

Do we know which app creates them?

**Comment by GabrielMGitHub** [comment]
@d4rken 

Yes, the original image is in Screenshots.
![screenshot_20171102-112930](https://user-images.githubusercontent.com/8754997/32328439-2311d720-bfc1-11e7-9444-beabc0ab4d44.jpg)

The copy is in .aux.
![screenshot_20171102-113009](https://user-images.githubusercontent.com/8754997/32328513-54a06cd4-bfc1-11e7-81a0-079931225529.jpg)

I noticed that the copy of the image that is in .aux has distortions in the image and low quality.

Original Folder Screenshots
![screenshot_20171102-113314](https://user-images.githubusercontent.com/8754997/32328670-d3768a16-bfc1-11e7-85ee-55a0d4f5b1e5.jpg)

Copyright Folder .aux
![screenshot_20171102-113331](https://user-images.githubusercontent.com/8754997/32328708-f6a925b6-bfc1-11e7-9ae3-ea8fc1ab4e70.jpg)

**Comment by GabrielMGitHub** [comment]
The .aux folder is created inside folders that contain images, whether in internal or external storage.

**Comment by GabrielMGitHub** [comment]
@d4rken I found out why this folder is created, when you edit an image, it saves a copy of the original in the .aux folder. Disregard this request, it is important to save the copy of the original.
