### ISSUE TITLE
Doubt - About Folder .facebook_cache, com.facebook.katana and com.facebook.orca

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1292]
I realized some time that the system has been creating a folder of name .facebook_cache, com.facebook.katana and com.facebook.orca. I wonder if it can be deleted without damage to the system, if it can, can be implemented in SD Maid?

Device: Asus Zenfone 2 Laser
Android: 6.0.1

![screenshot_20171102-111920](https://user-images.githubusercontent.com/8754997/32328056-d1411a9c-bfbf-11e7-8e3d-3e7f42ffbdcb.jpg)
![screenshot_20171102-111926](https://user-images.githubusercontent.com/8754997/32328062-d85646d6-bfbf-11e7-8f77-2d98f41530aa.jpg)
![screenshot_20171102-111929](https://user-images.githubusercontent.com/8754997/32328136-23577ff6-bfc0-11e7-8464-f7594b70f505.jpg)
![screenshot_20171102-111939](https://user-images.githubusercontent.com/8754997/32328138-2b557c1c-bfc0-11e7-88c6-9ff60dce1465.jpg)
![screenshot_20171102-111941](https://user-images.githubusercontent.com/8754997/32328148-339a335e-bfc0-11e7-87f7-9cccfe79d9c0.jpg)

**Comment by d4rken** [comment]
If you delete these folders and open the facebook apps again, are they recreated?

Is `.facebook_cache` created by both `orca` and `katana` or just one?

Are `com.facebook.orca` and `com.facebook.katana` the packagenames of your installed facebook apps( I think main + messenger)?

**Comment by GabrielMGitHub** [comment]
@d4rken When deleting folders, and open Facebook and Facebook Messeger, folders are not created immediately, so I realized when making use of the two applications, the folders are created. I believe they are cache and temporary files from Facebook and Messeger, but I can not say if they are really necessary.

**Comment by GabrielMGitHub** [comment]
@d4rken 

> É .facebook_cachecriado por ambos orcae / katanaou apenas um?
It's a separate folder. In the images at the top there is the path of each folder.

/sdcard/.facebook_cache

/sdcard/com.facebook.katana
/sdcard/com.facebook.katana/fb_temp

/sdcard/com.facebook.orca
/sdcard/com.facebook.orca/fb_temp

**Comment by GabrielMGitHub** [comment]
@d4rken 

> São com.facebook.orcae com.facebook.katanaas embalagens dos seus aplicativos instalados do Facebook (eu acho o principal + messenger)?

Yes Facebook and Messeger.

**Comment by d4rken** [comment]
I don't think these are strictly necessary and we can treat them like hidden cache. I'll add these to the hidden caches filter:

* `.facebook_cache`
* `com.facebook.katana/fb_temp`
* `com.facebook.orca/fb_temp`

I think we also need to add `.facebook_cache` to the clutter database.
Can you check in SD Maids Explorer if any are already recognized?

I'd like to know when exactly these are created, can you find that out?

**Comment by GabrielMGitHub** [comment]
@d4rken

Only the .facebook_cache folder is hidden.

**Comment by GabrielMGitHub** [comment]
@d4rken 

> Hidden meaning it has a "?" icon, and the others do not?

When the folder has a (.) In front of the name, it means that the folder is hidden, as it happens in Linux.

**Comment by d4rken** [comment]
SD Maid has no `.` == hidden feature, all file names are equal to SD Maid.

I'm referring to SD Maids file forensics. The right-side icon in the Explorer of SD Maid shows whether SD Maid knows which app owns a folder.

See:
https://github.com/d4rken/sdmaid-public/wiki/Explorer#known-owner

**Comment by GabrielMGitHub** [comment]
@d4rken 

> Can you check in SD Maids Explorer if any are already recognized?

Yes is displayed from File Explorer.

![screenshot_20171102-130856](https://user-images.githubusercontent.com/8754997/32333857-0cbfccde-bfd0-11e7-8554-5d0e5552a3bc.jpg)
![screenshot_20171102-130917](https://user-images.githubusercontent.com/8754997/32333873-1568eafa-bfd0-11e7-978f-90281d0b20f9.jpg)
![screenshot_20171102-130934](https://user-images.githubusercontent.com/8754997/32333896-2206cb06-bfd0-11e7-9c49-940e3a456760.jpg)

**Comment by d4rken** [comment]
Ok good, then I'll just need to code a few new hidden cache definitions. Thanks for the ticket.

**Comment by GabrielMGitHub** [comment]
@d4rken 
The (.) In name is to refer to Android itself that the folder is hidden. Example, if I open Asus File Manager I do not see the file, just enable the viewing of hidden files in settings. I just informed you that the .facebook_cache folder is a hidden folder, just like the thumbnails folder.

**Comment by GabrielMGitHub** [comment]
@d4rken 

> Eu não acho que estes são estritamente necessários e podemos tratá-los como cache escondido. Vou adicioná-los ao filtro cachês escondido:

.facebook_cache
com.facebook.katana/fb_temp
com.facebook.orca/fb_temp
Eu acho que também precisamos adicionar .facebook_cacheao banco de dados de destruição. 
Você pode verificar o SD Maids Explorer se algum deles já for reconhecido?

You should delete the top folders, there are no that are inside.

- facebook_cache
- com.facebook.katana
- com.facebook.orca

As said these folders are only created when they need to save temporary files and cache, I always delete the upper folders myself.

**Comment by d4rken** [comment]
The content of the three folders is covered by the AppCleaners hidden caches filter.
If they are empty, the system cleaner would delete the folders, even if installed, as it doesn't care about "apps".
If the apps are not installed, the CorpseFinder suggests them for deletion.
