### ISSUE TITLE
Find duplicate got file not found exception

### ISSUE THREAD

**Issue by rahmatfajar15** [d4rken/sdmaid-public#1294]
![](https://i.imgur.com/5IQplna.png)

Directory is 
`storage/emulated/0`

**Comment by d4rken** [comment]
Did you change the default search pathes of the Duplicates tool in the settings?

* Device?
* Android version?
* SD Maid version?

**Comment by rahmatfajar15** [comment]
I don't change it
Redmi 4 prime (markw)
6.0.1
4.8.3

I already try reinstall. But no luck.

**Comment by d4rken** [comment]
Hm looks like the sdcard didn't get correctly detected. Is your devices internal sdcard at `/storage/emulated/0`?

Can you record this error in a debuglog?

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by rahmatfajar15** [comment]
I found it.
There's a system file that I copy to my internal and the app can't read that file.
I delete it and it's working.

Thanks

**Comment by d4rken** [comment]
Care to give more details? How did you copy it? Was it a permission issue? What file was it?

**Comment by rahmatfajar15** [comment]
I use custom ROM. And sometimes when I restore from TWRP the password changes. So I need to remove the password. I got [this trick](https://forum.xda-developers.com/android/software-hacking/remove-lockscreen-recovery-t3530008). And for safety, I'm not removing it. Instead I move it to my internal. The `locksettings.db-shm` make the exception appear. It says that the app don't have access.
