### ISSUE TITLE
SAF permission setup does not propagate to child locations

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1296]
If we grant SD Maid SAF permission to the external sdcard, the correct SAF uri is only set to the Location object for the root of the sdcard (`Location.SDCARD`), but not sub locations of that (e.g. `Location.PUBLIC_DATA`).

SD Maid is not be able to use the permission for these sub location until restarted once.

**Comment by KSGUNNUTS** [comment]
child locations?

**Comment by d4rken** [comment]
@KSGUNNUTS What?

**Comment by d4rken** [comment]
Fixed by reloading SD Maids storage manager if the SAF setup step was necessary.
