### ISSUE TITLE
Cleaning up Media-Provider reference after deleting media files

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1309]
It should be possible to clean up Media-Provider references of duplicates that we deleted such that there are e.g. no stale gallery entries. We could add this as extra option, probably by default activated as this would help a lot of inexperienced users and stale gallery entries is something I would consider troublesome anyways.

This would also be viable to add as AppCleaner filter for the Media-Provider app though. We could iterate through all media references and delete those entries that we can't confirm to have an existing file.

**Comment by d4rken** [comment]
Not sure where this would be more appropriate. Theoretically stale references could be caused by any tool, not just the Duplicates tool, but the AppCleaner currently only works with `files` and what we are deleting now would be database entries from the Media-Provider. Then again we are "cleaning" a specific app which is the source of the issue so the AppCleaner seems to make sense.

Duplicates could get this as drop in option without much fuzz: internal routine during man deletion loop + setting to toggle this "feature".

AppCleaner would get this as extra "specific filter" and I'd have to change the AppCleaner results + details from displaying files to some kind of abstract class that could be a file but also something else (e.g. Media-Provider database entry). A lot of work, but makes it easier for future additions of this type.

**Comment by LOVETOHARD** [comment]
Please Help I Am Bugged For No Reason
