### ISSUE TITLE
False positive Corpse Finder

### ISSUE THREAD

**Issue by buffal0b1ll** [d4rken/sdmaid-public#1341]
data/user_de/0/magisk.db
Deleting it caused Magisk to loose root with Magisk 14.4+ on walleye.

**Comment by d4rken** [comment]
Can reproduce, thanks for the report.
Add an exclusion for now, I'll fix this with the next update.

**Comment by buffal0b1ll** [comment]
Awesome.  Thanks.

**Comment by Martinusbe** [comment]
see, Bill, Matthias is fast ;-)

**Comment by d4rken** [comment]
Commited for v4.8.7.

I'll aim to push this to beta with all the other definition updates this afternoon.

```patch
 }, {
   "pkgs": ["com.topjohnwu.magisk"],
-  "mrks": [{"loc": "SDCARD", "path": "MagiskManager"}]
+  "mrks": [
+       {"loc": "SDCARD", "path": "MagiskManager"},
+       {"loc": "PRIVATE_DATA", "path": "magisk.db"}
+  ]
 }, {
```

**Comment by buffal0b1ll** [comment]
Awesome.  Installed new beta and removed my exclusion.  No more false
positive on corpse finder magisk.db
Thank you!


--expect crazy typos--
