### ISSUE TITLE
Add System to AppControl filters before loading under correct circumstances

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1343]
"User" and "All" are options, why not add System under the right side bar if the user has Show system apps checked off under Appcontrol Settings, for the sake of consistency?

**Comment by mcl21014** [comment]
Meant to say checked on. Oops.

**Comment by d4rken** [comment]
Ah now I get it, hm yeah it doesn't show before loading...

Then again maybe we shouldn't show anything before loading?

**Comment by d4rken** [comment]
Filters are hidden until data is available.
