### ISSUE TITLE
Clutterreport: /data/user_de/0/magisk.db (FP)

### ISSUE THREAD

**Issue by BodenM** [d4rken/sdmaid-public#1345]
### Target
Target: `/data/user_de/0/magisk.db`
Prefix-free: `magisk.db`
Path-prefix: `/data/user_de/0/`
Type: `FILE`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Magisk Manager`
Packagename: `com.topjohnwu.magisk`
Version: `5.4.3 (64)`

### Current owners
None

### SD Maid
Version: `4.8.6 (40806)`

### Device
Fingerprint: `motorola/addison/addison:7.1.1/NPN26.118-22/5:user/release-keys`

**Comment by d4rken** [comment]
Fixed in v4.8.7, currently in beta.

#1341
