### ISSUE TITLE
Create SystemCleaner filter for .part files in /Downloads

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1347]
Partial downloads are accumulating in my Downloads folder, so why not add a filter to delete them? I would bet users often have these files lying around, so creating a filter for them would be practical.

**Comment by d4rken** [comment]
Was mentioned in #1154 too.

Seems .part is also used by parted zip files, seems dangerous to delete.

**Comment by d4rken** [comment]
".part" is too common of an extension to act on this.
