### ISSUE TITLE
Clutterreport: /storage/emulated/0/.thumbnails

### ISSUE THREAD

**Issue by Notyoursmine** [d4rken/sdmaid-public#1349]
### Target
Target: `/storage/emulated/0/.thumbnails`
Prefix-free: `.thumbnails`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.sec.android.app.videoplayer`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.8.6 (40806)`

### Device
Fingerprint: `ZTE/P675T07/P675T07:5.1/LMY47D/1470468601:user/release-keys`

**Comment by d4rken** [comment]
Hm?
Who do it belong to then?
