### ISSUE TITLE
Clutterreport: /persist (FP)

### ISSUE THREAD

**Issue by mopri** [d4rken/sdmaid-public#1351]
### Target
Target: `/persist`
Prefix-free: `/persist`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Android-systeem`
Packagename: `android`
Version: `5.1-1481766675 (22)`

### Current owners
None

### SD Maid
Version: `4.8.7 (40807)`

### Device
Fingerprint: `Lenovo/A1010a20/A1010a20:5.1/LMY47I/A1010a20_S253_161207.161215:user/release-keys`

**Comment by d4rken** [comment]
Reporting at this level is currently not supported.
