### ISSUE TITLE
v4.9.0 Root unavailable

### ISSUE THREAD

**Issue by KaMyKaSii** [d4rken/sdmaid-public#1352]
On v4.8.7 it was working perfectly, but on v4.9.0 I'm having this error. Sorry for not providing a logcat, but my logcat is only reporting about Wifi/RIL. Something that comes to your mind?
![screenshot_20171203-171958](https://user-images.githubusercontent.com/17092335/33528802-3c47e5f4-d84e-11e7-9f20-d4a08d3d5c2a.png)

**Comment by d4rken** [comment]
Can you record an upload a debug log of loading the overview screen?

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by KaMyKaSii** [comment]
@d4rken here
[sdmaid_logfile_1512337892620.log](https://github.com/d4rken/sdmaid-public/files/1525190/sdmaid_logfile_1512337892620.log)

**Comment by d4rken** [comment]
Thanks. If you remove SD Maid from the super user app, does the popup show that asks to grant/deny permission?

**Comment by KaMyKaSii** [comment]
Yes, normally. And just to inform, I'm using the latest version of suhide, but I have not selected to hide root of SDMaid or something like this

**Comment by d4rken** [comment]
It's a bug caused by the SD Maids root check not being correctly adapted to the new shell system I introduced in 4.9.0. I think I can fix it with the debug log you provided. Will get back to you if I need more.

Thanks for the report! Currently using Magisk so I didn't notice the behavior difference.

**Comment by KaMyKaSii** [comment]
I thank you for your kindness and great work. Good luck!

**Comment by d4rken** [comment]
@KaMyKaSii @noc-jfcbs

If you are up for it, could you send a quick mail to support@...? I'd like to give you a test version with a fix applied for this.

**Comment by noc-jfcbs** [comment]
Certainly. Going to arrive in a second.
