### ISSUE TITLE
v4.9.0-beta seems to not initialise

### ISSUE THREAD

**Issue by noc-jfcbs** [d4rken/sdmaid-public#1358]
Samsung Galaxy S3 LTE (GT-i9305)
Resurrection Remix-M-v5.7.4 with Chainfire's SuperSU v2.76 and rovo89's Official Xposed v88.2, GApps-free
Report related to v4.9.0-beta that was downloaded before you removed it from XDA (didn't find the time to test earlier to report); otherwise using v4.8.7 that is working fantastically.
Install-ID: 3369df7b-096e-4e3f-9686-3cded00a2173 (Attention: ID was taken from v4.8.7 as I couldn't go thus far with the concerned beta).

Installed v4.9.0-beta over the currently running v4.8.7. During the initial start of v4.9.0 after installation, I granted the SuperSU root access request for v4.9.0
Afterwards, v4.9.0 simply idled in queues whatever I selected (see screenshots). Unable to exit the app. Had to forcefully close SD Maid.
Logcat attached, which was taken throughout the above described procedure.
Issue is reproducable i.e. happens all the time.

Please advise if more information or additional logs are required.
[2017-12-05-12-07-36.txt](https://github.com/d4rken/sdmaid-public/files/1531067/2017-12-05-12-07-36.txt)
![screenshot_20171205-120813](https://user-images.githubusercontent.com/21972717/33606901-66d19a3c-d9bf-11e7-915d-37dcfbe68503.png)
![screenshot_20171205-120829](https://user-images.githubusercontent.com/21972717/33606904-6a2b3b02-d9bf-11e7-90bc-f3cef1c5f32f.png)
![screenshot_20171205-120843](https://user-images.githubusercontent.com/21972717/33606913-6dba8354-d9bf-11e7-894b-564532f4cb26.png)

**Comment by d4rken** [comment]
Thanks for the logs.

Dup of #1352
