### ISSUE TITLE
System Cleaner Calculating Erroneously

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1360]
System Cleaner calculating folder sizes and files erroneously

![screenshot_20171207-143904](https://user-images.githubusercontent.com/8754997/33726747-0d8aef2e-db5d-11e7-9080-6e4c18f55dc3.jpg)
![screenshot_20171207-143929](https://user-images.githubusercontent.com/8754997/33726745-0d5657e6-db5d-11e7-9988-f2921c389e62.jpg)
![screenshot_20171207-144805](https://user-images.githubusercontent.com/8754997/33726954-b81de694-db5d-11e7-84fb-9a2320df0589.jpg)
![screenshot_20171207-144809](https://user-images.githubusercontent.com/8754997/33726964-c1262440-db5d-11e7-909b-b78cd627eb2c.jpg)

**Comment by d4rken** [comment]
Neither app is calculating the size wrong.

The sizes are different because it's a [sparse-file](https://en.wikipedia.org/wiki/Sparse_file).

SD Maids screenshot shows "file size on storage", meaning the size in blocks occupied in the filesystem. This is relevant to your "free space" on the device.

Your other screenshot shows the "file size", meaning the size, the file itself says it is. This is relevant if you send this file over network, or move it to a storage that doesn't support sparse-files.

If you look at the file in SD Maids explorer, then you will see both sizes displayed.

**Comment by GabrielMGitHub** [comment]
In the first image the SD Maid shows 16 KB in the thumbnail file, in the second image it shows that this same file has 234.10 MB.

**Comment by GabrielMGitHub** [comment]
So what you saying that SD Maid shows the size of the block and not the space used.

This would not be a mistake since the user would not imagine that the thumbnails are only occupying 64 KB, but that in reality is 234.10 MB. I'm not very happy about that.

**Comment by GabrielMGitHub** [comment]
The system cleaner shows that I only have 1.5 to be cleaned, but in reality I have over 234.10 MB to clean, because SD Maid is calculating the size of the block and not the total space used.

![screenshot_20171207-150932](https://user-images.githubusercontent.com/8754997/33728265-0564fe80-db61-11e7-85f9-860091015618.jpg)
![screenshot_20171207-150940](https://user-images.githubusercontent.com/8754997/33728275-0e7cb062-db61-11e7-871b-8e9250a3324e.jpg)

**Comment by d4rken** [comment]
> So what you saying that SD Maid shows the size of the block and not the space used.

`BlockCount * BlockSize == Space Used` and this is not equal to file size/length for sparse-files.

> This would not be a mistake since the user would not imagine that the thumbnails are only occupying 64 KB, but that in reality is 234.10 MB. I'm not very happy about that.

In reality it's only occupying 64KB. It would be missleading to tell the user we can free `234MB`. This is also a reason why other cleaners seem to "clean more", it would obviously _look_ better to display larger numbers. SD Maid actually only changed this about a year ago.

> The system cleaner shows that I only have 1.5 to be cleaned, but in reality I have over 234.10 MB to clean, because SD Maid is calculating the size of the block and not the total space used.

No. SD Maid shows the "total space used", the other app shows "file length". The file does not occupy `234.10MB` on your device. If you delete the file, you don't get 234.10MB of additional space, you get `BlockCount * BlockSize` which is the `64Kb`.

The only thing interesting here is why the Explorer shows `64Kb` and SystemCleaner `16Kb`, it should be the same size, or is it not the same file?

**Comment by GabrielMGitHub** [comment]
Now I understand, it works as a file that reserves this space, as Linux does with Swap file and Windows does with the Virtual Memory File. I'm closing this topic as resolved.
