### ISSUE TITLE
Manual Deletion

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1361]
When you click the exclamation point and do the manual cleanup, when you return to the previous screen, the items you just deleted continue to be displayed, as if it had not been deleted, and is shown until you click refresh.

This occurs with System Cleanup and Application Cleanup.

![20171207_152158](https://user-images.githubusercontent.com/8754997/33729605-53a72e2a-db65-11e7-9462-f08ef9cde8f5.gif)

![20171207_152242](https://user-images.githubusercontent.com/8754997/33729599-5319d2a0-db65-11e7-8f15-8fd60999d688.gif)

**Comment by d4rken** [comment]
Awesome report with the GIFs. Very easy to understand the issue 👍

**Comment by GabrielMGitHub** [comment]
Yes very useful, I used Du Recorder ;>)

**Comment by d4rken** [comment]
Interesting, didn't spot it early because this only happens if there is just 1 entry.

**Comment by d4rken** [comment]
Also happens in the CorpseFinder

**Comment by d4rken** [comment]
Should be fixed with 4.9.1, good catch! 👍

**Comment by GabrielMGitHub** [comment]
When you automatically clean, the end result is shown like this:
![screenshot_20171215-175147](https://user-images.githubusercontent.com/8754997/34058325-c1cf49d4-e1c1-11e7-9561-f9e615e7d021.jpg)

Because when cleaning manually and shown like this (0,00 B | 0 ITEM:
![screenshot_20171215-175348_1](https://user-images.githubusercontent.com/8754997/34058378-f986a408-e1c1-11e7-9fbe-d25dc3f0d880.jpg)
![screenshot_20171215-175348](https://user-images.githubusercontent.com/8754997/34058399-082f587e-e1c2-11e7-817b-fb9b33152803.jpg)

**Comment by GabrielMGitHub** [comment]
Application Cleanup displays the same error:
![screenshot_20171215-185505](https://user-images.githubusercontent.com/8754997/34060142-869cca50-e1c9-11e7-8f73-e5a78d0a9113.jpg)

**Comment by d4rken** [comment]
Fixed it "again", good eye. 😁 

If you would like to test it, send me a short mail and I'll give you a test version.
