### ISSUE TITLE
Cannot Save Minimum Age

### ISSUE THREAD

**Issue by danielearrighi** [d4rken/sdmaid-public#1363]
Hello, I'm trying to create a filter to delete images OLDER than 1 year (in my whatsapp folder). To achieve this, I understand I need to create a system cleaner filter for the path with *minimum age* set to a lot of milliseconds (wouldn't a datetime picker be better?) but when I save the filter the value for minimum age is not getting saved. 

![youcut_20171208_083027027 1](https://user-images.githubusercontent.com/14169741/33755992-a8736246-dbf3-11e7-88aa-97e83b54201b.gif)
Thanks for your help

**Comment by d4rken** [comment]
Thanks for the ticket.

Is this SD Maid v4.8.7?

**Comment by d4rken** [comment]
> (wouldn't a datetime picker be better?)

Really depends on the usecase. A date picker doesn't easily allow to input small time deltas, like <1min. A "date picker" also wouldn't be suitable as we are not picking a date, but a time difference. But I agree that a graphical selection (with optional manual entry) would be nice to have. Always something to improve 😁 , maybe sometime in 2018 😉 .

**Comment by danielearrighi** [comment]
Hello, thanks for your reply. Yes this is SdMaid 4.8.7(40807). 
Can you confirm that, to delete files older than 1 year,  I have to set the minimum age?  As for the picker, you could leave the text input and add a picker button that simply translates the picked date in milliseconds 😬👍
