### ISSUE TITLE
Clearing the System Exception Bug

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#1366]
If you set an exception, when clearing the system, the value "4" (depends on how many exceptions there are, in this case there is only 4) is shown below the word FILTERING, as if it had found something, then disappears, when there is no exception configured, this error does not occur.

Except:
![20171208_164207](https://user-images.githubusercontent.com/8754997/33780175-06837fb8-dc37-11e7-9b97-9dad1d5bdb66.gif)

No exception:
![20171208_162228](https://user-images.githubusercontent.com/8754997/33780185-0ff2768a-dc37-11e7-8096-eb871be89239.gif)

**Comment by GabrielMGitHub** [comment]
A part of the bug was dealt with in issues 1290.

**Comment by d4rken** [comment]
Yeah looks like the progress messages still have the bug from #1290

**Comment by d4rken** [comment]
The 4 exclusions are for files that exist, right?

**Comment by GabrielMGitHub** [comment]
They were created for the test.

**Comment by GabrielMGitHub** [comment]
If you delete the files or folders the error does not appear even though they are still set to Exceptions.

**Comment by Mike8669** [comment]
--
Sent from Outlook Email App for Android Friday, 08 December 2017, 10:56AM -08:00 from Matthias Urhahn  notifications@github.com :

**Comment by Mike8669** [comment]
--
Sent from Outlook Email App for Android Friday, 08 December 2017, 10:53AM -08:00 from GabrielMGitHub  notifications@github.com :

**Comment by d4rken** [comment]
This isn't easily fixable because exclusions are only applied after the scan finishes.

The options are
* Remove the progress info on "found items" during the scan
* Or move the exclusions routine to the filtering routine, which is inefficient and would slow down the SystemCleaner.

What to do...

**Comment by GabrielMGitHub** [comment]
> Isso não é facilmente corrigível porque as exclusões só são aplicadas após a conclusão da verificação.
> 
> As opções são
> 
> Remova as informações de progresso em "itens encontrados" durante a verificação
> Ou mova a rotina de exclusão para a rotina de filtragem, o que é ineficiente e diminui o SystemCleaner.
> O que fazer...

The two options are not viable solutions.

**Comment by GabrielMGitHub** [comment]
I believe that all files located first should be compared to Exceptions. One comparison for each item you find.

According to the pseudo code below:

char searchcleaner [500];
char exceptions [500];
int count=0;
If (exceptions=!searchcleaner){
      count=count+1
      ‎}
else (exceptions==searchcleaner){
      count=count+0
      }

**Comment by d4rken** [comment]
For performance reasons this is not desirable.

If we match exclusions while scanning we may slow down the whole operations, generally we should try to let the I/O controller be the bottleneck.

Furthermore many exclusion comparisons may become superfluos if we apply them later.

e.g. Exclusion for `/test`
While scanning
`/test` <- match and exclude
`/test/A` <- match and exclude
`/test/B` <- match and exclude

Applying this after scanning would only require matching the exclusion one time as we would remove the nested folders in one go.
