### ISSUE TITLE
Strange job-canceling logic

### ISSUE THREAD

**Issue by Vankog** [d4rken/sdmaid-public#1369]
When running e. g. the System Cleaner scanner and aborting it via the top-right X, there are two things that are strange:
1. It does not cancel the scan in a reasonable time, but keeps on scanning (probably till the current location is done), which can take several minutes (!) on removable storage.   
Expectation: Cancel the job in a reasonable time frame, maybe about 5 seconds or so.
1. Even though there were already some found items during the scan so far, the result view shows 0 items after the abort finally happens. 
Expectation: If the progress status already told me about some found items, these should be available for further action, even after an abort of the scan.

v. 4.8.7

 :-)

**Comment by d4rken** [comment]
> It does not cancel the scan in a reasonable time, but keeps on scanning (probably till the current location is done), which can take several minutes (!) on removable storage.
Expectation: Cancel the job in a reasonable time frame, maybe about 5 seconds or so.

The actual search is canceled relatively quickly. But there are still many callbacks for found files in the pipeline, canceling directly is not easy as there is no place to add a  `isCanceled` check in the callback chain. But I'm currently not sure if they would even help, if the callbacks are backedup even before I could add the results to a queue, then an extra cancel flag after that won't really matter.

The basic canceling behavior should improve in the next update though, the [new shell system](https://github.com/d4rken/rxshell) has better canceling logic and a nice callback chain.

> Even though there were already some found items during the scan so far, the result view shows 0 items after the abort finally happens.
Expectation: If the progress status already told me about some found items, these should be available for further action, even after an abort of the scan.

Canceling is destructive, we try to exit as fast as possible. Displaying results despite canceling would be counter intuitive, then we also would have to show whether the results are "completed" or from a "canceled" search.

There are also several routines other routines that still have to execute after the file search is done. So we would have to cancel the search, then still run the following routines, but then it's not really canceling, and how would we cancel the following routines if we already canceled 😉 .

**Comment by Vankog** [comment]
Another issue: In AppControl, the cancelation of the scan just triggers a new scan right away.



> Canceling is destructive, we try to exit as fast as possible. Displaying results despite canceling would be counter intuitive, then we also would have to show whether the results are "completed" or from a "canceled" search. 
> 
> There are also several routines other routines that still have to execute after the file search is done. So we would have to cancel the search, then still run the following routines, but then it's not really canceling, and how would we cancel the following routines if we already canceled 😉 .

Not so counter-intuitive for me. I often rescan due to the recursive empty dir problem. However, I see during the scan that there are already some results found that are most likely the empty dirs I was looking for. I therefore abort, because it really takes ages to scan just for this minor task and expect to be able to delete the found dirs. I was bummed to be disappointed at this time. ^^

**Comment by d4rken** [comment]
>Another issue: In AppControl, the cancelation of the scan just triggers a new scan right away.

Likely #784 because canceling the scan calls the UI update routine again.

> because it really takes ages to scan

New shell system will make scanning 20-50% faster.

If your questions are answered, please close the ticket.
