### ISSUE TITLE
Folder and file sorting

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#1370]
Sorting Folders first then the files because It is hard to find files in many folders in File Explorer.
For example like this
![screenshot_2017-12-09-23-07-02](https://user-images.githubusercontent.com/26460124/33796748-d34da4fc-dd35-11e7-93ee-d7684f12803e.png)

**Comment by ya8sa** [comment]
Please select Windows mode in the Settings - Explorer - Sort mode. That shows folders first.

**Comment by Edfgdz** [comment]
@ya8sa thanks
