### ISSUE TITLE
Clutterreport: /storage/emulated/legacy (FP)

### ISSUE THREAD

**Issue by asiacross** [d4rken/sdmaid-public#1375]
### Target
Target: `/storage/emulated/legacy`
Prefix-free: `/storage/emulated/legacy`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `System UI`
Packagename: `com.android.systemui`
Version: `4.4.2-eng.buildteam.20150818.132655 (19)`

Appname: `Smith`
Packagename: `com.android.smith`
Version: `4.25-plat_4.4.2-KOT49H (425990)`

Appname: `Shell`
Packagename: `com.android.shell`
Version: `4.4.2-eng.buildteam.20150818.132655 (19)`

### Current owners
None

### SD Maid
Version: `4.8.7 (40807)`

### Device
Fingerprint: `htc/sprint_wwe_vm/htc_a11chl:4.4.2/KOT49H/373881.3:user/release-keys`

**Comment by d4rken** [comment]
Reports for this location are not supported.
