### ISSUE TITLE
Clutterreport: /storage/emulated/0/Music (FP)

### ISSUE THREAD

**Issue by rolang1980** [d4rken/sdmaid-public#1379]
### Target
Target: `/storage/emulated/0/Music`
Prefix-free: `Music`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `VLC`
Packagename: `org.videolan.vlc`
Version: `2.5.12 (12051207)`

### Current owners
Appname: `Android-System`
Packagename: `android`
Version: `7.0 (24)`

### SD Maid
Version: `4.8.7 (40807)`

### Device
Fingerprint: `samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU1DQD9:user/release-keys`

**Comment by d4rken** [comment]
Is this really a folder of VLC in the sense that on an empty sdcard, VLC creates this folder?

**Comment by buocnhay** [comment]
samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU1DQD9:user/release-keys
