### ISSUE TITLE
Copy multiple files paths

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#1381]
Want add a function that i can copy multiple files(folders) specific location in Explorer to show somebody else.
When i select serveral files and copy their paths,it can creat a new txt file like[Save directory structure] recording their paths in file system.

**Comment by d4rken** [comment]
I've  added that copy/move in the explorer will copy their paths to the system clipboard. The files don't have to be pasted, just the copy or move action has to be used.

**Comment by d4rken** [comment]
The "save directory structure" task will now also print all selected item results into the same file, instead of creating multiple.

**Comment by d4rken** [comment]
(Also found a bug, path dump should now work on files too.
