### ISSUE TITLE
SystemCleaner last item problem

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#1384]
It is strange that it is difficult to touch bottom filter mark in SystemCleaner.
At first touch, everthing is good,but after that things get wrong.It only happen on last item.
Btw,i dont know Corpsefinder,but Appcleaner and Duplicates have same problem.
Details have been sent to you in email.

**Comment by d4rken** [comment]
![svid_20171216_000548](https://user-images.githubusercontent.com/1439229/34059855-2b2a085a-e1e1-11e7-9dc1-bd599e6afe7e.gif)
![svid_20171216_611](https://user-images.githubusercontent.com/1439229/34059857-2c50e758-e1e1-11e7-9ae4-ff57f4d786f3.gif)
