### ISSUE TITLE
shortcut in explorer

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#1385]
It is easy to delete shorcut labels accidentally in Explorer.Suggest it changed to left swiping to delete labels by user.

**Comment by d4rken** [comment]
Mixing swipe movements is confusing as the bookmark drawer already reacts to swipes, I've added a confirmation dialog instead.

**Comment by Edfgdz** [comment]
Can it change to long press to delete bookmarks like user filter deletion in System Cleaner?
With this method,user can delete more bookmarks each time.

**Comment by d4rken** [comment]
It can but how often is that necessary? Seems like a lot of work for an already crowded UI in that area that will rarely be used, though I have to admit I dont have stats on how often it is used...
