### ISSUE TITLE
Clutterreport: /storage/B0BB-1DF2/emulated (new)

### ISSUE THREAD

**Issue by TheMadScientist777** [d4rken/sdmaid-public#1433]
### Target
Target: `/storage/B0BB-1DF2/emulated`
Prefix-free: `emulated`
Path-prefix: `/storage/B0BB-1DF2/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Ultra Explorer Pro`
Packagename: `com.ksharkapps.filebrowser`
Version: `1.2.8 (17)`

### Current owners
None

### SD Maid
Version: `4.9.4 (40904)`

### Device
Fingerprint: `samsung/j3popeltemtr/j3popeltemtr:7.0/NRD90M/J327T1UVU1AQK6:user/release-keys`

**Comment by d4rken** [comment]
What's the purpose of this folder?
