### ISSUE TITLE
Feature request: Evercookies/Zombie Cookies deletion

### ISSUE THREAD

**Issue by adalvigi** [d4rken/sdmaid-public#1434]
There is currently no real way, on Android, to get rid of [evercookies](https://en.wikipedia.org/wiki/Evercookie) or [zombie cookies](https://en.wikipedia.org/wiki/Zombie_cookie) like with CCleaner on PC. The only good cleaner app on Android, and best candidate to achieve this, is probably SD Maid, and I hope we'll manage to find a way to do this, as it would be a significant privacy and security improvement for Android users.

**Comment by d4rken** [comment]
Seems to be within SD Maids scope,

Which of SD Maids tools do you think should do this? How would we detect the files to delete?

**Comment by d4rken** [comment]
I just remembered, there was some discussion about this here, about a year ago:

https://www.reddit.com/r/androidapps/comments/5l0ab0/does_sd_maid_remove_evercookies/

The user sadly didn't follow up and I forgot about it.

**Comment by adalvigi** [comment]
I think it could be in the "AppCleaner" scope. I'm no Android developer sadly, but I know that it's important to delete simultaneously all instances of the evercookie from all browsers (which on android could be more annoying since a lot of apps like Twitter or Facebook have integrated browsers), and also Bleachbit claims to be able to delete them (even though there are few infos on that, last news are [an update from 2010](https://www.bleachbit.org/news/bleachbit-081-evercookie) and some forum posts), being open source it could be a starting point to find a way to delete them in SD Maid.

**Comment by d4rken** [comment]
Stale
