### ISSUE TITLE
SDMaid is probably deleting .stfolder files from Syncthing

### ISSUE THREAD

**Issue by kepi** [d4rken/sdmaid-public#1435]
Syncthing stopped working for couple of my directories because `.stfolder` files, which are marking Syncthing synchronized folders, vanished.

I'm not 100 % sure SD Maid is to blame but I didn't run anything else which should be able to do this. And I launched SD Maid just yesterday after couple months, probably first time after I started to use Syncthing.

If it is the case and SD Maid is deleting `.stfolder` files, it shouldn't :)

**Comment by d4rken** [comment]
Are the .stfolders listed in SD Maids history?

The only thing I can think off would be empty directory deletion, are they empty?

**Comment by kepi** [comment]
Not sure, where I find history? Looks like it is in statistics part, but I don't have Pro.

Anyway, I dig little more and found out that `.stfolder` is supposed to be directory and it is empty by default indeed, see https://docs.syncthing.net/users/config.html section `markerName`

What is weird is that not all `.stfolder` directories were deleted, like one in `DCIM/.stfolder` remains in place and is not offered for deletion. Ones I recreated are again offered for deletion so that was right guess.

**Comment by d4rken** [comment]
The empty dirs filter excludes some folders like `DCIM` that will likely change soon though.

We could exclude the `.stfolder` from the empty dirs filter while the app is installed.
What do you think?

I'm also wondering if we should creating a matching pair for ".stfolder" for the corpsefinder?

**Comment by kepi** [comment]
I think excluding from the empty dirs would be great.

Not sure about corpsefinder as I don't know what is his job exactly. If it will delete empty hidden files, than it can be problem as `.stfolder` can apparantly be both directory or file.

**Comment by d4rken** [comment]
> Not sure about corpsefinder as I don't know what is his job exactly. 

Find files that belong to uninstalled apps and recommend them for deletion.

https://github.com/d4rken/sdmaid-public/wiki/CorpseFinder

**Comment by d4rken** [comment]
Should the CorpseFinder recommend all `.stdfolder`'s for deletion if the syncthing app is not installed?

**Comment by kepi** [comment]
I'm not 100 % sure. Seams like good idea, but I'm not sure if there can't be more implementations than official app as SyncThing is open, but in most use cases it would be probably ok.

It may be best to ask directly someone from SyncThing as I'm only user without more deep knowledge.

**Comment by wright-p** [comment]
I just ran into this today, looking at the play store it looks like the only android app there that uses the `.stfolder` folders is the official syncthing app `com.nutomic.syncthingandroid` . I also looked at F-Droid, and that seems to be the only syncthing app on there as well. Thanks for keeping SDMaid updated!
