### ISSUE TITLE
Clutterreport: /storage/emulated/0/MoneyManager

### ISSUE THREAD

**Issue by RitchieW1121** [d4rken/sdmaid-public#1437]
### Target
Target: `/storage/emulated/0/MoneyManager`
Prefix-free: `MoneyManager`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Spendee`
Packagename: `com.cleevio.spendee`
Version: `3.6.0 (3600)`

### Current owners
Appname: `?`
Packagename: `com.realbyteapps.moneya`
Version: `null (0)`

Appname: `?`
Packagename: `com.realbyteapps.moneymanagerfree`
Version: `null (0)`

### SD Maid
Version: `4.9.4 (40904)`

### Device
Fingerprint: `motorola/cm_shamu_t/shamu_t:6.0.1/MOB30R/93ee9b2ba3:userdebug/test-keys`

**Comment by d4rken** [comment]
Can't confirm this, got anymore info on this?

**Comment by RitchieW1121** [comment]
Sorry, I made a mistake and should belong to Money Manager Expense & Budget instead of Spendee.

**Comment by d4rken** [comment]
So the current owners are correct?

**Comment by RitchieW1121** [comment]
Current owners
Appname: Money Manager
Packagename: com.realbyteapps.moneymanagerfree
Version: 3.7.5.3 FO

**Comment by d4rken** [comment]
Ok those are the ones already linked.

So we can close this, right?
