### ISSUE TITLE
Clutterreport: /firmware (FP)

### ISSUE THREAD

**Issue by sd4dummies101helpme** [d4rken/sdmaid-public#1440]
### Target
Target: `/firmware`
Prefix-free: `/firmware`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `LG GNSS 2.1`
Packagename: `com.lge.gnsspostest`
Version: `2.0 (2)`

Appname: `LG Account`
Packagename: `com.lge.lgaccount`
Version: `3.8.45 (308045)`

Appname: `Android System`
Packagename: `android`
Version: `7.0 (24)`

Appname: `com.android.frameworks.telresources`
Packagename: `com.android.frameworks.telresources`
Version: `7.0 (24)`

### Current owners
None

### SD Maid
Version: `4.9.4 (40904)`

### Device
Fingerprint: `MetroPCS/lv3_mpcs_us/lv3:7.0/NRD90U/17318120287ad:user/release-keys`

**Comment by sd4dummies101helpme** [comment]
I swear someone else is making changes and or controlling my phone

**Comment by d4rken** [comment]
Please don't use this feature if you don't know what you are doing.
