### ISSUE TITLE
Clutterreport: /storage/emulated/0/.SignatureCreator/.iSwiftSignatureCreatorSignature_2017-12-24_23-54-01.2.png (new)

### ISSUE THREAD

**Issue by rsh1977** [d4rken/sdmaid-public#1451]
### Target
Target: `/storage/emulated/0/.SignatureCreator/.iSwiftSignatureCreatorSignature_2017-12-24_23-54-01.2.png`
Prefix-free: `.SignatureCreator/.iSwiftSignatureCreatorSignature_2017-12-24_23-54-01.2.png`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Adobe Acrobat`
Packagename: `com.adobe.reader`
Version: `17.5.180092 (180092)`

Appname: `Adobe Fill & Sign`
Packagename: `com.adobe.fas`
Version: `1.3.0 (13002491)`

### Current owners
None

### SD Maid
Version: `4.9.4 (40904)`

### Device
Fingerprint: `ZTE/P895T20_MPCS/urd:6.0.1/MMB29M/20170802.130758:user/release-keys`

**Comment by d4rken** [comment]
What kind of data is in the folder?
Are you sure it belongs to Adobe?

**Comment by 21101969sanjay** [comment]
Not specified

**Comment by d4rken** [comment]
Lacks info, can't reproduce.
