### ISSUE TITLE
Clutterreport: /storage/emulated/0/fb.video.downloader (new)

### ISSUE THREAD

**Issue by kronos78** [d4rken/sdmaid-public#1464]
### Target
Target: `/storage/emulated/0/fb.video.downloader`
Prefix-free: `fb.video.downloader`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Facebook`
Packagename: `com.facebook.katana`
Version: `154.0.0.33.385 (87107448)`

### Current owners
None

### SD Maid
Version: `4.9.1 (40901)`

### Device
Fingerprint: `xiaomi/tissot/tissot_sprout:8.0.0/OPR1.170623.026/7.12.29:user/release-keys`

**Comment by d4rken** [comment]
This does not belong to the official Facebook app.
