### ISSUE TITLE
Clutterreport: /storage/emulated/0/.face (FP)

### ISSUE THREAD

**Issue by dianalynn1** [d4rken/sdmaid-public#1469]
### Target
Target: `/storage/emulated/0/.face`
Prefix-free: `.face`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.android.gallery3d`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `com.google.android.gallery3d`
Version: `null (0)`

Appname: `Gallery`
Packagename: `com.sec.android.gallery3d`
Version: `5.1.19 (511903000)`

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `samsung/j7popltespr/j7popltespr:7.0/NRD90M/J727PVPU3AQJ3:user/release-keys`

**Comment by d4rken** [comment]
Why is this match a false positive?
