### ISSUE TITLE
Amazon Fire 7" 5th incorrect Android version

### ISSUE THREAD

**Issue by maggymayandme** [d4rken/sdmaid-public#1475]
Reports my system as 5.0 where as I am running 5.1 updated to 5.6 on amazon fire 7" 5th gen. Also unable to root. I do not have a PC. Tried KingRoot didn't work. Went to rootjunky and they had same root program for fire. I'm stumped.

**Comment by d4rken** [comment]
I don't understand the purpose of this ticket, what do you want?

**Comment by maggymayandme** [comment]
SD maid says I am running android 5.0, my system says I am running 5.1.  Why the discrepancy?  How do I find a root that will work for my tablet? I want out of Amazon completely and use Android.

**Comment by d4rken** [comment]
SD Maid gets the version number from the system itself, see:
https://developer.android.com/reference/android/os/Build.VERSION.html

Can you post a screenshot of what SD Maid shows or a debug log?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

I'm not familiar with root methods for the fire devices, check here though:
https://forum.xda-developers.com/amazon-fire/general/index-amazon-fire-2015-t3210485

**Comment by maggymayandme** [comment]
On this tablet I don't know how to do screenshots. This is not an easy tablet to figure out. Took much amazon control. Also on SD maid, duplicate search stops at 65%. What do I need to do?

**Comment by d4rken** [comment]
> Also on SD maid, duplicate search stops at 65%. What do I need to do?

I have never really seen a case of SD Maid really hanging during this operation. Likely SD Maid is still working, albeit slowly, which maybe due to a faulty sdcard.
