### ISSUE TITLE
Basepath in filter

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#1476]
When i put new basepath into filter,it is in the bottom as expected,after into this filter again,its location changed.
Just want pathes append to the end.
![1516941712478](https://user-images.githubusercontent.com/26460124/35470064-26e1f452-037d-11e8-985a-2496528ca904.jpg)

![1516941715196](https://user-images.githubusercontent.com/26460124/35470058-04b5ad60-037d-11e8-9e1a-cb03e2a647af.jpg)

**Comment by d4rken** [comment]
Fixed order for other lists (exclusions, names etc.) too.
