### ISSUE TITLE
Userfilter sort

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#1477]
Wish the new created filter can be put on top of filters list automatically.So that dont need to scroll down to open filter.
It is also good that this happen on edited filters.

**Comment by Edfgdz** [comment]
I have a new idea for this issue.

When user finish filter settings and quit back,they will go to the top of filter list, in that situation, they have to scroll down to find the new added filter to open it.

So is it possible that when user quit back, you can make the new added filter appear in the upside of screen, not the upside of filter list, so user can open that filter without scrolling list to find it.

Personally,,i think this is better .

**Comment by d4rken** [comment]
You mean it remembers the scroll position?

**Comment by Edfgdz** [comment]
I think this issue can be closed because I created a ticket that add the function to make user can sort filters via date and name in this issue. 

https://github.com/d4rken/sdmaid-public/issues/2237

With this feature, user can find out new created filters easily.
