### ISSUE TITLE
Default exclusion for Viber thumbnails?

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1482]
`/storage/emulated/0/Android/data/com.viber.voip/files/.thumbnails`

matched by the hidden caches AppCleaner filter.

Causes:
![screenshot_2018-01-28-11-50-41](https://user-images.githubusercontent.com/1439229/35509226-ae5c1684-04f3-11e8-8c36-0368261f2e1d.png)

Fixed by clearing vibers cache and restarting the app.

I'm unsure if this warrants a default exclusion or if this is just something that should be left up to the user...

**Comment by patrickdrd** [comment]
I'm deleting viber images and
I'm getting those blank/empty images on the conversation's media information too,
I would prefer the opposite: all of them (images/thumbnails/blank/empty images deleted)

**Comment by d4rken** [comment]
The "blank image" is not something we can easily delete, it's part of the chata database referencing the image thumbnail that was deleted.

If you mean deleting the files received through Viber, then this is certainly something I could add (like for WhatsApp). Please make another ticket for that if you are interested in such a feature.

**Comment by d4rken** [comment]
A default exclusion isn't warranted.
