### ISSUE TITLE
FC when dragging autoselection elements

### ISSUE THREAD

**Issue by irontechmonkey** [d4rken/sdmaid-public#1483]
SD_Maid-v4.10.0(41000)-BETA-7d7a98ee9 installed on top of previous Playstore update to Pro on Moto G3 Osprey running LOS 14.1 (N 7.1.1) w/ LOS SU, and where display properties and pagination may be a factor Settings > Display > Font size = Largest. 
Install ID: 5a8f9a40-d626-456a-a2f2-1357d8a7b498 

Attached log spans:
- Open SD Maid
- Go to Duplicates
- Overflow (3dot) menu
- Configure Autoselection
- Grab by 2-line icon and drag until covering another item in the list.
- FC
- Can reproduce every time.

[SDMaidFC2018-01-29-15-38-27.txt](https://github.com/d4rken/sdmaid-public/files/1675636/SDMaidFC2018-01-29-15-38-27.txt)

**Comment by d4rken** [comment]
Thanks, can reproduce too.

**Comment by d4rken** [comment]
Got it fixed. 👍

**Comment by irontechmonkey** [comment]
Thanks. Will keep testing (within my limited range of experience).
