### ISSUE TITLE
Search with wildcards doesn't work as expected on exact matches

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#1487]
In search tool,Files only closed,Case-sensitive and Implicit Wildcards opened,entry [data] cant get any result,but device built-in explorer can get them.
 When Implicit Wildcards closed,it work well.

![1517376810526](https://user-images.githubusercontent.com/26460124/35606779-ca96faf0-068b-11e8-86b1-920b0f6f62ab.jpg)

![1517376810491](https://user-images.githubusercontent.com/26460124/35606784-cfc8e15a-068b-11e8-9d7e-1602eac1f89c.jpg)

**Comment by Edfgdz** [comment]
This is setting popup
![screenshot_2018-02-04-17-12-58](https://user-images.githubusercontent.com/26460124/35776981-0c8fd974-09e1-11e8-9d22-efef48abbd0c.png)

This is log file

https://drive.google.com/file/d/1D2JFWtOTcC-fQKVSTPK8VB6xev7SZgZ_/view?usp=sharing

**Comment by d4rken** [comment]
Search trips over an error:

```
1517737411918 D/RXS:RxShell:Session: writeLine(line=$V5B9D812A9C51 find '/storage/emulated/0' \(  -path '*hwvefs*' -o -path '*/proc/*' -o -path '/dev/*' -o -path '*/sys/*' -o -path '*/acct/*'  \) -prune -o -name *data* -print, flush=false)
1517737411918 D/RXS:RxShell:Session: writeLine(line=echo e1c27ae9-fc37-4f50-b758-25ff4f7f26c4 $?, flush=false)
1517737411918 D/RXS:RxShell:Session: writeLine(line=echo e1c27ae9-fc37-4f50-b758-25ff4f7f26c4 >&2, flush=true)
1517737411922 V/RXS:Harvester:Error: find: bad arg 'init.post-fs-data.rc'
1517737411922 D/RXS:Harvester:Error: find: bad arg 'init.post-fs-data.rc'
```

**Comment by d4rken** [comment]
```
sailfish:/sdcard $ find . -iname *data*
find: bad arg 'sleep-data'
sailfish:/sdcard $ find . -iname "*data"
./Android/data
./Android/data/com.google.android.apps.maps/testdata
./Android/data/com.google.android.GoogleCamera/files/storage/emulated/0/Android/data
./Android/data/ch.threema.app/files/data
./data
./sleep-data
./Documents/sleep-data
```
