### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/obb/com.netease.chijikas (FP)

### ISSUE THREAD

**Issue by dhoelogy** [d4rken/sdmaid-public#1495]
### Target
Target: `/storage/emulated/0/Android/obb/com.netease.chijikas`
Prefix-free: `com.netease.chijikas`
Path-prefix: `/storage/emulated/0/Android/obb/`
Type: `DIRECTORY`
Location: `PUBLIC_OBB`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Rules of Survival`
Packagename: `com.netease.chiji`
Version: `1.126941.131775 (258717)`

### Current owners
None

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `xiaomi/mido/mido:7.0/NRD90M/V9.0.3.0.NCFMIEI:user/release-keys`

### Comment
`Can't delete this folder.`

**Comment by d4rken** [comment]
Definition reporting are not about "deletability".
