### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.xiaomi.vip (FP)

### ISSUE THREAD

**Issue by EricChen1** [d4rken/sdmaid-public#1504]
### Target
Target: `/storage/emulated/0/Android/data/com.xiaomi.vip`
Prefix-free: `com.xiaomi.vip`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `我的小米`
Packagename: `com.xiaomi.vipaccount`
Version: `dev.1113 (1113)`

### Current owners
None

### SD Maid
Version: `4.10.0 (41000)`

### Device
Fingerprint: `xiaomi/mido/mido:7.0/NRD90M/8.2.1:user/release-keys`

**Comment by d4rken** [comment]
I think both `com.xiaomi.vipaccount` and `com.xiaomi.vip` exist, why do you think they share this folder?

**Comment by Bgimien11** [comment]
Nice huhu

**Comment by d4rken** [comment]
Lacks info.
