### ISSUE TITLE
Crash report: User Filter setting for SystemCleaner

### ISSUE THREAD

**Issue by ya8sa** [d4rken/sdmaid-public#1514]
Crashed when clicking + icon for new user filter or long press existing user filter then clicking edit icon.
The device infomation:
=== Device info ===
Install ID: 864fd4af-e09c-4ff5-9b7a-b9034f247720
ROM: samsung/SC-04J/SC-04J:7.0/NRD90M/SC04JOMU1AQJ3:user/release-keys/en
SD Maid: 4.10.1[41001]
Unlocker: 4.2.3[40203]
Root: false
Storage: /storage/emulated/0 (SAF-match=false)
Storage: /storage/9016-4EF8 (SAF-match=true)

The logs are attached.
Thanks.

[sdmaid_logfile_1518700220531.log](https://github.com/d4rken/sdmaid-public/files/1728006/sdmaid_logfile_1518700220531.log)
[sdmaid_logfile_1518702441175.log](https://github.com/d4rken/sdmaid-public/files/1728007/sdmaid_logfile_1518702441175.log)

**Comment by d4rken** [comment]
Thanks, will be fixed in v4.10.2.
