### ISSUE TITLE
Clutterreport: /storage/F91A-1F11/Vault/bt_firmware (new)

### ISSUE THREAD

**Issue by Valudonox** [d4rken/sdmaid-public#1515]
### Target
Target: `/storage/F91A-1F11/Vault/bt_firmware`
Prefix-free: `Vault/bt_firmware`
Path-prefix: `/storage/F91A-1F11/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `// substweaks //`
Packagename: `me.msfjarvis.substweaks`
Version: `3.2 (32)`

Appname: `ROM Patcher`
Packagename: `com.xperia64.rompatcher`
Version: `2.16 (26)`

### Current owners
None

### SD Maid
Version: `4.10.1 (41001)`

### Device
Fingerprint: `Verizon/heroqltevzw/heroqltevzw:7.0/NRD90M/G930VVRS4BRA1:user/release-keys`

**Comment by d4rken** [comment]
I don't think these two own that folder, can you elaborate?
