### ISSUE TITLE
Clutterreport: /storage/emulated/0/QQSecureDownload/mfcache/com.gotv.nflgamecenter.us.lite.cache

### ISSUE THREAD

**Issue by Valudonox** [d4rken/sdmaid-public#1516]
### Target
Target: `/storage/emulated/0/QQSecureDownload/mfcache/com.gotv.nflgamecenter.us.lite.cache`
Prefix-free: `QQSecureDownload/mfcache/com.gotv.nflgamecenter.us.lite.cache`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Hancom Office Editor`
Packagename: `com.hancom.office.editor.hidden`
Version: `7.0.171106 (341671)`

### Current owners
Appname: `?`
Packagename: `com.tencent.qqpimsecure`
Version: `null (0)`

Appname: `?`
Packagename: `com.tencent.qqpimsecurepad`
Version: `null (0)`

Appname: `?`
Packagename: `com.tencent.qqpimsecuret`
Version: `null (0)`

Appname: `?`
Packagename: `com.tencent.qqpadsecure`
Version: `null (0)`

### SD Maid
Version: `4.10.1 (41001)`

### Device
Fingerprint: `Verizon/heroqltevzw/heroqltevzw:7.0/NRD90M/G930VVRS4BRA1:user/release-keys`

**Comment by d4rken** [comment]
I don't think this is correct, can you explain?

**Comment by d4rken** [comment]
Hm?
