### ISSUE TITLE
import function is not working 

### ISSUE THREAD

**Issue by tom0034** [d4rken/sdmaid-public#1518]
device: Samsung s8 sm-g950f
android version: 7.0 custom Rom
root: magisk v15.2
sdmaid pro 4.9.5

**Comment by d4rken** [comment]
Which import function?

Please add a few more details.

**Comment by tom0034** [comment]
All import function is not working.
For example, in the "Exlusion" tag, i use the import function to add a path/folder, it does not present my selection.
Also the same result for the "SystemCleaner" tag -> filter manager -> user -> import , that is not working too

**Comment by d4rken** [comment]
Are you trying to create a new exclusion through the "import" option?
The import function is there to restore exclusions from backup files that have previously been exported.
You can not use it to choose the path you want to exclude.

Is this what you mean?

**Comment by tom0034** [comment]
Oh i see, sorry for the misunderstanding.
Thank you for clarifying that, i am sorry to bother you.
Sdmaid is an amazing tool , keep it up!

**Comment by d4rken** [comment]
No problem.
