### ISSUE TITLE
Clutterreport: /storage/emulated/0/Fonts

### ISSUE THREAD

**Issue by kenswa1** [d4rken/sdmaid-public#1519]
### Target
Target: `/storage/emulated/0/Fonts`
Prefix-free: `Fonts`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.shinycore.picsayfree`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `com.shinycore.picsaypro`
Version: `null (0)`

Appname: `?`
Packagename: `com.shinycore.fonts.dietersteffmann.b`
Version: `null (0)`

Appname: `?`
Packagename: `com.shinycore.fonts.kimberlygeswein.a`
Version: `null (0)`

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `samsung/heroqltetmo/heroqltetmo:7.0/NRD90M/G930TUVS4BRA1:user/release-keys`

**Comment by d4rken** [comment]
Hm?
