### ISSUE TITLE
Clutterreport: /storage/emulated/0/''1.Downloader''/''Download to Downloading''/toolbox-for-google-play-store-public-master/Versuch--master/Google Play Gift Card Code Generator (2014) (new)

### ISSUE THREAD

**Issue by Ich35** [d4rken/sdmaid-public#1523]
### Target
Target: `/storage/emulated/0/''1.Downloader''/''Download to Downloading''/toolbox-for-google-play-store-public-master/Versuch--master/Google Play Gift Card Code Generator (2014)`
Prefix-free: `''1.Downloader''/''Download to Downloading''/toolbox-for-google-play-store-public-master/Versuch--master/Google Play Gift Card Code Generator (2014)`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `1Mobile Market`
Packagename: `me.onemobile.lite.android`
Version: `3.9.5 (73)`

### Current owners
None

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `samsung/kltexx/klte:6.0.1/MMB29M/G900FXXS1CQD4:user/release-keys`

**Comment by d4rken** [comment]
A valid report need to be for the top most folder.

Is `''1.Downloader''` a default folder created by "1Mobile Market"?
