### ISSUE TITLE
SD Maid deletes systemless Xposed files as corpses

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1545]
Renders Xposed useless. I'm talking about the Xposed Oreo systemless beta via Magisk Manager's downloads. Too bad I don't have the corpses to back up the report - they're gone, and I cannot figure out how to reinstall Xposed as it falls.

**Comment by d4rken** [comment]
SD Maid Version?
Android Version?
What device?
Link to Xposed ?
Error that xposed gives?

**Comment by mcl21014** [comment]
SD Maid v4.10.3 26.02.2018
Android 8.1.0
Pixel XL OG
https://forum.xda-developers.com/xposed/unofficial-systemless-xposed-t3388268
Magisk Log: https://forum.xda-developers.com/xposed/unofficial-systemless-xposed-t3388268

**Comment by mcl21014** [comment]
Oops. https://www.dropbox.com/s/seskg5gkn0zch9w/install_log_20180301_112636.log?dl=0
This was supposed to be the Magisk log.

**Comment by d4rken** [comment]
Lack of info/repro.
