### ISSUE TITLE
Clutterreport: /storage/emulated/0/MIUI (new)

### ISSUE THREAD

**Issue by simone-viozzi** [d4rken/sdmaid-public#1548]
### Target
Target: `/storage/emulated/0/MIUI`
Prefix-free: `MIUI`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `MIUI Forum`
Packagename: `com.miui.enbbs`
Version: `2.0.0 (200)`

### Current owners
None

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `xiaomi/tissot/tissot_sprout:8.0.0/OPR1.170623.026/8.1.10:user/release-keys`

**Comment by d4rken** [comment]
This is used by multiple apps, right? The base `MIUI` folder.

**Comment by simone-viozzi** [comment]
right, but there isn't created by user, the system use this folder. if is possible to use the mi logo icon for this folder is pretty beautiful. thanks

**Comment by d4rken** [comment]
I can add a general match for `com.miui.*` but flag it as `COMMON` so it is not suggested for deletion.
