### ISSUE TITLE
Clutterreport: /storage/emulated/0/spy.phone2 (new)

### ISSUE THREAD

**Issue by regreg11** [d4rken/sdmaid-public#1556]
### Target
Target: `/storage/emulated/0/spy.phone2`
Prefix-free: `spy.phone2`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `com.qualcomm.qti.networksetting`
Packagename: `com.qualcomm.qti.networksetting`
Version: `6.0.1 (23)`

### Current owners
None

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `ZTE/P817T06_MPCS/camellia:6.0.1/MMB29M/20170615.175128:user/release-keys`

**Comment by d4rken** [comment]
Got some more info on this? Can't confirm it.

**Comment by d4rken** [comment]
Not enough info.
