### ISSUE TITLE
Rotating screen under AppControl or Exclusions with sidebar open resets filter to all items

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1558]
Device: Pixel XL
Android version: 8.1.0
Root status: Rooted with Magisk
Rotating the screen under AppControl or Exclusions with the sidebar open causes the filter to reset to All Items. Rotating the screen should preserve the previous selection.

**Comment by d4rken** [comment]
Which SD Maid version?

**Comment by mcl21014** [comment]
SD Maid v4.10.4

**Comment by d4rken** [comment]
Better late then never 😁
