### ISSUE TITLE
Clutterreport: /storage/emulated/0/.tubemate

### ISSUE THREAD

**Issue by hackills** [d4rken/sdmaid-public#1564]
### Target
Target: `/storage/emulated/0/.tubemate`
Prefix-free: `.tubemate`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `TubeMate`
Packagename: `devian.tubemate.v3`
Version: `3.0.7 (1034)`

### Current owners
~~Appname: `?`~~
~~Packagename: `devian.tubemate.home`~~
~~Version: `null (0)`~~

~~Appname: `?`~~
~~Packagename: `devian.tubemate.amazon`~~
~~Version: `null (0)`~~

~~Appname: `?`~~
~~Packagename: `devian.tubemate.slide`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `samsung/heroltexx/herolte:7.0/NRD90M/G930FXXS1DQHM:user/release-keys`

**Comment by d4rken** [comment]
Why are the others not a match?

**Comment by hackills** [comment]
Mine was different, so assumed it's the only valid package. They don't contain names either.

**Comment by d4rken** [comment]
I think those are possible variations of the same app that share this folder, but I'll look into it and add your report in any case.

Thanks for helping me!
