### ISSUE TITLE
Clutterreport: /storage/19B9-1DE7/Downloads (new)

### ISSUE THREAD

**Issue by banksoft** [d4rken/sdmaid-public#1568]
### Target
Target: `/storage/19B9-1DE7/Downloads`
Prefix-free: `Downloads`
Path-prefix: `/storage/19B9-1DE7/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `ระบบ Android`
Packagename: `android`
Version: `7.0 (24)`

### Current owners
None

### SD Maid
Version: `4.10.3 (41003)`

### Device
Fingerprint: `samsung/a9xproltedx/a9xproltesea:7.0/NRD90M/A910FXXU1BRA2:user/release-keys`

**Comment by d4rken** [comment]
Needs more info like #1569

Usually the system Download folder is `Download`.
