### ISSUE TITLE
Clutterreport: /storage/19B9-1DE7/Downloads (new)

### ISSUE THREAD

**Issue by banksoft** [d4rken/sdmaid-public#1569]
### Target
Target: `/storage/19B9-1DE7/Downloads`
Prefix-free: `Downloads`
Path-prefix: `/storage/19B9-1DE7/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `การจัดการการ​ดาวน์​โหลด`
Packagename: `com.android.providers.downloads`
Version: `7.0 (24)`

### Current owners
None

### SD Maid
Version: `4.10.3 (41003)`

### Device
Fingerprint: `samsung/a9xproltedx/a9xproltesea:7.0/NRD90M/A910FXXU1BRA2:user/release-keys`

**Comment by d4rken** [comment]
I'm not sure about this, usually the default folder is `Download`.

Got any more info?

**Comment by SuperSandro2000** [comment]
Some 3rdparty downloaders like adm do this.

**Comment by d4rken** [comment]
@SuperSandro2000 I agree, then matching this to the system downloader would be wrong.

Closed due to lack of information from the OP.
