### ISSUE TITLE
Doesn't work with Wine installed (apply exclusions before scanning).

### ISSUE THREAD

**Issue by VHrishikesh** [d4rken/sdmaid-public#1571]
Device: Coolpad Note 3

Android Version: 7.1.2 (problem initially noticed on 8.1.0)

SD Maid version: 4.10.6 (problem persistent through a few updates too)

What happens: The App Cleaner function never just finishes. It goes on and on and on like it's stuck. Once, I had it on for like 40mins., it was still going on and on. It gets stuck only on one folder /data/user/0/org.winehq.wine. So, I tried to exclude it from App Cleaner (and even global), it doesn't work. It still tries to scan the folder and gets stuck there. 

What's expected to happen: The scaning process should complete, either by scanning that folder or without scanning that particular folder.

Wine: https://dl.winehq.org/wine-builds/android/ There's the Wine app. I'm using v3.3 (arm). The problem existed with previous versions of Wine too and SD Maid works well without Wine installed. So, I just want to exclude the folder, at least.

Paths used: As I said before, SD Maid gets stuck at /data/user/0/org.winehq.wine. The folder has a total of 2440 files (within various sub-folders which total upto 117 folders - all nestings included) and its size is 344.8MB.

**Comment by d4rken** [comment]
The folder contains much more than 2440 files, at least 14.000.

There are also many loops that further slow SD Maid down:

```
1520949879549 V/RXS:Harvester:Error: find: '/data/user/0/org.winehq.wine/files/prefix/dosdevices/z:/sys/bus/cpu/devices/cpu4/subsystem': loop detected
1520949879550 D/RXS:Harvester:Error: find: '/data/user/0/org.winehq.wine/files/prefix/dosdevices/z:/sys/bus/cpu/devices/cpu4/subsystem': loop detected
1520949879551 V/RXS:Harvester:Error: find: '/data/user/0/org.winehq.wine/files/prefix/dosdevices/z:/sys/bus/cpu/devices/cpu5/subsystem': loop detected
1520949879551 D/RXS:Harvester:Error: find: '/data/user/0/org.winehq.wine/files/prefix/dosdevices/z:/sys/bus/cpu/devices/cpu5/subsystem': loop detected
```

The search process itself works fine but due to the internal loops SD Maid racked up 210k+ files/folders and is still going.

The existing exclusion system may not be enough because exclusions are applied after scanning, but before further processing. To be effective here, the exclusion needs to prevent SD Maid from scanning the path beforehand.

**Comment by VHrishikesh** [comment]
Well, okay. My file manager showed me just 2k files. Anyways, so, till we get an update, any way to use App Cleaner with Wine installed?

**Comment by d4rken** [comment]
Can reproduce with wine 3.11.

**Comment by d4rken** [comment]
I've added an additional early exclusion check within the AppCleaner tool and added a default exclusion (removable though) for `org.winehq.wine`.

**Comment by d4rken** [comment]
Databases tool was affected too. Fixed too 😁
