### ISSUE TITLE
Clutterreport: /storage/02F3-0C18/busybox-arm (new)

### ISSUE THREAD

**Issue by Ahmad1116** [d4rken/sdmaid-public#1577]
### Target
Target: `/storage/02F3-0C18/busybox-arm`
Prefix-free: `busybox-arm`
Path-prefix: `/storage/02F3-0C18/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `BusyBox Free`
Packagename: `stericson.busybox`
Version: `56 (206)`

### Current owners
None

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `HUAWEI/TRT-L21A/HWTRT-Q:7.0/HUAWEITRT-L21A/C185B150:user/release-keys`

**Comment by d4rken** [comment]
When is this created? Why should it be kept without the app ?
