### ISSUE TITLE
Clutterreport: /storage/emulated/0/.Instagram (new)

### ISSUE THREAD

**Issue by Ahmad1116** [d4rken/sdmaid-public#1578]
### Target
Target: `/storage/emulated/0/.Instagram`
Prefix-free: `.Instagram`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Instagram`
Packagename: `com.instagram.android`
Version: `stub (18.4) (1)`

### Current owners
None

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `HUAWEI/TRT-L21A/HWTRT-Q:7.0/HUAWEITRT-L21A/C185B150:user/release-keys`

**Comment by d4rken** [comment]
What does this contain to be marked as "keeper"?
