### ISSUE TITLE
Re-evaluate use of the accessibility service for cache cleaning

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1588]
The primary issues are:

* Google's disdain for abuse of this feature
* Doesn't work in the background
* Really cheap "hack"

Google seems to have relaxed their position, but requires a good explanation. See attached screenshot showing Taskers explanation.

Their GPlay description just contains:

> This app uses Accessibility services.

The foreground issue can't be fixed. So this will be difficult to run via scheduler. The only workaround I can think of would be to make this OPT-IN with huge warning not to cry 1 ⭐️  if it doesn't work as expected.

It being a "cheap hack" is still valid, but as Android 8.1 removed the global "clear cache" button in system > storage, this really makes it easier for the user (on <8.1 doing it manually is a lot faster).
<details><summary>Tasker Example</summary>

![screenshot_20180321-152518](https://user-images.githubusercontent.com/1439229/37733105-4a93aa8c-2d47-11e8-97c1-c82ef6f7f2a1.png)

</details>

**Comment by d4rken** [comment]
Comments welcome!

**Comment by jise** [comment]
Another example.
The same developer Sam Lu: https://play.google.com/store/apps/dev?id=7252933074709348199
AppMgr III (App 2 SD): https://play.google.com/store/apps/details?id=com.a0soft.gphone.app2sd

![screenshot_20190219-221728](https://user-images.githubusercontent.com/6588902/53048255-a20bd780-3494-11e9-8e83-8fe166c864bb.png)
![screenshot_20190219-163545](https://user-images.githubusercontent.com/6588902/53048272-a932e580-3494-11e9-8f4b-9e8b88aea540.png)

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service

**Comment by d4rken** [comment]
Got a working prototype, figuring out an easy UI integration will be a bit more work, but so far so good.

**Comment by d4rken** [comment]
I need help with the localization and different Android versions.

SD Maid needs to find the two items to click:

**Item 1** is a list entry that takes us to the app's storage details, in English on Android 9 the entry reads:
```
Storage
X,XX MB used in internal storage
```
[Example](https://user-images.githubusercontent.com/1439229/54468042-627d9600-4789-11e9-94dc-bc1e8ed0149d.png)


**Item 2** is the button for clearing the cache, in English on Android 9 it's labeled:
```
Clear cache
```
[Example](https://user-images.githubusercontent.com/1439229/54468047-69a4a400-4789-11e9-8216-012ed083df13.png)

**How to help:**

* Post the text of item 1 and item 2, so I can copy paste them (in case non Latin characters are used)
* Add a screenshot of both screens

**Comment by jise** [comment]
cs/Czech, 9 Xiaomi Mi A1

Úložiště
25,40 GB
Využito z 64 GB

VYMAZAT MEZIPAMĚŤ

![Screenshot_20190316-161559](https://user-images.githubusercontent.com/6588902/54477360-44ef1180-4807-11e9-974a-8b7b484d81a9.png)
![Screenshot_20190316-161653](https://user-images.githubusercontent.com/6588902/54477361-4ae4f280-4807-11e9-963e-9f6d4015e957.png)

**Comment by d4rken** [comment]
@jise The first screenshot is from the general "device storage" screen, isn't it? I need the app specific page, see my first example screenshot again.

**Comment by jise** [comment]
> @jise The first screenshot is from the general "device storage" screen, isn't it? I need the app specific page, see my first example screenshot again.

I'm so sorry, I was in a hurry and completely missed your clickable examples. Here is the correct one:

Úložiště
interní úložiště - využito 14,38 MB

![Screenshot_20190316-191432](https://user-images.githubusercontent.com/6588902/54479723-2ba68f00-4820-11e9-878c-7e3bcccec84a.png)

**Comment by d4rken** [comment]
The base implementation is done, to improve support for additional languages and ROMs see #2396
