### ISSUE TITLE
Clutterreport: /root (FP)

### ISSUE THREAD

**Issue by ACEBASS** [d4rken/sdmaid-public#1590]
### Target
Target: `/root`
Prefix-free: `/root`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Software update`
Packagename: `com.wssyncmldm`
Version: `2.0.54.0 (205400000)`

### Current owners
None

### SD Maid
Version: `4.10.6 (41006)`

### Device
Fingerprint: `samsung/j7popltespr/j7popltespr:7.0/NRD90M/J727PVPS3ARA1:user/release-keys`

**Comment by d4rken** [comment]
Please don't send reports if you don't under it.
