### ISSUE TITLE
Clutterreport: /storage/emulated/0/.Emoji & Smileys/.shareImage.png (new)

### ISSUE THREAD

**Issue by Wolfdragon78** [d4rken/sdmaid-public#1633]
### Target
Target: `/storage/emulated/0/.Emoji & Smileys/.shareImage.png`
Prefix-free: `.Emoji & Smileys/.shareImage.png`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Emoji`
Packagename: `com.pixelfoxes.stickers`
Version: `1.0 (3)`

### Current owners
None

### SD Maid
Version: `4.10.11 (41011)`

### Device
Fingerprint: `samsung/a5y17ltevl/a5y17ltecan:7.0/NRD90M/A520WVLS2BRC1:user/release-keys`

**Comment by Wolfdragon78** [comment]
Am pretty sure it is with this particular app...I have 5 emoji apps currently & every one of them copies from the other 4 in various ways...

**Comment by d4rken** [comment]
It is also possible to map multiple apps as owners to it if you think there are multiple.

Namewise it sounds a bit like this could be created by a keyboard app?

**Comment by Wolfdragon78** [comment]
Is possible yes. Was 1st time since getting the app that this happened so
was unsure if should ignore it or at least point out how 5 different app's
are copying each other... Better to be safe than sorry 👍

**Comment by d4rken** [comment]
Can you share the packagenames of the other apps?

**Comment by Wolfdragon78** [comment]
Here is a Screenshot of the Emoji apps where this mystery 1 was found by
the SD Maid this time. They are all from the Google Play Store BUT not easy
to locate 😶

**Comment by d4rken** [comment]
Can't confirm this, I installed and used the app but no folder was created.

**Comment by Wolfdragon78** [comment]
Since the initial email, have loyally kept using the app & am puzzled.
Reason being how long had those emoji apps as well as yours & yet never saw
that particular notification come up. Nor have I seen it since I am just
realizing as started this reply.

Is it possible there was an update to either app since my initial enquiry?

**Comment by d4rken** [comment]
It's possible, the app itself has the storage permission, but never asks for it, I gave it that permission manually, but nothing happened.

No worries, I'm closing this for now, if you find something new just reopen.

**Comment by Wolfdragon78** [comment]
Would rather err on the side of caution & report a false error over see
such a decent program get weighed down on any site it is available from by
people just refusing to ask for help as I did.
Appreciate the attention to this meantime. Case is definitely solved & with
excellent service 👍

**Comment by d4rken** [comment]
I agree, better one report too many than too few 👍
