### ISSUE TITLE
Clutterreport: /storage/emulated/0/shumei.txt (new)

### ISSUE THREAD

**Issue by faith2112** [d4rken/sdmaid-public#1634]
### Target
Target: `/storage/emulated/0/shumei.txt`
Prefix-free: `shumei.txt`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `APUS Browser`
Packagename: `com.apusapps.browser`
Version: `2.1.5 (139)`

### Current owners
None

### SD Maid
Version: `4.10.11 (41011)`

### Device
Fingerprint: `MetroPCS/sf340n_mpcs_us/sf340n:7.0/NRD90U/180360953701e:user/release-keys`

**Comment by d4rken** [comment]
Can you share some more details on what this file is?
Are you sure about this relation?

**Comment by d4rken** [comment]
Can't confirm.
