### ISSUE TITLE
Clutterreport: /storage/emulated/legacy/LDD软件 (new)

### ISSUE THREAD

**Issue by MMDKZT** [d4rken/sdmaid-public#1642]
### Target
Target: `/storage/emulated/legacy/LDD软件`
Prefix-free: `LDD软件`
Path-prefix: `/storage/emulated/legacy/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Kango`
Packagename: `com.kirin.project.kango`
Version: `1.2.23 (1223)`

### Current owners
None

### SD Maid
Version: `4.10.11 (41011)`

### Device
Fingerprint: `HUAWEI/TAG-AL00/HWTAG-L6753:5.1/HUAWEITAG-AL00/C00B121:user/release-keys`

**Comment by d4rken** [comment]
What does the folder name mean in english?

**Comment by MMDKZT** [comment]
这个文件夹没有英文名，因为这个软件只有中文显示（而且这个软件没有在GooglePlay上架）

This folder does not have an English name because the software is only displayed in Chinese (and this software is not on Google Play)
