### ISSUE TITLE
Clutterreport: /storage/emulated/legacy/MyFavorite (new)

### ISSUE THREAD

**Issue by MMDKZT** [d4rken/sdmaid-public#1644]
### Target
Target: `/storage/emulated/legacy/MyFavorite`
Prefix-free: `MyFavorite`
Path-prefix: `/storage/emulated/legacy/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Android System WebView`
Packagename: `com.android.webview`
Version: `39 (1447499983-arm64) (300002)`

Appname: `下载内容`
Packagename: `com.android.providers.downloads.ui`
Version: `5.1-1447499983 (22)`

Appname: `下载管理程序`
Packagename: `com.android.providers.downloads`
Version: `5.1-1447499983 (22)`

### Current owners
None

### SD Maid
Version: `4.10.11 (41011)`

### Device
Fingerprint: `HUAWEI/TAG-AL00/HWTAG-L6753:5.1/HUAWEITAG-AL00/C00B121:user/release-keys`

**Comment by d4rken** [comment]
I don't think this folder is created by these system apps, I have not seen such a folder on any other device. What makes you think it is?

**Comment by MMDKZT** [comment]
因为我发现这个文件夹是在用系统自带的浏览器下载文件时用的文件夹（安卓5.1.1)。

Because I found this folder to be used when downloading files from the browser that comes with the system (Android 5.1.1).


Using Google's machine translation, please understand that I can't speak English
