### ISSUE TITLE
Clutterreport: /storage/emulated/0/Tencent

### ISSUE THREAD

**Issue by Bobi60** [d4rken/sdmaid-public#1647]
### Target
Target: `/storage/emulated/0/Tencent`
Prefix-free: `Tencent`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
~~Appname: `?`~~
~~Packagename: `^(?:com\.tencent\..+?)$`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.10.11 (41011)`

### Device
Fingerprint: `Sony/C6603/C6603:5.1.1/10.7.A.0.228/58103698:user/release-keys`

**Comment by d4rken** [comment]
Why?
