### ISSUE TITLE
Can you add the following folders/paths to the AppCleaner section

### ISSUE THREAD

**Issue by briantyler7171** [d4rken/sdmaid-public#1650]
1)/data/data/com.snapchat.android/files/media_cache

2)/storage/emulated/0/Android/data/com.spotify.music/files/spotifycache/Storage

3)/storage/emulated/0/Android/data/com.zhiliaoapp.musically/files/frescocache
& /storage/emulated/0/Android/data/com.zhiliaoapp.musically/Videos

4)/storage/emulated/0/Keerby/FormatFactory/tmp

5)/storage/emulated/0/PicsArt/drawing/tracked

Reason:
1) Snapchat: these are all the loaded and (maybe) viewed snaps & stories which are of no use after you view them for the first time (Went upto 1GB before I deleted it manually)

2) Spotify: these are the cached audio files which aren't used again after you play 2 or 3 songs after it (free user) and downloads the full thing again if you go back to it. (Has gone upto 3GB)

3) Musical.ly: this is cache of the viewed videos and thumbnails (goes upto 300MB in my experience)

4) FormatFactory: cache after processing/rendering a video
(Rendered a 200MB video and this file had snapshots of each frame which were around 2.5MB each, total size of the folder went upto 800MB)

5) PicsArt: Previously drawn/edited stuff (goes upto 200MB for me)

**Comment by briantyler7171** [comment]
About the Spotify cache being music stored offline

Please add an option in settings to toggle it on or off..?

**Comment by briantyler7171** [comment]
Sorry for replying so late..

Links for each app:-
1)https://play.google.com/store/apps/details?id=com.snapchat.android

2)https://play.google.com/store/apps/details?id=com.spotify.music

3)https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically

4)https://play.google.com/store/apps/details?id=com.keerby.formatfactory

5)https://play.google.com/store/apps/details?id=com.picsart.studio

Answers to each question:
1) They'll load up again.. On second thought, keep this as an option, don't keep it on, by default.. (this folder includes a lot of filter cache and stuff so the first launch after deleting all this will be a slow launch)

2) Yep, extra filter would be good.. (For Snapchat too) And add a warning stating, if you're a paid user, songs you're downloaded for offline use will(maybe) get deleted

3) Yes.. Android doesn't clear this in the app info clear cache option.. 

4) No, /storage/emulated/0/Keerby/FormatFactory/ has the rendered files.. (Only delete /tmp)

5) Umm.. Yeah, I guess..

**Comment by d4rken** [comment]
- [ ] /data/data/com.snapchat.android/files/media_cache
- [ ] /storage/emulated/0/Android/data/com.spotify.music/files/spotifycache/Storage
- [ ] /storage/emulated/0/Android/data/com.zhiliaoapp.musically/files/frescocache
& /storage/emulated/0/Android/data/com.zhiliaoapp.musically/Videos
- [ ] /storage/emulated/0/Keerby/FormatFactory/tmp
- [ ]  /storage/emulated/0/PicsArt/drawing/tracked

**Comment by briantyler7171** [comment]
Awesome!
