### ISSUE TITLE
SD Maid Crash on Settings or Tools - StorageVolumeMapper Error

### ISSUE THREAD

**Issue by JamieBrassel** [d4rken/sdmaid-public#1677]
I'm getting this error in SD Maid 4.10.12 and the unlocker. I'm running the second beta of Android P (PPP2.180412.013), rooted with Magisk. I have tried resetting the app, restarting, and giving all the permissions. This happens whenever I try to navigate to Settings, or any one of the tools. All of them crash.

Below is a snippet of the logcat for the error:

> 05-09 10:56:23.093  6904  6954 W u.thedarken.sd: Accessing hidden method Landroid/os/storage/StorageManager;->getVolumes()Ljava/util/List; (light greylist, reflection)
> 05-09 10:56:23.093  6904  6954 W u.thedarken.sd: Accessing hidden method Landroid/os/storage/VolumeInfo;->getId()Ljava/lang/String; (light greylist, reflection)
> 05-09 10:56:23.093  6904  6954 W u.thedarken.sd: Accessing hidden method Landroid/os/storage/VolumeInfo;->getFsUuid()Ljava/lang/String; (light greylist, reflection)
> 05-09 10:56:23.093  6904  6954 W u.thedarken.sd: Accessing hidden method Landroid/os/storage/VolumeInfo;->getPath()Ljava/io/File; (light greylist, reflection)
> 05-09 10:56:23.094  6904  6954 W u.thedarken.sd: Accessing hidden method Landroid/os/storage/VolumeInfo;->isPrimary()Z (light greylist, reflection)
> 05-09 10:56:23.094  6904  6954 W u.thedarken.sd: Accessing hidden method Landroid/os/storage/VolumeInfo;->getDescription()Ljava/lang/String; (blacklist, reflection)
> 05-09 10:56:23.112   709  7047 D Magisk  : su: request from client: 18
> 05-09 10:56:23.112   709  7047 D Magisk  : su: request from uid=[10127] (#5)
> 05-09 10:56:23.113   709  7047 D Magisk  : su: waiting child: [7048]
> 05-09 10:56:23.113  7048  7048 D Magisk  : su: child process started
> 05-09 10:56:23.113  7048  7048 D Magisk  : su: argc=[1]
> 05-09 10:56:23.113  7048  7048 D Magisk  : su: argv[0]=[su]
> 05-09 10:56:23.113  7048  7048 D Magisk  : su: pts_slave=[]
> 05-09 10:56:23.113  7048  7048 D Magisk  : su: use namespace of pid=[7041]
> 05-09 10:56:23.144  6904  6954 W u.thedarken.sd: Accessing hidden field Landroid/provider/DocumentsContract;->PATH_TREE:Ljava/lang/String; (blacklist, reflection)
> 05-09 10:56:23.154   709  7037 D Magisk  : su: return code: [0]
> 05-09 10:56:23.155  6904  7069 D NetworkSecurityConfig: No Network Security Config specified, using platform default
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime: FATAL EXCEPTION: SDM:Thread:0
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime: Process: eu.thedarken.sdm, PID: 6904
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate StorageVolumeMapper.
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.tools.storage.oswrapper.mapper.c.<init>(StorageVolumeMapper.java:84)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.SDMContext.g(SDMContext.java:229)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.SDMContext.a(SDMContext.java:260)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.tools.storage.g.g(StorageFactory.java:5242)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.tools.storage.j.a(StorageManager.java:77)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.main.core.a.a(BaseConditions.java:93)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.main.core.ac.run(Unknown Source:1144)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at eu.thedarken.sdm.main.core.v.run(Unknown Source:1052)
> 05-09 10:56:23.155  6904  6954 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
> 05-09 10:56:23.201  6904  6904 W PropertyValuesHolder: Method set() with type float not found on target class class me.zhanghai.android.materialprogressbar.IndeterminateHorizontalProgressDrawable$RectTransformX
> 05-09 10:56:23.285  1215  4633 W ActivityManager:   Force finishing activity eu.thedarken.sdm/.main.ui.SDMMainActivity
> 05-09 10:56:23.286  1215  4633 V ActivityManager: Moving to PAUSING: ActivityRecord{7a97adc u0 eu.thedarken.sdm/.main.ui.SDMMainActivity t19 f}
> 05-09 10:56:23.286  1215  4633 V ActivityManager: State movement: ActivityRecord{7a97adc u0 eu.thedarken.sdm/.main.ui.SDMMainActivity t19 f} from:RESUMED to:PAUSING reason:startPausingLocked
> 05-09 10:56:23.288  6904  6954 I Process : Sending signal. PID: 6904 SIG: 9
> 05-09 10:56:23.301  1215  1238 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{2c0eb28 6904:eu.thedarken.sdm/u0a127} (pid=6904, uid=10127) requires android.permission.READ_LOGS due to sender android (uid 1000)
> 05-09 10:56:23.301  1215  1238 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
> 05-09 10:56:23.301  1215  1238 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
> 05-09 10:56:23.304   903   903 E lowmemorykiller: Error writing /proc/6904/oom_score_adj; errno=22
> 05-09 10:56:23.309   709  7047 D Magisk  : su: return code: [0]
> 05-09 10:56:23.310  1215  1344 W InputDispatcher: channel '1dcf81f eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 05-09 10:56:23.310  1215  1344 E InputDispatcher: channel '1dcf81f eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 05-09 10:56:23.311  1215  6114 I WindowManager: WIN DEATH: Window{1dcf81f u0 eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity}
> 05-09 10:56:23.311  1215  6114 W InputDispatcher: Attempted to unregister already unregistered input channel '1dcf81f eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity (server)'
> 05-09 10:56:23.312  1215  1231 I ActivityManager: Process eu.thedarken.sdm (pid 6904) has died: vis  +99TOP
> 05-09 10:56:23.313  1215  1231 V ActivityManager: Moving to DESTROYED: ActivityRecord{7a97adc u0 eu.thedarken.sdm/.main.ui.SDMMainActivity t19 f} (cleaning up)
> 05-09 10:56:23.313  1215  1231 V ActivityManager: State movement: ActivityRecord{7a97adc u0 eu.thedarken.sdm/.main.ui.SDMMainActivity t19 f} from:PAUSING to:DESTROYED reason:cleanupActivityLocked
> 05-09 10:56:23.313  1215  1241 W libprocessgroup: kill(-6904, 9) failed: No such process
> 05-09 10:56:23.313  1215  1241 I libprocessgroup: Successfully killed process cgroup uid 10127 pid 6904 in 0ms
> 05-09 10:56:23.313   771   771 I Zygote  : Process 6904 exited due to signal (9)
> 05-09 10:56:23.315  1215  1231 V ActivityManager: Moving to DESTROYED: ActivityRecord{7a97adc u0 eu.thedarken.sdm/.main.ui.SDMMainActivity t19 f} (removed from history)
> 05-09 10:56:23.315  1215  1231 V ActivityManager: State movement: ActivityRecord{7a97adc u0 eu.thedarken.sdm/.main.ui.SDMMainActivity t19 f} from:DESTROYED to:DESTROYED reason:removeActivityFromHistoryLocked
> 05-09 10:56:23.315  1215  1231 V ActivityManager: State unchanged from:DESTROYED
> 05-09 10:56:23.316   610   629 W SurfaceFlinger: Attempting to set client state on removed layer: eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity#0
> 05-09 10:56:23.316   610   629 W SurfaceFlinger: Attempting to destroy on removed layer: eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity#0

**Comment by d4rken** [comment]
>  and the unlocker.

The unlocker app itself crashes? Or just the main app?

**Comment by JamieBrassel** [comment]
My apologies for the confusion. The unlocker works perfectly, as far as I can tell. It's only the main app that crashes.

**Comment by d4rken** [comment]
Might also be this:
```
05-09 10:56:23.144 6904 6954 W u.thedarken.sd: Accessing hidden field Landroid/provider/DocumentsContract;->PATH_TREE:Ljava/lang/String; (blacklist, reflection)
```

I'll install Android P and try to reproduce it. Might push a quickfix as v4.10.13, v4.11.0 is not quite ready yet.

**Comment by d4rken** [comment]
Could reproduce.

Caused by reflection access to `DocumentsContract.PATH_TREE` and `PATH_DOCUMENT`.

I can likely hardcode their values for now and release a hotfix, then work on a better solution later.

**Comment by d4rken** [comment]
Let's continue in #2140 @patrickdrd
