### ISSUE TITLE
Sanity checks for final Android P preview

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1683]
- [x] Check whether `StorageVolume.getOwner()` is still blacklisted. (PPP3)
- [x] Check whether `VolumeInfo.getPathForUser(I)` is still blacklisted. (PPP3)
- [x] Check whether `VolumeInfo.getDescription()` is still blacklisted. (PPP3)
- [x] Check whether `DiskInfo.isAdoptable()` is still blacklisted. (PPP3)
- [x] Check whether `DiskInfo.isDefaultPrimary()` is still blacklisted. (PPP3)
- [x] Check whether `StorageManager.getStorageLowBytes()` (PPP3)
- [x] Check whether `StorageManager.getStorageFullBytes()` (PPP3)

**Comment by potjanat** [comment]
Hj

**Comment by d4rken** [comment]
Updated as of PPP3.
