### ISSUE TITLE
Add open with functionality to various tools

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1685]
Currently, Explorer, Searcher, and Duplicates just open files that you tap with the default app. Oftentimes, this is undesired behavior, as I had a case where .jpg images were opening in Microsoft Edge. Add an open with dialogue at minimum to add basic functionality. This would be more user friendly.

**Comment by d4rken** [comment]
Forcing the chooser for the explorer only, in other tools it will be annoying. But good idea, this is overdue.
