### ISSUE TITLE
Clutterreport: /storage/emulated/0/.aaffbbc (new)

### ISSUE THREAD

**Issue by Derrick1975** [d4rken/sdmaid-public#1700]
### Target
Target: `/storage/emulated/0/.aaffbbc`
Prefix-free: `.aaffbbc`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Advanced Task Manager`
Packagename: `mobi.infolife.taskmanager`
Version: `6.3.5 (198)`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `TCL/Alcatel_5044R/BUZZ6T4GGOPHONE:7.0/NRD90M/YAK:user/release-keys`

**Comment by d4rken** [comment]
What does this contain?
Are you sure about the ownership?
