### ISSUE TITLE
Clutterreport: /storage/emulated/0/ApkEditor

### ISSUE THREAD

**Issue by prem7844** [d4rken/sdmaid-public#1703]
### Target
Target: `/storage/emulated/0/ApkEditor`
Prefix-free: `ApkEditor`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.gmail.heagoo.apkeditor.pro`~~
~~Version: `null (0)`~~

~~Appname: `?`~~
~~Packagename: `com.gmail.heagoo.apkeditor`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `samsung/j7maxlteins/j7maxlte:7.0/NRD90M/G615FXXU2ARE1:user/release-keys`

**Comment by d4rken** [comment]
Why do you think it is not an owner?
