### ISSUE TITLE
Clutterreport: /storage/emulated/0/xbrowser

### ISSUE THREAD

**Issue by dpolson** [d4rken/sdmaid-public#1704]
### Target
Target: `/storage/emulated/0/xbrowser`
Prefix-free: `xbrowser`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `?`
Packagename: `com.mmbox.browser`
Version: `null (0)`

Appname: `?`
Packagename: `com.mmbox.xbrowser.gp`
Version: `null (0)`

~~Appname: `?`~~
~~Packagename: `com.mmbox.xbrowser.pro`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `com.mmbox.xbrowser`
Version: `null (0)`

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `samsung/j7popqltetfnvzw/j7popqltetfnvzw:6.0.1/MMB29M/S727VLUDU2AQG1:user/release-keys`

**Comment by d4rken** [comment]
Why do you think it is not an owner?
