### ISSUE TITLE
Clutterreport: /data/app/com.dv.adm.pay.swiftinstaller.overlay-M7-g-S4ULc2AF8mBZxZhHA== (FP)

### ISSUE THREAD

**Issue by HorstiG** [d4rken/sdmaid-public#1710]
### Target
Target: `/data/app/com.dv.adm.pay.swiftinstaller.overlay-M7-g-S4ULc2AF8mBZxZhHA==`
Prefix-free: `com.dv.adm.pay.swiftinstaller.overlay-M7-g-S4ULc2AF8mBZxZhHA==`
Path-prefix: `/data/app/`
Type: `DIRECTORY`
Location: `APP_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `samsung/greatltexx/greatlte:8.0.0/R16NW/N950FXXU3CRE5:user/release-keys`

### Comment
`over 50 overlays from Swift installer`

**Comment by d4rken** [comment]
Needs extra details, what package does this belong to?

**Comment by d4rken** [comment]
Fixed by #1813
