### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/System/local/acc.dat (FP)

### ISSUE THREAD

**Issue by truunforgiven69** [d4rken/sdmaid-public#1711]
### Target
Target: `/storage/emulated/0/Android/data/System/local/acc.dat`
Prefix-free: `System/local/acc.dat`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Google`
Packagename: `com.google.android.googlequicksearchbox`
Version: `8.3.14.21.arm (300774853)`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `MetroPCS/sf340n_mpcs_us/sf340n:7.0/NRD90U/180881144f876:user/release-keys`

**Comment by d4rken** [comment]
Please share some more details why you think this,

**Comment by potjanat** [comment]
Ml

**Comment by d4rken** [comment]
Lack of info.
