### ISSUE TITLE
`magiskhide`

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1715]
Might be cool to display each apps `magiskhide` status and allow it to be toggled via SD Maid...

Might not be cool because it overlaps with magiskmanager's own functionality... ?

```
MagiskHide v16.4(1642) (by topjohnwu) - Hide Magisk!

Usage: magiskhide [--options [arguments...] ]

Options:
  --enable          Start magiskhide
  --disable         Stop magiskhide
  --add PROCESS     Add PROCESS to the hide list
  --rm PROCESS      Remove PROCESS from the hide list
  --ls              Print out the current hide list
```

**Comment by SuperSandro2000** [comment]
Why bother with duplicating stuff?

**Comment by mcl21014** [comment]
Sounds cool but too superfluous. And like it will only lead to more bugs. Magisk Manager crashes enough as is ATM.

**Comment by d4rken** [comment]
I agree, let's not add this.
