### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM (FP)

### ISSUE THREAD

**Issue by Golgo13lou** [d4rken/sdmaid-public#1717]
### Target
Target: `/storage/emulated/0/DCIM`
Prefix-free: `DCIM`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Camera`
Packagename: `com.motorola.cameraone`
Version: `6.2.5.16 (60020516)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `8.0.0 (26)`

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `motorola/hannah_sprint/hannah:8.0.0/OCP27.91-32/33:user/release-keys`

**Comment by d4rken** [comment]
Usually the camera aps use a subfolder in `DCIM`, is there none here?

**Comment by Golgo13lou** [comment]
No just DCIM

**Comment by AaronPeepster** [comment]
Please help.. I'm having trouble getting my sdcard to be another drive for
my phone like usual and everything is screwed up.

**Comment by Golgo13lou** [comment]
Apparently Motorola E5 Plus DCIM folder is empty at first boot up. I just
ran SD Maid explorer after having taken pics and sending one. It identified
no problem as there were two sub folders this time. Guess it depends on if
DCIM is populated for it to work, just a guess. It's running great no other
issues for me.

**Comment by d4rken** [comment]
Where did you send the screenshot?
