### ISSUE TITLE
SD Maid crashes when going to Debug > Settings > General Settings > Advanced Settings

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1722]
Android version: P/9 DP3
Device: Pixel XL
SDM version: 4.11.0
Unlocker version: 4.2.6
Root status: rooted

Log: https://www.dropbox.com/s/kiaje3tgykuldyb/2018-06-11-10-43-07.txt?dl=0

Crashes when doing the steps mentioned in the title. SD Maid crashes when going to Debug > Settings > General Settings > Advanced Settings

**Comment by d4rken** [comment]
Fixed in dev
