### ISSUE TITLE
Clutterreport: /storage/emulated/0/com.facebook.pages.app (new)

### ISSUE THREAD

**Issue by cihankaralar** [d4rken/sdmaid-public#1727]
### Target
Target: `/storage/emulated/0/com.facebook.pages.app`
Prefix-free: `com.facebook.pages.app`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Sayfa Yöneticisi`
Packagename: `com.facebook.pages.app`
Version: `167.0.0.30.87 (112704067)`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `google/taimen/taimen:8.1.0/OPM2.171026.006.C1/4769658:user/release-keys`

**Comment by d4rken** [comment]
What's inside?

**Comment by cihankaralar** [comment]
Facebook pages managers temp files.

15 Haz 2018 Cum 00:03 tarihinde Matthias Urhahn <notifications@github.com>
şunu yazdı:
