### ISSUE TITLE
Home Screen Shortcut for App Cleaner

### ISSUE THREAD

**Issue by Shankdevilz** [d4rken/sdmaid-public#1731]
Is there any way to clear apps cache with a home screen shortcut

**Comment by d4rken** [comment]
No, but you can trigger the app cleaner via widget.

**Comment by Shankdevilz** [comment]
Sorry i didn't noticed that

**Comment by Shankdevilz** [comment]
But widget size is big,1x1 widget will be better.

**Comment by d4rken** [comment]
You can resize the widget.

**Comment by Shankdevilz** [comment]
A toast message would be better after completing the task.

**Comment by d4rken** [comment]
A toast message after what?

**Comment by d4rken** [comment]
I think most people would find that annoying as it obstructs the main screen. Additionally it is only shortly visible and to benefit from it you have to view the screen at the time.

The results are already shown via notifications which I think is more convenient than toasts.

**Comment by Shankdevilz** [comment]
Thank You for Giving Me Your Valuable Time.😊
