### ISSUE TITLE
Clutterreport: /storage/emulated/0/.thinkfree/AFonts/.ahn_l.ttf.cached.7-0-140412-lge.4.70.10 (FP)

### ISSUE THREAD

**Issue by Dianelyn** [d4rken/sdmaid-public#1732]
### Target
Target: `/storage/emulated/0/.thinkfree/AFonts/.ahn_l.ttf.cached.7-0-140412-lge.4.70.10`
Prefix-free: `.thinkfree/AFonts/.ahn_l.ttf.cached.7-0-140412-lge.4.70.10`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `ThinkFree Viewer`~~
~~Packagename: `com.lge.thinkfreeviewer`~~
~~Version: `4.70.10 (470000010)`~~

~~Appname: `?`~~
~~Packagename: `com.tf.thinkdroid.amarket`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `com.tf.thinkdroid.samsung`
Version: `null (0)`

Appname: `?`
Packagename: `com.tf.thinkdroid.asus`
Version: `null (0)`

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `lge/p1_vzw/p1:6.0/MRA58K/1714511498b1b:user/release-keys`

**Comment by d4rken** [comment]
Why did you reopen this?
