### ISSUE TITLE
Sliding list vibration

### ISSUE THREAD

**Issue by YiTuanJun** [d4rken/sdmaid-public#1737]
When I scroll through long lists, such as file lists, or application lists, the contents of the list wiggle up and down violently for a while，and then you go down a little bit.
I try to clean up the data, after I clean up the data for the first time open the SDM, sliding list is normal and smooth, but even if I'm not doing anything, exit and  reopen the SDM, list shake again, and this problem has lasted for several versions.

**Comment by d4rken** [comment]
Would it be possible for you to record a short video of the behavior?

I assume you are on SD Maid v4.10.13, what Android device and version?

**Comment by YiTuanJun** [comment]
I actually just touch the center of the screen and drag it up.

**Comment by d4rken** [comment]
Does it also happen if you touch it somewhere else?

Does it happen in landscape mode?

Does it happen in other apps?

I'm currently a bit puzzled and don't know where to even start looking into this ☹️ .

**Comment by YiTuanJun** [comment]
I say the center simply means that there is no touch fastscroller
I just tried the horizontal mode and it will do the same thing
It's normal to swipe anywhere else where can scroll the screen

**Comment by d4rken** [comment]
Does it also happen in SD Maids "Duplicates" tool?

**Comment by YiTuanJun** [comment]
Yes

**Comment by YiTuanJun** [comment]
Now this bug is like this, when I just open the application, if the current interface is rolling, then the normal for the first time, if then switch to any other interface, all rolling is not normal

**Comment by d4rken** [comment]
Is there any list in SD Maid where it doesn't happen?

We'll probably wait with debugging until after v4.11.0. It's possible that it already fixes it due to many widespread UI code changes. Generally debugging UI issues like this that I can't reproduce locally are a nightmare 😢 .

**Comment by YiTuanJun** [comment]
All places with long lists have this bug. I understand your inconvenience, but as soon as possible, I am a professional version user, this bug has a big impact on usage.

**Comment by d4rken** [comment]
Is still happening? I have not been able to reproduce this.
