### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download (FP)

### ISSUE THREAD

**Issue by a0943764882** [d4rken/sdmaid-public#1752]
### Target
Target: `/storage/emulated/0/Download`
Prefix-free: `Download`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
Appname: `下載`
Packagename: `com.android.providers.downloads.ui`
Version: `7.1.1 (25)`

~~Appname: `下載管理員`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `7.1.1 (25)`~~

Appname: `Android 系統`
Packagename: `android`
Version: `7.1.1 (25)`

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `samsung/c9ltezt/c9lte:7.1.1/NMF26X/C900YZTU1BQL3:user/release-keys`

**Comment by marlenehstack** [comment]
Need to root my Samsung s7
Can anyone help? Marlenehstack@gmail.com
