### ISSUE TITLE
Clutterreport: /data/user/0/1 (FP)

### ISSUE THREAD

**Issue by Kocyak** [d4rken/sdmaid-public#1770]
### Target
Target: `/data/user/0/1`
Prefix-free: `1`
Path-prefix: `/data/user/0/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.9.5 (40905)`

### Device
Fingerprint: `htc/htc_europe/ville:4.1.1/JRO03C/128506.10:user/release-keys`

### Comment
`can't delete folder. it was com.vkontakte.android/shared_prefs`

**Comment by d4rken** [comment]
The clutter report system is not for reporting files that can't be deleted.

Independent of that I would first update to the latest version and if it still doesn't work to create a new ticket with a debug log of the failing deletion attached:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
