### ISSUE TITLE
Clutterreport: /storage/emulated/legacy/kgmusic.ver (new)

### ISSUE THREAD

**Issue by MMDKZT** [d4rken/sdmaid-public#1793]
### Target
Target: `/storage/emulated/legacy/kgmusic.ver`
Prefix-free: `kgmusic.ver`
Path-prefix: `/storage/emulated/legacy/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `酷狗音乐`
Packagename: `com.kugou.android`
Version: `8.9.8 (8983)`

### Current owners
None

### SD Maid
Version: `4.11.0 (41100)`

### Device
Fingerprint: `HUAWEI/TAG-AL00/HWTAG-L6753:5.1/HUAWEITAG-AL00/C00B121:user/release-keys`

**Comment by d4rken** [comment]
Thank you. Great reports.
