### ISSUE TITLE
Bug: Uninstall watcher not running well

### ISSUE THREAD

**Issue by aditj77** [d4rken/sdmaid-public#1806]
### What happened?
SDMaid problem in v4.10.13 (stable in playstore) until v4.11.1 (beta). Uninstall watcher in CorpseFinder only works once after disable and enable again. After that, when I uninstall an app, uninstall watcher not auto run.

### What did you expect to happen?
Everytime after i uninstall app, should be uninstall watcher autorun.

### How can I reproduce the issue?
Uninstall watcher in CorpseFinder only works once after disable and enable again. After that, when I uninstall an app, uninstall watcher not auto run.

### SD Maid
Version: `4.11.1 (41101)`

### Device
Root: `Unknown`
Fingerprint: `Xiaomi/santoni/santoni:7.1.2/N2G47H/V9.5.10.0.NAMMIFD:user/release-keys`

**Comment by d4rken** [comment]
Can unfortunately not reproduce this. If you want to further pursue this please record an ADB logcat of SD Maid doing nothing, e.g. the time frame when it should have become active.
