### ISSUE TITLE
Request: Move user apps to system apps and vise versa

### ISSUE THREAD

**Issue by fabianbees** [d4rken/sdmaid-public#1808]
### What should the feature do?
Very simple: an option for "converting" system apps to non system apps, a for converting non system apps to system apps

### When/How would you use it?
If i want to install e.g. the Google Pixel Launcher on a non Pixel device i have to convert the Launcher to a system app to make use of Google Now cards ...

### How would you implement it?
Maybe somwere in the AppControl section ...

### Comments
I love your app. Its great. I mostly use it for uninstalling system apps ;) I realy want to see this feature in your app, because other apps which could do this are really crappy :-o

### SD Maid
Version: `4.11.2 (41102)`
Unlocker: `4.3.0 (40300) (true)`

### Device
Root: `Unknown`
Fingerprint: `OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447858500:user/release-keys`

**Comment by d4rken** [comment]
Merging this with ticket #1342
