### ISSUE TITLE
Request: Storage analyzer - cache memory

### ISSUE THREAD

**Issue by MarceloAmarante** [d4rken/sdmaid-public#1812]
### What should the feature do?
Improved presentation of cache memory for the user

### When/How would you use it?
Every time the cache memory was analyzed

### How would you implement it?
Uniformize the units of measure used when displaying free spaces and used in cache memory
Ex: 970 MB free
         17 MB used

SD Maid currently reports:
0.97 GB free
   17 MB used.

### Comments
In other stores, it seems that they are already made in the way previously mentioned.

### SD Maid
Version: `4.11.2 (41102)`
Unlocker: `4.3.0 (40300) (true)`

### Device
Root: `Unknown`
Fingerprint: `samsung/m0xx/m0:4.3/JSS15J/I9300XXUGMJ9:user/release-keys`

**Comment by d4rken** [comment]
I don't think that would be better.

Let's say we have a 128GB SDCARD and there is a 100KB file on it, we would then have to display something liek:
```
127GB free
0.0001GB used
or
127000MB free
0.1MB used
or
127000000KB free
100KB used
```

**Comment by SuperSandro2000** [comment]
Btw do you use base 1000 or 1024 for conversion?

**Comment by d4rken** [comment]
That's actually a good question, turns out both, depending on the Android Version...

>=N 1000
<N 1024

https://developer.android.com/reference/android/text/format/Formatter.html?hl=my#formatFileSize(android.content.Context,%20long)

"Just Android things"™️  😆
