### ISSUE TITLE
Clutterreport: /data/app/FelipeLeite.Greight-1 (FP)

### ISSUE THREAD

**Issue by gagabs** [d4rken/sdmaid-public#1815]
### Target
Target: `/data/app/FelipeLeite.Greight-1`
Prefix-free: `FelipeLeite.Greight-1`
Path-prefix: `/data/app/`
Type: `DIRECTORY`
Location: `APP_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Loja de temas`
Packagename: `com.samsung.android.themestore`
Version: `1.03.22(20160524) (10322)`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `samsung/o7ltedd/o7lte:6.0.1/MMB29M/G600FYVJU1BPL3:user/release-keys`

**Comment by d4rken** [comment]
Is this the same issue as #1813 ?

**Comment by SuperSandro2000** [comment]
Not exactly. As far as I can tell this is an Samsung Theme Store Theme. I am going to do some research.

**Comment by gagabs** [comment]
> As far as I can tell this is an Samsung Theme Store Theme.

Exactly. Every theme is removed in the current rules. After reboot they appear as broken in the apps list, but they should never appear here, as they are "special apps".

What info do you need?

**Comment by SuperSandro2000** [comment]
I provided quite a few infos in #1813. Should be fixes together with the substratum issues I would guess.

**Comment by d4rken** [comment]
Does this theming technique have the same `target_package` field as #1813??

**Comment by SuperSandro2000** [comment]
As you can see [here](https://github.com/d4rken/sdmaid-public/issues/1813#issuecomment-402662357) not exactly. Samsung does it different. The theme requests a permission and has a field that requests some "features" eg: ``<uses-feature d1p1:name="samsung.theme.wallpaper"/>``

**Comment by d4rken** [comment]
By "not exactly" you mean that not all Samsung themes have it? Do some have it? I guess we have to differentiate between user apps being themed and system components being themed?

**Comment by SuperSandro2000** [comment]
I mean that Samsung handles stuff differently than substratum.

All Samsung themes have this  com.samsung.android.permission.SAMSUNG_OVERLAY_* and one ore more <uses-feature d1p1:name="samsung.theme.*"/>

**Comment by d4rken** [comment]
So I think this will be adressed by the soslution proposed in https://github.com/d4rken/sdmaid-public/issues/1813#issuecomment-403207158

I don't have a Samsung device to test this, @gagabs please send me a mail to test a preview version when I have implemented this so that we can confirm it works correctly.

**Comment by SuperSandro2000** [comment]
> Suggested owners
Appname: Loja de temas
Packagename: com.samsung.android.themestore
Version: 1.03.22(20160524) (10322)

Just saying that this is technically not correct as theme store does not own the folder

**Comment by d4rken** [comment]
Closed #1813

**Comment by gagabs** [comment]
Still present in 4.11.3 BETA
![](https://i.imgur.com/KwrEqn3.png)

**Comment by gagabs** [comment]
Possible related info: working Samsung's themes  doesn't appear in any app list, only the broken ones

**Comment by SuperSandro2000** [comment]
This issue is about the apks. The issue with private data is located here #1842 and being looked at.

**Comment by d4rken** [comment]
@gagabs Please post the screenshot in #1842 and also elaborate on what you mean "only the broken ones"? 🤗 

That `system:ui` is also uncommon, maybe worth a ticket too if you think this is a false positive.
