### ISSUE TITLE
Request: Add Firefox and crash events folder to AppCleaner

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1816]
### What should the feature do?
Add both Firefox and Firefox Focus Nightly crash events to AppCleaner.

### When/How would you use it?
When running AppCleaner. Should at least be considered. I run AC at least once a week.

### How would you implement it?
For Firefox: /data/data/org.mozilla.firefox/files/mozilla/02fi9aav.default/crashes 
/data/data/org.mozilla.firefox/files/mozilla/02fi9aav.default/minidumps had a .dmp file in it that was safely deleted while running Firefox Focus Nightly, so the same should apply to Firefox.

For Nightly: 
/data/data/org.mozilla.fennec_aurora/files/mozilla/Crash Reports can be deleted safely as well.
/data/data/org.mozilla.fennec_aurora/files/mozilla/t9ce23sh.default/minidumps 
/data/data/org.mozilla.fennec_aurora/files/mozilla/t9ce23sh.default/crashes for Nightly.

For upcoming Focus:
/data/data/org.mozilla.focus/files/mozilla/9pi7l4gc.default/crashes
/data/data/org.mozilla.focus/files/mozilla/9pi7l4gc.default/minidumps
/data/data/org.mozilla.focus/files/mozilla/Crash Reports
### Comments
Firefox Focus will use Gecko in v6 instead of Android Webview, so that app may be considered as well. See screenshot here: https://www.dropbox.com/s/3aibdz9g7r6cjmw/Screenshot_20180704-122513.png?dl=0
https://www.dropbox.com/s/0s0m3ndaxuyfsnu/Screenshot_20180704-125328.png?dl=0
https://www.dropbox.com/s/e44c1wtyialqnr9/Screenshot_20180704-130242.png?dl=0
### SD Maid
Version: `4.11.3 (41103)`
Unlocker: `4.3.0 (40300) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/marlin/marlin:9/PPP4.180612.004/4838310:user/release-keys`

**Comment by mcl21014** [comment]
Screenshot contains what directory contents look like

**Comment by mcl21014** [comment]
Also, I deleted those files with Firefox running and noticed no issues.

**Comment by d4rken** [comment]
What does `/data/data/org.mozilla.firefox/files/mozilla/` look like, I think we need to match the different profile folders so we delete crash dumps for all users?

Why delete `events`? What about the parent folder `crashes`?

**Comment by mcl21014** [comment]
Also consider adding /data/data/org.mozilla.firefox/files/mozilla/02fi9aav.default/minidumps. I deleted this for Firefox Focus Nightly while running and it didn't cause any bad behaviors.

**Comment by mcl21014** [comment]
Hmm. Maybe you're right. Delete the paremt folder. It's recreated anyhow when Fx crashes again.

**Comment by d4rken** [comment]
Delete `/data/data/org.mozilla.firefox/files/mozilla/02fi9aav.default`? No, I think that's the profile dir.
