### ISSUE TITLE
Request: Add support for cleaning xposed folders from subdirectories in /data/data

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1822]
### What should the feature do?
Clean out empty xposed folders leftover in app subdirectories under /data/data/.

### When/How would you use it?
When Xposed had been installed but no longer is installed.

### How would you implement it?
First, we'd need a way to check if Xposed is installed. If it's not installed, I would create a filter under the CorpseFinder or any relevant tool to clean out these empty directories.

### SD Maid
Version: `4.11.3 (41103)`
Unlocker: `4.3.0 (40300) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/marlin/marlin:9/PPP4.180612.004/4838310:user/release-keys`

**Comment by d4rken** [comment]
Closing due to lack of interest, currently too niche.
