### ISSUE TITLE
Clutterreport: /storage/0123-4567/Audio (new)

### ISSUE THREAD

**Issue by James1733** [d4rken/sdmaid-public#1829]
### Target
Target: `/storage/0123-4567/Audio`
Prefix-free: `Audio`
Path-prefix: `/storage/0123-4567/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `8.0.0 (26)`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `samsung/starqltesq/starqltesq:8.0.0/R16NW/G960USQS2ARF4:user/release-keys`

**Comment by d4rken** [comment]
As far as I know this is not a folder that is created by the system, i.e. on a fresh install.


Why do you think this is owned by the system?
