### ISSUE TITLE
[Feature Request] Enable debug run from within the app

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#1838]
I am a very lazy guy and would love to beable to run the debug mode from within the app.

**Comment by d4rken** [comment]
Can you elaborate on that? I'm not sure what you mean by "from within the app".

**Comment by SuperSandro2000** [comment]
> Debugrun log
TL;DR
Force stop SD Maid.
Create the file <sdcard>/Android/data/eu.thedarken.sdm/files/sdm_force_debug_run
Open SD Maid and everything will be written into the log file
When you are done just exit SD Maid and mail/upload the log file from <sdcard>/Android/data/eu.thedarken.sdm/cache/logfiles

right now I need to follow those steps but maybe it is possible to add a setting entry for it so that I only need to hit one button SD Maid asks for confirmation and then restart with debuging enabled. Maybe show a toast that it worked?

**Comment by d4rken** [comment]
In the debug menu (long press settings), there is a button "Create debug trigger" which will do exactly that (I think?). Afterwards you have to manually force-stop SD Maid though as there is no releliable way to kill SD Maid natively (without getting too complex).

The simpler the debugging is, the less chance there is that a bug in the debugging code prevents us from debugging 😁

**Comment by SuperSandro2000** [comment]
Exactly what I searched for. Thanks for the info
