### ISSUE TITLE
Add Hidden Caches for Amazon's Webview

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1839]
Path is /data/data/com.amazon.mShop.android.shopping/app_mashWebViewState
Folder contains items named 1531151908029MASHWebFragment1.0, for example, as well as a journal file named journal. All files are safe to delete. Running Android 9 DP4 on a Pixel XL rooted with Magisk, and running SDM v4.11.3, with unlocker version 4.3.0.
https://www.dropbox.com/s/tp98k0yix7clifp/Screenshot_20180709-115725.png?dl=0

**Comment by SuperSandro2000** [comment]
The Amazon app seems to lag any function to delete them.
![](https://www.dropbox.com/s/tp98k0yix7clifp/Screenshot_20180709-115725.png?dl=1)

**Comment by d4rken** [comment]
Nice @mcl21014 

Also looks good for the "WebView caches" filter.
