### ISSUE TITLE
Add Puffin Favicon Cache

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1840]
Path is /data/data/com.cloudmosa.puffin/app_favicon_cache
https://www.dropbox.com/s/rh876cw9ppnlarm/Screenshot_20180709-121343.png?dl=0
Contents are safe to delete. Running Android 9 DP4 on a Pixel XL with SDM 4.11.3 and unlocker 4.3.0. Rooted with Magisk.

**Comment by d4rken** [comment]
Looks good. I think this would fit the "Webview caches" filter.
