### ISSUE TITLE
Add Hidden Caches for Google Plus

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#1841]
Path: /data/data/com.google.android.apps.plus/app_localMedia
Safe to delete. See this URL for contents of the path:
https://www.dropbox.com/s/icghgp6vf6wirwb/Screenshot_20180709-130956.png?dl=0
SDM v4.11.3, unlocker v4.3.0, Pixel XL on DP4 of 9 with Magisk su.

**Comment by SuperSandro2000** [comment]
Did you test if AppCleaner with all Settings activated clears this? Maybe G+ is installed as System and you didn't activate that option?

**Comment by mcl21014** [comment]
No it doesn't clear it.

**Comment by d4rken** [comment]
@SuperSandro2000 The explorer should show the AppCleaner icon for things that are recognized as "cache" independent of the AppCleaners settings. There is a module called `CacheForensics` which both Explorer and AppCleaner share that isn't affected by settings (I think... SD Maids codebase is quite large 😲 ).
