### ISSUE TITLE
Fail to change receptors in Applications control.

### ISSUE THREAD

**Issue by sironoris** [d4rken/sdmaid-public#1854]
I've tried to use application to change boot complete receptors in Android KitKat. But application failed to change anything.
I mention that I used another application (All-in-one) and it worked.
I have SuperSU installed and BusyBox. I've tried all BB installers from market and don't worked.
App works for anotherr device with LineageOS 14 with root.

**Comment by sironoris** [comment]
My device is Lenovo Yoga B-8000F. JB Android version from factory, OTA update to KK. Rooted with KingRoot, changed with SuperSU.

**Comment by d4rken** [comment]
Please provide a debuglog of it failing.

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by sironoris** [comment]
Mi, 11 iul. 2018, 02:14 Matthias Urhahn <notifications@github.com> a scris:

**Comment by d4rken** [comment]
Still need that log.

**Comment by sironoris** [comment]
Hi. For log please see the attachment of my previous mail.
I'm not a developer. I opened that thread because I believe that this will
help you more than a simple comment in Google market.
Your app is the best cleaner from market. This is the reason for buying pro
key. That was my help but please don't ask me for more.
Personal I believe that the problem is related with Titanium Backup that
fail to restore backups. Probably is something that remain read only. But
really I don't understand how All-in-one toolbox works and those two
favourite apps fail.
I hope you will solve this.
Best regards

**Comment by d4rken** [comment]
The previous comment does not contain a logfile.

I think attaching a file via mail response does not work on Github.

You have to upload via website or mail it to support@darken.eu

**Comment by d4rken** [comment]
Thanks for the logfile.
(Un)fortunately, this is not an SD Maid issue, but an issue with your ROM or super user app.

See #947 and #785. 

```
1531303892137 D/RXS:RxShell:Session: writeLine(line=LD_LIBRARY_PATH=/vendor/lib:/system/lib:$LD_LIBRARY_PATH pm disable 'com.google.android.apps.translate/com.google.android.apps.translate.RebootReceiver', flush=false)
1531303892149 D/RXS:RxShell:Session: writeLine(line=echo 612fed16-5b53-4208-8145-bf0f45e4e076 $?, flush=false)
1531303892150 D/RXS:RxShell:Session: writeLine(line=echo 612fed16-5b53-4208-8145-bf0f45e4e076 >&2, flush=true)
1531303892763 V/RXS:Harvester:Error: android.os.TransactionTooLargeException
1531303892764 D/RXS:Harvester:Error: android.os.TransactionTooLargeException
1531303892764 V/RXS:Harvester:Error: Error: Could not access the Package Manager.  Is the system running?
1531303892766 D/RXS:Harvester:Error: Error: Could not access the Package Manager.  Is the system running?
```
