### ISSUE TITLE
Clutterreport: /storage/emulated/0/Floating Apps (new)

### ISSUE THREAD

**Issue by lagunnic** [d4rken/sdmaid-public#1859]
### Target
Target: `/storage/emulated/0/Floating Apps`
Prefix-free: `Floating Apps`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Floating Apps`
Packagename: `com.lwi.android.flappsfull`
Version: `4.6.1 (140608013)`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `Meizu/meizu_M5s/M5s:6.0/MRA58K/1524191364:user/release-keys`

**Comment by d4rken** [comment]
You marked this "keeper" does this contain backups of some sort that are relevant even when the app is not installed?

**Comment by lagunnic** [comment]
Yes it is. In the subfolders of this folder, images, video, audio and other files created using this program are saved.

С уважением, Николай

________________________________

**Comment by d4rken** [comment]
👍 will be added with the next update. Spasibo!

**Comment by lagunnic** [comment]
👍bitte schön!

С уважением, Николай

________________________________
