### ISSUE TITLE
Overview show negative amount of free space

### ISSUE THREAD

**Issue by master1274** [d4rken/sdmaid-public#1863]
![screenshot_2018-07-11_10-46-28](https://user-images.githubusercontent.com/20639709/42622645-86b3670c-85c9-11e8-8781-ac05cbfbbe5f.png)

**Comment by d4rken** [comment]
Please provide a debug log
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by d4rken** [comment]
@master1274 I think I found the issue. Can you send me a mail and try a test version?

**Comment by master1274** [comment]
Какое письмо на какой адрес?

**Comment by SuperSandro2000** [comment]
support@darken.eu
