### ISSUE TITLE
Bug: I already paid for pro in marescamichael2@gmail.com now im mikey05301986@gmail.com

### ISSUE THREAD

**Issue by MichaelMaresca1986** [d4rken/sdmaid-public#1866]
### What happened?
I already paid for pro in marescamichael2@gmail.com now I'm mikey05301986@gmail.com

### What did you expect to happen?
Already paid for pro in marescamichael2@gmail.com im now mikey05301986@gmail.com

### How can I reproduce the issue?
Already paid for pro in marescamichael2@gmail.com now im mikey05301986@gmail.com

### Comments
Already paid for pro marescamichael2@gmail.com now im mikey05301986@gmail.com

### SD Maid
Version: `4.11.3 (41103)`
Unlocker: ` (0) (false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `TCL/5027B/Pixi445SPR:6.0.1/MMB29M/vNEE4-0:user/release-keys`

**Comment by SuperSandro2000** [comment]
Read that here: https://productforums.google.com/d/msg/play/jPyKkxuIXrI/Y0uhqYwnCAAJ

**Comment by d4rken** [comment]
@MichaelMaresca1986 This public issue tracker is only for code related issues. You need to write a mail to support@darken.eu for payment related issues. Purchases can't be moved though (see link by @SuperSandro2000). Write me a mail though, maybe I can still help you.
