### ISSUE TITLE
Corpse Finder and shaders files in MM

### ISSUE THREAD

**Issue by gagabs** [d4rken/sdmaid-public#1867]
Probably a false positive

![](https://i.imgur.com/jjlvddX.png)

![](https://i.imgur.com/nGMI2jP.png)

All itens in the first picture are similar to the item in the second one

**Comment by d4rken** [comment]
I've never seen that before.
What device+ROM is this?

Could this be "theme" related?

**Comment by gagabs** [comment]
It's a Samsung Galaxy On7 (SM-G600FY), Android 6.0.1 stock.

Not sure, it appears with or without themes.

I can try to find the owner if you tell me how to. I have the Magisk root.

**Comment by d4rken** [comment]
What happens if they are deleted?
Do you need to reboot? Does it cause errors?
Are they recreated?

**Comment by d4rken** [comment]
Not enough infos, reopen if still relevant.
