### ISSUE TITLE
Explorer launching with launcher shortcut

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#187]
Originally reported by: **Bitbucket: [avamander](http://bitbucket.org/avamander), GitHub: [avamander](http://github.com/avamander)**

----------------------------------------

Could you please make it possible to launch SD Maid's built-in file explorer by tapping a launcher shortcut?

----------------------------------------
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/188

**Comment by Avamander** [comment]
Yes.

**Comment by d4rken** [comment]
http://stackoverflow.com/questions/16873256/how-to-add-shortcut-to-home-screen-in-android-programatically

**Comment by d4rken** [comment]
Done
