### ISSUE TITLE
Clutterreport: /storage/F4C4-0E01/Android/data/com.lge.hiddenmenu (FP)

### ISSUE THREAD

**Issue by sewII** [d4rken/sdmaid-public#1871]
### Target
Target: `/storage/F4C4-0E01/Android/data/com.lge.hiddenmenu`
Prefix-free: `com.lge.hiddenmenu`
Path-prefix: `/storage/F4C4-0E01/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `LG System Resources`
Packagename: `com.lge`
Version: `3.0.0 (300)`

### Current owners
None

### SD Maid
Version: `4.10.13 (41013)`

### Device
Fingerprint: `lge/sf317_trf_us_vzw/sf317:7.0/NRD90U/173191700b287:user/release-keys`

### Comment
`unknown source`

**Comment by d4rken** [comment]
There is an actual app with that packagename, AFAIK this is not a false positive but a real corpse.

https://www.hybrid-analysis.com/sample/b28fcf9601c2356e97779b498e1ca6a1d836419622734985718448f3081d9589?environmentId=200
