### ISSUE TITLE
Очень прошу вас сделать по-другому цвет, если это возможно светло-серый градиент в режиме планшета, эта дисгармония очень раздражает. 😱😢

### ISSUE THREAD

**Issue by SergeyAquarius** [d4rken/sdmaid-public#1878]
Good afternoon, Matthias!
Matthias, my friend, regret my eyes...
Very much I ask you to make differently color over if it is possible this 
light gray gradient in tablet mode, this disharmony is very annoying. 😱😢
![screenshot_2018-07-20-10-29-03-01](https://user-images.githubusercontent.com/41520018/43038544-a0544256-8d23-11e8-8ea0-b97822beaf65.jpeg)

**Comment by d4rken** [comment]
![2018-07-25 16 43 45](https://user-images.githubusercontent.com/1439229/43208162-1430b246-902a-11e8-8c4a-917500e4a492.png)

**Comment by SergeyAquarius** [comment]
Теперь это отлично! Большое спасибо и мой глубокий поклон, Маттиас ...)

**Comment by SergeyAquarius** [comment]
Now it is excellent! Many thanks and my deep bow,  Matthias...)
