### ISSUE TITLE
AppCleaner does not show field size correctly

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#1886]
The AppCleaner tool does not show the size of items bigger than 99MB in detail view.
![screenshot_20180723-190142_sd maid](https://user-images.githubusercontent.com/7258858/43094638-6edd6de0-8eab-11e8-99c3-033986a0a838.jpg)

**Comment by d4rken** [comment]
The bounding box is cutting it off. Hm increasing the size would break MD specs.... Could decrease the font?

![2018-07-25 13 19 13](https://user-images.githubusercontent.com/1439229/43198017-605f791c-900d-11e8-9411-2a0218bdc352.png)

**Comment by d4rken** [comment]
bugfix hatrick 😁 👍 

![lgtm](https://user-images.githubusercontent.com/1439229/43198450-feff3296-900e-11e8-88e7-c754c21a0e31.PNG)
