### ISSUE TITLE
[Suggestion] Add option to skip unity game files

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#1887]
A lot of games now days download game assets afterward an store them in /sdcard/Android/data/com.example/files/UnityCache/Shared/ . I understand that you can redownload them and they can be considered junk if you desperately need more storage space but for a Samsung S7 User with more than enough storage and slow internet it is annoying to always get them cleared in AppCleaner. Because of that I would suggest adding a feature to skip those files while cleaning.

**Comment by SuperSandro2000** [comment]
Desirable cache? Maybe downloaded app data? Disable it by default but the option would be good for people that have the space.

**Comment by d4rken** [comment]
Hm difficult.

* Cache (exists)
* Hidden caches (exists)
* Offline cache (exists)
* Desirable cache
* Downloaded app data

Difficult to say where one put files, all similar, possibly overlapping.

Might fit the "Offline cache" filter best (currently requires experimental features to be enabled).

**Comment by SuperSandro2000** [comment]
I didn't even know that menu existed there. Offline caches sounds good and would fit that category.

**Comment by d4rken** [comment]
> I didn't even know that menu existed there.

Why? Icon not recognizable?

**Comment by SuperSandro2000** [comment]
No. It is just that corpse cleaner is in settings and it is inconsistent with that

**Comment by d4rken** [comment]
The CorpseFinder filters are things you don't change very often, while SystemCleaner and AppCleaner filters might be changed very often just to see what each filter finds. Especially in AppCleaner where all filter results are merged/grouped "per app".

But yeah it is inconsistent and it annoys me a lot. It will be changed as soon as I find time for some more refactoring of the settings code.

**Comment by d4rken** [comment]
Also made the offline cache filter case-insensitive which it wasn't before.
