### ISSUE TITLE
Add ZArchiver cache to AppCleaner

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#1889]
ZArchiver copies archives or files it extracts and shows in the app to this directory ``/storage/emulated/0/Android/data/ru.zdevs.zarchiver/files`` and provides no option for the user to delete those. The directory does not contain any other files and should be considered a cache folder.

**Comment by SuperSandro2000** [comment]
I don't understand your question. The files are not hidden.

**Comment by d4rken** [comment]
The AppCleaner has multiple filters the user can choose from, I was asking under which of those filters you would put this.

**Comment by SuperSandro2000** [comment]
Hidden caches probably.
And why is this menu not visible under settings?

**Comment by d4rken** [comment]
```
HiddenFilterTest.testZArchiver PASS
```

lgtm
