### ISSUE TITLE
Clutterreport: /storage/emulated/0/bmwgroup/.nomedia (new)

### ISSUE THREAD

**Issue by allio1187** [d4rken/sdmaid-public#1891]
### Target
Target: `/storage/emulated/0/bmwgroup/.nomedia`
Prefix-free: `bmwgroup/.nomedia`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Pandora`
Packagename: `com.pandora.android`
Version: `1807.1.2 (18071202)`

### Current owners
None

### SD Maid
Version: `4.11.4 (41104)`

### Device
Fingerprint: `Verizon/jfltevzw/jfltevzw:5.0.1/LRX22C/I545VRSGPL1:user/release-keys`

**Comment by d4rken** [comment]
Can you elaborate on this?

**Comment by d4rken** [comment]
https://forums.androidcentral.com/samsung-galaxy-s5/641548-not-sure-what.html

https://forums.androidcentral.com/samsung-galaxy-s6/641379-pandora-app-creating-album-my-gallery.html

**Comment by d4rken** [comment]
https://android.stackexchange.com/questions/136239/com-pandora-android

**Comment by d4rken** [comment]
Seems this is a shared dir.

Pandora owns `bmwgroup/com.pandora.android` but spotify would own `bmwgroup/com.spotify.music`.

Don't despair though SD Maid supports dynamic clutter matching :)
