### ISSUE TITLE
Track `/storage/emulated/0/KakaoTalk/cookie`

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1902]
- [ ] Track ownership as `com.kakao.talk`

- [ ] Match hidden caches or webview caches.

```
/storage/emulated/0/KakaoTalk/cookie
com.kakao.talk
```

**Comment by gaya4** [comment]
Kakaotalk is a Korean chat application; most similar to Telegram or maybe Whatsapp. Pictures can be shared and group chats can be started, stickers are also included. Pictures are stored locally and on the servers. They will, as far as I know, be kept locally indefinitely but deleted from their servers after some months (my closest guess is 6 months).
If cache is deleted, the locally stored gallery might loose its content.

**Comment by d4rken** [comment]
This directory is named `cookies` if KakaoTalk is a chat app, what kind of cookies are these?

**Comment by gaya4** [comment]
Correction on the storage period. I deleted the <contents> directory. The chats now show no pictures older than 2 weeks ("storage time expired").

The cookies directory contains only 1 file. A legit cookie with 150byte. It seems like it doesn't change. But I just deleted some other directory and restarted the app. I will report if I notice changes.

**Comment by d4rken** [comment]
@gaya4 Was there any issue with deleting it?
