### ISSUE TITLE
Investigate `/storage/emulated/0/Android/data/org.kman.aquamail/files/parts`

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1905]
Potential hidden caches.

```
/storage/emulated/0/Android/data/org.kman.aquamail/files/parts
```

**Comment by gaya4** [comment]
Mailprogram.
The `parts` directory contains some mail parts (readable), mostly attachments, pdf, xlsx andplenty of txt files of which I have no idea where they came from but they contain PGP signatures.
Also there is expected content like those pictures people seem to love in their signatures ("reach us on twitter...").

Side note:
Files also contains a directory `contentCopy` which contains in my case files only. As far as I can see that, those are attachments only from sent emails.

**Comment by gaya4** [comment]
I deleted both directories and checked a mail that I sent with two attachments. The first attachment cannot be displayed but is downloaded from the server and is then displayed. I did not check the second attachment.

After downloading, Aquamail created the parts directory again with both attachments and tagged the directory with the .nomedia file.

**Comment by d4rken** [comment]
Currently not planing to implement this due to potential downsides, risk to high.
