### ISSUE TITLE
Wechat cache clean

### ISSUE THREAD

**Issue by zasdf** [d4rken/sdmaid-public#1907]
Hi, 

The Wechat cache files also need to be cleaned up. For example, the Moments, audio and video cache files in Wechat.
I know the Moments file location, it takes about 2 G space on my phone. 
The Moments file is located at device/storage/emulated/0/tecent/"a long number and letter"/sns

If others have the similar issue, please also help to provide some feedback. 

Thanks,

**Comment by d4rken** [comment]
Can you provide some screenshots from SD Maids explorer?

There is also an option in SD Maids Explorer (see settings) called "Save directory structure" it will produce a text file that contains all the pathes.

Try to use that on the tencent folder.

**Comment by ya8sa** [comment]
Hi,
Folder structure list is attached.
I uses user filter of system cleaner for XLOG and CheckResUpdate folder.
Old files are remained, so age setting  of rule is applied in the filter.
No affects are found in app operation.
Regards,

[pathdump#_storage_emulated_0_tencent#1532987182448.txt](https://github.com/d4rken/sdmaid-public/files/2243052/pathdump._storage_emulated_0_tencent.1532987182448.txt)

**Comment by d4rken** [comment]
https://github.com/mzlogin/CleanExpert/blob/master/docs/data/user_cache_wechat.md

**Comment by d4rken** [comment]
* https://translate.google.de/translate?hl=de&sl=zh-CN&u=http://www.sohu.com/a/158426578_172722&prev=search
* https://translate.google.de/translate?hl=de&sl=zh-CN&u=https://zhidao.baidu.com/question/750591443673464532.html&prev=search
* https://github.com/mzlogin/CleanExpert/blob/master/docs/data/user_cache_wechat.md

**Comment by d4rken** [comment]
If anyone can help me test this, please send a mail to support@darken.eu and mention this ticket :+1:

**Comment by d4rken** [comment]
WeChat is a dirty app :grin: and cleaning has been split up between 3 filters:

Hidden caches filter

```
			"^(?>tencent\\/MicroMsg\\/CheckResUpdate\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/WebviewCache\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/Cache\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/CDNTemp\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/FailMsgFileCache\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/diskcache\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/)([0-9a-z-]{32}temp[\\d]{13})$",
			"^(?>tencent\\/MicroMsg\\/[0-9a-z-]{32}\/brandicon\/)(?>.+)",
			"^(?>tencent\\/assistant\\/cache\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/assistant\\/tmp\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/assistant\\/thumbnailcache\\/)([\\W\\w]+?)$",
			"^(?>VideoCache\\/com.tencent.mm\\/)([\\W\\w]+?)$"
```

Bugreporting filter

```
			"^(?>tencent\\/MicroMsg\\/crash\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/xlog\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/locallog\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/watchdog\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/failmsgfilecache\\/)([\\W\\w]+?)$",
			"^(?>tencent\\/MicroMsg\\/)(FTS5IndexMicroMsgInfo.txt)$",
			"^(?>tencent\/MicroMsg\/[0-9a-z-]{32}\/logcat\/)(?>.+)"
```

and a new WeChat filter just for sent/received files in chats and moments

```
                        "^(?>tencent\\/MicroMsg\\/[0-9a-z-]{32}\\/sns\\/)(?>.+)$",
                        "^(?>tencent\\/MicroMsg\\/[0-9a-z-]{32}\\/video\\/)(?>.+)$",
                        "^(?>tencent\\/MicroMsg\\/[0-9a-z-]{32}\\/image2\\/)(?>.+)$",
                        "^(?>tencent\\/MicroMsg\\/[0-9a-z-]{32}\\/voice2\\/)(?>.+)$"
```
