### ISSUE TITLE
WhatsApp/.Shared/?

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1924]
Hm?

```
WhatsApp/.Shared/a+eoHzX3bgPc8XdQjH7UcWPQIE4YGhFQyZZZi1KWvfs=.tmp.chck
```

**Comment by SuperSandro2000** [comment]
Send images, cropped image data, saved profile pictures, etc. I can send you some examples per mail I'd you want.
Crop files:
 ````
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, progressive, precision 8, 1600x778, frames 3
````
tmpt file:
````
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 96x96, frames 3
````
tmpp file:
````
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 640x640, frames 3
````
![screenshot_20180729-211622_solid explorer](https://user-images.githubusercontent.com/7258858/43370295-c2586ab0-9374-11e8-8b81-091f6911d300.jpg)

**Comment by aamadorj** [comment]
I constantly delete the files at this path (WhatsApp/.Shared/) with no side effects, AFAIK.

**Comment by SuperSandro2000** [comment]
My guess is that WhatsApp cleaned them manually sometimes or otherwise that folder would overflow for me

**Comment by d4rken** [comment]
https://www.quora.com/Is-it-ok-to-delete-the-shared-folder-in-WhatsApp

https://www.quora.com/What-is-the-shared-file-present-in-the-WhatsApp-folder
