### ISSUE TITLE
Bug: Database tool does not report storage gained after optimization

### ISSUE THREAD

**Issue by bglover** [d4rken/sdmaid-public#1926]
### What happened?
Optimize the database of an app, reports +/- 0B

### What did you expect to happen?
See the exact number of bytes saved.

### How can I reproduce the issue?
Go to database tool, click the (i) info button to see the size of the database. Optimize that app, click the info button again. It shows a smaller size, but the main database screen shows +/- 0B

### Comments
Here are screenshots before and after optimizing the f-droid app: https://photos.app.goo.gl/eoRetdNoFgpcDMFx7

### SD Maid
Version: `4.11.5 (41105)`
Unlocker: `4.3.1 (40301) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `OnePlus/OnePlus5/OnePlus5:8.1.0/OPM1.171019.011/06131715:user/release-keys`

**Comment by d4rken** [comment]
Possibly a rounding issue? Does this only happen for small differences?

**Comment by bglover** [comment]
I don't think so. In this example (https://photos.app.goo.gl/CyAn2mD2KmeENN2t9), the offline database lost more than 100kB and it didn't show.
