### ISSUE TITLE
Apps not working after freeze / delete of other apps with SD Maid

### ISSUE THREAD

**Issue by Melissengeist** [d4rken/sdmaid-public#1944]
Hi there,

I experienced something strange: I updated my phone (Oneplus 3t, TWRP 3.2.3, rooted with Magisk, now on OOS 5.0.4) and - as usual - used SD Maid to freeze or completely delete some apps (most Google apps, Talkback, Oneplus community). Out of the blue other apps did not work any more (Simple calender, Firefox clear, K-Mail, maybe more, not tested), apps could not start or were closed repeatedly. Never had that problem before.
Is this a know problem?

BR

**Comment by Melissengeist** [comment]
sorry, I restored my backup when I realized that it was probably SD Maid, so system log no longer available to the issues.

Nope. Deleted YouTube and Android Pay. Tested this morning, same result

**Comment by d4rken** [comment]
¯\\\_(ツ)_/¯

I'd need the error messages from the crashing apps and a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log) of what SD Maid uninstalled to look into this.

**Comment by d4rken** [comment]
Not enough info available.
