### ISSUE TITLE
Clutterreport: /storage/emulated/0/.collectorConfig/.collectorGlobal (new)

### ISSUE THREAD

**Issue by branne1220** [d4rken/sdmaid-public#1952]
### Target
Target: `/storage/emulated/0/.collectorConfig/.collectorGlobal`
Prefix-free: `.collectorConfig/.collectorGlobal`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `AASAservice`
Packagename: `com.samsung.aasaservice`
Version: `5.0 (5)`

### Current owners
None

### SD Maid
Version: `4.11.6 (41106)`

### Device
Fingerprint: `samsung/trltexx/trlte:6.0.1/MMB29M/N910FXXU1DQL2:user/release-keys`

**Comment by d4rken** [comment]
Unclear.

Also been mentioned in #1699 and #1698

Why do you think this app creates this folder?
