### ISSUE TITLE
Clutterreport: /storage/emulated/0/.analytics/7F7023B6CEC7CDED.data (new)

### ISSUE THREAD

**Issue by josemnuel5012** [d4rken/sdmaid-public#1954]
### Target
Target: `/storage/emulated/0/.analytics/7F7023B6CEC7CDED.data`
Prefix-free: `.analytics/7F7023B6CEC7CDED.data`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Videoder Video Downloader`
Packagename: `com.rahul.videoderbeta`
Version: `14.2 (135)`

### Current owners
None

### SD Maid
Version: `4.11.6 (41106)`

### Device
Fingerprint: `HUAWEI/FIG-LX3/HWFIG-H:8.0.0/HUAWEIFIG-LX3/108(C25):user/release-keys`

**Comment by d4rken** [comment]
How did you come to this conclusion?
