### ISSUE TITLE
Clutterreport: /storage/emulated/0/Flowdia Demo (new)

### ISSUE THREAD

**Issue by atmouse-** [d4rken/sdmaid-public#1957]
### Target
Target: `/storage/emulated/0/Flowdia Demo`
Prefix-free: `Flowdia Demo`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Flowdia Lite`
Packagename: `com.bezapps.flowdiademo`
Version: `1.3.14 (103142)`

### Current owners
None

### SD Maid
Version: `4.11.6 (41106)`

### Device
Fingerprint: `Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V9.2.3.0.OCAMIEK:user/release-keys`

**Comment by d4rken** [comment]
`com.bezapps.flowdia` too
