### ISSUE TITLE
Bug: Trush button in storage analyzer

### ISSUE THREAD

**Issue by ya8sa** [d4rken/sdmaid-public#1959]
### What happened?
Trush button appears bottom right

### What did you expect to happen?
Refresh button should appear when cancelled

### How can I reproduce the issue?
Long press file or folder, then push back button for cancel

### Comments
However pressing button operate as refresh normally

### SD Maid
Version: `4.11.6 (41106)`
Unlocker: `4.3.1 (40301) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/SC-04J/SC-04J:8.0.0/R16NW/SC04JOMU1BRG6:user/release-keys`

**Comment by d4rken** [comment]
👍  can reproduce it, good catch.
