### ISSUE TITLE
Request: Display info in storage analyzer

### ISSUE THREAD

**Issue by ya8sa** [d4rken/sdmaid-public#1960]
### What should the feature do?
Same format like as explorer, time stamp or text wrapping

### When/How would you use it?
Check  unknown file by size or time stamp

### SD Maid
Version: `4.11.6 (41106)`
Unlocker: `4.3.1 (40301) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/SC-04J/SC-04J:8.0.0/R16NW/SC04JOMU1BRG6:user/release-keys`

**Comment by d4rken** [comment]
I could add the modification date to the info dialog, would that help you?

There is not much space in the 2 line items from the StorageAnalyzer UI.

Previous updates of SD Maid had larger lines, but users complained that they prefered a more compact UI for the StorageAnalyzer.

**Comment by ya8sa** [comment]
Understood compact UI, and agree to date in info dialog.
Thanks for the improvement.
