### ISSUE TITLE
Clutterreport: /storage/6BC3-1813/Downloads (new)

### ISSUE THREAD

**Issue by lickawitch** [d4rken/sdmaid-public#1971]
### Target
Target: `/storage/6BC3-1813/Downloads`
Prefix-free: `Downloads`
Path-prefix: `/storage/6BC3-1813/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `6.30.11.1 (63001101)`

Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `7.0 (24)`

### Current owners
None

### SD Maid
Version: `4.11.6 (41106)`

### Device
Fingerprint: `lge/elsa_tmo_us/elsa:7.0/NRD90M/1814810049f4f:user/release-keys`

**Comment by SuperSandro2000** [comment]
By default the vanilla AOSP downloads manager does not download to the SD card. Are you using a third-party app that does that? If yes I would suggest giving that app the folder.

**Comment by d4rken** [comment]
AFAIK the AOSP downloader uses `<internalsd>/Download`  (without the trailing `s`).

Closing due to unclear.
