### ISSUE TITLE
WeChat cannot run when the database is cleaned up

### ISSUE THREAD

**Issue by mb2014happy** [d4rken/sdmaid-public#1973]
Hello Darken,
If inscribe, WeChat cannot run when the database is cleaned up.
The package name of WeChat is com.tencent.mm .
Hope to fix it in the next version.

Thanks,
Marike

**Comment by d4rken** [comment]
https://www.reddit.com/r/sdmaid/comments/9b8s5o/app_crashes_continuously_after_running_sdmaid/
