### ISSUE TITLE
Nested empty directories require multiple scans

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#201]
Originally reported by: **Bitbucket: [avamander](http://bitbucket.org/avamander), GitHub: [avamander](http://github.com/avamander)**

---

SystemCleaner often deletes the entire contents of a folder and on the second run, it deletes the folder it left empty. My suggestion is that you'd make a dialogue pop up saying something like "Deeper cleaning?" and then rescans using only the empty folder filter (If there is no performance loss in running other filters then that would be fine too). And automatically deletes what has been found. That would result is much more effective (altho slower) cleaning.

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/202

**Comment by d4rken** [comment]
It's a caveat of how the current design works. It scans all files and directories and filters according to each files attributes.
From just the attributes of a single directory, we can't detect nested empty directories.

I don't see a trivial solution for this.
Current options I see:
* We could start additional scans per directory to determine if they are nested, but that would mean an additional scans for every non empty directory. Which makes the already long scan a lot longer.
* We could try to pass each filter all files that have been scanned so far, but this would cause memory issues because we can no longer through files away that have been scanned but didn't fit a filter.
* Just rescan and redelete until the filter comes up empty or after X scans, but this would still not be much faster even if we only scan with one filter active, as the what takes so long is mostly the scan.

I'm not a fan of any of those solutions.

**Comment by Gitoffthelawn** [comment]
1. If directory files = 0, delete directory
  2. If delete directory, traverse one level up tree, then go to *Step 1*

I'm guessing it can't be that simple due to the existing design?

**Comment by Gitoffthelawn** [comment]
Hmmm... the current design does make it a bit of a challenge.  I almost wonder if finding empty folders should be a separate, possibly recursive, routine within the cleaner module.

The big drawback to the current implementation is that it makes SD Maid, which is an excellent product, look buggy.  The user thinks they are deleting all empty folders, but then if they validate the results, they see that plenty of empty folders still exist.

**Comment by d4rken** [comment]
> within the cleaner module

What module?

Currently on the CorpseFinder Filter get to execute their own searches.
In all other tools a global search is executed and filters then just work on the results (which is more efficient than having each Filter execute their own searches).
This really only fits the SystemCleaner in terms of scope.

"Recursive Empty directories" is just a special because we are looking for items whose attributes will be affected by a future deletion.

> The user thinks they are deleting all empty folders, but then if they validate the results, they see that plenty of empty folders still exist.

Well they ARE deleting all empty folders, it's just that the deletion creates new empty folders :grin:.


The dirty solution would be to just add some xtra code outside of the filter, into the core systemcleaner routine that checks if the empty directories filter is active and then does extra scans.
Then we need a routine that can determine nested empty directories.

**Comment by Gitoffthelawn** [comment]
> What module?  ... But the act of deleting empty directories really only fits the SystemCleaner in terms of scope/responsibility.

I agree... it's within the scope of SystemCleaner.

> Well they ARE deleting all empty folders, it's just that the deletion creates new empty folders :grin:.

LOL :grin::grin::grin:

The *dirty* solution you recommend will probably result in the best *cleaning*. :+1:

**Comment by d4rken** [comment]
> The dirty solution you recommend will probably result in the best cleaning. 

But prone to bugs and harder to maintain.

**Comment by Gitoffthelawn** [comment]
Maybe a functional compromise is in order.  For my use, I prefer it to be 100% accurate for `/storage/emulated/*` and `/storage/external_SD/*`.

Perhaps just having a dedicated routine to handle those two locations would be a fair compromise between speed and getting the job done.

**Comment by d4rken** [comment]
Specific pathes are not a concern anyways. Since SD Maid v4 all tools only work with abstract location types i.e. Location.SDCARD or Location.PUBLIC_DATA. Concrete pathes for these Locations are determined during first load (which is what that takes a few moments).

I don't like this because it makes the architecture and responsibilities within SD Maids modules "unclean". An app has to be beautiful on the inside and outside :grin:.

I have not ruled this out and will think a bit about it.

**Comment by Gitoffthelawn** [comment]
I agree!  Sounds good Matthias. :+1:

**Comment by Vankog** [comment]
I just wanted to point out this recurring issue, too and found this issue.

I understand that you want to solve this recursive issue in an elegant way within the filtering logic:

> It goes like this:
> 
> Start scan
> Load all activate filters
> Load all public storage, private storage and cache locations from SD Maids StorageManager
> For each location start a search that calls back for each file/directory that is found
> For each item:
> 
> Check if it matches an exclusion, if so discard
> Iterate through all loaded filters by giving each filter the item (file/dir).
> If a filter matches an item the will say "I want that", then this item is "matched" and will be added to the filter
> If no filter matched an item it is discarded too.

Well, There is logically no solution that works in one run. The way I see it is by executing a new custom scan as part of the deletion task:
1. There is no way in foretelling what the user really deletes in the end after a scan. So you have to rely solely on the deletion-task to gather information about what paths were actually cleaned. So:
1. If the Empty Dir filter is active: 
    1. Wait for when deletion is done. 
    1. Now you have all affected paths with file/dir deletions in a list. No need to rescan at all. Just reuse what is already known.
    1. If there are >0 affected paths:
        1. Check if they exist. If not: 1-up the path unless root
        1. Feed these paths again just through the Empty Dir filter.
        1. Trigger deletion automatically.
        1. goto 2.i.
    1. else: done

The feedback loop should be quite fast, because we don't have to rescan, just double checking the results. You could also offer this feedback loop as a dialog after deletion: "Check for new empty directories? - Yes, All, No, I like Cookies..."

I know its not pretty in the current architecture, but honestly I don't see any way around this, because you really have to know what paths are actually affected by the deletion.

And it really is annoying to hit scan over and over again just for the chain of empty directories, which often are quite long. Especially because a full rescan is done all the time taking several minutes.

**Comment by d4rken** [comment]
I've added a recursive method that starts from within the filter itself. It traverse the file tree and if all children are empty dirs then it will consider the dir we started on also an empty dir.

The exclusions are applied after filtering so this shouldn't cause any issues.

This will only work for files accessible without root and without SAF, so just basic File API, but better then nothing.
