### ISSUE TITLE
Bug: SD Maid does not clean - says su permission denied

### ISSUE THREAD

**Issue by sanjayen** [d4rken/sdmaid-public#2010]
### What happened?
SD Maid used to clean app cache but with this new version it fails saying su permission is demied. I use Magisk and have always provided root access to SD Maid.

### What did you expect to happen?
SD Maid should clean all app cache

### How can I reproduce the issue?
Install older version of SD Maid and give su permission using Magisk 17.1. Upgrade to the latest beta version and SD Maid will not clean app cache saying su permission denied.

### Comments
Please do let me know what other reports will you require to recreate this bug.

### SD Maid
Version: `4.11.8 (41108)`
Unlocker: `4.3.2 (40302) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.2.0.NAAMIEB:user/release-keys`

**Comment by d4rken** [comment]
The latest version did not change root related code in any way. This is likely just a hickup with the Superuser app. This sometimes tends to happen during updates, but it's not something I can solve within SD Maid.

Remove SD Maid from the superuser app and reboot, then try again.

If that does not help, please post a debug log so I can see what exactly is going on.

This may also be an issue with toybox/busybox as your signature says that SD Maid has root...
What does SD Maids Overview page show?

**Comment by sanjayen** [comment]
Thank you @d4rken for the explanation. I did as you suggested and SD Maid works perfectly now.

A suggestion - can you add an option to check if su permission is available to SD Maid or not? Flashify has a similar option using which you can check for access from within the app.

Closing this ticket as it was a not a bug. Keep up the good work.
