### ISSUE TITLE
Switch to interactive root shell

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#2018]
SD maid would run a bit faster if you would use an interactive root shell and not doing 7 root requests to launch app control.

**Comment by SuperSandro2000** [comment]
When I simply launch the app control in SD Maid the app does a total of 7 root requests to magisk. Maybe decrease them cause each su request is an intensive operation.

**Comment by d4rken** [comment]
Is it only the first time on a cold start?
Some calls may come from SD Maids initial setup routines.
Reusing shells across unrelated modules is possible but makes multitasking
more bug prone.

I'll have to look into each call.

Sandro Jäckel <notifications@github.com> schrieb am So., 23. Sep. 2018,
12:32:

**Comment by d4rken** [comment]
Base setup

1. RootContext, shell launch is part of su test
2. Binary setup, shell is launched once for all applet tests to know if they work with root
3. Storage setup, one shell for all storage modules to get their data
4. Storage setup, private data module starts another shell  :question: 

AppControl

5. Loading process data, e.g. running apps
6. Perform a check for hidden apps when loading app data, check for instant apps
7. Another check for hidden apps :question:

**Comment by d4rken** [comment]
3 is a basic command shell, but 4 is a filereader that internally uses a root shell too.

7 is the actual loading of installed apps, 6 is actually part of 5, because to load running apps we also need to know the installed apps.

**Comment by d4rken** [comment]
I think I can remove 4, by reusing 3's shell.

I'll have to look more into whether we can do 7 first, then reuse it in 5 and 6.

I've started on removing 4, but it's more complicated than I thought. Too exhausted for that now I want to release this beta. Pushing this to the next update :sweat_smile:.

**Comment by d4rken** [comment]
Eliminated 4 by reusing 3's shell.

Also eliminated 6 by ensuring 5 runs after 7. With 5 will reuse the cached data from step 7, so no extra shell will be launched.

7 -> 5 :+1: 

The rest can't easily be eliminated without breaking seperation of concerns between the different parts of SD Maid. It would also get us into concurrency hell when multiple tools are running in parallel.
