### ISSUE TITLE
{Error: malformed database schema (MmapStatus)-near"(": syntax error}

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2042]
> When I run QuickAccess and under Databases I get:
>1 skipped
> SyncData.sqlite
> Chrome
> {Error: malformed database schema (MmapStatus)-near"(": syntax error}

```
=== Device info ===
Install ID: b400912c-4105-4c22-b2c1-8c9508d243e5
ROM: google/angler/angler:8.1.0/OPM5.171019.019/4619337:user/release-keys/en_GB
SD Maid: 4.11.9[41109]
Unlocker: 4.3.2[40302]
Root: true
Storage: /storage/emulated/0 (SAF-match=false)
```

**Comment by d4rken** [comment]
Chrome's SQL version is newer then what SD Maid has, so we would have to update SD Maids sql binaries.

Or introduce version checking into the binary deployment system for sql binaries (not trivial).

**Comment by SuperSandro2000** [comment]
According to this post/thread it shouldn't be that hard https://stackoverflow.com/a/9646399/4446318.
I am only worried about that maybe performance could be a problem

**Comment by d4rken** [comment]
Useful:

https://github.com/EXALAB/sqlite3-android
