### ISSUE TITLE
Do not distinguish hiragana/katakana/half width katakana for search

### ISSUE THREAD

**Issue by azumukupoe** [d4rken/sdmaid-public#2043]
Japanese has different characters that means the same
hiragana あいうえお
katakanaアイウエオ
half width katakana ｱｲｳｴｵ

**Comment by d4rken** [comment]
I'm not sure what you mean, can you elaborate?

Is this a translation issue?

**Comment by d4rken** [comment]
I understand your point, I just don't understand this means for SD Maid.

**Comment by azumukupoe** [comment]
Basic Japanese keyboards outputs hiragana, the basic characters, but searching in hiragana would not find apps with katakana name without converting them.

**Comment by d4rken** [comment]
Understanding the that certain characters are equal in certain languages is outside of SD Maids scope.

Do you know a project that supports this? Does Windows or Linux support this?

**Comment by azumukupoe** [comment]
Yes it does on Windows

**Comment by d4rken** [comment]
Have you seen this in an Android app?

For which tool in SD Maid do you want this feature?

What problem of yours would it solve?

**Comment by d4rken** [comment]
If there is a ready library for this I could maybe do something, I don't think this is supported by Android directly.

 Do you know an app that can do this? The. We could ask the developer for some help.
