### ISSUE TITLE
Updated Material Design

### ISSUE THREAD

**Issue by Rakleed** [d4rken/sdmaid-public#2059]
Make apps in updated material design. Examples of applications with updated design: Google Photos, Google Phone, Google Fit, Google Contacts, Google Calendar, Android Messages.

https://material.io

**Comment by d4rken** [comment]
Please be more specific, are you looking for changes to specific elements?

**Comment by Rakleed** [comment]
@d4rken a lot of empty space, the use of Google Sans font, transparent elements, rounded edges, the active use of white, the acquisition of minimalism, the shadows do not play a key role in the positioning of design elements.

**Comment by Rakleed** [comment]
@d4rken why did you close the issue? So you do not want to improve the design?

**Comment by d4rken** [comment]
I do, but the ticket is too unspecific, it's like "Make everything better". There would never be a moment when the issue is finished.
