### ISSUE TITLE
Bug: I bought this app under marescamichael2@gmail.com

### ISSUE THREAD

**Issue by BigMike86** [d4rken/sdmaid-public#2069]
### What happened?
No i lost control of my original account now my gmail is mikeym05301986@gmail.com

### What did you expect to happen?
Im hoping to get the full (version) back or full beta version back please because i already paid for it and i am low income thank you! Mike!

### How can I reproduce the issue?
Just release the complete version to mikeym05301986@gmail.com throught the google play store my numbrr is 9096768176 thanks.

### Comments
Great app i also use CCleaner but i dont subscribe as to where your app is a 1time only fee.

### SD Maid
Version: `4.11.9 (41109)`
Unlocker: ` (0) (false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `TCL/A574BL/BUZZ6T4GTFUMTS:7.1.1/NMF26F/vG5H:user/release-keys`

**Comment by d4rken** [comment]
Please contact support@darken.eu for Google Play related issues.
