### ISSUE TITLE
Clutterreport: /storage/emulated/0/default.prop (new)

### ISSUE THREAD

**Issue by Lobesitdoll** [d4rken/sdmaid-public#2081]
### Target
Target: `/storage/emulated/0/default.prop`
Prefix-free: `default.prop`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `AutoPreconfig`
Packagename: `com.sec.android.AutoPreconfig`
Version: `2.0.0 (1)`

### Current owners
None

### SD Maid
Version: `4.11.9 (41109)`

### Device
Fingerprint: `samsung/j2ltedo/j2lte:5.1.1/LMY47X/J200YDOU2ARC2:user/release-keys`

**Comment by Lobesitdoll** [comment]
Need patch

**Comment by d4rken** [comment]
Matching is not correct, unrelated.
