### ISSUE TITLE
App control listing empty

### ISSUE THREAD

**Issue by JonnyTech** [d4rken/sdmaid-public#2083]
When selecting categories `user` and `system` together, the list clears and no apps are displayed.

**Comment by d4rken** [comment]
This is by design as an app can not be both user and system app, it's either.

**Comment by JonnyTech** [comment]
The `categories` have check boxes. Usually a ticked box means show and empty box is do not show. So to show all apps that are not `frozen` then intuitively one would select `user` and `system` while unchecking `frozen`. Is my logic flawed or is the selection method counter-intuitive?

**Comment by d4rken** [comment]
> The categories have check boxes. Usually a ticked box means show and empty box is do not show. So to show all apps that are not frozen then intuitively one would select user and system while unchecking frozen. Is my logic flawed or is the selection method counter-intuitive?

In your system how would you filter such that only frozen system apps are shown?

**Comment by d4rken** [comment]
> Maybe break up the frozen category into frozen system and frozen user apps, but that may complicate things

Now I want to view only frozen user apps that have a boot receiver, how do I do that ;).

> and I would really need to see the code to make a better suggestion.

Why? It's not about the code.

> But back to the original issue: if there is a tick in both the system and user categories, why does that exclude all apps rather than include both categories?

I think I have explained that, because there is no app that is both a system app and a user app. I think your confusion comes from the label "categories", the ticks act more like filters, the more filters you add, the less results you get.

So what's the solution? Make it a RadioGroup and only allow one category at a time?

**Comment by d4rken** [comment]
Or we just change the label from "Categories" to "Filters" :laughing:

**Comment by JonnyTech** [comment]
> I think I have explained that, because there is no app that is both a system app and a user app. I think your confusion comes from the label "categories", the ticks act more like filters, the more filters you add, the less results you get.

By your logic, selecting `All items` should show nothing :)

> Or we just change the label from "Categories" to "Filters"

It's your decision

**Comment by d4rken** [comment]
> By your logic, selecting All items should show nothing :)

Yeah it doesn't seem to be a clear UI concept. If we stick with filters then "all items" should be replaced with a button that says "Clear filters" or something like that.

> Or we just change the label from "Categories" to "Filters"

I'm 50/50 currently, which concept is more useful to the user? Filtering is more powerful then just "categories", I think the main issue with the current system is the confusion about how it works. Do you think changing the label to "Filter" would have helped in your case?

**Comment by JonnyTech** [comment]
Not sure. My `user` box says 40 items, and `frozen` shows 4 items. If I select both then 4 are listed. But people might see both boxes ticked and expect 40. Regardless of wording, there are two scenarios:

- show all `user` apps **and** all `frozen` apps
- show all `user` apps that are (ie **filtered**) `frozen`

Maybe it needs two columns:

```
STATE             USER       SYSTEM
ALL               [ ]         [ ]
RUNNING           [ ]         [ ]
FROZEN            [X]         [ ]
BOOT              [ ]         [ ]
STOPPED           [ ]         [ ]
NO APK            [ ]         [ ]
```

Am I overthinking this? Please tell me to stop!
