### ISSUE TITLE
How to edit wiki pages?

### ISSUE THREAD

**Issue by JonnyTech** [d4rken/sdmaid-public#2095]
Can I request access to edit the [wiki](https://github.com/d4rken/sdmaid-public/wiki) as I have found an error but there is no edit option available?

**Comment by d4rken** [comment]
I don't think I can give access to only the wiki, it always includes the other files in the repo too.
Hm...

I could remove the restriction on the wiki, but I think the chance is high that people do stupid stuff, like random comments.

I'll think about what to best do, in the meantime, what's the error, I'll fix it for now.

**Comment by JonnyTech** [comment]
3x changes in bold:

Reset app
 
Returns the app to **its** install state. This will **delete** the apps data, but not the app itself. Similar to Clear data in the systems app settings, but it also includes extra app directories outside of default directories, that the system does not know about.

EDIT: The third change is that the period after the last word "directories" should be a comma - but markup does not let me change that without putting a space before it.

**Comment by d4rken** [comment]
Thank you. Fixed it.

I've looked a bit more into and it seems the permission system is all or nothing :-1: ?

A collaborator is allowed you to edit the wiki, committed files, issue tickets and comments. First 3 are obvious, the 4th one is weird. I actually never noticed that. Anyone can edit anyone's comment?

It's not about trusting you, which I do :smile:,  based on our history, but I'm a bit of a security fanatic so I start to wonder, what if your computer is breached etc... So it's something I would worry about. If you are looking to contribute a lot, then the benefits would outweigh the risks and I would add you as collaborator. I hope you can understand my concerns.

**Comment by JonnyTech** [comment]
Kudos for finding the right wiki page to edit, sorry for not specifying it earlier (rubbish at multitasking!).

Concerns acknowledged, and sorry for the trouble. I did not realise that such a simple question would open up so many issues.

As much as I like to contribute/collaborate to projects, finding the time is always difficult. I shall just report issues when I find them. Keep up the good work.
