### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android (FP)

### ISSUE THREAD

**Issue by Ktifgeo26** [d4rken/sdmaid-public#2103]
### Target
Target: `/storage/emulated/0/Android`
Prefix-free: `Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
~~Appname: `Система Android`~~
~~Packagename: `android`~~
~~Version: `8.0.0 (26)`~~

### SD Maid
Version: `4.11.9 (41109)`

### Device
Fingerprint: `HUAWEI/WAS-LX1/HWWAS-H:8.0.0/HUAWEIWAS-LX1/365(C10):user/release-keys`

**Comment by thongchai9532** [comment]
good

**Comment by thongchai9532** [comment]
good
