### ISSUE TITLE
Show system information along with app information

### ISSUE THREAD

**Issue by jidanni** [d4rken/sdmaid-public#2105]
We can see app information.  But  with a hundred apps  we are just missing  one more piece of information, the system ROM information.  See: https://forum.xda-developers.com/android/general/hard-to-copy-version-t3861718

**Comment by d4rken** [comment]
Which information are you looking for?

There is also some information in SD Maid's `Overview` page, I think this is not easily copy-able, but I could change that easily.

If you select apps in AppControl and from the context menu choose "Share", you get the option save/share a list of the selected apps which includes system information and apps versions, example:

```
### SD Maid - Share - 05.11.2018 23:35:05
Device: google/walleye/walleye:9/PPR1.180610.009/4898911:user/release-keys
___
1. Google Play Store (com.android.vending)
   * 12.3.19-all [0] [PR] 218276083 (81231900)
   * https://play.google.com/store/apps/details?id=com.android.vending
2. Google Pay (com.google.android.apps.walletnfcrel)
   * 2.77.219367708 (930147315)
   * https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel
3. SD Maid (eu.thedarken.sdm)
   * 4.11.10 (41110)
   * https://play.google.com/store/apps/details?id=eu.thedarken.sdm
```

**Comment by jidanni** [comment]
I was thinking about the stuff in the green rectangles on
https://gadgetguideonline.com/android/android-101/how-to-check-version-of-android-in-your-phone-or-tablet/

**Comment by d4rken** [comment]
Seems reasonable, I'll add it to Overview.
