### ISSUE TITLE
Include WhatsApp Business AppCleaner filter

### ISSUE THREAD

**Issue by MicaelJarniac** [d4rken/sdmaid-public#2127]
On the AppCleaner module, there are filters under "Specific" for WhatsApp files, like sent/received media and old backups, but these don't apply to WhatsApp Business.

**Packagename:**
- com.whatsapp.w4b

**Locations:**
- /data/user_de/0/com.whatsapp.w4b
- /storage/emulated/0/Android/data/com.whatsapp.w4b
- /data/app/com.whatsapp.w4b-[...]==
- /data/user/0/com.whatsapp.w4b
- /storage/emulated/0/WhatsApp Business

**Backups Location** (I believe):
- /storage/emulated/0/WhatsApp Business/Databases (files named "msgstore-[year]-[month]-[date].[id].db.crypt12" like "msgstore-2018-11-13.1.db.crypt12")

**Media Location**:
* /storage/emulated/0/WhatsApp Business/Media
  * /.Statuses
  * /WallPaper
  * /WhatsApp Business Animated Gifs
  * /WhatsApp Business Audio
  * /WhatsApp Business Documents
  * /WhatsApp Business Images
  * /WhatsApp Business Profile Photos
  * /WhatsApp Business Quick Reply Attachments
  * /WhatsApp Business Stickers
  * /WhatsApp Business Video
  * /WhatsApp Business Voice Notes

**Comment by d4rken** [comment]
I've taken my current "normal WhatsApp" test suit and generated the same one for the Business variant. Can you have  a look at the pathes and tell me whether they are the same?

E.g. file formats, ".nomedia" files.

```java
    @Test
    public void testWhatsBusinessAppSentFilter() {
        addDefaultNegatives();

        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Calls").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs").build());

        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Calls/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201402/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/201402/testfile").build());

        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/.nomedia").build());

        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video/Sent/testfile").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images/Sent/testfile").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio/Sent/testfile").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents/Sent/testfile").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/Sent/testfile").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/Sent/VID-20170330-WA0016.mp4").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/Sent/VID-20170330-WA0016.gif").build());

        checkCanidates(new WhatsAppSentFilter(getSDMContext()));
    }

    @Test
    public void testWhatsAppBusinessReceivedFilter() {
        addDefaultNegatives();

        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Calls").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs").build());

        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Calls/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents/Sent/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/.nomedia").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/.nomedia").build());

        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201347").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201547").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201405").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201540").build());

        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video/Sent/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images/Sent/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio/Sent/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents/Sent/testfile").build());
        addCandidate(neg().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/Sent/testfile").build());

        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Video/VID-20140118-WA0000.mp4").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images/IMG-20131129-WA0001.jpg").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Images/IMG-20140725-WA0000.jpeg").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio/AUD-20151012-WA0000.aac").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Audio/AUD-20151205-WA0000.m4a").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Documents/Something123123!§($).pdf").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201347/PTT-20131121-WA0000.3ga").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201547/PTT-20151118-WA0000.aac").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201405/PTT-20140129-WA0000.amr").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Voice Notes/201540/6e435ac2dbd60fa01deb42ab538a02d7.1.aac").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/VID-20170330-WA0016.mp4").build());
        addCandidate(pos().pkgs("com.whatsapp.w4b").locs(SDCARD).prefixFree("WhatsApp Business/Media/WhatsApp Business Animated Gifs/VID-20170330-WA0016.gif").build());

        checkCanidates(new WhatsAppReceivedFilter(getSDMContext()));
    }

    @Test
    public void testWhatsAppBusinessBackupsFilter() {
        addDefaultNegatives();

        addCandidate(Candidate.neg().pkgs("com.whatsapp.w4b").locs(Location.SDCARD).prefixFree("WhatsApp Business").build());
        addCandidate(Candidate.neg().pkgs("com.whatsapp.w4b").locs(Location.SDCARD).prefixFree("WhatsApp Business/Media").build());
        addCandidate(Candidate.pos().pkgs("com.whatsapp.w4b").locs(Location.SDCARD).prefixFree("WhatsApp Business/Databases/msgstore-2017-10-21.1.db.crypt12").lastModified(System.currentTimeMillis() - 86400000L - 1000).build());

        checkCanidates(new WhatsAppBackupsFilter(getSDMContext()));
    }
```

**Comment by MicaelJarniac** [comment]
I'm quite a little bit very confused, so I'll check what I think you asked me to check, but I'm not sure if that's actually what you want, so...

**Packagename:**
- com.whatsapp.w4b


**Locations:**
- /data/user_de/0/com.whatsapp.w4b
- /storage/emulated/0/Android/data/com.whatsapp.w4b
- /data/app/com.whatsapp.w4b-[...]==
- /data/user/0/com.whatsapp.w4b
- /storage/emulated/0/WhatsApp Business

* /storage/emulated/0/WhatsApp Business
  * /.Shared
    * A lot of files, most ending with ".chck"
    * Some ".jpg" files
    * Some image files with no extension
    * An image file named "tmpp" (49 kB) and another named "tmpt" (2.2 kB) with no extension, both appears to be the current profile photo
  * /.trash
  * /Backups
    * /chatsettingsbackup.db.crypt1
    * /stickers.db.crypt1
    * /wallpaper.bkup
  * /Databases
    * Files named "msgstore-[year]-[month]-[date].[id].db.crypt12"
    * /msgstore.db.crypt12
  * /Media
    * /.Statuses
      * Many ".jpg" files
    * /WallPaper
    * /WhatsApp Business Animated Gifs
      * /Private
        * /.nomedia
      * /Sent
        * /.nomedia
        * A few ".mp4" files
      * A few ".mp4" files
    * /WhatsApp Business Audio
      * /Private
        * /.nomedia
      * /Sent
        * /.nomedia
      * A ".m4a" file
    * /WhatsApp Business Documents
      * /Private
        * /.nomedia
      * /Sent
        * /.nomedia
      * A ".docx" file
    * /WhatsApp Business Images
      * /Private
        * /.nomedia
      * /Sent
        * /.nomedia
        * Many ".jpg" files
      * Many (MANY) ".jpg" and ".jpeg" files
    * /WhatsApp Business Profile Photos
      * A ".jpg" file
    * /WhatsApp Business Quick Reply Attachments
      * /.nomedia
    * /WhatsApp Business Stickers
      * /.nomedia
      * Many ".webp" files
    * /WhatsApp Business Video
      * /Private
        * /.nomedia
      * /Sent
        * /.nomedia
        * A few ".mp4" files
      * A few ".mp4" files
    * /WhatsApp Business Voice Notes
      * Folders named "[year][id]"
        * /.nomedia
        * Files named "PTT-[year][month][date]-WA[sequence].opus"
      * /.nomedia

Yes, I tried making a file tree here. I hope it helps. If it's not quite what was requested, then tell me and I'll then try to do it right.

One other thing, as you can probably notice, I described the folder structure for my own WhatsApp installation, so there may be folders missing for some features I don't use, or some folders may be empty for the same reason.

**Comment by MicaelJarniac** [comment]
Well, I do believe that deleting the /.Statuses is not a great idea, because that's where the Status lives, and by definition those should only last 24h, so they should automatically clean themselves, and if they get deleted, you won't be able to view them again although they've not officially expired. Also, those files are "hidden" from the system, meaning they don't show on galleries, and Google Photos also doesn't back them up. I'd leave that folder alone for it to do it's thing.

The /.Shared folder is mysterious for me. Most of the files inside show "4.1 kB (0 B)" as their size, and there are some images inside. I don't know what this folder is for, so I guess it'd be safer also skipping it and leaving it be until we're sure about what it's for.

My "Quick Reply Attachments" folder only has the ".nomedia" file inside, so it would probably hold images, videos or audio files, I guess, but I'm also not sure. I'd suggest also skipping it.

The "Stickers" folder is for the new feature they added last month or so. Now we can download Sticker Packs and install them on WhatsApp, allowing us to send stickers, that are in my opinion essentially image files with a nice transparent background and some extra info to make them behave like emojis. I would recommend leaving this folder alone as well, because deleting it would, as far as I know, be almost the same as deleting your emojis, meaning your stickers would disappear, and you'd probably see either blank images or error flags where there should be stickers either sent or received. The stickers we receive probably are stored in there with the ones we installed, as if we had those installed as well which in my opinion could mean that this folder will eventually clutter up with a bunch of stickers, but for now leaving it alone is probably the best option. If you manage to clean it up while keeping the installed stickers and maybe not making the received stickers disappear on the chats, then that'd be nice. But for now, I suggest skipping it.

I have a few spare phones (a Nexus 5 (hammerhead) and a Moto X Play (lux)), both running LineageOS 14.1 (as far as I remember), and a spare tablet (unknown brand, and veeery old, pretty much useless now), so if you want me to do some testings, I could try. The bad thing is that I have no spare phone numbers to use for registration on WhatsApp, and I'm not up to sacrificing my own WhatsApp account, I love to keep memories, old chats, old images and all, so I'll do all I can to preserve them. That's also the main reason I haven't signed up for the beta program of SD Maid. I'm afraid there may be bugs or glitches that could put my precious (MY PRECIOUS) data at risk.

**Comment by d4rken** [comment]
I agree. I've commit the changes and it will be part of the next update.

If you would like to experiment with SD Maid a bit more, without risking too much, there is an experimental setting in the debug menu (long press settings) that "disarms" SD Maid and exchanges the `rm` command for `echo`.

On a side note, independent of SD Maid, if those old images are important to you, I hope you have a backup.
