### ISSUE TITLE
Bug: The loading is getting very long.

### ISSUE THREAD

**Issue by dariusity** [d4rken/sdmaid-public#2132]
### What happened?
I noticed that since i installed new Magisk v17.1 the loading gets at least double, if not triple the time that it used to take. I believe there could be some issue dealing with systemless root as your app is based on full root access. Can i ask what are the tasks performed on Databases? Are they SQLite3 and ZipAlign? Thanks very much. Cheers 

### What did you expect to happen?
I hope you could bring down the loading time a little, please. 

### How can I reproduce the issue?
Anytime you want to launch a task, like App Control or Database. 

### Comments
I still love SD Maid.

### SD Maid
Version: `4.11.10 (41110)`
Unlocker: `4.3.4 (40304) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `samsung/j2ltedx/j2lte:5.1.1/LMY47X/J200GUDXU3AQC1:user/release-keys`

**Comment by d4rken** [comment]
sql `VACUUM` is performed.
Most of the work is being done by the sqlite binary, I'm not sure how much impact Magisk could have on that.
