### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/.fotaApps (FP)

### ISSUE THREAD

**Issue by mbirth** [d4rken/sdmaid-public#2134]
### Target
Target: `/storage/emulated/0/Android/data/.fotaApps`
Prefix-free: `.fotaApps`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Updates`
Packagename: `com.tcl.ota.bb`
Version: `70103.0806.32.280 (818072601)`

### Current owners
None

### SD Maid
Version: `4.11.10 (41110)`

### Device
Fingerprint: `blackberry/bbb100emea/bbb100:8.1.0/OPM1.171019.026/ABJ879:user/release-keys`

### Comment
`TCL Updater temporary files, used on BlackBerry and Alcatel phones`

**Comment by d4rken** [comment]
Should this be included in the AppCleaner too? As hidden cache?

**Comment by d4rken** [comment]
Done & done.
