### ISSUE TITLE
Bug: False Deletion of Telegram X settings via SD Maid v4.12.0

### ISSUE THREAD

**Issue by TensorLake** [d4rken/sdmaid-public#2147]
### What happened?
Telegram X v0.21.1.1010 loses its settings after cleaning(all options selected) via SD Maid v4.12.0

### What did you expect to happen?
I expect to run a full clean without losing telegram's settings.

### How can I reproduce the issue?
sd maid 4.12.0 select all cleaning options and run a full clean, then the telegram x's settings will be remove

### SD Maid
Version: `4.11.10 (41110)`
Unlocker: ` (0) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `HUAWEI/GRA-L09/HWGRA:6.0/HUAWEIGRA-L09/C109B379:user/release-keys`

**Comment by d4rken** [comment]
What's the settings path?

**Comment by d4rken** [comment]
Possibly check via SD Maids statistics, I currently can't reproduce this.

**Comment by d4rken** [comment]
SystemCleaner, logs filter matches a db file.

`/data/data/org.thunderdog.challegram/files/pmc/db/\d+\.log`

**Comment by d4rken** [comment]
:heart:  fixed

**Comment by TensorLake** [comment]
> ❤️ fixed

I didn't notice your reply sir,sorry. Thanks!
