### ISSUE TITLE
Request: Ads Cleaner

### ISSUE THREAD

**Issue by JohnDoeIsBack** [d4rken/sdmaid-public#2148]
### What should the feature do?
Delete all the Ads cache data i.e google, vungle, Ad Images & videos, popups cache, unityshadercache, etc

### When/How would you use it?
Atleast once in a week to remove all those pesky ads files from my device.

### How would you implement it?
Apps download those Ad images & short vids in the background all the time, so removing them could free up space drastically.

### Comments
I've been using SDmaid for quite a while so bought it just to support you :) Keep it up dev!

### SD Maid
Version: `4.12.1 (41201)`
Unlocker: `4.3.4 (40304) (true)`

### Device
Root: `Unknown`
Fingerprint: `motorola/athene_f/athene_f:7.0/NPJS25.93-14-18/3:user/release-keys`

**Comment by d4rken** [comment]
Do you have concrete pathes that SD Maid is currently missing?
