### ISSUE TITLE
Bug: Databases cleaning not working

### ISSUE THREAD

**Issue by rfurb** [d4rken/sdmaid-public#2163]
### What happened?
During the scan phase the message "Sqlite binary unavailable" is displayed and this item do not star in the "run" phase.

### What did you expect to happen?
The database cleaning to be performed normally as it was before.

### How can I reproduce the issue?
Upgrade to version 4.12.2 and run the scan.

### Comments
Problem is solved by downgrading back to version 4.12.1

### SD Maid
Version: `4.12.2 (41202)`
Unlocker: `4.3.4 (40304) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `samsung/trltexx/trlte:4.4.4/KTU84P/N910FXXU1ANK4:user/release-keys`

**Comment by d4rken** [comment]
Likely #2154, if you can provide a debug log I can confirm.

**Comment by rfurb** [comment]
Hi,
Attached follows the requested log file.
Best regards,
R. Furbetta

--
Sent from myMail for Android Sunday, 02 December 2018, 03:53PM +01:00 from Matthias Urhahn  notifications@github.com :

>Likely  #2154 , if you can provide a debug log I can confirm.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .
---- 2 Dec 2018 16:01:23 ----

12-02 15:49:18.559 26272 26272 E WindowManager: android.view.WindowLeaked: Activity eu.thedarken.sdm.tools.bugs.reporter.ReportActivity has leaked window android.widget.LinearLayout{42c6e040 V.E..... ......ID 0,0-320,191} that was originally added here

12-02 15:51:24.349 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762284359, type=START, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:51:24.359 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762284364, type=RESUME, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:51:31.999 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762292005, type=PAUSE, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:51:32.029 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762292038, type=PREDEFINED, details=null, customType=null, customAttributes={}, predefinedType=contentView, predefinedAttributes={contentId=eu.thedarken.sdm_41202_4.12.2, contentName=692adab5-trltexx-en_GB, contentType=eu.thedarken.sdm.main.ui.settings.SettingsActivity-eu.thedarken.sdm}, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:51:32.129 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762292063, type=START, details={activity=eu.thedarken.sdm.main.ui.settings.SettingsActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:51:32.149 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762292159, type=RESUME, details={activity=eu.thedarken.sdm.main.ui.settings.SettingsActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:51:32.549 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762292555, type=STOP, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:52:40.409 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762360413, type=PAUSE, details={activity=eu.thedarken.sdm.main.ui.settings.SettingsActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:52:40.439 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762360438, type=START, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:52:40.449 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762360443, type=RESUME, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:52:40.749 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762360745, type=STOP, details={activity=eu.thedarken.sdm.main.ui.settings.SettingsActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:52:47.049 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762367059, type=PAUSE, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:52:47.549 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762367559, type=STOP, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:54:41.039 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762481035, type=START, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:54:41.039 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762481039, type=RESUME, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:54:47.169 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762487175, type=PAUSE, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:54:47.529 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762487542, type=STOP, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:54:49.769 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762489681, type=PREDEFINED, details=null, customType=null, customAttributes={}, predefinedType=contentView, predefinedAttributes={contentId=eu.thedarken.sdm_41202_4.12.2, contentName=692adab5-trltexx-en_GB, contentType=eu.thedarken.sdm.main.ui.SDMMainActivity-eu.thedarken.sdm}, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:54:49.819 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762489826, type=START, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:54:49.909 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762489910, type=RESUME, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:02.679 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762502687, type=PAUSE, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:03.139 26272 26313 E Answers : Failed to write event: [SessionEvent: timestamp=1543762503147, type=STOP, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=19a6f149-3c5c-480e-9bf7-1d28b4310056, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:18.679 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762518671, type=PREDEFINED, details=null, customType=null, customAttributes={}, predefinedType=contentView, predefinedAttributes={contentId=eu.thedarken.sdm_41202_4.12.2, contentName=692adab5-trltexx-en_GB, contentType=eu.thedarken.sdm.main.ui.SDMMainActivity-eu.thedarken.sdm}, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:18.709 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762518709, type=START, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:18.789 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762518795, type=RESUME, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:25.679 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762525688, type=PAUSE, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:26.059 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762526071, type=STOP, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:33.759  1070  1178 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{430189f0 26272:eu.thedarken.sdm/u0a275} (pid=26272, uid=10275) requires android.permission.READ_LOGS due to sender android (uid 1000)

12-02 15:55:59.219 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762559188, type=PREDEFINED, details=null, customType=null, customAttributes={}, predefinedType=contentView, predefinedAttributes={contentId=eu.thedarken.sdm_41202_4.12.2, contentName=692adab5-trltexx-en_GB, contentType=eu.thedarken.sdm.main.ui.SDMMainActivity-eu.thedarken.sdm}, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:59.259 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762559263, type=START, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:55:59.339 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762559342, type=RESUME, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:57:02.899 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762622909, type=PAUSE, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 15:57:03.379 26272 26272 I dalvikvm: Could not find method android.content.Context.startForegroundService, referenced from method eu.thedarken.sdm.tools.j.a

12-02 15:57:03.589 26272 26321 E Answers : Failed to write event: [SessionEvent: timestamp=1543762623603, type=STOP, details={activity=eu.thedarken.sdm.main.ui.SDMMainActivity}, customType=null, customAttributes=null, predefinedType=null, predefinedAttributes=null, metadata=[appBundleId=zzz.zzzz.fabric_0100, executionId=eadbeb13-346b-47f5-9221-84833027c168, installationId=125d920a34574bcb8873d49a1abb810f, limitAdTrackingEnabled=false, betaDeviceToken=null, buildId=00ef2605-84cc-42bb-b832-765c72b724f2, osVersion=4.4.4/N910FXXU1ANK4, deviceModel=samsung/SM-N910F, appVersionCode=41202, appVersionName=4.12.2]]

12-02 16:00:07.199  1070  1178 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{430189f0 26272:eu.thedarken.sdm/u0a275} (pid=26272, uid=10275) requires android.permission.READ_LOGS due to sender android (uid 1000)

---- 2 Dec 2018 16:01:23 ----

**Comment by rfurb** [comment]
Here you go (attached).
      
      
      Matthias Urhahn wrote on 02/12/2018 16:22:
    
    
      
      Thanks but I would need a log like this:
      https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/d4rken/sdmaid-public","title":"d4rken/sdmaid-public","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/d4rken/sdmaid-public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@d4rken in #2163: Thanks but I would need a log like this:\r\n\r\nhttps://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log"}],"action":{"name":"View Issue","url":"https://github.com/d4rken/sdmaid-public/issues/2163#issuecomment-443515563"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/d4rken/sdmaid-public/issues/2163#issuecomment-443515563",
"url": "https://github.com/d4rken/sdmaid-public/issues/2163#issuecomment-443515563",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [d4rken/sdmaid-public] Bug: Databases cleaning not working (#2163)",
"sections": [
{
"text": "",
"activityTitle": "**Matthias Urhahn**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@d4rken",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"d4rken/sdmaid-public\",\n\"issueId\": 2163,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"d4rken/sdmaid-public\",\n\"issueId\": 2163\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/d4rken/sdmaid-public/issues/2163#issuecomment-443515563"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 418758131\n}"
}
],
"themeColor": "26292E"
}
]
