### ISSUE TITLE
Request: add dex2oat function in AppControl or QuickAccess.

### ISSUE THREAD

**Issue by lifansama** [d4rken/sdmaid-public#2164]
### What should the feature do?
Using dex2oat to make apps launch and run faster.

### When/How would you use it?
When I install/update a new app or I want to clean my phone.

### How would you implement it?
just run command `cmd package compile -m speed -a`

### SD Maid
Version: `4.12.2 (41202)`
Unlocker: `4.2.2 (40202) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `xiaomi/whyred/whyred:8.1.0/OPM1.171019.011/V9.5.11.0.OEIMIFA:user/release-keys`

**Comment by d4rken** [comment]
Might be out of scope...

Doesn't the system do this automatically?

On what Android versions would this work?

Why is it necessary after cleaning/deleting with SD Maid?

**Comment by lifansama** [comment]
I am very sorry that I write this meaningless require.
It's true that system will do this. 
Maybe I need to do this by tasker.
Thank you.
