### ISSUE TITLE
AppControl incorrectly reports size of Termux

### ISSUE THREAD

**Issue by Mihara** [d4rken/sdmaid-public#2166]
On my particular phone (OnePlus 5) SDMaid's AppControl incorrectly reports the size of Termux app ([com.termux](https://play.google.com/store/apps/details?id=com.termux)) as equal to the size of every file in `/storage/emulated/0/` combined -- resulting in an obviously bogus app size of 45 gigabytes, and probably a *lot* of needlessly lost data if I were to try deleting it with AppControl. Which I'm not anxious to attempt for obvious reasons.

Termux builds a linux chroot-style environment inside its own data directory, and one of the options for accessing the rest of your data is to symlink your storage from inside this environment, which is probably why this happens -- but maybe this case deserves some special handling? Termux is quite a popular app.

**Comment by Mihara** [comment]
![screenshot_20181203-224223](https://user-images.githubusercontent.com/400675/49397444-a99cc980-f74c-11e8-8e29-de21fbd602f6.jpg)

For the record, this is what it looks like.

**Comment by d4rken** [comment]
Which SD Maid version and Android version, Magisk or SuperSU?

**Comment by d4rken** [comment]
> Termux builds a linux chroot-style environment inside its own data directory, and one of the options for accessing the rest of your data is to symlink your storage from inside this environment, which is probably why this happens -- but maybe this case deserves some special handling? 

I agree with your evaluation, it's likely symlink related.

> resulting in an obviously bogus app size of 45 gigabytes, and probably a lot of needlessly lost data if I were to try deleting it with AppControl

I don't think it would lead to data loss, but you don't have to try. SD Maid will delete the owner folders by their top level path and not traverse them to delete everything individually, so I think only the symlinks would be deleted. 

SD Maid determines the path sizes using `du` though and I think it currently follows symlinks. So the question is in which scenarios do we need `du` to follow symlinks for accurate sizes. I'll check my commit history to see if I added the flag for a reason or if it was just the default.

The default install of Termux doesn't seem to create this chroot environment, can you post a guide on how to set this up such that I can reproduce this?

**Comment by Mihara** [comment]
> Which SD Maid version and Android version, Magisk or SuperSU?

SD Maid 4.11.10 Pro, Magisk 17.1, Android 8.1

> The default install of Termux doesn't seem to create this chroot environment, can you post a guide on how to set this up such that I can reproduce this?

It always creates the environment, but it doesn't symlink your storage until you execute the command from inside it. The procedure [is detailed in Termux wiki](https://wiki.termux.com/wiki/Termux-setup-storage).

**Comment by d4rken** [comment]
Before

```java
        List<SDMFile> fileList = ReadTask.Builder.read(target)
                .atLevel(level)
                .followSymlinks() // /data/user/0 can be a symlink to /data/data
                .through(getSmartIO());
```

Now

```java
        // Apps like termux internally symlink to public storage
        // https://github.com/d4rken/sdmaid-public/issues/2166
        if (target.isSymbolicLink()) target = Check.notNull(target.getSymlink());
        List<SDMFile> fileList = ReadTask.Builder.read(target)
                .atLevel(level)
                .through(getSmartIO());
```

Seems to work for me now.
If you'd like to try a test version send me a short mail :wink:
