### ISSUE TITLE
Clutterreport: /storage/sdcard0/Video

### ISSUE THREAD

**Issue by puckfan2** [d4rken/sdmaid-public#2168]
### Target
Target: `/storage/sdcard0/Video`
Prefix-free: `Video`
Path-prefix: `/storage/sdcard0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners/storageAppname: `Video Player`
Packagename: `com.sec.android.app.videoplayer`
Version: `1.1 (1)`

Appname: `Android System`
Packagename: `android`
Version: `4.1.2-I497UCBMF3 (16)`

### Current owners
Appname: `?`
Packagename: `devian.tubemate.slide`
Version: `null (0)`

Appname: `?`
Packagename: `devian.tubemate.amazon`
Version: `null (0)`

Appname: `?`
Packagename: `devian.tubemate.v3`
Version: `null (0)`

Appname: `?`
Packagename: `devian.tubemate.home`
Version: `null (0)`

Appname: `?`
Packagename: `com.oneplus.gallery`
Version: `null (0)`

### SD Maid
Version: `4.11.10 (41110)`

### Device
Fingerprint: `samsung/espresso10uc/espresso10att:4.1.2/JZO54K/I497UCBMF3:user/release-keys`

**Comment by d4rken** [comment]
I don't think the Android system creates this folder by default.
