### ISSUE TITLE
SD Maid delete BMap's Offline Map data

### ISSUE THREAD

**Issue by im1989** [d4rken/sdmaid-public#2180]
It always accidentally deletes Bmap's offline map. Bmap is a map software in China, please help me to solve it.

Bmap download address:
https://down.shouji.com.cn/wap/down/app/package?package=me.gfuil.bmap

You can download this software and test it.

**Comment by d4rken** [comment]
What's the path of the data?

Which tool? CorpseFinder or AppCleaner?

What SD Maid version and device/android version?

**Comment by im1989** [comment]
Thank you focus this issue, I already solve this problem. I update SD Maid to latest version ()
