### ISSUE TITLE
Bug: Restore default settings button doesn't work

### ISSUE THREAD

**Issue by thunderschnozzle** [d4rken/sdmaid-public#2196]
### What happened?
In Settings --> CorpseFinder, I checked the "Uninstall Watcher" featured and then clicked on the "Restore Default Settings" button. Then I exited the CorpseFinder section, reentered it, and the "Uninstall Watcher" featured was once again checked

### What did you expect to happen?
I expected that once I exited the CorpseFinder section and then Reentered it the "Uninstall Watcher" featured will remain unchecked

### How can I reproduce the issue?
Go to Settings --> CorpseFinder, tick the "Uninstall Watcher" checkbox, click on the "Restore Default Settings" button, exit and yhen immediately reenter the CorpseFinder section, and then you'll see that the "Uninstall Watcher" checkbox is once again ticked

### SD Maid
Version: `4.12.3 (41203)`
Unlocker: `4.3.5 (40305) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `ZTE/P996A01_O/ailsa_ii:8.0.0/OPR1.170623.032/20180815.171922:user/release-keys`

**Comment by d4rken** [comment]
Can reproduce :+1: , looking into it.

**Comment by d4rken** [comment]
One routine activated the watcher depending on the setting value, while the other set the setting value depending on whether the watcher component was enabled. This didn't play nice toegether. I've improved the code :+1:
