### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/me.pushy.sdk (FP)

### ISSUE THREAD

**Issue by yosimor** [d4rken/sdmaid-public#2199]
### Target
Target: `/storage/emulated/0/Android/data/me.pushy.sdk`
Prefix-free: `me.pushy.sdk`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `RedAlert`
Packagename: `com.red.alert`
Version: `1.0.9.6 (10096)`

### Current owners
None

### SD Maid
Version: `4.12.3 (41203)`

### Device
Fingerprint: `samsung/ha3gub/ha3g:5.0/LRX21V/N900UBUEBOK1:user/release-keys`

**Comment by yosimor** [comment]
'[pushy.sdk](https://pushy.me)' aims to provide "Lightning-fast, highly-reliable push notification delivery", and has nothing to do with advertising.

It seems to be used inside @eladnava's '[RedAlert](https://redalert.me/index_en.html)' rocket-alert [app](https://github.com/eladnava/redalert-android), which provides notifications on incoming missile attacks in Israel.

**Comment by eladnava** [comment]
[Pushy](https://pushy.me/) is a push notification service (non-advertising related).

The `/Android/data/me.pushy.sdk` directory contains device token information which we store to re-identify devices after they reinstall an application. You may examine this directory contents to confirm.
