### ISSUE TITLE
Unavailable: TestApplet

### ISSUE THREAD

**Issue by Ubimo** [d4rken/sdmaid-public#2216]
I get an error when I click on settings. I did debloat my S7 edge stock oreo a little bit. Is sdmaid relying on some certain apps? I use latest magisk.

Edit:
I just updated to latest version, its working again.

![screenshot_20181225-113119_sd maid](https://user-images.githubusercontent.com/11019557/50420790-38c36b80-0839-11e9-8877-55f30a85c16b.jpg)

**Comment by d4rken** [comment]
It's not an app but a file, it would very unusual to delete this, even accidental. This can also happen if you allowed SD Maid root once, but then irregularly denied on subsequent requests.

But if it's now working :+1: 

Happy holidays :christmas_tree:
