### ISSUE TITLE
Add name and date sort in userfilter

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#2237]
I think you could add a sidebar into Userfilter page like in app control to sort filters ,when you add it, user can sort filters via name and edited date with ascend and discend.

**Comment by d4rken** [comment]
I don't think it currently saves a date. Will have to add it to the format.

**Comment by d4rken** [comment]
Maybe creation + modification date.

**Comment by Edfgdz** [comment]
OK
