### ISSUE TITLE
Problem with root and database...

### ISSUE THREAD

**Issue by JitterGamesYT** [d4rken/sdmaid-public#2238]
When i search database with root permisson it found 200 folders...Yeah and when i remove the 200 files and click on again search database ..They are there again?! What is that?! Withou root it don't do.. Fix it and i am happy okey? I want remove this sshitty ...Folders or files i don't know my english isn't good :D

**Comment by d4rken** [comment]
The databases are not junk files. They are not removed, they optimized, e.g. vacuumed:
https://www.google.com/search?q=SQL+VACUUM

**Comment by JitterGamesYT** [comment]
LoL i know but they didn't optimize..

**Comment by JitterGamesYT** [comment]
No..Bye

út 1. 1. 2019 21:25 odesílatel Matthias Urhahn <notifications@github.com>
napsal:
