### ISSUE TITLE
SystemCleaner "base path" behavior

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#2243]
System Cleaner has some problem that may cause wrong deletion.

When i added one folder [/storage/emulated/0/.c] into basepath, systemcleaner will scan out [/storage/emulated/0/.cc], [/storage/emulated/0/.clipboard] and [/storage/emulated/0/.ccf5d48d821324d1a992687444a73464].

I think if someday i want to delete one folder [/storage/emulated/0/.c], sd maid can delete more folder/files that i don't want it delete.
    
So could you fix this problem?

**Comment by d4rken** [comment]
This is by design.

"Basepath" could be more accurately named "Path starts with".

You have to either append a `/` at the end, e.g. `/storage/emulated/0/.c/`

Or you add `.c` to "name starts with" and "name ends with", which then would act like a fictive "name equals".

**Comment by Edfgdz** [comment]
I think this design is too complex.

Add a complete file/folder path into basepath and system cleaner search out that file/folder with that name without other folder/file is more easily to be understanded by user.

**Comment by d4rken** [comment]
If you create the filter from the Explorer, it will automatically add `/storage/emulated/0/.c/`.

I don't think adding a `/` at the end is too complex. "Basepath" seems to be missleading though, we could rename it to "Path starts with" to make the behavior more obvious.

**Comment by d4rken** [comment]
If we restrict the matching of this field to only "whole folders", then it would make the filters less powerful and also break everyone filters who use this mechanic to match multiple paths.

**Comment by d4rken** [comment]
> You can add a setting that user can choose open/close this mechanic themeselves in sd maid. settings to care about those users.

Changing the filtering engine to require options is not a very clean approach. I would prefer to not modify the way filters work. It would be cleaner to rename "basepath" to "starts with" and add a new "basepath", but any new filter criterium costs scan speed.

We could change the explorer tool to have an option "whole folder" vs "content" and then it would automatically created the right filter as mentioned in https://github.com/d4rken/sdmaid-public/issues/2243#issuecomment-450898119 this would make it less complex to create a filter.

**Comment by Edfgdz** [comment]
At present this design could make user has more workloads.

Because if one user want to delete whole folder,he must add folder path into basepath and add folder name into name end with, if he doesn't do that, there always be possibility that sd maid could delete more folders which he doesn't want to delete,because user can't remember all folder/file names,sd maid could scan out some folder/file that he doesn't know to delete.

If basepaths too much,it will be a pain for him to do this work.

**Comment by Edfgdz** [comment]
You want to add another basepath, does this basepath has mechanic restriction?


I add that folder not from Explorer, i firstly copy that folder path and add it to filter manually.

**Comment by Edfgdz** [comment]
I have two ideas to reduce scan time,not sure if it will work.

Userfilter are composed of several factors,some factors have been added by user,some haven't.

If one factor hasn't been added.by user,is it possible that make sd maid believe this factor are not been coded into filter,and sd maid can scan this filter without using corresponding code of factor hasn't been added,in another word,make sd maid skip that code.

Not sure if you can change sd maid scanning code structure to make it happen.

Another idea is that you can make sd maid put added factors into one group,put unadded factors into another group backgroundly when user add paths.  

When sd maid scan paths,it can scan added factors group and not scan unadded group.

I think second idea could spend more time.

**Comment by Edfgdz** [comment]
OK.But after i upgrade to that version,can you make file paths in basepath migrate to new filter type from the basepath at present?

I don't want to migrate them manually at that time,because of lots of work.

**Comment by d4rken** [comment]
There will be no automatic migration. If the user has a custom filter currently in use, then the user knows what it does and made it that way on purpose. I can't write code that understands the users intentions, so any migration that changes filter behavior is too dangerous, and any migration that doesn't change behavior is unnecessary.

**Comment by Edfgdz** [comment]
I think some users could use basepath to create userfilters because they are not familiar with regex.

If they use basepath to create userfilters, in their opinion, if they add the file (/storage/emulated/0/A) into basepath, they could think sd maid will only scan out (/storage/emulated/0/A), some of them may not realize that sd maid could also scan out other possibilities like (/storage/emulated/0/Aa) or (/storage/emulated/0/AB) etc.

When you add another basepath and change old basepath become Path starts with, there's a  problem, the paths users added are still in the Path starts with, not moved to the new basepaths, it means these paths could make sd maid scan more files users don't know, and therefore sd maid could delete more files they don't know.

I think this is not safe, it is better to solve this history problem when added another basepath.

**Comment by Edfgdz** [comment]
I checked the wiki about Userfilters creation, it doesn't especially emphasize and write clearly that basepath could catch more files with Strawberry.pdf starts, it means if there is a file named Strawberry.pdfg, and if this file is important to user,, sd maid will bring damage to user when sd maid delete it.

**Comment by Edfgdz** [comment]
![Screenshot_2020-06-22-13-11-35-886_com xbrowser play](https://user-images.githubusercontent.com/26460124/85251477-f578a600-b48b-11ea-92f3-df3eab7f386d.jpg)

**Comment by Edfgdz** [comment]
I don't know what is your thought on this issue, but I know that this risk will always exists if not make old basepaths moved to new basepaths or if we not make any changes to it.

**Comment by Edfgdz** [comment]
I find Exclusion have this problem too, if you can make basepath changed, don't forget about sd maid Exclusion.

**Comment by Edfgdz** [comment]
I think it is not good to add [Path starts with] directly into Userfilters with Basepath, maybe it is better to make user could switch between [Basepath] and [Path starts with] in this style.

How do you think about it?

**Comment by Edfgdz** [comment]
![Screenshot_2020-07-15-19-49-13-994_eu thedarken sdm](https://user-images.githubusercontent.com/26460124/87542126-0906dd80-c6d5-11ea-8558-a64fdb5872e6.jpg)
