### ISSUE TITLE
Make Chinese character sorted regularly in Appcontrol and Appcleaner

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#2247]
I find file/folder name with Chinese character are name sorted in mess.

Can you make Chinese character sorted regularly in name sort?

You can use Chinese pinyin to sort because they are as same as English alphabet.

**Comment by d4rken** [comment]
I'm not sure how to do this as the filenames can be anything.

**Comment by Edfgdz** [comment]
There are three steps 

Judge if the name of file/folder contains Chinese character

Convert that Chinese character into Chinese pinyin

Regard that pinyin as English letter to sort.

**Comment by d4rken** [comment]
> Judge if the name of file/folder contains Chinese character
> Convert that Chinese character into Chinese pinyin

How do I do this?

**Comment by Edfgdz** [comment]
I find Chinese character name sort in App control  are in mess,so i created this issue,but i didn't look.clear if sd maid explorer name sort is same.

At present, i find explorer.Chinese character name sort work without problem,but App control,App Cleaner have problem.

Can you make them work as same as explorer?

**Comment by d4rken** [comment]
I've checked the code and all (explorer,appcontrol,appcleaner) use similar methods of comparison.

AppCleaner and AppControl unnecessarily ignored case-sensitivity. I've changed this in v4.13.1.

Please reopen with examples if is not solved in the next update.
