### ISSUE TITLE
Bug: App uninstalled on opening

### ISSUE THREAD

**Issue by underskyzx** [d4rken/sdmaid-public#2248]
### What happened?
I just opened SD Maid and as soon I opened I got a message saying an app was uninstalled (Almeida Bible something like that)

### What did you expect to happen?
Nothing... Should just open and stand by waiting for command

### How can I reproduce the issue?
Dam the app is still here...... I think it was just a random message maybe? This is the app  https://play.google.com/store/apps/details?id=br.com.frizeiro.bibliaalmeidaatualizada

### Comments
After what happened I uninstalled normally 2 other apps so ignore everything this batch uninstall to focus on what happened before that should help reduce the logs to look

### SD Maid
Version: `4.13.0 (41300)`
Unlocker: `4.3.5 (40305) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Xiaomi/santoni/santoni:7.1.2/N2G47H/V9.5.10.0.NAMMIFD:user/release-keys`

**Comment by d4rken** [comment]
> After what happened I uninstalled normally 2 other apps so ignore everything this batch uninstall to focus on what happened before that should help reduce the logs to look

I can't see random logs from device, you'll need to reproduce this and manually record one if the app didn't crash.

Did you previously uninstall "Almeida Bible"? Sounds like the CorpseFinder's uninstall watcher was triggered, but the window didn't get shown until you launched SD Maid.
