### ISSUE TITLE
Request: Sort by size

### ISSUE THREAD

**Issue by underskyzx** [d4rken/sdmaid-public#2249]
### What should the feature do?
Would be nice if we could sort de results in the App Cleaner Details by size

### When/How would you use it?
I would default to descendant size

### How would you implement it?
Shouldn't be hard to fit this option in the screen

### Comments
Sup

### SD Maid
Version: `4.13.0 (41300)`
Unlocker: `4.3.5 (40305) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Xiaomi/santoni/santoni:7.1.2/N2G47H/V9.5.10.0.NAMMIFD:user/release-keys`

**Comment by d4rken** [comment]
I think it's a good idea.

Closing in favor of duplicate #2200
