### ISSUE TITLE
Clutterreport: /storage/48EA-6F84/backups

### ISSUE THREAD

**Issue by MDA-The-Developer** [d4rken/sdmaid-public#2252]
### Target
Target: `/storage/48EA-6F84/backups`
Prefix-free: `backups`
Path-prefix: `/storage/48EA-6F84/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.jrummy.app.managerfree`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `com.estrongs.android.pop.cupcake`
Version: `null (0)`

Appname: `?`
Packagename: `com.estrongs.android.pop.pro`
Version: `null (0)`

Appname: `?`
Packagename: `com.estrongs.android.pop.app.shortcut`
Version: `null (0)`

~~Appname: `?`~~
~~Packagename: `com.estrongs.android.pop`~~
~~Version: `null (0)`~~

~~Appname: `?`~~
~~Packagename: `ccc71.at.free`~~
~~Version: `null (0)`~~

Appname: `?`
Packagename: `ccc71.at`
Version: `null (0)`

### SD Maid
Version: `4.12.3 (41203)`

### Device
Fingerprint: `samsung/crownqltesq/crownqltesq:8.1.0/M1AJQ/N960USQS1ARJ9:user/release-keys`

**Comment by SuperSandro2000** [comment]
Seems to be a false report.
