### ISSUE TITLE
Not removing .odex file in system

### ISSUE THREAD

**Issue by HemanthJabalpuri** [d4rken/sdmaid-public#2253]
When we are deleting app and its data.. of system app
it is not deleting the corresponding .odex files...
I am on 4.4.2 Samsung Stock ARMv7l sdmaid v4.12.0
I am rooted with su 2.82sr5

**Comment by lertsak679** [comment]
#2253

**Comment by HemanthJabalpuri** [comment]
and also not giving info in size in app details about the corresponding .odex files......

**Comment by d4rken** [comment]
Please update to at least SD Maid v4.13.4 and if the issue persists, record the uninstall:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
