### ISSUE TITLE
Request: Export/import config

### ISSUE THREAD

**Issue by rhjdvsgsgks** [d4rken/sdmaid-public#2259]
### What should the feature do?
Export the config to the file , and import config from the file

### When/How would you use it?
Transfer config to new phone ,or share my config to the others

### SD Maid
Version: `4.13.0 (41300)`
Unlocker: `4.3.5 (40305) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Sony/G8142/G8142:8.0.0/47.1.A.16.20/623594567:user/release-keys`

**Comment by d4rken** [comment]
Duplicate #599, it's planned for the next dev sprint.

Config sharing might be difficult, feel free to add your thoughts to #599.
