### ISSUE TITLE
Bug: Frequently dialled contacts are cleared

### ISSUE THREAD

**Issue by ghpranav** [d4rken/sdmaid-public#2272]
### What happened?
Whenever I optimise the database, frequently dialled contacts are getting cleared from the AOSP Phone Dialler app.

### What did you expect to happen?
I expect it to not get deleted, like before. This issue started to show up after a recent update

### How can I reproduce the issue?
Use AOSP Dialer app to check frequently dialled contacts, optimise the database & frequent contacts will get cleared.

### SD Maid
Version: `4.13.1 (41301)`
Unlocker: `4.3.5 (40305) (true)`

### Device
Root: `Unknown`
Fingerprint: `xiaomi/tissot/tissot_sprout:8.0.0/OPR1.170623.026/8.1.10:user/release-keys`

**Comment by d4rken** [comment]
The last update didn't change that functionality.

Did you change the option "skip running"?

**Comment by ghpranav** [comment]
I have enabled Skip Running option from quite a long time now

**Comment by d4rken** [comment]
The updates did not change SD Maids behavior in this regard and I can't change how `SQL VACUUM` behaves.

Are you sure it is caused by 'optimise databases' function? It does not delete any files. The only way I see that this could happen is if the dialer app starts while the database is being worked on.

The only solution I currently is to exclude this app from the operation.

**Comment by ghpranav** [comment]
I can't exclude that app because it was never included, as it's a system app. But strangely enough, now I'm unable to reproduce the bug, even though I haven't changed anything. Feel free to close this issue as it magically got resolved...

**Comment by d4rken** [comment]
Why can't you exclude it? Long press the database and add an exclusion. Or exclude the whole packagename.

**Comment by ghpranav** [comment]
I can't exclude that app because AOSP Dialler doesn't even show up on the list, as I haven't enabled "Include system apps" option, & AOSP Dialler is a system app, in my RR ROM

**Comment by d4rken** [comment]
If the app or it's databases are not shown in the search results of the database tool, then the database isn't being optimized and this isn't caused by the database tool.
