### ISSUE TITLE
Shows with App's it's displaying Advertisements

### ISSUE THREAD

**Issue by evandroks** [d4rken/sdmaid-public#2277]
I have a Motorola Z2 Play with Android 8.0.0

I install a lot of apps in My android - I have at this moment 722  apps installed. (because my duty is a app tester)

I installed some app that started to show Advertisements in the screen - even after I reboot my device, after some minutes the AD's starts to pop up in the screen.

If I open SdMaid Pro , it show me that just Sdmaid it's in running state. ( a incorrect information) 
I need Sdmaid to help me to find the name of the App who is displaying the Advertisments.

**Comment by d4rken** [comment]
Advertisement detection is out of SD Maids scope. Detection of running apps may currently be inaccurate on Android 8+ due to system restrictions. I'm looking into it but unaware of any workarounds without root.
