### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by jels1** [d4rken/sdmaid-public#2279]
you used your app to wipe my phone. nice work. it would be nice with an explanation. You did however leave your mark so it would be easy for me to find you. u must be proud. and the reputation of the website must be great. until now i have not been aggressive. i hope i.m not forced. best regards.

**Comment by jels1** [comment]
i take it that u are not the one hacking my computers then? Very cool gesture of u. I enjoy it å lot.

**Comment by Suz1118** [comment]
How horrible & ugly people can be never ceases to amaze me me. Revenge
usually a thing that makes one feel satisfied, however getting even by way
of teaching one a lesson in life rarely leaves one feeling unsatisfied.  So
my advice (if you want to take it) is to play professor and teach this ugly
person a very personal lesson,one that they should never forget.  You may
just be helping others from future deastores that happened to you and don't
have the abilities  or resources that you have.  So with that said I am
wishing that you and yours have a very blessed life.  Thanks for all you do
for the rest of us.
Have an awesome day.  Suz
