### ISSUE TITLE
Crash changing SD Maid receiver

### ISSUE THREAD

**Issue by ChristophHeilmann** [d4rken/sdmaid-public#2287]
I don't think you test that because it's silly to do so, but when you disable SD Maids own receiver the app crashes (win death).

My device: Sony tablet Z4 with Marshmallow 6.0.1

**Comment by d4rken** [comment]
Ha :grin:  good catch. :+1: 

That should actually not be possible. I need to disable this for SD Maid.
It's not actually a crash, but the system closes SD Maid which is just what it does when you toggle an app component.
