### ISSUE TITLE
Safer/Securer/Reliabler Removal Of Contacts Duplicates! 

### ISSUE THREAD

**Issue by ScorpioViking** [d4rken/sdmaid-public#2294]
Have yet to find an app. which properly scrubs contact lists of duplicates. Keeping a temporary copy of status before run, maybe even showing before & after on split screen would be most helpful as well to assist in clean up & make last minute adjustments. How about you folks having a go at it?

**Comment by d4rken** [comment]
I don't think this is within the scope of SD Maid, sorry :frowning:.

**Comment by ScorpioViking** [comment]
If not clean-up/tidying is not within the scope SD Maid then who do you recommend? Remember you folks do have a removal of Duplicate section, just saying.

**Comment by d4rken** [comment]
The duplicate section still "just" compares files based on checksums.

Contacts are not actually files, but in one single database file, duplicate search would be lot's of individual comparisons of numbers, names etc.

It just doesn't fit SD Maid, and to be honest it's not something that sounds fun to develop either :disappointed:.

> you folks

There is no team, just me :wink: . Well there kinda is a team, all the nice volunteers who help me! But codewise, justme :yum: .

**Comment by ScorpioViking** [comment]
Seeing as your in the business of coding I'd greatly appreciate it if you would inform me, as already requested, who you deem, app.-wise that is, to be best suited for Contacts List tidying/cleanup or at least contact your peers who might have the answer & kindly forward it to yours truly. Thanks.

**Comment by d4rken** [comment]
I've done no research for such apps.
I suggest to ask on https://www.reddit.com/r/androidapps/ for some recommendations.
