### ISSUE TITLE
Bug: SELinux state isn't correctly shown

### ISSUE THREAD

**Issue by zputnyq** [d4rken/sdmaid-public#2298]
### What happened?
SELinux state isn't correctly shown on overview

### What did you expect to happen?
It should show the correct SELinux state

### How can I reproduce the issue?
Tap overview, start it then see root status section

### Comments
It should show the correct SELInux state

### SD Maid
Version: `4.12.3 (41203)`
Unlocker: `4.3.6 (40306) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Sony/E2306/E2306:6.0.1/26.3.A.1.33/1954918276:user/release-keys`

**Comment by d4rken** [comment]
What is it showing and what do you expect it to show?

**Comment by zputnyq** [comment]
It should shows permissive as it's the state on my device. But on SDMaid it shows enforce[
![_20190211_112305](https://user-images.githubusercontent.com/31039796/52546239-26ed5600-2df0-11e9-84f8-99ce9e9de556.JPG)
![_20190211_112125](https://user-images.githubusercontent.com/31039796/52546245-2e146400-2df0-11e9-9c24-273f9e3648ca.JPG)

](url)

**Comment by d4rken** [comment]
What does `getenforce` output if you run it without root?

**Comment by zputnyq** [comment]
I can't get any output.
On termux it says command not found.
On terminal emulator 'permission denied'.
However I checked the enforce file using explorer that support root it shows '0'

**Comment by d4rken** [comment]
SD Maid checks without root and on `permission denied` defaults to `ENFORCING`.

I'll look into whether we can use root for the check. Though if we have root, the SELINUX state is a bit less interesting to us :laughing:

**Comment by zputnyq** [comment]
Ok, no problem :-)

**Comment by d4rken** [comment]
Currently out of scope, would require changes to [RxShell](https://github.com/d4rken/RxShell, created a ticket there and closing it here.

https://github.com/d4rken/RxShell/issues/28

**Comment by edd04** [comment]
> ### What happened?
> SELinux state isn't correctly shown on overview
> 
> ### What did you expect to happen?
> It should show the correct SELinux state
> 
> ### How can I reproduce the issue?
> Tap overview, start it then see root status section
> 
> ### Comments
> It should show the correct SELInux state
> 
> ### SD Maid
> Version: `4.12.3 (41203)`
> Unlocker: `4.3.6 (40306) (true)`
> 
> ### Device
> Root: `RootContext(rootState=Root(state=ROOTED)`
> Fingerprint: `Sony/E2306/E2306:6.0.1/26.3.A.1.33/1954918276:user/release-keys`

**Comment by d4rken** [comment]
I'll remove this in newer versions of Android where root is necessary to display this, it's not very useful.

**Comment by Zetotez** [comment]
> ### What happened?
> SELinux state isn't correctly shown on overview
> 
> ### What did you expect to happen?
> It should show the correct SELinux state
> 
> ### How can I reproduce the issue?
> Tap overview, start it then see root status section
> 
> ### Comments
> It should show the correct SELInux state
> 
> ### SD Maid
> Version: `4.12.3 (41203)`
> Unlocker: `4.3.6 (40306) (true)`
> 
> ### Device
> Root: `RootContext(rootState=Root(state=ROOTED)`
> Fingerprint: `Sony/E2306/E2306:6.0.1/26.3.A.1.33/1954918276:user/release-keys`
