### ISSUE TITLE
 can't attach images when reporting a bug from within the app

### ISSUE THREAD

**Issue by jidanni** [d4rken/sdmaid-public#2301]
Reporting a bug from within the app gives one no way to attach an image.

Therefore I would have a link at the bottom of the form. The link would be to GitHub for the advanced way to report a bug.

**Comment by d4rken** [comment]
I will look into it.

Currently the bug reporting form just preconstructs a URL for GitHub, I don't think I can upload files that way. So I might have to look at the GitHub API.

**Comment by jidanni** [comment]
In fact the user might be much more comfortable just reporting a bug via
github, so be sure to offer the direct link too, so he is aware that he can.

**Comment by d4rken** [comment]
Direct image upload via Github API is out of scope for this feature, but I've added a direct link from within the same form.
