### ISSUE TITLE
 provide link to share apps

### ISSUE THREAD

**Issue by jidanni** [d4rken/sdmaid-public#2302]
![screenshot_20190213-184901-270x480](https://user-images.githubusercontent.com/1230959/52706565-b21d4600-2fc0-11e9-8cc3-8a37c85daeb9.jpg)
Here our user is looking for a way to share a typical app with his friends. Alas there is no way to get the link to Google Play of the app. He can only stare at the and part of the link but he can't copy the whole link. See also #255.

**Comment by jidanni** [comment]
He needs to put together the following link by hand , 
https://play.google.com/store/apps/details?id=tms.tw.governmentcase.TaoyuanBus

**Comment by d4rken** [comment]
:+1: 

I could add it in the toolbar at the top-right?

What if the app is not on Google Play?

**Comment by jidanni** [comment]
Yes I suppose.
Hmmm, don't apps have some field within them saying if they came from
the Play Store or not?

I suppose that is how the stock Andriod App Info can tell(?) when at the
bottom they have a link to open in the Play Store.

**Comment by d4rken** [comment]
You are right, I should be able to determine if it was installed via Google Play and only then show it.
