### ISSUE TITLE
Clutterreport: /storage/enc_emulated (FP)

### ISSUE THREAD

**Issue by sassygirl** [d4rken/sdmaid-public#2314]
### Target
Target: `/storage/enc_emulated`
Prefix-free: `/storage/enc_emulated`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Fused Location`
Packagename: `com.android.location.fused`
Version: `6.0.1 (23)`

### Current owners
None

### SD Maid
Version: `4.12.3 (41203)`

### Device
Fingerprint: `samsung/j7popqltetfnvzw/j7popqltetfnvzw:6.0.1/MMB29M/S727VLUDS4ARF2:user/release-keys`

**Comment by JavkhlanK** [comment]
Wut?
