### ISSUE TITLE
Clutterreport: /storage/emulated/0/Cardboard/current_device_params

### ISSUE THREAD

**Issue by UryAlexander** [d4rken/sdmaid-public#2324]
### Target
Target: `/storage/emulated/0/Cardboard/current_device_params`
Prefix-free: `Cardboard/current_device_params`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `YouTube`
Packagename: `com.lara.android.youtube`
Version: `12.45.56 (1245562300)`

### Current owners
Appname: `?`
Packagename: `com.google.vr.cyclops`
Version: `null (0)`

Appname: `?`
Packagename: `com.google.samples.apps.cardboarddemo`
Version: `null (0)`

### SD Maid
Version: `4.12.3 (41203)`

### Device
Fingerprint: `lge/cv7a_lao_com/cv7a:8.1.0/OPM1.171019.019/183310412dd8e.FG:user/release-keys`

**Comment by d4rken** [comment]
Can you tell me more about this app and path?
