### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.hdeva.launcher/files (FP)

### ISSUE THREAD

**Issue by Georgious40** [d4rken/sdmaid-public#2325]
### Target
Target: `/storage/emulated/0/Android/data/com.hdeva.launcher/files`
Prefix-free: `com.hdeva.launcher/files`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Shared Library`
Packagename: `com.google.android.ext.shared`
Version: `1 (1)`

### Current owners
Appname: `Lean Launcher`
Packagename: `com.hdeva.launcher`
Version: `1.1.9 (24)`

### SD Maid
Version: `4.13.1 (41301)`

### Device
Fingerprint: `SKY/Platinum_B5/Platinum_B5:8.1.0/O11019/1542357804:user/release-keys`

**Comment by Georgious40** [comment]
Be nice to root this device

**Comment by d4rken** [comment]
This is not the place for this.
