### ISSUE TITLE
Ghost files and possible recovery in sdcard

### ISSUE THREAD

**Issue by GamaXplorer** [d4rken/sdmaid-public#2329]
While deleting files through storage analyser, an enormous number of items have seemingly disappeared. Although sdmaid and my regular explorer say the space is still being occupied, when going in depth the files simply aren't there and can not be accessed in any way.
Is there any way to get these files back?

**Comment by d4rken** [comment]
Hm not sure what you mean, can you share some screenshots?
What does the history in SD Maids statistics show?

**Comment by GamaXplorer** [comment]
@d4rken sorry, i'm unnable to post screenshots at the moment. 
The history doesn't show anythig out of place. However, sd maid has now become unnable to read my sd card through storage analyser.

**Comment by GamaXplorer** [comment]
![](https://i.imgur.com/MlPr1yR.jpg) all i can give i'm afraid

**Comment by d4rken** [comment]
> However, sd maid has now become unnable to read my sd card through storage analyser.

What happens if you try?

**Comment by GamaXplorer** [comment]
@d4rken it just doesnt show up

**Comment by d4rken** [comment]
I'm a bit confused. Is this about recovering deleted files, or about missing free space?

**Comment by d4rken** [comment]
For recovery see here:
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#recover-deleted-files

If you are missing free space, it's possible the deleted files were sparse files:
https://github.com/d4rken/sdmaid-public/wiki/explorer#file-size

Another, but rare, possibility is that the filesystem didn't correctly mark the space as freed, then this could point to a faulty sdcard. In that case I'd try to fix the filesystem from a desktop computer.
