### ISSUE TITLE
Clutterreport: /storage/emulated/0/.thumbnails

### ISSUE THREAD

**Issue by benatdjakait** [d4rken/sdmaid-public#2346]
### Target
Target: `/storage/emulated/0/.thumbnails`
Prefix-free: `.thumbnails`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `YouTube`
Packagename: `com.google.android.youtube`
Version: `14.09.52 (1409523320)`

### Current owners
Appname: `?`
Packagename: `com.sec.android.app.videoplayer`
Version: `null (0)`

### SD Maid
Version: `4.13.2 (41302)`

### Device
Fingerprint: `Itel/I806/itel-P31:7.0/NRD90M/P31-I806-7.0-OP-V035-20180420:user/release-keys`

**Comment by d4rken** [comment]
AFAIk this isn't true?

**Comment by JavkhlanK** [comment]
I thought that's from Samsung Gallery (for Android 7.0)

**Comment by d4rken** [comment]
There is also the more commonly used `DCIM/.thumbnails`, I think that's what the Samsung Gallery app uses too @JavkhlanK .

I use the youtube app too and don't have this folder, so I'm closing this.
