### ISSUE TITLE
Clutterreport: /storage/emulated/0/HDVideoBox (new)

### ISSUE THREAD

**Issue by samkom98** [d4rken/sdmaid-public#2352]
### Target
Target: `/storage/emulated/0/HDVideoBox`
Prefix-free: `HDVideoBox`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `HD VideoBox`
Packagename: `dkc.video.hdbox`
Version: `2.10.8 (279)`

### Current owners
None

### SD Maid
Version: `4.11.9 (41109)`

### Device
Fingerprint: `Xiaomi/rosy/rosy:8.1.0/OPM1.171019.026/V10.1.3.0.ODAMIFI:user/release-keys`

**Comment by d4rken** [comment]
Why close? This looks legit!
