### ISSUE TITLE
[Feature Request] option to optimize pictures

### ISSUE THREAD

**Issue by Tids** [d4rken/sdmaid-public#2353]
Lately on Linux I found the tool `jpegoptim`, that lossless optimizes pictures you give it. So I did it and saved some real space.
633 pics of my android phone, about 150MiB saved.
![bildschirmfoto von 2019-03-08 08-52-29](https://user-images.githubusercontent.com/18744080/54015614-82f19300-4180-11e9-948f-d03b05bbffec.png). Always keep in mind that this is without any quality loss, or resizing.

I think a feature like this would be nice to have in sd-maid. Since many of us have thousands of pictures, probably many GiB of them.

What do you think?

**Comment by SuperSandro2000** [comment]
Has this tool any side effects? Losing meta data or making the images incompatible in any way?

https://github.com/tjko/jpegoptim

**Comment by Tids** [comment]
I dont see any side effects. I still can view them everywhere (Lin, Win, Android), can edit them.
Metadata is still in place (there is an additional argument to remove them, not active by default).

So if there are some downsides, I cant find them.

++thanks for the link to the project!

**Comment by SuperSandro2000** [comment]
This would need intensive testing before it could even be included in the beta as it could have potentially big down sides.
Maybe some games check hashes of their assets and would then redownload everything or some other crazy shit.

**Comment by Tids** [comment]
It's would be for user data only. We should *not* optimize app data. Everything that you see inside your gallery app should be fine.

**Comment by d4rken** [comment]
Where would this fit within SD Maid?

**Comment by Tids** [comment]
@d4rken I don't understand that question. You mean which category? That's not easy. Probably if you change Databases to a generic "Optimizations" it would fit right in there. :thinking:

**Comment by d4rken** [comment]
That was my question, and you are right it could fit in there. If we do jpeg optimization we should also do png optimization. Two more thoughts on this

* This would not be a lossless procedure, this would need to be made clear to the user.
* This would increase SD Maids size significantly as I would probably have to include the binaries (in multiple variations, e.g. x86/ARM) within.

**Comment by d4rken** [comment]
I'm wondering whether this wouldn't be better suited for an extra app :man_shrugging:, that begs the question, are there any other apps that do this?

I know there are multiple "duplicate finder" tools similar to what SD Maid offers.

**Comment by SuperSandro2000** [comment]
And we probably would need multiple binaries for different image formats.
Maybe even support video formats? Then we would need to make clear that the operation could take a long time and use a lot of battery.
Then it would need a failsave for files that have the wrong extension or magic header.
Then we can't really tell if an image is already optimised or needs optimisation. So we would rerun the operation on the same file a lot.
Then I don't take many pictures but I already have 2.9 GB pics and 1.2 GB videos alone in my DCIM/Camera folder. 
So maybe a new app would be necessary as this sounds a bit out of scope for as maid.

**Comment by d4rken** [comment]
I think this doesn't fit SD Maids scope and should be done in an extra app. This sounds like an app I might write but I'll have to do some research regarding existing solutions to see whether there is need for a new app to do this.
