### ISSUE TITLE
Bug: File/Directory icons not loading

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#2363]
### What happened?
I opened a file w/ ES-Text Editor and after closing the file, SD-Maid refused to load the file/directory icons (loading gif is present). After restarting, everything works

### What did you expect to happen?
That it will get fixed, it sometimes disturbs me

### How can I reproduce the issue?
Welp, idk. Maybe use ES-Text Editor (Pro) and try out. Sry :(

### Comments
Hi!

### SD Maid
Version: `4.13.3 (41303)`
Unlocker: `4.3.6 (40306) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS7CSA1:user/release-keys`

**Comment by d4rken** [comment]
If this is reproducible, please record it on a debug log and make it available to me :+1: 

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by d4rken** [comment]
Lack of info (debug log), but might be fixed by the Explorer rework in v4.14.0 anyways.
