### ISSUE TITLE
Clutterreport: /storage/emulated/0/database/files (new)

### ISSUE THREAD

**Issue by Goshvit** [d4rken/sdmaid-public#2386]
### Target
Target: `/storage/emulated/0/database/files`
Prefix-free: `database/files`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Запись звонка`
Packagename: `com.enlightment.voicecallrecorder`
Version: `1.5.42 (118)`

### Current owners
None

### SD Maid
Version: `4.13.3 (41303)`

### Device
Fingerprint: `DEXP/ML350/ML350:7.0/NRD90M/1499311022:user/release-keys`

**Comment by d4rken** [comment]
Sure about this? The path seems pretty generic.
