### ISSUE TITLE
Bug: Can't delete anything with SD-Maid

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#2389]
### What happened?
Every time I want to delete something with SD-Maid, it doesn't. I've allowed all the permissions for that, but writing works

### What did you expect to happen?
I thought the files would get deleted.

### How can I reproduce the issue?
Just try to delete somthing. It doesn't work

### Comments
Hi!

### SD Maid
Version: `4.13.4 (41304)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS7CSA1:user/release-keys`

**Comment by d4rken** [comment]
Please provide an example path of what you are trying to delete.

**Comment by d4rken** [comment]
With which tool are you trying to delete it?

**Comment by JavkhlanK** [comment]
Okay, I created a file text.txt on my phone. I want to delete it with Explorer, on the SnackBar is "Success!" and after reloading it, tadaaaa, it is still there 👎 .
[sdmaid_logfile_1552751693729.txt](https://github.com/d4rken/sdmaid-public/files/2974068/sdmaid_logfile_1552751693729.txt)

**Comment by d4rken** [comment]
You have used "armed state" debugging feature. SD Maid is faking deletions on purpose. Long press settings, set the armed state to `true` (red), restart SD Maid. :grin:

**Comment by JavkhlanK** [comment]
No, I didn't! On SD-Maid, there is: "Armed: false"!

**Comment by d4rken** [comment]
I'm pretty sure you did, the setting doesn't change by itself :wink: .

* Armed = True (SD Maid is armed with the weapons of file deletion :laughing: ) = red
* Armed = False (The safety is on and SD Maid is not dangerous) = green

Armed = True (red) is the default when you do a fresh install.

**Comment by JavkhlanK** [comment]
Look again...

**Comment by d4rken** [comment]
Read again what I wrote!

**Comment by JavkhlanK** [comment]
I'm so intelygent 😆 
thx :D
