### ISSUE TITLE
Request features Wifi log

### ISSUE THREAD

**Issue by Antokta** [d4rken/sdmaid-public#2394]
one more request for adding a wifi log feature or displaying a wifi list to delete so as not to make a full list of old wifi.
![Screenshot_2019-03-17-10-38-23-94_1552927853065](https://user-images.githubusercontent.com/48705969/54581180-20c94580-4a3e-11e9-886d-9beec9f8455f.png)
![Screenshot_2019-03-17-10-38-17-93_1552928093222](https://user-images.githubusercontent.com/48705969/54581182-2161dc00-4a3e-11e9-8e9c-42c2ef596498.png)

**Comment by d4rken** [comment]
Does this delete the Wifi Passwords?

**Comment by Antokta** [comment]
yes delete the name and password to reduce the list of old wifi that is stored is no longer used.

**Comment by d4rken** [comment]
Deleting wifi passwords is not within SD Maids scope.
