### ISSUE TITLE
Improve language and ROM compatibility for cache deletion via accessibility service.

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2396]
Support status of #1588 .

Supported since v4.14.0:

- [x] English (en) (AOSP 6.0 to 9.0)
- [x] German (de) (AOSP 6.0 to 9.0, Huawei 9.0)
- [x] Czech (cs) (AOSP 6.0 to 9.0)
- [x] Russian (ru) (AOSP 6.0 to 9.0, Samsung 8.1)
- [x] Spanish (es) (AOSP 6.0 to 9.0)
- [x] Chinese (zh) (AOSP 6.0 to 9.0)
- [x] Japanese (ja) (AOSP 6.0 to 9.0)
- [x] Portoguese (pt_BR) (AOSP 6.0 to 9.0)
- [x] Indonesian (id) (AOSP 6.0 to 9.0)
- [x] Hindi (hi) (AOSP 6.0 to 9.0)
- [x] Italian (it) (AOSP 6.0 to 9.0)
- [x] Ukrainian (uk) (AOSP 6.0 to 9.0)
- [x] French (fr) (AOSP 6.0 to 9.0)
- [x] Turkish (tr) (AOSP 6.0 to 9.0)
- [x] Polish (pl) (AOSP 6.0 to 9.0)
- [x] Korean (kr) (AOSP 6.0 to 9.0)
- [x] Dutch (nl) (AOSP 6.0 to 9.0)
- [x] Hungarian (hu) (AOSP 6.0 to 9.0)
- [x] Vietnamese (vi) (AOSP 6.0 to 9.0)
- [x] Greek (el) (AOSP 6.0 to 9.0)
****

**To add support for other languages:**

* State your locale/language, Android version and device.
* Post the text of step 1 and step 2, so I can copy paste them (in case non Latin characters are used)
* Add a screenshot of both screens

_Step 1_ is a list entry that takes us to the app's storage details, in English on Android 9 the entry reads:
```
Storage
X,XX MB used in internal storage
```
[Screenshot](https://user-images.githubusercontent.com/1439229/54468042-627d9600-4789-11e9-94dc-bc1e8ed0149d.png)

_Step 2_ is the button for clearing the cache, in English on Android 9 it's labeled:
```
Clear cache
```
[Screenshot](https://user-images.githubusercontent.com/1439229/54468047-69a4a400-4789-11e9-8216-012ed083df13.png)

**Comment by d4rken** [comment]
* Russian (ru) (AOSP 9.0)
  * Item 1 `Хранилище`
  * Item 2 `Очистить кеш`

**Comment by PauloFerr** [comment]
Why don't you use views id instead of text?

**Comment by d4rken** [comment]
@PauloFerr The entries are viewholders in a recyclerview, so they all have the same ID. I tried to use position, but that's variable too (at least between ROMs).

**Comment by drezz2** [comment]
Lenguaje:Spanish (es_ES)  Version: Lineage 16  Device:Oneplus One
Step 1
![imagen](https://user-images.githubusercontent.com/49213483/55439424-d949ca00-55a4-11e9-9b2c-57af1b2e6ac6.png)



Step2
![imagen](https://user-images.githubusercontent.com/49213483/55439398-c2a37300-55a4-11e9-8e87-226b6d22839a.png)

**Comment by d4rken** [comment]
@drezz2 Thanks, SD Maid will figure out lower/upper case herself. So it should work, but it wouldn't hurt if you test it in the next beta :wink:.

**Comment by drezz2** [comment]
do you see the two images? I do not know the reason why it only shows one (step 2) and the other appears as a link. (step 1)

When you join a beta program, does Google Play only notify you of betas?

**Comment by d4rken** [comment]
> do you see the two images? I do not know the reason why it only shows one (step 2) and the other appears as a link. (step 1)

Sorry I edited your comment to make it smaller, fixed.

> When you join a beta program, does Google Play only notify you of betas?

No, you will always get the latest version, if there is no beta then you'll get the production version.

**Comment by drezz2** [comment]
ok, so when you update you do not know if it is a beta or final version? (It's just curiosity, I do not know how this works, or if the play store indicates it)

**Comment by d4rken** [comment]
Google Play does no detection. I tell Google Play where to publish it. Any version that is published as beta on Google Play can also be moved forward to production. 

Independent of that when there have been many large changes I build SD Maid with a "beta" flag which will make it show "Beta" in the app too and improve debugging while sacrificing a bit performance. Builds with the "beta" flag will just not be moved to production by me.

Sometimes I think a build is stable but after publishing it on the beta track a few problems arise and I never move that problematic update out of beta, but replace it with an update, and if that update is stable enough I move it forward to production.

**Comment by d4rken** [comment]
* Russian (ru) (samsung/gta2slte:8.1.0)
  * Item 1 `Память`
  * Item 2 `Очистить кеш`

**Comment by d4rken** [comment]
* Chinese (zh) (AOSP 9.0)
  * Item 1 `存储`
  * Item 2 `清除缓存`

**Comment by d4rken** [comment]
* Japanese (ja) (AOSP 9.0)
  * Item 1 `ストレージ`
  * Item 2 `キャッシュを削除`

**Comment by d4rken** [comment]
* German (de) (Huawei Honor 10 (COL-L29) @ Android 9)
    * Item 1 `Speicher`
    * Item 2 `CACHE LÖSCHEN`

https://github.com/d4rken/sdmaid-public/issues/2503

**Comment by d4rken** [comment]
* Portuguese (pt_BR) (AOSP)
    * Item 1 `Armazenamento`
    * Item 2 `LIMPAR CACHE`

**Comment by d4rken** [comment]
* Indonesian  (id_IN) (AOSP 9.0)
   * `Penyimpanan`
   * `Hapus cache`

**Comment by d4rken** [comment]
* Hindi (hi_IN) (AOSP 9.0)
    * `मेमोरी`
    * `कैश साफ़ करें`

**Comment by d4rken** [comment]
* Italian (it_IT) (AOSP 9.0)
    * `Spazio di archiviazione`
    * `Svuota cache`

**Comment by d4rken** [comment]
* Ukranian (uk_UA) (AOSP 9.0)
    * `Пам'ять`
    * `Очистити кеш`

**Comment by d4rken** [comment]
* French (fr_FR) (AOSP 9.0)
    * `Stockage`
    * `Vider le cache`

**Comment by d4rken** [comment]
* Turkish (tr_TR) (AOSP 9.0)
    * `Depolama`
    * `Önbelleği temizle`

**Comment by d4rken** [comment]
* Korean (ko_KR) (AOSP 9.0)
    * `저장용량`
    * `캐시 지우기`

**Comment by d4rken** [comment]
* Polish (pl_PL) (AOSP 9.0)
    * `Pamięć wewnętrzna`
    * `Wyczyść pamięć podręczną`

**Comment by d4rken** [comment]
* Vietnemese (vi_VN) (AOSP 9.0)
    * `Bộ nhớ`
    * `Xóa bộ nhớ đệm`

**Comment by d4rken** [comment]
* Greek (el_GR) (AOSP 9.0)
    * `Αποθηκευτικός χώρος`
    * `Διαγραφή προσωρινής μνήμης`

**Comment by d4rken** [comment]
* Dutch (nl_NL) (AOSP 9.0)
    * `Opslagruimte`
    * `Cache wissen`

**Comment by d4rken** [comment]
* Hungarian (hu_HU) (AOSP 9.0)
    * `Tárhely`
    * `A gyorsítótár törlése`

**Comment by d4rken** [comment]
This should be the most used languages according to stats. If yours is still missing just post and I'l reopen this ticket.

**Comment by d4rken** [comment]
* Spanish (es_US) (Moto 9.0)
   * `Almacenamiento`
   * `BORRAR MEMORIA CACHÉ`

**Comment by programmist87** [comment]
Russian (ru) (Meizu M8, Android 8.1.0, Russian)

На моём телефоне очистка кэша находится сразу при входе из списка приложений, поэтому Item 1 указать не могу.

Item 1 

Item 2 Очистить кэш

**Comment by programmist87** [comment]
Russian (ru) (Meizu M8, Android 8.1.0, Russian)

На моём телефоне очистка кэша находится сразу при входе из списка приложений, поэтому Item 1 указать не могу.

Item 1

Item 2 Очистить кэш

![S00121-112452(1)](https://user-images.githubusercontent.com/60130882/72789386-bfb56400-3c44-11ea-8e59-94c41c2281c8.png)

**Comment by d4rken** [comment]
@programmist87 Thanks, can you create a new ticket for improving meizu support?
https://github.com/d4rken/sdmaid-public/issues/new

**Comment by programmist87** [comment]
@d4rken , тикет нужно создавать как описано по ссылке? https://guides.github.com/activities/hello-world/

**Comment by Ingood5** [comment]
Я правильно понял, что очистка скрытого кэша не поддерживается на Android 10? Если это так, возможно создать тикет для устройства с Андроидом 10?

**Comment by d4rken** [comment]
@Ingood5 It's supported, but I don't have access to all types of ROMs. 

It works on AOSP like ROMs (Pixel / Android One). If manufacturers make major UI changes to the ROM from Android 9 to Android 10, I need tickets with debug logs for each ROM to teach SD Maid to recognize it.
