### ISSUE TITLE
Bug:Connection to sessions.bugsnag.com even disabling Bug Reporting options

### ISSUE THREAD

**Issue by Jorgu81** [d4rken/sdmaid-public#2400]
**What happened?**
When I disable the three options in the Bug Reporting section it still connects to sessions.bugsnag.com

**What did you expect to happen?**
Not to connect to this host

**How can I reproduce the issue?**
Force closing the app and opening afterwards the program connects to the domain. You can see in AdAway or Afwall firewall.

**SD Maid**
SD Maid versions 4.13.3 and maybe 4.13.2

**Device**
Lenovo P2 rooted with Magisk and running LineageOs 15.1 (Android 8.1)

**Comments**
I attach a log file
[sdmaid_logfile_1553106995460.txt](https://github.com/d4rken/sdmaid-public/files/2989665/sdmaid_logfile_1553106995460.txt)

**Comment by d4rken** [comment]
The log at least shows

```
1553107014565  I/SDMaid: Installing Bugsnag NOP error handler due to user opt-out!
```

maybe the bugsnag client still creates a connection when initializing, even if no actual reports will be send when a crash happens.

**Comment by d4rken** [comment]
Could reproduce. Should be fixed in the next non beta version
