### ISSUE TITLE
recycle bin (samsung galaxy S8)

### ISSUE THREAD

**Issue by ahk1973** [d4rken/sdmaid-public#2401]
Hello there. I am a Samsung Galaxy S8 user and I am in the android pie version. In my device's gallery, the Trash can delete photos that are not completely deleted to restore when necessary. "SD Maid will find a solution, otherwise I will have to delete your application, thanks.

**Comment by d4rken** [comment]
Please provide the packagename of the gallery app and the path of the trash files.

**Comment by SuperSandro2000** [comment]
It is this one https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-gallery/

I think the gallery just moved or renames the files to a "trash bin" folder and does not really delete the files.
Hit me up if you need someone to test. I have a S8 with Pie, too.

**Comment by d4rken** [comment]
To get this going I'd need someone that does a pathdump on the folder that contains the files to delete. I currently don't have the time to install the app and do my own investigation.

**Comment by SuperSandro2000** [comment]
The actual image files are not touched. I guess the gallery app just hides the files for itself.

**Comment by d4rken** [comment]
stale
