### ISSUE TITLE
Clutterreport: /storage/0BBB-1EF5/Android/data/com.lge.hiddenmenu (FP)

### ISSUE THREAD

**Issue by DJBowling** [d4rken/sdmaid-public#2408]
### Target
Target: `/storage/0BBB-1EF5/Android/data/com.lge.hiddenmenu`
Prefix-free: `com.lge.hiddenmenu`
Path-prefix: `/storage/0BBB-1EF5/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `lge/mcv7a_spr_us/mcv7a:8.1.0/O11019/190081322fe34:user/release-keys`

### Comment
`Backup/photos.donotdelete
`

**Comment by DJBowling** [comment]
I am completely lost, can anyone help??

**Comment by JavkhlanK** [comment]
What the heck are you doing?

**Comment by DJBowling** [comment]
JavkhlanK  I have no clue obviously, I however realize what I posted but I'm in the very early learning stage, been having issues with hacks and deleted files and folders and can't seem to get any real experienced help... I don't know how to clear it completely off of here, "IF" I even can??!!....😣🙃😕😔😵
