### ISSUE TITLE
Feature Request: Add secure over the air updates for clutter and hidden caches

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#2413]
Atm it may not be the most secure and sensible option, but long term, why not add it for user convenience? No need for an update to update the clutter and hidden caches. Of course, still bundle the freshest definitions with each update. Some major competition has this feature. Add IAPs as well to make it make more sense.
Device: Pixel XL
Android version: Stock 9 Pie with March 2019 updates
Root status: Rooted with Magisk 18.1
SD Maid version: Internal 4.14.0

**Comment by d4rken** [comment]
Dup #153
