### ISSUE TITLE
Clutterreport: /storage/6AA3-3F59/Ams_vault (new)

### ISSUE THREAD

**Issue by cyasucka** [d4rken/sdmaid-public#2430]
### Target
Target: `/storage/6AA3-3F59/Ams_vault`
Prefix-free: `Ams_vault`
Path-prefix: `/storage/6AA3-3F59/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `ADWLauncher EX`
Packagename: `org.adwfreak.launcher`
Version: `1.3.3.9 (48)`

### Current owners
None

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `samsung/j7popqltetfnvzw/j7popqltetfnvzw:6.0.1/MMB29M/S727VLUDU3ARC1:user/release-keys`

**Comment by d4rken** [comment]
I don't think this is correct.
