### ISSUE TITLE
Intermittent Scheduled Reboot, boots to bootloader

### ISSUE THREAD

**Issue by ThatJeffGuy** [d4rken/sdmaid-public#2437]
- Magisk 19
- Pixel 2 April 2019 Update
- No Xposed
- SD Maid Pro, 4.13.4
- Clean installed April Update, no data restore (I wanted a clean start)

Scheduled reboot, full device reboot (not "hot"), reboots occasionally to the bootloader, and then sits there until user interaction starts the device.

Bootloader mode will not auto-exit due to inactivity, so scheduling maintenance overnight means a potentially missed morning alarm to get up for work.. this *totally* didn't happen to me this morning.

Since the reboot was successful, there's no actual log detail, however I can replicate this on about 1/10 reboots by setting scheduler to reboot in 1 minute from current test time. It runs the scheduled tasks then reboots, but about 1/10 times, stays at the bootloader screen (android with ! icon in belly, etc.)

The "hot" reboot isn't affected by this, for obvious reasons.

Scheduled Tasks:
Corpse Finder, Delete
SystemCleaner, Delete
AppCleaner, Delete
Databases, Optimize
Reboot, Full Reboot
Time: 11am now, but originally had it at 4am

**Comment by d4rken** [comment]
This feature didn't change much since #188. The full reboot still uses `am start -a android.intent.action.REBOOT` to trigger the reboot, if that doesn't work it will fall back to just `reboot`.

Is it exactly after 10 times or still random?

Start a debug recording before the reboot and finish it afterwards, the log should show which method SD Maid uses to trigger the reboot.

I'm unsure how I could solve this though as I don't think either of the commands is wrong, though maybe there is a more specific command available on newer Android version since #188.

When in debugging (or experimental?) there should be a "Play button" that just launches the scheduler without timer, you could use it for easier testing. I also have a Pixel2 with Magisk, I'll try to reproduce it.

**Comment by d4rken** [comment]
I uses `am start -a android.intent.action.REBOOT` on mine, so I'd guess on yours too.

**Comment by ThatJeffGuy** [comment]
It seemingly is random - roughly 1/10 times it reboots to bootloader.

I rebooted my phone manually and eventually with Tasker every morning, and only SDMaid caused this intermittent issue.

Let me perform some more tests with debugging on - where are the logs stored for attachment?

**Comment by d4rken** [comment]
`Android/data/eu.thedarken.sdm/cache/logfiles` but when you stop the recording it should offer you the path and to share.

**Comment by ThatJeffGuy** [comment]
With the status Armed: False, as I don't want it to actually reboot every test, it still reboots :(

Any way to have that toggle part of the simulate action?

I can't save the debug log/recording - launching SDM after reboot doesn't start the recording as per the wiki/howto

**Comment by d4rken** [comment]
> With the status Armed: False, as I don't want it to actually reboot every test, it still reboots :(
> Any way to have that toggle part of the simulate action?

Hm yeah, next update, :wink: 

> I can't save the debug log/recording - launching SDM after reboot doesn't start the recording as per the wiki/howto

That's a bug I just noticed too, looking into it, it works across SD Maid sessions, weird.

That said, I've done 13 reboots now (through SD Maid) and can't reproduce it. If it only happens with SD Maid then the it must be related to the used reboot command, you should see in superuser logs which command the other apps use.

But: The system itself uses the same one though AFAIK, so I think it's just chance that you only reproduced it with SD Maid, but it's not limited to SD Maid.

**Comment by ThatJeffGuy** [comment]
I'll keep an eye on it and test again after the next update.

In my testing with you here, I also was not able to replicate.. might have been more rare than my original 1/10.. however I did replicate it this morning about 3 times with about 30 reboots..

**Comment by d4rken** [comment]
Just fixed the debug log issue, that was a good one to find, thanks :+1:.

Did another 8 reboots without reproducing it though :man_shrugging: Pixel2@9 with Magisk 18

**Comment by d4rken** [comment]
The debug log fix should be in v4.14.0 whic is available as beta now.

**Comment by d4rken** [comment]
Please reopen if this is still and issue and you found any new information.
