### ISSUE TITLE
Clutterreport: /storage/emulated/0/Alan Walker - Faded ������ Bass Boosted ������.m4a (new)

### ISSUE THREAD

**Issue by ashish280007** [d4rken/sdmaid-public#2450]
### Target
Target: `/storage/emulated/0/Alan Walker - Faded ������ Bass Boosted ������.m4a`
Prefix-free: `Alan Walker - Faded ������ Bass Boosted ������.m4a`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `xiaomi/tissot/tissot_sprout:9/PKQ1.180917.001/V10.0.7.0.PDHMIXM:user/release-keys`

### Comment
`unable to delete it`

**Comment by d4rken** [comment]
Please record a debug log of SD Maid trying to delete it:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
