### ISSUE TITLE
Request Fitur HIBERNATION

### ISSUE THREAD

**Issue by Antokta** [d4rken/sdmaid-public#2453]
Request new features; hibernation application mode no root by utilizing system administration. Thanks

**Comment by pusri34567** [comment]
Me Also

**Comment by d4rken** [comment]
What do you mean by "hibernation" and what do you mean by "system administration"?

**Comment by Antokta** [comment]
Hibernation help you identify and put the misbehaving apps into hibernation when you are not actively using them, to stop them from lagging your device or leeching the battery, in a unique way! and system administration (DEVICE ADMIN) : This app uses administrator privilege to turn off the screen immediately after automated hibernation on non-root devices.

**Comment by d4rken** [comment]
I'm unclear on the requirements. When is an app "misbehaving" and how would SD Maid detect that?

Which function that requires device administrator privileges would SD Maid use to "hibernate" the apps?

**Comment by Antokta** [comment]
Accessibility + Accessibility service and device administrator.

I sent videos and screenshots of the requirements for how to detect applications in the background that are commonly used by many other applications.

**Comment by d4rken** [comment]
[Screenshot_2019-04-08-01-55-28-06_1554664614607](https://user-images.githubusercontent.com/1439229/55712538-33a4b980-59ef-11e9-876a-008751362167.png)
[Screenshot_2019-04-08-01-54-24-89_1554664403401](https://user-images.githubusercontent.com/1439229/55712539-343d5000-59ef-11e9-9ff5-81ca347b1afc.png)
[Screenshot_2019-04-08-01-53-38-03_1554663637984](https://user-images.githubusercontent.com/1439229/55712540-343d5000-59ef-11e9-8d02-738679bb10e4.png)
[Screenshot_2019-04-08-01-54-12-64_1554663467900](https://user-images.githubusercontent.com/1439229/55712541-343d5000-59ef-11e9-9f7c-82b7eab35a05.png)

This feature is out of SD Maids scope.
