### ISSUE TITLE
Clutterreport: /storage/emulated/legacy/ScreenRecorderWithInternalAudio/recording_20190407_032507.mp4 (new)

### ISSUE THREAD

**Issue by fariel36** [d4rken/sdmaid-public#2454]
### Target
Target: `/storage/emulated/legacy/ScreenRecorderWithInternalAudio/recording_20190407_032507.mp4`
Prefix-free: `ScreenRecorderWithInternalAudio/recording_20190407_032507.mp4`
Path-prefix: `/storage/emulated/legacy/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Screen Recorder with Internal Audio`
Packagename: `com.gravitycommunications.screen.recorder.with.internal.audio.screenrecorderwithinternalaudio`
Version: `1.0.5 (5)`

### Current owners
None

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `Lenovo/cm_Lenovo_P1m/Lenovo_P1m:5.1.1/LMY49J/1c5065c957:userdebug/test-keys`

**Comment by d4rken** [comment]
What a long packagename :laughing:
