### ISSUE TITLE
Bug: App cleaner with accessibility setting enabled causes SD Maid to crash

### ISSUE THREAD

**Issue by ToniDolphin** [d4rken/sdmaid-public#2457]
### What happened?
Can't enable the Accessibility for the App cleaner, if enabled it causes SD Maid to stop working. So I have to disable Accessibility and perform cache cleaning manually.

### What did you expect to happen?
I expected the APP CLEANER to work with the Accessibility setting enabled

### How can I reproduce the issue?
Enable SD Maid in the Accessibility settings and run APP CLEANER

### Comments
Please let me know when this issue is fixed

### SD Maid
Version: `4.14.0 (41400)`
Unlocker: `4.3.6 (40306) (true)`

### Device
Root: `Unknown`
Fingerprint: `ZTE/Z982/crocus:7.1.1/NMF26V/20180914.042313:user/release-keys`

**Comment by d4rken** [comment]
Can you post your install ID?

(Long press "Settings" in SD Maid)

What ROM and language?

**Comment by ToniDolphin** [comment]
Hi d4rken,

My install ID: 
5286e153-127f-4ff4-910e-9c0154ce3e8c

Model number
Z982
Android version
Android security patch level
September 1, 2018
Baseband version
Z982H01
Kernel version
3.18.31-perf-g132f55c-00955-gbbfddb5
zte-kernel@Zdroid-SMT
Build number
Z982_0MV1.0.0B03
Hardware version
Z982HW1.0

Language: English

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.IllegalStateException** in **AppCleanerDetailsPagerActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5ca7ca3f4fcb3d0019025820?event_id=5caaf6c90037e637cef30000&i=gh&m=li)

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.NullPointerException** in **SDMMainActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5ca7ca70bc828400197ea014?event_id=5caaf7cb0037dd8549d10000&i=gh&m=li)

**Comment by d4rken** [comment]
Both times it should have resulted in an error message, but not in a crash:

As far as I can tell, SD Maid clicked another entry (I think the "Permission Storage" one), and then fails to find the "Clear Cache" button.

Not sure yet why it crashes and not catches the error and then returns an error result.

**Comment by d4rken** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**java.lang.IllegalStateException** in **SDMMainActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5ca7ca3f4fcb3d0019025820?event_id=5caf3d80003817a56ec20000&i=gh&m=fx)

**Comment by d4rken** [comment]
As far as I understand it, the crash came from two crashes overlapping.
I've improved the related code a lot and we'll have to test this again in v4.14.1.
