### ISSUE TITLE
Bug: SD Maid crashes when opening the scheduler settings for the first time

### ISSUE THREAD

**Issue by Yowlen** [d4rken/sdmaid-public#2466]
### What happened?
The app crashes when going to Settings > Scheduler for the first time.

### What did you expect to happen?
I expect it to open the settings as per normal.

### How can I reproduce the issue?
Clear the app data, then open the settings and attempt to open the scheduler subsection.

### Comments
I found this while testing for #2465. It will work on subsequent tries, so I assume this is an issue with the default config variables from initial setup and the crash routine then resets it to a proper variable that it can work with.

### SD Maid
Version: `4.14.0 (41400)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `Unknown`
Fingerprint: `samsung/on7xelteins/on7xelte:7.0/NRD90M/G610FXXU1BRB4:user/release-keys`

**Comment by d4rken** [comment]
It was a racecondition between the settings UI being loaded, and a following routine that sets the correct states for some settings.
In this case it was the UI trying to disable the "minimum battery level entry" if "skip on low battery" was not enabled.

Subsequent loads likely used a cached UI fragment such that the timing worked out.
On one device it never happened, on another one (slower one) it always happened.

While fixing this I also added a "reset to default" options like the other tools have and improved the code responsible for synchronizing between UI and settings object a bit.
