### ISSUE TITLE
Clutterreport: /system/plugin/FwkPlugin (FP)

### ISSUE THREAD

**Issue by madnessgl** [d4rken/sdmaid-public#2467]
### Target
Target: `/system/plugin/FwkPlugin`
Prefix-free: `plugin/FwkPlugin`
Path-prefix: `/system/`
Type: `DIRECTORY`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `FwkPlugin`
Packagename: `com.mediatek.fwk.plugin`
Version: `1.0 (1)`

### Current owners
None

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `ZTE/P635A60_AU_TLS/P635A60:6.0/MRA58K/20161206.195344:user/release-keys`

**Comment by d4rken** [comment]
Clutter reports for  `SYSTEM` are currently not supported.
