### ISSUE TITLE
Corpse Finder failing to find asec corpses

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#247]
Originally reported by: **Anonymous**

---

Corpse Finder won't search for asec files on SD card. Needs to look for dead asec files located in /mnt/secure/asec as well as /mnt/asec in addition to /data/app-asec. The issue is discussed on XDA beginning (http://forum.xda-developers.com/showthread.php?p=61675296)

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/249

**Comment by prasanthrn2k** [comment]
My app stopped or crashed pro user  prasanthrn2k@gmail.com registered for Beta is it because of that?

**Comment by d4rken** [comment]
@prasanthrn2k Possibly but what does that have to do with this ticket?
