### ISSUE TITLE
Clutterreport: /storage/79BF-1DEB/Download/21.mp4 (FP)

### ISSUE THREAD

**Issue by Rhynodeeds** [d4rken/sdmaid-public#2474]
### Target
Target: `/storage/79BF-1DEB/Download/21.mp4`
Prefix-free: `Download/21.mp4`
Path-prefix: `/storage/79BF-1DEB/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Chrome Dev`
Packagename: `com.chrome.dev`
Version: `75.0.3752.2 (375200232)`

### Current owners
Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `8.0.0 (26)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `7.20.9 (72000900)`

Appname: `Android System`
Packagename: `android`
Version: `8.0.0 (26)`

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `lge/h1_vzw/h1:8.0.0/OPR1.170623.032/182811215750c:user/release-keys`

**Comment by Rhynodeeds** [comment]
...

**Comment by d4rken** [comment]
Please elaborate

**Comment by Rhynodeeds** [comment]
I'm on disability for mental illness legitimately I get a check every month my mom's my payee I got an okay sweetheart mint on a nice side of town right out of prison to no background check because my dad name somebody all of a sudden some dick head at this leasing place decided that because I've had 911 here kind of frequently because of my mental illness and that I don't get along with everybody because of my antle illness I'm a little different I'm being discriminated against and he's giving me two weeks till you just apartment I need attention and weapons right pointed at apartment Mart which is located in Bloomington Illinois on Linden Street can you help me?

**Comment by Rhynodeeds** [comment]
My phone number is 309-824-1178 my best email address is rhynodeeds@gmail.com  text or whatever for email me I'm on Facebook as well just Ryan Dorn and I'm located in Bloomington Illinois
