### ISSUE TITLE
Clutterreport: /data/app/com.android.vending-1/oat/arm/base.odex (FP)

### ISSUE THREAD

**Issue by louieslide** [d4rken/sdmaid-public#2476]
### Target
Target: `/data/app/com.android.vending-1/oat/arm/base.odex`
Prefix-free: `com.android.vending-1/oat/arm/base.odex`
Path-prefix: `/data/app/`
Type: `FILE`
Location: `APP_APP`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Google Play Store`~~
~~Packagename: `com.android.vending`~~
~~Version: `14.3.18-all [0] [PR] 241092342 (81431800)`~~

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `google/shamu/shamu:6.0.1/MOB31H/3234857:user/release-keys`

**Comment by louieslide** [comment]
This Google play store versions says that I am not certified..it have a certificate..it limits me to what I can get on the play store and runs extremely slow..don't know why, but I downloaded an earlier version and it work just fine.

**Comment by d4rken** [comment]
I don't understand what this has to do with this file.
