### ISSUE TITLE
Bug: AppCleaner results showing after QuickAccess

### ISSUE THREAD

**Issue by RockwellB1** [d4rken/sdmaid-public#2486]
### What happened?
Like the title says. I run QuickAccess and once it finishes task results for AppCleaner is coming up now. Happening on Note 9 Pie and Tab S3 Oreo.

### What did you expect to happen?
For it to stay on the QuickAccess overview so i could see the results from all tasks.

### How can I reproduce the issue?
Just run QuickAccess with AppCleaner included. Specifically i have CorpseFinder, SystemCleaner, AppCleaner, and Databases selected to run and delete in one pass.

### Comments
Great app, keep it up!

### SD Maid
Version: `4.14.0 (41400)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/crownqltesq/crownqltesq:9/PPR1.180610.011/N960USQU1CSC1:user/release-keys`

**Comment by d4rken** [comment]
Are you using the Accessibility service for the AppCleaner?

**Comment by d4rken** [comment]
Could reproduce, it's related to the accessibility service.
