### ISSUE TITLE
Bug: A translate issues in Chinese

### ISSUE THREAD

**Issue by Ezawa-Akihiko** [d4rken/sdmaid-public#2487]
### What happened?
Byte,M and G have been translated

### What did you expect to happen?
Other things been translated but no need to translate the unit

### How can I reproduce the issue?
there's no need to translate them

### SD Maid
Version: `4.14.0 (41400)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/SC-01L/SC-01L:8.1.0/M1AJQ/SC01LOMU1ARL4:user/release-keys`

**Comment by d4rken** [comment]
Hi,

Can you give me an example on which screen this happens?
I don't think I can change this though as I don't translate the labels, but use a system function:

https://developer.android.com/reference/android/text/format/Formatter.html

**Comment by d4rken** [comment]
Don't think I can do anything about that :(.
