### ISSUE TITLE
accelerometer high usage

### ISSUE THREAD

**Issue by patrickdrd** [d4rken/sdmaid-public#2488]
![Screenshot_20190415-125818](https://user-images.githubusercontent.com/24896778/56129625-4a1cb900-5f8b-11e9-889c-afcfee7717b6.png)

why so much accelerometer usage?

**Comment by d4rken** [comment]
SD Maid doesn't use the accelerometer. 

Which app is that on the screenshot?

**Comment by patrickdrd** [comment]
[gsam battery monitor](https://play.google.com/store/apps/details?id=com.gsamlabs.bbm&hl=el)

**Comment by d4rken** [comment]
I'm not sure if GSAM interprets the stats wrong or if the system counts the time against both but it seems to count any wakelock time, additionally as accelerometer time.

e.g. if you download my wakelock app and acquire a wakelock it will also start increasing the accelerometer time in GSAM.

You'll have to ask the GSAM dev why it counts wakelock time as accelerometer time.

Regarding wakelocks itself:
SD Maid acquires one for the duration that tasks are running, after the last task finishes it is released again. If something goes wrong, there is also a timeout that will release the wakelock after 10 min.

As far as I'm aware there is no issues with the wakelock release. If you find a case where SD Maid is leaking wakelocks, please create a new ticket with steps to reproduce it and I'll look into it.

**Comment by patrickdrd** [comment]
![Screenshot_20190415-162023](https://user-images.githubusercontent.com/24896778/56136307-32e5c780-5f9b-11e9-8f0c-8f8cf0f17c38.png)

BetterBatteryStats shows accelerometer too, but much less time (7min),
maybe it was the timeout case you mentioned
