### ISSUE TITLE
accessibility service unable to clear cache

### ISSUE THREAD

**Issue by floh96** [d4rken/sdmaid-public#2491]
What happened?
SD Maid was not able to clear the cache from SamsungDLPService with accessibility service
Error message: Error during Spec(label=Launch settings(com.samsung.android.dlp.service))

What did you expect to happen?
Cache should be cleared

How can I reproduce the issue?
Try to clear the cache of SamsungDLPService with accessibility service

Comments
Debug Log: https://drive.google.com/open?id=1cW2TGKgHLYGvjACvt9Ek_RQ0BJmV-YGD

SD Maid
Version: 4.14.1 (41401) [360cd22b3, 2019-04-16T16:37:16Z]
Unlocker: 4.3.7 (4037)

**Comment by d4rken** [comment]
Do other apps work?

Can you record a video of this?

According to the log SD Maid waits for the systems window of the app to show (expects "com.android.settings"), but cam't find that window on screen.

**Comment by floh96** [comment]
Does clearing other apps than this one work?
Yes, but now i have the same error for the facebook app. Recorded a video.
Can you record a video of this?
https://drive.google.com/file/d/1ihcD17OzPZaQxc5vwcoDt_dm3Vtm0zX2/view?usp=sharing
(I restarted the cleaning once wen it closed itself.)

**Comment by d4rken** [comment]
Btw for testing you can long press SD Maids settings button and then toggle "Armed" to false, it will then simulate deletion so you keep some files for testing ;).

If the video shows the same issue as in the log, then SD Maid doesn't recognize the settings window although it's open.

There short set (4) events from `com.android.settings` followed by lots of events from SD Maid again (e.g. on screen events).

The current "root" of the UI tree is SD Maid instead of the settings app.

**Comment by floh96** [comment]
Yeah it seems to be the same error. What do you need that you can fix it more logs?

**Comment by d4rken** [comment]
Hm no the logs are good, they show though that SD Maid is working as expected, the system just isn't giving us what we expect. I think we can try an approach where SD Maid will opt to just launch the same window again until we get what we want (as it seems to work with other apps, just randomly with some not).

Thinking about the timings, we need to wait at least X after the window is opened, where X is the amount of time it takes until the window displays something that SD Maid can read, and then if we can't find what we want after X+Y we launch the window again.

This might need some trial&error. From the video i'd say it takes 2-3 seconds until the window content becomes visible the first time for each app.

Can you mail me at support@darken.eu so we can exchange a few test versions in private?

**Comment by floh96** [comment]
send you an email

**Comment by d4rken** [comment]
I think we fixed the initial issue.

Let's create a new ticket if the current issue persists in v4.14.2
