### ISSUE TITLE
Bug: Clean cache

### ISSUE THREAD

**Issue by lordballiwns** [d4rken/sdmaid-public#2492]
### What happened?
Application > (app[x]) > storage > clean cache 

### What did you expect to happen?
Application > (app[x]) > storage > clean cache 

### How can I reproduce the issue?
Application > (app[x]) > storage > clean cache 

### Comments
I'm not writing - speaking English 

### SD Maid
Version: `4.14.1 (41401)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Polaroid/PSPCL20A0/PSPCL20A0:7.0/NRD90M/1536975036.01:user/release-keys`

**Comment by d4rken** [comment]
I need more details.

**Comment by d4rken** [comment]
v4.14.2 will contain major improvements to the accessibility based deletion option, if the issue persists, please create a new ticket with more details.

**Comment by turbo25** [comment]
The problem still persists, on Motorola Moto x4 and Android 9 the automation gets in a loop and doesn't do anything.

**Comment by d4rken** [comment]
@turbo25 Please make a new ticket for this and record a debug log of this happening:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
