### ISSUE TITLE
Clutterreport: /storage/emulated/0/Anime247

### ISSUE THREAD

**Issue by ILoveCreepers** [d4rken/sdmaid-public#2494]
### Target
Target: `/storage/emulated/0/Anime247`
Prefix-free: `Anime247`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Anime 247`
Packagename: `xyz.kicu.animevsub`
Version: `1.27 (28)`

### Current owners
Appname: `?`
Packagename: `xyz.kicu.animetv`
Version: `null (0)`

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `Nokia/Panda_00WW/PDA_sprout:9/PPR1.180610.011/00WW_2_14B:user/release-keys`

**Comment by d4rken** [comment]
#2500

I think we should keep the old packagename, as not all users will always update to the newest version with the different packagename.

**Comment by ILoveCreepers** [comment]
The developer got their app deleted by the Play Store for some "reasons", they just change the package name and re-up the app.

**Comment by d4rken** [comment]
If we remove the old package name from SD Maids database and users update SD Maid before they get the new app, SD Maid might delete this folder.

There is really no downside to keeping both relations in the database.

**Comment by d4rken** [comment]
> The developer got their app deleted by the Play Store for some "reasons"

Probably copyright issues? Though no one really knows why Google does what Google does :man_shrugging: 

Updated for next update :grin:.

**Comment by ILoveCreepers** [comment]
Also the corpses finder think that the app was uninstalled so it keep delete it data when I run a Quick Access clean.

**Comment by d4rken** [comment]
> Also the corpses finder think that the app was uninstalled so it keep delete it data when I run a Quick Access clean.

Because it doesn't know that the packagename changed (yet), this will be in v4.14.2

**Comment by ILoveCreepers** [comment]
It deleted a 2 GB folder before I realise that 😂
