### ISSUE TITLE
Bug: bnjakait1@gmail.com

### ISSUE THREAD

**Issue by benatdjakait** [d4rken/sdmaid-public#2495]
### What happened?
Sdmaid has no configuration to proceed with the settings she demands (rooted)

### What did you expect to happen?
To run and delete the contents in the so called"premium feature"

### How can I reproduce the issue?
To aweken the startup feature and checkingbox configuration

### Comments
Sdmaid is my favorite cleaner and a small development will be highly appreciated

### SD Maid
Version: `4.14.1 (41401)`
Unlocker: ` (0) (false)`

### Device
Root: `Unknown`
Fingerprint: `Itel/I806/itel-P31:7.0/NRD90M/P31-I806-7.0-OP-V035-20180420:user/release-keys`

**Comment by d4rken** [comment]
I don't know what you are talking about :(
