### ISSUE TITLE
Bug: Error during Spec

### ISSUE THREAD

**Issue by charlybaer0366** [d4rken/sdmaid-public#2502]
### What happened?
Programm Starts and aborted by AppCleaner

### What did you expect to happen?
The AppCleaner ends normaly an not with a crash

### How can I reproduce the issue?
Start it normaly the ends Codes 

### SD Maid
Version: `4.14.1 (41401)`
Unlocker: `4.3.6 (40306) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/gts4lwifixx/gts4lwifi:8.1.0/M1AJQ/T830XXU2ARK4:user/release-keys`

**Comment by d4rken** [comment]
What language is the device on?

**Comment by d4rken** [comment]
#2503
