### ISSUE TITLE
Bug: Error during Spec (label=Find & click 'Clean Cache' (com.huawei.camera))

### ISSUE THREAD

**Issue by charlybaer0366** [d4rken/sdmaid-public#2503]
### What happened?
It crashed by AppCleaner.         

### What did you expect to happen?
That Programm ends normally.    

### How can I reproduce the issue?
Start it the end comes.         

### SD Maid
Version: `4.14.2 (41402)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `HONOR/COL-L29/HWCOL:9/HUAWEICOL-L29/207C432R1:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debuglog of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by charlybaer0366** [comment]
Here the Log file
-----------------------------




Rechtliche Hinweise:




Diese elektronische Nachricht enthält vertrauliche Informationen, die nur 
für die im Text bezeichneten Personen bestimmt sind. Die Nachricht ist 
durch das Briefgeheimnis geschützt und unterliegt gegebenenfalls den Regeln 
zum Schutz der Vertraulichkeit. Jede Benutzung, Versendung, Herstellung von 
Kopien oder Veröffentlichung durch andere Personen ist ohne Zustimmung des 
Absenders untersagt. Wenn Sie diese Nachricht irrtümlich erhalten haben, 
bitten wir Sie höflichst, sie auf Ihren Systemen zu löschen und den 
Absender umgehend zu benachrichtigen.




This electronic mail transmission contains confidential information 
intended only for the person(s) named. It is subject to the laws of mail 
secrecy and may be protected by legal privileges. Any use, distribution, 
copying or disclosure by another person is strictly prohibited without the 
consent of the sender. If this transmission has been received in error, you 
are kindly requested to delete it from your system and to contact the 
sender immediately.
Am 19. April 2019 09:38:39 schrieb Matthias Urhahn <notifications@github.com>:

**Comment by d4rken** [comment]
I don't see the logfile, I think it might not work via email to github.

If you can't attach it here, you can mail it to support@darken.eu while referencing this ticket.

**Comment by charlybaer0366** [comment]
I have packed the file in .zip because the mail comes return it is to long. 
Sorry!
-----------------------------




Rechtliche Hinweise:




Diese elektronische Nachricht enthält vertrauliche Informationen, die nur 
für die im Text bezeichneten Personen bestimmt sind. Die Nachricht ist 
durch das Briefgeheimnis geschützt und unterliegt gegebenenfalls den Regeln 
zum Schutz der Vertraulichkeit. Jede Benutzung, Versendung, Herstellung von 
Kopien oder Veröffentlichung durch andere Personen ist ohne Zustimmung des 
Absenders untersagt. Wenn Sie diese Nachricht irrtümlich erhalten haben, 
bitten wir Sie höflichst, sie auf Ihren Systemen zu löschen und den 
Absender umgehend zu benachrichtigen.




This electronic mail transmission contains confidential information 
intended only for the person(s) named. It is subject to the laws of mail 
secrecy and may be protected by legal privileges. Any use, distribution, 
copying or disclosure by another person is strictly prohibited without the 
consent of the sender. If this transmission has been received in error, you 
are kindly requested to delete it from your system and to contact the 
sender immediately.
Am 19. April 2019 11:53:24 schrieb Matthias Urhahn <notifications@github.com>:

**Comment by d4rken** [comment]
Thanks for the logfile, it was perfect.

The issue is caused by ROM differences.

My Android Version: `Cache leeren`.
Your Android Version: `Cache löschen`.

Will be fixed with the next update :+1:
