### ISSUE TITLE
Bug: Start key

### ISSUE THREAD

**Issue by benatdjakait** [d4rken/sdmaid-public#2504]
### What happened?
Still displaying payment restriction

### What did you expect to happen?
To disappear after ticking the orange icon

### How can I reproduce the issue?
Send the start key required by PlayStore

### Comments
Every thing is OK except that

### SD Maid
Version: `4.14.1 (41401)`
Unlocker: ` (0) (false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Itel/I806/itel-P31:7.0/NRD90M/P31-I806-7.0-OP-V035-20180420:user/release-keys`

**Comment by d4rken** [comment]
Not sure what you mean, got screenshots?
