### ISSUE TITLE
Clutterreport: /storage/emulated/0/mobilism

### ISSUE THREAD

**Issue by xorcan** [d4rken/sdmaid-public#2505]
### Target
Target: `/storage/emulated/0/mobilism`
Prefix-free: `mobilism`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `org.mobilism.android`
Version: `null (0)`

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `OnePlus`

### Comment
`this is backup for whitelist `

**Comment by d4rken** [comment]
I need some more details about this
