### ISSUE TITLE
Clutterreport: /storage/0403-0201/SHAREit

### ISSUE THREAD

**Issue by KPP6** [d4rken/sdmaid-public#2507]
### Target
Target: `/storage/0403-0201/SHAREit`
Prefix-free: `SHAREit`
Path-prefix: `/storage/0403-0201/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.lenovo.anyshare`
Version: `null (0)`

Appname: `?`
Packagename: `com.lenovo.anyshare.gps`
Version: `null (0)`

### SD Maid
Version: `4.14.1 (41401)`

### Device
Fingerprint: `google/taimen/taimen:9/PQ2A.190305.002/5240760:user/release-keys`

### Comment
`Clear only cache and thumbnails related junks. Exclude major directories i.e. files, audios, pictures, videos etc.`

**Comment by d4rken** [comment]
Hi,

I'm not sure what you are talking about, can you elaborate?

**Comment by KPP6** [comment]
I meant that it detecting desirable remnants from sdcard's ShareIt folder i.e. sensitive images, docs, videos, apks with useless caches. (I have the app uninstalled though, is it the reason)

P.S. Thank you, for this awesome maid ;-)

**Comment by d4rken** [comment]
> (I have the app uninstalled though, is it the reason?!)

Yes. If you need it, either disable "show desirable remnants" in the options or add an exclusion.
