### ISSUE TITLE
/data/data/com.android.chrome/app_chrome/GrShaderCache/GPUCache/

### ISSUE THREAD

**Issue by patrickdrd** [d4rken/sdmaid-public#2513]
/data/data/com.android.chrome/app_chrome/GrShaderCache/GPUCache/
should be deleted I think

**Comment by patrickdrd** [comment]
actually these are the files of chrome I'm deleting:

```
data/data/com.android.chrome/app_tabs/*/*
data/data/com.android.chrome/app_chrome/.*/Bookmarks.bak
data/data/com.android.chrome/app_chrome/Default/IndexedDB/http.*indexeddb.leveldb.*$
data/data/com.android.chrome/app_chrome/BrowserMetrics.*$
data/data/com.android.chrome/app_chrome/GrShaderCache/GPUCache/
```

**Comment by d4rken** [comment]
I've made some improvements to the WebView filter. Added better matching for `GrShaderCache` and `GPUCache`, the others should be left alone.

**Comment by patrickdrd** [comment]
the others should be deleted too, I'm deleting them on both my desktop/laptop 
(except the first one which exists only on android) and
eventually on two mobile devices too without any problem

**Comment by d4rken** [comment]
Changing this affects millions of devices, not just yours, so we have to be careful.

`BrowserMetrics` could be added to the analytics filter, if you can share some more details on that in an extra ticket I'll look into it for the next update.

Deleting `app_tabs` clears the list of open tabs in Chrome, this is not something I want usually.

Not sure about `Default/IndexedDB/http.*indexeddb.leveldb*` this would need further investigation, as well as `Bookmarks.bak`. Each would deserve an extra ticket with more details.

**Comment by patrickdrd** [comment]
correct, https://wiki.mozilla.org/Browser_Metrics is related to analytics,
also https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/zKSMVrpFVK8,
I would add it to analytics filter

bookmarks.bak is, as the name implies, a bookmarks backup,
which I personally don't need, because I'm using titanium backup and
my bookmarks are synced with my laptop/desktop too, 
I've also got a bookmarks file kept separately (taken from windows chrome,
which I upload to my google drive as well)

indexeddb files are only usefiul on windows as well,
since there is extensions' data there:
https://github.com/MoscaDotTo/Winapp2/issues/320
(and which I have excluded from cleanup on windows of course)
in android, where we don't have extensions I would say it's pretty much useless

as for app_tabs, I found 1000+ files there, 
even though I always close all open tabs before closing chrome,
so I think there could be leftovers, at least in my case
I'm using custom tabs a lot too (since lynket: https://play.google.com/store/apps/details?id=arun.com.chromer&hl=el is my default browser),
but why would I want a custom tab's state?

I understand your fist line, of course, after all it's your decision to make
