### ISSUE TITLE
Clutterreport: /storage/BF6A-11E9/Boom Player(3)/ca/boomplayer.db (new)

### ISSUE THREAD

**Issue by benatdjakait** [d4rken/sdmaid-public#2525]
### Target
Target: `/storage/BF6A-11E9/Boom Player(3)/ca/boomplayer.db`
Prefix-free: `Boom Player(3)/ca/boomplayer.db`
Path-prefix: `/storage/BF6A-11E9/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Boomplay`
Packagename: `com.afmobi.boomplayer`
Version: `4.0.8 (528)`

### Current owners
None

### SD Maid
Version: `4.14.6 (41406)`

### Device
Fingerprint: `Itel/I806/itel-P31:7.0/NRD90M/P31-I806-7.0-OP-V038-20190401:user/release-keys`

**Comment by d4rken** [comment]
Can't confirm this.
