### ISSUE TITLE
Clutterreport: /storage/emulated/0/.thumbnails/.thumbdata-7.0_1

### ISSUE THREAD

**Issue by benatdjakait** [d4rken/sdmaid-public#2528]
### Target
Target: `/storage/emulated/0/.thumbnails/.thumbdata-7.0_1`
Prefix-free: `.thumbnails/.thumbdata-7.0_1`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Intent Filter Verification Service`
Packagename: `com.android.statementservice`
Version: `1.0 (1)`

### Current owners
Appname: `?`
Packagename: `com.sec.android.app.videoplayer`
Version: `null (0)`

### SD Maid
Version: `4.14.6 (41406)`

### Device
Fingerprint: `Itel/I806/itel-P31:7.0/NRD90M/P31-I806-7.0-OP-V038-20190401:user/release-keys`

**Comment by d4rken** [comment]
This is not a correct match. That app doesn't own that path.
