### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/ATV(you.love.atv.eng)-6.2(50).apk (FP)

### ISSUE THREAD

**Issue by shresthamanju272** [d4rken/sdmaid-public#2531]
### Target
Target: `/storage/emulated/0/Download/ATV(you.love.atv.eng)-6.2(50).apk`
Prefix-free: `Download/ATV(you.love.atv.eng)-6.2(50).apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `com.android.backupconfirm`
Packagename: `com.android.backupconfirm`
Version: `6.0.1 (23)`

### Current owners
Appname: `Android system`
Packagename: `android`
Version: `6.0.1 (23)`

Appname: `?`
Packagename: `com.android.providers.downloads.ui`
Version: `null (0)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `6.0.1 (23)`

### SD Maid
Version: `4.14.6 (41406)`

### Device
Fingerprint: `samsung/j7e3gxx/j7e3g:6.0.1/MMB29K/J700HXXS3BRL1:user/release-keys`

**Comment by shresthamanju272** [comment]
Why atv and other one apps is not working

**Comment by JavkhlanK** [comment]
Are you sure? This is in the Downloads Folder and a apk...

**Comment by d4rken** [comment]
I agree with @JavkhlanK , this seems like a non-sense report.
