### ISSUE TITLE
Bug: AppControl - scanning rearranges sorting

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#2537]
### What happened?
User loads up AppControl, then sorts app as they desire, in my case by last update.  I scanned an app, package name com.vzw.apnlib. Then I went back to the AppControl list and the scanned entry was put to the bottom of the list. Scanning additional entries does the same.

### What did you expect to happen?
The sorting (in my case by last update) would remain the same.

### How can I reproduce the issue?
Load up AppControl. Sort by last update. Scan an app and see if it changes the position in the AppControl results list. 

### Comments
Check with different sorting methods as well.

### SD Maid
Version: `4.14.8 (41408)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `Unknown`
Fingerprint: `google/crosshatch/crosshatch:9/PQ2A.190405.003/5310204:user/release-keys`

**Comment by d4rken** [comment]
Can't reproduce.

**Comment by d4rken** [comment]
Can reproduce on system apps, but not all, seems random? Doesn't happen with Chrome or GPlay, but e.g. with live wallpaper.

**Comment by mcl21014** [comment]
Can only reproduce on system apps, and certain ones at that. All the Verizon bloat that starts with vzw seems to be affected by this bug.
