### ISSUE TITLE
Request: AppControl - Add ACS cleaning per app

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#2547]
### What should the feature do?
When loading an app's details under AppControl, the user should be able to clear the cache via the accessibility service.

### When/How would you use it?
Whenever I wanna clean an app on an unrooted device.

### How would you implement it?
Via AppControl details.

### SD Maid
Version: `4.14.8 (41408)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `google/crosshatch/crosshatch:9/PQ3A.190505.002/5450365:user/release-keys`

**Comment by d4rken** [comment]
The user can do this via appcleaner already, I don't think it's necessary to add this to app control, the scan overhead wouldn't be worth it, asbitsbnot trivial, we still need to scan almost everything to determine the caches for a single app accurately.
