### ISSUE TITLE
Clutterreport: /storage/emulated/0/Telegram/Telegram Video/5_6334677003223957569.mp4 (FP)

### ISSUE THREAD

**Issue by 3xploiton3** [d4rken/sdmaid-public#2550]
### Target
Target: `/storage/emulated/0/Telegram/Telegram Video/5_6334677003223957569.mp4`
Prefix-free: `Telegram/Telegram Video/5_6334677003223957569.mp4`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Telegraph`
Packagename: `ir.ilmili.telegraph`
Version: `T5.4.0 - P7.1.1 (15255)`

### Current owners
Appname: `Telegram`
Packagename: `org.telegram.messenger`
Version: `5.5.0 (15457)`

Appname: `?`
Packagename: `org.telegram.plus`
Version: `null (0)`

Appname: `?`
Packagename: `org.thunderdog.challegram`
Version: `null (0)`

### SD Maid
Version: `4.14.7 (41407)`

### Device
Fingerprint: `xiaomi/whyred/whyred:8.1.0/OPM1.171019.011/V10.2.2.0.OEIMIXM:user/release-keys`

**Comment by 123456788h** [comment]
# @d4rken
