### ISSUE TITLE
Bug: Android 10 - Slow performance

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#2557]
### What happened?
I go to use a tool, such as the CorpseFinder, and the device lags like heck. The UI even lags.

### What did you expect to happen?
No noticable lag in SD Maid, the system, or UI.

### How can I reproduce the issue?
Use any tool as far as I'm aware. Not reproducable 100% of the time but most of the time. Not yet sure of the circumstances.

### Comments
Running Q Beta 3.

### SD Maid
Version: `4.14.8 (41408)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/marlin/marlin:10/QPP3.190404.015/5505587:user/release-keys`

**Comment by d4rken** [comment]
What does the progress bar display when it's bring slow?

I'll likely need a debug recording from SD Maid with a simultaneous logcat recording to debug this.

**Comment by mcl21014** [comment]
Ok. Will do soon as I get to my beta testing device.

**Comment by mcl21014** [comment]
Here is a log of slow analysis via the SystemCleaner. I didn't delete anything, though. https://mega.nz/#!Ld0HgSpB!_pNUVN68imf_S5gbZwt8WCaKc40YbFT5-DzeZX-4-PA

**Comment by d4rken** [comment]
I think was fixed in the recent Android Q beta, was it?
