### ISSUE TITLE
Clutterreport: /storage/emulated/0/log (new)

### ISSUE THREAD

**Issue by epiccakeking** [d4rken/sdmaid-public#2558]
### Target
Target: `/storage/emulated/0/log`
Prefix-free: `log`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Galaxy Wearable`
Packagename: `com.samsung.android.app.watchmanager`
Version: `2.2.24.19031361 (2119031361)`

### Current owners
None

### SD Maid
Version: `4.14.7 (41407)`

### Device
Fingerprint: `ZTE/Z971/peony:7.1.1/NMF26V/20180818.181041:user/release-keys`

Edit: storage/emulated/0/log/GearLog may be better...

**Comment by d4rken** [comment]
Ah okay so this is a folder. I agree that /log/ would be a bit too common.
Are there other folders in /log/ ?

Can you show me what is inside "GearLog", should this be added to the AppCleaner too?

**Comment by epiccakeking** [comment]
![Screenshot_20190510-122107~2](https://user-images.githubusercontent.com/33770464/57551595-4aa43780-731e-11e9-8c39-f00776e5b5ae.png)

GearLog is the only folder in /log/ and deleting it doesn't seem to do anything, not sure if deleting it automatically would be a good idea though...
