### ISSUE TITLE
Granting usage statistics permission on Android TV

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2559]
Usage statistics permission might not exist on Android TV?

A user reported that nothing happens when clicking the "allow" button.

Theoretically the permission could still exist, but the intent to open the correct settings page does not?

**Comment by mcl21014** [comment]
Definitely doesn't exist on the Fire Stick.

**Comment by d4rken** [comment]
Seems to exist at least on Android TV with Android 8 but it doesn't support opening on that screen directly.
Adding a fallback where SD Maid shows the app settings screen from which the user will have to find their own way.

**Comment by d4rken** [comment]
`settings put secure enabled_accessibility_services eu.thedarken.sdm/.accessibility.core.ACCService`

**Comment by Werve** [comment]
Thanks, i did it and no error reported.
But the app stll doesnt work... maybe there is no accessibility services on fire tv...

**Comment by Werve** [comment]
Actually after a reboot it asked again the usage stats permission so I think is not the case.

**Comment by d4rken** [comment]
Sorry don't have a TV device, you will have to tinker with it a bit more, I know that some users got it working, but maybe it's different TV devices?

**Comment by oldman20** [comment]
> settings put secure enabled_accessibility_services eu.thedarken.sdm/.accessibility.core.ACCService

is it right?
adb  shell settings put secure enabled_accessibility_services eu.thedarken.sdm/eu.thedarken.sdm.accessibility.core.ACCService
