### ISSUE TITLE
Clutterreport: /storage/emulated/0/Pictures/Telegram (FP)

### ISSUE THREAD

**Issue by f8192** [d4rken/sdmaid-public#2562]
### Target
Target: `/storage/emulated/0/Pictures/Telegram`
Prefix-free: `Pictures/Telegram`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Telegram`
Packagename: `org.telegram.messenger`
Version: `5.6.0 (15877)`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `9 (28)`~~

### SD Maid
Version: `4.14.7 (41407)`

### Device
Fingerprint: `xiaomi/whyred/whyred:8.1.0/OPM1.171019.011/V9.5.11.0.OEIMIFA:user/release-keys`

**Comment by d4rken** [comment]
already added.
