### ISSUE TITLE
Clutterreport: /storage/emulated/0/X-plore settings backup/X-plore settings 2019.05.04 09.58.53.zip (new)

### ISSUE THREAD

**Issue by 8Ball683** [d4rken/sdmaid-public#2564]
### Target
Target: `/storage/emulated/0/X-plore settings backup/X-plore settings 2019.05.04 09.58.53.zip`
Prefix-free: `X-plore settings backup/X-plore settings 2019.05.04 09.58.53.zip`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `X-plore`
Packagename: `com.lonelycatgames.Xplore`
Version: `4.14.09 (41409)`

### Current owners
None

### SD Maid
Version: `4.14.7 (41407)`

### Device
Fingerprint: `samsung/gtaslitelteuc/gtaslitelteatt:8.1.0/M1AJQ/T387AAUCU1ASC3:user/release-keys`

**Comment by d4rken** [comment]
Hm is this really a default order?
