### ISSUE TITLE
Bug Quick access

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#2567]
Even after closing the SD Maid continues to show to delete the items I checked earlier.  The correct would be if I close the SD Maid should I make quick new search to delete the items and not the previous search I did not delete.  This error happens when accessibility is enabled, because even by closing the SD Maid it continues running in the background.
![Screenshot_20190512-025159_SD Maid](https://user-images.githubusercontent.com/8754997/57578409-12a60d00-7462-11e9-8ef7-85d9996e5928.jpg)

**Comment by d4rken** [comment]
How did you close SD Maid?

Does it make a different if you use the backbutton or swipe it from recent tasks or a combination thereof?

**Comment by GabrielMGitHub** [comment]
Only closes if I force closure on application information, but disable accessibility.  Any other way I close the application is running because accessibility is active, so the cleanup stays there until I click "Run Now".

**Comment by d4rken** [comment]
The accessibility service itself is a system process and not subject to SD Maids lifecycle, I think it might be keeping SD Maid alive.

I'm not sure whether we can decouple the lifecycles. I can not just turn the accessibility service on/off programmatically.

One workaround would be to forcibly clear SD Maids data on exit.

**Comment by GabrielMGitHub** [comment]
When closing, it would have to abort the previous check, but because accessibility is active, the application continues to run even if it closes.

**Comment by d4rken** [comment]
What "previous check"?

**Comment by GabrielMGitHub** [comment]
When you click to search for quick access, it does not click to clear and close the application.  If the person opens SD Maid two days later, that search, stays there until you click clean, but this search will not have the waste of these two days.

It's a bit difficult for me to explain why I'm Brazilian and my native language is Portuguese.

**Comment by d4rken** [comment]
My current understanding of the issue you described:

With the accessibility service enabled, SD Maid does not fully close like before.
When opening SD Maid again old results are still present and this makes it difficult to use QuickAccess.

**Comment by GabrielMGitHub** [comment]
Yes, because the previous search is shown, but in the example I passed, and if the user opens the application only days later, this search that got stuck will not show the current days waste.  You will have to click clean and then re-search and clean again.

**Comment by d4rken** [comment]
Possibly solutions, thinking out loud...

* Kill the accessibility service (ACS) via PID on double-back exit, then hope the system removes SD Maid from memory before the ACS is relaunched
* On double back, send cancel to all services and clear all worker data.
* Check references from within the ACS are keeping SD Maid in memory and whether we can remove those references.

**Comment by d4rken** [comment]
I think I found a simpler solution, there was a bug when calling SD Maids `reset()` function, SD Maid checked a variable that was never assigned under some circumstances.

**Comment by GabrielMGitHub** [comment]
If you have a trial version I can test it.

**Comment by d4rken** [comment]
New beta will be available in an hour at the latest.

**Comment by GabrielMGitHub** [comment]
Resolved in part, but caused other bugs.

**Comment by GabrielMGitHub** [comment]
Clicking on "back" once, opens the menu.

![Screenshot_20190514-204951_SD Maid](https://user-images.githubusercontent.com/8754997/57739404-db19a980-7689-11e9-8e49-ec2ba38cf058.jpg)

Clicking "back" twice closes the application.

![Screenshot_20190514-205116_SD Maid](https://user-images.githubusercontent.com/8754997/57739489-22079f00-768a-11e9-9414-8d8a4d4d2fae.jpg)

If I click recent and then pull up to close the SD Maid still continues to show the previous fetch on the next application run.

![Screenshot_20190514-205348_SD Maid](https://user-images.githubusercontent.com/8754997/57739658-d86b8400-768a-11e9-9731-eb6a0bd7c336.jpg)
![Screenshot_20190514-205415_One UI Home](https://user-images.githubusercontent.com/8754997/57739663-de616500-768a-11e9-8551-c3c50d22be09.jpg)
![Screenshot_20190514-205925_SD Maid](https://user-images.githubusercontent.com/8754997/57739747-2e402c00-768b-11e9-88d0-62df05273b23.jpg)

**Comment by GabrielMGitHub** [comment]
Another bug
If I leave "Quick Access" selected and double-click to exit and then run SD Maid, whatever item I select in Quick Access, the menu is opening together.

![Screenshot_20190514-210531_SD Maid](https://user-images.githubusercontent.com/8754997/57739993-17e6a000-768c-11e9-87c7-cc563e36948f.jpg)
![Screenshot_20190514-210550_SD Maid](https://user-images.githubusercontent.com/8754997/57740003-21700800-768c-11e9-8bdd-3b24feb20de9.jpg)

**Comment by GabrielMGitHub** [comment]
One more bug

If I let the "Quick Access" selected close the application with two clicks, running the SD Maid again shows the window of the previously selected item (Quick Access).

![Screenshot_20190514-211251_SD Maid](https://user-images.githubusercontent.com/8754997/57740221-136eb700-768d-11e9-88b1-c63f029d0f03.jpg)

If I leave any other item selected and close the application with two clicks, running SD Maid again shows the menu above the item.

![Screenshot_20190514-211515_SD Maid](https://user-images.githubusercontent.com/8754997/57740291-68123200-768d-11e9-95d7-423a6f21d04b.jpg)

**Comment by GabrielMGitHub** [comment]
@d4rken look above.

**Comment by d4rken** [comment]
> https://github.com/d4rken/sdmaid-public/issues/2567#issuecomment-492453541

I think this has always been the case, hasn't it? There might be a small difference between ROMs, I think the recent tasks dismiss behavior is not always the same. In any case, if you make a new ticket, we can discuss changing this too.

> https://github.com/d4rken/sdmaid-public/issues/2567#issuecomment-492454951

Yeah that's a bug :frowning: due to the new navigation code, good catch :+1: . Can you make a new ticket for this too?

> https://github.com/d4rken/sdmaid-public/issues/2567#issuecomment-492456492

This has always been the case, as far as I know. If you'd like to discuss changing this, new ticket please :wink: .

**Comment by d4rken** [comment]
Fixed https://github.com/d4rken/sdmaid-public/issues/2567#issuecomment-492454951 in code just now :+1:

**Comment by GabrielMGitHub** [comment]
Very good to have corrected, I opened the other tickets
