### ISSUE TITLE
Statistics pie issues

### ISSUE THREAD

**Issue by eboye** [d4rken/sdmaid-public#2574]
Not a big problem, but just wanted to report that percentages are overlapping

![Screenshot_20190515-052841_SD_Maid](https://user-images.githubusercontent.com/624357/57746688-9403d680-76d2-11e9-9101-3b4d850a1e40.png)

**Comment by d4rken** [comment]
Dup of #1187 
Not nice, but not a huge UI issue, sadly not easily fixable afaik, as I would have to rewrite the whole chart library to fix it?

See #1187, do you see any other solution?
