### ISSUE TITLE
Navigationdrawer behaves differently when resuming QuickAccess

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#2578]
If I let the "Quick Access" selected close the application with two clicks, running the SD Maid again shows the window of the previously selected item (Quick Access).

![Screenshot_20190514-211251_SD Maid](https://user-images.githubusercontent.com/8754997/57740221-136eb700-768d-11e9-88b1-c63f029d0f03.jpg)

If I leave any other item selected and close the application with two clicks, running SD Maid again shows the menu above the item.

![Screenshot_20190514-211515_SD Maid](https://user-images.githubusercontent.com/8754997/57740291-68123200-768d-11e9-95d7-423a6f21d04b.jpg)

**Comment by d4rken** [comment]
This is working as intended, or at least how it is in previous versions too.

The most common use-case is that people stay on the QuickAccess page, opening the menu automatically would require 1 extra click to dismiss it and use QuickAccess, but when people reopen SD Maid on any other page, it is likely that they want to switch pages, so the menu will be automatically open the first time.

I've made a small tweak to this in v4.14.10, but I think the general behavior is good. :thought_balloon:
