### ISSUE TITLE
Bug Debug

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#2584]
![Screenshot_20190515-194739_SD Maid](https://user-images.githubusercontent.com/8754997/57814563-6b1f2800-774a-11e9-97fb-4d8a6494c65d.jpg)
![Screenshot_20190515-194703_SD Maid](https://user-images.githubusercontent.com/8754997/57814564-6b1f2800-774a-11e9-8da4-c2dff23e0545.jpg)
![Screenshot_20190515-194716_SD Maid](https://user-images.githubusercontent.com/8754997/57814565-6bb7be80-774a-11e9-8c39-b3fd6c18c058.jpg)

**Comment by d4rken** [comment]
This is the debug menu, it's intended that you can show the dialog manually.

**Comment by GabrielMGitHub** [comment]
But is it correct to ask me to buy the PRO version even though I have the PRO version?

**Comment by d4rken** [comment]
Yes.

The button says "Show IAP Dialog", you click it and the purchase dialog is shown.

It is a debug menu, it's for testing, users don't go there normally.

**Comment by GabrielMGitHub** [comment]
Now I understood, I thought it was a feature, where to have access I needed to have the paid version.
