### ISSUE TITLE
Bug Ticket Problems.

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#2586]
There is no send button.

![Screenshot_20190516-192758_SD Maid](https://user-images.githubusercontent.com/8754997/57891649-7dfd2f80-7812-11e9-815e-882d93f9de17.jpg)

**Comment by spicyfoxx** [comment]
28 characters required. You need more text to be able to send the ticket.

**Comment by GabrielMGitHub** [comment]
> 28 characters required. You need more text to be able to send the ticket.

Lack of attention on my part, you really need a title with 8 characters, and other boxes 32 characters.  Thank you.
