### ISSUE TITLE
Redesign of Quickaccess

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#259]
Originally reported by: **Bitbucket: [d4rken](http://bitbucket.org/d4rken), GitHub: [d4rken](http://github.com/d4rken)**

----------------------------------------

The Quickaccess screen could make better use of the space.
One idea would be to reduce the padding between entries and use list items instead of cards.

----------------------------------------
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/261

**Comment by D0r4** [comment]
Kinda like a checkerboard look if u understand me?

**Comment by d4rken** [comment]
Should fit nicely on phone screens now. Tablet is for another task.
