### ISSUE TITLE
Bug: FAB-Icon sometimes not showing

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#2594]
![Screenshot_20190519-140331](https://user-images.githubusercontent.com/40118124/57982017-7cfd1580-7a3f-11e9-959e-1c0ea926d9b6.png)
### What happened?
I started SD Maid and selected Explorer. Then the FAB-Image was totally green/not visible

### What did you expect to happen?
I thought the image wouldn't be green/transparent

### How can I reproduce the issue?
Try starting SD Maid sometimes. 

### Comments
What's up?

### SD Maid
Version: `4.14.11 (41411)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS8CSC2:user/release-keys`

**Comment by d4rken** [comment]
I have a hard time reproducing this.
Looking at the code I saw one potential cause though and made some changes.
This might affect other tools too that don't have a FAB that switches state (scan/delete), e.g. AppControl, Searcher. 
Let me know if this happens in the next update.
