### ISSUE TITLE
Request: Hidden caches: com.xda.labs

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#2596]
### What should the feature do?
Clean out the hidden caches for the package name com.xda.labs.

### When/How would you use it?
Whenever I run SD Maid and want to clear out app caches.

### How would you implement it?
Through the AppCleaner as a filter.

### Comments
APK inside was deleted and no nasty surprises. Think it contains APK files and maybe even Xposed zips. Stuff cached that the user has downloaded. Pathdump: 
google/crosshatch/crosshatch:9/PQ3A.190505.002/5450365:user/release-keys

FILE       660 10149: 9997    3.09 MB 2019.05.19 18:29:13 /storage/emulated/0/Android/data/com.xda.labs/files/a84a0910-7b06-4629-b87b-480ab63d496c_2710.apk

### SD Maid
Version: `4.14.12 (41412)`
Unlocker: `4.3.8 (40308) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/crosshatch/crosshatch:9/PQ3A.190505.002/5450365:user/release-keys`

**Comment by spicyfoxx** [comment]
Did you try using accessibility service?

**Comment by d4rken** [comment]
Is there a pattern to it?

`files/a84a0910-7b06-4629-b87b-480ab63d496c_2710.apk` is very generic and we can't just match `files` which would surely delete too much.
