### ISSUE TITLE
Clutterreport: /storage/9C33-ACA4/Jay Google pics (new)

### ISSUE THREAD

**Issue by cornfed79** [d4rken/sdmaid-public#2621]
### Target
Target: `/storage/9C33-ACA4/Jay Google pics`
Prefix-free: `Jay Google pics`
Path-prefix: `/storage/9C33-ACA4/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Drive`
Packagename: `com.google.android.apps.docs`
Version: `2.19.152.06.46 (191520646)`

### Current owners
None

### SD Maid
Version: `4.14.13 (41413)`

### Device
Fingerprint: `lge/joan_att_us/joan:8.0.0/OPR1.170623.026/191121131d721:user/release-keys`

**Comment by d4rken** [comment]
Custom dir, not a default one.
