### ISSUE TITLE
Clutterreport: /storage/emulated/0/com.sdk.ida.callvu (new)

### ISSUE THREAD

**Issue by djjeew** [d4rken/sdmaid-public#2625]
### Target
Target: `/storage/emulated/0/com.sdk.ida.callvu`
Prefix-free: `com.sdk.ida.callvu`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `לאומי`
Packagename: `com.leumi.leumiwallet`
Version: `30.5 (762)`

### Current owners
None

### SD Maid
Version: `4.14.4 (41404)`

### Device
Fingerprint: `Xiaomi/beryllium/beryllium:8.1.0/OPM1.171019.026/V10.0.6.0.OEJMIFH:user/release-keys`

**Comment by d4rken** [comment]
I don't think these two are related, got some more info?

**Comment by djjeew** [comment]
Sorry for the delay @d4rken,just saw your comment.

Yes,it is related.

That is the contents of the folder **com.sdk.ida.callvu** that I labeled:

![WhatsApp Image 2019-06-13 at 23 22 40](https://user-images.githubusercontent.com/40543822/59464961-7ab98b80-8e32-11e9-8033-85fe88191be5.jpeg)

Inside that folder there is the same icon as the app Leumi(לאומי).

**Comment by d4rken** [comment]
Hm, will have to do some lookup on the SDK dir itself, might be used by other apps too?

**Comment by djjeew** [comment]
So,made a little investigation here.

Googled the **callvu** word.

Quoitng their site:

> CallVU addresses the business need of diverting calling customers to digital self-service while optimizing the efficiency of calls that are put through to a live agent. Our Digital Engagement Platform reduces the call volume placed on contact centers, ensures higher usage of digital assets and facilitates better customer experiences.
>CallVU’s advanced suite of Digital Engagement Platforms comprises Visual-IVR, Conversational-IVR, Agent-Caller Collaboration, Service BOT, and Digital Forms. Each one blends rich digital and interactive media with web, voice and social channels.

This is the following [app](https://play.google.com/store/apps/details?id=com.ida.callvu&hl=en) that I found in playstore.
In addition to this at their sirte there is an [article](https://callvu.com/post_trusted/leumi-bank/) about their collaboration with **Leumi Bank**,that I labeled in pull-request.
So at the end it suites for this folder to be related to the banks(I have an account in Israeli bank Leumi for example).

This is the company that provides self-service solutions(i.e GUI ) for call centers,tech-support of the companies. 

For example:if you call your bank in oreder to check out current balance,this app is automatically redirects you to the auto-generated web-page of the bank and at this page you have possibility to check your balance account,your line credit,to choose for the appropriate time to get the call back from the tech-support without waisting your time on the line.
[Youtube Link](https://www.youtube.com/watch?v=jQD8Pnz-Zxg)
[Youtube Link #2](https://www.youtube.com/watch?v=nNI26j1bz20)

So,in theory,this app can be connected to any other app that uses the call centers(Banks,Insurance Companies,Telecoms ,etc)
In reality this are the companies I found in their [**"honorable mentions"**](https://callvu.com/post_trusted/) section of the site.
After scouting this page,it is clear to me that most of the companies are Israeli based : Leumi bank , Pelephone etc.

It's really strange that this folder(**com.sdk.ida.callvu**) is popped up in my file system,I remember using some sort of the features of CallVu years ago,I had  a different smartphone (I called the bank number,recevied link to the web page,checked some boxes and after some hours recieved the call from the bank)
**But it seemes that this features are gone away**

So,it seems to me that this service, despite having android application(CallVu) is provides servers,and web-based pages to the companies.

I'm hoping that this information can be usefull for you.
