### ISSUE TITLE
Permission Error Memory Card

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#2634]
When you open SD Maid for the first time and then click on settings only and shown to give permission for internal storage.  However when you open the SD Plus for the first time and click on any cleanup it asks for permission from the internal storage and from the memory card.

**Comment by d4rken** [comment]
Interesting!
Will look into it.

**Comment by d4rken** [comment]
I can't reproduce this on an Android emulator, can you still reproduce it on the latest beta?

**Comment by GabrielMGitHub** [comment]
Yes, you should test on a real handset.

**Comment by d4rken** [comment]
Bought a Nokia 8.1, can reproduce now.

**Comment by d4rken** [comment]
This was a good bug to find. :heart: 

Going to settings triggers the setup, but also blocks until the setup is complete.
The blocking part of this calls a function that only returns after setup is complete, but inadvertently also triggered the setup itself.

This lead to a situation where the setup was initialized too early and information about storage was not available yet.

**Comment by BostonPilot** [comment]
> This was a good bug to find. 
> 
> Going to settings triggers the setup, but also blocks until the setup is complete.
> The blocking part of this calls a function that only returns after setup is complete, but inadvertently also triggered the setup itself.
> 
> This lead to a situation where the setup was initialized too early and information about storage was not available yet.

Thats great, how is this fixed? The latest beta still has this bug.

**Comment by d4rken** [comment]
@BostonPilot You are the first one telling me about this. So I assume the underlying issue described here was fixed. Please create a new bug ticket so we can separately investigate your issue.
