### ISSUE TITLE
Still lots of /data/**/inaccessible items

### ISSUE THREAD

**Issue by freitasfabiano** [d4rken/sdmaid-public#2646]
Hi,

After running the AppCleaner, a lot of _inaccessible_ items are still around. I suppose this is because I am using an unrooted phone. If so, do you think it would be a better idea to hide those items (or have an option to do so) from the results on unrooted phones?

![15596167432550](https://user-images.githubusercontent.com/7709813/58849143-a03edc00-865f-11e9-9ffa-1de3f1fc55d0.png)

![15596167433101](https://user-images.githubusercontent.com/7709813/58849157-af258e80-865f-11e9-9e5b-be0deb475b80.png)

Best regards.

**Comment by d4rken** [comment]
> If so, do you think it would be a better idea to hide those items (or have an option to do so) from the results on unrooted phones?

There is an option to do that:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#show-inaccessible-items

> After running the AppCleaner, a lot of inaccessible items are still around. I suppose this is because I am using an unrooted phone. 

If you are using the accessibility service option, then there is a chance that SD Maid doesn't recognize the necessary elements in the system screens. You would see SD Maid repeatedly trying the same app again, then giving up after ~20 seconds. This can be fixed if you show me the screens such that I can see what SD Maid is not understanding. A debug log would also be good:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

Alternatively, everything went well, but those caches are not deletable. You can try to go into the system settings for one of those apps, press "Clear cache", then exit and re-enter that screen and check whether it still shows the same sizes. We'd need root here for SD Maid to not depend on system provided data.

**Comment by freitasfabiano** [comment]
> There is an option to do that:
> https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#show-inaccessible-items

OK, now I get it. Thanks for the link. This clears things up a bit (mainly about the fake files thingy).
 
> If you are using the accessibility service option, then there is a chance that SD Maid doesn't recognize the necessary elements in the system screens. You would see SD Maid repeatedly trying the same app again, then giving up after ~20 seconds. This can be fixed if you show me the screens such that I can see what SD Maid is not understanding. A debug log would also be good:
> https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

No, it doesn't happen to me...

> Alternatively, everything went well, but those caches are not deletable. You can try to go into the system settings for one of those apps, press "Clear cache", then exit and re-enter that screen and check whether it still shows the same sizes. We'd need root here for SD Maid to not depend on system provided data.

This, however, happens to me. If I hit "Clear Cache" and then go back to that screen, it'll show the same values for cache size.

But that's okay for me.. I know what's going on with the app.

Thanks.
