### ISSUE TITLE
The "blank image" is not something we can easily delete, it's part of the chat database referencing the image thumbnail that was deleted.

### ISSUE THREAD

**Issue by patrickdrd** [d4rken/sdmaid-public#2647]
The "blank image" is not something we can easily delete, it's part of the chat database referencing the image thumbnail that was deleted.

If you mean deleting the files received through Viber, then this is certainly something I could add (like for WhatsApp). Please make another ticket for that if you are interested in such a feature.

_Originally posted by @d4rken in https://github.com/d4rken/sdmaid-public/issues/1482#issuecomment-361314268_

**Comment by patrickdrd** [comment]
can something be done about this?

maybe you've found a way?

I've created a system cleaner user rule to delete the images, 
but I have to go through each conversation to delete the thumbnail leftovers

**Comment by d4rken** [comment]
Modifying app databases of any kind in such a specific manner is too complex for SD Maids scope :disappointed:.

**Comment by patrickdrd** [comment]
ok, nevermind :)
