### ISSUE TITLE
Clutterreport: /storage/emulated/0/mtklog

### ISSUE THREAD

**Issue by jemchone** [d4rken/sdmaid-public#2652]
### Target
Target: `/storage/emulated/0/mtklog`
Prefix-free: `mtklog`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `8.1.0 (27)`

### Current owners
Appname: `?`
Packagename: `com.mediatek.mtklogger`
Version: `null (0)`

### SD Maid
Version: `4.14.14 (41414)`

### Device
Fingerprint: `TCL/5041C/U50A_ATT:8.1.0/OPM1.171019.011/v8M8Y-0:user/release-keys`

**Comment by jemchone** [comment]
Is this important

**Comment by d4rken** [comment]
I'm not sure but I'd say no.
