### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/Helios_7870-Pie.zip (FP)

### ISSUE THREAD

**Issue by bundie1990** [d4rken/sdmaid-public#2653]
### Target
Target: `/storage/emulated/0/Download/Helios_7870-Pie.zip`
Prefix-free: `Download/Helios_7870-Pie.zip`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `bootagent`
Packagename: `com.samsung.ucs.agent.boot`
Version: `8.1.0 (27)`

### Current owners
Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `8.1.0 (27)`

Appname: `Download manager`
Packagename: `com.android.providers.downloads`
Version: `8.1.0 (27)`

Appname: `Android System`
Packagename: `android`
Version: `8.1.0 (27)`

### SD Maid
Version: `4.14.18 (41418)`

### Device
Fingerprint: `samsung/j7popeltemtr/j7popeltemtr:8.1.0/M1AJQ/J727T1UVS5BSC2:user/release-keys`

**Comment by d4rken** [comment]
I don't think this is a correct match?
