### ISSUE TITLE
Clutterreport: /storage/emulated/0/Videoder Downloads (new)

### ISSUE THREAD

**Issue by spicyfoxx** [d4rken/sdmaid-public#2663]
### Target
Target: `/storage/emulated/0/Videoder Downloads`
Prefix-free: `Videoder Downloads`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Videoder Video Downloader`
Packagename: `com.rahul.videoderbeta`
Version: `14.2 (136)`

### Current owners
None

### SD Maid
Version: `4.14.19 (41419)`

### Device
Fingerprint: `samsung/a70qdx/a70q:9/PPR1.180610.011/A705FXXU2ASE8:user/release-keys`

**Comment by d4rken** [comment]
This will likely be files the user wants to keep after removing the app? e.g. should be flagged `keeper`?

**Comment by spicyfoxx** [comment]
I always forget check that.
