### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM/Video Editor (FP)

### ISSUE THREAD

**Issue by spicyfoxx** [d4rken/sdmaid-public#2666]
### Target
Target: `/storage/emulated/0/DCIM/Video Editor`
Prefix-free: `DCIM/Video Editor`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Video trimmer`
Packagename: `com.samsung.app.newtrim`
Version: `2.3.33.0 (233300000)`

### Current owners
~~Appname: `Android system`~~
~~Packagename: `android`~~
~~Version: `9 (28)`~~

### SD Maid
Version: `4.14.19 (41419)`

### Device
Fingerprint: `samsung/a70qdx/a70q:9/PPR1.180610.011/A705FXXU2ASE8:user/release-keys`

**Comment by d4rken** [comment]
![20190606_123012](https://user-images.githubusercontent.com/1439229/59018557-6ed43500-8846-11e9-8042-d6bea12ce78d.jpg)

**Comment by d4rken** [comment]
`DCIM/Video Editor` is such a generic name, will also have to mark this as `common`, in addition to `keeper` as this is stuff users will want to keep in any case.
