### ISSUE TITLE
App language only changes partially

### ISSUE THREAD

**Issue by freitasfabiano** [d4rken/sdmaid-public#2669]
Hi,

I have found a topic in which describes the exact same issue I'm having:

[Changing app language leaves some of the lines in original language](https://github.com/d4rken/sdmaid-public/issues/1619)

I have read it thoroughly and did all the steps you suggested (except making a video). The only way to have the app fully translated is to change the **device** language (i.e. setting en_US as primary language and leaving Portuguese as secondary).

Here are some screenshots:
![15598630848220](https://user-images.githubusercontent.com/7709813/59073382-4deafe80-889d-11e9-80db-ddb7d018110f.png)
![15598648805831](https://user-images.githubusercontent.com/7709813/59073387-53484900-889d-11e9-95e6-2bd489740c29.png)

The main menu and certain UI parts miss the translation.

I can provide further information, if need be.

Thank you.

**Comment by d4rken** [comment]
Did you reboot/force close SD Maid?

**Comment by d4rken** [comment]
Got a new test device, can reproduce this now. Looking into it.

**Comment by d4rken** [comment]
Got it fixed.
