### ISSUE TITLE
Bug: Debugging phone. Still having issues

### ISSUE THREAD

**Issue by gism4rc0s** [d4rken/sdmaid-public#2671]
### What happened?
Still very new with this app' but it is user error. Having issues removing a SQL system that was installed without permission. It seems to have thrown itself a big party  and every other APP  was invited... minus the owner. 

### What did you expect to happen?
I simply  want to remove this SQL due to some issues it has caused.

### How can I reproduce the issue?
I would like' to not' reproduce this issue.

### Comments
Short term: user downloads app. App works. User makes mistake. App throws party. Infects all apps. User sad  because not invited. All infected apps teasing user.  User sad. User wants move forward. 

### SD Maid
Version: `4.14.14 (41414)`
Unlocker: `4.3.8 (40308) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/crownqltesq/crownqltesq:9/PPR1.180610.011/N960USQS1CSE1:user/release-keys`

**Comment by d4rken** [comment]
I don't understand what you are talking about :frowning:

**Comment by gism4rc0s** [comment]
Sorry. I tried to make my description funny. A little bit more enjoyable at
least rather than reading someone inablitity to remove an SQL off this
phone.

**Comment by d4rken** [comment]
What is "an SQL"?
