### ISSUE TITLE
Bug: Auto cache deleting: Language problem

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#2673]
### What happened?
I switched my main language to English, but SD Maids language was German (DE). I wanted to clean the caches with the Accessibility Service.

### What did you expect to happen?
During AppCleaning, it can't find the matching text and can't clean the caches.

### How can I reproduce the issue?
Maybe change system language and keep SD Maid language.

### Comments
Hi!

### SD Maid
Version: `4.14.20 (41420)`
Unlocker: `4.3.8 (40308) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS8CSC2:user/release-keys`

**Comment by d4rken** [comment]
This seems to have been broken by:
https://github.com/d4rken/sdmaid-public/issues/2669

**Comment by d4rken** [comment]
A nice example of `Resources.getSystem()` vs `getContext().getResources()` :+1:
