### ISSUE TITLE
Fix grammar: 'have' should be changed to 'has'

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#268]
Originally reported by: **Shiv Manas (Bitbucket: [dextersgenius](http://bitbucket.org/dextersgenius), GitHub: [dextersgenius](http://github.com/dextersgenius))**

----------------------------------------

The text "##MB have been freed" should be changed to "##MB has been freed".

'Have' should be used in conjunction with plural terms, ie in case of Megabytes. So "## megabytes have been freed" is correct but "##MB have been freed" is incorrect.

----------------------------------------
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/270

**Comment by Avamander** [comment]
For me "2.85MB has been freed" sounds much better than "2.85MB have been freed" and "2.85MBs have been freed" but not "2.85MBs has been freed".

**Comment by dextersgenius** [comment]
Avamander is correct. According to Wikipedia [1], MB stands for Megabyte, which is a singular term. 
Therefore MBs would be the plural equivalent for Megabytes. So I would suggest either adding an 's' to the MB/GB suffixes, or changing have to has.

[1]. https://en.m.wikipedia.org/wiki/Megabyte

**Comment by Spire42** [comment]
I disagree. “MB” can stand for either “megabyte” or “megabytes”, so there is no need for an “s” for the plural. The correct forms are:

* 0 MB have been freed.
* 1 MB has been freed.
* 2 MB have been freed.

However, to avoid confusion, I suggest that the string simply be shortened to:

* 0 MB freed.
* 1 MB freed.
* 2 MB freed.

**Comment by d4rken** [comment]
I like the idea of shortening it.
And actually let's change the whole wording because "freed" is missleading.

For deletion lets just say "128MB deleted", and for actions like sql vacuum "128MB gained".
``` %s deleted ```
``` %s gained ```
Because with sparse files etc. 128MB deleted != 128MB gained.
