### ISSUE TITLE
Clutterreport: /storage/emulated/0/Music/FindSongs (FP)

### ISSUE THREAD

**Issue by fabalexsie** [d4rken/sdmaid-public#2684]
### Target
Target: `/storage/emulated/0/Music/FindSongs`
Prefix-free: `Music/FindSongs`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `FindSongs`
Packagename: `de.appsbyfabs.findsongs`
Version: `1.0 (2)`

### Current owners
~~Appname: `Android-System`~~
~~Packagename: `android`~~
~~Version: `7.0 (24)`~~

### SD Maid
Version: `4.14.14 (41414)`

### Device
Fingerprint: `Lenovo/kuntao_row/P2a42:7.0/NRD90N/P2a42_S251_171107_ROW:user/release-keys`

**Comment by d4rken** [comment]
Why did you close this? lgtm

**Comment by fabalexsie** [comment]
Because FindSongs isn't a public app. I wrote it myself. I just thought I can add the association local on my phone.

**Comment by d4rken** [comment]
Ah I understand. I wish you much success with your app.
