### ISSUE TITLE
Issues with AppCleaner on a non-root device

### ISSUE THREAD

**Issue by antonio-gil** [d4rken/sdmaid-public#2695]
### What happened?

Whenever I try to clear the caches, it seems ("behind" the overlay) that the Accessibility service successfully opens the "App Info" section, but it doesn't do anything there. Actually, it opens the "App Info" section a couple of times (ten times, if I'm counting correctly) before continuing to the next application on the list. And, I'm assuming that it is not doing anything because the cache size is the same after the process is done than it was before. Also, I've noticed that sometimes, by some unknown reason the process finished abruptly, and the Accessibility Service is disabled.

(The last part was already clarified on the SDMaid subreddit, but I'm mentioning it here for the sake of completeness)

### What did you expect to happen?

That the application's cache were deleted according to the current configuration.

### What actions did you take?

This happens whenever I run the AppCleaner module individually, or when running the QuickAccess operations.

### Can you reproduce it, i.e. does this happen everytime?

Yes, this happens every time.

Additionally, I take a look into the log, and something that I noticed is that (if I understandit correctly) it seems that there's a small discrepancy regarding the expected option (`Storage`) and the existing one (`Storage space`). Of course, I could be misinterpreting what I saw, but I got curious about it. 

---

### Additional Info:

**Device:** `Nokia 3.1`
**Android version:** `Stock Android One 9`
**Root:** `Unavailable`
**SD Maid / SD Maid Pro version:** `SD Maid v4.14.21, Unlocker v4.3.8`
**Install ID:** `8e69d020-1539-4abd-b200-417eceff5b2d`
**Debug Log:** [`sdmaid_logfile_1560215854679.txt.zip`](https://github.com/d4rken/sdmaid-public/files/3274428/sdmaid_logfile_1560215854679.txt.zip)
**Video:** [`recording_20190610_201744.zip`](https://github.com/d4rken/sdmaid-public/files/3274439/recording_20190610_201744.zip) (Disclaimer: It's an MP4 file, but I couldn't upload it as it is here, so I zipped it. Also, I **really don't know why**, but although it looks good on my device, on my computer it looks *weird* (as if a duplicated of the video was appended to the bottom of the video), nonetheless, the issue is visible). Also, I attach [an screenshot](https://user-images.githubusercontent.com/9835489/59238311-135eca00-8bed-11e9-9802-7df26629878d.png) taken after the video was recorded (you can check the clock), and the information on the AppCleaner module was refreshed (doing a "pulling down") in order to show that the cache size is still the same.

**Comment by d4rken** [comment]
> Actually, it opens the "App Info" section a couple of times (ten times, if I'm counting correctly) before continuing to the next application on the list.

SD Maid's retry+timeout mechanism.

> Additionally, I take a look into the log, and something that I noticed is that (if I understandit correctly) it seems that there's a small discrepancy regarding the expected option (Storage) and the existing one (Storage space). Of course, I could be misinterpreting what I saw, but I got curious about it.

That's exactly what it is. :+1:  Interesting that this is a stock ROM, as there is also a typo :astonished:, a missing space after the size.

![Screenshot from 2019-06-11 11-58-23](https://user-images.githubusercontent.com/1439229/59262960-7f1e5280-8c40-11e9-929a-b1bdee27d2e7.png)

Can you check whether the storage page's `Clear cache` is named exactly that? Maybe post a screenshot of that too. Would suck if I update for this only for SD Maid to be stuck on the next page :wink: 

btw, love the detailed ticket.

**Comment by antonio-gil** [comment]
Hi!

As requested, here is the requested screenshot:

- [Main Page](https://user-images.githubusercontent.com/9835489/59278694-1b882b00-8c28-11e9-9c55-28674d569a55.png) (just in case)
- [Storage Space Page](https://user-images.githubusercontent.com/9835489/59278695-1b882b00-8c28-11e9-9375-42a5481336f1.png)

If you need something else, please let me know.

>  Interesting that this is a stock ROM, as there is also a typo 😲

Haha I didn't noticed that! I guess that the guys on HDM Global didn't pay enough attention to that. 

> btw, love the detailed ticket.

Thank you sir! Glad to know that it was helpful 😁

**Comment by d4rken** [comment]
Thanks, will be fixed in the next update.
