### ISSUE TITLE
Clutterreport: /OP (FP)

### ISSUE THREAD

**Issue by Georgious40** [d4rken/sdmaid-public#2709]
### Target
Target: `/OP`
Prefix-free: `/OP`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Audiobooks`
Packagename: `sanity.freeaudiobooks`
Version: `1.13.3 (142)`

### Current owners
None

### SD Maid
Version: `4.14.22 (41422)`

### Device
Fingerprint: `lge/k6p_global_ca/k6p:6.0.1/MXB48T/180261825c32d:user/release-keys`

**Comment by Arnoldgenes** [comment]
🚬
