### ISSUE TITLE
purge app_webview folder for cookies and other privacy related data

### ISSUE THREAD

**Issue by bege10** [d4rken/sdmaid-public#2712]
Hi,
apps collect cookies and other data that can be used for tracking in the app_webview folders. I deleted the whole folders of some apps and they still run without problem. This may not be the case with every app, but weather forecasts, time table and ticket apps, email-clients work without problem on my phone. Of course, the folders are added again when using the apps again. Scheduling to purge the folders would be helpful for aggravating tracking.
Could SD Maid accomplish this on rooted phones?

**Comment by d4rken** [comment]
Maybe!

Can you share some paths? Preferably the output of SD Maids "Save directory structure" on the paths of interest.
There is a "WebView" filter already in the AppCleaner, maybe matching just needs to be improved.

**Comment by bege10** [comment]
> 
> 
> Maybe!
> 
> Can you share some paths? Preferably the output of SD Maids "Save directory structure" on the paths of interest.
> There is a "WebView" filter already in the AppCleaner, maybe matching just needs to be improved.

The "WebView" filter seems to be for the cache folder only.
The AppCleaner seems to clean only the /data/user_0 structure but not the /data/data structure which also contains an app_webview folder with privacy relevant data.

Where do I find SD Maids "Save directory structure"?

**Comment by d4rken** [comment]
> Where do I find SD Maids "Save directory structure"?

Explorer, optional action:
https://github.com/d4rken/sdmaid-public/wiki/explorer#save-directory-structure

**Comment by bege10** [comment]
[pathdump#_data_data_de.wetteronline.wetterapp_app_webview#1560698332842.txt](https://github.com/d4rken/sdmaid-public/files/3294254/pathdump._data_data_de.wetteronline.wetterapp_app_webview.1560698332842.txt)


The IndexedDB, Local Storage, Session Storage folders contain files that contain data showing visited sites and others. Of course the Cookies file contains tracking data, I don't know about the vaiations_seed and Web Data files.

**Comment by d4rken** [comment]
> The "WebView" filter seems to be for the cache folder only.
> The AppCleaner seems to clean only the /data/user_0 structure but not the /data/data structure which also contains an app_webview folder with privacy relevant data.

I'll try to reproduce this and fix it then, sounds like a bug. If that is fixed, do you still want to expand the matching or would that also cover your issue.

**Comment by d4rken** [comment]
While for a weather app it likely doesn't matter, for other apps deleting the webview including cookies and local storage could delete necessary login tokens.

**Comment by bege10** [comment]
Could this be accomplished as an "opt-in" option, so the user has to chose the apps where to delete? Or to have an option to add folders manually to the apps in the AppCleaner?

**Comment by d4rken** [comment]
> Could this be accomplished as an "opt-in" option, so the user has to chose the apps where to delete?
 
It could be, but I'm not sure if enough users would value such a feature that it warrants adding this as extra filter.

> Or to have an option to add folders manually to the apps in the AppCleaner?

Not to the AppCleaner but you can configure arbitrary paths for deletion via SystemCleaner custom filters.

**Comment by bege10** [comment]
Thanks.
