### ISSUE TITLE
Clutterreport: /storage/knox-emulated (FP)

### ISSUE THREAD

**Issue by zeus3041** [d4rken/sdmaid-public#2715]
### Target
Target: `/storage/knox-emulated`
Prefix-free: `/storage/knox-emulated`
Path-prefix: ``
Type: `SYMBOLIC LINK`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `My Knox`
Packagename: `com.sec.enterprise.knox.express`
Version: `2.0.18 (201800000)`

Appname: `com.sec.enterprise.knox.attestation`
Packagename: `com.sec.enterprise.knox.attestation`
Version: `1.0.1 (1)`

### Current owners
None

### SD Maid
Version: `4.14.22 (41422)`

### Device
Fingerprint: `samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUPQG1:user/release-keys`

**Comment by d4rken** [comment]
The mapping is likely correct but SD Maid does currently not support mapping this location.
