### ISSUE TITLE
Does not clean slingplayer app

### ISSUE THREAD

**Issue by joejoejo** [d4rken/sdmaid-public#273]
Sd maid does not clean slingplayer cache because it does not clean files in folders called file or files we need to teach sd maid that is an exception to the rule
attached is the pathdump
The pathdump is for slingplayer for phones but should be the same for slingplayer for tablets (com.slingmedia.slingPlayerTablet) slingplayer free for tablets (com.slingmedia.slingPlayerTabletFreeApp) and slingplayer free for phones (com.slingmedia.slingPlayerFreeApp) as they are based on the same code

[pathdump#_storage_emulated_0_Android_data_com.slingmedia.slingPlayer_files.txt](https://github.com/d4rken/sdmaid-public/files/75793/pathdump._storage_emulated_0_Android_data_com.slingmedia.slingPlayer_files.txt)

**Comment by d4rken** [comment]
Next update.
