### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/magisk_patched.img (FP)

### ISSUE THREAD

**Issue by kennet88** [d4rken/sdmaid-public#2734]
### Target
Target: `/storage/emulated/0/Download/magisk_patched.img`
Prefix-free: `Download/magisk_patched.img`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `null (0)`~~

Appname: `下载管理服务`
Packagename: `com.android.providers.downloads`
Version: `1.4.2 (142000)`

Appname: `Android 系统`
Packagename: `android`
Version: `8.1.0 (27)`

### SD Maid
Version: `4.14.22 (41422)`

### Device
Fingerprint: `OPPO/CPH1819/CPH1819:8.1.0/O11019/1547278409:user/release-keys`

**Comment by hokizedu** [comment]
storage/emulated/0/Download/magisk_patched-26400_KCfFQ.img

**Comment by MoeHtet1355** [comment]
> ### Target
> Target: `/storage/emulated/0/Download/magisk_patched.img` Prefix-free: `Download/magisk_patched.img` Path-prefix: `/storage/emulated/0/` Type: `FILE` Location: `SDCARD` Current keeper state: `true` Suggested keeper state: `false`
> 
> ### Suggested owners
> ### Current owners
> ~Appname: `?`~ ~Packagename: `com.android.providers.downloads.ui`~ ~Version: `null (0)`~
> 
> Appname: `下载管理服务` Packagename: `com.android.providers.downloads` Version: `1.4.2 (142000)`
> 
> Appname: `Android 系统` Packagename: `android` Version: `8.1.0 (27)`
> 
> ### SD Maid
> Version: `4.14.22 (41422)`
> 
> ### Device
> Fingerprint: `OPPO/CPH1819/CPH1819:8.1.0/O11019/1547278409:user/release-keys`
