### ISSUE TITLE
No SU request in work profile

### ISSUE THREAD

**Issue by JonnyTech** [d4rken/sdmaid-public#2735]
Using [Shelter](https://f-droid.org/en/packages/net.typeblog.shelter/) to manage Android work profile and running SD Maid from within, there is no superuser request. Magisk is set to multiuser, each user has root. Can SDM be forced to request SU? SDM in user profile works correctly.

Nokia 3, Android 8.0, SD Maid 4.14.22, Magisk 19.3, Manager 7.3.2, Shelter 1.4.1

**Comment by d4rken** [comment]
Do other apps work with Magisk in work profile mode?

I'm not so sure this is a SD Maid issue. SD Maid requests root by trying to open a shell with `su`. Profiles are not involved and I don't see how I could or would involve them.

**Comment by JonnyTech** [comment]
Gotcha. Shall report it with Shelter and Magisk as trying to su a terminal app fails too. Thanks and sorry for the noise.

**Comment by JonnyTech** [comment]
An update to anyone who has this issue: not only do you have to set Magisk Manager to "Multiuser Mode", but you also have to install Magisk Manager into the work / sheltered profile for root requests to be intercepted and granted. As @d4rken correctly stated, this is not a SD Maid issue.
