### ISSUE TITLE
Improve WhatsApp related cleaning

### ISSUE THREAD

**Issue by Idruk95** [d4rken/sdmaid-public#2739]
The app don't clean some WhatsApp folders: .Shared, .Thumbs and .Trash

**Comment by d4rken** [comment]
Please share more details about the paths and files they contain.

**Comment by Idruk95** [comment]
The path is:

/storage/emulated/0/WhatsApp/


Il Lun 24 Giu 2019, 15:27 Matthias Urhahn <notifications@github.com> ha
scritto:

**Comment by d4rken** [comment]
Both .Shared and .Trash are already  covered by the AppCleaner, please share some concrete examples that are not matches by SD Maid.
