### ISSUE TITLE
Receiver Manager Boot Indicator

### ISSUE THREAD

**Issue by reholli** [d4rken/sdmaid-public#275]
Feature request: When Receiver Manager is used to toggle off all receivers for an app, the Boot indicator disappears and you can no longer tell at a glance if an app has that capability. I for one cannot possibly remember them all, so it would be nice if the Boot indicator didn't disappear but just changed in appearance (color or something) like the Autostart indicator in v3.

**Comment by reholli** [comment]
As always, thanks for your effort!



Sent from my Samsung Galaxy Light

<div>-------- Original message --------</div><div>From: Matthias Urhahn <notifications@github.com> </div><div>Date:02/20/2016  22:49  (GMT-08:00) </div><div>To: d4rken/sdmaid-public <sdmaid-public@noreply.github.com> </div><div>Cc: reholli <reholli@pacbell.net> </div><div>Subject: Re: [sdmaid-public] Receiver Manager Boot Indicator (#275) </div><div>
</div>Closed #275 via 5d218ce84003e4e6c1a3e7e7820152ae57834deb.

**Comment by d4rken** [comment]
:+1:

**Comment by master1274** [comment]
content://media/external/images/media/523234
