### ISSUE TITLE
Duplication menu

### ISSUE THREAD

**Issue by D0r4** [d4rken/sdmaid-public#276]
I have Duplicate music files in my sd card not s big problem but maid is unable or just wont clean them also mayb a problem on my end sd randomly dupes video files. ..

**Comment by d4rken** [comment]
Android version? Device? Root? Location of the duplicates?
Preferably a debug run of deletion failing.

**Comment by D0r4** [comment]
4.1.2  s3 sch-s968c not rooted yet (may be the issue)

**Comment by D0r4** [comment]
The Duplicates are in their home extsd folder seems to be copies once rooted I can give more info sorry didnt expect a prompt response

**Comment by d4rken** [comment]
There are no known sdcard restrictions on 4.1.2., Root shouldnt be necessary.
If you can provide a debug run log (Settings > Advanced) using SD Maids latest beta, then I can further investigate.

**Comment by D0r4** [comment]
Hey no worries i got the s5 now😊
