### ISSUE TITLE
The guy wit

### ISSUE THREAD

**Issue by JJVirgo26** [d4rken/sdmaid-public#2767]
![Screenshot_20190702-193558_SD Maid](https://user-images.githubusercontent.com/52159106/60579366-c7a8c780-9d37-11e9-8489-c2f53153deb6.jpg)
![Screenshot_20190702-193651_SD Maid](https://user-images.githubusercontent.com/52159106/60579375-cd061200-9d37-11e9-8c41-007c9dbd5c68.jpg)

> @
![Uploading 20190702_175610.jpg…]()

**Comment by JJVirgo26** [comment]
I'm having issues uploading any data to you such as folders and actual hardware

**Comment by d4rken** [comment]
I don't understand what you are trying to say.

**Comment by JJVirgo26** [comment]
Its like they have control over all my stuff. My phone apps folders..everything

**Comment by JJVirgo26** [comment]
Those pictures are the fake apps that have been pre-loaded on my phone. I have been through quite an battle for two months. Trying to protect my information and credit worthiness, as well as clients information.

**Comment by JJVirgo26** [comment]
Your maidpro app and the one that checks the authenticity of the app is what saved me.
