### ISSUE TITLE
systemcleaner import file picker 

### ISSUE THREAD

**Issue by patrickdrd** [d4rken/sdmaid-public#2772]
I think that the files should be sorted by date,
the file names are useless anyway, 
so when I create a new user filter and
try to import in another device I have to go through 
all of them to find the latest by date,
so maybe these should be sorted by date?

thanks

**Comment by d4rken** [comment]
What's the current sort?
The easy solution would be to have it default to "DATE", I think it's by name now.

The slightly not easy solution would be an extra UI for changing sort modes.

Hmmm

**Comment by d4rken** [comment]
I'll have some extra time friday, will look into it.

**Comment by d4rken** [comment]
The new default sortmode is now `lastModified` (newest first) taken from the filter file timestamps.

There is an menu option to toggle between name and date sort.
