### ISSUE TITLE
Drinking coffee animation

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#2775]
Hi d4rken, why the maid while its drinking its coffee, it lags, the animation is not smooth, but in older version of the app, it's smooth (in version 4.9.5 and earlier), im using MyPhone RIO 2 running on QuadCore 1GB(plus with 400MB+ of swap) ram and Android L (5.0)

**Comment by d4rken** [comment]
> the animation is not smooth, but in older version of the app, it's smooth (in version 4.9.5 and earlier)

Older versions used a static GIF file, while newer version have an animated vector graphic.
The vector graphic uses a lot less space while offering a crisp picture on all screen sizes.

> im using MyPhone RIO 2 running on QuadCore 1GB(plus with 400MB+ of swap) ram and Android L (5.0)

You can disable the animation via settings > general settings if it's problematic on your device.
