### ISSUE TITLE
Scheduler crashes if setup was not done

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#278]
If the scheduler triggers and the setup was not done, SD Maid tries to show the setup dialog but crashes.

We could either force the setup when opening the scheduler view or show a notification that the scheduler skipped because the setup was not done.

**Comment by Trasd** [comment]
darken, might I suggest executing the setup on the first SD Maid run itself?  My reasoning for this is that if you add some other feature later that also needs the setup to be complete before functioning, you'll know it's already done and won't need to add or rewrite code then.

**Comment by d4rken** [comment]
I don't like it though if when opening the app the first thing the user sees is some kind of loading and then a popup without having done anything. It also means the causality isn't clear, if the user clicks an action and then it happens the causality is more obvious.

I'll make a specific setup check and sprinkle it across a few things (for now).

**Comment by Trasd** [comment]
Matthias,
If I remember correctly, the app opens to the Quick Access screen.
What about putting a button there that only shows up if an external SD card is present, but not setup.  Once setup, the button no longer appears and any changes or additional inclusions need to be setup as normal?
Sorry if I'm off, but I don't even remember when it does show up for the first time.
It's late.  I'll look at it tomorrow, but you know more about it than I do!
Troy
On Jan 7, 2016 12:19 AM, Matthias Urhahn <notifications@github.com> wrote:I don't like it though if when opening the app the first thing the user sees is some kind of loading and then a popup without having done anything. It also means the causality isn't clear, if the user clicks an action and then it happens the causality is more obvious.

I'll make a specific setup check and sprinkle it across a few things (for now).

**Comment by d4rken** [comment]
It's not only about QuickAccess, you could have been on another page and then inserted an sdcard and reopened SD Maid. Furthermore it's not just about external sdcards, but also root check and since 6.0 storage permission.

**Comment by Trasd** [comment]
True.
That why we make the suggestions, you make the decisions!
Troy
On Jan 7, 2016 12:56 AM, Matthias Urhahn <notifications@github.com> wrote:It's not only about QuickAccess, you could have been on another page and then inserted an sdcard and reopened SD Maid. Furthermore it's not just about external sdcards, but also root check and since 6.0 storage permission.

**Comment by d4rken** [comment]
Which helps me make the decisions :).
btw Check your email app, you seem to copy the previous post into each of your posts when responding.
(I've edited your posts and removed it)

**Comment by Trasd** [comment]
Sorry, it took me a bit to realize these weren't direct emails from you, but were posting directly to (and coming from) the new issues list!  When we email, I use my gmail address - that should have been a dead giveaway.
This one should be correct (no previous text).
Thanks.
