### ISSUE TITLE
Automated app cleaning doesn't work

### ISSUE THREAD

**Issue by turbo25** [d4rken/sdmaid-public#2780]
[sdmaid_logfile_1562405327486.txt.zip](https://github.com/d4rken/sdmaid-public/files/3364581/sdmaid_logfile_1562405327486.txt.zip)
I'm on Android 9, Motorola Moto x4

**Comment by d4rken** [comment]
SD Maid can't find the "Storage" entry to click, can you show me a screenshot?

**Comment by d4rken** [comment]
SD Maid is looking for:

```
                "it".toLang() == lang -> listOf(
                        "Spazio di archiviazione",
                        "Memoria archiviazione" // https://github.com/d4rken/sdmaid-public/issues/2545
                )
```

on your device it could be just `Memoria`?

**Comment by turbo25** [comment]
> 
> 
> SD Maid can't find the "Storage" entry to click, can you show me a screenshot?

Yes, it's "Memoria", but watch out, on other OSes or phones, "Memoria" is also used for the RAM options and usages. Also in the mine, despite the fact that it's "hidden" in a sub-menu, as you can see at the bottom of the screenshot.

![Screenshot_20190708-093303](https://user-images.githubusercontent.com/9088592/60791618-55374d80-a164-11e9-9f44-ec98b16cb693.png)

**Comment by d4rken** [comment]
>  Also in the mine, despite the fact that it's "hidden" in a sub-menu, as you can see at the bottom of the screenshot.

I'm not sure what you mean, how does it look like when not expanded?

Can you also show me a screenshot of the next page?

**Comment by turbo25** [comment]
![Screenshot_20190708-112602](https://user-images.githubusercontent.com/9088592/60799361-4906bc80-a173-11e9-963c-27df5c918834.png)

**Comment by d4rken** [comment]
> Can you also show me a screenshot of the next page?

I meant to click on the first `Memoria` so I can see whether SD Maid can find the `Clear cache` button.

**Comment by d4rken** [comment]
> > > Also in the mine, despite the fact that it's "hidden" in a sub-menu, as you can see at the bottom of the screenshot.
> > 
> > 
> > I'm not sure what you mean, how does it look like when not expanded?
> > Can you also show me a screenshot of the next page?
> 
> ![Screenshot_20190708-112602]

The extra "Memoria" at the bottom should be okay as SD Maid traverses the layout from the top.

**Comment by turbo25** [comment]
> 
> 
> > Can you also show me a screenshot of the next page?
> 
> I meant to click on the first `Memoria` so I can see whether SD Maid can find the `Clear cache` button.

Oh, sorry
![Screenshot_20190708-113111](https://user-images.githubusercontent.com/9088592/60799757-127d7180-a174-11e9-9e98-1465553d912a.png)
