### ISSUE TITLE
Bug: Requires SD Maid Pro text.

### ISSUE THREAD

**Issue by spicyfoxx** [d4rken/sdmaid-public#2781]
### What happened?
When I opened the app, in Quick access page, the Duplicates finder shows up the text: Requires SD Maid Pro.

### What did you expect to happen?
The text doesn't show up since I already have the Pro version.

### How can I reproduce the issue?
This is the first time it happened so I don't know how.

### Comments
The Duplicates finder still function and the text disappear after I re-open the app.

### SD Maid
Version: `4.14.27 (41427)`
Unlocker: `4.3.8 (40308) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a70qdx/a70q:9/PPR1.180610.011/A705FXXU2ASF6:user/release-keys`
![20190706_104047](https://user-images.githubusercontent.com/24849056/60756683-b8bd6000-a02a-11e9-9613-d3968fedd331.jpg)

**Comment by d4rken** [comment]
Some thoughts for later:

The worker only takes the first upgrade status that is published, which on a fresh launch, could shortly be "no upgrades" (racecondition). Need to process follow up emissions of new upgrade data too.

**Comment by d4rken** [comment]
Likely affects AppCleaner too as they use similar code for this.
