### ISSUE TITLE
Clutterreport: /system/plugin/FwkPlugin/FwkPlugin.apk (FP)

### ISSUE THREAD

**Issue by MedChem-Innovations** [d4rken/sdmaid-public#2787]
### Target
Target: `/system/plugin/FwkPlugin/FwkPlugin.apk`
Prefix-free: `plugin/FwkPlugin/FwkPlugin.apk`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.14.27 (41427)`

### Device
Fingerprint: `ZTE/P635A60_AU_TLS/P635A60:6.0/MRA58K/20161206.195344:user/release-keys`

### Comment
`unsure if malicious?`

**Comment by d4rken** [comment]
This is not what clutter reports are for.
https://github.com/d4rken/sdmaid-public/wiki/CorpseFinder#improving-detection
