### ISSUE TITLE
XAxis PieChart labels stacked when 0 value

### ISSUE THREAD

**Issue by seanyc4** [d4rken/sdmaid-public#2788]
I've spent a good 12 hours trying to find a solution to this problem including reading many other issues opened here with the same problem that were all closed without any solution provided.

When YValues on the piechart are 0 the XLabels all stack ontop of each other and it looks like a hot mess. Ive seen Phils previous suggestion of using the value formatter but this only applys to the YValues and not the Xlabels. How can I apply the same logic to the XLabels like if <4 set xLabels to ""; Surely this much be possible, it seems so simply and yet all these hours later I still cant get this to work.

**Comment by d4rken** [comment]
This ticket is read like it's meant for a different issue tracker?
