### ISSUE TITLE
Bug: Storage analyzer lag

### ISSUE THREAD

**Issue by xhn16729** [d4rken/sdmaid-public#2789]
### What happened?
Storage analyzer lag while sorting

### What did you expect to happen?
Sort will be finished in few seconds but I wait over minutes.

### How can I reproduce the issue?
Do storage analys and wait it sort

### SD Maid
Version: `4.14.27 (41427)`
Unlocker: `4.3.8 (40308) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `Xiaomi/jason/jason:7.1.1/NMF26X/V9.6.2.0.NCHMIFD:user/release-keys`

**Comment by d4rken** [comment]
Can you show me a video of what you mean?

**Comment by xhn16729** [comment]
Sorry, It works well now.
Maybe because my files too much lol

**Comment by d4rken** [comment]
The last update made a few changes that moved some calculations into the main search process instead of doing them while viewing the lists which could cause UI lag.

If you still think there is an issue, please provide a video or debug log.

Have a nice weekend!
