### ISSUE TITLE
The application cleaner is always leaving the last application to be cleaned "open", this error did not happen in previous versions.

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken/sdmaid-public#2792]
The application cleaner is always leaving the last application to be cleaned "open", this error did not happen in previous versions.

![Screenshot_20190710-194633_SD Maid](https://user-images.githubusercontent.com/8754997/61010408-7c507380-a34c-11e9-8f4e-d1100d116035.jpg)
![Screenshot_20190710-194731_Settings](https://user-images.githubusercontent.com/8754997/61010410-7ce90a00-a34c-11e9-8d82-eb16d4e59353.jpg)
![Screenshot_20190710-194736_Settings](https://user-images.githubusercontent.com/8754997/61010411-7ce90a00-a34c-11e9-80c5-b23ffd2ee575.jpg)

**Comment by d4rken** [comment]
Dup #2686
