### ISSUE TITLE
Cover MOO 音乐 in Corpse Finder

### ISSUE THREAD

**Issue by cokecodecock** [d4rken/sdmaid-public#2794]
Please cover a Tencent music app `MOO音乐(com.tencent.blackkey)` in Corpse Finder.

The path is `/storage/emulated/0/blackkey`

**Comment by d4rken** [comment]
What does the folder contain?

**Comment by cokecodecock** [comment]
Audio cache, lyrics cache, log and device ID

**Comment by d4rken** [comment]
Maybe this warrants adding it to the AppCleaner too?

If you would like to help with that, make an extra ticket and include the directory structure, e.g. via:
https://github.com/d4rken/sdmaid-public/wiki/Explorer#save-directory-structure

**Comment by d4rken** [comment]
#2795
