### ISSUE TITLE
AppCleaner: ACS: Improve locale support on MIUI ROMs

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2802]
Basically need the labels that SD Maid uses to recognize the actions in different locales.

* The label of the small action button in the bottom right, Which is either "Clear data" or "Clear cache" depending on the apps as we have found out.
* The label of the "Clear cache" entry within the popup dialog from the bottom that allows us to choose between the different actions. I think it's always the same as the button labels, but we'd need to confirm that.
* The title of the confirmation dialog, i.e. "Clear cache?". Theoretically we could ignore this but then we'd have no protection against pressing OK on any random dialog.

For languages using latin characters, screenshots should suffice.
For those without, e.g. Chinese, a log recording is necessary as I will have to copy paste the labels, of just the labels if you can type them out in this ticket ;).

Record a log for this by starting a [debug recording](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) and within the same menu also press "Debug Accessibility Service" which will cause SD Maid to log the UI hierarchy.

Initial ticket for MIUI support was #2783

![Screenshot from 2019-07-13 17-04-50](https://user-images.githubusercontent.com/1439229/61173209-8498f080-a590-11e9-9229-28469ea8a65a.png)
![Screenshot from 2019-07-13 17-04-33](https://user-images.githubusercontent.com/1439229/61173210-8498f080-a590-11e9-95f9-7f35bf822d27.png)
![Screenshot from 2019-07-13 17-04-20](https://user-images.githubusercontent.com/1439229/61173211-8498f080-a590-11e9-94d1-d4b27a786c54.png)

**Comment by JeffHorinzon** [comment]
Hey there!  Jeff here! (Yep, that "Jeff" that opened support for ACS on MIUI xD)  Here are a short list of languages I've covered so far:

German
````
Daten löschen > Cache löschen > OK
Cache löschen > OK
````

Indonesian
````
Hapus data > Bersihkan cache > Oke
Bersihkan cache > Oke
````

Simplified Chinese
````
清除数据 > 清除缓存 > 确定
清除缓存 > 确定
````

Traditional Chinese (Taiwan) [Written using GBoard - Traditional Chinese]
````
清除資料 > 清除暫存 > 確定
清除暫存 > 確定
````

Traditional Chinese (Hong Kong) [Written using GBoard - Cantonese]
````
清除資料 > 清除暫存 > 確定
清除暫存 > 確定
````

Spanish (U.S. America)
````
Limpiar datos > Limpiar caché > Aceptar
Limpiar caché > Aceptar
````

Spanish (Spain)
````
Limpiar datos > Limpiar caché > Aceptar
Limpiar caché > Aceptar
````

Italian
````
Elimina dati > Svuota la cache > OK
Svuota la cache > OK
````

Portuguese (Brazil)
````
Limpar dados > Limpar cache > OK
Limpar cache > OK
````

Portuguese (Portugal)
````
Limpar dados > Limpar cache > OK
Limpar cache > OK
````

Hindi
````
डेटा मिटाएं > कैशे मिटाएं > ठीक
कैशे मिटाएं > ठीक
````

Ukrainian
````
Очистити дані > Очистити кеш > ОК
Очистити кеш > ОК
````

Russian
````
Очистить > Очистить кэш > ОК
Очистить кэш > ОК
````

French
````
Effacer les données > Vider le cache > OK
Vider le cache > OK
````

Turkish
````
Verileri temizle > Önbelleği temizle > Tamam
Önbelleği temizle > Tamam
````

Polish
````
Wyczyść dane > Wyczyść pamięć podręczna > OK
Wyczyść pamięć podręczna > OK
````

Korean
````
데이터 지우기 > 캐시 지우기 > 확인
캐시 지우기 > 확인
````

Japanese
````
データをクリア　>　キャッシュをクリア　>　OK
キャッシュをクリア　>　OK
````

Here are also the sets of screenshot of the interface in their respective languages.
[MIUI Language Sets.zip](https://github.com/d4rken/sdmaid-public/files/3389476/MIUI.Language.Sets.zip)

**Comment by JeffHorinzon** [comment]
JEFF'S BACK WITH ANOTHER WAVE OF LANGUAGES!  YEAH!
Here ya go :)

Azerbaijani
````
Məlumatları təmizlə > Keşi təmizlə > Oldu
Keşi təmizlə > Oldu
````
Malay
````
Kosongkan data > Bersihkan cache > Ok
Bersihkan cache > Ok
````
Bosnian
````
Izbriši podatke > Izbriši predmemoriju > U redu
Izbriši predmemoriju > U redu
````

Catalan
````
Esborra les dades > Esborra la memòria cau > D'acord
Esborra la memòria cau > D'acord
````
Czech
````
Vymazat data > Vyčistit mezipamět' > OK
Vyčistit mezipamět' > OK
````

Danish
````
Ryd data > Ryd cache > OK
Ryd cache > OK
````

Estonian
````
Puhasta andmed > Puhasta vahemälu > OK
Puhasta vahemälu > OK
````

Basque
````
Datuak ezabatu > Garbitu cache-a > ados
Garbitu cache-a > ados
````

Galician
````
Eliminar datos > Eliminar a cache > Aceptar
Eliminar a cache > Aceptar
````

Hausa
````
Share bayanai > Share gurbin bayanai > Ya yi
Share gurbin bayanai > Ya yi
````

Croatian 
````
Izbriši podatke > Očisti predmemoriju > U redu
Očisti predmemoriju > U redu
````

Latvian 
````
Notīrīt datus > Tīrīt kešatmiņu > OK
Tīrīt kešatmiņu > OK
````

Lithuanian
````
Išvalyti duomenis > Valyti podėlį > Gerai
Valyti podėlį > Gerai
````

Hungarian
````
Adatok törlése > Gyorsítótártörlés > Rendben
Gyorsítótártörlés > Rendben
````

Maltese
````
Neħħi d-dejta > Battal il-cache > OK
Battal il-cache > OK
````

Dutch
````
Gegevens wissen > Cache wissen > OK
Cache wissen > OK
````

Norwegian
````
Slett data > Tøm cache > OK
Tøm cache > OK
````

Uzbek
````
Ma'lumotlarni tozalash > Keshni tozalash > OK
Keshni tozalash > OK
````

Romanian
````
Șterge date > Șterge cache > OK
Șterge cache > OK
````

Albanian 
````
Pastro të dhënat > Pastro deponë > OK
Pastro deponë > OK
````

Slovak
````
Vymazat' dáta > Vyčistit' cache > OK
Vyčistit' cache > OK
````

Slovene
````
Počisti podatke > Očisti predpomnilnik > V redu
Očisti predpomnilnik > V redu
````

Finnish
````
Tyhjennä tiedot > Tyhjennä välimuisti > OK
Tyhjennä välimuisti > OK
````

And... as usual, screenshots!
[MIUI Language Sets 2.zip](https://github.com/d4rken/sdmaid-public/files/3389946/MIUI.Language.Sets.2.zip)
