### ISSUE TITLE
Clutterreport: /storage/self (FP)

### ISSUE THREAD

**Issue by PersonalRobotJesus** [d4rken/sdmaid-public#2809]
### Target
Target: `/storage/self`
Prefix-free: `/storage/self`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `8.1.0 (27)`

### Current owners
None

### SD Maid
Version: `4.14.27 (41427)`

### Device
Fingerprint: `TCL/A502DL/U50A_PLUS_TF:8.1.0/OPM1.171019.011/vG7W-0:user/release-keys`

**Comment by d4rken** [comment]
This location is not supported by SD Maid
