### ISSUE TITLE
Add a home button to Explorer and any file dialogues

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#281]
This is needed since at least on Marshmallow, if the user navigates to the root of the device (/), and they try to open /sdcard or any location but /storage/emulated/0, they'll be at a dead end. The user will have to look very hard to find the root of their internal storage or SD Card compared to in earlier SD Maid versions. So, adding a home button is a good idea to increase user friendliness. I believe I've seen a home button or two already in some parts of SD Maid v4.

**Comment by d4rken** [comment]
Done in previous versions afaik.
