### ISSUE TITLE
Request: Night mode

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#2812]
### What should the feature do?
How about an option, which makes the entire UI of SD-Maid OLED optimized, e.g. many layouts completely dark

### When/How would you use it?
Daily, because I want to save battery :D

### How would you implement it?
Extra code for every UI element. It's tough, but I think it's worth it.

### Comments
What's up?

### SD Maid
Version: `4.14.28 (41428)`
Unlocker: `4.3.8 (40308) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS8CSC2:user/release-keys`

**Comment by spicyfoxx** [comment]
![20190714_182112](https://user-images.githubusercontent.com/24849056/61182919-77e5cc80-a664-11e9-9eff-e0e02e61b321.jpg)
It doesn't save battery that much anyway.
https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/

**Comment by d4rken** [comment]
I'm not against theming, but for this project it's just out of scope. This has also gotten much easier since the start of 2019 due to Google adding day/night support for the Material Design themes, I'll add light/dark theme in my next app :wink: .
