### ISSUE TITLE
Clutterreport: /storage/emulated/0/Samsung/Music (FP)

### ISSUE THREAD

**Issue by dreadpirate1979** [d4rken/sdmaid-public#2824]
### Target
Target: `/storage/emulated/0/Samsung/Music`
Prefix-free: `Samsung/Music`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Amazon Music`
Packagename: `com.amazon.mp3`
Version: `15.21.10 (315211010)`

### Current owners
Appname: `Galaxy Store`
Packagename: `com.sec.android.app.samsungapps`
Version: `4.5.05.5 (450505110)`

### SD Maid
Version: `4.14.27 (41427)`

### Device
Fingerprint: `samsung/greatqltesq/greatqlte:9/PPR1.180610.011/N950USQU5DSD9:user/release-keys`

**Comment by d4rken** [comment]
Amazon uses the Samsung music folder?
