### ISSUE TITLE
Clutterreport: /storage/355B-A2EB/GALLERYSETTING (new)

### ISSUE THREAD

**Issue by dreadpirate1979** [d4rken/sdmaid-public#2825]
### Target
Target: `/storage/355B-A2EB/GALLERYSETTING`
Prefix-free: `GALLERYSETTING`
Path-prefix: `/storage/355B-A2EB/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Gallery`
Packagename: `com.sec.android.gallery3d`
Version: `10.0.02.106 (1000200106)`

### Current owners
None

### SD Maid
Version: `4.14.27 (41427)`

### Device
Fingerprint: `samsung/greatqltesq/greatqlte:9/PPR1.180610.011/N950USQU5DSD9:user/release-keys`

**Comment by d4rken** [comment]
AFAIK this is not correct? Got any more info on this?
