### ISSUE TITLE
Clutterreport: /storage/678B-6214/Camera

### ISSUE THREAD

**Issue by blakRoz** [d4rken/sdmaid-public#2836]
### Target
Target: `/storage/678B-6214/Camera`
Prefix-free: `Camera`
Path-prefix: `/storage/678B-6214/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Camera`
Packagename: `com.fujitsu.mobile_phone.camera`
Version: `1.1.40001 (40001)`

### Current owners
Appname: `?`
Packagename: `jp.kyocera.camera`
Version: `null (0)`

### SD Maid
Version: `4.14.30 (41430)`

### Device
Fingerprint: `DOCOMO/F04G/F04G:6.0.1/V19R57C/F04G.20181001.140641:user/release-keys`

**Comment by d4rken** [comment]
Note: Need to check whether this is flagged as `COMMON` which it should.
