### ISSUE TITLE
SDMaid crashes when scanning or running AppCleaner.

### ISSUE THREAD

**Issue by ognjen73** [d4rken/sdmaid-public#2843]
Hi,
SDMaid crashes when scanning or running AppCleaner.
Please find debug log attached. 
Thank you. 

[sdmaid_logfile_1563738804196.txt.zip](https://github.com/d4rken/sdmaid-public/files/3418366/sdmaid_logfile_1563738804196.txt.zip)

**Comment by d4rken** [comment]
From the log it looks like SD Maid is running out of memory.
Specifically the "Bug reporting" filter at the end of the log there are 314127 entries from Fabric/Crashlytics specific files.

The biggest offenders are:

```
/data/data/yo.app/files/.Fabric
/data/user/0/com.makonda.blic/files/.Fabric
/data/user/0/com.samruston.weather/files/.Fabric
```

Are you blocking Internet for apps?

There is no trivial fix for `OutOfMemory` errors from my end for this so I would suggest to use the explorer and manually deleted the files.

If you deleted `/data/user/0/com.samruston.weather/files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/` by hand the AppCleaner should run through byitself as that directory alone contains at least 287738 files.

If you are going to delete it through SD Maids Explorer I would recommend to temporarily turn off the options "Research owner", "SystemCleaner" and "AppCleaner" before browsing to that folder (or you don't open the folder itself but delete it directly from the folder above).

**Comment by ognjen73** [comment]
Hi d4rken,
Thank you for your quick response.
I forgot to tell you my id is ddf6535c-c124-410b-b461-d3906ae13634.
I will try to delete those files manually.
Version 4.14.24 did not crash.

**Comment by JeanMS** [comment]
Thanks. I've let this build up and your help is reminding me how I have to focus.

**Comment by ognjen73** [comment]
I deleted two out of three folders. In order to delete the last one, I had to uninstall corresponding application.
Now everything works fine, but folders and files within are being generated again and again.
Interesting, these folders do not exist on my other devices in the same applications.
Thank you d4rken very much!

**Comment by waddlet** [comment]
Im sorry

**Comment by d4rken** [comment]
@ognjen73 :+1:

**Comment by JeanMS** [comment]
Thanks so much
