### ISSUE TITLE
[System cleaner] Add folder to system cleaner by default

### ISSUE THREAD

**Issue by spicyfoxx** [d4rken/sdmaid-public#2849]
[pathdump_storage_emulated_0_.sems1564378908108.txt](https://github.com/d4rken/sdmaid-public/files/3443172/pathdump_storage_emulated_0_.sems1564378908108.txt)
This folder belongs to `Samsung Experience Mobile Service`, contains 1 picture which doesn't of use for anything. Delete the folder will free us more space, the app won't create the folder again.

**Comment by d4rken** [comment]
What's the packagename of the app?

**Comment by spicyfoxx** [comment]
> What's the packagename of the app?

com.samsung.android.mobileservice
