### ISSUE TITLE
Hidden cache

### ISSUE THREAD

**Issue by CaptainFrosty** [d4rken/sdmaid-public#2861]
For some reason, my CCleaner Pro app detects "hidden cache" data that does not show up in SD Maid App Cleaner. Does anyone know why this might be so??

Thanks in advance

**Comment by d4rken** [comment]
If CCleaner doesn't share any details about it, then it could be anything, including nothing :man_shrugging:

**Comment by NoCompromise** [comment]
To me SD maid does not find any hidden cache, while ccleaner does it.

**Comment by CaptainFrosty** [comment]
I figured out it was because my cache settings was set to 7 days

**Comment by d4rken** [comment]
Thanks for the update.
