### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/obb/.nomedia (FP)

### ISSUE THREAD

**Issue by Kilo-411** [d4rken/sdmaid-public#2862]
### Target
Target: `/storage/emulated/0/Android/obb/.nomedia`
Prefix-free: `.nomedia`
Path-prefix: `/storage/emulated/0/Android/obb/`
Type: `FILE`
Location: `PUBLIC_OBB`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `SystemPanel`
Packagename: `nextapp.sp`
Version: `2.0.b14 (2070)`

### Current owners
None

### SD Maid
Version: `4.14.30 (41430)`

### Device
Fingerprint: `lge/cv3_lao_com/cv3:8.1.0/OPM1.171019.026/19155140321d4:user/release-keys`

**Comment by d4rken** [comment]
Why do you think this app created it?
