### ISSUE TITLE
Clutterreport: /storage/emulated/0/tencent

### ISSUE THREAD

**Issue by Peamod** [d4rken/sdmaid-public#2863]
### Target
Target: `/storage/emulated/0/tencent`
Prefix-free: `tencent`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `?`
Packagename: `^(?:com\.tencent\..+?)$`
Version: `null (0)`

### SD Maid
Version: `4.14.31 (41431)`

### Device
Fingerprint: `Nokia/TA-1053_00WW/ND1:9/PKQ1.181105.001/00WW_6_18B:user/release-keys`

### Comment
`I never installed any chinese apps so why it is here I delete it many times but it comes back again and again`

**Comment by d4rken** [comment]
You obviously still have an app that keeps creating this folder.
Unfortunately I can't tell you which one, but if you find out, let me know :).

**Comment by Peamod** [comment]
Before 2-3 months ago the folder name tencent was not there. and I still
have those application in my phone there is no any new application. maybe
some hidden application has been installed but I am not able to find.

**Comment by d4rken** [comment]
Can't help with that.
