### ISSUE TITLE
Inaccurate wording in Searcher regarding root search

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#287]
When SD Maid is denied root, going to the Searcher and trying to toggle on root search says “Requires SD Maid Pro” which isn't true, as I have the v4 unlocker installed. It should be hidden when the device isn't rooted, and not hidden only if root is detected. Or it could show under both cases but show different text. You could also just hide the filter completely on unrooted devices, only suggesting Pro when the device is rooted but SD Maid Pro is not installed. Currently, SD Maid told me I needed Pro when I didn't grant it root, but Pro was installed. Consider the following situations:
Unrooted device without SD Maid Pro: output “Requires root and SD Maid Pro” 
Unrooted device with SD Maid Pro: output “Requires root”
Rooted device without SD Maid Pro: output “Requires SD Maid Pro”
Rooted device with SD Maid Pro: nothing extra needed.

**Comment by d4rken** [comment]
Should be fixed with 4.0.4, otherwise reopen.
