### ISSUE TITLE
export split apks correctly

### ISSUE THREAD

**Issue by jancm** [d4rken/sdmaid-public#2876]
Currently when exporting an app which is composed of split APKs only the base apk gets exported. Installing just the base apk leaves you with a non-functional app.

Suggest that for split APKs you follow the format used by SAI https://github.com/Aefyr/SAI (Split APK Installer). Basically grab all the relevant apk files and place then in an apks file, which SAI can then use to install them.

**Comment by d4rken** [comment]
Is there one specific format that all apps use or is SAI just the most popular tool for this purpos?

**Comment by jancm** [comment]
I don't know. I don't even know if there are other tools that do it. A
non-exhaustive check didn't find any other apps dealing with split APKs
either on the Play Store or F-Droid. Ask the SAI dev? He's responsive
enough.

I also sent an email to Titanium asking them to support split APKs - they
currently don't. apkmirror also doesn't support them, at least not yet. So
support isn't exactly widespread at the moment. I was surprised to find
I've got 35 split apk apps currently installed.

**Comment by d4rken** [comment]
Can you share a few packagenames of those 35 so I can use them for testing?

**Comment by jancm** [comment]
Sure. Here's a few. Including version numbers because I don't know when
they started using splits. All of these were installed via Play Store.

Chrome Canary  (78.0.3887.0)
Duo  (60.0.261761289.DR60_RC08)
MatLog (1.2.3)
Photos (4.22.0.263006408) (only system app, so far)
Reddit (3.33.1)
FBReader (3.0.15)
FBReader Bookshelf (1.7.2.4)
FBReader PDF plugin (2.2.7)
Moon+ Reader (5.1)
Home (2.13.1.10)

That should do for starters. I suspect you have at least some of those
already installed. I don't know if regular Chrome is split, I have it
frozen.
