### ISSUE TITLE
InAppBillingService

### ISSUE THREAD

**Issue by ZachParris37** [d4rken/sdmaid-public#2881]
Is InAppBillingService suppose to be running in the background all the time?

**Comment by d4rken** [comment]
Kinda.

`InAppBillingService` doesn't run as part of SD Maid, it's running all the time as part of Google Play Services. While running, SD Maid will `bind` to it, to be notified of related IAPs. SD Maid binding to it should have no impact on your devices performance or battery life.

Does that answer your question?
