### ISSUE TITLE
Feature request... 

### ISSUE THREAD

**Issue by Sridhar-Ananthanarayanan** [d4rken/sdmaid-public#2889]
Good day Matthias,

BUGS

1. The force media scan feature doesn't seem to have any effect. The gallery apps continue to display thumbnails of files already deleted. This is the only app I found to work nicely:

https://play.google.com/store/apps/details?id=com.house.noranuko.mediarescanner

Kindly fix.

2. Duplicate files deletion - this feature is largely well done, although it tends to, at times, not delete duplicate files. This is very rare, so only bringing it to your attention so you could improve the algorithms.

FEATURE REQUESTS

Here is a list of feature requests for your consideration.

1. App shortcut - ability to trigger SD Maid function using an automation app like Tasker/ Macrodroid. 

2. Startup Manager - ability to stop apps from starting up when Android boots. The autostart feature (receiver manager) lists several entries, and some of them have "boot" mentioned against them. Will disabling them block apps from starting up on boot? My device is rooted with Magisk. Can you make this process simpler by allowing us to simply select apps that must not start with Android boot?

3. Firewall - there is only one app on Google Play Store (AFWall+) that does an excellent job but needs root. All other firewall apps have very limited functionality. I would prefer an app (preferably if it can work without root) that can allow other apps to only communicate within the local network (LAN only) while blocking all communications over the internet or outside of the network.

Currently the local VPN based apps can either block WiFi altogether or allow it full access. There is no way to implement a LAN only access to apps. The idea is essentially to protect our own privacy by blocking apps from communicating over the internet. 

4. Folder/ path selection - currently we have to manually input the full folder path when adding a folder to the exclusion list. Is it possible to use the explorer to select the desired folder instead of having to manually enter it?

5. APK manager - I have a habit of backing up apk files, to allow me to restore an earlier version if an update breaks certain functionality. Ideally, I would like to automate this process, so that everytime an app gets updated, SD Maid will automatically backup the apk. The apk filename should be simple (appname_version) format. Also the option to keep only a user specified number of backups.

I know all these things require your time. You may consider developing a paid add-on to support these features or a different app altogether if required.

Thank you.

Sridhar

**Comment by d4rken** [comment]
Please split your ideas into individual tickets so they can be addressed on their own.
