### ISSUE TITLE
LAN only access for apps... 

### ISSUE THREAD

**Issue by Sridhar-Ananthanarayanan** [d4rken/sdmaid-public#2891]
Good day,

**Firewall** 

There is only one app on Google Play Store (AFWall+) that does an excellent job on permitting network connections, but needs root. All other firewall apps have very limited functionality. 

I would prefer an app (preferably if it can work **without root**) that can allow other apps to only communicate within the local network (LAN only) while blocking all communications over the internet or outside of the network.

Currently the local VPN based apps can either block WiFi altogether or allow it full access. There is no way to implement a LAN only access to apps. The idea is essentially to protect our own privacy by blocking apps from communicating over the internet.

The feature essentially allows the user to individually control if an app can communicate under the following channels:

1. LAN
2. WiFi
3. Mobile Data
4. Mobile Data (Roaming)
5. VPN

You can consider this as a feature of SD Maid, or as an add-on or even a completely separate app. I would be more than happy to purchase it if you could offer the above functionality.

Thank you for your consideration.

**Comment by Sridhar-Ananthanarayanan** [comment]
Of all the tickets I have raised, this is the one I am looking forward to the most.

For rooted devices, there is already a very good app called AFWall+ (although alternatives are always welcome).

But for non-rooted devices which are the majority, the existing local VPN based solutions like Netguard, No-root firewall, etc are very basic and very limited in functionality.

During times when we need to use a real VPN, we have to disable these local VPNs, and the whole purpose is defeated because all apps would then have free access to the internet.

The only way I can think of as a solution is to have an app that can do the following:

1. Ability to Close/ Hibernate all selected apps when the firewall app is disabled. Also prevent automatic restart of those apps.

2. The firewall app should be able to allow LAN only connection to apps, and this will be extremely handy to people who use a local network for file transfers and media streaming. All such activities will remain inside the network and therefore should address privacy concerns adequately. 

I really look forward to you taking this up as your next project.

Thank you.

**Comment by d4rken** [comment]
This feature is out of scope for SD Maid. I have no plans to work on such an app. Sorry.

**Comment by Sridhar-Ananthanarayanan** [comment]
Okay. Thanks for the clarification.
