### ISSUE TITLE
APK manager... 

### ISSUE THREAD

**Issue by Sridhar-Ananthanarayanan** [d4rken/sdmaid-public#2893]
Good day,

**APK manager**

I have a habit of backing up apk files, to allow me to restore an earlier version if an update breaks certain functionality. Ideally, I would like to automate this process, so that everytime an app gets updated (or on a user specified time based schedule), SD Maid will automatically backup the updated apk. 

1. The apk filename should be simple (appname_version.apk) format. 

2. There should be an option to keep only a user specified number of backups.

3. There should be an option to choose the folder where these APKs must be backed up.

Thank you.

**Comment by d4rken** [comment]
App backup functionality is out of scope for SD Maid.

I like your idea though and want the same feature. I'm already working on an extra app that can do this :grin: . I think it will be 1-2 month till the first beta though. :thinking:
