### ISSUE TITLE
App Shortcut... 

### ISSUE THREAD

**Issue by Sridhar-Ananthanarayanan** [d4rken/sdmaid-public#2894]
Good day,

**App shortcut**

Ability to trigger SD Maid function using an automation app like Tasker/ Macrodroid.

Please provide a Android shortcut for SD Maid functions that can be triggered using automation apps.

Thank you.

**Comment by d4rken** [comment]
SD Maid has a widget and app shortcuts (Android 8+) to make quick access easier to launch, tasker support is a dup of #83 and while not completely out of scope, not a high priority feature.
