### ISSUE TITLE
Bug: Storage Analyzer problem

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#2901]
### What happened?
I analyzed /system with Storage Analyzer, then clicked on a symlink (/product) and SD Maid crashed. There's a folder in it, which size isn't measurable (no root).

### What did you expect to happen?
It crashed. That shouldn't happen, right?

### How can I reproduce the issue?
Maybe try on a device with Android 9?

### Comments
This is a comment.

### SD Maid
Version: `4.14.32 (41432)`
Unlocker: `4.3.9 (40309) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a70qeea/a70q:9/PPR1.180610.011/A705FNXXU2ASF5:user/release-keys`

**Comment by JavkhlanK** [comment]
Logfile:
[sdmaid_logfile_1566999888345.txt](https://github.com/d4rken/sdmaid-public/files/3551208/sdmaid_logfile_1566999888345.txt)

**Comment by d4rken** [comment]
> It crashed. That shouldn't happen, right?

While /system and /preload isn't directly supported without root, it should never crash :smile:

**Comment by d4rken** [comment]
The issue was the symlink throwing the us off. The code assumes a top down structure where every locations parent has been visited.

As symlinks don't impact the size results, and including them is slightly confusing, I've solved this by removing symlinks from results.
