### ISSUE TITLE
Bug: root with magsik is not recognized

### ISSUE THREAD

**Issue by patecatl1972** [d4rken/sdmaid-public#2904]
### What happened?
despite displayed supersu access, the root functions are not possible

### What did you expect to happen?
I have tested different version of magisk at all the same problem.Is there a setting I overlooked?

### How can I reproduce the issue?
Using Magisk with SD Maid the problem occurs

### SD Maid
Version: `4.14.32 (41432)`
Unlocker: `4.3.9 (40309) (true)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `samsung/hltexx/hlte:5.0/LRX21V/N9005XXSGBRI2:user/release-keys`

**Comment by d4rken** [comment]
To further debug this I'll need a log of the root check happening:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

I'm unaware of any specific magic issues. What does SD Maid display in the overview page?

**Comment by d4rken** [comment]
Reopen if still relevant and log is available.
