### ISSUE TITLE
Clutterreport: /storage/emulated/0/MIUI

### ISSUE THREAD

**Issue by mkp95** [d4rken/sdmaid-public#2913]
### Target
Target: `/storage/emulated/0/MIUI`
Prefix-free: `MIUI`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Backup`
Packagename: `com.miui.backup`
Version: `6.3.3.0 (6330)`

Appname: `com.miui.miwallpaper`
Packagename: `com.miui.miwallpaper`
Version: `7.1.2 (1000)`

Appname: `Wallpaper Carousel`
Packagename: `com.miui.android.fashiongallery`
Version: `V7-G-190411 (20190411)`

### Current owners
Appname: `?`
Packagename: `com.miui.enbbs`
Version: `null (0)`

### SD Maid
Version: `4.14.32 (41432)`

### Device
Fingerprint: `Xiaomi/santoni/santoni:7.1.2/N2G47H/9.6.27:user/release-keys`

### Comment
`This folder is used in almost every basic operation that deals with the Media access... In miui roms`

**Comment by d4rken** [comment]
I think I'll add a regex marker for com.miui.* :thinking:
