### ISSUE TITLE
Improve language support for cache clearing via ACS on Android 10

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2922]
Android 10 changed the labeling of the storage entry.

Included in SD Maid v4.14.35:

- [x] `en` `Storage` -> `Storage & cache`
- [x] `de` `Speicher` -> `Speicher und Cache`
- [x] `it` `Spazio di archiviazione` -> `Spazio di archiviazione e cache`
- [x] `nl` `Opslagruimte` -> `Opslag en cache`
- [x] `fr` `Stockage` -> `Espace de stockage et cache`
- [x] `cs` `Úložiště` -> `Úložiště a mezipaměť`
- [x] `ru` `Хранилище` -> `Хранилище и кэш`
- [x] `hi` `भंडारण` -> `स्टोरेज और कैश`
- [x] `iw`
- [x] `th`
- [x] `ml`
- [x] `fi`
- [x] `ar`
- [x] `es`
- [x] `zh-Hans`
- [x] `zh-Hant`
- [x] `ja`
- [x] `pt`
- [x] `uk`
- [x] `tr`
- [x] `kr`
- [x] `pl`
- [x] `vi`
- [x] `el`
- [x] `hu`
- [x] `ko`
- [x] `sl`
- [x] `sr`
- [x] `th`
- [x] `iw`
- [x] `ml`
- [x] `fi`
- [x] `ar`
- [x] `nb`
- [x] `sr`
- [x] `bg`
- [x] `sk`
- [x] `fa`
- [x] `ca`
- [x] `ms`
- [x] `sv`
- [x] `da`

Missing as of v4.14.35:

- [ ] `id`
- [ ] `fil_PH`

**Comment by d4rken** [comment]
![Screenshot from 2019-09-05 16-06-08](https://user-images.githubusercontent.com/1439229/64349393-279d4200-cff7-11e9-85c8-de78f29094fd.png)

**Comment by MK-translations** [comment]
Suggestion for 'ru':
Хранилище -> Хранилище и кэш

**Comment by novas78** [comment]
For 'cs'
Úložiště -> Úložiště a mezipaměť

**Comment by theimpulson** [comment]
For 'hi'
भंडारण -> स्टोरेज और कैश

**Comment by d4rken** [comment]
`storage_settings_for_app`

https://github.com/aosp-mirror/platform_packages_apps_settings/blob/android10-mainline-release/res/values/strings.xml#L3094
