### ISSUE TITLE
Clutterreport: /storage/C0F4-1B0F/Android/data/com.xmwork.ringmaster.maker (FP)

### ISSUE THREAD

**Issue by Nomadic-Knight78** [d4rken/sdmaid-public#2933]
### Target
Target: `/storage/C0F4-1B0F/Android/data/com.xmwork.ringmaster.maker`
Prefix-free: `com.xmwork.ringmaster.maker`
Path-prefix: `/storage/C0F4-1B0F/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Google Play Store`
Packagename: `com.android.vending`
Version: `16.6.26-all [0] [PR] 268150575 (81662600)`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.xmwork.ringmaster.maker`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.14.32 (41432)`

### Device
Fingerprint: `samsung/jackpotltevl/jackpotltecan:9/PPR1.180610.011/A530WVLS7CSH2:user/release-keys`

### Comment
`Is part of a app that is either duplicate or passed off as a 2nd under name of MP3 Cutter - Ringtone Maker through Google Play Store with neither app matching "Known Owner's" as displayed`

**Comment by d4rken** [comment]
Can you post a link to the app?
Need to know the package name (it's usually in the link on Google Play) or visible in SD Maids AppControl.
