### ISSUE TITLE
Problem with ext. SD card

### ISSUE THREAD

**Issue by Anyn** [d4rken/sdmaid-public#294]
On one moment I installed this beta on my Lenovo Vibe p1m with Android 5.1 but it indefinitely show the problem with "grant access to external SD card" and all Setting and of course, all functionality rotates in this circle + constantly woning about update and Unocker update which failed in any combination! The phone is not rooted and it will be a big problem for 4. version!! 
Fortunately I successfully back it on ver3!

**Comment by d4rken** [comment]
The unlocker update has nothing to do with the sdcard issue. Please only report one issue per ticket.

Is your device rooted? Please do a debug run and attach the log.

**Comment by Anyn** [comment]
O.K.
I installed this beta on my Lenovo Vibe p1 m with Android 5.1 but it 
indefinitely show the problem with "grant access to external SD card" and all 
Setting and of course, all functionality rotates in this circle (it opened only 
"Recent" but empty) The phone is not rooted and it will be a big problem if 
required for 4. version!!
 Fortunately I successfully back it up  on ver3!
Please, I have not the nerve to log any error because it is a Phone not tablet 
which is used for talking!
Best Regards!

**Comment by d4rken** [comment]
If you can't get into settings to start a debug run, you can also force it like this:

* Force stop SD Maid
* Create a file or folder on your sdcard named "sdm_force_debug_run".
* Start SD Maid, it should now be doing a debug run

**Comment by Anyn** [comment]
It presume that I must install again the beta ver.
Sorry. Do not have the patience now. Maybe later.
Best Regards!

**Comment by redmax1976** [comment]
I have this issue as well. Does not let me grant access to internal or external SD cards. This is on a lg g3 on 5.0 not rooted.

**Comment by d4rken** [comment]
Internal? SD Maid should not need to be granted UriPermission for the internal SDCard on 5.0.
You can experiment with the uri permission through the advanced settings.
If you find out more let me know.

**Comment by redmax1976** [comment]
This is screen shots of the options I get.

Graham

**Comment by d4rken** [comment]
I see no screenshot?
