### ISSUE TITLE
Clutterreport: /storage/emulated/0/GravityBox

### ISSUE THREAD

**Issue by nift4** [d4rken/sdmaid-public#2949]
### Target
Target: `/storage/emulated/0/GravityBox`
Prefix-free: `GravityBox`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners

Appname: `GravityBox Unlocker`
Packagename: `com.ceco.gravitybox.unlocker`
Version: `1.8`

Appname: `GravityBox [Q]`
Packagename: `com.ceco.q.gravitybox`
Version: `10 (1000)`

Appname: `GravityBox [P]`
Packagename: `com.ceco.pie.gravitybox`
Version: `9.1.1 (912)`

Appname: `GravityBox [O]`
Packagename: `com.ceco.oreo.gravitybox`
Version: `8 (800)`

Appname: `GravityBox [N]`
Packagename: `com.ceco.nougat.gravitybox`
Version: `7 (700)`

Appname: `GravityBox [MM]`
Packagename: `com.ceco.marshmallow.gravitybox`
Version: `6 (600)`

Appname: `GravityBox [L]`
Packagename: `com.ceco.lollipop.gravitybox`
Version: `5 (500)`

Appname: `GravityBox [KK]`
Packagename: `com.ceco.kitkat.gravitybox`
Version: `4.4 (440)`

Appname: `GravityBox [JB]`
Packagename: `com.ceco.gm2.gravitybox`
Version: `4 (400)`

### Current owners
Appname: `?`
Packagename: `com.ceco.kitkat.gravitybox`
Version: `null (0)`

Appname: `?`
Packagename: `com.ceco.lollipop.gravitybox`
Version: `null (0)`

### SD Maid
Version: `4.14.32 (41432)`

### Device
Fingerprint: `motorola/cedric/cedric:8.1.0/OPPS28.85-13-2/d04a4:user/release-keys`

**Comment by edd04** [comment]
suggested keppr state: true

**Comment by edd04** [comment]
@d4rken 

> ### Target
> Target: /storage/emulated/0/GravityBox
> Prefix-free: `ravityBox
> Path-prefix:/storage/emulated/0/
> Type: DIRECTORY
> Location: `SDCARD
> Current keeper state: true
> Suggested keeper state: true
> 
> ### Suggested owners
> Appname: GravityBox [P]
> Packagename: com.ceco.pie.gravitybox
> Version: 9.1.1 (912)
> 
> ### Current owners
> Appname: graviti
> Packagename: com.ceco.kitkat.gravitybox
> Version: true (1)
> 
> Appname: ?
> Packagename: com.ceco.lollipop.gravitybox
> Version: `null (0)`
> 
> ### SD Maid
> Version: 4.14.32 (41432)
> 
> ### Device
> Fingerprint: motorola/cedric/cedric:8.1.0/OPPS28.85-13-2/d04a4:user/release-keys

**Comment by nift4** [comment]
@edd04 @d4rken Reworked:
- Add all GravityBoxes
- Add Unlocker
- Set keeper state to true

**Comment by d4rken** [comment]
```
{
  "pkgs": ["com.ceco.gravitybox.unlocker"],
  "regexPkgs": ["^(?:com\\.ceco\\..+\\.gravitybox)$"],
  "mrks": [{"loc": "SDCARD", "path": "GravityBox", "flags": ["keeper"]}]
}
```
