### ISSUE TITLE
Notifications do funny jumps

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#295]
Video: https://www.youtube.com/watch?v=2JvNIxtIY0U
G+: https://plus.google.com/u/0/+SandroJ%C3%A4ckel/posts/R29UmiDAb4Z

**Comment by d4rken** [comment]
Device info, likely universal though.
[debugrun1.txt](https://github.com/d4rken/sdmaid-public/files/109729/debugrun1.txt)

**Comment by d4rken** [comment]
The next update simplifies the notifications which will result in less notification updates and also fix this problem (as well as other notification spam related issues).
