### ISSUE TITLE
Clutterreport: /data/data/com.mheducation.readerShellApp.readAnywhere/files (FP)

### ISSUE THREAD

**Issue by CaptainFrosty** [d4rken/sdmaid-public#2950]
### Target
Target: `/data/data/com.mheducation.readerShellApp.readAnywhere/files`
Prefix-free: `com.mheducation.readerShellApp.readAnywhere/files`
Path-prefix: `/data/data/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `ReadAnywhere`
Packagename: `com.mheducation.readerShellApp.readAnywhere`
Version: `2.1.10 (1909101523)`

### SD Maid
Version: `4.14.35 (41435)`

### Device
Fingerprint: `samsung/dream2qltesq/dream2qltesq:7.0/NRD90M/G955USQS2BQL1:user/release-keys`

### Comment
`downloaded textbooks that take up an enormous amount of space`

**Comment by d4rken** [comment]
Wouldn't the user want to keep their textbooks?

**Comment by CaptainFrosty** [comment]
maybe, but they are 2+ GB and people may not be aware of it

**Comment by d4rken** [comment]
If this is deleted, will they be downloaded again?

Can you offer more details on the path I think "files" is too broad, is there a subdirectory?

Might be able to add this to offline caches.
