### ISSUE TITLE
Feature Request: Built-in anti-malware

### ISSUE THREAD

**Issue by jebeld17** [d4rken/sdmaid-public#2955]
I would find it very useful and helpful to have a simple built-in anti-malware feature built into SD Maid that quickly performs a signature and heuristic-based scan of all files on the user device.
Such a feature can take advantage of already established antivirus engines such as ClamAV (as an example), etc. and give users a privacy-centric alternative to Google's current built-in antivirus solution.

**Comment by d4rken** [comment]
Anti-Malware is out of scope for SD Maid.
