### ISSUE TITLE
Storage items show a size of -1

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2964]
![unnamed](https://user-images.githubusercontent.com/1439229/65683955-d6fd8f80-e05e-11e9-9f53-b07b9e69f99f.png)
[sdmaid_logfile_1569427140760.txt.zip](https://github.com/d4rken/sdmaid-public/files/3657459/sdmaid_logfile_1569427140760.txt.zip)

**Comment by d4rken** [comment]
-154 is the sum of all entries.
-1 is the default size prior to calculation.

The underlying issue is that size was not calculated, or calculated and then reset and not recalculated (if changes were made).

**Comment by 1nikolas** [comment]
Here is what I did exactly:
-Entered Android/data
-Entered 2 subdirs
-Deleted something
-Clicked "data" from the top bar (so its 2 folders back)
-(showing old sizes) Clicked refresh and this happened

**Comment by d4rken** [comment]
Can reproduce. :heart:

**Comment by d4rken** [comment]
Just refreshing a folder is enough to trigger this. The top bar is supposed to navigate the existing cached tree, while the FAB is supposed to refresh the current subtree.

The refresh hooks a new subtree of items into the existing tree, but then calls `calculate` without setting `force=true`. The node in the existing tree, that we connect our refreshed subtree to (e.g. `Android/data`, still has it's size calculated, so it won't recalculate without `force=true`, while the refreshed (new) items in the new subtree (`Android/data/*`) all have their initial size value of `-1`.

**Comment by d4rken** [comment]
I'm passing the `force=true` along correctly now and I've also add a call such that any changes to child elements of a node automatically reset the size of the parent node.

This bug was a nice find :+1:
