### ISSUE TITLE
Request: How do I root this phone? 

### ISSUE THREAD

**Issue by bundie1990** [d4rken/sdmaid-public#2965]
### What should the feature do?
It should root my device because I've never done it. 

### When/How would you use it?
Always. Before, during and after boot. 

### How would you implement it?
In just looking for an experience. 

### SD Maid
Version: `4.14.35 (41435)`
Unlocker: `4.3.9 (40309) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `motorola/sperry_sprint/sperry:7.1.1/NCQS26.69-64-21/26:user/release-keys`

**Comment by d4rken** [comment]
Rooting is out of scope for SD Maid.

For instructions on how to root your device, search XDA and lookup Magisk.
