### ISSUE TITLE
AppControl stops after going to home screen

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#297]
I started AppControl and switched to my home screen and waited until the app was done. After I saw the app finished building the list I opened the notification but AppControl looked like it never started.

**Comment by d4rken** [comment]
If there are no other indicators this is not a bug. The system removed SD Maid to free memory in favor of another process. If you do a debug run while this happens you will likely see something like: ```onTrimMemory: TRIM_MEMORY_COMPLETE``` 

http://developer.android.com/reference/android/content/ComponentCallbacks2.html#TRIM_MEMORY_COMPLETE

Reopen if you find information pointing to something else.
