### ISSUE TITLE
Unlocker icon can't be hidden on Android 10

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2972]
https://issuetracker.google.com/issues/130152645

**Comment by nift4** [comment]
My ideas:
- Provide possibility to buy Pro as an In-App Purchase
- Create a message that the app can't hide itself but eventually the launcher can

**Comment by d4rken** [comment]
I'm adding IAP as unlock option and will hide the "hide option" for Android 10+ in the unlocker.
