### ISSUE TITLE
SystemCleaner hint about different paths leading to public storage

### ISSUE THREAD

**Issue by Trasd** [d4rken/sdmaid-public#298]
@d4rken, ticket open per your request (https://plus.google.com/100388844525777256771/posts/LirjZMQStBH?_utm_source=1-2-2).  Even though I believe my Google+ issue and your interpretation were a bit off, this nonetheless registered in you something that needs attention.

With SD Maid, only the newer OS path aliases work.

In the examples below, where all the paths point to the same directory (from root), on my system only the first one works in SD Maid:

/storage/emulated/0/Test
/sdcard/Test
/mnt/sdcard/Test

The problem is that I was to the point of pulling my hair out because my custom User Filters were not working, as well as some exclusions, because I was using older paths descriptions.

Can something be done to warn users that an invalid path has been entered when appropriate?

**Comment by d4rken** [comment]
Maybe add an options menu entry that links to a wiki page about creating user filters?

**Comment by Trasd** [comment]
Others may have better ideas, but since there are no consistent directories across all Android devices, maybe have step-by-step instructions in a tutorial that starts off by creating and populating a folder specifically for the purpose of using it with filters.  Other than that, I'm lost as to how to demonstrate with generic instructions.

Also, the demo folder's creation and population could somehow be automated from within Maid.

Food for thought....

**Comment by d4rken** [comment]
I've expanded the documentation for the SystemCleaner.

Any thoughts on what to add to explain this issue further, such that we could link from within the app to the wiki page?
https://github.com/d4rken/sdmaid-public/wiki/Systemcleaner

**Comment by Trasd** [comment]
Matthias, maybe put a "?" at the top of the **Filter manager**, **SystemCleaner** - **USER** screen, to the left of the _add new_ and _Import icons_, or on the **USER** new-filter screen itself (there are no icons on the right side of the toolbar on the screen).

Might I also suggest you mention that the paths that are used in the filters be taken from Maid's Explorer (long-press the current path at the top of Explorer's screen to copy it to the clipboard)?  This way, there is no chance of enetering an invalid path for Maid (the reason I originally opened this ticket).  It's the first entry at the top that has:

> In the examples below, where all the paths point to the same directory (from root), on my system only the first one works in SD Maid:
> 
> /storage/emulated/0/Test
> /sdcard/Test
> /mnt/sdcard/Test

I also some a few items on the linked Wiki that needs attention, but I'll get back to you on that one.

BTW, Bold (**) markdown doesn't seem to work, in Preview, if not in the sentry's body itself.

**Comment by d4rken** [comment]
I added a link to the toolbar of the filter creation page.
It links to https://github.com/d4rken/sdmaid-public/wiki/Systemcleaner#userfilter

> Might I also suggest you mention that the paths that are used in the filters be taken from Maid's Explorer (long-press the current path at the top of Explorer's screen to copy it to the clipboard)?

The Explorer already has an option "Create filter" which opens the filter creation page with the selected path.
