### ISSUE TITLE
Invalid path for document chooser

### ISSUE THREAD

**Issue by Bluscream** [d4rken/sdmaid-public#2983]
Why can't your app just go with the path it gets?

And how can i find out the path my documentpicker returns so i can give it to you for acceptance

**Comment by d4rken** [comment]
Normally, SD Maid displays both the label and path of what should be selected, see:
https://github.com/d4rken/sdmaid-public/wiki/Setup

**Comment by d4rken** [comment]
I don't understand so issue, please provide additional details.

> Why can't your app just go with the path it gets?

SD Maid looks up all storage sections of your device, checks for which access is needed and then asks you to provide that access if necessary. Providing a path different from what SD Maid asks for doesn't make sense here.

> And how can i find out the path my documentpicker returns so i can give it to you for acceptance

Post a video or screenshots from the point where you are unable to continue.

**Comment by Bluscream** [comment]
Well, i get it only on a couple of occasions, and then when i try to run a task it would say "Setup required", in which it doesn't accept any path as valid path. I have to restart the device a few times before sdmaid doesn't ask for setup again

**Comment by d4rken** [comment]
Take a few screenshots the next time this happens, they should show the dialog which displays which path SD Maid is looking for, and which path you are selecting.

The only instances I know of where the permissions "get lost" is when an app is installed a removable sdcard and the device is rebooted.

**Comment by Bluscream** [comment]
It didn't happen yet

**Comment by d4rken** [comment]
Closing this topic due to inactivity, if necessary, just re-open.

**Comment by Bluscream** [comment]
oh, i definitly have way too many open issues. Anyway, i don't own the device that i had the issue with anymore and haven't had it on another device
