### ISSUE TITLE
Clutterreport: /data/app/com.google.android.trichromelibrary_386509238-BNzqulWfIsldWr5s_tkrOg== (FP)

### ISSUE THREAD

**Issue by ajayjohn** [d4rken/sdmaid-public#2987]
### Target
Target: `/data/app/com.google.android.trichromelibrary_386509238-BNzqulWfIsldWr5s_tkrOg==`
Prefix-free: `com.google.android.trichromelibrary_386509238-BNzqulWfIsldWr5s_tkrOg==`
Path-prefix: `/data/app/`
Type: `DIRECTORY`
Location: `APP_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
None

### SD Maid
Version: `4.14.36 (41436)`

### Device
Fingerprint: `google/crosshatch/crosshatch:10/QP1A.190711.020.C3/5869620:user/release-keys`

### Comment
`Causes the phone to bootloop in Android 10, when the corpse finder deletes this file. `

**Comment by d4rken** [comment]
To which package does this belong though?

**Comment by ajayjohn** [comment]
My hunch is that I related to the browser or web-view. This is because the file icon is that of the in-built browser (not chrome) and after the file is deleted, before rebooting, the first symptom is the Chrome browser and any apps that use a web-view start crashing.

**Comment by d4rken** [comment]
If you enable system apps for AppControl and search for "trichromelibrary" or similar keywords, does any package show up?

**Comment by ajayjohn** [comment]
Nothing shows up. I tried a few combinations of search strings and none of them yielded any results. Even enabled system apps in App Control just to rule out that option.

**Comment by d4rken** [comment]
I'd have expect for either `com.google.android.trichromelibrary` or `org.chromium.trichromelibrary` to exist.

Can you zip the folder and send/upload it?

**Comment by d4rken** [comment]
Will set up matching for Chrome and WebView but I think other manufactors will use different packages names there. Due to this having a bigger impact I'll also set `android` as custodian for this.

**Comment by ajayjohn** [comment]
Thanks! Do you still need the .zip file you requested for earlier?

**Comment by d4rken** [comment]
Currently not,  thanks.
I'll revert this fix again for a cleaner solution in v4.14.38. Instead of clutter entries we'll pull the list of "shared libraries" which will contain this app.
