### ISSUE TITLE
Exclusions Bug

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#300]
I made a fresh install of the beta app and the beta pro key. When i press the exclusions button i get an instant crash. The bad thing is that this crash has no recovery for me. No matter if i kill the app or reboot my phone the app wont open. Instead there will be a crash message saying that the app has stopped. Only an uninstall and reinstall allows me to use the app.

**Comment by d4rken** [comment]
Thanks for the report. I assume you are using v4.0.5?
I've commited a fix and it will be released in v4.0.6.
It sadly keeps crashing because SD Maid tries to open on the same page.

**Comment by Geocfu** [comment]
Yes the version is v4.0.5. Thank you!
