### ISSUE TITLE
Sepperately show what SD Maid did while the UI was closed.

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#301]
These bugs are from the Beta version 4.0.5.
I had enabled the Uninstall watcher for the CorpseFinder. When i uninstalled an app the the notification showend up and did its thing. When i came back after some time to the app, the cleaned statistics were being shown on the QuickAccess CorpseFinder tab. Is this behaviour normal?

**Comment by d4rken** [comment]
Yeah that's normal. The uninstall watcher is just another trigger for the CorpseFinder worker, as there can currently only be one worker per type, when you open the UI and the server that holds the worker was not pushed out of memory yet, the UI pulls the last from the worker and displays it.

Do you have an idea how this could be done better, or less confusing?

**Comment by Geocfu** [comment]
I think it might be more sufficient if there is a pop-up message every time you open the app(if threre is something to display) displaying what happend during the off-app period(like what got deleted or what have failed?).

**Comment by d4rken** [comment]
Where do we draw the line though? What about SD Maid being open and 4 tools running but you are only looking at one page of SD Maid, technically you would  only have seen what one tool did (ok except if you have QuickAcess open).

A future update will bring detailed statistics such that you could see what each tool deleted. Would this solve this issue? 

Imagine you trigger SD Maid, then do something else shortly, then open SD Maid again, now we need to pull the last results. Wouldn't showing a popup everytime be annoying? I mean you just launched SD Maid a few seconds ago and just quickly switched apps. And we would still need to show the results in the UI besides the popup.

**Comment by Geocfu** [comment]
I think the creation of a new tab at the slide menu showing what is happening/has happend on the app since its last trigger start. (That would be awesome!)

**Comment by d4rken** [comment]
The new statistics/history page covers this.
