### ISSUE TITLE
Clutterreport: /storage/emulated/0/.aide (FP)

### ISSUE THREAD

**Issue by nift4** [d4rken/sdmaid-public#3019]
### Target
Target: `/storage/emulated/0/.aide`
Prefix-free: `.aide`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `AIDE Web`
Packagename: `com.aide.web`
Version: `1.0.190514 (1905140001)`

Appname: `AIDE`
Packagename: `com.aide.ui`
Version: `3.2.190809 (1908090002)`

Appname: `AIDE PhoneGap`
Packagename: `com.aide.phonegap`
Version: `1.2.160216 (1602160003)`

### Current owners
Appname: `AIDE PhoneGap`
Packagename: `com.aide.phonegap`
Version: `1.2.160216 (1602160003)`

Appname: `AIDE`
Packagename: `com.aide.ui`
Version: `3.2.190809 (1908090002)`

### SD Maid
Version: `4.14.35 (41435)`

### Device
Fingerprint: `motorola/cedric/cedric:8.1.0/OPPS28.85-13-2/d04a4:user/release-keys`

**Comment by d4rken** [comment]
Good report, I've fixed this also for future packages by regex matching `com.aide.*`
