### ISSUE TITLE
Clutterreport: /storage/emulated/0/fixperms.sh (new)

### ISSUE THREAD

**Issue by TowliexXl** [d4rken/sdmaid-public#3034]
### Target
Target: `/storage/emulated/0/fixperms.sh`
Prefix-free: `fixperms.sh`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Termux`
Packagename: `com.termux`
Version: `0.75 (75)`

Appname: `Root Browser`
Packagename: `com.jrummyapps.rootbrowser.classic`
Version: `2.7.6.0 (27600)`

### Current owners
None

### SD Maid
Version: `4.14.38 (41438)`

### Device
Fingerprint: `UMIDIGI/Power_EEA/Power:9/PPR1.180610.011/1557998488:user/release-keys`

**Comment by tkelley731** [comment]
Unsubscribe

**Comment by d4rken** [comment]
Sure about "Root Browser"? I can find references for Termux, but not Root Browser.
