### ISSUE TITLE
Bug: SD Maid Accessibility AppCleaner broken with One UI 2.0/Android 10

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#3036]
### What happened?
I ran the accessibility cleaner and it gets stuck on the first app.

### What did you expect to happen?
The accessibility cleaner should run through the app list cleaning each app as expected.

### How can I reproduce the issue?
Get a Samsung device (now all the S10 editions save the 5G variant) and enroll in the beta via the Samsung Members app. You have to be living in South Korea, the USA, or Germany. Download and install Android 10 beta with OneUI 2 via Settings > Software update. Run the Accessibility service for the AppCleaner and notice it gets stuck in a loop.

### Comments
Don't know what Samsung did with the clear cache and data buttons that's breaking things. Seems to be an overlay at the bottom of the app info screen now that follows the user around as they scroll. Hopefully Samsung didn't just break the service for good.

### SD Maid
Version: `4.14.38 (41438)`
Unlocker: `4.3.9 (40309) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/beyond2qlteue/beyond2q:10/QP1A.190711.020/G975U1UEU2ZSJA:user/release-keys`

**Comment by d4rken** [comment]
Related to #2909

**Comment by d4rken** [comment]
Pre Android 10 AOSP labels will be used by Samsung devices on Android 10.
