### ISSUE TITLE
Can't Delete Cache On Vivo Funtouch 4+

### ISSUE THREAD

**Issue by ianz56** [d4rken/sdmaid-public#3046]
SD Maid like Can't touch delete cache 
![Screenshot_20191020_085628](https://user-images.githubusercontent.com/41635087/67153823-8d7d2900-f31a-11e9-9ef6-fd0f6e6dd6be.jpg)

**Comment by d4rken** [comment]
The UI looks very different from other ROMs which is why SD Maid likely can't find the correct button to press.

Please share a debug log of this situation: https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
