### ISSUE TITLE
Why do SD maids distinguish between uppercase and lowercase in English?

### ISSUE THREAD

**Issue by Vstory** [d4rken/sdmaid-public#3062]
The root directory is `/storage/emulated/0/`,the path contains the settings below.
1.If the actual path of the file is `Tencent/MobileQQ/chatpic/chatthumb/`;
2.The path that must be included is written by `tencent/MobileQQ/chatpic/chatthumb/
` ;
SD Maid does not scan junk files and directories.
Why do custom rules for system cleanup distinguish between uppercase and lowercase directories?

`Tencent/` and `tencent/` are two results.

**Comment by SuperSandro2000** [comment]
Cause this is the normal *nix way.

**Comment by d4rken** [comment]
@SuperSandro2000 Is correct.

While the public internal storage, is usually case insensitive, the system cleaner also searches the internal partitions, if root is available, which are case-sensitive. While the chance is low, going case-insensitive may cause false positives. Some tools make use of case-insensitive matching, e.g. some AppCleaner filters, custom system filters do not.

@Vstory It's possible to achieve case-insensitive matching by using the regex matching option when creating custom filters.

**Comment by Vstory** [comment]
> @SuperSandro2000 Is correct.
> 
> While the public internal storage, is usually case insensitive, the system cleaner also searches the internal partitions, if root is available, which are case-sensitive. While the chance is low, going case-insensitive may cause false positives. Some tools make use of case-insensitive matching, e.g. some AppCleaner filters, custom system filters do not.
> 
> @Vstory It's possible to achieve case-insensitive matching by using the regex matching option when creating custom filters.


I specified the scan path as `PUBLIC_DATA` & `SDCARD`，I don't know how to write case insensitive for the following example.
Can you write an example for this attachment? 
`{"color":"#03a9f4","description":"QQ聊天缓存图片","identifier":"753eb3fc3374.scuf.sdm","label":"QQ","locations":["PUBLIC_DATA","SDCARD"],"mainPath":["/storage/emulated/0/"],"pathContains":["Tencent/MobileQQ/chatpic/chatthumb","Tencent/MobileQQ/chatpic/chatraw","Tencent/MobileQQ/chatpic/chatimg","Tencent/MobileQQ/diskcache/"],"version":4}`

**Comment by Vstory** [comment]
> @SuperSandro2000 Is correct.
> 
> While the public internal storage, is usually case insensitive, the system cleaner also searches the internal partitions, if root is available, which are case-sensitive. While the chance is low, going case-insensitive may cause false positives. Some tools make use of case-insensitive matching, e.g. some AppCleaner filters, custom system filters do not.

To prevent scanning to the system partition, I specified the scan location for it.  `PUBLIC_DATA` & `SDCARD`.

**Comment by d4rken** [comment]
> To prevent scanning to the system partition, I specified the scan location for it. PUBLIC_DATA & SDCARD

The SystemCleaner doesn't change case-sensitivity based on the specified locations. If you think this something SD Maid should do, please make a feature request ticket.

> Can you write an example for this attachment?

https://regex101.com/r/pGjvJr/1

Theoretically you can also match the whole path with a regex, but regex matching is slower than normal matching. So you can do a few tricks to speed filtering by adding stuff like `mainPath: ["/storage/emulated/0"]` or `pathContains: ["encent/"]` to only apply the regexes to relevant paths.

```json
{
	"color":"#03a9f4",
	"description":"QQ聊天缓存图片",
	"identifier":"753eb3fc3374.scuf.sdm",
	"label":"QQ",
	"locations":[
		"PUBLIC_DATA",
		"SDCARD"
	],
	"mainPath":[
		"/storage/emulated/0/"
	],
	"pathContains":[
		"encent/"
	],
	"regexes":[
		"(?i)(.+\/tencent\/mobileqq\/chatpic\/chatthumb(\/)*).*",
		"(?i)(.+\/tencent\/mobileqq\/chatpic\/chatraw(\/)*).*",
		"(?i)(.+\/tencent\/mobileqq\/chatpic\/chatimg(\/)*).*",
		"(?i)(.+\/tencent\/mobileqq\/diskcache\/).*"
	],
	"version":4
}
```

You can also test this in SD Maid
![Screenshot from 2019-11-01 16-44-35](https://user-images.githubusercontent.com/1439229/68036973-04290780-fcc7-11e9-8230-a0913a7c3085.png)

**Comment by Vstory** [comment]
> > To prevent scanning to the system partition, I specified the scan location for it. PUBLIC_DATA & SDCARD
> 
> The SystemCleaner doesn't change case-sensitivity based on the specified locations. If you think this something SD Maid should do, please make a feature request ticket.
> 
> > Can you write an example for this attachment?
> 
> https://regex101.com/r/pGjvJr/1
> 
> The prepended `(?i)` makes it match case insensitive.
> 
> Theoretically you can also match the whole path with a regex, but regex matching is slower than normal matching. So you can do a few tricks to speed filtering by adding stuff like `mainPath: ["/storage/emulated/0"]` or `pathContains: ["encent/"]` to only apply the regexes to relevant paths.
> 
> ```json
> {
> 	"color":"#03a9f4",
> 	"description":"QQ聊天缓存图片",
> 	"identifier":"753eb3fc3374.scuf.sdm",
> 	"label":"QQ",
> 	"locations":[
> 		"PUBLIC_DATA",
> 		"SDCARD"
> 	],
> 	"mainPath":[
> 		"/storage/emulated/0/"
> 	],
> 	"pathContains":[
> 		"encent/"
> 	],
> 	"regexes":[
> 		"(?i)(.+\/tencent\/mobileqq\/chatpic\/chatthumb(\/)*).*",
> 		"(?i)(.+\/tencent\/mobileqq\/chatpic\/chatraw(\/)*).*",
> 		"(?i)(.+\/tencent\/mobileqq\/chatpic\/chatimg(\/)*).*",
> 		"(?i)(.+\/tencent\/mobileqq\/diskcache\/).*"
> 	],
> 	"version":4
> }
> ```
> 
> You can also test this in SD Maid
> ![Screenshot from 2019-11-01 16-44-35](https://user-images.githubusercontent.com/1439229/68036973-04290780-fcc7-11e9-8230-a0913a7c3085.png)


Thank you for your reply.
I don't think there is a need to distinguish between path case when `PUBLIC_DATA & SDCARD` is specified.This makes it easier for users who are not familiar with regular expressions to create rules.
Or provide an option to decide whether to distinguish between path case.
