### ISSUE TITLE
Clutterreport: /system/etc/prop.default (FP)

### ISSUE THREAD

**Issue by 26082608** [d4rken/sdmaid-public#3065]
### Target
Target: `/system/etc/prop.default`
Prefix-free: `etc/prop.default`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `build.prop Editor`
Packagename: `org.nathan.jf.build.prop.editor`
Version: `2.0.1 (4)`

### Current owners
None

### SD Maid
Version: `4.14.36 (41436)`

### Device
Fingerprint: `samsung/a20psq/a20p:9/PPR1.180610.011/A205USQU2ASI7:user/release-keys`

**Comment by d4rken** [comment]
That app may edit this file, but it doesn't own it.
