### ISSUE TITLE
Clutterreport: /storage/1FB0-0A18/contacts

### ISSUE THREAD

**Issue by amir8256** [d4rken/sdmaid-public#3066]
### Target
Target: `/storage/1FB0-0A18/contacts`
Prefix-free: `contacts`
Path-prefix: `/storage/1FB0-0A18/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Contacts Storage`
Packagename: `com.android.providers.contacts`
Version: `10.1.11 (1011103000)`

### Current owners
Appname: `?`
Packagename: `com.jbapps.contactpro`
Version: `null (0)`

Appname: `?`
Packagename: `com.jbapps.contact`
Version: `null (0)`

### SD Maid
Version: `4.14.38 (41438)`

### Device
Fingerprint: `samsung/j7y17ltexx/j7y17lte:9/PPR1.180610.011/J730FXXU5CSG3:user/release-keys`

**Comment by d4rken** [comment]
I don't think this relation is correct, can you share more details?
