### ISSUE TITLE
system cleaner import sort by date?

### ISSUE THREAD

**Issue by patrickdrd** [d4rken/sdmaid-public#3067]
hello,
can you please add an option or sort files by date when importing user filters for system cleaner?

also, the last exported path should be remembered/saved,

thanks

**Comment by patrickdrd** [comment]
it seems that I've already requested this one since july:
https://github.com/d4rken/sdmaid-public/issues/2772

so maybe you could implement it some time soon please?

**Comment by d4rken** [comment]
Closing due to dub #2772
