### ISSUE TITLE
sdext2

### ISSUE THREAD

**Issue by mmasic** [d4rken/sdmaid-public#307]
/data/sdext2 is default mount point for Link2SD - /dev/block/mmcblk1p2 > /dev/block/vold/179:130
and it should be included as search location for SDMaid.

**Comment by d4rken** [comment]
How is it used? What kind of data does it contain? In which tools should it be included as search location?

**Comment by mmasic** [comment]
From https://play.google.com/store/apps/details?id=com.buak.Link2SD&

"Link2SD uses a secondary partition on your SD card and uses it as another segment of internal storage.
Link2SD moves apk, dalvik-cache (.dex), lib and internal data files into this partition, which the OS mounts on boot, and creates a symbolic link in the original location.
This retains the file structure that the system expects but with the bulk of the data moved to the SD card."

IMHO this "location" should be included in every step of cleaning.

**Comment by d4rken** [comment]
Please attach a pathdamp of the file structure if you have time.

> Link2SD moves apk, dalvik-cache (.dex), lib and internal data files into this partition

These are specific storage location where each does not take part in all of SD Maids tools, e.g. dalvik and lib data is something the CorpseFinder only looks at, while internal datafiles and apk files is something AppControl and AppCleaner could be interrested in.

While you want it included, others seem to want the opposite:
https://github.com/d4rken/sdmaid-public/issues/254

After going stable I'll probably have to find the time to setup a test system for this.
> /data/sdext2 is default mount point for Link2SD

Is that configurable, what do we do if the user changes the default location? Can we detect it?

**Comment by mmasic** [comment]
> Please attach a pathdamp of the file structure if you have time.
[sdext2.txt](https://github.com/d4rken/sdmaid-public/files/129200/sdext2.txt)

> While you want it included, others seem to want the opposite: #254
MO is when you buy vacuum cleaner, it should've access to ALL corners of your flat floor.

> Is that configurable, what do we do if the user changes the default location? Can we detect it?
[11link2sd.txt](https://github.com/d4rken/sdmaid-public/files/129203/11link2sd.txt)
In general you can change only mounted partition - meaning /data/sdext2 stays.

**Comment by d4rken** [comment]
Are you certain that SD Maid is not checking those already?
Theoretically SD Maid should follow the symlinks.

It's weird that link2sd dumps all apk files into the /data/sdext2/ folder instead of creating another subfolder like it did for app and app-lib.

**Comment by mmasic** [comment]
> Are you certain that SD Maid is not checking those already?
Theoretically SD Maid should follow the symlinks.

No, I'm not sure.
But, I just added manually sdext2 as search path for databases (only tab that allows adding custom path to search locations) and result was different than previous run.

**Comment by d4rken** [comment]
I would imagine it duplicates the databases as it then scan the same content twice (if symlink is activated as setting).
According to code tools like CorpseFinder and AppCleaner should already follow symlinks by default.
Unfortunately i have currently no link2sd setup where i could test this.

If you can record a debugrun (advanced settings) we should be able to see what was scanned.

**Comment by mmasic** [comment]
[dump.zip](https://github.com/d4rken/sdmaid-public/files/129270/dump.zip)

**Comment by d4rken** [comment]
Thanks.

According to the log, at least CorpseFinder and AppCleaner are following the symlinks by default and matching them correctly.

Unless you see a specific case where this is not working I would consider closed.
