### ISSUE TITLE
Duplicate feature not finding identical files

### ISSUE THREAD

**Issue by sabret00the** [d4rken/sdmaid-public#308]
It's the same file. So quite literally a duplicate but with one has a "-" in the filename while the other doesn't i.e. "file - name.mp3" vs "file name.mp3"

**Comment by sabret00the** [comment]
[sdmaid_logfile_1455725931294 .txt](https://github.com/d4rken/sdmaid-public/files/134839/sdmaid_logfile_1455725931294.txt)

Oops, log didn't attach the first time.

**Comment by d4rken** [comment]
Would you also tell the pathes+names we are talking about so I can find them in the log :)?

**Comment by d4rken** [comment]
One example that fits your criteria is this:
``` text
1455725974573 V/SDM:CheckSum: MD5 CHECKSUM for:/storage/371E-2FF8/Music/Clementine/Kano/Flow Of The Year  Dirty Die (KING KONG Riddim)/Kano  Flow Of The Year featuring JME.mp3 is 6DD24EA6CF1F71BA9430461552561C93
1455725974933 V/SDM:CheckSum: MD5 CHECKSUM for:/storage/371E-2FF8/Music/Clementine/Kano/Flow Of The Year  Dirty Die (KING KONG Riddim)/Kano - Flow Of The Year featuring JME.mp3 is B97E1093FF695CCB469A6DBE2BB61AD0
```
Both files are found, but they have a different checksum.

**Comment by d4rken** [comment]
Closing this due to working as expected, if you have new information that says otherwise, just reopen the issue.

**Comment by sabret00the** [comment]
Thank you for taking the time to look into it.
