### ISSUE TITLE
Clutterreport: /storage/sdcard1/micro_thumbnail_blob.0 (new)

### ISSUE THREAD

**Issue by fajar1111** [d4rken/sdmaid-public#3088]
### Target
Target: `/storage/sdcard1/micro_thumbnail_blob.0`
Prefix-free: `micro_thumbnail_blob.0`
Path-prefix: `/storage/sdcard1/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Berkas`
Packagename: `com.android.fileexplorer`
Version: `1.7.7 (1770)`

### Current owners
None

### SD Maid
Version: `4.14.39 (41439)`

### Device
Fingerprint: `Xiaomi/kenzo/kenzo:5.1.1/LMY47V/V8.0.6.0.LHOMIDG:user/release-keys`

**Comment by d4rken** [comment]
Got more infos on this?
