### ISSUE TITLE
SD Maid ask for sd card setup with no card inserted

### ISSUE THREAD

**Issue by SuperSandro2000** [d4rken/sdmaid-public#309]
On my older phone I have no sd card inserted but a slot for it and Sd maid ask every start to setup a sd card that is not inserted. I can't dismiss the setup dialog and I can only use the app if I choose the internal storage. Then sd maid says that is the wrong storage and I can close the dialog.

**Comment by d4rken** [comment]
Let's start with a debug log.
If can force record a debug log without going into settings by creating a file named ```sdm_force_debug_run``` on your internal storage.

What path is SD Maid displaying when asking for storage permission?

**Comment by d4rken** [comment]
What phone, what ROM?

**Comment by SuperSandro2000** [comment]
`=== BEGIN ===
1455880805397 I/null: SD Maid logfile: /storage/emulated/0/Android/data/eu.thedarken.sdm/files/logfiles/sdmaid_logfile_1455880805392.log
1455880805398 I/SDM:SDMaid: Debuglevel: 2
1455880805398 I/SDM:SDMaid: Getting ready (✿◠‿◠)
1455880805399 I/SDM:SDMaid: samsung/cm_golden/golden:5.1.1/LMY49F/8da9875ebc:userdebug/test-keys
1455880805461 D/SDM:SDMaid: Bugsnag setup done.
1455880805461 I/SDM:SDMaid: Install ID: 69cc4fb2-c60d-48b6-9b52-f4443a790d67
1455880805470 I/SDM:SDMaid: F: VERSIONNAME:4.0.6; VERSIONCODE:4006
1455880805473 I/SDM:SDMaid: P: VERSIONNAME:4.0.1; VERSIONCODE:4001
1455880805558 D/SDM:SDMaid: onTrimMemory: TRIM_MEMORY_RUNNING_MODERATE
1455880805742 I/SDM:SDMaid: Debuglevel: 2
1455880805743 I/SDM:SDMMainActivity: I'm SD Maid, how can i help you? ^_^
1455880805743 V/SDM:SDMMainActivity: onCreate
1455880805777 D/SDM:SDMServiceActivity: requestBinder(eu.thedarken.sdm.SDMMainActivity@2800df0a)
1455880806005 V/SDM:SDMMainActivity: initDrawer
1455880806012 D/SDM:SDMMainActivity: savedInstanceState == null
1455880806013 D/SDM:SDMServiceActivity: Connecting to SDMService(eu.thedarken.sdm.SDMMainActivity@2800df0a)
1455880806263 D/SDM:SDMServiceActivity: requestBinder(AppControlFragment{2bc8bbe #1 id=0x7f0d0077 eu.thedarken.sdm.appcontrol.AppControlFragment})
1455880806265 D/SDM:SDMMainActivity: onStart
1455880806265 V/SDM:SDMMainActivity: onPostCreate
1455880806266 V/SDM:SDMMainActivity: onResume
1455880806266 D/SDM:SDMServiceActivity: requestBinder(eu.thedarken.sdm.SDMMainActivity@2800df0a)
1455880806267 D/SDM:SDMServiceActivity: requestBinder(eu.thedarken.sdm.navigation.p@97db36c)
1455880806310 D/SDM:SDMService: onCreate
1455880806316 D/SDM:SDMService: onStartCommand
1455880806318 D/SDM:SDMService: onBind
1455880806328 V/SDM:SDMMainActivity: onAttachedToWindow
1455880806986 I/SDM:SDMServiceActivity: SDMService is bound
1455880806986 D/SDM:SDMServiceActivity: Delivering SDMBinder(eu.thedarken.sdm.SDMMainActivity@2800df0a)
1455880806987 D/SDM:SDMService: Deactivating worker notifications.
1455880806987 D/SDM:SDMServiceActivity: Delivering SDMBinder(AppControlFragment{2bc8bbe #1 id=0x7f0d0077 eu.thedarken.sdm.appcontrol.AppControlFragment})
1455880807029 D/SDM:AppControlWorker: WORKERBUS uncacheBusEvents()
1455880807031 D/SDM:SDMServiceActivity: Delivering SDMBinder(eu.thedarken.sdm.navigation.p@97db36c)
1455880807338 V/SDM:AppControlFragment: WORKERBUS: Cached worker event:[rx.a@df4db0e OnCompleted]
1455880807339 V/SDM:AppControlFragment: onCompleted
1455880807340 V/SDM:AppControlFragment: internalSwitchWorkingState(false)
1455880809221 V/SDM:SDMMainActivity: onDrawerClosed
1455880811337 D/SDM:SDMMainActivity: onPause
1455880811840 V/SDM:SDMMainActivity: onSaveInstanceState
1455880811855 D/SDM:SDMServiceActivity: onStop
1455880811855 D/SDM:SDMServiceActivity: Disconnecting from SDMService(eu.thedarken.sdm.SDMMainActivity@2800df0a)
1455880811859 D/SDM:SDMaid: onTrimMemory: TRIM_MEMORY_UI_HIDDEN
1455880811859 D/SDM:SDMService: onUnbind
1455880811860 D/SDM:SDMService: Activating worker notificatio`
Path: /storage/sdcard1
Phone: S3 mini (golden), Rom: [Novafusions CM](http://novafusion.pl/)

**Comment by d4rken** [comment]
Thanks, but the log doesn't include a storage setup. Did you do one?
As these logs grow very large please attach them as file.

A menu entry that offers "Don't show again" should become visible after failing to select the correct path, that's another bug though and it currently only shows after rotating the device. Fixed this for the next release now, but maybe we can still fix the underlying issue.

**Comment by SuperSandro2000** [comment]
I tried it again. New log.
[sdmaid_logfile_1455889468621.txt](https://github.com/d4rken/sdmaid-public/files/138032/sdmaid_logfile_1455889468621.txt)

**Comment by d4rken** [comment]
The issue likely stems from this:
```
Output:/dev/fuse on /storage/sdcard1 type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other)
```

Why is there a mount for sdcard1 if there is no extra sdcard.
Could this be a ROM issue?

**Comment by SuperSandro2000** [comment]
I had a sd card inserted a while back. Maybe it wasn't removed properly.

**Comment by d4rken** [comment]
I'm closing this for now as this seems to be a ROM issue, if you find new information that points into another direction just reopen it. :coffee:
