### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/DumpCollector(com.samsung.carrier.logcollector)-3.6.00(360000000).apk (FP)

### ISSUE THREAD

**Issue by chaddabb** [d4rken/sdmaid-public#3091]
### Target
Target: `/storage/emulated/0/Download/DumpCollector(com.samsung.carrier.logcollector)-3.6.00(360000000).apk`
Prefix-free: `Download/DumpCollector(com.samsung.carrier.logcollector)-3.6.00(360000000).apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `9 (28)`~~

~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `9 (28)`~~

~~Appname: `Download Manager`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `9 (28)`~~

### SD Maid
Version: `4.14.39 (41439)`

### Device
Fingerprint: `samsung/a10esq/a10e:9/PPR1.180610.011/A102USQU2ASI1:user/release-keys`

**Comment by chaddabb** [comment]
Spy apps

**Comment by CPU1803** [comment]
> ### Target
> Target: `/storage/emulated/0/Download/DumpCollector(com.samsung.carrier.logcollector)-3.6.00(360000000).apk`
> Prefix-free: `Download/DumpCollector(com.samsung.carrier.logcollector)-3.6.00(360000000).apk`
> Path-prefix: `/storage/emulated/0/`
> Type: `FILE`
> Location: `SDCARD`
> Current keeper state: `true`
> Suggested keeper state: `false`
> 
> ### Suggested owners
> ### Current owners
> ~Appname: `Android System`~
> ~Packagename: `android`~
> ~Version: `9 (28)`~
> 
> ~Appname: `Downloads`~
> ~Packagename: `com.android.providers.downloads.ui`~
> ~Version: `9 (28)`~
> 
> ~Appname: `Download Manager`~
> ~Packagename: `com.android.providers.downloads`~
> ~Version: `9 (28)`~
> 
> ### SD Maid
> Version: `4.14.39 (41439)`
> 
> ### Device
> Fingerprint: `samsung/a10esq/a10e:9/PPR1.180610.011/A102USQU2ASI1:user/release-keys`
