### ISSUE TITLE
Chronic improvement

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#310]
### **Chronic**
Its nice to see that something i suggested has been implemented. Of course i am talking about chronic. So, if it is possible, make the chronic's statistics show as-per-tool (namely APPCLEANER, SYSTEMCLEANER) separately. That is, when you press inside the chronic a button(eg. the APPCLEANER button) it will only show the button's statistics. That way the chronic will be much more clean and easy to read. Thanks.

**Comment by d4rken** [comment]
Thanks. I think the column color state should be easy to fix. I've created a second ticket (#311) that way I can work on a specific issue and close a ticket when it's done for maximum satisfaction :wink: .

You can already type in "appcleaner" to only show AppCleaner entries. We could possibly add a menu entry that opens a popup and within that popup are the different tools, if you select one it automatically inserts e.g. "APPCLEANER" into the search field. This would both filter it and teach the user about this way of filtering. What do you think @Geocfu ?

**Comment by Geocfu** [comment]
Thats a good idea but i am not completely sure. Lets test it and see the results. Also, with all the respect, if the idea of chronic was first stated by me, if it is possible i would like to see my name somewhere in the app ex. in Credits. It feels good to see your name somewhere where you have helped and contributed. Thank you.

**Comment by d4rken** [comment]
If you mean #301, I'm sorry to say that is not where this feature originated from. The base idea was suggested in some email over a year ago, but the architecture at that point did not allow to add this very neatly as it is now.

I'll credit you for the chart bug though :smile: .

**Comment by Geocfu** [comment]
Well i am happy to hear that. Also about the chart bug credit. Mention me with my xda name "Geocfu1" if it is possible . Thanks alot.
