### ISSUE TITLE
[Explorer] More accurate file size.

### ISSUE THREAD

**Issue by spicyfoxx** [d4rken/sdmaid-public#3112]
I want 2 digits behind the `.` so I could see the file size more accurate without doing extra steps. Can you change the default to `x.xx` (2 digits behind the `.`) or add a feature that let the user change how many digits they want to see?
If possible I want this to apply with `kB`, `MB` and other digital storage units too.
![20191117_102717](https://user-images.githubusercontent.com/24849056/69002588-e2658c80-0924-11ea-8845-4925fa700651.jpg)

**Comment by isabel030maria** [comment]
> Quiero 2 dígitos detrás `.`para poder ver el tamaño del archivo con mayor precisión sin hacer pasos adicionales. ¿Puede cambiar el valor predeterminado a `x.xx`(2 dígitos detrás del `.`) o agregar una función que permita al usuario cambiar cuántos dígitos quiere ver?
> Si es posible quiero que esto se aplica a `kB`, `MB`y otras unidades de almacenamiento digitales también.
> ![20191117_102717](https://user-images.githubusercontent.com/24849056/69002588-e2658c80-0924-11ea-8845-4925fa700651.jpg)

https://github.com/d4rken/sdmaid-public/issues/3112#issue-523929704
