### ISSUE TITLE
Request: Hello. Wonderful tool you've created here. I simply wanted to say your team is exceptional! Thanks again...

### ISSUE THREAD

**Issue by mrwinfield** [d4rken/sdmaid-public#3113]
### What should the feature do?
I'm patiently waiting for the next feature!

### When/How would you use it?
Honestly, I use this app on a frequent basis. I depend on it and it's never failed me!

### How would you implement it?
Thanks again and great work!

### Comments
Kevin Scott

### SD Maid
Version: `4.14.39 (41439)`
Unlocker: `4.3.9 (40309) (true)`

### Device
Root: `Unknown

**Comment by d4rken** [comment]
Thanks, doing my best! :smiley:
