### ISSUE TITLE
Clutterreport: /storage/emulated/0/Pictures/Microsoft Edge feedback.jpg (FP)

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#3116]
### Target
Target: `/storage/emulated/0/Pictures/Microsoft Edge feedback.jpg`
Prefix-free: `Pictures/Microsoft Edge feedback.jpg`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Edge`
Packagename: `com.microsoft.emmx`
Version: `42.0.24.4048 (4048024)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `10 (29)`

### SD Maid
Version: `4.15.0 (41500)`

### Device
Fingerprint: `samsung/beyond2qlteue/beyond2q:10/QP1A.190711.020/G975U1UEU2ZSKF:user/release-keys`

### Comment
`Screenshots captured through feedback in the browser. Follows the naming scheme of normal screenshots. Titled "Microsoft Edge feedback" and "Microsoft Edge feedback (1)" etc.`

**Comment by Coke08** [comment]
> ### Target
> Target: `/storage/emulated/0/Pictures/Microsoft Edge feedback.jpg`
> Prefix-free: `Pictures/Microsoft Edge feedback.jpg`
> Path-prefix: `/storage/emulated/0/`
> Type: `FILE`
> Location: `SDCARD`
> Current keeper state: `false`
> Suggested keeper state: `false`
> 
> ### Suggested owners
> Appname: `Edge`
> Packagename: `com.microsoft.emmx`
> Version: `42.0.24.4048 (4048024)`
> 
> ### Current owners
> Appname: `Android System`
> Packagename: `android`
> Version: `10 (29)`
> 
> ### SD Maid
> Version: `4.15.0 (41500)`
> 
> ### Device
> Fingerprint: `samsung/beyond2qlteue/beyond2q:10/QP1A.190711.020/G975U1UEU2ZSKF:user/release-keys`
> 
> ### Comment
> `Screenshots captured through feedback in the browser. Follows the naming scheme of normal screenshots. Titled "Microsoft Edge feedback" and "Microsoft Edge feedback (1)" etc.`
