### ISSUE TITLE
[Purchase] Make the IAP available for people who already purchased the Unlocker. 

### ISSUE THREAD

**Issue by spicyfoxx** [d4rken/sdmaid-public#3117]
The in-app-purchase is inaccessible for people who already purchased Pro version using the Unlocker method. Can you add an option to buy it again using the IAP method somewhere in the Settings? Can you also make the app recommends users to uninstall the Unlocker if they bought the Pro version through the IAP method but still having the Unlocker app installed?
![Screenshot_20191123-203027_SD Maid](https://user-images.githubusercontent.com/24849056/69479693-bc634f00-0e32-11ea-997b-cd95a9f5d757.jpg)

**Comment by d4rken** [comment]
> Can you add an option to buy it again using the IAP method somewhere in the Settings?

If you long press settings, there is a debug option to show the upgrade dialog. I'll look into making this available somewhere less hidden.

> Can you also make the app recommends users to uninstall the Unlocker if they bought the Pro version through the IAP method but still having the Unlocker app installed?

Good idea.
