### ISSUE TITLE
Clutterreport: /data/data/杂末2 (FP)

### ISSUE THREAD

**Issue by csc001** [d4rken/sdmaid-public#3126]
### Target
Target: `/data/data/杂末2`
Prefix-free: `杂末2`
Path-prefix: `/data/data/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `?`
Packagename: `杂末2`
Version: `null (0)`

### SD Maid
Version: `4.14.39 (41439)`

### Device
Fingerprint: `Xiaomi/land/land:6.0.1/MMB29M/9.9.9:user/release-keys`

### Comment
`There are two folders in the date / user / 0 folder that cannot be deleted. These two folders are left after uninstalling qq, but they cannot be deleted. You can rename and copy them, but they cannot be deleted.`

**Comment by d4rken** [comment]
If you can rename them you should be able to delete them.
Can you post a debug log of it failing?

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
