### ISSUE TITLE
Clutterreport: /storage/emulated/0/GCam

### ISSUE THREAD

**Issue by spencebain** [d4rken/sdmaid-public#3142]
### Target
Target: `/storage/emulated/0/GCam`
Prefix-free: `GCam`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `org.codeaurora.snapcam`
Version: `null (0)`

### SD Maid
Version: `4.15.1 (41501)`

### Device
Fingerprint: `OnePlus/OnePlus7Pro/OnePlus7Pro:10/QKQ1.190716.003/1911140100:user/release-keys`

### Comment
`there is another subfolder`

**Comment by d4rken** [comment]
Are you reporting that this should be a "keeper", i.e. kept after app uninstall?
