### ISSUE TITLE
Clutterreport: /storage/emulated/0/AMap/data_v6/mapcache/res_time_stmp/res_tm_14.db

### ISSUE THREAD

**Issue by anarchize01** [d4rken/sdmaid-public#3143]
### Target
Target: `/storage/emulated/0/AMap/data_v6/mapcache/res_time_stmp/res_tm_14.db`
Prefix-free: `AMap/data_v6/mapcache/res_time_stmp/res_tm_14.db`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `"Bixby" voice wake-up`
Packagename: `com.samsung.android.bixby.wakeup`
Version: `2.1.14.12 (211400012)`

Appname: ``
Packagename: `android.ext.services`
Version: `null (-1)`

### Current owners
Appname: `?`
Packagename: `com.autonavi.minimap`
Version: `null (0)`

### SD Maid
Version: `4.14.39 (41439)`

### Device
Fingerprint: `samsung/dream2qltesq/dream2qltesq:9/PPR1.180610.011/G955USQS7DSK2:user/release-keys`

**Comment by d4rken** [comment]
Hm, relation to #3145 ?
