### ISSUE TITLE
[REQUEST/QUESTION] Delete files older than X days

### ISSUE THREAD

**Issue by AndhikaWB** [d4rken/sdmaid-public#3147]
It would be nice if SD Maid is able to delete files inside a specified folder if they are older than X days.

This is very useful for most chat and messaging apps like WhatsApp, Telegram, etc. The current version of SD Maid is able to delete these  kind of files (received and sent files for messaging app) but the user has no control over it (all files will be deleted, no matter if it's new or old).

**Comment by d4rken** [comment]
You can achieve this using SystemCleaner user filters: https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner#minimum-age

**Comment by AndhikaWB** [comment]
I actually want to close this issue but.. Are all fields on user filter required to be filled?

This is an example of my user filter (doesn't work):

```
{
    "version": 4,
    "label": "WhatsApp Media Files",
    "description": "Delete all WhatsApp sent and received (media) files if older than 90 days.",
    "identifier": "6ebe88d7da1b.scuf.sdm",
    "color": "#03a9f4",
    "rootOnly": false,
    "targetType": "FILE",
    "mainPath": [
        "\/storage\/emulated\/0\/WhatsApp Media\/"
    ],
    "minimumAge": 7776000000
}
```
Since the file names and extensions of sent and received files could be anything then I dont give any file name filter. Should it be `*.*` on regex? Then what should I write on name init and name ending?

Also is this recursive search? There are some more folder inside `WhatsApp Media` like `WhatsApp Images`, `WhatsApp Images/Sent`, `WhatsApp Videos`, `WhatsApp Videos/Sent`, etc. that I don't want to write every of them manually (since it's quite tiring).

**Comment by d4rken** [comment]
Is the path correct? Isn't it `WhatsApp/Media`

```json
{
   "color":"#03a9f4",
   "description":"1 Element @ /storage/emulated/0/WhatsApp",
   "identifier":"40758be62324.scuf.sdm",
   "label":"3147",
   "locations":[
      "SDCARD"
   ],
   "mainPath":[
      "/storage/emulated/0/WhatsApp/Media/"
   ],
   "minimumAge":7776000000,
   "targetType":"FILE",
   "version":4
}
```

> Since the file names and extensions of sent and received files could be anything then I dont give any file name filter. Should it be *.* on regex? Then what should I write on name init and name ending?

You can create a filter inside SD Maid, then export it to view the minimal amount of fields. Theoretically just a `mainPath` is enough.

The explorer also has an action to create basic filters for you which can then still extend.

> Also is this recursive search? There are some more folder inside WhatsApp Media like WhatsApp Images, WhatsApp Images/Sent, WhatsApp Videos, WhatsApp Videos/Sent, etc. that I don't want to write every of them manually (since it's quite tiring).

All files are part of search and the filter is matched against each entry, e.g.

```
/dirA
/dirA/file1
/dirA/dirB/file2
/dirB/file2
```
etc.

The filter will be matched against each and if it matches, the file will be suggested for deletion.

In the above example, if you have `mainPath` = `/dirA/` the whole content of `dirA` will be deleted.

Hint: For best performance, if you use regex (you don't have to), use a non regex rule to sort out stuff early, regex is expensive and will be matched last, if any criteria helps to rule out results earlier, you get a faster scan.

**Comment by AndhikaWB** [comment]
Uh sorry, it actually works since the beginning, just checked my WhatsApp folder and the oldest file is from October (so SD Maid really delete everything older than 3 months).

I must be having so many media files on my WhatsApp folder so that the differences are almost not noticeable at first (only saved less than 50 MBs, which is quite disappointing for me). Of course this is not SD Maid's fault, guess I need to lower the minimum age to a month...

Thank you.

**Comment by d4rken** [comment]
Thanks for the update.
