### ISSUE TITLE
Clutterreport: /storage/9C33-6BBD/Android/media/audio (FP)

### ISSUE THREAD

**Issue by honsberg** [d4rken/sdmaid-public#3148]
### Target
Target: `/storage/9C33-6BBD/Android/media/audio`
Prefix-free: `audio`
Path-prefix: `/storage/9C33-6BBD/Android/media/`
Type: `DIRECTORY`
Location: `PUBLIC_MEDIA`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `audio`
Version: `null (0)`

### SD Maid
Version: `4.15.2 (41502)`

### Device
Fingerprint: `motorola/cedric/cedric:8.1.0/OPP28.85-19-4-2/3447de:user/release-keys`

### Comment
`Benutzer Klingelton etc.`

**Comment by d4rken** [comment]
can you show me what files are inside?
