### ISSUE TITLE
Clutterreport: /storage/emulated/0/.archivetemp (new)

### ISSUE THREAD

**Issue by artipalka** [d4rken/sdmaid-public#3154]
### Target
Target: `/storage/emulated/0/.archivetemp`
Prefix-free: `.archivetemp`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Dysk`
Packagename: `com.google.android.apps.docs`
Version: `2.19.212.04.40 (192120440)`

### Current owners
None

### SD Maid
Version: `4.14.39 (41439)`

### Device
Fingerprint: `HUAWEI/POT-LX1EEA/HWPOT-H:9/HUAWEIPOT-L21/293C431:user/release-keys`

**Comment by d4rken** [comment]
Sure about this?
