### ISSUE TITLE
Quickaccess progress information jumps depending on content

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#317]
While the app operates the cleanup, the titles of the tools in the Quick Access tab are "jumping", but slightly.

**Comment by d4rken** [comment]
Do you mean at the end when the operation finished?

**Comment by Geocfu** [comment]
While the operation is taking place and is showing the names of the files that are being scanned and deleted.

**Comment by d4rken** [comment]
K, if you have time a video would be cool, but only if it's not too much effort.

**Comment by Geocfu** [comment]
I am using a custom rom and the screen recording feature is not supported. Also i have finished the app translations on crowdin and have written my name on the translators, take a look if you can.

**Comment by Geocfu** [comment]
I managed to screenshot the effect. In order for you to see it, you need to download the pictures and go fast from one to the other.Note that this happens with all the tools not /w just the SystemCleaner.
![screenshot_2016-03-06-14-51-55](https://cloud.githubusercontent.com/assets/9702033/13554307/3e5d8778-e3ad-11e5-96b7-d4cfa1187045.png)
![screenshot_2016-03-06-14-52-00](https://cloud.githubusercontent.com/assets/9702033/13554308/3e61ce46-e3ad-11e5-9f5b-e9f0b435d3bb.png)

**Comment by d4rken** [comment]
:+1: 
Wow it seems like the capital letters push the bounds?

**Comment by Geocfu** [comment]
Not exactly. Here is the effect on the CorpseFinder tool.
Example 1:
![screenshot_2016-03-06-16-51-43](https://cloud.githubusercontent.com/assets/9702033/13554913/898114ea-e3bc-11e5-87be-65b1ce2440ab.png)
![screenshot_2016-03-06-16-51-49](https://cloud.githubusercontent.com/assets/9702033/13554914/89868880-e3bc-11e5-99ee-3575721c4aed.png)
Example 2:
![screenshot_2016-03-06-16-51-52](https://cloud.githubusercontent.com/assets/9702033/13554917/94a3c9c6-e3bc-11e5-957a-e37ba228b9d0.png)
![screenshot_2016-03-06-16-51-53](https://cloud.githubusercontent.com/assets/9702033/13554918/94a4c89e-e3bc-11e5-8255-e7435254642c.png)
