### ISSUE TITLE
My Lenovo K8 note heat and automatically restart

### ISSUE THREAD

**Issue by a55g** [d4rken/sdmaid-public#3172]
My Lenovo K8 note heat and automatically restart

**Comment by JavkhlanK** [comment]
Uninstall some battery-eating apps or stop them. If that doesn't help, go to a service centre.

**Comment by d4rken** [comment]
SD Maid tries to get work done as quickly as possible, throttling SD Maid is out of scope.

If an app can get your device to reboot it's a ROM/Kernel bug or hardware defect. The processor should have lowered frequency if thermals are too high.
