### ISSUE TITLE
Clutterreport: /storage/emulated/0/system

### ISSUE THREAD

**Issue by Skinwalker499** [d4rken/sdmaid-public#3175]
### Target
Target: `/storage/emulated/0/system`
Prefix-free: `system`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.yingyonghui.market`~~
~~Version: `null (0)`~~

### SD Maid
Version: `4.15.3 (41503)`

### Device
Fingerprint: `Sony/I4113_EEA/I4113:9/53.0.A.8.71/252988725:user/release-keys`

**Comment by d4rken** [comment]
To which app does this belong?
