### ISSUE TITLE
QuickAccess title translation size 

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#318]
The translations of the tools at the QuickAccess tab are not being fully shown. Instead only the first word is shown.

**Comment by d4rken** [comment]
Screenshot?

**Comment by Geocfu** [comment]
![screenshot_2016-03-06-12-51-12](https://cloud.githubusercontent.com/assets/9702033/13553850/ae22a934-e39f-11e5-9748-81cbdba083fe.png)
![screenshot_2016-03-06-12-51-18](https://cloud.githubusercontent.com/assets/9702033/13553851/b0fa076a-e39f-11e5-82b6-28e072e24332.png)

The first screenshot represents what is being currently displayed in the QuickAccess.
The second screenshot represents what should be displayed in the QuickAccess.
The translation is on greek language.
