### ISSUE TITLE
Fluid Simulation Analytics files

### ISSUE THREAD

**Issue by zombosses** [d4rken/sdmaid-public#3181]
An app named Fluid Simulation keeps creating analytics files every time it's launched.

And it's launched very often as it's my live wallpaper.

I've disabled its internet access as it just uploads these files with barely any data.

So it always accumulates and in just a day or two makes a 10000 files and a few hundred folders.
![Screenshot_20191210-105653](https://user-images.githubusercontent.com/42095453/70853613-2fae2d00-1ed6-11ea-8aa3-47258b4b7bde.jpg)

I've made a custom filter that just deletes the whole analytics folder. - https://envl.app/rabitsfoot/y6tYOK!fkcwSg58qRKcI1II

**Comment by d4rken** [comment]
Intresting find!

Due to Unity being a widespread engine, we have to be careful as this can be used in many different ways AFAIK.

So we should not generally delete this for every app it matches:
```
SDCARD/Android/data/<pkg>/files/Unity/<UUID>
```

I think we could match just the subfolder `Analytics` though and put it under the analytics filter.
```
SDCARD/Android/data/<pkg>/files/Unity/<UUID>/Analytics
```

Could you use the Explorer function "save directory structure" on the whole folder:
```
SDCARD/Android/data/<pkg>
```

and share that with me?

**Comment by zombosses** [comment]
> Could you use the Explorer function "save directory structure" on the whole folder:
> 
> ```
> SDCARD/Android/data/<pkg>
> ```
> 
> and share that with me?

How do I get the save directory structure option? I can't seem to find it.

The structure is, as you said
`/storage/emulated/0/Android/data/<pkg>/files/Unity/<UUID>/Analytics` 

and after that there's another folder under it
`/ArchivedEvents/157695955000839.2f2c6864`

**Comment by d4rken** [comment]
> How do I get the save directory structure option? I can't seem to find it.

Enable it in the options.

**Comment by zombosses** [comment]
https://envl.app/rabitsfoot/zwXl9g!X99CDZYHRgiqzkoo

I hope this helps

**Comment by d4rken** [comment]
It does, thanks.

```
OnePlus/OnePlus6/OnePlus6:9/PKQ1.180716.001/1909112330:user/release-keys

DIRECTORY  770 10206: 9997    8.19 kB 2019.12.23 21:49:57 /storage/emulated/0/Android/data/games.paveldogreat.fluidsim/files/Unity/29018317-00d5-499b-87d2-5177b9d551c9/Analytics/ArchivedEvents/157711799700099.c3c11664
FILE       660 10206: 9997    8.19 kB 2019.12.23 21:49:57 /storage/emulated/0/Android/data/games.paveldogreat.fluidsim/files/Unity/29018317-00d5-499b-87d2-5177b9d551c9/Analytics/ArchivedEvents/157711799700099.c3c11664/g
FILE       660 10206: 9997    8.19 kB 2019.12.23 21:49:57 /storage/emulated/0/Android/data/games.paveldogreat.fluidsim/files/Unity/29018317-00d5-499b-87d2-5177b9d551c9/Analytics/ArchivedEvents/157711799700099.c3c11664/c
FILE       660 10206: 9997    8.19 kB 2019.12.23 21:49:57 
```
