### ISSUE TITLE
Bug: Initial Scans Produce 0

### ISSUE THREAD

**Issue by JandNL** [d4rken/sdmaid-public#3197]
### What happened?
Selected Corpsefinder, etc. & scanned

### What did you expect to happen?
Should have had at least a few items to clean

### How can I reproduce the issue?
Select Corpsefinder, etc. and run scan.

### Comments
We select and run initial scans for Corpsefinder, Databases, Duplicates, Appcleaner, and SystemCleaner.  Each initial scan shows 0.  This is simply not possible.

### SD Maid
Version: `4.15.4 (41504)`
Unlocker: `4.4.0 (40400) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/beyond0qltesq/beyond0q:10/QP1A.190711.020/G970USQU2CSKP:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log of such a scan:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
