### ISSUE TITLE
QuickAccess Screen doesn't stay on

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#320]
With the lattest update, when the Databases tool is operating (e.g scaning and deleting the databases) my screen goes dark (not off) and opens again but in the lockscreen.

**Comment by d4rken** [comment]
The Databases tool doesn't delete databases, it executes SQL VACUUM.

What was on screen while it went dark, the Databases tool?

**Comment by Geocfu** [comment]
i was on the quickaccess page.

**Comment by d4rken** [comment]
Codewise, I have taken the necessary staps and asked for "SCREEN_ON". This didn't change with the latest update, was this working before?

**Comment by Geocfu** [comment]
Yes my screen before was always on. Never had that issue.

**Comment by d4rken** [comment]
Tried it on 3 of my devices and the screen stayed on, maybe something is wrong with your device?

**Comment by Geocfu** [comment]
I re-installed the app and the unlocker and this issue is still present. Do you need a logcat?

**Comment by Geocfu** [comment]
It happens both when all of the tools are running from QuickAccess and when database tool is operating alone but from the QuickAccess screen. While it optizizes the databases the screen goes dark and then back at lockscreen. Note that if i open the Databases tab from the slide menu this does not happen.

**Comment by d4rken** [comment]
Then it's solved :).

> screen goes dark and then back at lockscreen

That's the important part. This is a symptom of #325 .
The launcher and or system UI is killed which throws the app back to the lockscreen.
The fix for #325 should also fix this.
