### ISSUE TITLE
Clutterreport: /storage/emulated/0/Web Video Caster (FP)

### ISSUE THREAD

**Issue by CaptainFrosty** [d4rken/sdmaid-public#3205]
### Target
Target: `/storage/emulated/0/Web Video Caster`
Prefix-free: `Web Video Caster`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Web Video Caster`~~
~~Packagename: `com.instantbits.cast.webvideo`~~
~~Version: `5.0.0 (2024)`~~

### SD Maid
Version: `4.15.4 (41504)`

### Device
Fingerprint: `samsung/dream2qltesq/dream2qltesq:7.0/NRD90M/G955USQS2BQL1:user/release-keys`

### Comment
`thumbnails`

**Comment by d4rken** [comment]
What do you want changed, SD Maid knows this owner already?
