### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#321]
Some new words (e.g. Chronic) have not been added to the translation's page (Greek).

**Comment by d4rken** [comment]
Where do you still see "Chronic"? I removed it in favor of "History" which is more universally understandable. I thought analog to the german word "Chronik", i could use "Chronic", but in english "History" is more appropriate.

**Comment by Geocfu** [comment]
What i wanted to say is that some words are not implemented to the translation's page. Resulting in having some words inside the app in english and the others in greek. Also i have completed all the translations (all of them to 100%) and still in the app there are words which are not translated yet.

**Comment by d4rken** [comment]
Ah right, some are not localized, please post screenshots of these cases.

**Comment by Geocfu** [comment]
![screenshot_2016-03-06-18-51-45](https://cloud.githubusercontent.com/assets/9702033/13556383/efd35ff4-e3e0-11e5-8574-2d1d8df509f5.png)
![screenshot_2016-03-06-18-52-38](https://cloud.githubusercontent.com/assets/9702033/13556384/efd5e166-e3e0-11e5-90b9-3cb78d21187c.png)
![screenshot_2016-03-06-18-53-58](https://cloud.githubusercontent.com/assets/9702033/13556385/efd8bd5a-e3e0-11e5-985a-47eddaf61ad6.png)
![screenshot_2016-03-06-18-54-06](https://cloud.githubusercontent.com/assets/9702033/13556386/efe00178-e3e0-11e5-9776-f9c634de7e19.png)
![screenshot_2016-03-06-18-57-40](https://cloud.githubusercontent.com/assets/9702033/13556387/efe09336-e3e0-11e5-85e1-7f2dd8b234ae.png)
![screenshot_2016-03-06-18-58-05](https://cloud.githubusercontent.com/assets/9702033/13556388/efe34680-e3e0-11e5-9b0f-5e8723318597.png)
