### ISSUE TITLE
QuickAccess wrong button in single pass mode

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#322]
Can you explain what is the behaviour of the bottom button at the QuickAccess tab? I am quite sure i found another bug.

**Comment by d4rken** [comment]
On first launch offer scan, after completing a scan offer delete, followed by scan again.
While any tool is running it should offer to cancel the actions.

**Comment by Geocfu** [comment]
With the single pass enabled?

**Comment by Geocfu** [comment]
What is its behaviour then?

**Comment by d4rken** [comment]
Then it should always show delete, except when it's running then it show cancel.

**Comment by Geocfu** [comment]
Yes, i was correct. Its a bug.
This is shown when i first open the app:
![screenshot_2016-03-06-15-00-18](https://cloud.githubusercontent.com/assets/9702033/13556891/2fca7276-e3ed-11e5-94df-9e410ab2a0f1.png)

This is when the operation has finished:
![screenshot_2016-03-06-15-02-37](https://cloud.githubusercontent.com/assets/9702033/13556895/60f7f3a0-e3ed-11e5-8147-e7cd99c700fe.png)

Then i pressed scan and this showed up:
![screenshot_2016-03-06-15-03-19](https://cloud.githubusercontent.com/assets/9702033/13556901/7f108ac8-e3ed-11e5-95d5-ecf8ca885bea.png)

And right after the press of the delete this showed up:
![screenshot_2016-03-06-15-04-45](https://cloud.githubusercontent.com/assets/9702033/13556905/930ce1d4-e3ed-11e5-9c35-c4007c0acb8a.png)

While by your words it should always show delete.

**Comment by d4rken** [comment]
Yeah the scan button should not show in single pass mode, I'll look into it.
