### ISSUE TITLE
Clutterreport: /storage/emulated/0/Messaging/sms-20191229141518.xml

### ISSUE THREAD

**Issue by stevenserika28** [d4rken/sdmaid-public#3226]
### Target
Target: `/storage/emulated/0/Messaging/sms-20191229141518.xml`
Prefix-free: `Messaging/sms-20191229141518.xml`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Message service`
Packagename: `com.samsung.android.communicationservice`
Version: `2.0.73 (207317100)`

### Current owners
Appname: `?`
Packagename: `com.sonyericsson.conversations`
Version: `null (0)`

### SD Maid
Version: `4.15.4 (41504)`

### Device
Fingerprint: `samsung/j3popltetfnvzw/j3popltetfnvzw:6.0.1/MMB29M/S327VLUDS4ARF2:user/release-keys`

**Comment by d4rken** [comment]
Can anyone confirm that this is the messaging app on Samsung devices?
