### ISSUE TITLE
Clutterreport: /storage/emulated/0/Mobile Content Transfer/data (new)

### ISSUE THREAD

**Issue by perfectlyimaginary** [d4rken/sdmaid-public#3227]
### Target
Target: `/storage/emulated/0/Mobile Content Transfer/data`
Prefix-free: `Mobile Content Transfer/data`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Messenger`
Packagename: `com.facebook.orca`
Version: `245.0.0.19.113 (189084117)`

### Current owners
None

### SD Maid
Version: `4.15.4 (41504)`

### Device
Fingerprint: `samsung/j2coreplteuc/j2coreplteatt:9/PPR1.180610.011/J260AUCU3BSH6:user/release-keys`

**Comment by d4rken** [comment]
What's inside this folder?
