### ISSUE TITLE
Clutterreport: /system/build.prop (FP)

### ISSUE THREAD

**Issue by sarapaige** [d4rken/sdmaid-public#3236]
### Target
Target: `/system/build.prop`
Prefix-free: `build.prop`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `android.oem.overlay`
Packagename: `android.oem.overlay`
Version: `8.0.0 (26)`

### Current owners
None

### SD Maid
Version: `4.15.4 (41504)`

### Device
Fingerprint: `motorola/hannah_t/hannah:8.0.0/OCPS27.91-150-11-2/3:user/release-keys`

**Comment by sarapaige** [comment]
My device says it has never been rooted but the only storage on my phone I can access is /system/emulated/0. I'm new to all this and just wanting to learn. Any help please

**Comment by d4rken** [comment]
Sounds normal. For further help try a forum specific to your device.
