### ISSUE TITLE
Clutterreport: /storage/emulated/0/.Cool Memo and To Do Tasks with Colourful Reminder Notes (new)

### ISSUE THREAD

**Issue by Chacha4149** [d4rken/sdmaid-public#3238]
### Target
Target: `/storage/emulated/0/.Cool Memo and To Do Tasks with Colourful Reminder Notes`
Prefix-free: `.Cool Memo and To Do Tasks with Colourful Reminder Notes`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Cool Memo and To Do Tasks with Colourful Reminder Notes`
Packagename: `com.ProDataDoctor.CoolMemoToDoTasksNotes`
Version: `1.10 (10)`

### Current owners
None

### SD Maid
Version: `4.15.5 (41505)`

### Device
Fingerprint: `google/crosshatch/crosshatch:10/QQ1A.191205.008/5974827:user/release-keys`

**Comment by d4rken** [comment]
#3237
