### ISSUE TITLE
Clutterreport: /storage/emulated/0/DailyNotesBackup (new)

### ISSUE THREAD

**Issue by Chacha4149** [d4rken/sdmaid-public#3239]
### Target
Target: `/storage/emulated/0/DailyNotesBackup`
Prefix-free: `DailyNotesBackup`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Daily Notes`
Packagename: `com.cemandroid.dailynotes`
Version: `1.9.9 (31)`

### Current owners
None

### SD Maid
Version: `4.15.5 (41505)`

### Device
Fingerprint: `google/crosshatch/crosshatch:10/QQ1A.191205.008/5974827:user/release-keys`

**Comment by d4rken** [comment]
#3237
