### ISSUE TITLE
Statistics bug

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#324]
Same as the previous on ticket about this issue but now is even worse.
Before the "fix" when you were pressing a bar from the graph a toast notification would popup and then  would go away leaving the pressed bar deep green instead of returing it to its original bright state. Now after the "fix" when you press a bar from the graph the toast notification will not popup leaving the pressed bar deep green instead of returing it to its original bright state. :(

**Comment by d4rken** [comment]
That is the desired behavior.
There is no longer a toast, you press a bar, it changes color to signify it has been selected, it will display it's value in the graph near the bar until you press outside of the chart or another bar.

**Comment by Geocfu** [comment]
Ohhh. In my opinion the old was better if the bar wasnt staying deep green after the touch.

**Comment by d4rken** [comment]
Possibly, though subjective.
The current solution is quite clean as it is contained within the chart view.
We can reevaluate after a public release, let's wait for some feedback.
