### ISSUE TITLE
Bug: Caches are not cleaned.

### ISSUE THREAD

**Issue by brobi69** [d4rken/sdmaid-public#3246]
### What happened?
Used system cleaner but after checking cache was not empty.

### What did you expect to happen?
Application caches fully emptied.

### How can I reproduce the issue?
Run system cleaner and check e.g. Chrome's cache.

### Comments
I can send a screen record if you need.

### SD Maid
Version: `4.15.4 (41504)`
Unlocker: `4.4.0 (40400) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/j6ltexx/j6lte:9/PPR1.180610.011/J600FNXXU6BSK2:user/release-keys`

**Comment by brobi69** [comment]
Forgot to mention that reinstalled, checked app permissions etc. But all settings seemed okay to me.

**Comment by brobi69** [comment]
Sorry it wasn't system cleaner, but the app cleaner.
Also I forgot to mention that I reinstalled SD Maid, checked app permissions etc. But all settings seemed okay to me.

**Comment by d4rken** [comment]
Is the accessibility option enabled?
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service

**Comment by brobi69** [comment]
yes it is on.

REgards,

Bácskai Róbert
Budapest

**Comment by d4rken** [comment]
Please provide a video or a debug log demonstrating the issue.

**Comment by brobi69** [comment]
Here is a screen record.
https://drive.google.com/file/d/1kzaO3EghHgodgubBTbW5vJf2B9njw3Gk/view?usp=drivesdk

**Comment by d4rken** [comment]
Either it's possible to clear these, or SD maid think the right action was clicked, when reality it wasn't.

Let's first confirm that it's possible. For an app that SD Maid fails to clear as seen in the video, go yourself to the system settings and click `Clear cache`, does that work?

**Comment by brobi69** [comment]
It works in the app's settings. But let me show you sth interesting... See screenshots. This is sth I've never seen yet. It is displayed of you click on the little "i" on the right in the app cleaner.

[Image]

[Image]
[Image]


________________________________

**Comment by d4rken** [comment]
I can't view the images. I think adding images via inline email response does not work.

**Comment by brobi69** [comment]
okay so here they are attached.

**Comment by d4rken** [comment]
Doesn't work. If you can't open Github, you can mail them to support@darken.eu too

**Comment by brobi69** [comment]
![3](https://user-images.githubusercontent.com/3862387/72246440-fe1ea380-35f2-11ea-93c1-4a232647c51b.jpg)
![2](https://user-images.githubusercontent.com/3862387/72246441-feb73a00-35f2-11ea-99a5-32ddb7bfc39f.jpg)
![1](https://user-images.githubusercontent.com/3862387/72246442-feb73a00-35f2-11ea-8218-4bf6a2b51bc5.jpg)

**Comment by brobi69** [comment]
Uploaded - hope this way you can view now.

**Comment by d4rken** [comment]
Thanks.

The screenshots look normal.

Please record a debug log of SD Maid deleting 1 or 2 caches:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by brobi69** [comment]
[sdmaid_logfile_1578909692004.txt.zip](https://github.com/d4rken/sdmaid-public/files/4052996/sdmaid_logfile_1578909692004.txt.zip)
here it is

**Comment by d4rken** [comment]
`D/Debug:SysInfoModule: isArmed: false`

You disabled deletion in the debug menu :roll_eyes:  

Why?

Toggle `isArmed` to `true`.

**Comment by d4rken** [comment]
![52920602-a0180c00-330e-11e9-855f-5e892abbde2f](https://user-images.githubusercontent.com/1439229/72481578-40b2cc80-37fb-11ea-92f8-c0a11a229377.png)

**Comment by brobi69** [comment]
Thanks. Here's the new bug file.
https://drive.google.com/file/d/1na5jAQbNyQzlM6yqLZlmJp6jnFY3AN--/view?usp=drivesdk

**Comment by d4rken** [comment]
I don't see any error in the log.
Is it still not deleting?
Note that you need to check by doing it manually whether it is possible.
Sometimes it's just not, if you click clear cache manually and reopen the system screen, nothing has changed, with the accessibility service feature, SD Maid depends on the information the system delivers.
