### ISSUE TITLE
Database optimization renders GooglePhotos database unusable

### ISSUE THREAD

**Issue by Maximilian1271** [d4rken/sdmaid-public#326]
After performing a Database Optimization with SDMaid (4.0.8 Beta) GooglePhotos (com.google.android.apps.photos 1.15.0.116298504 (162143)) would only crash after opening. I suspect Database Optimization to be the fault since logcat would throw tons of SQL errors since i did the optimization.

I ran "AppCleaner" as well but i don't suspect this to be the reason why GooglePhotos crashes.
Please investigate :)

[logcat.txt](https://github.com/d4rken/sdmaid-public/files/167420/logcat.txt)

**Comment by d4rken** [comment]
Thanks for the report!
The underlying issue is likely the same as for #325.
I'm publishing v4.0.9 later today which should fix this, if that's not the case let me know.
