### ISSUE TITLE
Clutterreport: /storage/F9E0-1C0F/manga (new)

### ISSUE THREAD

**Issue by dragonfly54** [d4rken/sdmaid-public#3264]
### Target
Target: `/storage/F9E0-1C0F/manga`
Prefix-free: `manga`
Path-prefix: `/storage/F9E0-1C0F/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Tachiyomi`
Packagename: `eu.kanade.tachiyomi`
Version: `0.8.4 (41)`

### Current owners
None

### SD Maid
Version: `4.15.5 (41505)`

### Device
Fingerprint: `lge/k5n_global_com/k5n:6.0.1/MMB29M/1809323273bfc:user/release-keys`

### Comment
`is a manga app `

**Comment by d4rken** [comment]
Is this a custom folder you yourself use for manga or is this created by tachiyomi?

**Comment by spicyfoxx** [comment]
> Is this a custom folder you yourself use for manga or is this created by tachiyomi?

It's probably custom created since I never see a folder like this. 🤔
