### ISSUE TITLE
App Cleaner crashes

### ISSUE THREAD

**Issue by infinitewaveparticle** [d4rken/sdmaid-public#3267]
After just updating to the most recent version today I was able to successfully run the App Cleaner once. Every time after that it hangs on building the search paths. It just sits there and eventually crashes. No buttons work and minimizing and coming back shows a blank screen.

Samsung Galaxy S7 Edge running stock Android 8

**Comment by d4rken** [comment]
First the basics :wink: 
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#step-2---basics

Then if possible a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#step-3---advanced-report
