### ISSUE TITLE
Clutterreport: /storage/emulated/0/backups/PureWriterAutoBackups

### ISSUE THREAD

**Issue by MCmadam** [d4rken/sdmaid-public#3269]
### Target
Target: `/storage/emulated/0/backups/PureWriterAutoBackups`
Prefix-free: `backups/PureWriterAutoBackups`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.jrummy.app.managerfree`
Version: ` (-1)`

Appname: `?`
Packagename: `ccc71.at.free`
Version: ` (-1)`

~~Appname: `?`~~
~~Packagename: `ccc71.at`~~
~~Version: ` (-1)`~~

~~Appname: `?`~~
~~Packagename: `com.estrongs.android.pop.cupcake`~~
~~Version: ` (-1)`~~

~~Appname: `?`~~
~~Packagename: `com.estrongs.android.pop.pro`~~
~~Version: ` (-1)`~~

~~Appname: `?`~~
~~Packagename: `com.estrongs.android.pop.app.shortcut`~~
~~Version: ` (-1)`~~

Appname: `?`
Packagename: `com.estrongs.android.pop`
Version: ` (-1)`

### SD Maid
Version: `4.15.5 (41505)`

### Device
Fingerprint: `samsung/beyond2ltexx/beyond2:10/QP1A.190711.020/G975FXXS3BSL4:user/release-keys`

**Comment by d4rken** [comment]
Hm?
