### ISSUE TITLE
Improve accessibility based app cleaner on Meizu ROMs

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#3273]
By @programmist87 https://github.com/d4rken/sdmaid-public/issues/2396#issuecomment-576581054

> Russian (ru) (Meizu M8, Android 8.1.0, Russian)

> На моём телефоне очистка кэша находится сразу при входе из списка приложений, поэтому Item 1 указать не могу.

> Item 1

> Item 2 Очистить кэш

![72789386-bfb56400-3c44-11ea-8e59-94c41c2281c8](https://user-images.githubusercontent.com/1439229/72870625-f3e26080-3ce8-11ea-9b08-364f6e1cb12a.png)

**Comment by d4rken** [comment]
Can you provide a debug log of SD Maid trying to delete?

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by programmist87** [comment]
Meizu M8

Android: 8.1.0

No root

SD Maid v4.15.5, Unlocker v4.4.0

install ID: bc94d23f-f639-43ca-9ce2-cff6c0210c6e

При попытке очистить недоступный кэш, в окне sd maid открывается окно настроек телефона, и sd maid пытается нажать кнопку "очистить кэш". После нескольких попыток с первым приложением, sd maid переходит к следующему, и так далее. В результате кэш оказывается неочищенным. Служба sd maid в специальных возможностях телефона включена. При новой попытке  очистить повторяется то же самое. Sd maid переустанавливал, результат тот же.

[sdmaid_logfile_1579697896944.txt.zip](https://github.com/d4rken/sdmaid-public/files/4097476/sdmaid_logfile_1579697896944.txt.zip)

**Comment by d4rken** [comment]
Please send me a mail if you want a test version before the next beta :smile:

**Comment by programmist87** [comment]
Пожалуйста, пришлите мне тестовую версию.

вс, 26 янв. 2020 г., 2:08 Matthias Urhahn <notifications@github.com>:

**Comment by d4rken** [comment]
:mailbox: to support@darken.eu

**Comment by programmist87** [comment]
Здравствуйте. Недоступный кэш так и не очищается, к сожалению, проблема осталась.

**Comment by programmist87** [comment]
Доброго дня. Полностью удалил SD Maid и установил новую бета-версию, отправленную на почтовый ящик, проблема все равно осталась(

install ID: 115cd9d1-8b33-4fc2-80fa-4fdf647e49db

[sdmaid_logfile_1584272040470.txt.zip](https://github.com/d4rken/sdmaid-public/files/4334132/sdmaid_logfile_1584272040470.txt.zip)

**Comment by programmist87** [comment]
Все отлично! Теперь работает! Спасибо)

**Comment by d4rken** [comment]
:heart: 

The changes will be part of the next official v4.15.9 update, you can keep using the build I send you, but you might not get notified by Google about the official update until the next one (as they use the same version numbers).

**Comment by programmist87** [comment]
В версии 4.15.12 опять та же проблема 😔 Можете опять прислать бета-версию для этой версии до выхода новой? 

560ee930-d4f0-4d01-8995-c144f353fce0

[sdmaid_logfile_1592207038593.txt.zip](https://github.com/d4rken/sdmaid-public/files/4778831/sdmaid_logfile_1592207038593.txt.zip)

**Comment by programmist87** [comment]
Спасибо! С предыдущей версии до бета-версии и с бета-версии до новой вышедшей версии я всегда могу просто обновлять, не переустанавливать

**Comment by d4rken** [comment]
Yes, for changes such as this you can just upgrade.

**Comment by programmist87** [comment]
Да
