### ISSUE TITLE
AppCleaner loops on Huawei P30 Pro

### ISSUE THREAD

**Issue by michalpl7** [d4rken/sdmaid-public#3275]
Hello,

I have issue with app cache cleaning in AppCleaner on Huawei P30 Pro.

- Device: Huawei P30 Pro
- Android: 10 ( EMUI 10.0.0.178 )
- Device not rooted
- SD Maid PRO 4.15.5 with Unlocker 4.4.0

When I run app cache cleaning which should cycle through all apps and clean their cache it loops on first app and is not going further. Seems it does not recognize UI layout.

Here is how it looks like: [https://www.youtube.com/watch?v=fn4ohAsb-tI](https://www.youtube.com/watch?v=fn4ohAsb-tI)

Greetings,
Mike
[sdmaid_logfile_1579767192346.txt.zip](https://github.com/d4rken/sdmaid-public/files/4101987/sdmaid_logfile_1579767192346.txt.zip)

**Comment by d4rken** [comment]
Instead of "Pamięć i pamięć podręczna" (on AOSP) on Huawei @ Android 10 we need to look for "Pamięć".

Currently waiting on confirmation.

**Comment by d4rken** [comment]
Confirmed to be fixed.
