### ISSUE TITLE
Clutterreport: /system/product/app/Gmail/Gmail.apk (FP)

### ISSUE THREAD

**Issue by joakin2k** [d4rken/sdmaid-public#3276]
### Target
Target: `/system/product/app/Gmail/Gmail.apk`
Prefix-free: `product/app/Gmail/Gmail.apk`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Gmail`
Packagename: `com.google.android.gm`
Version: `2019.09.15.270135155.release (61836890)`

### Current owners
None

### SD Maid
Version: `4.15.5 (41505)`

### Device
Fingerprint: `google/coral/coral:10/QQ1B.200105.004/6031802:user/release-keys`

**Comment by joakin2k** [comment]
I don't know much, Dev, I send you a mail with the logs , Gmail i think it was in other folder...
That's why sd Maid can't delete it (its a system app)...

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
