### ISSUE TITLE
Clutterreport: /storage/emulated/0/Remove Content/.temp (new)

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3277]
### Target
Target: `/storage/emulated/0/Remove Content/.temp`
Prefix-free: `Remove Content/.temp`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Удалить нежелательный объект`
Packagename: `vn.remove.photo.content`
Version: `1.1.7 (16)`

### Current owners
None

### SD Maid
Version: `4.15.5 (41505)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

### Comment
`Здравствуйте. Эта папка является ненужным кэшем приложения, достигла объёма 500 мб. Остаётся неочищенной при всех включённых опциях в настройках`

**Comment by d4rken** [comment]
When is it created by the app?

**Comment by programmist87** [comment]
Кэш создаётся в процессе работы в самом приложении, у приложения нет функций, выполняемых в фоне

**Comment by programmist87** [comment]
После удаления приложения, папку "Remove Content"  удалять не нужно, так как в ней остаются фотографии.

**Comment by d4rken** [comment]
Why are photos inside this folder?

Is this not a trashcan/recyclerbin folder?

**Comment by programmist87** [comment]
Нет, у приложения отсутствует корзина. По какой-то причине оно сохраняет  обработанные фотографии в этой папке.
