### ISSUE TITLE
Jumping labels on quickaccess.

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#328]
After the #314 fix, the textboxes are staying still but the labels below them (eg. Searching) are jumping depending from the current search result.

**Comment by d4rken** [comment]
There is a primary textbox and a secondary textbox. The secondary textbox is vanishing if there is no secondary output. As the items are centered vertically, they may jump due to that. Is that what you mean? Otherwise can you provide some screenshots?

**Comment by Geocfu** [comment]
Maybe this is what is happening. Take a look at some screenshots:
![screenshot_2016-03-11-12-19-40](https://cloud.githubusercontent.com/assets/9702033/13699650/673ee328-e784-11e5-801f-394328a6a15b.png)
![screenshot_2016-03-11-12-19-45](https://cloud.githubusercontent.com/assets/9702033/13699651/673e744c-e784-11e5-9813-eb1120f65739.png)

**Comment by d4rken** [comment]
It's something else.... dam those jumpy boxes.
I'll look into it.

**Comment by d4rken** [comment]
```android:singleLine="true"``` fixed it, ```android:maxLines="1"``` was apparently not enough.
