### ISSUE TITLE
QuickAccess single pass operation bug

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#329]
After the #322 fix, only the button is fixed. What i am trying to say is that after the first press of the "Delete" button everything goes as it should(namely everything gets deleted). After the finish of the operation, the button is displaying "Delete" correctly but the operation that it does is scanning. Then you have to press "Delete" one more time for the scanned items to be deleted.

Before the first press of the "Delete" button:
![screenshot_2016-03-11-02-52-55](https://cloud.githubusercontent.com/assets/9702033/13699385/b58a1e5a-e782-11e5-8431-844c69b13f55.png)

After the first press of the "Delete" button:
![screenshot_2016-03-11-02-50-30](https://cloud.githubusercontent.com/assets/9702033/13699402/c6fa2aea-e782-11e5-9eab-d768c7db785f.png)

After the the second press of the "Delete" button:
![screenshot_2016-03-11-02-49-15](https://cloud.githubusercontent.com/assets/9702033/13699421/e481747e-e782-11e5-9e53-15c1ef678acf.png)

After the the third press of the "Delete" button:
![screenshot_2016-03-11-12-21-42](https://cloud.githubusercontent.com/assets/9702033/13699618/2b260d3a-e784-11e5-9862-0aa400ee96d6.png)

**Comment by d4rken** [comment]
I'll look into.

**Comment by d4rken** [comment]
Next update should fix this.
