### ISSUE TITLE
Bug: Shortcuts not working

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#3304]
### What happened?
I created shortcuts to different activities and they all were the same shortcut, directing to the first activity

### What did you expect to happen?
That you can have more than one shortcut for activities.

### How can I reproduce the issue?
Try adding shortcuts for activities.

### Comments
What's up?

### SD Maid
Version: `4.15.6 (41506)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a70qeea/a70q:9/PPR1.180610.011/A705FNXXU5ASL4:user/release-keys`

**Comment by d4rken** [comment]
All apps? Specific apps? Got a few examples?

Some apps may just have code that redirects you.

**Comment by JavkhlanK** [comment]
I used the Settings app for OneUI 1.1, Android 9. I tested the activities before creating a shortcut for them.

**Comment by JavkhlanK** [comment]
Here's a video of it: https://drive.google.com/file/d/1bsa-j-WRCYVYTJCHwSzgARa4H_mjecWX/view?usp=drivesdk

**Comment by d4rken** [comment]
I fixed a bug that caused the shortcuts to have the same ID, so they would overwrite each other.
I think this is the issue you are experiencing. The fix will be part of 4.15.7
