### ISSUE TITLE
QuickAccess function names cut off

### ISSUE THREAD

**Issue by jpzex** [d4rken/sdmaid-public#331]
On the SD Maid update to 4.0.10, on the "QuickAccess" tab, the name of the functions (corpse finder, system cleaner, app cleaner) are not fully shown, it is cutting the name on the end of the line. That was not happening before. There is a screenshot attached. It is happening in portuguese (br), in english it does not happen because the names are short. I think in other languages it may be happening too.
![shabt](https://cloud.githubusercontent.com/assets/16583317/13940093/36f014ca-efb9-11e5-9413-e4e5155c6fd6.png)

**Comment by d4rken** [comment]
Reopen if it's still not ok with v4.0.11
