### ISSUE TITLE
Delete requiring empty directory 

### ISSUE THREAD

**Issue by sourkarm2** [d4rken/sdmaid-public#332]
Requiring (nested) empty directory deletion is not happening. But there are huge numbers of such directories in internal storage as well as in external storage. Would like have this feature.

**Comment by d4rken** [comment]
Do you mean nested empty directories requiring multiple scans? Like #201 ?

**Comment by sourkarm2** [comment]
Sorry, i made some spelling mistake - -  i mean to say recurring emty directories like dir a contains only  dir b, dir b contains only dir c and dir c is empty. Then cleaning should delete everything including dir a and below.

**Comment by d4rken** [comment]
No problem, you can also edit your posts.

I'm closing this though as it's basically the same feature request as #201, i.e. not having to scan multiple times for nested empty dirs.

Feel free to add thoughts or ideas to ticket #201.
