### ISSUE TITLE
UserFilter - File age based filter attribute

### ISSUE THREAD

**Issue by debopriyobasu** [d4rken/sdmaid-public#333]
Hello! We make backups of many apps/chats of WhatsApp for which we only need the latest backup of the app/chat.Any old backups consume storage space and I would request SD Maid Dev to incorporate a user filter with "keep newest" option in system cleaner so that the old backups get deleted automatically.

**Comment by sonyjosephk** [comment]
I completely agree with you.  It's very must and also allow us to analyze individual directory were Duplicate files can be deleted.

**Comment by d4rken** [comment]
@sonyjosephk What do you mean? You can already add specific scanpaths to the duplicates tool? What does this have to do with this ticket?

**Comment by sonyjosephk** [comment]
Darken,

Coz, your Duplicate Finder fails to recognize it in-spite of specifying the
"Path"

**Comment by d4rken** [comment]
WhatsApp backups are not duplicate files.

**Comment by sonyjosephk** [comment]
Darken,

I am also an tester for Microsoft and I know that WhatsApp backup does not
have Duplicate files but if you read the original post then you woukd
understand what he meant...

You just can't sound rude.  Anyways, I am in a Easter Mood and celebrating
it with my family and closed friends in India.

Regard,
Sony Joseph

WhatsApp backups are not duplicate files.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/d4rken/sdmaid-public/issues/333#issuecomment-202065515>

**Comment by d4rken** [comment]
I understand the original ticket, I don't understand your comments.
>  It's very must and also allow us to analyze individual directory were Duplicate files can be deleted.

What does that mean?

**Comment by sonyjosephk** [comment]
Well reply on this later...

**Comment by d4rken** [comment]
Suspects
```
shell@hammerhead:/sdcard/WhatsApp $ ls -la Databases/
-rw-rw---- root     sdcard_rw  4314259 2016-03-20 02:00 msgstore-2016-03-21.1.db.crypt8
-rw-rw---- root     sdcard_rw  4318019 2016-03-21 02:00 msgstore-2016-03-22.1.db.crypt8
-rw-rw---- root     sdcard_rw  4322675 2016-03-22 02:00 msgstore-2016-03-23.1.db.crypt8
-rw-rw---- root     sdcard_rw  4325811 2016-03-23 02:00 msgstore-2016-03-24.1.db.crypt8
-rw-rw---- root     sdcard_rw  4337299 2016-03-24 02:00 msgstore-2016-03-25.1.db.crypt8
-rw-rw---- root     sdcard_rw  4404835 2016-03-25 02:00 msgstore-2016-03-26.1.db.crypt8
-rw-rw---- root     sdcard_rw  4413763 2016-03-26 02:00 msgstore-2016-03-27.1.db.crypt8
-rw-rw---- root     sdcard_rw  4449651 2016-03-27 03:00 msgstore-2016-03-28.1.db.crypt8
-rw-rw---- root     sdcard_rw  4524803 2016-03-28 02:00 msgstore.db.crypt8
```

**Comment by d4rken** [comment]
> What I'd like to see is the ability to periodically delete photos that are of a certain age and older.

> In the Last Modified view I can return a list by modifying the settings of directory location and min/max > age. It would be great to be able to select all those files returned in the list for deletion.
> Another idea would be to add modification date as a new criteria for a custom filter in System Cleaner, > this would also have the benefit of being able to run from the Scheduler.

**Comment by undersound** [comment]
I would love to see this feature as well. 
A Date From / Date To option in the User section of Filter manager would work for my use case.

**Comment by d4rken** [comment]
Maybe just a date/timepicker combo?

@undersound If you are willing to manually edit a filter (e.g. no ui), I could give you a test version.

**Comment by d4rken** [comment]
Actually we wouldn't want a timepicker combo, because matching needs to be relative.
So we need somekind of slider for "older than X days"?

**Comment by undersound** [comment]
Just out of curiousity why does matching needs to be relative?

> So we need somekind of slider for "older than X days"?
This would already be realy nice to have

**Comment by d4rken** [comment]
Someone creating a filter wants files older than X days, if we save an actual date, and time progresses (as it naturally does), "older than X" value would steadily increase. So we need to save a relative time value.

Probably time in miliseconds, then we just check `currentTime - file.getModTime() > filter.getMinAge()` something like that.

**Comment by undersound** [comment]
For scheduled runs it makes a lot more sense indeed.

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner#minimum-age

Next update.
If someone comes up with a good whatsapp filter we could add it as default.

**Comment by antonio-gil** [comment]
Well, after a brief testing (almost since you've replied on Reddit), I've came up with a filter that considers all backups that are older than today (as WA makes a daily backup in my case) to be deleted.

So far, it works as intended (IMHO), so I can share (just need to know how haha) it to be evaluated by the community.

**Comment by d4rken** [comment]
@antonio-gil https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner#export

**Comment by antonio-gil** [comment]
Perhaps I'm doing something wrong, but is not exporting anything...

Is should be looking for which file type?

**Comment by d4rken** [comment]
Did it say `1 OK` at the bottom after exporting? The file looks like `abe1234fef.scuf.sdm.json`. Default path should be `<sdcard>/Download`.

**Comment by antonio-gil** [comment]
Oddly, I was able to see the file on the device file explorer but not via Windows Explorer (as if it has the "hidden" attribute)

[Here is the exported file](https://drive.google.com/file/d/0Bxx4vyCI9ucbSG5PVU9WVXV1VzVWa0xZbWZuREtqQjY3UnRF/view?usp=sharing).

Regards!

**Comment by d4rken** [comment]
Awesome!

I've made a few more tweaks and added some explanations.
Lets continue this here #904
