### ISSUE TITLE
Crash on Android 4.4

### ISSUE THREAD

**Issue by SergeyAquarius** [d4rken/sdmaid-public#3340]
Good afternoon, Matthias!
Matthias, my friend, I am the beta tester of your program. I have version 4.15.7 installed with the play market, but it does not start on a tablet with android 4.4.2. An error occurred while trying to open the application. All previous versions of the program up to 4.15.6 worked.
Install ID: e34a0a02-58eb-4e3f-a1f6-59b16d6483e8
ROM: Lenovo/A5500-HV/A5500-HV:4.4.2/KOT49H/A5500HV_A442_000_029_150401_ROW:user/release-keys/ru
SD Maid v.4.15.6
SD Maid Pro (key)v.4.4.1

**Comment by d4rken** [comment]
Thanks for the report. I'll fix this today.

**Comment by SergeyAquarius** [comment]
Thank you very much!
You and your team are real good fellows and professionals!

**Comment by d4rken** [comment]
Let's keep this open until I made the change, so I don't forget :sweat_smile: .
