### ISSUE TITLE
What does the number in appcleaner mean?

### ISSUE THREAD

**Issue by redjumper** [d4rken/sdmaid-public#3343]
When using appcleaner, what does the number mean? ![Screenshot_20200305-125709](https://user-images.githubusercontent.com/16910542/75950690-d8bc6080-5ee4-11ea-8adc-6cfa220a17ef.png)
And if i don't select any filter in appcleaner, it still spends time on scaning , filting , and so systemcleaner does.

**Comment by d4rken** [comment]
> When using appcleaner, what does the number mean?

The amount of locations being searched, it's something like <AppCount>*<BaseLocations>.

> And if i don't select any filter in appcleaner, it still spends time on scaning , filting , and so systemcleaner does.

With few exceptions (root/noroot), filters do not affect where is searched, but only what is done with the found files.

**Comment by redjumper** [comment]
> With few exceptions (root/noroot), filters do not affect where is searched, but only what is done with the found files.

Is there any difference with the amount of locations being searched in systemcleaner and in appcleaner?

**Comment by d4rken** [comment]
* SystemCleaner will always search the same amount of locations, filters have no impact on that.
* AppCleaner will determine the locations based your installed apps. You can affect this by excluding apps by packagename. Changing filters should have no effect on the amount of searched locations.
