### ISSUE TITLE
Issue: Corpse Finder (Beta v4)

### ISSUE THREAD

**Issue by sonyjosephk** [d4rken/sdmaid-public#335]
My previous issue related to "CUT & PASTE" is so far resolved in your BETA (Ver. 4) as you have replaced "CUT & PASTE" as "MOVE"

Now the additional issue I have noticed that the " Corpse  Finder" is not removing the certain folder related to that particular app which is usually stored in "Phone Device"

**Comment by d4rken** [comment]
Please provide a debug run log of SD Maid failing to remove that entry.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug

**Comment by d4rken** [comment]
Reopen if further information is available.
