### ISSUE TITLE
Bug: SdMaid Pro starts Tasks without an active scheduler

### ISSUE THREAD

**Issue by alsenbornmax** [d4rken/sdmaid-public#3358]
### What happened?
It happend 3 times now that I randomly saw the SdMaid Notification Popup saying 4 Tasks running. When I click on the notification Sd Maid opens and I can see all 4 Tasks running, so it's not just a notification bug. The problem is all tasks are disabled in the scheduler, I even tried to enable and then disable them again, but that also didn't solve the problem.

### What did you expect to happen?
Scheduler off --> Tasks don't start randomly in the background

### How can I reproduce the issue?
If I'd know I'd stop doing that ^^

### Comments
Galaxy S9 SM G960F, Android 10, No root
### SD Maid
Version: `4.15.6 (41506)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/starltexx/starlte:10/QP1A.190711.020/G960FXXS7DTAD:user/release-keys`

**Comment by d4rken** [comment]
What does SD Maid's statistics section show?

Do you have Settings>CorpseFinder>Uninstall Watcher enabled?

**Comment by d4rken** [comment]
Closing this topic due to inactivity, if necessary, just re-open.
