### ISSUE TITLE
Crashing on android 6 (LG G2 Mini -D620r - Resurrection Remix ROM)

### ISSUE THREAD

**Issue by Vagelis1608** [d4rken/sdmaid-public#336]
Every time I try to do anything (even access the settings) SD Maid prompts me to give it access to the SD. I do but then SD Maid crashes.
When I look at App Permissions of SD Maid, storage is granted.
![screenshot_20160327-133403](https://cloud.githubusercontent.com/assets/6294294/14065220/8b85d0c2-f42a-11e5-84c8-e2b3aec8b638.png)

[log.txt](https://github.com/d4rken/sdmaid-public/files/190880/log.txt)

**Comment by d4rken** [comment]
When being granted the permission SD Maid checks the result code whether the action was successful, if it is successful SD Maid tries to "take" and persist the uri permission it was just granted.

Now despite getting the OK, we didn't get the permission so when trying to take it we crash with a ```SecurityException```. This seems to be a ROM issue, but I've improved upon this a little bit as SD Maid should no longer crash in this case but just show an error.

**Comment by Vagelis1608** [comment]
I figured it out.
It was an xposed module (XInstaller) that was causing the issue.

**Comment by d4rken** [comment]
What does that module do?
I'm seeing similar issues still in the bugtracker, possibly people with the same module?

**Comment by Vagelis1608** [comment]
Here is the link to the Xposed repo entry for XInstaller:
http://repo.xposed.info/module/com.pyler.xinstaller
