### ISSUE TITLE
how the criterias work in user filter

### ISSUE THREAD

**Issue by redjumper** [d4rken/sdmaid-public#3360]
The user filter has many criterias which having effect on the matching result, such like targetType,locations,mainPath,pathContains,regexes,etc. 
I know simple filter creating by the explorer is very fast which only using mainPath and locations because it's a fixed path, but sometimes you need other criterias to match. 
Is there any order when applying these criterias and how they impact the performance?

**Comment by d4rken** [comment]
I've updated the wiki to answer this:
https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner

The listed order is equal to the evaluation order, and later arguments are more costly.

With regex being very costly, and determining the location type being very very costly.

**Comment by redjumper** [comment]
Thanks for the explain, i'm surprised that the locations is slow than regex. The location is never used separately, and it seems that the performance is same whether to use the location in simple filter creating by the explorer. 
Below is a simple filter which i use the explorer to create, the location seems does not impact the performance.
> {
	"color": "#03a9f4", 
	"description": "1 item @ /storage/emulated/0/Android/data/org.telegram.messenger/cache", 
	"identifier": "case1.scuf.sdm", 
	"label": "case1", 
	"locations": [
		"PUBLIC_DATA"
	], 
	"mainPath": [
		"/storage/emulated/0/Android/data/org.telegram.messenger/cache/-2147483648_-210042.jpg"
	],
	"version": 4
}

**Comment by d4rken** [comment]
Regex can just work on the provided path. Location can trigger additional look ups that are costly, whether this happens depends on what SD Maid did previously and whether the information is already cached in memory.

On the same device `locations` can be omitted if you use the full path. But if you want the filters to be cross-device compatible (if you share them), you need to use locations and shorten the path.

This only works on devices similar to yours, and only on your primary public storage. The location doesn't really matter here because the full `mainPath` will only matches one thing.

```json
"locations": ["PUBLIC_DATA"],
"mainPath": [
"/storage/emulated/0/Android/data/org.telegram.messenger/cache/-2147483648_-210042.jpg"
],
```

This variant would work on almost all devices and would also check secondary storage (e.g. removable sdcard):

```json
"locations": ["PUBLIC_DATA"],
"pathContains": ["/org.telegram.messenger/cache/-2147483648_-210042.jpg"]
```

Specifying `PUBLIC_DATA` as location will cause the filter only to match for files in that location, but the location itself will depend on the device.

**Comment by redjumper** [comment]
Now i know `locations` is mainly used for compatibility . I'll rewrite the rules with `locations` and `pathContains`, although i think the location of modern rom's public storage may always be /storage/emulated/0 . 
I still have a few more questions , the following two filters just clean the same files . But i think case3 is more faster , because case2 needs 2 * m * n matchs ,  while case3 needs 2 * 1 * n matchs . Am' i right ? 
```
{
	"color": "#FF4CB050", 
	"description": "case2", 
	"identifier": "case2.scuf.sdm", 
	"label": "case2", 
	"locations": [
		"SDCARD",
		"PUBLIC_DATA"
	], 
	"pathContains": [
        "\/Tencent\/wns\/",
        "\/Tencent\/XG\/",
        "\/Tencent\/mta\/",
        "\/Tencent\/tbs_live_log\/",
        "\/Tencent\/msflogs\/",
        "\/Tencent\/qalsdklogs\/",
        "\/Tencent\/imsdklogs\/",
        "\/Tencent\/imsdkfilecache\/",
        "\/Tencent\/imsdkpiccache\/",
        "\/Tencent\/imsdkvideocache\/",
        "\/Tencent\/wtlogin\/",
        "\/Tencent\/TMAssistantSDK\/",
        "\/tencent\/wns\/",
        "\/tencent\/XG\/",
        "\/tencent\/mta\/",
        "\/tencent\/tbs_live_log\/",
        "\/tencent\/msflogs\/",
        "\/tencent\/qalsdklogs\/",
        "\/tencent\/imsdklogs\/",
        "\/tencent\/imsdkfilecache\/",
        "\/tencent\/imsdkpiccache\/",
        "\/tencent\/imsdkvideocache\/",
        "\/tencent\/wtlogin\/",
        "\/tencent\/TMAssistantSDK\/",
        "\/tencent\/beacon\/",
        "\/Tencent\/beacon\/",
        "\/tencent\/blob\/",
        "\/Tencent\/blob\/",
        "\/tencent\/TPush\/Logs\/",
	"\/Tencent\/TPush\/Logs\/"
    ],
	"regexes": [
		"^(?:.+?\\/(?:T|t)encent\\/msflogs\\/(?>\\w+\\/){3})(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/wns\\/.*Logs\\/[\\w\\.]+\/)([\\W\\w]+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/XG\\/Logs\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/mta[\\d]*\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/tbs_live_log(\\/.+){2})(\\.livelog)$",
		"^(?:.+?\\/(?:T|t)encent\\/(imsdk(logs|(file|pic|video)cache)|qalsdklogs)\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/wtlogin\\/.+\\/)(.+\\.log)$",
		"^(?:.+?\\/(?:T|t)encent\\/TMAssistantSDK\\/Download\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/beacon\\/.+)(\\.dat)$",
		"^(?:.+?\\/(?i:t)encent\\/blob\\/.+\\/)(.+?)$",
		"^(?:.+?\\/(?i:t)encent\\/TPush\\/Logs\\/.+)(\\.txt)$"
	],
	"version": 4
}
```
```
{
	"color": "#FF4CB050", 
	"description": "case3", 
	"identifier": "case3.scuf.sdm", 
	"label": "case3", 
	"locations": [
		"SDCARD",
		"PUBLIC_DATA"
	], 
	"pathContains": [
	"encent"
    ],
	"regexes": [
		"^(?:.+?\\/(?:T|t)encent\\/msflogs\\/(?>\\w+\\/){3})(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/wns\\/.*Logs\\/[\\w\\.]+\/)([\\W\\w]+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/XG\\/Logs\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/mta[\\d]*\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/tbs_live_log(\\/.+){2})(\\.livelog)$",
		"^(?:.+?\\/(?:T|t)encent\\/(imsdk(logs|(file|pic|video)cache)|qalsdklogs)\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/wtlogin\\/.+\\/)(.+\\.log)$",
		"^(?:.+?\\/(?:T|t)encent\\/TMAssistantSDK\\/Download\\/)(.+?)$",
		"^(?:.+?\\/(?:T|t)encent\\/beacon\\/.+)(\\.dat)$",
		"^(?:.+?\\/(?i:t)encent\\/blob\\/.+\\/)(.+?)$",
		"^(?:.+?\\/(?i:t)encent\\/TPush\\/Logs\\/.+)(\\.txt)$"
	],
	"version": 4
}
```

**Comment by d4rken** [comment]
Yeah case3 is likely faster, you'll have to measure it if you want actual numbers.

If you record a debug log of the scans, SD Maid will print timing information for tasks somewhere (filter for `SDM:WorkerHub:Processor`), you can also compare against the `op/s` number in the progress bar.

You shouldn't need to escape the `/` in `pathContains`.

**Comment by redjumper** [comment]
Yeah there is `D/WorkerHub:Processor` showing the time consumed for the task, and does enable debug lag the op/s? 
In my test, case2 is faster then case3, so i'm a bit confused. Let's simplify the case, if the filter only uses `locations` 、`pathContains`、`regexes`, and there is only one value in `pathContains` and one value in `regexes`. Is it right that the less entries `pathContains` sorts out, the more faster the `regexes` finishs?

**Comment by d4rken** [comment]
Yes, debug will make things over all slower, but if you compare it against other debug logs, it should be comparable. Do a few measurements, but if the difference is small, it won't be noticeble as there will be some variance caused by other running apps.

> In my test, case2 is faster then case3, so i'm a bit confused. 

Might just be variance, how large was the difference?

> Let's simplify the case, if the filter only uses locations 、pathContains、regexes, and there is only one value in pathContains and one value in regexes. Is it right that the less entries pathContains sorts out, the more faster the regexes finishs?

The amount of entries in `pathContains` has no impact on how fast `regexes` finishes. SD Maid will only look at `regexes` if one of the `pathContains` matches (or if it is empty). If `pathContains` is not empty and  also does not match the current file object being tested, than SD Maid will abort early and not check the regex. `pathContains` is also compared with the file object under test in the order they are added. So if the first path in `pathContains` already matches the file we are comparing against, SD Maid will stop and continue with the next criteria (possibly the regexes).

**Comment by d4rken** [comment]
I think this makes it easier:

```java
public boolean match(SDMContext sdmContext, SDMFile subject) {
    // Directory or file?
    if (targetType != null && targetType != TargetType.UNDEFINED
            && ((targetType == TargetType.DIRECTORY && !subject.isDirectory()) || (targetType == TargetType.FILE && !subject.isFile()))) {
        return false;
    }

    // Empty or not ?
    if (isEmpty != null && ((isEmpty && !subject.isEmpty()) || (!isEmpty && subject.isEmpty()))) {
        return false;
    }

    // Is our subject too large?
    if (maximumSize != null && (subject.length() > maximumSize)) return false;

    // Maybe it's too small
    if (minimumSize != null && (subject.length() < minimumSize)) return false;

    if (maximumAge != null && (System.currentTimeMillis() - subject.getLastModified().getTime()) > maximumAge) {
        return false;
    }

    if (minimumAge != null && (System.currentTimeMillis() - subject.getLastModified().getTime()) < minimumAge) {
        return false;
    }

    final String subjectPath = subject.getPath();
    final String subjectName = subject.getName();

    boolean matched = false;

    if (possibleBasePathes != null) {
        // Check path starts with
        matched = false;
        for (String beginToken : possibleBasePathes) {
            if (subjectPath.startsWith(beginToken)) {
                matched = true;
                break;
            }
        }
        if (!matched && !possibleBasePathes.isEmpty()) return false;
    }

    if (possiblePathContains != null) {
        // Path contains
        matched = false;
        for (String pathContent : possiblePathContains) {
            if (subjectPath.contains(pathContent)) {
                matched = true;
                break;
            }
        }
        if (!matched && !possiblePathContains.isEmpty()) return false;
    }

    if (possibleNameInits != null) {
        // Check name starts with
        matched = false;
        for (String nameBeginning : possibleNameInits) {
            if (subjectName.startsWith(nameBeginning)) {
                matched = true;
                break;
            }
        }
        if (!matched && !possibleNameInits.isEmpty()) return false;
    }

    if (possibleNameEndings != null) {
        // Check name ends with
        matched = false;
        for (String nameEnding : possibleNameEndings) {
            if (subjectName.endsWith(nameEnding)) {
                matched = true;
                break;
            }
        }
        if (!matched && !possibleNameEndings.isEmpty()) return false;
    }

    if (exclusions != null) {
        // Check what the path should not contain
        for (String hasnot : exclusions) {
            if (subjectPath.contains(hasnot)) {
                return false;
            }
        }
    }

    if (regex != null) {
        // REGEX
        matched = false;
        for (Pattern pattern : regex) {
            if (pattern.matcher(subjectPath).matches()) {
                matched = true;
                break;
            }
        }
        if (!matched && !regex.isEmpty()) return false;
    }
    if (locations != null) {
        // Is correct location?
        //noinspection RedundantIfStatement
        if (!locations.isEmpty() && !locations.contains(sdmContext.getFileForensics().determineLocationType(subject).getLocation())) {
            return false;
        }
    }

    return true;
}
```

**Comment by redjumper** [comment]
Sorry i did not make it clearly,i means the amout `pathContains` matches. 
Now it's very clear, thank you for your help and patience.

**Comment by redjumper** [comment]
Last question,what's the order of exclusions in others setting when applying to systemcleaner. Do they append to user filter's exclusions?

**Comment by d4rken** [comment]
The SystemCleaner applies the exclusions generated via https://github.com/d4rken/sdmaid-public/wiki/Exclusions to the final results,.

**Comment by redjumper** [comment]
Got it, thank you.
