### ISSUE TITLE
App Cleaner - Clear Cache not working (with Accessibility enabled)

### ISSUE THREAD

**Issue by shashankvray** [d4rken/sdmaid-public#3362]
This is a reply to my Play store reply by Developer for being a beta tester.
While having the SD maid running in foreground, (with pro genuine pro unlocker installed), I tried to clean app cache which was supposed to go to app info of every app and click on "Clear Cache" and "OK" button too.
But with the latest Android upgrade, this Clear Cache and Clear Data button is made available only within the option named "Storage" in any app info which would require SD Maid to first open app info of the desired app that is to be cleaned cache of, then click on "Storage" and then click on "Clear Cache" and then "OK".
Having the latest SD Maid Beta installed, when the App Cleaner is let to start its execution process of cleaning cache of every app installed (I've toggled "Clean running apps too" button ON), it just opens app info of an app, (say Chrome) and just stands still there for, like, ever.. I manually have to click on x mark to stop the process.
Please update this feature. Let the app search for "Clear Cache" immediately after entering app-info, if not found then make it to click on "Storage"..

**Comment by d4rken** [comment]
Please provide a debug log and a video of SD Maid trying and failing:

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
