### ISSUE TITLE
Apps uninstall creates ghost apps? (no apk)

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#337]
On some devices apps fail to uninstall and remain in a "ghost"? state where they remain listed as installed without an apk.

**Comment by igoivo** [comment]
The bug is reproducible in at least couple devices (GT-N7100, SM-T311), running 4.1.2 and 4.2.2.
For example:
=== Device info ===
samsung/t03gxx/t03g:4.1.2/JZO54K/N7100XXDMB6:user/release-keys/en
SD Maid: 3.1.4.8[385]  or 4.0.10[4010]
Unlocker: 3.1.0.4[310]  or 4.0.2[4002]
Root: true
Storage0: /storage/sdcard0
Storage1: /storage/extSdCard
=================
The section AppControl lists uninstalled apk-s. It is possible to delete apk's data, which releases large amount (up to 100MB !) of the internal memory by using V3 only, but not with the newest V4, unfortunately. And it lists the uninstalled apk-s again after the device restart. 

Questions:
1) How to delete the data of uninstalled apk-s permanently ?
2) Why does it works in V3 and does not work in V4 ?
3) Does it apk-s dalvik cache ?

Expectation: it should clean all traces of uninstalled apk-s which includes both data and dalvik cache.
So, it must not resume at startup. 

Examples (V3): 
![screenshot_2016-03-24-20-59-16](https://cloud.githubusercontent.com/assets/18104173/14067544/0efc2b04-f467-11e5-988d-53b8a207e7c4.png)

Log report (V4): Uninstalling air.com.adobe.pstouch[keepData:false]
[sdmaid_logfile_1459106796681_extract.txt](https://github.com/d4rken/sdmaid-public/files/191098/sdmaid_logfile_1459106796681_extract.txt)

**Comment by d4rken** [comment]
Can you get me the same log from SD Maid v4?

**Comment by igoivo** [comment]
Dear Matthias
The log was from V4
Regards, yours, Igor I

On 28 March 2016 at 16:46, Matthias Urhahn <notifications@github.com> wrote:

> Can you get me the same log from SD Maid v4?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/d4rken/sdmaid-public/issues/337#issuecomment-202400350>
>



-- 
Regards, yours,
______________
Igor Ivonin, PhD
e-mail:   ivonine@yahoo.com
<https://mail.google.com/mc/compose?to=ivonine@yahoo.com>
Mobile:   +7 915 202 3669
Skype:    igoivo

**Comment by d4rken** [comment]
Oh :frowning: 
The app wasn't a system app, right?
The log indicates that the uninstall through the native package manager was successful. SD Maid additionally checks if all known files are gone too. In this case it's only the apk that SD Maid knows of, and it is gone, so SD Maid is happy deems it successful.

I've tried to reproduce it on a Nexus5, MotoG3, Nexus9 and Note4 without success, though these have 5.0+, so maybe it's 4.1/4.2 specific, but I can't reproduce it on my i9100 either.

We need to narrow it down somehow. Does this happen for all apps or just some?

If you run the "pm uninstall" command manually from a root shell, does this also happen?

> 2) Why does it works in V3 and does not work in V4 ?

Why do you say it works in V3, according the the screenshots the uninstall also leaves "no apk" entries on V3?

**Comment by d4rken** [comment]
I just fixed a bug that caused SD Maid to display a 0kb apk size on <5.0 devices, but I don't think that's your issue as the apk was uninstalled, even after reboots.

**Comment by igoivo** [comment]
Dear Matthias
1) yes, these are custom apps, not system ones
2) It's happened for all apps, which I ever tried to install, both from Google Play and other markets.
3) V3 shows non-zero (more than 100MB intotal) memory waste in such deleted app entries, see the screenshot. V3 allows me to release the memory, unlike V4, which reports zero memory waste. 
4) I have disabled app signatere check (by using Xposed XInstaller). Could it be a reason?
Another consern is that it could be  dalvic cache, which recreares at the device startup. 
Regards. Yours, Igor I. 

-------- Исходное сообщение --------
От: Matthias Urhahn <notifications@github.com> 
Дата: 28.03.2016  18:05  (GMT+03:00) 
Кому: d4rken/sdmaid-public <sdmaid-public@noreply.github.com> 
Cc: igoivo <igor.ivonin@gmail.com> 
Тема: Re: [sdmaid-public] Apps uninstall creates ghost apps? (no apk) (#337) 
 
Oh  
The app wasn't a system app, right?
The log indicates that the uninstall through the native package manager was successful. SD Maid additionally checks if all known files are gone too. In this case it's only the apk that SD Maid knows of, and it is gone, so SD Maid is happy deems it successful.

I've tried to reproduce it on a Nexus5, MotoG3, Nexus9 and Note4 without success, though these have 5.0+, so maybe it's 4.1/4.2 specific, but I can't reproduce it on my i9100 either.

We need to narrow it down somehow. Does this happen for all apps or just some?

If you run the "pm uninstall" command manually from a root shell, does this also happen?

2) Why does it works in V3 and does not work in V4 ?

Why do you say it works in V3, according the the screenshots the uninstall also leaves "no apk" entries on V3?

**Comment by d4rken** [comment]
> 3) V3 shows non-zero (more than 100MB intotal) memory waste in such deleted app entries, see the screenshot. V3 allows me to release the memory, unlike V4, which reports zero memory waste. 

Where do I see 100MB on the screenshot I only see 128kb?

On entries that have a size > 0kb, what details do they show for size? Both v3 and v4 should try to show where the size comes from. In v3 it's in details in v4 it's in details when you press the size card.

>  4) I have disabled app signatere check (by using Xposed XInstaller). Could it be a reason? Another consern is that it could be  dalvic cache, which recreares at the device startup. 

Possibly something xposed related, I don't think dalvik cache as that only gets created if there is an apk to source them from.

You see this issue on multiple of your devices, I don't see it on any of mine. What do your two devices have in common? Same custom ROM? Same Xposed modules?

**Comment by igoivo** [comment]
1) "Where do I see 100MB on the screenshot I only see 128kb?"
I have couple hundreds of uninstalled "no apk" entries. Some of them have large size, see V3 screenshot:
![screenshot_2016-03-29-16-35-55](https://cloud.githubusercontent.com/assets/18104173/14376963/4e4b5730-fd6d-11e5-939e-def3081af026.png)
Thus, in total, it can be up to 100MB!  My problem is that V4 shows zero size and, thus, can clean nothing. 
2) "On entries that have a size > 0kb, what details do they show for size? Both v3 and v4 should try to show where the size comes from. In v3 it's in details in v4 it's in details when you press the size card".
Even V3 shows no details:
![screenshot_2016-04-07-09-12-22](https://cloud.githubusercontent.com/assets/18104173/14377023/b98283b6-fd6d-11e5-9a85-a1cbac016307.png)
But V3 (only V3, not V4) is able to clean:
![screenshot_2016-04-07-09-49-32](https://cloud.githubusercontent.com/assets/18104173/14377051/e44fcdb0-fd6d-11e5-96d5-228fb30f087a.png)

**Comment by igoivo** [comment]
SOLVED: it was XInstaller preventing full uninstallation of the apps.

**Comment by d4rken** [comment]
@igoivo Thanks for clearing that up.
