### ISSUE TITLE
App cleaner keeps freezing up phone.

### ISSUE THREAD

**Issue by futurest1r** [d4rken/sdmaid-public#3373]
Everytime I've used the App cleaner with this phone (Sony Xperia 10 plus Android 9) it freezes my phone. When things do go back to normal (sort of) the system ui crashes multiple times in ten minutes or so as well as settings in my phone being changed. This happens every time I use this option. I'm using the latest version without root. Never had this problem with my other devices, replayed the situation to double check on multiple phones as well. Only happens on Xperia 10 plus.

**Comment by futurest1r** [comment]
![Screenshot_20200316-224734](https://user-images.githubusercontent.com/58458721/76827317-bd522f00-67db-11ea-8370-8ee990170f13.png)

**Comment by d4rken** [comment]
I'm unsure if there is anything I can do about this. Sounds like a ROM instability.

Can you provide a `logcat` from when this occurs? What kind of errors is the system outputting?
