### ISSUE TITLE
Bug: duplicates does not work

### ISSUE THREAD

**Issue by tarkashi38** [d4rken/sdmaid-public#3378]
### What happened?
Under /Android/data, duplicates does not work.

### What did you expect to happen?
If it is the same file, it is a hit in the search.

### How can I reproduce the issue?
Please put the same file under /Android/data and run duplicates.

### SD Maid
Version: `4.15.8 (41508)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `motorola/lake_n/lake_n:10/QPWS30.61-21-3/0f1d7:user/release-keys`

**Comment by d4rken** [comment]
There is a removable default exclusion for `/Android/data` you can remove it yourself.

See
https://github.com/d4rken/sdmaid-public/wiki/Exclusions

**Comment by tarkashi38** [comment]
Hello Matthias-san,

Thank you for your reply.

I understood about Exclusions below.

Best Regards,
Takashi

On Sun, 22 Mar 2020 02:46:28 +0900,
Matthias Urhahn wrote:
