### ISSUE TITLE
SDmaid betta 4.0.x

### ISSUE THREAD

**Issue by Zavatur** [d4rken/sdmaid-public#338]
Guys, you are the best! This program is the best of the best (of all), I even use the Pro version and give the program access Root (fly Sparck IQ4404), but really do not like a bug! When I click "clear application" it together with all the music from the VK removes applications and account for its cache again. Remove yourself. My email zavatur@gmail.com

**Comment by d4rken** [comment]
Do you mean in the AppCleaner?
Please record a debug run log and reproduce the issue on the log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug
Then I should see the files that should not be removed on the log.

Or show me through screenshots or Explorer>Pathdump which files are removed, but should not be.

**Comment by d4rken** [comment]
Closed due to inactivity, reopen if further info is available.
