### ISSUE TITLE
Clutterreport: /mnt/sdcard/Download/IPTV Smarters Pro(com.nst.iptvsmarterstvbox)-2.2.2(67)-base.apk (FP)

### ISSUE THREAD

**Issue by h69-n** [d4rken/sdmaid-public#3380]
### Target
Target: `/mnt/sdcard/Download/IPTV Smarters Pro(com.nst.iptvsmarterstvbox)-2.2.2(67)-base.apk`
Prefix-free: `Download/IPTV Smarters Pro(com.nst.iptvsmarterstvbox)-2.2.2(67)-base.apk`
Path-prefix: `/mnt/sdcard/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System WebView`
Packagename: `com.android.webview`
Version: `39 (5.0.8-arm64) (300002)`

Appname: `CaptivePortalLogin`
Packagename: `com.android.captiveportallogin`
Version: `5.1.1-5.0.8 (22)`

Appname: `IPTV Smarters Pro`
Packagename: `com.nst.iptvsmarterstvbox`
Version: `2.2.2 (67)`

Appname: `مدير الجهاز`
Packagename: `com.android.managedprovisioning`
Version: `5.1.1-5.0.8 (22)`

Appname: `KLauncher`
Packagename: `com.ktc.launcher`
Version: `1.0 (1)`

### Current owners
Appname: `‏نظام TV`
Packagename: `android`
Version: `5.1.1-5.0.8 (22)`

Appname: `التنزيلات`
Packagename: `com.android.providers.downloads.ui`
Version: `5.1.1-5.0.8 (22)`

Appname: `إدارة التنزيل`
Packagename: `com.android.providers.downloads`
Version: `5.1.1-5.0.8 (22)`

### SD Maid
Version: `4.15.7 (41507)`

### Device
Fingerprint: `TOSHIBA/aosp_toshiba/toshiba:5.1.1/LMY47V/5.0.8:userdebug/test-keys`

**Comment by ballack2110400030697** [comment]
> ### Target
> Target: `/mnt/sdcard/Download/IPTV Smarters Pro(com.nst.iptvsmarterstvbox)-2.2.2(67)-base.apk` Prefix-free: `Download/IPTV Smarters Pro(com.nst.iptvsmarterstvbox)-2.2.2(67)-base.apk` Path-prefix: `/mnt/sdcard/` Type: `FILE` Location: `SDCARD` Current keeper state: `true` Suggested keeper state: `true`
> 
> ### Suggested owners
> Appname: `Android System WebView` Packagename: `com.android.webview` Version: `39 (5.0.8-arm64) (300002)`
> 
> Appname: `CaptivePortalLogin` Packagename: `com.android.captiveportallogin` Version: `5.1.1-5.0.8 (22)`
> 
> Appname: `IPTV Smarters Pro` Packagename: `com.nst.iptvsmarterstvbox` Version: `2.2.2 (67)`
> 
> Appname: `مدير الجهاز` Packagename: `com.android.managedprovisioning` Version: `5.1.1-5.0.8 (22)`
> 
> Appname: `KLauncher` Packagename: `com.ktc.launcher` Version: `1.0 (1)`
> 
> ### Current owners
> Appname: `‏نظام TV` Packagename: `android` Version: `5.1.1-5.0.8 (22)`
> 
> Appname: `التنزيلات` Packagename: `com.android.providers.downloads.ui` Version: `5.1.1-5.0.8 (22)`
> 
> Appname: `إدارة التنزيل` Packagename: `com.android.providers.downloads` Version: `5.1.1-5.0.8 (22)`
> 
> ### SD Maid
> Version: `4.15.7 (41507)`
> 
> ### Device
> Fingerprint: `TOSHIBA/aosp_toshiba/toshiba:5.1.1/LMY47V/5.0.8:userdebug/test-keys`

**Comment by Realstraitup** [comment]
Love Sonsssssssssssßssssssssssssssss9Everlating Life Full of HEALTH WEALTH AND FULFILLNESS.
