### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/WhatsApp(com.whatsapp)-2.20.97(453296)-base.apk (FP)

### ISSUE THREAD

**Issue by LeGros07122e** [d4rken/sdmaid-public#3381]
### Target
Target: `/storage/emulated/0/Download/WhatsApp(com.whatsapp)-2.20.97(453296)-base.apk`
Prefix-free: `Download/WhatsApp(com.whatsapp)-2.20.97(453296)-base.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `Système Android`~~
~~Packagename: `android`~~
~~Version: `10 (29)`~~

Appname: `Téléchargements`
Packagename: `com.android.providers.downloads.ui`
Version: `10 (29)`

Appname: `Gestionnaire de téléchargement`
Packagename: `com.android.providers.downloads`
Version: `10 (29)`

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `samsung/star2qltecs/star2qltecs:10/QP1A.190711.020/G965WVLU7DTB2:user/release-keys`

**Comment by LeGros07122e** [comment]
Really Sorry about that

**Comment by Vtmt0609** [comment]
[A_Day_in_the_Life_of_Your_Data (2).pdf](https://github.com/user-attachments/files/18090786/A_Day_in_the_Life_of_Your_Data.2.pdf)
