### ISSUE TITLE
Clutterreport: /storage/emulated/0/Pictures (FP)

### ISSUE THREAD

**Issue by enocck** [d4rken/sdmaid-public#3395]
### Target
Target: `/storage/emulated/0/Pictures`
Prefix-free: `Pictures`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Almacenamiento de medios`
Packagename: `com.android.providers.media`
Version: `7.0 (801)`

### Current owners
Appname: `Sistema Android`
Packagename: `android`
Version: `7.0 (24)`

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `motorola/panell_25_s/panell_s:7.0/NRD90M.05.039/039:user/release-keys`

**Comment by d4rken** [comment]
HM don't think the media provider owns this.
