### ISSUE TITLE
Feature Suggestion: Tinted NavigationBar Option

### ISSUE THREAD

**Issue by DJayM** [d4rken/sdmaid-public#340]
I love the new UI but i think the black navbar ruins the look of the app it just stands out to much i think it would be better grey like the background color or darker grey like the background on the items. I know google dev docs say it should always remain black so thats why i suggested this as a option^ cheers.

![screenshot_20160401-023216](https://cloud.githubusercontent.com/assets/18201610/14195548/6ecd849e-f7b2-11e5-87a2-32af9dfab8ac.png)

**Comment by d4rken** [comment]
It's not actually black. The bottom bar with "JAY" on your screenshot is black.
The statusbar on all 5.0+ devices is a semi transparent bar with colorcode `#191919`.
If you open the navigation drawer (which should slide below the statusbar) you might see it.

So you would petition for a lighter color?
Currently we have, but I'm open for suggestions.
* Statusbar `#191919`
* Foreground `#303030`
* Background `#424242`

**Comment by DJayM** [comment]
yeah im talking about the bar with my name on it, its pure black i know the status bars transparent that looks cool i like that it matches the rest of the UI. Let me make sum mock ups with the colors you mentioned and il pick one. cheers.

**Comment by d4rken** [comment]
Ah I totally missread your post, you wrote "NavigationBar" but I read "StatusBar", yeah the navigationbar is completely black. I know that it can at least be made transparent. The difficult thing will probably be the different android versions, will have to look into that.

Looking forward to your mockups.

**Comment by DJayM** [comment]
![background](https://cloud.githubusercontent.com/assets/18201610/14197083/98af69ac-f7c2-11e5-992a-f77c024c2b51.png)
![black](https://cloud.githubusercontent.com/assets/18201610/14197085/98b0d4ea-f7c2-11e5-9b5a-d0935a596416.png)
![forground](https://cloud.githubusercontent.com/assets/18201610/14197084/98af7294-f7c2-11e5-9a6c-e473f64a5396.png)
![statusbar](https://cloud.githubusercontent.com/assets/18201610/14197086/98b29118-f7c2-11e5-9b7b-92998fbeb8fc.png)

i think the background one looks the best with statusbar coming in at 2nd place, yeah i think you might be right about android versions being a problem because i only have 3 apps that tint the navbar Solid Explorer,Phonograph and Lightning Launcher and in all of them its optional.

**Comment by bgiesing** [comment]
I personally think it should be kept the way it is and not add an option just for the sake of adding it as it might complicate the code just for a color change.

If you do it though, I think it should inherit the color above it (so basically extend the color below a transparent bar). This way the Green scan button would make the navbar green while other pages would be the light gray background color.

**Comment by d4rken** [comment]
I think this is something better suited for a future major release where we drop older Android versions.
