### ISSUE TITLE
Files from recycle bins are being deleted, even if corresponding checkbox is unticked

### ISSUE THREAD

**Issue by megapro17** [d4rken/sdmaid-public#3404]
It is a stock gallery app from Samsung firmware, it have support for offline recycle bin

![Screenshot_20200324-025758_SD Maid](https://user-images.githubusercontent.com/16743370/78614938-b79ab700-7878-11ea-9ab7-58b04fe8c0a7.jpg)
![Screenshot_20200324-030037_SD Maid](https://user-images.githubusercontent.com/16743370/78614964-d00ad180-7878-11ea-8c58-e3d9b13c4dc3.jpg)

**Comment by megapro17** [comment]
this issue was mentioned before, but author not provided a path to files https://github.com/d4rken/sdmaid-public/issues/2401

**Comment by d4rken** [comment]
I see, there might be a definition that just includes this for "Hidden caches". I'll look into it, thanks for the ticket reference to #2401 and the screenshots.

If you have spare time, can you record a debug log of the AppCleaner scan that produced those screenshots?

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by megapro17** [comment]
Of course
[sdmaid_logfile_1586697868242.txt.zip](https://github.com/d4rken/sdmaid-public/files/4466407/sdmaid_logfile_1586697868242.txt.zip)

**Comment by d4rken** [comment]
Should be okay, thanks for the log.
