### ISSUE TITLE
Bug: Default caches doesn't clear actual app cache

### ISSUE THREAD

**Issue by Rohan-B-97** [d4rken/sdmaid-public#3408]
### What happened?
Use app cleaner and it didn't clean app cache which i then manually did by going to app info and then storage

### What did you expect to happen?
It should clear app cache from the storage section

### How can I reproduce the issue?
Just scan and clean using app cleaner

### Comments
It should clear app cache from the storage section
### SD Maid
Version: `4.15.8 (41508)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2002220019:user/release-keys`

**Comment by d4rken** [comment]
Are you using the accessbility option?

https://github.com/d4rken/sdmaid-public/wiki/AppCleaner

**Comment by Rohan-B-97** [comment]
You were right I hadn't enabled it. Just did that and it works like a charm!
