### ISSUE TITLE
[request] Make the app open source

### ISSUE THREAD

**Issue by etmatrix** [d4rken/sdmaid-public#3423]
I'm glad one day to see this app become open source.
There are some apps open source , with apk pro version sold on play store.
Your app tried to become root in my device, but I give root access only to open source apps.

**Comment by d4rken** [comment]
I understand your concerns and agree that it's a sane approach to root apps.

I'd like to open-source it too, at some point, currently I see more drawbacks than benefits though.

So for now you'll have to either trust me or use SD Maid without root.

Stay healthy!
