### ISSUE TITLE
Clutterreport: /storage/emulated/legacy/Download/Adobe Acrobat (FP)

### ISSUE THREAD

**Issue by joshwiker14** [d4rken/sdmaid-public#3435]
### Target
Target: `/storage/emulated/legacy/Download/Adobe Acrobat`
Prefix-free: `Download/Adobe Acrobat`
Path-prefix: `/storage/emulated/legacy/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Adobe Acrobat`
Packagename: `com.adobe.reader`
Version: `20.3.0.12688 (1920312688)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `5.0.1-I337UCSGOK3 (21)`

Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `5.0.1-I337UCSGOK3 (21)`

Appname: `Download manager`
Packagename: `com.android.providers.downloads`
Version: `5.0.1-I337UCSGOK3 (21)`

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `samsung/jflteuc/jflteatt:5.0.1/LRX22C/I337UCSGOK3:user/release-keys`

**Comment by d4rken** [comment]
What's inside the folder?

**Comment by joshwiker14** [comment]
It holds the pdfs that were saved by adobe acrobat, so should be a desireable remnant. I must have missed the desireable remnant checkbox when making the report.
