### ISSUE TITLE
Database - Pro version 4.x beta

### ISSUE THREAD

**Issue by radhx** [d4rken/sdmaid-public#344]
Database comparing is taking too long compared to the previous version and heats up the handset considerably. Also, Compacting process returns to Comparing and hangs after completing about 90-95%. 
HTC Sensation XE Z715e, unlocked, rooted, custom rom, JellyBean 4.1.2, + xposed + Mount2SD.

**Comment by d4rken** [comment]
By previous version you mean SD Maid v3, and by current you mean v4.1.2?

Comparing takes longer because SD Maid v4 now checks ~50% more databases.

Regarding the hang, please provide me with a debug run log of when it hangs:
https://bugsnag.com/darken-development/sd-maid/errors

**Comment by d4rken** [comment]
Had an email conversation with the user.
Quoting it here for future reference

> So the good news is that SD Maid is not hanging!
> The bad news is, something weird is going on with your contacts app.
> 
> SD Maid seems to hang because it is overwhelmed with work.
> In side the folder "/data/user/0/com.android.providers.contacts/databases/" SD Maid has found ~33000 files like "contacts2.db-mjE5562B9E4" which all meet SD Maids criterium that they MIGHT be a database.
> Checking if they actually are databases is what is taking so long.
> 
> Let's do two things here:
> You check why there are so many files like that in the folder.
> **I will implement a stricter filter for the next update that sorts these out early on.**
> **Most of the files are only 75 Byte, so i will filter out too small files because they can't be databases.**

Second convo

> Very few (1 in bunch of 25-30 files) are with today's date 04/04/2016 with size 1.00 KB.
> All other are dated 05/01/2016 with size 75.00 B.
> (snapshot attached.)
> 
> Looks like temporary files resulting from some kind of a crash as my 4 year old HTC Sensation XE crashes once in a while.
> 
> There is one folder named "Corrupted" containing 10 sub-folders named "01" to "09".
> Each contains a copy of contacts2.db and contacts2.db-journal.
> These 2 files in each sub-folder are again dated 05/01/2016.
> 
> Four other files which look good are -
> 1] contacts2.db 4.96 MB
> 2] contacts2.db-journal 0.00 B
> 3] profile.db 480.00 KB
> 4] profile.db-journal 20.54 KB
> with today's date 04/04/2016.

![screenshot_2016-04-04-20-55-48 1](https://cloud.githubusercontent.com/assets/1439229/14255504/9647c856-fa94-11e5-8aff-d48f5624079f.png)
![screenshot_2016-04-04-20-36-37 1](https://cloud.githubusercontent.com/assets/1439229/14255505/966fd31e-fa94-11e5-9893-da7800525d3e.png)

**Comment by d4rken** [comment]
Size of >= 1024Byte is committed, will be in the next update.
