### ISSUE TITLE
Clutterreport: /storage/sdcard0/.MPA/MPA.info (new)

### ISSUE THREAD

**Issue by zubiii20** [d4rken/sdmaid-public#3445]
### Target
Target: `/storage/sdcard0/.MPA/MPA.info`
Prefix-free: `.MPA/MPA.info`
Path-prefix: `/storage/sdcard0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `AutoMMI`
Packagename: `com.gionee.autommi`
Version: `1.0 (1)`

### Current owners
None

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `KAZAM/Tornado_348/Tornado_348:4.4.2/KOT49H/1412085373:user/release-keys`

**Comment by d4rken** [comment]
What kind of data is this?
