### ISSUE TITLE
Setup for external SD card fails

### ISSUE THREAD

**Issue by moonryder** [d4rken/sdmaid-public#345]
After starting SDMaid there is a popup window to setup SDMaid.
A new window appears: "An additonal storage has been found....
Clicking on the button to grant access (for external SDcard - but nothing happens).
The only way to go further is to skíp this step.

Really weird (cuz this popup window appears on every start of SDMaid

**Comment by d4rken** [comment]
You should see the system documents app.
There is more info here and some screenshots of how it should look:
https://github.com/d4rken/sdmaid-public/wiki/Setup

Please supply some more information:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug

**Comment by d4rken** [comment]
Best guess so far:
For some reason the ROM does not have the documents app (package: com.android.documentsui) installed. It should be a preinstalled system app on all 5.0+ devices.

It's the app that answers the intent `Intent.ACTION_OPEN_DOCUMENT_TREE` if there is no system app to react to this intent then SD Maid (or any other app) will not be able to gain storage access on the device.

**Comment by d4rken** [comment]
> http://stackoverflow.com/questions/34021039/action-open-document-not-working-on-miui

Case where Xiaomi screwed up and didn't include the system app ("xiaomi mi4c with miui 7 based on android 5.1.1")

**Comment by d4rken** [comment]
It's also possible that the app is installed by has been frozen or otherwise deactivated.
In any case I can not fix this type issue as it's a ROM issue.

I'm closing the ticket, if you feel my understanding of the issue was wrong please reopen the ticket.
