### ISSUE TITLE
Smaller folder row

### ISSUE THREAD

**Issue by aristo28** [d4rken/sdmaid-public#346]
Could you shrink the folder icon row? so i can see more folder rows without too much scrolling.

I know this is against the Google guidelines, but would be pleased if you take this into consideration. Thank you! ^^

**Comment by d4rken** [comment]
Hm, I isn't it a bit crowded then?

![2016-04-10 23 25 02](https://cloud.githubusercontent.com/assets/1439229/14413850/935cae3a-ff86-11e5-9716-a828e76e7968.png)

**Comment by d4rken** [comment]
Done
