### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM/Auto Photo Cut Paste/.temp (FP)

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3460]
### Target
Target: `/storage/emulated/0/DCIM/Auto Photo Cut Paste/.temp`
Prefix-free: `DCIM/Auto Photo Cut Paste/.temp`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Auto Photo Cut Paste`
Packagename: `com.morningshine.autocutpaste`
Version: `2.4 (18)`

### Current owners
~~Appname: `Система Flyme`~~
~~Packagename: `android`~~
~~Version: `8.1.0 (27)`~~

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by Ingood5** [comment]
Заметил ошибку SD Maid. Папка очищается как кэш. Но если удалить приложение, папка помечается как keeper и уже не удаляется. 

По поводу самой папки, ее можно считать не keeper, здесь временные файлы, которые не используются после окончания работы.

**Comment by d4rken** [comment]
The parent directory `DCIM/Auto Photo Cut Paste` is marked as keeper. 
It's not possible to remove only subfolders on uninstall for a specific app.

**Comment by Ingood5** [comment]
Возможно, я что-либо не понял. Эта папка #3278 очищается как кэш, но если кэш не очистить и удалить приложение, то SD Maid все равно удалит ее при следующей очистке. С Auto Photo Cut Paste / .temp это не работает, то есть SD Maid удаляет ее как кэш, но если кэш не очистить и удалить приложение, то SD Maid ее уже не удалит.

**Comment by d4rken** [comment]
The cache clearing behavior should have no impact on whether it's detected as corpse.

Can you show me a video? Is it possible that it's related to #3879 ?

**Comment by Ingood5** [comment]
Это не связано. Файл остаётся как keeper даже после перезагрузки, т.е. выглядит так же, как в конце видео.


[S00906-03484056.mp4.zip](https://github.com/d4rken/sdmaid-public/files/5178941/S00906-03484056.mp4.zip)

**Comment by d4rken** [comment]
Thank you!

This is related to #3520 
When you re-open SD Maid it's not a complete SD Maid (you can see the explorer is loaded).
If you force-stop SD Maid, the issue shouldn't appear.

Maybe it would be helpful to show additional information in the Explorer, about the corpsefinder and appcleaner icon :thinking:

**Comment by Ingood5** [comment]
> If you force-stop SD Maid, the issue shouldn't appear.

О какой именно проблеме речь? С данной папкой проблема, то что она успешно очищается как кэш, но после удаления приложения оказывается помеченной как keeper, хотя по логике если это кэш, то после удаления приложения он должен быть сразу удалён и не может помечаться как keeper. В этом вся проблема. После принудительной остановки SD Maid она не решается.

На видео я показал именно это, то есть что папка одновременно и кэш, и keeper (противоречие):

![S00907-04005771](https://user-images.githubusercontent.com/60130882/92339832-b63c1780-f0c0-11ea-948f-baf5ea8172db.jpg)


Проблема #3879 попала на видео случайно 😀

> Maybe it would be helpful to show additional information in the Explorer, about the corpsefinder and appcleaner icon 

Вы о скриншоте выше? Или нужна другая информация?

**Comment by d4rken** [comment]
> What problem are you talking about? The problem with this folder is that it is successfully cleared as a cache, but after deleting the application it turns out to be marked as keeper, although logically if it is a cache, then after removing the application it should be immediately deleted and cannot be marked as keeper. This is the whole problem. After forcibly stopping SD Maid, it is not resolved.

https://github.com/d4rken/sdmaid-public/issues/3460#issuecomment-683430305

SD Maid can not remove just subfolders when an app is uninstalled and we don't want to remove `DCIM/Auto Photo Cut Paste`.

**Comment by Ingood5** [comment]
Вы мне отвечали (#3401):

>The CorpseFinder doesn't support removing only parts of the files.
We need to add the parent folder (this) as keeper, and then create an extra ticket to add the files that can be deleted to the AppCleaner.
So it's better to make different tickets for that, one for the folder<>pkg relation (this ticket), and then we make another one about the files can cleaned.

То есть после удаления приложения подпапку можно удалить, только если она является кэшем?

**Comment by d4rken** [comment]
The CorpseFinder can only make decision on complete folders. Either the whole folder is removed or nothing.

**Comment by Ingood5** [comment]
Прошу прощения, я напутал. Я выше писал, что папка RemoveObjects/.temp (#3278) является кэшем и в отличие от Auto Photo Cut Paste/.temp очищается даже после удаления приложения. Я думал так должно быть. Оказалось, что RemoveObjects по ошибке помечена как не keeper, поэтому папка .temp тоже удаляется. Нужно RemoveObjects сделать не keeper, я об этом написал здесь – #3278. 

Тогда остаётся  вопрос, можно ли сделать, чтобы AppCleaner очищал кэш приложения, если приложение уже удалено? Кэш все равно остаётся помеченным AppCleaner, но не удаляется. У некоторых приложений большие кэши, и неопытный пользователь, который не пользуется включением удаления нужных остатков в настройках, так этот кэш и не удалит.

**Comment by d4rken** [comment]
> Тогда остаётся вопрос, можно ли сделать, чтобы AppCleaner очищал кэш приложения, если приложение уже удалено? Кэш все равно остаётся помеченным AppCleaner, но не удаляется. У некоторых приложений большие кэши, и неопытный пользователь, который не пользуется включением удаления нужных остатков в настройках, так этот кэш и не удалит.

That's not possible, the AppCleaner can only work with installed packages, it's a core part of it's logic :frowning:

**Comment by Ingood5** [comment]
> Thank you!
> This is related to #3520
> When you re-open SD Maid it's not a complete SD Maid (you can see the explorer is loaded).
> If you force-stop SD Maid, the issue shouldn't appear.
> Maybe it would be helpful to show additional information in the Explorer, about the corpsefinder and appcleaner icon

Т.к. я ошибся, уточните о какой проблеме вы здесь говорите? Я думал, что папка с кэшем помечена как keeper по ошибке, и с самого начала я писал именно об этой ошибке.

**Comment by d4rken** [comment]
I'm now also confused :dizzy_face: .

Which question is still unanswered now?

**Comment by Ingood5** [comment]
Если никакими способами невозможно удалить папку с кэшем приложения, после того как само приложения удалено (не считая очистки с включённым пунктом keeper), то на счёт этого вопросов нет.

Тогда вопрос остаётся только этот: 

> Thank you!
This is related to #3520
When you re-open SD Maid it's not a complete SD Maid (you can see the explorer is loaded).
If you force-stop SD Maid, the issue shouldn't appear.
Maybe it would be helpful to show additional information in the Explorer, about the corpsefinder and appcleaner icon

Как я понял, здесь вы обнаружили какую-то ошибку вместо моей. Можете описать какую именно? 

Вот нужные вам скриншоты:


![S01005-14382020](https://user-images.githubusercontent.com/60130882/95075342-adb71b00-0718-11eb-97b9-e025b49cc78f.png)
![S01005-14382541](https://user-images.githubusercontent.com/60130882/95075345-aee84800-0718-11eb-9945-239920c50e9e.png)

**Comment by d4rken** [comment]
Is the application still installed?

**Comment by Ingood5** [comment]
Приложение удалено.

**Comment by d4rken** [comment]
There currently no more information needed.
The remaining issue visible on the screen is the showing the "appcleaner" icon for an uninstalled app, to fix this, I need to fix/implement this: https://github.com/d4rken/sdmaid-public/issues/3879

Thanks for all the detailed posts!
