### ISSUE TITLE
More compact UI in AppControl

### ISSUE THREAD

**Issue by TWiStErRob** [d4rken/sdmaid-public#347]
Most of the applications are not "Running" or "Autostart" so their sizes would fit nicely in the right column, which would in turn make the list item height smaller.

**Comment by d4rken** [comment]
True but then the list item heights are not all the same, which would look weird, wouldn't it?

**Comment by TWiStErRob** [comment]
I don't think that would be a problem, in v4 try to hide the label container if there are no labels (running/boot). Because items with labels are significantly less in count it shouldn't be strange.

Currently v4 displays 5 apps (v3 displayed 9) in that list and it looks like another 5 would snuggly fit into those margin gaps. Note that I'm using compact view in GMail too, not comfortable: I'm information-centric and huge padding is distracting and forces me to scroll twice as much. This is a trend nowadays the screens are getting bigger and the margins are getting bigger, instead of displaying more information...

**Comment by d4rken** [comment]
I was working close to the material design guidelines, which is were I sourced the margins/padding and the aversion to non uniform list item heights. I'll try it in a future beta version, though I must say that I'm a fan of uniform item heights.

**Comment by TWiStErRob** [comment]
I think uniform item height only makes sense if the items are of the same type, which we could argue that the ones with label (special) are different than the ones without (general).

I know material design like huge margins, and I agree it looks more pleasing, but at some point it starts to become counterproductive: I don't use my phone because it's nice to look at, it's a productivity tool.

In the end it's your app, this is just one feedback of many.

**Comment by d4rken** [comment]
v4.3.0
