### ISSUE TITLE
Clutterreport: /storage/emulated/0/ShrtcutCustomizer (new)

### ISSUE THREAD

**Issue by rgaskill6** [d4rken/sdmaid-public#3475]
### Target
Target: `/storage/emulated/0/ShrtcutCustomizer`
Prefix-free: `ShrtcutCustomizer`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Shortcut Creator`
Packagename: `com.alextern.shortcuthelper`
Version: `3.1.4 (56)`

### Current owners
None

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `samsung/j3popltetfnvzw/j3popltetfnvzw:6.0.1/MMB29M/S327VLUDS4ARF2:user/release-keys`

**Comment by d4rken** [comment]
Hm? This looks valid
