### ISSUE TITLE
Clutterreport: /storage/emulated/0/.um (new)

### ISSUE THREAD

**Issue by aces7878** [d4rken/sdmaid-public#3476]
`###` Target
Target: `/storage/emulated/0/.um`
Prefix-free: `.um`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `samsung/a20psq/a20p:9/PPR1.180610.011/A205USQU4ATA5:user/release-keys`

### Comment
`this is a virus I can't get rid of and goes undetected`
@d4rken

**Comment by d4rken** [comment]
SD Maid isn't an anti-malware tool.

If SD Maid fails to delete a file unexpectedly, provide a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by aces7878** [comment]
sorry, thought that was going on github. im aware of that.
