### ISSUE TITLE
AppControl Overflow menu becomes unresponsive

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3477]
Meizu M8
Android: 8.1.0
No root
SD Maid v4.15.8, Unlocker v4.4.1
install ID:
752f3a56-3ca9-487f-b99f-8576e5af9fc2

Если выполнить последовательность действий: открыть менеджер приложений, нажать кнопку "обновить", ввести текст в поле поиска, зайти в любое найденное приложение, и затем нажать на кнопку "назад", чтобы вернуться к списку приложений — то кнопка в виде трёх точек в верхнем правом углу работать не будет. Это происходит каждый раз, даже если я только что открыл SD Maid. SD Maid переустанавливал.

[sdmaid_logfile_1588486631013.txt.zip](https://github.com/d4rken/sdmaid-public/files/4569714/sdmaid_logfile_1588486631013.txt.zip)

**Comment by d4rken** [comment]
I tried it, but couldn't reproduce it.

Can you show me a video of it happening?

**Comment by programmist87** [comment]
[video.mp4.zip](https://github.com/d4rken/sdmaid-public/files/4625244/video.mp4.zip)

**Comment by d4rken** [comment]
I can reproduce it now, the issue was that I need to press `X` two times to dismiss the input field and then it doesn't work.
