### ISSUE TITLE
What does the red SD Maid icon mean?

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3479]
Добрый день. Что означает значок SD Maid красного цвета в проводнике? В справке для SD Maid это не написано.

![S00503-131959(1)](https://user-images.githubusercontent.com/60130882/80911807-5cf25f00-8d41-11ea-99b2-42503d1d9213.png)

**Comment by d4rken** [comment]
It's this:
https://github.com/d4rken/sdmaid-public/wiki/Explorer#common

The color is wrong. I'll fix it.

It's an item that SD Maid thinks is a corpse, but the name is too common, so it's too dangerous for SD Maid to suggest it for deletion.
