### ISSUE TITLE
Clutterreport: /storage/emulated/0/Photo Editor/.bg (new)

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3482]
### Target
Target: `/storage/emulated/0/Photo Editor/.bg`
Prefix-free: `Photo Editor/.bg`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Polish`
Packagename: `photo.editor.photoeditor.photoeditorpro`
Version: `1.261.62 (20062)`

### Current owners
None

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by d4rken** [comment]
What kind of data does this contain?

**Comment by programmist87** [comment]
Это фоны для коллажей из фото. Они автоматически загружаются приложением из интернета при выборе в нём нужного фона.

**Comment by d4rken** [comment]
I'll add it as "hidden cache" okay?

**Comment by programmist87** [comment]
Хорошо, это кэш.
