### ISSUE TITLE
Clutterreport: /storage/emulated/0/Photo Editor/.mosaic (new)

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3486]
### Target
Target: `/storage/emulated/0/Photo Editor/.mosaic`
Prefix-free: `Photo Editor/.mosaic`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Polish`
Packagename: `photo.editor.photoeditor.photoeditorpro`
Version: `1.261.62 (20062)`

### Current owners
None

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by d4rken** [comment]
What kind of data does this contain?

**Comment by programmist87** [comment]
Это шаблоны для кисти. После удаления приложения они не нужны.

**Comment by d4rken** [comment]
Also hidden cache? Or "offline files"?

**Comment by programmist87** [comment]
Хорошо, это кэш.

**Comment by maggymayandme** [comment]
Please unsubscribe me from github. Emails are overwhelming my inbox. 30-50
a day, a bit too much.
Thank you.

**Comment by programmist87** [comment]
Yes, hidden cache.
