### ISSUE TITLE
Clutterreport: /storage/emulated/0/Photo Editor/.neon (new)

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3487]
### Target
Target: `/storage/emulated/0/Photo Editor/.neon`
Prefix-free: `Photo Editor/.neon`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Polish`
Packagename: `photo.editor.photoeditor.photoeditorpro`
Version: `1.261.62 (20062)`

### Current owners
None

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by d4rken** [comment]
What's this?

**Comment by programmist87** [comment]
These are graphic effects. After uninstalling the application, they are not needed.

**Comment by d4rken** [comment]
What about before? Hidden cache? Offline files?

**Comment by programmist87** [comment]
Хорошо, это кэш.
