### ISSUE TITLE
Clutterreport: /storage/emulated/0/Photo Editor/.sticker (new)

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3488]
### Target
Target: `/storage/emulated/0/Photo Editor/.sticker`
Prefix-free: `Photo Editor/.sticker`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Polish`
Packagename: `photo.editor.photoeditor.photoeditorpro`
Version: `1.261.62 (20062)`

### Current owners
None

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by d4rken** [comment]
Is this cache?

If this is not cache, then #3489 is enough to add definition for `Photo Editor`.

**Comment by programmist87** [comment]
Это стикеры, загружаются в процессе работы приложения. После удаления приложения их нужно удалить.

**Comment by d4rken** [comment]
It's not possible to set different "KEEPER" states on subfolders.

A clutter report is always for the top-level directory of a folder. If the folder contains any items that should not be removed automatically by the corpsefinder, then the top-level folder has to be marked as "keeper".

If the top-level folder contains items that can be deleted, then these need to be handled through the AppCleaner.

The usual pattern would be:
* Report top level folder, and mark as "KEEPER" if any subfolders should be kept
* Create a ticket for any subfolders that can be deleted via AppCleaner

In the future we can use this to execute the AppCleaner on apps that are uninstalled.

**Comment by programmist87** [comment]
В родительской папке сохраняются фотографии. У них нет внутри отдельной папки и сохраняются прямо в родительской. Я пометил родительскую папку как keeper, а после этого я отдельно пометил все папки внутри нее, которые нужно удалить (no keeper), чтобы в результате сохранились нужные фотографии. Что именно неправильно?

**Comment by d4rken** [comment]
> Что именно неправильно?

Nothing wrong. You did good :ok_hand: 

The parent folder was correctly reported.
In the future, for the other reports just mention in the comment, example:
"Add to AppCleaner, hidden cache/offline files/recyclebin ..." :grin: 

Stay healthy :heart: !

**Comment by d4rken** [comment]
Should this `.sticker` folder be deleted when cleaning caches, like the others?

**Comment by programmist87** [comment]
> Should this `.sticker` folder be deleted when cleaning caches, like the others?

Да

> "Add to AppCleaner, hidden cache/offline files/recyclebin ..." 


То есть варианты:

"Add to AppCleaner, hidden cache"

или

"Offline files"

или

"recyclebin" 

Правильно?

**Comment by d4rken** [comment]
Which type of cache is it?

https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#filter

**Comment by programmist87** [comment]
Это Hidden cache.
