### ISSUE TITLE
Clutterreport: /storage/emulated/0/Photo Editor/.tattooTemp (new)

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3489]
### Target
Target: `/storage/emulated/0/Photo Editor/.tattooTemp`
Prefix-free: `Photo Editor/.tattooTemp`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Polish`
Packagename: `photo.editor.photoeditor.photoeditorpro`
Version: `1.261.62 (20062)`

### Current owners
None

### SD Maid
Version: `4.15.9 (41509)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by d4rken** [comment]
Parent folder needs to be marked as keeper, see #3489

**Comment by programmist87** [comment]
Я помечал.

https://github.com/d4rken/sdmaid-public/issues/3481

Что-либо неправильно?

**Comment by d4rken** [comment]
It was just a reminder for myself.

#3489 is for the clutter database + corpsefinder.

I will use this ticket for add it to the AppCleaner (hidden caches filter).
