### ISSUE TITLE
Sidebar scroll jumping when scan active

### ISSUE THREAD

**Issue by chidi9901** [d4rken/sdmaid-public#349]
I noticed when I,for example, start scanning in the system cleaning section and at the same time I want to scroll down in the sidebar, it automatically jumps up a bit. This results in the situation where I can not properly access the categories that are down below because the sidebar always jumps up.
I have only noticed this on my Xperia Z3 Tablet Compact (running Android 5.1.1) in landscape mode. On portrait mode it doesn't happen.

**Comment by d4rken** [comment]
Could you somehow get me a video of that?

**Comment by chidi9901** [comment]
Sorry for the late reply, here is a video: https://drive.google.com/file/d/1CQZsCM3K7q4_zpDQ2IxM5fSQda-3_HpnkQ/view?usp=sharing
By the way my tablet is also rooted.

**Comment by d4rken** [comment]
Thanks. I don't think I will be able to fix this. It doesn't seem to be an SD Maid issue, but a ROM/hardware related.
See here:
https://www.google.de/search?q=Xperia+Z3+Tablet+Compact+recyclerview+scroll+jumps
Also this example which demonstrates the same effect:
https://www.youtube.com/watch?v=B60caaAbz4M

Do you agree?

**Comment by chidi9901** [comment]
Ok, it might be a firmware/ROM issue. It's not a big problem anyways. It only happens with scanning System Cleaner, so I tried this on another tablet (Android 6.0.1) and I couldn't replicate the problem. The app must be fine.
