### ISSUE TITLE
Make cleaning "frequents" in the SMS/MMS application

### ISSUE THREAD

**Issue by igordrozdov** [d4rken/sdmaid-public#350]
![screenshoot_05 04 2016_11 05 49](https://cloud.githubusercontent.com/assets/10287269/14275359/814c33e8-fb1f-11e5-9b8e-20c2bd782051.jpg)

**Comment by d4rken** [comment]
Please provide more details about your device, the app and what you want SD Maid to clean.
I need file paths and packagename of the app.
