### ISSUE TITLE
Missing skip secondary storage option

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#352]
If the Documents app is empty, you can't choose a wrong entry and the "Don't show again" option for the secondary storage setup never shows up.

**Comment by d4rken** [comment]
![](https://cloud.githubusercontent.com/assets/1439229/14256420/51aa30f8-fa99-11e5-9853-5d6b41e4cbbc.png)

**Comment by d4rken** [comment]
Will be fixed in 4.1.4 later today.

**Comment by 21101969sanjay** [comment]
Not working properly with mi max 2
