### ISSUE TITLE
Prevent deletion of Signal backups

### ISSUE THREAD

**Issue by breversa** [d4rken/sdmaid-public#3524]
Hello !

For the nth time, SD Maid has deleted my backups of Signal (www.signal.org) that were both in the internal storage and external SD card, while I had Signal uninstalled : I was in the process of making the cleanest state possible before reinstalling (to troubleshoot a very obscure bug), but wasn't expecting SD Maid to delete the backup files (my bad, it seems I never learn) !

I'm pretty heavy-handed with the System Cleaner options, but I don't see any toggle that could explain why those files got deleted, except "Misc. files".

The files I'm talking about were located in directories named "Signal", sitting both at the root of my internal storage and external SD card, organized as such :

- `/Signal/`
- `/Signal/Backups/`
- `/Signal/Backups/signal-YYYY-MM-DD-hh-mm-ss.backup` (there were several of them)
- `/Signal/`[at least one other file]

I'm wondering :
1- Why did SD Maid think it was sound to delete those files (not judging here ; I'm curious about the criterias) ?
2- Is there a way to prevent the deletion of those files ?

**Comment by d4rken** [comment]
If you uninstall the app `org.thoughtcrime.securesms` and have the CorpseFinder option "Show desirable remnants" enabled, then the CorpseFinder will delete it.

The CorpseFinder can be triggered manually by you, by the UninstallWatcher option (if enabled) or the scheduler.

You can prevent deletion by creating an exclusion:
https://github.com/d4rken/sdmaid-public/wiki/Exclusions

The statistics section should also show that the folder was deleted by the CorpseFinder tool, if you want to verify it.

**Comment by breversa** [comment]
> If you uninstall the app `org.thoughtcrime.securesms` and have the CorpseFinder option "Show desirable remnants" enabled, then the CorpseFinder will delete it.

> This totally answers my question. Thank you !
