### ISSUE TITLE
Can I transfer SD Maid settings?

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3538]
Возможно как-то переносить настройки SD Maid, чтобы мне не нужно было их заново настраивать? Может быть, через копирование файла настроек или как-либо ещё.

**Comment by azlanzakaria** [comment]
> Возможно как-то переносить настройки SD Maid, чтобы мне не нужно было их заново настраивать? Может быть, через копирование файла настроек или как-либо ещё.

**Comment by azlanzakaria** [comment]
https://github.com/d4rken/sdmaid-public/issues/3538#issue-618256818

**Comment by d4rken** [comment]
There is no official way to do this but you could copy the private data folder if you have root:
`/data/data/eu.thedarken.sdm/files`.

This only works between same versions.

**Comment by d4rken** [comment]
Dup #599

**Comment by Ingood5** [comment]
Можно ли сделать, чтобы файл/файлы с настройками всегда находились в /storage/emulated/0/Android/data/eu.thedarken.sdm ? Тогда можно будет переносить настройки без Рут-доступа.

**Comment by d4rken** [comment]
> Is it possible to make the configuration file / files always be in /storage/emulated/0/Android/data/eu.thedarken.sdm? Then it will be possible to transfer the settings without Root access.

Technically yes, but I'm not sure if this is a good idea. Malicious apps could influence SD Maids behavior by editing the settings such that SD Maid accesses or deletes files that shouldn't be deleted.
