### ISSUE TITLE
Scheduler stops running app

### ISSUE THREAD

**Issue by Ezrway** [d4rken/sdmaid-public#3542]
What happened:
Scheduled app daily. Ran for a few days and then stopped working.

What did you expect to happen
Scheduler to run app every day at set time. 

Set scheduler to run daily and it should stop running app after a few days:

This has been happening for awhile.

**Comment by d4rken** [comment]
Please provide more details about SD Maid and your device.

Make sure you have disabled battery optimizations:
https://dontkillmyapp.com/

**Comment by Ezrway** [comment]
Sorry for the delay in my reply.

Thanks for the link you sent. It was helpful. I used the info there to
adjust the power settings. Now I'm monitoring the app.

My phone is a Samsung Galaxy S7 Edge running Android 8.0.0. What other
specs do you need?

**Comment by Ezrway** [comment]
Here is a screenshot showing SD MAID is off under "OPTIMIZE BATTERY USAGE",
"Apps not optimized".

This is the way settings were before I emailed you about the app not
running running under the Scheduler after a period of time.

---------- Forwarded message ---------
From: Andrew B <abeeler2489@gmail.com>
Date: Sat, May 23, 2020, 11:01 AM
Subject: Re: [d4rken/sdmaid-public] Scheduler stops running app (#3542)
To: d4rken/sdmaid-public <
reply@reply.github.com>


Sorry for the delay in my reply.

Thanks for the link you sent. It was helpful. I used the info there to
adjust the power settings. Now I'm monitoring the app.

My phone is a Samsung Galaxy S7 Edge running Android 8.0.0. What other
specs do you need?

**Comment by d4rken** [comment]
Is this still an issue?
