### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/contacts (1).csv (FP)

### ISSUE THREAD

**Issue by robertsimmons514** [d4rken/sdmaid-public#3544]
### Target
Target: `/storage/emulated/0/Download/contacts (1).csv`
Prefix-free: `Download/contacts (1).csv`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `3Fan`
Packagename: `com.dating.threefan`
Version: `1.0.4 (5)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `9 (28)`

Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `9 (28)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `9 (28)`

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `Coolpad/lithium/lithium:9/3705A.MPCS.200228.0D/farmlnj04-1402:user/release-keys`

**Comment by d4rken** [comment]
Is the a default file or something you specifically created, the path seems user picked?
