### ISSUE TITLE
App hangs after being granted root

### ISSUE THREAD

**Issue by Dave247** [d4rken/sdmaid-public#355]
My Device is a Samsung Galaxy Note Edge (SM-N915G) running stock 5.1.1, rooted with SuperSU 2.76 also with Busybox box 1.24.1, a custom kernel and Xposed v80 installed.
I have SD Main 4.1.3 Free Production branch installed.

I don't normally use the app that often as I don't have much need for it, but upon it updating to 4.1.3 today I have found that I am no longer able to start any of the scans as, after requesting and being granted root access it will simply stay stuck waiting in the queue. The settings menu will not open either and will just stay endlessly stay stuck on loading.

Attached is the debug log. 
[sdmaid_logfile_1459852389958.txt](https://github.com/d4rken/sdmaid-public/files/204291/sdmaid_logfile_1459852389958.txt)

**Comment by Dave247** [comment]
After going over the log file myself and noticing the mention of Busybox I managed to fix my own problem. I uninstalled Busybox which I had previous installed in /su/bin and instead installed it to /system/xbin and the app now works as intended.
The reason why I installed it in /su/bin/ was because originally Busybox Pro showed both /system/ directories as not able to calculate any free space.

**Comment by d4rken** [comment]
The perfect ticket, WITH LOG and then it solves itself :))! More of that please.

> SuperSU 2.76 
Isn't 2.71 the latest?

So there was no busybox at "/system/xbin/busybox" when the logfile was recorded?

**Comment by Dave247** [comment]
Whoops, sorry you're right I meant 2.67. Typed them around the wrong way.
As for Busybox, to my knowledge there wasn't or at least shouldn't have been. I guess there is a posability that there was the remnants of a past BusyBox installation there.

Every so often I wipe and install a new ROM onto my phone either to update to a new stock build or to try out a custom ROM or to just clean everything out, but I always make sure to wipe everything I can in the recovery before installing even if it's just a new updated stock ROM. I'm pretty sure the last time I installed BusyBox to /su/bin was also the last time I had re-flashed my device which is why I say there shouldn't have been anything there, though there could be something I'm simply not remembering as it has been a while since I did so.

**Comment by d4rken** [comment]
Thanks for the info.
In anycase, I want to improve upon this, v4.1.4 will also check `/system/bin/busybox` AFTER checking `/system/xbin/busybox` stopping with the first one that works correctly.

**Comment by Dave247** [comment]
I'm glad I could help while also being able to fix the issue myself so I didn't have to give you more work to do. ^_^

**Comment by Dave247** [comment]
I just wanted to add that I've since noticed that everytime I reboot my phone the Busybox app shows shows Busybox is not installed, and yet your app continues to work as normal. That along with a separate issue regarding a request for root from a app that shouldn't be asking, and testing on a separate rooted device doesn't ask leads me to believe that there is something wrong with my phone currently and I will have to wipe everything again for good measure.

**Comment by d4rken** [comment]
SD Maid has its own busybox, it can use a system one but only if the own one doesn't work.

**Comment by Dave247** [comment]
Fair enough. I suspect that's what it must be doing then as I tried running busybox in a terminal emulator as a test only for nothing to happen.
For now I'll just put up with it while waiting for the Marshmallow build to come out in my region until I reflash as Samsung have finally started their rollout for my device.
