### ISSUE TITLE
Crash on startup due to GPlay IAP services not allowing SD Maid to bind.

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#3559]
> build.board: shamu
build.bootloader: moto-apq8084-72.04
build.brand: google
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: shamu
build.display: QQ2A.200501.001.B2
build.fingerprint: google/shamu/shamu:7.1.1/N6F27M/4299435:user/release-keys
build.hardware: shamu
build.host: The-GodFather
build.id: QQ2A.200501.001.B2
build.manufacturer: motorola
build.model: Nexus 6
build.product: shamu
build.radio: unknown
build.serial: unknown
build.tags: release-keys
build.time: 1589701417000
build.type: user
build.user: jenkins
version.codename: REL
version.incremental: 23e5eda112
version.release: 10
version.sdk_int: 29

```java
05-23 15:05:36.697 E/AndroidRuntime(7554): FATAL EXCEPTION: RxCachedThreadScheduler-16
05-23 15:05:36.697 E/AndroidRuntime(7554): Process: eu.thedarken.sdm, PID: 7554
05-23 15:05:36.697 E/AndroidRuntime(7554): io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.functions.a$k.a(Functions.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.m.a(LambdaObserver.java:13)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$a.a(ObservableSubscribeOn.java:3)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at c0.f.a.a$d.a(ReplayingShare.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.n0$b.a(ObservableRefCount.java:4)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.m0$b.a(ObservablePublishAlt.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.b(ObservableFlatMap.java:8)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.g(ObservableFlatMap.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.f(ObservableFlatMap.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$a.a(ObservableFlatMap.java:28)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.k0$a.a(ObservableOnErrorNext.java:18)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.a.a(BasicFuseableObserver.java:9)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.a.a(BasicFuseableObserver.java:9)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.h$a.a(ObservableDoFinally.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.w0$b.e(ObservableSwitchMap.java:14)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.w0$b.a(ObservableSwitchMap.java:22)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at c0.f.a.a$d.a(ReplayingShare.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.n0$b.a(ObservableRefCount.java:4)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.m0$b.a(ObservablePublishAlt.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at a0.v.e0.a(ViewGroupUtilsApi14.java:128)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.o0$a$a.a(ObservableRetryWhen.java:6)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.b(ObservableFlatMap.java:8)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.g(ObservableFlatMap.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.f(ObservableFlatMap.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.a(ObservableFlatMap.java:67)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.z0$a.a(ObservableTakeWhile.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.z0$a.a(ObservableTakeWhile.java:12)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.subjects.b.a(PublishSubject.java:15)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.subjects.d.a(SerializedSubject.java:27)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.o0$a.a(ObservableRetryWhen.java:5)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.h$a.a(ObservableDoFinally.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$a.a(ObservableSubscribeOn.java:3)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.e$a.a(ObservableCreate.java:8)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.e.b(ObservableCreate.java:5)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.p.a(Observable.java:64)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$b.run(ObservableSubscribeOn.java:1)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.v$a.run(Scheduler.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.schedulers.l.run(ScheduledRunnable.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.schedulers.l.call(ScheduledRunnable.java:1)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.lang.Thread.run(Thread.java:919)
05-23 15:05:36.697 E/AndroidRuntime(7554): Caused by: io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
05-23 15:05:36.697 E/AndroidRuntime(7554): 	... 41 more
05-23 15:05:36.697 E/AndroidRuntime(7554): Caused by: io.reactivex.exceptions.CompositeException$a: Chain of Causes for CompositeException In Order Received =>
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.StrictModeHandler.getRootCause(StrictModeHandler.java:1)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.StrictModeHandler.getRootCause(StrictModeHandler.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.StrictModeHandler.isStrictModeThrowable(StrictModeHandler.java:1)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.ExceptionHandler.uncaughtException(ExceptionHandler.java:1)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at e.a.a.b.b.o.a(SDMDebug.kt:5)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.plugins.a.b(RxJavaPlugins.java:18)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.functions.a$k.a(Functions.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.m.a(LambdaObserver.java:13)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$a.a(ObservableSubscribeOn.java:3)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at c0.f.a.a$d.a(ReplayingShare.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.n0$b.a(ObservableRefCount.java:4)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.m0$b.a(ObservablePublishAlt.java:7)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.b(ObservableFlatMap.java:8)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.g(ObservableFlatMap.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.f(ObservableFlatMap.java:2)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$a.a(ObservableFlatMap.java:28)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	... 41 more
05-23 15:05:36.697 E/AndroidRuntime(7554): Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.billing.iab.InAppBillingService (has extras) }
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1740)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at android.app.ContextImpl.bindService(ContextImpl.java:1650)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at e.a.a.a.a.a.a.a$i.a(IAPRepo.kt:43)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.e.b(ObservableCreate.java:3)
05-23 15:05:36.697 E/AndroidRuntime(7554): 	... 10 more
```

**Comment by d4rken** [comment]
Unrelated?

* https://stackoverflow.com/questions/28177863/java-lang-nullpointerexception-at-iabhelper-startsetupiabhelper-java266/28177965?noredirect=1#comment44726861_28177965
* https://stackoverflow.com/questions/14309928/in-app-billing-issue-with-iabhelper/19880056#19880056

Possibly related?

* https://stackoverflow.com/questions/22806236/android-in-app-billing-securityexception-binder-invocation-to-an-incorrect-inte

None really match the exception here though and all of the above issues would trigger for every users, this seems to only trigger for a few.

**Comment by chiakeewang83** [comment]
> > build.board: shamu
> > build.bootloader: moto-apq8084-72.04
> > build.brand: google
> > build.cpu_abi: armeabi-v7a
> > build.cpu_abi2: armeabi
> > build.device: shamu
> > build.display: QQ2A.200501.001.B2
> > build.fingerprint: google/shamu/shamu:7.1.1/N6F27M/4299435:user/release-keys
> > build.hardware: shamu
> > build.host: The-GodFather
> > build.id: QQ2A.200501.001.B2
> > build.manufacturer: motorola
> > build.model: Nexus 6
> > build.product: shamu
> > build.radio: unknown
> > build.serial: unknown
> > build.tags: release-keys
> > build.time: 1589701417000
> > build.type: user
> > build.user: jenkins
> > version.codename: REL
> > version.incremental: 23e5eda112
> > version.release: 10
> > version.sdk_int: 29
> 
> ```java
> 05-23 15:05:36.697 E/AndroidRuntime(7554): FATAL EXCEPTION: RxCachedThreadScheduler-16
> 05-23 15:05:36.697 E/AndroidRuntime(7554): Process: eu.thedarken.sdm, PID: 7554
> 05-23 15:05:36.697 E/AndroidRuntime(7554): io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.functions.a$k.a(Functions.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.m.a(LambdaObserver.java:13)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$a.a(ObservableSubscribeOn.java:3)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at c0.f.a.a$d.a(ReplayingShare.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.n0$b.a(ObservableRefCount.java:4)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.m0$b.a(ObservablePublishAlt.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.b(ObservableFlatMap.java:8)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.g(ObservableFlatMap.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.f(ObservableFlatMap.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$a.a(ObservableFlatMap.java:28)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.k0$a.a(ObservableOnErrorNext.java:18)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.a.a(BasicFuseableObserver.java:9)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.a.a(BasicFuseableObserver.java:9)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.h$a.a(ObservableDoFinally.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.w0$b.e(ObservableSwitchMap.java:14)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.w0$b.a(ObservableSwitchMap.java:22)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at c0.f.a.a$d.a(ReplayingShare.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.n0$b.a(ObservableRefCount.java:4)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.m0$b.a(ObservablePublishAlt.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at a0.v.e0.a(ViewGroupUtilsApi14.java:128)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.o0$a$a.a(ObservableRetryWhen.java:6)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.b(ObservableFlatMap.java:8)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.g(ObservableFlatMap.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.f(ObservableFlatMap.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.a(ObservableFlatMap.java:67)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.z0$a.a(ObservableTakeWhile.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.z0$a.a(ObservableTakeWhile.java:12)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.subjects.b.a(PublishSubject.java:15)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.subjects.d.a(SerializedSubject.java:27)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.o0$a.a(ObservableRetryWhen.java:5)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.h$a.a(ObservableDoFinally.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$a.a(ObservableSubscribeOn.java:3)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.e$a.a(ObservableCreate.java:8)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.e.b(ObservableCreate.java:5)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.p.a(Observable.java:64)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$b.run(ObservableSubscribeOn.java:1)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.v$a.run(Scheduler.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.schedulers.l.run(ScheduledRunnable.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.schedulers.l.call(ScheduledRunnable.java:1)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.lang.Thread.run(Thread.java:919)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): Caused by: io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	... 41 more
> 05-23 15:05:36.697 E/AndroidRuntime(7554): Caused by: io.reactivex.exceptions.CompositeException$a: Chain of Causes for CompositeException In Order Received =>
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.StrictModeHandler.getRootCause(StrictModeHandler.java:1)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.StrictModeHandler.getRootCause(StrictModeHandler.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.StrictModeHandler.isStrictModeThrowable(StrictModeHandler.java:1)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at com.bugsnag.android.ExceptionHandler.uncaughtException(ExceptionHandler.java:1)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at e.a.a.b.b.o.a(SDMDebug.kt:5)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.plugins.a.b(RxJavaPlugins.java:18)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.functions.a$k.a(Functions.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.m.a(LambdaObserver.java:13)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.observers.k.a(DisposableLambdaObserver.java:12)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.v0$a.a(ObservableSubscribeOn.java:3)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at c0.f.a.a$d.a(ReplayingShare.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.n0$b.a(ObservableRefCount.java:4)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.m0$b.a(ObservablePublishAlt.java:7)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.i$a.a(ObservableDoOnEach.java:16)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.b(ObservableFlatMap.java:8)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.g(ObservableFlatMap.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$b.f(ObservableFlatMap.java:2)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.p$a.a(ObservableFlatMap.java:28)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	... 41 more
> 05-23 15:05:36.697 E/AndroidRuntime(7554): Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.billing.iab.InAppBillingService (has extras) }
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1740)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at android.app.ContextImpl.bindService(ContextImpl.java:1650)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at e.a.a.a.a.a.a.a$i.a(IAPRepo.kt:43)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	at io.reactivex.internal.operators.observable.e.b(ObservableCreate.java:3)
> 05-23 15:05:36.697 E/AndroidRuntime(7554): 	... 10 more
> ```

**Comment by d4rken** [comment]
While the underlying issue doesn't seem like something I can fix, I've added additional error handling such that SD Maid should no longer crash due to this system state.
