### ISSUE TITLE
Clutterreport: /storage/emulated/0/.huvle (new)

### ISSUE THREAD

**Issue by DWR64** [d4rken/sdmaid-public#3585]
### Target
Target: `/storage/emulated/0/.huvle`
Prefix-free: `.huvle`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `FOTO Gallery`
Packagename: `kr.co.ladybugs.fourto`
Version: `4.00.24 (124)`

### Current owners
None

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `samsung/gtaxlwifixx/gtaxlwifi:8.1.0/M1AJQ/T580UEU4CSC1:user/release-keys`

**Comment by d4rken** [comment]
What kind of files does this contain?

**Comment by DWR64** [comment]
Application - Foto
I do not know what files but I can positively identify the folder goes with
that app

**Comment by d4rken** [comment]
Ok, thanks!

**Comment by DWR64** [comment]
I have received your message. What can I help you with?
