### ISSUE TITLE
AppControl Bug

### ISSUE THREAD

**Issue by evilreiz** [d4rken/sdmaid-public#3588]
![Screenshot_20200610-045159](https://user-images.githubusercontent.com/66702067/84205114-a9fee900-aad6-11ea-8aa1-e84d8e1e83c7.png)

Hello there, SD Maid Team.

I really love the app, very helpful!  But, one of my favorites feature is now not working properly as before. It happened for quite a while already, and I always waiting it to be fixed, until I thought I should posted this so the Team gonna fix this really soon.

So, the problem is it won't showing/labelling apps as a "Running" app(s) except the SD Maid itself and only. Here in the picture I brought is an example of MX Player Pro in PiP mode, then I tried to scan with AppControl but it still won't labeled as a "Running" app.

So... yeah, I think that's it for now. Thank u for reading, and I hope it'll be fix rlly soon.
Stay safe, SD Maid Team.

**Comment by d4rken** [comment]
Long term issue, currently only works with root, there has been some discussion here about how to achieve similar operation without root:

https://github.com/d4rken/sdmaid-public/issues/946
(dup)

Still looking for ideas.
