### ISSUE TITLE
Use Mutative Design for some elements

### ISSUE THREAD

**Issue by bgiesing** [d4rken/sdmaid-public#359]
You talked before that you changed the FAB on QuickAccess to a bar because of user discovery. I propose you implement Mutative Design for the issue.

Mutive Design (aka Project Phoebe) by Liam Spradlin (of Android Police and Dadapixel) is a concept where apps adapt to their users in addition to screen sizes. One of those changes is in their app Serene (https://github.com/liamspradlin/Phoebe) where the FAB while morph into the bottom bar (like you switched to) with an animation if the user hasn't touched it a while after opening the app.

![image](https://cloud.githubusercontent.com/assets/7895463/14335708/031feb72-fc23-11e5-97c9-220abfee33c1.png)

[Liam says in the blog post for it](https://medium.com/project-phoebe/mutate-more-digging-deeper-into-ui-that-evolves-with-the-user-fc0e0d94b402#.wkjzr87l9):
> A simple example we’ve implemented in the app is the FAB for creating new notes. There’s data to show that floating action buttons — since the introduction of material design — have promoted and increased engagement with certain actions in apps, but to someone unfamiliar with tech or the UX patterns of Android, the simple plus icon may not be intuitive right away.
>
> So in Selene, if the user enters the app for the first time and has no notes, and lingers on the main screen for a while, the FAB will visually morph into a full-bleed button prompting them to touch and create a new note.
>
> In instances like this, it’s important that — visually — the user can tell where the animation comes from and what it is doing. “Meaningful motion” is, after all, a main tenet of motion in material design.
>
> What’s interesting about this particular transformation (and transformations like it) is that it’s not happening in response to user input. Typically if the user were touching a button to make this happen, we could get away with a little less explicit motion since the action is connected in a way the user explicitly intended. But for a transformation that happens on its own, the connection must be clear.
>
> After all, once the user has the hang of creating new notes, the FAB takes back its place in the layout, lending more room to the content area.

Since the code is available at the GitHub link above, (as long as it matches your license) it should be relatively easy to implement. @d4rken 

------

[More about it](http://hello.phoebe.xyz)

**Comment by d4rken** [comment]
Changing the design on the user without updates seems to be a good source for confusion and likely ends up with requests for settings to show it in one way or another.

It is pretty fancy, but I don't think it's something for SD Maid as this point.
