### ISSUE TITLE
Update link to bugsnag privacy policy.

### ISSUE THREAD

**Issue by vladrevers** [d4rken/sdmaid-public#3602]
In https://sdmaid.darken.eu/privacy

https://bugsnag.com/docs/privacy > https://docs.bugsnag.com/legal/privacy-policy

**Comment by d4rken** [comment]
Done. Thank you :heart:

**Comment by d4rken** [comment]
I also updated Piwik to Matomo (they had a name change).
And removed ACRA as crash tracking for SD Maid v3.X doesn't exist anymore.
