### ISSUE TITLE
Clutterreport: /storage/emulated/0/Notes/media

### ISSUE THREAD

**Issue by DEC344** [d4rken/sdmaid-public#3621]
### Target
Target: `/storage/emulated/0/Notes/media`
Prefix-free: `Notes/media`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Black Hole`
Packagename: `com.android.galaxy4`
Version: `1.0 (1)`

### Current owners
Appname: `?`
Packagename: `com.oneplus.note`
Version: ` (-1)`

### SD Maid
Version: `4.15.8 (41508)`

### Device
Fingerprint: `Coolpad/cp3622a_mpcs/cp3622a:5.1.1/LMY47V/1670629:user/release-keys`

**Comment by d4rken** [comment]
I don't think these are related.
