### ISSUE TITLE
Issue while cleaning app cache

### ISSUE THREAD

**Issue by subviper** [d4rken/sdmaid-public#3640]
I'm not able to clean the cache in app cleaner bar/ribbon it says active the accessibility settings everytime .......and I already activated this service............ please help me🥺🥺🥺🥺

**Comment by d4rken** [comment]
Try restarting your device.
SD Maid can only check whether the service is enabled, and if it's running.
Actually starting the service is done by the system, sometimes the system fails to do so until reboot.

**Comment by subviper** [comment]
Tried all the tricks but didn't work🥺

**Comment by d4rken** [comment]
What device and ROM is this on?

Also disable any optimizations for SD Maid, see:
https://dontkillmyapp.com/

and disable this if you have it:
![1594106788791102090176500787856](https://user-images.githubusercontent.com/1439229/86775942-175f5480-c058-11ea-9b92-90fb49069e72.png)

**Comment by d4rken** [comment]
Any update on this?

**Comment by subviper** [comment]
No

**Comment by subviper** [comment]
Same problem

**Comment by PurrePuck** [comment]
Hi. I been experiencing the same problem. I been following the instructions here and don't kill my apps without success. I'm not experienced in developing but  I can leave screenprints of the process as you prefer, and hopefully be helpful in solving this issue.

**Comment by d4rken** [comment]
Current information points to this not being an SD Maid issue but related to ROMs killing SD Maid (task killer?) and then the system thinks SD Maid's ACS crashed (when it was just killed).

See:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting
