### ISSUE TITLE
App cleaner not working

### ISSUE THREAD

**Issue by CoderLoneWolf** [d4rken/sdmaid-public#3648]
when i try to delete unnecessary files from app cleaner it shows some error message
I'm using redmi k20 pro facing this issue after miui 12 update 

![Screenshot_2020-07-05-22-19-10-645_eu thedarken sdm](https://user-images.githubusercontent.com/37626734/86537584-b461a680-bf0d-11ea-8065-91dda998d70c.jpg)

**Comment by d4rken** [comment]
This feature is not working correctly:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service
More specifically, it's enabled, but the service, which the system should launch, is not launched.

A reboot usually fixes this, have you tried that?

**Comment by CoderLoneWolf** [comment]
hi

Thank you for your response. I tried rebooting my device even reinstall and
follow all steps but still the same problem. I'm facing this only after
miui 12 update

I like this app so much keeps my phone clean keep up the good work

**Comment by d4rken** [comment]
Apparently there is a hidden setting called "MIUI Optimization" in the developer options.

Other users have had success disabling it.

![1594106788791102090176500787856](https://user-images.githubusercontent.com/1439229/87036924-cbddaf80-c1eb-11ea-8cdd-64747f6a2991.png)

**Comment by d4rken** [comment]
Currently I'm unable to fix anything on SD Maids end here. Sorry.

The next update will fix the scan skipping apps on MIUI 12.
