### ISSUE TITLE
ACS using Samsung specs on Samsung devices with LOS ROM fails to work

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#3652]
Based on the log by @vatonbero from here:
https://github.com/d4rken/sdmaid-public/issues/3639#issuecomment-654163963

The label SD Maid is looking for is `Меморијски простор и кеш` which is known as AOSP label, but SD Maid tries to use Samsung specific specs.

> 1594032289154  V/AppCleaner:ACS:Samsung29Specs: Getting specs for org.fdroid.fdroid (lang=sr, script=)

So SD Maid needs to detect that this is a Samsung device, but not a Samsung ROM.

**Comment by d4rken** [comment]
On a side note, if you already have a custom ROM installed, it should be a small hurdle to let SD Maid run with root permission, which would make this process much cleaner as SD Maid wouldn't have to use the accessibility service.

**Comment by d4rken** [comment]
According to your log and some googlefu, we can use the build prop for `Build.DISPLAY`:

```
D/Debug:BuildProp: ro.build.display.id=lineage_starlte-userdebug 10 QQ3A.200605.001 5a751cbb04
```

Those all start with `lineage`.
I will apply this fix for all other non-AOSP specs too (LGE, MIUI, Flyme etc.) as the same issue should occur there.
SD Maid will automatically fallback to AOSP specs and it should work.

**Comment by vatonbero** [comment]
Hi there,

Thank you for your swift response.

> On a side note, if you already have a custom ROM installed, it should be a small hurdle to let SD Maid run with root permission, which would make this process much cleaner as SD Maid wouldn't have to use the accessibility service.

I would hovewer i use no root method on my Lineage OS nor i intend to do that. I see no benefit for it to be honest.

Also i had a feeling that localization will do some damage. Before, we had similar issue in GNOME whereas nautilus tried to mount android phone by not using whatever UID is available ending with device which cannot be read on computer.

**Comment by d4rken** [comment]
> Also i had a feeling that localization will do some damage. Before, we had similar issue in GNOME whereas nautilus tried to mount android phone by not using whatever UID is available ending with device which cannot be read on computer.

The alternative approach was to go by layout structure and IDs, but that turned out to be even more brittle as the UI structure can change dynamicly. So recognizing it by labels (like us humans do) was the most reliable approach.

**Comment by vatonbero** [comment]
Just to give feedback here: i have tried beta this morning and issue has been fixed in it for the following reported device:

```
Device: Samsung Galaxy S9 (starlte)
OS: Lineage OS 17.1 (July patch)
```

Thank you!

**Comment by d4rken** [comment]
Thanks for confirming :+1:
