### ISSUE TITLE
CorpseFinder is not excluding parent folders if a nested item is excluded

### ISSUE THREAD

**Issue by programmist87** [d4rken/sdmaid-public#3654]
Не всегда работают добавленные исключения. Например, при добавлении файла galleryEx.db (#3626), он не отображается в списке найденного мусора, но всё равно удаляется. Исключение добавлено для всех инструментов.

**Comment by d4rken** [comment]
#3626 is deleted by the corpsefinder until v4.15.13 is released.

Exclusions should still work though. Can you record a debug log of SD Maid deleting it?
Can you show me the exclusion?

**Comment by programmist87** [comment]
Все остальные исключения, сделанные таким же образом, работают.

[sdmaid_logfile_1594637023622.txt.zip](https://github.com/d4rken/sdmaid-public/files/4911960/sdmaid_logfile_1594637023622.txt.zip)

![S00713-134626(1)](https://user-images.githubusercontent.com/60130882/87296809-027b3900-c510-11ea-9a3c-97a998c3dc40.png)

**Comment by d4rken** [comment]
```
1594637033106  D/Exclusion:Simple: '/storage/emulated/0/Android/data/Gallery_local/galleryEx.db' matches '/storage/emulated/0/Android/data/Gallery_local/galleryEx.db'
1594637033107  D/Exclusion:Simple: '/storage/emulated/0/Android/data/Gallery_local/galleryEx.db' matches '/storage/emulated/0/Android/data/Gallery_local/galleryEx.db-journal'
```

The exclusion itself works, but the CorpseFinder does not skip the parent folder, if a child item is excluded.

Good catch :+1:

**Comment by jor514** [comment]
content://com.android.providers.downloads.documents/document/1959

**Comment by jor514** [comment]
content://eu.thedarken.sdm.provider/device_root/storage/emulated/0/Download/sdmaid_logfile_1594637023622%20(1).txt
