### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/shared-com.eusoft (FP)

### ISSUE THREAD

**Issue by MarkussLugia** [d4rken/sdmaid-public#3664]
### Target
Target: `/storage/emulated/0/Android/data/shared-com.eusoft`
Prefix-free: `shared-com.eusoft`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Eudic`
Packagename: `com.eusoft.eudic`
Version: `7.7.2 (325)`

### Current owners
~~Appname: `?`~~
~~Packagename: `shared-com.eusoft`~~
~~Version: ` (-1)`~~

### SD Maid
Version: `4.15.12 (41512)`

### Device
Fingerprint: `Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys`

**Comment by d4rken** [comment]
Thanks for this!
