### ISSUE TITLE
FC when use AppCleaner

### ISSUE THREAD

**Issue by GoFly-wenxue** [d4rken/sdmaid-public#3668]
I'm a SD Maid user from China. When I was using AppCleaner, it fc. How can I do for that?
It seems that SD Maid haven't permission called android.permission.KILL_BACKGROUND_PROCESSES.
This is very important for me and I hope to fix this bug as soon as possible. :(

MIUI 12, Magisk rooted, multiple users used

**Comment by GoFly-wenxue** [comment]
Android 9

**Comment by GoFly-wenxue** [comment]
log link: https://drive.google.com/file/d/1I2V8H13-G_djVRSG77BB-AWV7GupUPEo/view?usp=sharing

**Comment by d4rken** [comment]
Thanks for the report. Will be fixed in the next update.
