### ISSUE TITLE
Vivo in Indonesian application cleaning problem

### ISSUE THREAD

**Issue by ianz56** [d4rken/sdmaid-public#3670]
When I use Indonesian language, App Cleaner in SD Maid always stuck on Clear Cache button, but when I use English language, App Cleaner can working

**Comment by ianz56** [comment]
There is on English Language version

**Comment by ianz56** [comment]
[App Cleaner on English version](https://photos.app.goo.gl/894Zy65srsJhskXz8) 
There app Cleaner on English version

**Comment by ianz56** [comment]
Phone Vivo y81, Android 8.1, Funtouch 4.0

**Comment by ianz56** [comment]
https://photos.app.goo.gl/AzQsLxN8JwbQnWBx7
This is Indonesian version screen record

**Comment by ianz56** [comment]
https://drive.google.com/file/d/12O8O9oaS4z9VSdALaYD-ihb_TEK2fgxu/view?usp=drivesdk

Link log

**Comment by d4rken** [comment]
Thanks, I'll look into it.

It looks like it's not working English either, it just gives up after 10-20 seconds, if it's working it should take 1-2 seconds per app.

**Comment by d4rken** [comment]
@ianz56 Try this:
https://www.dropbox.com/s/6k7m97tjerak0zu/SD_Maid-v4.15.14%2841514%29-BETA-cdb686ec1.apk?dl=0

**Comment by ianz56** [comment]
@d4rken wow it's worked

**Comment by d4rken** [comment]
Great, I'll make the fix part of the next update.

Thanks for improving SD Maid!
