### ISSUE TITLE
Clutterreport: /storage/9C53-F380/Android/data (FP)

### ISSUE THREAD

**Issue by sultudsurmaboy** [d4rken/sdmaid-public#3672]
### Target
Target: `/storage/9C53-F380/Android/data`
Prefix-free: `Android/data`
Path-prefix: `/storage/9C53-F380/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `Android system`
Packagename: 
Version: `9 (28)`

### SD Maid
Version: `4.15.11 (41511)`

### Device
Fingerprint: `xiaomi/tulip/tulip:9/PKQ1.180904.001/V11.0.4.0.PEKMIXM:user/release-keys`

### Comment
`unexpectedly deleted some very important corpse file. how to fully recover it. help please. `

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#recover-deleted-files
