### ISSUE TITLE
[Features add] Make SD Maid able to extract and install split apk.

### ISSUE THREAD

**Issue by sp1cyf0x** [d4rken/sdmaid-public#3674]
![Screenshot_20200716-235429_Discord](https://user-images.githubusercontent.com/24849056/87700192-25337900-c7c0-11ea-97eb-d005f4d47bcb.png)
![Screenshot_20200716-233845_Discord](https://user-images.githubusercontent.com/24849056/87700196-26fd3c80-c7c0-11ea-871e-595085eb2ed5.png)
![Screenshot_20200716-234039_Discord](https://user-images.githubusercontent.com/24849056/87700199-2795d300-c7c0-11ea-8d95-84ace858f359.png)
https://developer.android.com/guide/app-bundle
https://developer.android.com/studio/command-line/bundletool

**Comment by d4rken** [comment]
Support for installing the format that SD Maid exports itself (`-base.apk` + further `*.apk`) in next beta :slightly_smiling_face:
