### ISSUE TITLE
Bug: Android Photo Editor

### ISSUE THREAD

**Issue by usevinc** [d4rken/sdmaid-public#3697]
### What happened?
Android Photo Editor App Not Work Correct

### What did you expect to happen?
Android Photo Editor App Not Work Correct

### How can I reproduce the issue?
Android Photo Editor App Not Work Correct

### Comments
When I edit a photo and using drawing tool with android gallery app, it draw with pen. But when I try saving photo, app is save photo but without not save my drawing.
### SD Maid
Version: `4.15.12 (41512)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `Unknown`
Fingerprint: `samsung/ja3gxx/ja3g:5.0.1/LRX22C/I9500XXUHPJ3:user/release-keys`

**Comment by d4rken** [comment]
What's the relation to SD Maid here?

**Comment by usevinc** [comment]
> What's the relation to SD Maid here?

because i installed sd maid on two of my devices and i bought  license for my devices. Before installing the sd maid, I had no problems with the drawing tool of the gallery app. but after installing sd maid the drawing tool was inoperable.

**Comment by d4rken** [comment]
Which tools in SD Maid show files from this app if you execute a scan?

**Comment by usevinc** [comment]
> Which tools in SD Maid show files from this app if you execute a scan?

At the end of the scan I see "Gallery application" in "application cleaner".
https://i.hizliresim.com/BIV3in.jpg

**Comment by d4rken** [comment]
Can you show me what the details show (Click on the info icon)?

**Comment by usevinc** [comment]
Sure! 
https://bit.ly/30JER2l

**Comment by d4rken** [comment]
None of these would explain your issues.

The only other thing I could thing of, is that the SystemCleaner deleted an empty directory that the app used to store images in, and the app does not recreate that if necessary. Can you specify the storage path somewhere?

**Comment by usevinc** [comment]
> None of these would explain your issues.
> 
> The only other thing I could thing of, is that the SystemCleaner deleted an empty directory that the app used to store images in, and the app does not recreate that if necessary. Can you specify the storage path somewhere?

I don't know how it's done. Could you help me?

**Comment by d4rken** [comment]
I don't know the specific gallery app you are using, the only other suggestions would be to add an exclusion for that app:
https://github.com/d4rken/sdmaid-public/wiki/Exclusions

**Comment by d4rken** [comment]
Unable to reproduce :(
