### ISSUE TITLE
Bug: One error

### ISSUE THREAD

**Issue by vas99** [d4rken/sdmaid-public#3748]
### What happened?
After scheduler run, the report advises of one error.

### What did you expect to happen?
The scheduler to run all tasks smoothly

### How can I reproduce the issue?
Run the scheduler with do not disturb on

### Comments
I checked the report but cannot pinpoint the error and what to do to fix it. It happens every single time
### SD Maid
Version: `4.15.13 (41513)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a50eea/a50:10/QP1A.190711.020/A505FNXXU5BTF7:user/release-keys`

**Comment by d4rken** [comment]
Can you show me the error?

**Comment by vas99** [comment]
Hi.

Thank you for your time.

When I click on the error message, it goes straight to the quick access
screen. I then check on the statistics screen where I assume the errors are
displayed with an exclamation mark next to each report.
I have included screenshots.
I'm not that savvy with error reports so if there is another way, please
let me know.

Hope you are well and safe.

Regards,
Vas


On 4 Aug 2020 at 16:31, Matthias Urhahn <notifications@github.com> wrote:

Can you show me the error?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/d4rken/sdmaid-public/issues/3748#issuecomment-668666476>,
or unsubscribe

**Comment by vas99** [comment]
Had to send 2 emails to include all screenshots


On 4 Aug 2020 at 16:31, Matthias Urhahn <notifications@github.com> wrote:

Can you show me the error?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/d4rken/sdmaid-public/issues/3748#issuecomment-668666476>,
or unsubscribe

**Comment by d4rken** [comment]
I'm trying to follow up on this, what was the subject of your email, I'm having trouble finding the screenshots.
