### ISSUE TITLE
Clutterreport: /storage/emulated/0/3D Movie Effects (new)

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3758]
### Target
Target: `/storage/emulated/0/3D Movie Effects`
Prefix-free: `3D Movie Effects`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `3D Movie Effects`
Packagename: `com.appwallet.movieeffects`
Version: `1.16 (17)`

### Current owners
None

### SD Maid
Version: `4.15.13 (41513)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1540458380:user/release-keys`

**Comment by Ingood5** [comment]
Эта папка так и не помечается как принадлежащая этому приложению.

Вы проверяете как SD Maid находит новые добавленные папки?

**Comment by d4rken** [comment]
Yes I but not every entry. I write tests for new AppCleaner changes, and for clutter entries if they have problematic names.

This does not look like a problematic name, maybe I made a copy&paste error. Will check.

Thanks for letting me know.

**Comment by Ingood5** [comment]
Возможно, у вас получится проверять все записи 🤔

**Comment by d4rken** [comment]
Copy&Paste error, sorry :( fixed!

**Comment by Ingood5** [comment]
А возможно написать тест, в который можно будет отправлять все записи, чтобы избежать таких случайных случаев?

**Comment by Ingood5** [comment]
Вы не пропустили?

**Comment by Ingood5** [comment]
Вы не пропустили? 😸
