### ISSUE TITLE
Clutterreport: /storage/emulated/0/VoiceChangerWE/VoiceChanger Audio (new)

### ISSUE THREAD

**Issue by Invisible02** [d4rken/sdmaid-public#3793]
### Target
Target: `/storage/emulated/0/VoiceChangerWE/VoiceChanger Audio`
Prefix-free: `VoiceChangerWE/VoiceChanger Audio`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Преобразователь голоса с эффектами`
Packagename: `com.baviux.voicechanger`
Version: `3.7.7 (3707)`

### Current owners
None

### SD Maid
Version: `4.15.13 (41513)`

### Device
Fingerprint: `Xiaomi/rosy/rosy:8.1.0/OPM1.171019.026/V11.0.2.0.ODAMIXM:user/release-keys`

**Comment by d4rken** [comment]
What about `/storage/emulated/0/VoiceChangerWE` ?
Is that created by another app?
Or is it shared by multiple apps?

**Comment by Invisible02** [comment]
> What about `/storage/emulated/0/VoiceChangerWE` ?
> Is that created by another app?
> Or is it shared by multiple apps?

The `/storage/emulated/0/VoiceChangerWE` folder was created by the same `Преобразователь голоса с эффектами` application.
