### ISSUE TITLE
Stuck on 'In queue' process

### ISSUE THREAD

**Issue by k4tipun** [d4rken/sdmaid-public#3796]
When running a process, such as 'Overview', 'Explorer', 'Quick Access' it will stuck on In queue and will not continue. Even opening the Settings will be stuck on loading screen. Reinstalled the app and still same issue.
This app previously worked on Poco F1 MIUI 11
Since I switch to LineageOS 17.1 the app don't work.
![Screenshot_20200813-101017_SD_Maid](https://user-images.githubusercontent.com/25127774/90086817-e86e8980-dd4d-11ea-9cf3-c137168a06b9.png)
![Screenshot_20200813-101510_SD_Maid](https://user-images.githubusercontent.com/25127774/90086830-eefd0100-dd4d-11ea-98fd-bf87c48e99e0.png)

**Comment by d4rken** [comment]
Hi,

See:
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#hanging
