### ISSUE TITLE
Clutterreport: /storage/emulated/0/citra-emu

### ISSUE THREAD

**Issue by luziferius** [d4rken/sdmaid-public#3799]
### Target
Target: `/storage/emulated/0/citra-emu`
Prefix-free: `citra-emu`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Citra`
Packagename: `org.citra.citra_emu`
Version: `3608cb90b (14075545)`

### Current owners
Appname: `?`
Packagename: `org.citra.emu`
Version: ` (-1)`

### SD Maid
Version: `4.15.13 (41513)`

### Device
Fingerprint: `samsung/a5y17ltexx/a5y17lte:8.0.0/R16NW/A520FXXUECTDA:user/release-keys`

### Comment
It seems that the Citra developers have renamed the package.

I got the early access version from.Google Play.

**Comment by Blh18** [comment]
Ez mi?

**Comment by Blh18** [comment]
Ez mien alkalmazás?
