### ISSUE TITLE
Make use of freeStorageAndNotify optional on unrooted devices

### ISSUE THREAD

**Issue by fotopan** [d4rken/sdmaid-public#380]
As per [developer explanation](https://github.com/d4rken/sdmaid-public/wiki/Appcleaner#some-appcleaner-exclusions-dont-work-without-root) using freeStorageAndNotify means that not SD Maid, but the system itself does the deletion and the system does not know about SD Maids exclusions. 

Please make use of the freeStorageAndNotify optional in case somebody would like to be sure the excluded files will not be deleted when using SD Maid.

**Comment by d4rken** [comment]
Just to note, this will cause the private cache to not be deleted at all, for any app. Though this is a restriction everyone will face soon as the `freeStorageAndNotify` trick stops working with Android 6.0.

FYI: http://stackoverflow.com/questions/31989637/android-m-reflection-method-freestorageandnotify-exception

I like this request though and I'm confident it will be part of the next few updates.
