### ISSUE TITLE
Add ability to save/share file list (Last Modified)

### ISSUE THREAD

**Issue by cheshyrex** [d4rken/sdmaid-public#382]
As a user investigating the files changed by a recent action,
I want the ability to save/share SDMaid's Last Modified file list
So that I can review the files in another app or offline.

**File format:**
Plain text is fine.
At a minimum, only the paths & filenames are necessary.
If reasonable, it would be nice to include the filesize and timestamp.

**Delivery method:**
Bare minimum: save to the sdcard (default filename shd include timestamp, but be editable).
Ideally, offer choice between saving locally or using standard Share options.

**Comment by d4rken** [comment]
While the LastModified section no longer exists on it's own, the idea now would be to allow selecting results from the search tool and export it to a markdown formatted .txt file.
