### ISSUE TITLE
Bug: spend too much time on scanning excluded path

### ISSUE THREAD

**Issue by rhjdvsgsgks** [d4rken/sdmaid-public#3834]
### What happened?
spend too much time on scanning excluded path

### What did you expect to happen?
skip excluded path on scanning

### How can I reproduce the issue?
create a folder with much of small files in termux , add /data/user/0/com.termux to exclude path , run system cleaner

### SD Maid
Version: `4.15.12 (41512)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`

**Comment by rhjdvsgsgks** [comment]
actually, not only "spend too much time", but also caused sdmaid freeze and crash. at least right now if i don't uninstall the application which have many small file, sdmaid will crash when AppCleaner running
here is the log of crash
```
FATAL EXCEPTION: pool-5-thread-1
Process: eu.thedarken.sdm, PID: 31791
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```
and in another crash it says " binder timeout " , but i forgot to save the log to file

**Comment by d4rken** [comment]
Was SystemCleaner really the only tool you ran? Unless you have a filter matching 100k files, there should be no OOM.

**Comment by rhjdvsgsgks** [comment]
actually, i have 354067 files under `/data/data/com.termux`, but i dont know how many files matched
