### ISSUE TITLE
Moving apps to storage

### ISSUE THREAD

**Issue by michu2** [d4rken/sdmaid-public#3837]
I really love your product and have been using it for many years the question I have is when I move an app to my SD card it doesn't free up any space on my normal memory on the phone so why is that and is there something I can do to free up that memory on the phone since I moved the app to the SD card appreciate any help you can give thank you

**Comment by d4rken** [comment]
Moving apps to storage is currently out of scope for SD Maid as there are too many different approaches over the Android versions.
SD Maid supports a single "default" approach, if it's available it will be visible in AppControl, if not then not (likely needs root).

Depending on your Android version, moving to sdcard does not move all app files, and it's possible that the files that can't be moved make up most of the app's files.
