### ISSUE TITLE
Request: Export and import app settings

### ISSUE THREAD

**Issue by JonDous** [d4rken/sdmaid-public#3838]
### What should the feature do?
Export settings to file. Import from the file. 

### When/How would you use it?
When reinstall app, os or buy new phone. To give settings to friends. 

### SD Maid
Version: `4.15.13 (41513)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Xiaomi/cepheus/cepheus:9/PKQ1.181121.001/V10.2.14.0.PFAMIXM:user/release-keys`

**Comment by d4rken** [comment]
Exclusions and custom Filters can already be exported, whole settings backup is currently not supported, unless you have root and can make a full app backup.

Closing as dub in favor of #599

**Comment by JonDous** [comment]
Are you serious? I even didn't know about it. People on forum also told me there are no options. I've been looking two minutes to understand how to export. It is not obvious.

And request was to make a one button for all available settings (I can pick checkboxes), not to run from one tab to another.

**Comment by d4rken** [comment]
> And request was to make a one button for all available settings (I can pick checkboxes), not to run from one tab to another.

I understand, that is what #599 is about. I'm sorry I can't offer you a more satisfying solution at the moment.

**Comment by JonDous** [comment]
I'm sure you don't want to understand what I've written. I didn't ask for root settings. I'm asking to make only one button for all AVAILABLE settings. Do you feel the difference? Now there are minimum two (maybe be more but I found only two. Before your answer not me not people on the forum had not known about these export options coz they are not obvious).

Just make a button or tab in the options to export settings and let user choose what he needs between different settings.

For now i must to open one tab and export settings, open next tab and export settings again. The same with import.

Why we should run from tab to tab. Is it too hard to make a one button with checkboxes what to export/import? Why other apps can do it but you don't want?

![Screenshot_2020-08-30-18-20-25-200_idm internet download manager plus](https://user-images.githubusercontent.com/68903949/91657742-82278c00-eaed-11ea-9506-d26f73bc2f40.png)
![Screenshot_2020-08-30-18-20-28-031_idm internet download manager plus](https://user-images.githubusercontent.com/68903949/91657746-89e73080-eaed-11ea-960f-af3e430629b5.png)
