### ISSUE TITLE
Scheduler time selection doesn't fit in screen. 

### ISSUE THREAD

**Issue by Tritonio** [d4rken/sdmaid-public#384]
This is on an LG Leon 5.0.1.
![screenshot_2016-05-05-16-02-33](https://cloud.githubusercontent.com/assets/1833520/15045574/8948747a-12db-11e6-98a4-1d2948ac8bca.png)

**Comment by d4rken** [comment]
How does it look in landscape?

**Comment by d4rken** [comment]
Fix committed for v4.2.5
