### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM/Video Merge (FP)

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3847]
### Target
Target: `/storage/emulated/0/DCIM/Video Merge`
Prefix-free: `DCIM/Video Merge`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Видео слияние`
Packagename: `com.psma.videomerge`
Version: `1.7 (9)`

### Current owners
~~Appname: `Система Flyme`~~
~~Packagename: `android`~~
~~Version: `8.1.0 (27)`~~

### SD Maid
Version: `4.15.13 (41513)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by Ingood5** [comment]
Пропущено 😦 Не помечено данным приложением.

**Comment by d4rken** [comment]
Sorry my mistake, fixed now.
