### ISSUE TITLE
Any issues with moving SD Maid to external microSD card?

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#386]
The manifest for SD Maid is set to allow it to be installed on an external microSD card (thanks!).

When apps are moved to an external microSD card, they generally can't respond to BOOT_COMPLETED.

Is there any loss of functionality for either the free or paid versions of SD Maid when it is moved to the external microSD card?

Any problems with moving it to the external microSD card?

**Comment by d4rken** [comment]
The scheduler will loose it's settings on reboot as the alarm has to be restored through the `BOOT_COMPLETED` event. See: http://developer.android.com/guide/topics/data/install-location.html

I'm unaware of any other issues.

**Comment by Gitoffthelawn** [comment]
Thanks Matthias.  So if we don't use the scheduler, there are no issues.

Very much appreciate your help. :-)
