### ISSUE TITLE
SystemCleaner default filter list sorting is semi random

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3862]
После перезагрузки телефона хаотично меняется очерёдность фильтров в списке в SystemCleaner. Другие фильтры не проверял.

**Comment by d4rken** [comment]
Does this also happen if you "Force stop" SD Maid?

**Comment by Ingood5** [comment]
Да. Проверил, ошибка только на вкладках Универсальные и Специфичные. В AppCleaner ошибки нет.

**Comment by d4rken** [comment]
Currently can't reproduce this, can you show a video?

**Comment by Ingood5** [comment]
Как оказалось, для появления проблемы достаточно принудительно остановить SD Maid.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5254662/video.zip)
