### ISSUE TITLE
Oppo A9 (2020) incorrect work

### ISSUE THREAD

**Issue by Hunterus2020** [d4rken/sdmaid-public#3864]
Oppo A9 (2020) — ColorOS 7.1 (based on Android 10) incorrect working again!

About phone:
https://drive.google.com/file/d/1HV2MuGeKuh5aYTYTDYOKVWhIcFDPoSd-/view?usp=drivesdk

Video: 
https://drive.google.com/file/d/1HDbBbcV32CV3r5sVVziPspk1sPC8vRrD/view?usp=drivesdk

log:
https://drive.google.com/file/d/1HJXTJvgtnEyC3ssz9GFEN4wBLjzJoEA-/view?usp=drivesdk

**Comment by Hunterus2020** [comment]
Will there be a fix?

**Comment by d4rken** [comment]
Yes, just need more time, sorry!

**Comment by Hunterus2020** [comment]
Hello!  ColorOS has recently been updated to version c79 (there was a version c69).

![IMG_20200928_185058](https://user-images.githubusercontent.com/67745239/94455415-b315e200-01bb-11eb-8796-576a3cd40de6.jpg)
The problem is still there. :—)

**Comment by Hunterus2020** [comment]
Hello!  Will there be a solution to this problem?

**Comment by d4rken** [comment]
Fixed in the next update.

**Comment by Hunterus2020** [comment]
Hello! :(
![Uploading Screenshot_2020-11-09-14-08-41-91_62f0e9ef2a35bdc7c62d39832d484c48.jpg…]()

**Comment by Hunterus2020** [comment]
Hello! :(

![Screenshot_2020-11-09-14-08-41-91_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/67745239/98534276-46e7cd00-2295-11eb-8154-e2ef39cea2b1.jpg)
