### ISSUE TITLE
SDMaid V4.2.0 is unable to make SystemCleaning

### ISSUE THREAD

**Issue by igoivo** [d4rken/sdmaid-public#387]
V4.2.0 is unable to clean data/logs, data/system/usagestats... - 10-20MB in total, usually.  
Previous version of SDMaid was able to clean it.

**Comment by d4rken** [comment]
Please provide a debug run log of SD Maid failing to delete the files in question.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by d4rken** [comment]
Identified the issue, will be fixed in the next update. Thanks for your report.

**Comment by HorstiG** [comment]
Great thank you. Was wäre ich ohne meine Maid :-)
