### ISSUE TITLE
Suggestion to change dimension calculation in explorer

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3870]
Наверно стоит изменить в проводнике отображение размера файлов и папок, чтобы размер в мб и кб делился не на 1000, а на 1024, как в других проводниках. Если приходится сравнивать файлы с другими проводниками, это иногда запутывает.

**Comment by d4rken** [comment]
Can you give an example?

SD Maid uses the systems default file size formatting:
https://developer.android.com/reference/android/text/format/Formatter#formatFileSize(android.content.Context,%20long)

**Comment by Ingood5** [comment]
Есть файл размером 2.090.000.000 байт.

SD Maid показывает у него размер 2,09 гб.
Встроенный проводник Meizu и ES  проводник показывают 1,95 гб.  
Из 10 популярных проводников из Google Play, 6 –показывают 1.95 гб, 4 – показывают 2.09 гб. 
На форуме много информации, что производители памяти считают объём 1 кб = 1000 байт, а программы и OS: 1 кб = 1024 байт. 
И разве в компьютерной системе исчисления на задумано изначально, что 1 кб это 1024 байта? На деле правильно именно так.

Возможно стоит или изменить вычисление размера на: 1 кб = 1024 байт, или сделать этот вариант по умолчанию, а в настройках добавить опцию переключения на 1 кб= 1000 байт. Потому что даже встроенный проводник подсчитывает как 1024, и если приходится при поиске мусора использовалась его, разные размеры запутывают. Если будет необходимость смены способа подсчёта, то тот кому это нужно, всегда сможет ее поменять в настройках.

**Comment by d4rken** [comment]
I'm not going to add extra settings just for this, sorry :frowning: .

For < Android N the system uses `1024`, and for Android N+ it uses `1000`, SD Maid does the same.

I think it is best to stick with the official calculation method which is now `1000` on new Android versions, and I think that using `1000` is actually more correct, because that's the official standard:
https://en.wikipedia.org/wiki/Kilobyte

**Comment by Ingood5** [comment]
> https://en.wikipedia.org/wiki/Kilobyte

О, благодарю, не знал!
