### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#389]
Apparently SD Maid can currently not be installed on Android TV.

**Comment by DJayM** [comment]
The following Intent will allow the app to be installed on TVs and will also make it show up as a tile on LeanBack Launcher

```
<intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
    </intent-filter>
```

More information about TV app development can be found here

https://developer.android.com/training/tv/start/start.html

cheers.
