### ISSUE TITLE
Clutterreport: /storage/emulated/0/Contacts

### ISSUE THREAD

**Issue by msjb4109** [d4rken/sdmaid-public#3898]
### Target
Target: `/storage/emulated/0/Contacts`
Prefix-free: `Contacts`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Contacts`
Packagename: `com.samsung.android.contacts`
Version: `10.2.30.15 (1023000015)`

### Current owners
Appname: `?`
Packagename: `com.jbapps.contact`
Version: ` (-1)`

Appname: `?`
Packagename: `com.jbapps.contactpro`
Version: ` (-1)`

### SD Maid
Version: `4.15.14 (41514)`

### Device
Fingerprint: `samsung/a50dv/a50:9/PPR1.180610.011/A505YNDVS4ATA1:user/release-keys`

### Comment
`Hi, 

I created this directory to store backups of my contacts, using the stock Samsung Contacts app.

Sometimes I found that while using another app, the Contacts directory and its contents were missing, so I setup a Tasker directory monitor to find out which app was deleting this directory, and on my next run of SD Maid (scan and delete in one pass) I was immediately notified that SD Maid was the foreground app running when the Contacts directory was deleted. 

I replaced it with a backup copy then manually ran Corpse Finder, scan only, which then suggested that the Contacts directory be deleted. 

(Samsung A50, Android 9)`

**Comment by d4rken** [comment]
Thanks. Will fix this and also flag this as `common` due to the name `Contacts` it's likely  to happen with other contact apps too.
