### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.adguard.android (FP)

### ISSUE THREAD

**Issue by bpetter** [d4rken/sdmaid-public#3905]
### Target
Target: `/storage/emulated/0/Android/data/com.adguard.android`
Prefix-free: `com.adguard.android`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `AdGuard`
Packagename: `com.adguard.android`
Version: `3.2.140 (3002140)`

### SD Maid
Version: `4.15.14 (41514)`

### Device
Fingerprint: `lge/timelm/timelm:10/QKQ1.191222.002/202201224550b:user/release-keys`

### Comment
`app archive backup`

**Comment by d4rken** [comment]
What's the issue with the current state?
Seems SD Maid already knows the owner?

**Comment by bpetter** [comment]
Nothing just a new user
