### ISSUE TITLE
Clutterreport: /storage/emulated/0/.profig.os

### ISSUE THREAD

**Issue by zputnyq** [d4rken/sdmaid-public#3916]
### Target
Target: `/storage/emulated/0/.profig.os`
Prefix-free: `.profig.os`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `?`
Packagename: `com.instagram.android`
Version: ` (-1)`

### SD Maid
Version: `4.15.14 (41514)`

### Device
Fingerprint: `Sony/E2306/E2306:6.0.1/26.3.A.1.33/1954918276:user/release-keys`

### Comment
`This item should only be deleted if the app that created it is not installed or removed. The reason is, this Item won't be created if it is still exist, but if this item is deleted it will be created again.`

**Comment by d4rken** [comment]
What app created it, SD Maid currently says Instagram, is that not the case?

**Comment by zputnyq** [comment]
Yes that's not the case, what create it is not the case. So far Instagram creates it, that's right. I did a testing by uninstalling instagram then delete that file and then using my device without instagram for several days profig.os doesn't come back.

The case is that file will be back again after it is deleted if still using instagram. I think it's better if this file is only deleted when instagram is uninstalled, or this file in my opinion is better to be put into remnants category

**Comment by d4rken** [comment]
Which tool deletes it? SD Maid should only delete it via CorpseFinder when Instagram is no longer installed.

What's the package name of Instagram on your device?

**Comment by zputnyq** [comment]
My apology. It's my mistake. I used the wrong apk it was an instgram mod that I used. No problem when I use official instgram
