### ISSUE TITLE
Scheduler not working on 4.2.0

### ISSUE THREAD

**Issue by sharky127** [d4rken/sdmaid-public#392]
The count down timer resets back to --:--:-- after reaching 00:00:00. Moreover, it doesn't actually perform the selected tasks.

**Comment by d4rken** [comment]
What device/ROM?

At which point does it reset? While watching? When exiting the app? When rebooting?
Might be a case of this: https://github.com/d4rken/sdmaid-public/issues/377

**Comment by sharky127** [comment]
SG Note 4, CM13 unofficial, SD Maid 4.2.0 Pro.

Set my scheduler (every 1 day), after reaching 00:00:00 the countdown timer restarts but doesn't perform any actions (while watching _or_ SD Maid closed). I've caught the scheduler resetting back to --:--:-- a few times, but can't determine the cause (opening SD Maid on random and seeing that the scheduler is off). Double tapping to exit _or_ killing the SD Maid itself _or_ rebooting device doesn't seem to reset the timer (just tested).

**Comment by d4rken** [comment]
I think this is #377
 I've added your details there, feel free to add more info.
