### ISSUE TITLE
Clutterreport: /data/app/~~u_9YNU_1-CdkglzGds9oDg== (FP)

### ISSUE THREAD

**Issue by unsavedmatt** [d4rken/sdmaid-public#3930]
### Target
Target: `/data/app/~~u_9YNU_1-CdkglzGds9oDg==`
Prefix-free: `~~u_9YNU_1-CdkglzGds9oDg==`
Path-prefix: `/data/app/`
Type: `DIRECTORY`
Location: `APP_APP`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.15.14 (41514)`

### Device
Fingerprint: `google/coral/coral:11/RP1A.200720.009/6720564:user/release-keys`

### Comment
`Hi. I'm not quite sure if this is helpful, but I just upgraded my Pixel 4XL to Android 11 and after getting everything set up I ran an SDMaid scan. It found 4.9 gb of corpse files that look like this in /data/app/. When I ran the cleaner I started getting a bunch of force close errors for multiple apps and when I rebooted my phone it had wiped all of my apps. I don't know if this is unexpected behavior or user error. Thanks. `

**Comment by d4rken** [comment]
It's unexpected behavior. A change in Android 11.
Looking into it and will issue a hotfix, thanks :heart: !

**Comment by d4rken** [comment]
Update is available now.
