### ISSUE TITLE
CorpseFinder uninstalling WhatsApp

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#394]
Reported by ew on XDA [here](http://forum.xda-developers.com/showpost.php?p=67010563&postcount=2483) and [here](http://forum.xda-developers.com/showpost.php?p=67023347&postcount=2485).

> It found and deleted com.whatsapp-10 from data/app - and then began my issues with whatsapp.
> The app is not immediately uninstalled. What happens is I get an fc each time I try to open whatsapp. I then reboot my phone - and whatsapp is uninstalled.

**Comment by d4rken** [comment]
Mismatching regex due to double digit install number appendix, will be fixed with v4.2.3.

**Comment by Gitoffthelawn** [comment]
Was this a bug or a feature ;-)

**Comment by d4rken** [comment]
Clearly a bug :)
