### ISSUE TITLE
Bug: An error occurred while scanning with an added exception.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3952]
### What happened?
Если добавить в исключения папки из /storage/emulated/0/Android/data/pushSdk, то во время сканирования CorpseFinder – SD Maid закрывается с ошибкой. Это происходит каждый раз.

[S00914-05132015.mp4.zip](https://github.com/d4rken/sdmaid-public/files/5215777/S00914-05132015.mp4.zip)

[sdmaid_logfile_1600049332258.txt.zip](https://github.com/d4rken/sdmaid-public/files/5215781/sdmaid_logfile_1600049332258.txt.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Awesome find, could reproduce, will fix :+1:

**Comment by d4rken** [comment]
Was likely a mistake I made when adding #3654

**Comment by Ingood5** [comment]
👍
