### ISSUE TITLE
Is it possible to subscribe to new version notifications?

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3963]
Возможно ли подписаться на уведомления на электронную почту о выходе новых версий SD Maid, если в Google Play отключено автообновление? Неудобно постоянно вручную проверять выход новой версии. В Google Play я такой функции не заметил.

**Comment by d4rken** [comment]
I don't have any feature like this, if there is none on Google Play, there is no such feature, sorry :(.

Maybe you can monitor http://sdmaid.darken.eu/download with a script?

**Comment by Ingood5** [comment]
Благодарю! Можно отслеживать с помощью сайта для отслеживания веб-страниц.
