### ISSUE TITLE
Ошибка: CorpseFinder skips garbage

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#3969]
Файл помечен CorpseFinder, но CorpseFinder его не находит.

![S00916-06580547(1)](https://user-images.githubusercontent.com/60130882/93291109-e97e5500-f7ea-11ea-8ad0-a8c0efc19230.png)

[sdmaid_logfile_1600228731974.txt.zip](https://github.com/d4rken/sdmaid-public/files/5229584/sdmaid_logfile_1600228731974.txt.zip)

**Comment by d4rken** [comment]
It should not be deleted, but it should also not be marked as garbage.

**Comment by Ingood5** [comment]
Проблема осталась 😟
