### ISSUE TITLE
Clutterreport: /data/data/com.giovannibozzano.wakeblock (FP)

### ISSUE THREAD

**Issue by t-jinyi7C** [d4rken/sdmaid-public#3980]
### Target
Target: `/data/data/com.giovannibozzano.wakeblock`
Prefix-free: `com.giovannibozzano.wakeblock`
Path-prefix: `/data/data/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `WakeBlock`
Packagename: `com.giovannibozzano.wakeblock`
Version: `0.5.2 (46)`

### SD Maid
Version: `4.15.15 (41515)`

### Device
Fingerprint: `samsung/nobleltejv/noblelte:7.0/NRD90M/N920CXXU3CQH6:user/release-keys`

### Comment
`There are some required files here for wakeblock to work but AppCleaner deletes everything. Sorry I can't pinpoint which exactly are they. If there's any method to tell, I would be glad to try. AppCleaner settings: everything in generic selected.`

**Comment by githubcomLGFam5** [comment]
LICENSE.txt

**Comment by d4rken** [comment]
I need a debug log to check this 

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Babygitzy100** [comment]
I am responding to your email https://github.com/d4rken/sdmaid-public/issues/3980
