### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.spotify.music/files/spotifycache/offline.bnk (FP)

### ISSUE THREAD

**Issue by scottieboomz** [d4rken/sdmaid-public#3987]
### Target
Target: `/storage/emulated/0/Android/data/com.spotify.music/files/spotifycache/offline.bnk`
Prefix-free: `com.spotify.music/files/spotifycache/offline.bnk`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `Spotify`
Packagename: `com.spotify.music`
Version: `8.5.76.962 (64232017)`

### SD Maid
Version: `4.15.15 (41515)`

### Device
Fingerprint: `lge/cv7as/cv7as:10/QKQ1.200308.002/202391619c522:user/release-keys`

### Comment
`This is my user profiles for Spotify.`

**Comment by d4rken** [comment]
What's your question?
