### ISSUE TITLE
Accessibility service is not triggered when deletion via AppCleaner details

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4005]
В AppCleaner без root не удаляется скрытый кеш отдельного приложения, если это делать нажатием на пункт в списке. Если удалить нажатием на значок корзины вверху, то кэш успешно удаляется.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5277067/video.zip)

[sdmaid_logfile_1600959413432.txt.zip](https://github.com/d4rken/sdmaid-public/files/5277071/sdmaid_logfile_1600959413432.txt.zip)

**Comment by d4rken** [comment]
Nice find. :+1: 
Accessibility based deletion is not triggered when the mock entry in the app cleaners details is clicked.
