### ISSUE TITLE
Automate the deletion cache files does not work (AppCleaner)

### ISSUE THREAD

**Issue by xdadi** [d4rken/sdmaid-public#4008]
SDMaid App verison: 4.15.15
Phone: Note 10 Plus, Android 10, September security update.

![Screenshot_20200925-122745_Settings](https://user-images.githubusercontent.com/71876242/94251571-61efbf00-ff2b-11ea-95d8-ccebd099b9a9.jpg)

**Comment by d4rken** [comment]
I need a debug log of this to fix it.

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by aminkh1373** [comment]
> SDMaid App verison: 4.15.15
> Phone: Note 10 Plus, Android 10, September security update.
> 
> ![Screenshot_20200925-122745_Settings](https://user-images.githubusercontent.com/71876242/94251571-61efbf00-ff2b-11ea-95d8-ccebd099b9a9.jpg)
