### ISSUE TITLE
AppCleaner exclusions doesn't work (no root, freeStorageAndNotify off)

### ISSUE THREAD

**Issue by Kisl0iD** [d4rken/sdmaid-public#401]
I have read the wiki about freeStorageAndNotify trick, and i disabled this function. But all temporary files of excluded apps in Android/data/{app}/ still clearing with AppCleaner. Is there any way to fix it?
Android 5.1.1, no root.
Anyway thanks for the app;)

**Comment by d4rken** [comment]
Can you show me your exclusions and the files that still appear after a scan even though they should be excluded?

**Comment by Kisl0iD** [comment]
SdMaid 4.2.2. Here you are. Zedge exclusions just for testing, it's also appears after a scan. Samsung Galaxy Note 5.
![screenshot_2016-06-01-13-53-25](https://cloud.githubusercontent.com/assets/19685605/15707573/11cb5566-2802-11e6-9fb3-67fc0e846ffb.jpg)
![screenshot_2016-06-01-13-54-03](https://cloud.githubusercontent.com/assets/19685605/15707574/13bc4196-2802-11e6-91e9-0adcdb4da456.jpg)
![screenshot_2016-06-01-13-54-24](https://cloud.githubusercontent.com/assets/19685605/15707575/1550bad2-2802-11e6-86e0-0e35971b4dbc.jpg)
![screenshot_2016-06-01-13-54-54](https://cloud.githubusercontent.com/assets/19685605/15707577/18cd972a-2802-11e6-9df4-5c76a9044bce.jpg)
![screenshot_2016-06-01-13-57-46](https://cloud.githubusercontent.com/assets/19685605/15707579/19daa176-2802-11e6-960b-006d682c6013.jpg)

Sorry for the size)

**Comment by d4rken** [comment]
I'll see if I can reproduce this. If you have some spare time, you could record a debug log (https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log). You can attach it as .zip file to this ticket, or mail it to me.

(Don't worry about the screenshot size)

**Comment by Kisl0iD** [comment]
I hope this will help. Anyway, i think i must root my phone and the issue will gone. Sadly, Samsung invent new tricks with every new phone generation to prevent rooting.
[sdmaid_logfile_1464780206753.log.zip](https://github.com/d4rken/sdmaid-public/files/293281/sdmaid_logfile_1464780206753.log.zip)

**Comment by d4rken** [comment]
Thanks for the log.
Rooting your phone will definitely grant SD Maid more options and room to work with, but I've reproduced your issue and this is definitely a bug.
Currently working on a fix.

**Comment by Kisl0iD** [comment]
Thanks! If I won't root my phone, I'll wait for update)

**Comment by d4rken** [comment]
Fix is committed for v4.2.4
