### ISSUE TITLE
After cleaning, went to my app cache, and  it wasn't clean, help please.

### ISSUE THREAD

**Issue by clmaclean** [d4rken/sdmaid-public#403]
After cleaning w SD Maid Pro, I went to my app cache in my phone settings, and  it wasn't clean, help please. This has happened with every other cleaner I have tried. I have Android 6.

**Comment by d4rken** [comment]
This is a limitation since Android 6.0 as the `freeStorageAndNotify` trick no longer works, the only way for an app to delete private caches is with root access.

Also see:
https://github.com/d4rken/sdmaid-public/wiki/Appcleaner#cache-deletion-on-unrooted-devices-running-android-60
