### ISSUE TITLE
Bug: Does not detect or clean app cache

### ISSUE THREAD

**Issue by Kunzai1** [d4rken/sdmaid-public#4047]
### What happened?
Has stopped detecting app caches in Android 11

### What did you expect to happen?
Till Android 10, detected and cleaned app caches of various apps like YouTube, reddit etc.

### How can I reproduce the issue?
Simply scan and you'll see that it does not detect anything like before (less than 10 mb files to be cleaned out)

### Comments
Does it support Android 11 correctly now?
### SD Maid
Version: `5.0.0 (50000)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `google/walleye/walleye:11/RP1A.200720.009/6720564:user/release-keys`

**Comment by d4rken** [comment]
Have you enabled the accessibility service? If yes, provide a debug log + possibly a video of the AppCleaner not working.

https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Kunzai1** [comment]
The accessibility service was enabled. Here is the video showing the problem and the debug log.

[sdmaid_logfile_1601303087842.txt.zip](https://github.com/d4rken/sdmaid-public/files/5296907/sdmaid_logfile_1601303087842.txt.zip)

Somehow I'm not able to upload video here so here is the drive link!
https://drive.google.com/file/d/13i1R13Tfc9_SRk1wHUkNajt8M00FxAoA/view?usp=drivesdk

**Comment by swejuggalo** [comment]
> The accessibility service was enabled. Here is the video showing the problem and the debug log.
> 
> [sdmaid_logfile_1601303087842.txt.zip](https://github.com/d4rken/sdmaid-public/files/5296907/sdmaid_logfile_1601303087842.txt.zip)
> 
> Somehow I'm not able to upload video here so here is the drive link!
> https://drive.google.com/file/d/13i1R13Tfc9_SRk1wHUkNajt8M00FxAoA/view?usp=drivesdk
> 

Did you wipe data on SDMaid and set it up fresh? It finds cache for me on Oxygen OS 11 BETA 2.
Going to try to replicate and investigate some other 11 issues though. Probably mentioned here somewhere though.

**Comment by Kunzai1** [comment]
I'm not using beta! Mine is pixel 2 so i have the normal build but regardless of that this issue persists. I like this app but it doesn't have much use for me if it can't clean the app caches. I hope this gets fixed soon.

Please keep updating on any progress made!

**Comment by d4rken** [comment]
So the log shows

```kotlin
1601303098250  D/AppCleaner:Worker:ScanModule: Found 0 apps.
```

So there have been no apps found with any cache.
I think that this is negatively influenced by Android 11, limiting direct access to `Android/data`, but SD Maid can pull some info via "Usage statistics", do you have granted for SD Maid?
The general ACS based cleaning via accessibility service works for me on an Android 11 in German and English :thinking: .

**Comment by Kunzai1** [comment]
Well it seems accessibility based service is not working for me! I'm not sure about the "usage statistics" point here. I think the required permissions have been granted. Regardless, you got anything for me that i need to do?? Steps to enable or grant permission for something??

**Comment by d4rken** [comment]
The accessibility service just executes the deletion, but according to the log that never starts, because SD Maid doesn't find anything during the scan phase.

Check that in the AppCleaner settings that both "Show inaccessible items" and "Accessibility service" is enabled.
Also go into your system settings and see if SD Maid has been granted the "USAGE STATS" permission.

If that still does not work I might make a new version with extra logging around your issue to find out more details on why SD Maid doesn't think there is any cache.

**Comment by Kunzai1** [comment]
Everything was already enabled that you asked about but it didn't produce
any change so i did a clean install and enabled those two options only and
now it does the job. IT'S FINALLY DONE!

(Maybe one of the settings conflicts with the accessibility one, that's why
it was not working earlier).
