### ISSUE TITLE
Clutterreport: /storage/emulated/0/Pictures/Solar Walk 2 Free (FP)

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4058]
### Target
Target: `/storage/emulated/0/Pictures/Solar Walk 2 Free`
Prefix-free: `Pictures/Solar Walk 2 Free`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Solar Walk 2 Free`
Packagename: `com.vitotechnology.SolarWalk2Free`
Version: `1.6.3 (10603030)`

### Current owners
~~Appname: `Система Flyme`~~
~~Packagename: `android`~~
~~Version: `8.1.0 (27)`~~

Appname: `?`
Packagename: `com.sec.android.gallery3d`
Version: ` (-1)`

### SD Maid
Version: `4.15.15 (41515)`

### Device
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

### Comment
`Здесь сохраняются результаты.`

**Comment by d4rken** [comment]
:heart:  your reports, awesome !
