### ISSUE TITLE
Easier filtering of appcontrol data

### ISSUE THREAD

**Issue by dukelc** [d4rken/sdmaid-public#406]
In AppControll it would be nice to have separate columns for system and user apps.
When I set not to show system apps in settings, it scans all apps even system.
(And when shown both - system and user - its disorganized a bit)
So no settings for it, but only in AppControll two columns for user apps and system apps.
Just an idea - not a request.

**Comment by d4rken** [comment]
> When I set not to show system apps in settings, it scans all apps even system.

Can you further elaborate on that? Does the setting not work on your device?

> In AppControll it would be nice to have separate columns for system and user apps.

So like a viewpager, with tabs? Could you describe a usecase where this would benefit you?
Are you aware that you can type in "system" (differs with language) into the search field and then only see system apps?

**Comment by dukelc** [comment]
1. Do not show system app is ok. It shows only user apps. 
But what I mean is, that it need to scan all apps,even system,but system apps are not showen.
 It is ok. (system enabled-scan 133 apps.-show all) ( System disabled-scan 133 apps-show user apps only)

2. When I select show system,it is working all good,BUT when I need just user apps I need to go to settings to disable system apps.

3. Use - just more uncluttered without to write in search or go to settings to disable showing system apps when not needed.


![screenshot_20160611-192232](https://cloud.githubusercontent.com/assets/16635770/15986575/0a405c5e-300b-11e6-865b-d9be28914d20.png)

**Comment by d4rken** [comment]
> (system enabled-scan 133 apps.-show all) ( System disabled-scan 133 apps-show user apps only)

SD Maid needs to first determine that an app is a system app in order to be able to skip it. The setting affects whether SD Maid further processes an app once it is determined to be a system app.

> Use - just more uncluttered without to write in search or go to settings to disable showing system apps when not needed.

What about a drawer on the right side, like the explorer bookmarks. In the drawer you could have entries:

* All apps (100)
* System apps (40)
* User apps (60)
* Disabled apps (15)
etc.

Clicking on such an entry would filter the list. What do you think?

**Comment by dukelc** [comment]
Yes! 
That would be perfect!

**Comment by d4rken** [comment]
Great, I think that is a good new feature.
If you have more thoughts about it, let me know!

By the way, I love it when users make sketches of how they imagine a new feature would look :+1:
