### ISSUE TITLE
Bug: Accessibility Permission issue

### ISSUE THREAD

**Issue by theincognito-inc** [d4rken/sdmaid-public#4062]
### What happened?
In Android 11, SD Maid doesn't ask for Accessibility permission anymore, thereby the cleaning service gets stuck.

### What did you expect to happen?
Expected a popup asking for Accessibility permission info, just like the root permission popup/storage access popup.

### How can I reproduce the issue?
Just need to be on Android 11, sd maid fresh install, and try to do the quick cleaning.

### Comments
I guess SD Maid needs to be ported/optimized for 11?
### SD Maid
Version: `5.0.0 (50000)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/coral/coral:11/RP1A.200720.009/6720564:user/release-keys`

**Comment by d4rken** [comment]
Did you get a popup on Android 10?

**Comment by theincognito-inc** [comment]
I think so, yes. I used to get 3 popups on a fresh install, iirc.
Root popup, followed by storage access popup, followed by accessibility popup.

**Comment by d4rken** [comment]
Made the accessibility popup part of the setup flow, let's see how that works out.

**Comment by theincognito-inc** [comment]
@d4rken I'm still on Android 11. When you push the update, I will test and if it's not fixed, will comment here.

**Comment by theincognito-inc** [comment]
@d4rken Tested on 5.0.1. Working fine now. Thanks a lot!
