### ISSUE TITLE
Treat frozen app's folder as corpses?

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4071]
Возможно ли сделать,  чтобы при включённом пункте keeper в настройках CorpseFinder удалялись папки замороженных приложений? Если пользователь отключил приложение, то с большой долей вероятности оно ему не нужно, а папки остаются. Для безопасности можно сделать удаление этих папок только при включённом удалении keeper.

> Is it possible to make sure that when the keeper item is enabled in the CorpseFinder settings, the folders of frozen applications are deleted? If the user has disabled the application, then with a high degree of probability he does not need it, but the folders remain. For safety, you can delete these folders only when keeper deletion is enabled.

**Comment by d4rken** [comment]
I think it's too dangerous. While it might help a few users, in general most users don't want such behavior.
I will not add this, sorry.
