### ISSUE TITLE
Can't delete system app

### ISSUE THREAD

**Issue by randomname1234** [d4rken/sdmaid-public#410]
Device: Sony xperia z4 tablet (SGP712)

Android: 6.0.1 (no custom rom) 

root: yes. Rooted with SuperSU v2.74

SD Maid: 4.2.5

When I try to delete some system apps sd maid show me no error, but it doesn't really remove any folder/apk. 

Log: [http://hastebin.com/mivixoqupi.coffee](http://hastebin.com/mivixoqupi.coffee)

Could it be ? 
> 1465845871994 V/SDM:StreamHarvester: Error:rm: can't remove '/vendor/overlay/PhonebookRuntimeOverlay/PhonebookRuntimeOverlay.apk': Read-only file system
1465845871995 V/SDM:StreamHarvester: Error:rm: can't remove '/vendor/overlay/PhonebookRuntimeOverlay': Read-only file system

**Comment by d4rken** [comment]
Yeah SD Maid fails to remount `/vendor` which seems to be a read-only partition.

Further up the log we see:
```
1465845879960 D/SDM:FileForensics: Unknown location:/vendor/overlay/ConversationsRuntimeOverlay
1465845879960 V/SDM:FileForensics: Location: 1ms (UNKNOWN), Processing: 0ms, avg. 1ms (/vendor/overlay/ConversationsRuntimeOverlay)
```
Which means SD Maid doesn't understand that this is a specific location type. Resulting in SD Maid trying to remount the wrong location for deletion:

```
1465845871975 V/SDM:InteractiveShell: outStream|toolbox mount -o rw,remount / 
```

Can you get me a log from a fresh launch of SD Maid? I need to see the log part at the beginning where SD Maid detects the storage.

Aweome issue ticket btw :+1:

**Comment by randomname1234** [comment]
Thank you :smile: 

Now that you mention it, by tapping on the application in the AppControl list, it shows me the wrong path. 
It says: /vendor/overlay/appname 
while the correct path is: /system/vendor/overlay/appname

Full log: (just a second)

**Comment by randomname1234** [comment]
Also, don't know if it helps you but
Org.codeaurora.ims located in '/system/vendor/app/ims' doesn't create any problem. The process works fine, the path is correct and codeaurora can be removed.

**Comment by randomname1234** [comment]
Update: I just noticed there is a symlink on '/' named '/vendor' which redirect to '/system/vendor'. 

Sorry for repeated comments, I'm not using my pc

**Comment by d4rken** [comment]
It's unclear why one app would use a symlink via `/vendor` and directly uses `/system/vendor`.

```
1465847714297 D/SDM:PackageEstateSearcher: getBaseCodePath():/vendor/overlay/overlay-semcexperienceflow2-300-release.apk
1465847710912 D/SDM:PackageEstateSearcher: getBaseCodePath():/system/vendor/app/ims
```

We have options at different levels here:
* Detect this case in AppControl and replace the path internally, so although the path stored in Androids packagemanager points to `/vendor` SD Maid would use `/system/vendor`. Here I would have to check what other methods could be affected as the path might be used for comparison in other methods.
* Try to detect `/vendor` as specific storage location during storage setup, determine if it is a symlink. If it is a symlink we use the symlink target to find the partition. This should result in SD Maid detecting `/system` as base mount before reaching `/`. Might to change AppControl to also build data for the `Location.VENDOR` then.

Second option seems to be the way to go. It's more work, but the first one is kind of a workaround, while the second option correctly introduces the `/vendor` location into SD Maids core modules.

```
1465847706143 V/SDM:StreamHarvester: Output:rootfs on / type rootfs (ro,seclabel)
1465847706144 V/SDM:StreamHarvester: Output:tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=1417140k,nr_inodes=354285,mode=755)
1465847706144 V/SDM:StreamHarvester: Output:devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
1465847706144 V/SDM:StreamHarvester: Output:none on /dev/cpuctl type cgroup (rw,relatime,cpu)
1465847706144 V/SDM:StreamHarvester: Output:adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
1465847706145 V/SDM:StreamHarvester: Output:proc on /proc type proc (rw,relatime)
1465847706145 V/SDM:StreamHarvester: Output:sysfs on /sys type sysfs (rw,seclabel,relatime)
1465847706145 V/SDM:StreamHarvester: Output:selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
1465847706145 V/SDM:StreamHarvester: Output:debugfs on /sys/kernel/debug type debugfs (rw,seclabel,relatime)
1465847706145 V/SDM:StreamHarvester: Output:none on /sys/fs/cgroup type tmpfs (rw,seclabel,relatime,size=1417140k,nr_inodes=354285,mode=750,gid=1000)
1465847706145 V/SDM:StreamHarvester: Output:pstore on /sys/fs/pstore type pstore (rw,seclabel,relatime)
1465847706145 V/SDM:StreamHarvester: Output:securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
1465847706145 V/SDM:StreamHarvester: Output:none on /acct type cgroup (rw,relatime,cpuacct)
1465847706146 V/SDM:StreamHarvester: Output:tmpfs on /mnt type tmpfs (rw,seclabel,relatime,size=1417140k,nr_inodes=354285,mode=755,gid=1000)
1465847706146 V/SDM:StreamHarvester: Output:/dev/fuse on /mnt/runtime/default/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other,allow_utime_grp)
1465847706146 V/SDM:StreamHarvester: Output:/dev/fuse on /mnt/runtime/read/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other,allow_utime_grp)
1465847706146 V/SDM:StreamHarvester: Output:/dev/fuse on /mnt/runtime/write/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other,allow_utime_grp)
1465847706146 V/SDM:StreamHarvester: Output:tmpfs on /tmp type tmpfs (rw,seclabel,nosuid,relatime,size=1417140k,nr_inodes=354285,mode=755)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/system on /system type ext4 (ro,seclabel,noatime,discard,data=ordered)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/userdata on /data type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/oem on /oem type ext4 (ro,seclabel,noatime,data=ordered)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/cache on /cache type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,data=ordered)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/apps_log on /rca type ext4 (rw,seclabel,nosuid,nodev,noexec,noatime,discard,nobarrier,data=ordered)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/diag on /idd type ext4 (rw,seclabel,nosuid,nodev,noexec,noatime,discard,nobarrier,data=ordered)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/persist on /persist type ext4 (rw,seclabel,nosuid,nodev,relatime,data=ordered)
1465847706147 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/modem on /firmware type vfat (ro,context=u:object_r:firmware_file:s0,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro)
1465847706148 V/SDM:StreamHarvester: Output:/dev/block/bootdevice/by-name/LTALabel on /lta-label type ext4 (ro,context=u:object_r:lta_label:s0,nosuid,nodev,noexec,noatime,data=ordered)
1465847706148 V/SDM:StreamHarvester: Output:/dev/block/loop0 on /su type ext4 (rw,seclabel,noatime,data=ordered)
1465847706148 V/SDM:StreamHarvester: Output:tmpfs on /storage type tmpfs (rw,seclabel,relatime,size=1417140k,nr_inodes=354285,mode=755,gid=1000)
1465847706148 V/SDM:StreamHarvester: Output:/dev/fuse on /storage/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other,allow_utime_grp)
1465847706148 V/SDM:StreamHarvester: Output:tmpfs on /storage/self type tmpfs (rw,seclabel,relatime,size=1417140k,nr_inodes=354285,mode=755,gid=1000)
```

Some reading material:
**https://github.com/anestisb/android-prepare-vendor**
https://github.com/CyanogenMod/android_build/commit/5edc9e08ca395769f975dd817c38784a68b166b5
https://android.googlesource.com/platform/system/core/+/master/rootdir/init.rc#43
https://01.org/blogs/2015/android-customizing

**Comment by randomname1234** [comment]
Yeah, second option is the right thing to do.

Also, I noticed some leftover files of old uninstalled apps in '/system/etc/product/applications' . The only app which is still installed doesn't seem to have this directory listed in AppControl.

Not sure if it is related to the fact that there is a symlink named '/etc' which points to '/system/etc' or it is a totally different thing and I have to open a new issue

**Comment by d4rken** [comment]
Open another ticket for that.

Also note that if a system app gets updated, the installed app is coming from the updated apk file in userspace (e.g. /data/app), but the original apk in /system is still what gives it system app priviledges.
SD Maid removes the update on first uninstall and then it should show the app referencing the apk in /system.

I'll do some research on this issue, so far couldnt find a device with apps using these locations. Would probably be best if I send you a test version once I got something. If you want, send a mail to support referencing this and I'll get you a test apk once iI got one.

**Comment by d4rken** [comment]
@randomname1234 If you send me a mail I can give you a test build and you could confirm the fix if you want.

**Comment by randomname1234** [comment]
Sure, use this o001@libero.it

**Comment by d4rken** [comment]
From @randomname1234 

> Here is the [log](https://gist.githubusercontent.com/randomname1234/03598e4c5ae92ab531681fc51f927391/raw/66575a31c5a0c877883a976e97059734c4f0a7da/sdmaid_logfile_1466335382093.log)
> I also tried to delete an app located `/vendor` as you asked me for a log in the mail

Fix is confirmed, yay!
