### ISSUE TITLE
Bug: VSCO thumbnails has been cleared

### ISSUE THREAD

**Issue by qttc** [d4rken/sdmaid-public#4112]
### What happened?
Thumbnails of stored photos in VSCO deleting

### What did you expect to happen?
 The thumbnails of stored photos in VSCO shouldn't be clear after SdMain clean up

### How can I reproduce the issue?
1. Install VSCO 2. Import 1 photo 3. See the preview (thumbnail) of photo 4. Start up clean up in SD Main 5. Clean files after clean up scan 6. Open VSCO 7. Photo doesn't have a preview, it couldn't be fixed anymore, I have to re-upload photo

### SD Maid
Version: `5.0.0 (50000)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `Unknown`
Fingerprint: `Xiaomi/dipper/dipper:8.1.0/OPM1.171019.011/V9.5.5.0.OEAMIFA:user/release-keys`

**Comment by d4rken** [comment]
Which tool in SD Maid deletes the files?  Can you show me the path of the files?
Record a debuglog?

**Comment by qttc** [comment]
AppCleaner, I suggest.

I added com.vsco.cam at exclusions for Databases, SystemCleaner, AppControl AppCleaner, and CorpseFinder. Now it works well. But you should check the cause of that behavior.

**Comment by qttc** [comment]
Also, if you send me any guide or instruction how I can get logs from your app - I can do that to improve the app.

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
