### ISSUE TITLE
Improve AppControl share dialog dismiss behavior

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4158]
### What happened?
Если при отправке ссылок, указывающих на Google Play, в AppControl выбрать вариант Отменить или нажать мимо окна, чтобы его закрыть, то окно с предложением Отправить и Отменить будет все равно появляться даже после перезапуска SD Maid. Лучше чтобы окно появлялось только один раз, независимомо от того, куда пользователь нажал после этого.
Повторяется каждый раз.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5428847/video.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Should now only display once :+1: 
Fixed it for other dialogs and snackbars in AppControl too.
