### ISSUE TITLE
Explorer navigation bar not handling symlink properly

### ISSUE THREAD

**Issue by randomname1234** [d4rken/sdmaid-public#416]
Device: Sony xperia z4 tablet (SGP712) 
Android: 6.0.1 (no custom rom)
root: yes. Rooted with SuperSU v2.74
SD Maid: 4.2.5 

Let's say you have an app like smallbrowser (I'm starting hating this app), in AppControl the path points to `/data/user/0/com.sonymobile.smallbrowser`. If you open the directory in Explorer (by clicking on it from the AppControl) you will have `/data/user/0/com.sonymobile.smallbrowser` in the navigation bar. This allow you to access `/data/user/0` (by clicking 0 in the navigation bar) which returns "0 items" as 0 is a symlink in `/data/user` which points to `/data/data`

**Comment by d4rken** [comment]
After clicking the path in AppControl and the Explorer loading, the initial folder `/data/user/0/com.sonymobile.smallbrowser` shows correctly though, right?
What happens if you navigate down in that folder e.g. into `/files/`, does that work?

**Comment by randomname1234** [comment]
> After clicking the path in AppControl and the Explorer loading, the initial folder /data/user/0/com.sonymobile.smallbrowser shows correctly though, right?

yes

> What happens if you navigate down in that folder e.g. into /files/, does that work?

yes

The problem is when I try to access the symlink path, it doesn't redirect me to the path the symlink points to

**Comment by d4rken** [comment]
Maybe it's as simple as `if(file.isSymlink())`, I hope... Thanks should be enough to get me started on this.

**Comment by d4rken** [comment]
Wasn't as easy as I thought, but could improve the whole logic a bit in this change and it seems to also have improved navigation around /storage/*

Committed for next v4.2.7
