### ISSUE TITLE
Clutterreport: /storage/emulated/0/Flagg (new)

### ISSUE THREAD

**Issue by GingerGoddess78** [d4rken/sdmaid-public#4160]
### Target
Target: `/storage/emulated/0/Flagg`
Prefix-free: `Flagg`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `APKPure`
Packagename: `com.apkpure.aegon`
Version: `3.17.14 (3171411)`

### Current owners
None

### SD Maid
Version: `4.15.15 (41515)`

### Device
Fingerprint: `google/crosshatch/crosshatch:11/RP1A.201005.004/6782484:user/release-keys`

**Comment by d4rken** [comment]
Can you provide more info on this file?
