### ISSUE TITLE
Whitelisting apps for cleaning cache...

### ISSUE THREAD

**Issue by Sridhar-Ananthanarayanan** [d4rken/sdmaid-public#4168]
Long time user of SD Maid. 

With Android 11, access to the Android/ Data folder is no longer available for 3rd party apps, without root. Apps often store their cache in that folder. Earlier, I would add paths to apps in the Android/ Data folder in the Exclusions list if I want to whitelist apps whose cache I don't want cleared. Very useful for gallery, video players, file managers, etc. 

1. Is this no longer possible in Android 11 without root?
2. Is cache cleaning for apps even possible in Android 11 without root?

**Comment by d4rken** [comment]
> Is this no longer possible in Android 11 without root?

As far as I can currently tell, it's no longer possible without root on Android 11.
Even with an extra permission, that will be in SD Maid v5.1.0 (#3875), the `Android/data` folder is not accessible.

> Is cache cleaning for apps even possible in Android 11 without root?
If you use the accessibility service option, the deletion through the `Clear Cache` button should still clear the default caches in `Android/data`. SD Maid can't look for custom caches any more there though without root, only on the root of the sdcard (like those recyclebins you mentioned in another ticket).

So if you want to exclude apps from cache cleaning, even the accessibility service (ACS) based one, make sure to exclude the apps package name from the AppCleaner, i.e. via AppControl.

**Comment by Sridhar-Ananthanarayanan** [comment]
Thanks for the clarification.

Since apps like Gallery, video players, file managers, etc tend to cache files within their own data folders (which is inaccessible in Android 11), I guess whitelisting is no longer required. 

For example, Google Photos currently occupies about 1.7 GB on my internal storage, of which user data is about 850 MB and Cache is about 700 MB. Even without whitelisting, I don't think SD Maid will delete files from either of these two. Am I right?

**Comment by d4rken** [comment]
Not sure, will have to look that up. Depends on which filters are enabled in AppCleaner and SystemCleaner.
