### ISSUE TITLE
Improve ROM info in debug log

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#417]
Currently we only print Build.Fingerprint, which looks like this:
```
Fingerprint: samsung/d2uc/d2att:4.4.2/KOT49H/I747UCUFNJ2:user/release-keys
```
for a
```
Phone: SGH-i747 (AT&T Samsung GS3)
Rom: Official CM13 20160613 nightly
Android Version: 6.0.1
```

Going to flash CM13 to a test device and see what other information the `Build` class holds.

**Comment by randomname1234** [comment]
Have you tried using getprop ? 

I used it with adb in the past and then filter the results with grep.

**Comment by d4rken** [comment]
I have not, good idea. 
The question is whether it is available on every ROM and if it can be executed without root on every ROM. Note that an adb shell is different from an app shell.

**Comment by randomname1234** [comment]
I don't think you need root, /system is world-readable, so you can read build.prop information. [This one](https://play.google.com/store/apps/details?id=com.elusev.getprop) works without root.

Also, [this](http://forum.xda-developers.com/showthread.php?t=2375952) could be useful
