### ISSUE TITLE
The program runs slowly until it stops responding

### ISSUE THREAD

**Issue by Mapaler** [d4rken/sdmaid-public#4178]
Originally published at #4124, Now move to stand-alone issue.

---
I used outlook desktop tools.
![Screenshot_20201021-032427](https://user-images.githubusercontent.com/6565860/96636610-1d9be700-1350-11eb-8702-65c4a90229e8.png)
When I clean up the app, it stops at outlook.
![Screenshot_20201021-032417](https://user-images.githubusercontent.com/6565860/96636639-255b8b80-1350-11eb-81e5-f429ee9f1a53.png)
Sd maid then becomes slower and more inoperable until the system recommends stopping![Screenshot_20201021-033626](https://user-images.githubusercontent.com/6565860/96636650-2a203f80-1350-11eb-8fc1-a4e2ab6d2bcc.png)
I tried to remove the desktop tool, but it didn't help.The program also will still slow down to stop.

---

* device: LG v40(LM-V405UA)
* Android 9 (LG's version V405UA20a)
* Rooted with Magisk 20.4 (Manager 8.0.2)
* SD Maid v4.15.15, Unlocker v4.4.1
* install-id: aa987bae-ee68-4c6b-916c-3304d96846af
 
---
Log files exceed 500MB until the program stops.
I can only compress and upload to the network disk.
https://1drv.ms/u/s!AmFzz3_4XoK_g7By-Up2LcpXsSTA0g?e=kTi7fp

**Comment by Mapaler** [comment]
Outlook already has a 5.8GB cache before processing.
![Screenshot_20201025-135217](https://user-images.githubusercontent.com/6565860/97112841-953b8e80-1721-11eb-856b-082711a62f0b.png)

I cleared the cache and updated the version.
![Screenshot_20201025-140105](https://user-images.githubusercontent.com/6565860/97112843-98cf1580-1721-11eb-948c-5f4864b98ed9.png)

Then there was no more clean-up stop.
![Screenshot_20201025-140934](https://user-images.githubusercontent.com/6565860/97112847-9a98d900-1721-11eb-9775-eac50e164273.png)

This is the log file.
https://1drv.ms/u/s!AmFzz3_4XoK_g7Jkto-ysXOuyoQ6Cw?e=sUC9TS

**Comment by d4rken** [comment]
So the outlook cache was just too much for SD Maid.
I currently don't see an easy fix for this. :thinking: 
How much RAM does your device have?

**Comment by Mapaler** [comment]
2020-10-25 14:00 I cleaned outlook cache, but 2020-10-26 3:45, and it's got 2.72 GB again.
![Screenshot_20201026-034530](https://user-images.githubusercontent.com/6565860/97137888-dc616800-1791-11eb-9790-8972744b354e.png)
This time there was a long pause at outlook (about 20 minutes), but it finally passed.
![Screenshot_20201026-035227](https://user-images.githubusercontent.com/6565860/97137891-dd929500-1791-11eb-9650-57d046c386b2.png)
![Screenshot_20201026-040611](https://user-images.githubusercontent.com/6565860/97137894-de2b2b80-1791-11eb-89a8-d56c0579b911.png)
It took another 20 minutes to clean up.
![Screenshot_20201026-040823](https://user-images.githubusercontent.com/6565860/97137898-df5c5880-1791-11eb-9ad7-debe4a489e0d.png)
But the statistics don't seem to have been cleared successfully.
![Screenshot_20201026-042152](https://user-images.githubusercontent.com/6565860/97137901-e08d8580-1791-11eb-912d-ca655ad3c4f3.png)
![Screenshot_20201026-042201](https://user-images.githubusercontent.com/6565860/97137909-e1beb280-1791-11eb-94a2-d2bb3b8aab2f.png)
![Screenshot_20201026-042213](https://user-images.githubusercontent.com/6565860/97137912-e2efdf80-1791-11eb-8d0b-174e633f3741.png)
But it should actually be cleared.
![Screenshot_20201026-042243](https://user-images.githubusercontent.com/6565860/97137920-e6836680-1791-11eb-978e-d1344073fd5a.png)

---
2020-10-26 13:55, Now it's increased to 1.09 GB.
![Screenshot_20201026-135502](https://user-images.githubusercontent.com/6565860/97138336-ec2d7c00-1792-11eb-8e15-5f7b98877af0.png)

**Comment by Mapaler** [comment]
RAM is 6GB

**Comment by d4rken** [comment]
Currently can't offer a permanent solution except to delete it often or exclude it.

It just seems that you have a large mailbox and that the app caches a lot, there is nothing wrong with that AFAICT.

**Comment by Mapaler** [comment]
I don't have a large mailbox, it looks more like an outlook bug.
The new version, updated today, seems to solve this problem.
![Screenshot_20201029-000606](https://user-images.githubusercontent.com/6565860/97463523-cc58ac80-197a-11eb-8691-dcc535be556d.png)
