### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM/Video trimmer (FP)

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#4179]
### Target
Target: `/storage/emulated/0/DCIM/Video trimmer`
Prefix-free: `DCIM/Video trimmer`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Video trimmer`
Packagename: `com.samsung.app.newtrim`
Version: `2.4.23.1 (242301000)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `10 (29)`

Appname: `?`
Packagename: `com.meizu.media.gallery`
Version: ` (-1)`

### SD Maid
Version: `5.0.1 (50001)`

### Device
Fingerprint: `samsung/a70qeea/a70q:10/QP1A.190711.020/A705FNXXU5BTH4:user/release-keys`

**Comment by venhimadrid** [comment]
> ### Target
> Target: `/storage/emulated/0/DCIM/Video trimmer`
> Prefix-free: `DCIM/Video trimmer`
> Path-prefix: `/storage/emulated/0/`
> Type: `DIRECTORY`
> Location: `SDCARD`
> Current keeper state: `true`
> Suggested keeper state: `true`
> 
> ### Suggested owners
> Appname: `Video trimmer`
> Packagename: `com.samsung.app.newtrim`
> Version: `2.4.23.1 (242301000)`
> 
> ### Current owners
> Appname: `Android System`
> Packagename: `android`
> Version: `10 (29)`
> 
> Appname: `?`
> Packagename: `com.meizu.media.gallery`
> Version: ` (-1)`
> 
> ### SD Maid
> Version: `5.0.1 (50001)`
> 
> ### Device
> Fingerprint: `samsung/a70qeea/a70q:10/QP1A.190711.020/A705FNXXU5BTH4:user/release-keys`
