### ISSUE TITLE
App cleanup not worked again

### ISSUE THREAD

**Issue by bartekslowik** [d4rken/sdmaid-public#4181]
In issue #4124 I reported a problem in cleaning the application. I downloaded the beta version to verify the solution to the problem but encountered another problem.

My device is:
Samsung Galaxy A41 model SM-A415F
Android 10
One UI: 2.1

 Log in attachment
[sdmaid_logfile_1603705466713.txt.zip](https://github.com/d4rken/sdmaid-public/files/5438075/sdmaid_logfile_1603705466713.txt.zip)

Below a gif of the behavior of SD Maid

![GIF-b1dbb6d199bb54f3b71375be80257fd0](https://user-images.githubusercontent.com/73062944/97158628-0149e100-177a-11eb-90d4-6c3a40ebec60.gif)

what I noticed goes to the application options but does not click on "pamięć cache"  and does not clear the data

**Comment by d4rken** [comment]
SD Maid was looking for "Wyczyść pamięć podręczną", I've made changes for this ROM/language combination.
Report back after the next update.
