### ISSUE TITLE
Offer to export Activity.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4223]
Возможно нужно добавить экспорт Активити, в приложениях для создания Активити экспорт часто есть. Бывает мне нужно переустановить SD Maid во время поиска ошибок, и Активити приходится создавать заново. Можно сделать или в виде списка, который экспортируется, или просто при импорте все экспортированные  Активити автоматически создаются заново.

**Comment by d4rken** [comment]
Hm need sure what you mean, can you explain your idea further?

**Comment by Ingood5** [comment]
1 вариант: все ярлыки для Активити приложений, созданные пользователем, отображаются в SD Maid в виде списка. Список Активити можно экспортировать, чтобы в последствии импортировать и быстро создать ярлыки для тех же самых Активити заново.

2 вариант: списка нет, а есть просто функция экспорта, в последствии при импорте все ярлыки для Активити, экспортированные ранее, сразу автоматически создаются.

**Comment by d4rken** [comment]
Ok, I understand your idea now.

Unfortunately this is out of scope for SD Maid.
The benefit is too small and it is too complex to develop this feature.
