### ISSUE TITLE
SystemCleaner scan unsuccessfully

### ISSUE THREAD

**Issue by Easeman** [d4rken/sdmaid-public#423]
Hi, I'm new to Github.

SD Maid 4.2.5/4.2.6 Beta on Android 6.0.1 Nexus 6P(PureNexus build 6/21), Systemless Root

It takes forever for SystemCleaner to scan. Whatever I set the filter, the scan cannot finish. It seems that it gets stuck somewhere.

1. Start SystemCleaner scanning
2. Toast of granting root access from SuperSu, as usual
3. Everything seems fine
4. Another toast of granting root access from SuperSu
5. Scanning speed (op/s) starts to decrease
6. Speed continues to decreases and scanning process never finishs.

I don't know why this happens. Other function of SD Maid works fine.﻿

**Comment by d4rken** [comment]
Sounds like SD Maid gets stuck in a loop during search.
Please record a debug log of this happening:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

The log will tell us what exactly SD Maid is doing that's taking so long.

**Comment by Easeman** [comment]
I tried today and SystemCleaner just works fine. The issue seems to be gone. I will upload log when the issue occurs again.

**Comment by d4rken** [comment]
Ok, just reopen this then.
