### ISSUE TITLE
Settings Do Nothing

### ISSUE THREAD

**Issue by Trasd** [d4rken/sdmaid-public#424]
v4.2.7 Pro beta: all Settings do nothing.  Go to Settings, then further taps don't work.  Nothing happens.

Samsung Galaxy TabPRO SM-T900 12.2" with Android 5.1.1, unrooted.

**Comment by dukelc** [comment]
Galaxy s4 android 6.0.1, root, same.

**Comment by d4rken** [comment]
Proguard *sigh*, thanks for the report guys. Fix coming right up.
