### ISSUE TITLE
Another question about appcleanup

### ISSUE THREAD

**Issue by Tritium404** [d4rken/sdmaid-public#4267]
Hello, sir. Nice to meet you again.I noticed something special about the use of ”startWith” in inner filter.how's it working?Why is it useful to "endWith" ?I want to get to the bottom of this.`{
	  "packages": ["com.microsoft.emmx","com.android.chrome"],
	  "fileFilter": [
		{
		  "locations": ["SDCARD"],
		  "startsWith": ["Download/",".crdownload"],
		  "patterns": ["^(?:Download\\/)([\\W\\w]+?\\.crdownload)$"]
		}
	  ]
	}`

**Comment by d4rken** [comment]
Directly editing these files is not supported. I can't offer anymore help.

**Comment by Tritium404** [comment]
i edited for checking.and i have some spicific demand so i modified it directly.Cuz author can not satisfy everyone,doesn&#39;t it?I am sorry for my unrespective behaviors.And i will upload some fixed or new filter and new fixed SDCARD marked in my next spare time.I am verifying , don&#39;t go mad anymore.
---原始邮件---
发件人:&quot;Matthias Urhahn&quot;<notifications@github.com&gt;
发送时间:2020年11月15日 星期日 下午10:54
收件人:&quot;d4rken/sdmaid-public&quot;<sdmaid-public@noreply.github.com&gt;
抄送:&quot;tritium404&quot;<798485443@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;
主题:Re: [d4rken/sdmaid-public] Another question about appcleanup (#4267)



Closed #4267.

&mdash;
