### ISSUE TITLE
When cloning SD Maid, shortcuts for Activity disappear.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4274]
### What happened?
Если клонировать SD Maid встроенным в Meizu инструментом для клонирования приложений, то при запуске клона с главного экрана телефона исчезают ярлыки для  Активити, созданные с помощью SD Maid (не с помощью клона).

[sdmaid_logfile_1605582661768.txt.zip](https://github.com/d4rken/sdmaid-public/files/5551070/sdmaid_logfile_1605582661768.txt.zip)

### SD Maid
Version: `4.15.15 (41515)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
Cloning apps is not an officially supported. I can look into it though, but without access to a Meizu device, it will be difficult to debug.

Can you share `adb logcat` from the moment where the app was cloned, I'm interested in possibly error messages from the system or the Meizu cloning app.

**Comment by Ingood5** [comment]
Включил запись после клонирования, перед запуском клона SD Maid.

[logcat.txt](https://github.com/d4rken/sdmaid-public/files/5620406/logcat.txt)

**Comment by d4rken** [comment]
Doesn't look reasonably fixable, sorry :frowning: 

```
12-01 07:19:13.407   961   975 I ActivityManager: Force stopping eu.thedarken.sdm appid=10192 user=999: deletePackageX
12-01 07:19:13.408   961   975 I ActivityManager: Killing 20208:eu.thedarken.sdm/u999a192 (adj 700): reason: deletePackageX, stop eu.thedarken.sdm
12-01 07:19:13.416   961   975 I ActivityManager:   Force finishing activity ActivityRecord{30467ca u999 eu.thedarken.sdm/.main.ui.SDMMainActivity t99900002}
12-01 07:19:13.461   961   984 W ActivityManager: setHasOverlayUi called on unknown pid: 20208
12-01 07:19:13.882   961   999 I ActivityManager: Start proc 20344:com.android.defcontainer/u0a12 for service com.android.defcontainer/.DefaultContainerService
12-01 07:19:13.883   961   999 I ActivityManager: Force stopping eu.thedarken.sdm appid=10192 user=999: pkg removed
12-01 07:19:13.889   961   999 I ActivityManager: Force stopping eu.thedarken.sdm appid=10192 user=999: pkg removed
12-01 07:19:13.903   961   961 W ActivityManager: Unable to start service Intent { act=android.intent.ac
```

Looks like the cloning process triggers an uninstall broadcast which likely causes the launcher app to remove all shortcuts belonging to the removed app.
