### ISSUE TITLE
Clutterreport: /system/priv-app/Accessibility/Accessibility.apk (FP)

### ISSUE THREAD

**Issue by ladyraevyn55** [d4rken/sdmaid-public#4275]
### Target
Target: `/system/priv-app/Accessibility/Accessibility.apk`
Prefix-free: `Accessibility/Accessibility.apk`
Path-prefix: `/system/priv-app/`
Type: `FILE`
Location: `SYSTEM_PRIV_APP`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Accessibility`~~
~~Packagename: `com.samsung.accessibility`~~
~~Version: `10.0.04.15 (1000415000)`~~

### SD Maid
Version: `4.13.4 (41304)`

### Device
Fingerprint: `samsung/a10esq/a10e:9/PPR1.180610.011/A102USQU8ATJ1:user/release-keys`

**Comment by ladyraevyn55** [comment]
I can't get acessabilities to work at all,won't open crashes immediately and pops open window to close app or open to app menu...help

**Comment by d4rken** [comment]
Need more infos:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
