### ISSUE TITLE
4.2.9 multithreading no longer adjustable

### ISSUE THREAD

**Issue by jawz101** [d4rken/sdmaid-public#428]
Nexus 5.  Used to be able to use all 4 cores.  Now it defaults to 2 still even if I set to 4.  App restarts and still set to 2.

**Comment by d4rken** [comment]
Works for me on a Nexus5.
Try killing SD Maid, possibly the restart is not working correctly.

If that doesn't help lets start with a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

Note that the setting does not directly relate to how many cores SD Maid uses, just to how many workers may be active in parallel.

**Comment by jawz101** [comment]
I collected a debug log.  Can I email this to you?  I don't know if any of this is sensitive info

**Comment by jawz101** [comment]
I went ahead and emailed it.  I'm on a Nexus 5 as well.  Tried using both CyanogenMod 13 and Purity ROM(which is just a CM derivative

**Comment by d4rken** [comment]
There might be an issue with the automatic relaunch. As i think it's unexpected behavior anyways I've replaced it with a message that requests the user to manually restart SD Maid.

(Didn't see any sensitive info in the log)
[sdmaid_logfile_1467336315084.txt](https://github.com/d4rken/sdmaid-public/files/343176/sdmaid_logfile_1467336315084.txt)
