### ISSUE TITLE
The application has stopped working on my Samsung Galaxy S4 after the latest update

### ISSUE THREAD

**Issue by OleksandrShkurat** [d4rken/sdmaid-public#4307]
My SD Maid Pro has updated to 5.0.3
After the update, it's crashing each time I try to start the analysis.
The same crash appears on any other action including my attempts to open Settings section (I wanted to switch the language from my Ukrainian to English in order to make it easier for reading to you, however, it also doesn't work).
Thus, the screenshot will be in Ukrainian:
![image](https://user-images.githubusercontent.com/10740620/99781500-98f3e280-2b20-11eb-945d-3fccd56756d2.png)

The translation is:
"Error
The required file can't be set up. The execution is impossible.
Usually, it's could be caused by not complete root-permission. Please, check the settings of your device."

Everything else doesn't require translation.

Please fix it, as the application is totally blocked from being used.

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
