### ISSUE TITLE
Samsung Galaxy S5 Missing File Root Error Magisk

### ISSUE THREAD

**Issue by twindragon6** [d4rken/sdmaid-public#4309]
![Screenshot_2020-11-22-10-23-08](https://user-images.githubusercontent.com/37599898/99913549-28c69780-2cad-11eb-85f3-a5e86d260e57.png)
![Screenshot_2020-11-22-10-23-11](https://user-images.githubusercontent.com/37599898/99913558-31b76900-2cad-11eb-8c0a-cfedb9f00b25.png)
![Screenshot_2020-11-22-10-23-14](https://user-images.githubusercontent.com/37599898/99913562-38de7700-2cad-11eb-8a4e-00f23040852d.png)

![Screenshot_2020-11-20-07-54-55](https://user-images.githubusercontent.com/37599898/99828192-7c02e380-2b0f-11eb-971d-e8b49b16b3a2.png)
The application crashes at launch with this error. When I run the Pro Unlocker the application runs until I restart my phone. Also the database optimization part doesn't run correctly and fails at 17 databases.

**Comment by twindragon6** [comment]
https://android-doc.github.io/ndk/guides/abis.html#sa
The CPU is not supported in this build!
Hard float when specified as armeabi-v7a-hard. Incompatible with ARMv5, v6 devices.

**Comment by Siva981** [comment]
I am facing the same issue in my Android 5.0.1 phone. I am using the Pro version. Ever since SD Maid got updated to version 5.0.3, it throws this error page even when I try to open the Settings window. My phone is not rooted.

However, this issue seems to happen only if I move the SD Maid app to the external SD Card in my phone. It works alright if I move the app back to my phone's Internal Memory. Until this version 5.0.3, the app used to work alright even if I move the Main App to the SD Card, and keep the Unlocker App in the Internal Memory. 

Now, it throws this error page if I move the main app to the SD Card. 

Please do the needful.

**Comment by twindragon6** [comment]
> 
> 
> I am facing the same issue in my Android 5.0.1 phone. I am using the Pro version. Ever since SD Maid got updated to version 5.0.3, it throws this error page even when I try to open the Settings window. My phone is not rooted.
> 
> However, this issue seems to happen only if I move the SD Maid app to the external SD Card in my phone. It works alright if I move the app back to my phone's Internal Memory. Until this version 5.0.3, the app used to work alright even if I move the Main App to the SD Card, and keep the Unlocker App in the Internal Memory.
> 
> Now, it throws this error page if I move the main app to the SD Card.
> 
> Please do the needful.

That did the trick! Apparently V5.0.3 is not a moveable app anymore!
https://developer.android.com/guide/topics/data/install-location

**Comment by d4rken** [comment]
Did you move it through the system or with an extra app?

This is likely caused by https://github.com/d4rken/sdmaid-public/issues/2380

**Comment by Siva981** [comment]
> Did you move it through the system or with an extra app?
> 
> This is likely caused by #2380

I moved it through the system, via Settings --> Apps --> SD Maid --> Move To SD Card.

Android Version:    5.0.1
Model:    Swipe Elite Plus

**Comment by d4rken** [comment]
SD Maid does no longer support being moved to external storage, see #2380

**Comment by Tats528** [comment]
_Sent from my SM-S767VL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
