### ISSUE TITLE
Failure to open "Documents" Activity

### ISSUE THREAD

**Issue by dredd9877** [d4rken/sdmaid-public#432]
> OPEN_DOCUMENT_TREE.  ERROR 255.   CONTAINS EXTRA

It is not reading my ext_sd.       Probably have to format dose anyone have a solution I've flashes and wiped cached and decalvs.  And factory reset uninstalled installed this is the app I have not working. It's probably a error on my part would like to know how to fix for future use.

**Comment by d4rken** [comment]
SD Maid tries to open the Documents app which seems to fail.
This is a ROM issue, see:

https://github.com/d4rken/sdmaid-public/wiki/Setup#error-activity-not-found

Also see:
https://github.com/d4rken/sdmaid-public/wiki/Setup#secondary-storage-setup

**Comment by dredd9877** [comment]
Thanks I was pretty sure it was my fault love that by the way thanks

**Comment by d4rken** [comment]
@dredd9877 No worries, thanks for making a ticket. I'm happy about everyone using the issue tracker.
