### ISSUE TITLE
The time of the last update of applications changes, although the applications have not been updated.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4324]
### What happened?
Иногда в AppControl у приложений изменяется дата последнего обновления, хотя они не обновлялись. В последний раз это произошло у этих двух: 

![S01123-10144544](https://user-images.githubusercontent.com/60130882/99936924-655dc600-2d75-11eb-807c-bf8da0ca7384.png)
![S01123-10143753](https://user-images.githubusercontent.com/60130882/99936929-668ef300-2d75-11eb-9be5-5132f2e5eff5.png)

Это происходило два раза, каждый раз незадолго перед этим я менял дату в настройках телефона, возможно это связано с этим.

### SD Maid
Version: `5.0.3 (50003)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
This has already come up in a previous bug report where I already investigated this. SD Maid behaves correctly. The information coming from the system has the new date, SD Maid just displays it.

Unfortunately I did not find out why the date has changed, but this is an issue with the system. I can't fix this in SD Maid.
