### ISSUE TITLE
Not deleting all empty folders

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#433]
I'm noticing that SD Maid is not deleting all empty folders, especially nested empty folders.

I notice this in different tree areas, but particularly for folders within the `Android` folder in user storage.

Is this by design, or is it a bug?

Tested on KitKat.

**Comment by d4rken** [comment]
Basically this:
https://github.com/d4rken/sdmaid-public/issues/201

I've added some extra info to that ticket.
