### ISSUE TITLE
The schedule is reset when you reset the schedule settings.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4334]
### What happened?
При сбросе настроек расписания отключается само расписание. Если это не убирает возможные глюки расписания, из-за которых возможно пришлось бы переустановить SD Maid, то отключать расписание не надо.

### SD Maid
Version: `5.0.3 (50003)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
This is working as intended. The "current schedule" is also just a setting. 
The reset option sets everything to default, and the default also means "no active schedule".

**Comment by Ingood5** [comment]
Возможно, пользователь захочет сбросить дополнительные настройки расписания без отключения самого расписания. Само расписание он всегда может отключить вручную. Получается неявным, что при сбросе отключится и расписание, обычно при сбросе настроек сбрасываются только пункты, которые в самом окне настроек 🤔 Я сам с этим столкнулся, хотел сбросить настройки в окне, а позже оказалось, что отключил и само расписание.

**Comment by Ingood5** [comment]
Вы не пропустили?

**Comment by Ingood5** [comment]
Вы не пропустили?
