### ISSUE TITLE
Load folders immediately in Explorer

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#434]
When the user initially starts the Explorer from the side panel, they receive a mostly empty screen with a refresh button.

I recommend performing an initial refresh, as that is almost always the first step in whatever task the user is about to perform.

**Comment by d4rken** [comment]
Some thoughts:

True, but isn't that the case for any tool?

I don't like the idea of starting a potentially long running operation just by switching pages.

Starting an initial refresh would potentially also trigger a root check, Android 6.0 permission check as well as permission granting for secondary storage access, i.e. the whole setup.

For any tool that refreshes automatically on initial load, the tool description would never be visible.

**Comment by Gitoffthelawn** [comment]
Good points.

My experience is going to that tool, and then always having to hit the refresh button because the page is empty.  It usually takes under a second... just like loading Root Explorer, Solid Explorer, Ghost Commander, Total Commander, X-plore File Manager, or any other file explorer.

But maybe there are many cases where it takes much longer?  In those cases, if it starts automatically, it would need a *cancel* button.  What are those cases?

**Comment by Gitoffthelawn** [comment]
I'm not convinced either.

On the other hand, when using any other file explorer, even from a cold start, the files/folders are populated almost instantly without having to press a button to load the default directory.  It seems reasonable for SD Maid to be able to do the same when the user selects the *Explorer* tab.

**Comment by randomname1234** [comment]
> On the other hand, when using any other file explorer, even from a cold start, the files/folders are populated almost instantly without having to press a button to load the default directory.

True, I'm using Amaze (open source: [https://github.com/arpitkh96/AmazeFileManager](https://github.com/arpitkh96/AmazeFileManager) ) and a cold start in a folder like `/storage/emulated/0/.aptoide/icons` (706 files) on amaze is way faster than a **refresh** in sdmaid in the same folder

**Comment by d4rken** [comment]
It's the research regarding each file that takes so long, turn that off in the settings and it will also be pretty fast.

**Comment by randomname1234** [comment]
If you mean 'research owner', it's turned off, but still sdmaid requires 3,70s to perform a refresh, while amaze loads all the files in 1,92s on a cold start

**Comment by d4rken** [comment]
* Research owner
* SystemCleaner
* AppCleaner

Those 3 are additional research action that happen on every refresh if you want the extra icons on the row end.

The coldstart difference is currently unavoidable as there is no difference between the base conditions (setup) being done for the Explorer or for other tools.
If you do a debug run, most of the time is spent loading storage information (partitions, mounts, permissions).

We could discuss loading on page open as an extra option. This use case exists for every tool, so maybe as a general setting?

**Comment by randomname1234** [comment]
> Research owner
> SystemCleaner
> AppCleaner
> Those 3 are additional research action that happen on every refresh if you want the extra icons on the row end.

Ok, my bad, now is fast. Then wouldn't it be possible to simply perform a refresh without additional research on a cold start ? This wouldn't affect performance that much and the aim of retrieving the folders list would be achieved without any side effect.

**Comment by Gitoffthelawn** [comment]
> We could discuss loading on page open as an extra option. This use case exists for every tool, so maybe as a general setting?

Initially, I really like that idea.  But I want to give it some more thought.

**Comment by d4rken** [comment]
#187 adds the option for a home screen shortcut that opens the explorer and immediately loads the content. Would that help your usecase @Gitoffthelawn ?

**Comment by Gitoffthelawn** [comment]
Excellent question.

The answer is no, not with the current level of functionality within SD Maid's Explorer.

SD Maid's Explorer is rather limited, and that's okay, because it SD Maid excels in other areas.  I primarily use a full-featured file explorer (actually, more than one, because I haven't found **one** that has all the features I want).

I use SD Maid's Explorer as a convenience when I'm already in SD Maid, or on a device that doesn't currently have a full-featured file explorer installed (usually a temporary situation).

**Comment by d4rken** [comment]
By default nothing should be started, only get active upon user input.
We have #187 for the use-case of just wanting to use the explorer.
I don't think an extra option would be warranted at this point.
