### ISSUE TITLE
Restored settings cause app to clean without its permissions

### ISSUE THREAD

**Issue by sjoshua270** [d4rken/sdmaid-public#435]
I recently reset my phone to factory settings and had it restore SD Maid. Last night, the cleaning process was triggered, but the app did not have storage access. I had to force close the app and re-open it to grant the storage permission

**Comment by d4rken** [comment]
What behavior would you expect from SD Maid?

**Comment by sjoshua270** [comment]
If SD Maid could leave a notification mentioning that the permission had not been granted, that would be useful. This would only need to happen after a scheduled task fails. 

The problem is that all of the app's settings had been restored, and that caused the scheduled tasks to run even though I hadn't opened the app since the factory reset. They were trying to do their operations, but couldn't.

I had to force close the app from android settings before I was able to control the app again and grant the storage permission. Then everything ran fine.

**Comment by d4rken** [comment]
Did you reboot your device after restoring the app?
The reboot could have theoretically reinstantiated the alarm.
Though in the default state the boot receiver doing this should be disabled...
I'll look into that.

I'll probably add a notification that says something a long "Setup required".

> How did you restore SD Maid?

Titanium Backup?

**Comment by sjoshua270** [comment]
Oh I see what you mean by 'restore'. I didn't use anything like Titanium Backup. 
I set up my phone to restore from my previous setup (which Google had stored). 
I suppose the restore came from Google. I know that some developers have enabled their apps to backup data with Google. If you have enabled it in this app, my previous settings probably restored through that service.

**Comment by d4rken** [comment]
Hm I never neither enabled it nor disabled it, I think it's default=on since 6.0+.

**Comment by sjoshua270** [comment]
No, I think they disable it by default because of the way different apps handle/encrypt their data. 
Anyway, somehow my scheduled task was triggered before I opened the app to enable permissions. Thanks for the awesome app and thanks for being so responsive to feedback :)

**Comment by sjoshua270** [comment]
Here: I believe you have to register for it and set it up: https://developer.android.com/guide/topics/data/backup.html#BackupManifest

**Comment by d4rken** [comment]
Please post your device info and SD Maid version.

**Comment by d4rken** [comment]
Fix committed to v4.3.0
