### ISSUE TITLE
AppCleaner caught in a loop with "Cam Viewer" app.

### ISSUE THREAD

**Issue by Boothy99** [d4rken/sdmaid-public#4353]
Issue relates to -
AppCleaner (Hidden Caches enabled) and an app called "Cam Viewer" by Nextbase UK (dash cam manufacturer).

After the recent update to SD Maid Pro, I was more than pleased to find I can now use AppCleaner on my Xiaomi Mi 9T. Unfortunately, the only app it gets stuck on is "Cam Viewer". When AppCleaner reaches this app during it's cache cleaning, it gets stuck in a loop - repeatedly opening & closing it without success, and is unable to move on.

I've temporarily excluded "Cam Viewer" from AppCleaner, which allows it to then function as expected.

If you require any further information other than that listed below, I'll be happy to provide it.
Thanks again.

Mobile phone device: Xiaomi Mi 9T
MIUI version: 12.0.3 stable
Apps: All fully updated
Android: 10
Android Security Patch: 2020-10-01
SD Maid: 5.0.3 [50003]
Pro: Unlocker: 4.4.1
Root: false

**Comment by d4rken** [comment]
That's indeed very strange.

Can you please a debug log of this so I can see what SD Maid is seeing?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Boothy99** [comment]
Hello,
Well ... fortunately (or unfortunately as regards sending a bug report) - I 
removed Can Viewer from exclusions, and commenced a Bug Report run. Oddly 
... AppCleaner ran perfectly, cleaning Cam Viewer without issue  🤔🤨

So, whatever the cause was, it fixed itself. So ... apologies for taking up 
your time, after all that. I'll write in Github as resolved.

Thanks again - and apologies,
Dave.

**Comment by Boothy99** [comment]
Iss resolved itself after removing Cam Viewer from exclusions.
