### ISSUE TITLE
Должен ли SD Maid игнорировать файлы?

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4355]
В папке приложения для создания видео с эффектами (com.da.fxdirector) есть файлы, помеченные как файлы мусора macOS. Нужно ли, чтобы SD Maid их игнорировал?

[pathdump#_storage_emulated_0_MovieFxDirectorMagicTai_source_effect#1606825426337.txt](https://github.com/d4rken/sdmaid-public/files/5622555/pathdump._storage_emulated_0_MovieFxDirectorMagicTai_source_effect.1606825426337.txt)

**Comment by d4rken** [comment]
I don't think SD Maid should ignore them. The files serve no purpose there.

I think the developer of the app uses a computer with MacOS and accidentally included these files in the final APK :smile:

**Comment by Ingood5** [comment]
Такое впечатление что файлы загружаются из интернета 🤔 При выборе в приложении нового видеоэффекта он загружается из интернета, в этот момент в папке __MACOSX появляются новые папки со множеством файлов.
