### ISSUE TITLE
Optimise databases shows same two failures

### ISSUE THREAD

**Issue by tinydynamite00** [d4rken/sdmaid-public#436]
@d4rken Same '2 fails' appear after optimising databases on two separate devices: shamu; LG d801. The package ID  is <code>com.android.providers.contacts</code> in both cases. SD Maid reports _Not possible_ next to the scan's result entries. [See screenshots]

> The db affected are as follows:
<code>$PATH</code>='/data/user/0/com.android.providers.contacts/databases/contacts2.db'
<code>$PATH</code>='/data/user/0/com.android.providers.contacts/databases/profile.db'

**Error**: no such collation sequence: PHONEBOOK. 

**Running Beta channel v4.2.12 on shamu, release v4.2. 11 on d801

Expected behaviour: SDM terminates with 0 fails

![screenshot_20160710-145707](https://cloud.githubusercontent.com/assets/6479505/16745075/7b9eb062-4771-11e6-8ab9-b5fb60e0392e.png)

![screenshot_20160710-145729](https://cloud.githubusercontent.com/assets/6479505/16745132/ad23a6e2-4771-11e6-8fed-90c97588ec9b.png)

![screenshot_20160710-145737](https://cloud.githubusercontent.com/assets/6479505/16745147/bf50d934-4771-11e6-97df-9190b5811b37.png)

**Comment by d4rken** [comment]
AFAIK there is no way for SD Maid to reasonably handle such databases. If you look up the error message, at least I came to the conclusion that I would need specific knowledge of each database to deal with extra collation sequences, possibly building sqlite binaries with support per individual non default collation sequence, which is unreasonable.

Unless you know a solution for this, the only thing we can change is how SD Maid displays or handles such a case.

**Comment by tinydynamite00** [comment]
I hold no expectation that SD Maid should, will or needs to optimise my contacts database but it tries and it fails. This is relative to beta testing, thus I wanted to bring the matter to your attention, as it has been persistent across new releases - beta and production channels - for some time; though I've not had the time to report the issue. 

I'm not a programmer by any stretch of the imagination. However, in computing, job management more specifically, I suspect the objective for any task or a task's exit status is that it be 0; preferable over an error exit code. I may be wrong in my assumption. 

Moreover, if this is a matter of SD Maid needing to jump through extraordinarily lengthy regular expressions, concatenating obscure strings or any such outside the app's scope, then simply change the handling of the case in point. 

It really is a negligible problem, mostly cosmetic. Still, I'd be content to see it go away.

**Comment by d4rken** [comment]
> as it has been persistent across new releases - beta and production channels - for some time

Yeah, this basically existed since the introduction of the database tool, what changed is the amount of details displayed to the user.

> I'm not a programmer by any stretch of the imagination. However, in computing, job management more specifically, I suspect the objective for any task or a task's exit status is that it be 0; preferable over an error exit code. I may be wrong in my assumption. 

I totally agree, sometimes, like in this case, trying it is just the most efficient way.

> Moreover, if this is a matter of SD Maid needing to jump through extraordinarily lengthy regular expressions, concatenating obscure strings or any such outside the app's scope, then simply change the handling of the case in point. 

This is basically outsourced by SD Maid, the whole database operations are done by an default sqlite binary you also find on some systems by default, which SD Maid just calls upon. The operation fails fairly quickly so this is not a huge impact on resources.

> It really is a negligible problem, mostly cosmetic. Still, I'd be content to see it go away.

You are not the only one, I've had people complaining about this, though most just assumed SD Maid was doing something wrong when it was just being more honest :frowning: .

AFAIK this only happens for the two apps you listed. I propose we add a default (but removable) exclusion for those two apps from the databases tools. What do you think?

**Comment by tinydynamite00** [comment]
Yes, you are right, it is only the two reported databases that are affected. There are so many entries in the issue tracker I didn't see any clear way to sift through all of them to verify this rather minor hiccup had been reported before. 

At the same time, I couldn't imagine being the only user affected. The fact others have reported this before eases my apprehensions that the database optimisation output was in some way the result of user error.

Your proposal sounds right on point! I would be less hesitant myself if I had more confidence in my basic scripting abilities. 

Although, now confronted with a challenge, I will attempt to add a simple exclusion to the database scan based on the paths provided in my OP - before you push an update for SD Maid with an exclusion of your own. 😉 Besides, I need to get over the baseless fear I have of scripting in general.

Thanks so much for your work! That is something I have no problem stating without end. Your tireless work on SD Maid is the sole impetus I needed to invest in another Pro key for a secondary device. 

Thank you, again, for taking time to respond and explain the situation.

**Comment by d4rken** [comment]
> Although, now confronted with the challenge, I will attempt to add a simple exclusion in the database settings based on the paths provided in my OP

As simple as long pressing an entry and selecting "Add exclusion".

>before you push an update for SD Maid with an exclusion of your own. :wink: Besides, I need to get over the baseless fear I have of scripting in general.

I will be adding one anyways as people keep bringing it up as a failure on SD Maids part.

**Comment by d4rken** [comment]
Reopening this so I don't forget to implement the default exclusion.

**Comment by tinydynamite00** [comment]
Thank you @d4rken! Very much appreciated. (=
