### ISSUE TITLE
How do I track rare bugs? 

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4360]
Как отследить редкие ошибки? Например, бывает при отправке отчёта при нажатии значка со стрелкой в верхнем правом углу окно полностью зарывается вместо открытия браузера. Бывают другие подобные ошибки, когда при определённом действии вместо перехода к следующему окну все сбрасывается и SD Maid выглядит, как будто только что запущен, то есть сбрасываются загруженные папки в проводнике и т.д. Это относительно редкие ошибки, не получится запускать запись лога при каждом запуске SD Maid.

**Comment by d4rken** [comment]
Difficult. Best way is always to have steps how to reproduce it every time.
If that's not possible then it depends on the issue. For AppCleaner problem it's often good to get a debug log from SD Maid itself.

> For example, it happens when sending a report when you click the arrow icon in the upper right corner, the window is completely closed instead of opening the browser. 

For this problem `adb logcat` would be good, to see if the system shows an error. Maybe it is related to how much text we are trying to pass to the browser?

> here are other similar errors when, at a certain action, instead of going to the next window, everything is reset and SD Maid looks as if it has just been launched, that is, the loaded folders in the explorer are reset, etc.

This sounds like the system wanted more free memory and removed SD Maid's process when it was not on screen.

**Comment by Ingood5** [comment]
> For this problem adb logcat would be good, to see if the system shows an error. Maybe it is related to how much text we are trying to pass to the browser?

Проверил. Если отправить слишком длинный текст, браузер сообщает, что слишком длинное имя, ошибка не возникает. Насколько помню, было связано не с длиной текста. Я отправлял отчёт о найденной папке (возможно было и при отправке отчёта об ошибке), возникала ошибка, после этого отправлял повторно (возможно иногда текст был идентичен, т.е. скопирован, но не уверен), второй раз отправлялось без ошибок. Текст был не больше нескольких строк. Ошибка стала появляться часто, иногда 2-3 раза в день. После переустановки SD Maid возникла всего 1-2 раза за два месяца.

> This sounds like the system wanted more free memory and removed SD Maid's process when it was not on screen.

Это происходило, когда SD Maid был открыт, сразу после выбора определённого действия.

**Comment by d4rken** [comment]
I'm not sure what I can do here.

**Comment by Ingood5** [comment]
Попробую записать adb logcat или log SD Maid если проблемы опять появятся. Для чего нужен install ID? Он не помогает отследить ошибки с помощью отправленных с устройства отчётов о сбоях?

**Comment by d4rken** [comment]
> Попробую записать adb logcat или log SD Maid если проблемы опять появятся. Для чего нужен install ID? Он не помогает отследить ошибки с помощью отправленных с устройства отчётов о сбоях?

Yes.
All automatically collected data is anonymous. To find the data for a specific device, I need to know the install ID.

**Comment by Ingood5** [comment]
Install ID не поможет найти вышеуказанные ошибки? Вышеназванная ошибка, происходящая во отправке отчёта, после последней переустановки SD Maid несколько раз возникала.

Install ID 
017ed435-c04d-4128-962c-c9a93ff794d3

**Comment by Ingood5** [comment]
Заметил что Install ID не прикрепляется к отчёту при отправке отчёта из SD Maid. Возможно, нужно сделать чтобы Install ID отправлялся в отчёте.

**Comment by d4rken** [comment]
The install ID will be in a generated debuglog:
```
1610958171629  I/Debug:InstallID: Install-ID: ...............
```

but it will only help me to filter automatic bug reports.
Automatic bug reports are usually errors that crash the app.
