### ISSUE TITLE
Bug: Непонятный пункт в AppCleaner.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4367]
### What happened?
Если в настройках SD Maid отключить службу специальных возможностей, но оставить включённым отображение недоступных элементов, то в AppCleaner появится пункт в виде восклицательного знака, при нажатии на который, по видимому, должно открыться меню в настройках телефона, в котором можно очистить недоступный кэш вручную. 

![S01205-11250501(1)](https://user-images.githubusercontent.com/60130882/101238039-8e277900-36ee-11eb-9289-70e309e3a24b.png)

На моём телефоне очистка кэша происходит с помощью встроенного чистильщика, который находится в приложении Безопасность. Для перехода к нему после нажатия на восклицательный знак в открывшемся окне нужно нажать ещё раз на пункт вверху:

![S01205-11252529(1)](https://user-images.githubusercontent.com/60130882/101238078-caf37000-36ee-11eb-96a0-3f640d710341.png)

Возможно нужно сделать, чтобы при нажатии на восклицательный знак сразу открывался встроенный чистильщик.

### SD Maid
Version: `5.0.3 (50003)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by d4rken** [comment]
There is only an official way to get to the current screen. How to get to the second screen (the security cleaner app on your device), will be different for every device. I don't want to maintain a list of every security app on every phone and how to get to it.
