### ISSUE TITLE
Corpse Finder no longer works

### ISSUE THREAD

**Issue by goodboi69** [d4rken/sdmaid-public#4374]
Google Pixel 3 with Android 11 and the latest SD Main Pro.

I have found that the Corpse Finder is no longer working. Every time I run it, it returns zero results when I know there is.

**Comment by d4rken** [comment]
Please provide details on what SD Maid is missing.

**Comment by goodboi69** [comment]
> 
> 
> Please provide details on what SD Maid is missing.

I have tons of empty folders and SD Maid doesn't pick them up. This makes me wonder what else it's not picking up.

**Comment by d4rken** [comment]
That answer does not help me fix anything.
