### ISSUE TITLE
Exit toast has black font

### ISSUE THREAD

**Issue by TWiStErRob** [d4rken/sdmaid-public#438]
Minor UI cosmetic issue:
![screenshot_2016-07-16-15-27-10](https://cloud.githubusercontent.com/assets/2906988/16895074/16ec4c0e-4b6a-11e6-8c13-896b592b4845.png)

**Comment by d4rken** [comment]
Thanks for the report.
What ROM / device is this?
It doesn't look like the default toast message theme at all.

Is this a recent issue or has it always been the case?

**Comment by TWiStErRob** [comment]
I don'k now if it's changed since earlier versions, it's a brand new stock Galaxy S5 Andorid 5.0.

You might be using a custom view for it, because the device default doesn't look like that: In my app, I have black text on white and the corners are not that rounded (quickly added a toast to my app):
![image](https://cloud.githubusercontent.com/assets/2906988/16900689/3b675d86-4c2c-11e6-8591-191e016817f4.png)

I'm using a theme that extends `Theme.AppCompat.Light`, but it looks the same with `Theme.AppCompat` (above is with latter).

**Comment by d4rken** [comment]
Found it. I'm using the the base context which AFAIK doesn't get a theme applied.
Not sure why, probably a typo.

```
Toast.makeText(getBaseContext(), R.string.double_tap_to_exit, Toast.LENGTH_SHORT).show();
```

**Comment by TWiStErRob** [comment]
Huh, you're right; that's good to know, here's test for posterity:
```java
Toast.makeText(getApplicationContext(), "app", Toast.LENGTH_LONG).show();
Toast.makeText(this, "this", Toast.LENGTH_LONG).show();
Toast.makeText(this.getBaseContext(), "base", Toast.LENGTH_LONG).show();
```
![image](https://cloud.githubusercontent.com/assets/2906988/16900786/b93bc38e-4c2f-11e6-94a5-fb8afd840e9a.png)
![image](https://cloud.githubusercontent.com/assets/2906988/16900789/c767c37c-4c2f-11e6-80a7-cfa0aab88af2.png)
![image](https://cloud.githubusercontent.com/assets/2906988/16900793/d367a5e8-4c2f-11e6-8688-43d8d9056166.png)

**Comment by d4rken** [comment]
:+1: Are those just screenshots or do you have a cool tool for these tests :)?

I'm suprised by the difference between the application context and the activity though...

**Comment by TWiStErRob** [comment]
Yeah, the activity and application should look the same, especially since they have the same theme.
I just put those 3 lines into my main activity and took 3 shots quickly, no magic tool (except maybe IrfanView for cropping).

**Comment by d4rken** [comment]
On my N9@Nougat & N5@6.0 all 3 cases look the same (case "this).
Don't have a Samsung device at hand atm.
Definitely interesting.

Guessing: TouchWiz overrides the APP theme/styles somewhere but not the ACTIVITY theme/styles? Maybe this is a bug in TouchWiz where they forgot to alter all necessary styles?
