### ISSUE TITLE
[Critical] Fix ACS Support caused by MIUI 11+

### ISSUE THREAD

**Issue by JeffHorinzon** [d4rken/sdmaid-public#4386]
UPDATE 4th January: PLEASE READ THE NEXT POST FOR THE CURRENT FIX.

Hey there!  Fellow readers!  It's ya boi back at it again.  So, like I expected from issue #2816 , Mi Developers broke SDMaid again.  So, D4rken asked me to create a new issue dedicated to fixing the issue.  This issue should aim to fix users from MIUI 11 up to latest 12.0.1 (as of writing).  

From his observations from a logcat from my usual test device (Redmi Note 7, Lavender), it seems that MIUI System has killed Accessibility access for SDMaid after killing the app through multitasking.  From his perspective is seen as "forcefully closed/crashed".  Hence the need to reboot to get it working once again, only to have it not work after closing again from multitask.

D4rken requests a logcat so he can observe the Android system behaviors in MIUI for him to code his way around this issue.

**WARNING BEFORE YOU PROCEED: ADB Logcat will (probably) expose sensitive data as third party apps can just YEET whatever they want into the logs, which may or may not contain your sensitive info.  Please perform your contributions in a completely separate environment (basically a similarly affected phone with not much sensitive data that could be exposed).**  

Steps to create it:
Step 1 - Get phone (duh)
<img src="https://user-images.githubusercontent.com/3746534/101896842-8f700e80-3be4-11eb-89de-fc1e193028a8.JPEG" width="400">

Step 2 - Install ADB in computer
[Here's a link on how to do it](https://www.xda-developers.com/install-adb-windows-macos-linux/) (DM me on SDMaid Discord server if you need help)
<img width="600" alt="downloadadb" src="https://user-images.githubusercontent.com/3746534/101896954-c0e8da00-3be4-11eb-927b-5ba40f67d2af.PNG">

Step 3 - Get phone cable and sticc it into your phone and PC
<img src="https://user-images.githubusercontent.com/3746534/101896976-ca724200-3be4-11eb-9d83-166a08a11e45.JPEG" width="400">
_mmyes_

Step 4 - Turn on [developer options > USB Debugging]
<img src="https://user-images.githubusercontent.com/3746534/101897144-0e654700-3be5-11eb-8783-699ae2cacd39.jpg" width="400">
(If you can't find it, go to About Phone and find the Build Number and tap it 7 times)

Additional Settings >
<img src="https://user-images.githubusercontent.com/3746534/101897056-eb3a9780-3be4-11eb-8ebb-a7d6b91cb56d.jpg" width="400">
Developer Options >
<img src="https://user-images.githubusercontent.com/3746534/101897099-fd1c3a80-3be4-11eb-9fdb-8d9ac4a205e7.jpg" width="400">
USB Debugging ON
<img src="https://user-images.githubusercontent.com/3746534/101897125-05747580-3be5-11eb-8246-38596233e028.jpg" width="400">

Step 5 - Go to command prompt (if you've not set your ADB as [Environment PATH] then open it from the folder you had adb in) and type [adb devices] to make sure you can find your phone.
<img width="600" alt="adb device" src="https://user-images.githubusercontent.com/3746534/101900236-1f648700-3bea-11eb-9b7f-7f580a7a61d9.PNG">

Step 6 - Start debug logging in your SDMaid App
Follow the steps in [HERE](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) to access the debug screen.  If you do it right, you'll see this.  Then, press [RECORD DEBUG LOG].
<img src="https://user-images.githubusercontent.com/3746534/101905171-f516c780-3bf1-11eb-8fd6-75686554b400.jpg" width="400">

Step 6 - Return to your PC command prompt and type [adb logcat -f /storage/emulated/0/meow.txt] (meow.txt is just name of my choice OwO)
<img width="600" alt="adb logcat1" src="https://user-images.githubusercontent.com/3746534/101903321-0f9b7180-3bef-11eb-89bf-5a7d84f05bd8.PNG">

Step 7 - Recreate the problem
Perform whatever is it you're doing to cause the problem.  (You have to start logging from when it was ok until you created the problem to make it count)
<img src="https://user-images.githubusercontent.com/3746534/101903978-1a0a3b00-3bf0-11eb-98a8-3952a6bca172.jpg" width="400">
(Picture is just for reference only, not submission material)

Step 8 - Press Ctrl + C on the command prompt to stop logging
<img width="600" alt="adb logcat" src="https://user-images.githubusercontent.com/3746534/101903273-feeafb80-3bee-11eb-9deb-dfeb1db5c799.PNG">

Step 9 - Find the files in your phone in the previously mentioned directory (/storage/emulated/0/meow.txt) and SDMaid's log folder (/storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_somenumbers1231231.txt) using the File Manager.
<img src="https://user-images.githubusercontent.com/3746534/101904021-2b534780-3bf0-11eb-9026-8919e369dc66.jpg" width="400">
<img src="https://user-images.githubusercontent.com/3746534/101905817-ff859100-3bf2-11eb-96d6-dac7efe4fba5.jpg" width="400">

Step 10 - Send it here with the following format:
OS Version: (Insert MIUI version and Android version)
SDMaid Version: (Insert SDMaid version)
System Language: (what is the language you were using? (and optionally if you know, you can include the locale code))
[Then drag and drop the files to upload the file into the box.]
Example:
<img width="600" alt="uploadgithub" src="https://user-images.githubusercontent.com/3746534/101906030-4b383a80-3bf3-11eb-9f8f-3cb022dd5de9.PNG">

Should we need more info from you, we'll ask from you on this same thread.  Your contribution is greatly appreciated, thanks for helping :)

**Comment by JeffHorinzon** [comment]
According to #4345 , D4rken states that it is more of the third party manufacturer's issues than SDMaid's.  And here I've found a solution to it.  This is needed for every MIUI users, do once and forget.

Step 1: Open App Info of SDMaid
<img src="https://user-images.githubusercontent.com/3746534/103486439-f2963f00-4e38-11eb-975f-8e0075c6390f.jpg" width="400">

Step 2: Enable Autostart
<img src="https://user-images.githubusercontent.com/3746534/103486456-0cd01d00-4e39-11eb-90b6-9646f68e4d5e.jpg" width="400">

Optional step (Sanity check): Reboot device and have fun :)

Backstory: D4rken discussed with me privately and suspected the built in Battery Saver was causing the issue.  However, on my test device (Redmi Note 7, Lavender, 12.0.1), the main battery saver wasn't even on.  Though, I spotted that SDMaid was set as Battery Saver for "Background settings" but that didn't change anything either.  Until I found that Autostart solves the problem.  My personal suspicion (without reading the logs lol) is that the ACS service for SDMaid didn't actually close (as intended) when ended with multitasking.  Hence, allowing AppCleaner to run using the same unrevoked permission given at boot (because autostart is on).

Note to D4rken: I've tried this multiple times across multiple reboots and they all work.  If you need the logs, do lemme know on Discord.  If there's nothing else, you may close this ticket and reference this ticket to all MIUI users facing the same issue.

**Comment by JeffHorinzon** [comment]
Issue closed as it is an unfixable issue from SDMaid's end but rather MIUI Developer's end.  The temporary fix above is still valid as of closing this issue.

**Comment by maganezf** [comment]
> UPDATE 4th January: PLEASE READ THE NEXT POST FOR THE CURRENT FIX.
> 
> Hey there! Fellow readers! It's ya boi back at it again. So, like I expected from issue #2816 , Mi Developers broke SDMaid again. So, D4rken asked me to create a new issue dedicated to fixing the issue. This issue should aim to fix users from MIUI 11 up to latest 12.0.1 (as of writing).
> 
> From his observations from a logcat from my usual test device (Redmi Note 7, Lavender), it seems that MIUI System has killed Accessibility access for SDMaid after killing the app through multitasking. From his perspective is seen as "forcefully closed/crashed". Hence the need to reboot to get it working once again, only to have it not work after closing again from multitask.
> 
> D4rken requests a logcat so he can observe the Android system behaviors in MIUI for him to code his way around this issue.
> 
> **WARNING BEFORE YOU PROCEED: ADB Logcat will (probably) expose sensitive data as third party apps can just YEET whatever they want into the logs, which may or may not contain your sensitive info. Please perform your contributions in a completely separate environment (basically a similarly affected phone with not much sensitive data that could be exposed).**
> 
> Steps to create it: Step 1 - Get phone (duh) <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101896842-8f700e80-3be4-11eb-89de-fc1e193028a8.JPEG">
> 
> Step 2 - Install ADB in computer [Here's a link on how to do it](https://www.xda-developers.com/install-adb-windows-macos-linux/) (DM me on SDMaid Discord server if you need help) <img alt="downloadadb" width="600" src="https://user-images.githubusercontent.com/3746534/101896954-c0e8da00-3be4-11eb-927b-5ba40f67d2af.PNG">
> 
> Step 3 - Get phone cable and sticc it into your phone and PC <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101896976-ca724200-3be4-11eb-9d83-166a08a11e45.JPEG"> _mmyes_
> 
> Step 4 - Turn on [developer options > USB Debugging] <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101897144-0e654700-3be5-11eb-8783-699ae2cacd39.jpg"> (If you can't find it, go to About Phone and find the Build Number and tap it 7 times)
> 
> Additional Settings > <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101897056-eb3a9780-3be4-11eb-8ebb-a7d6b91cb56d.jpg"> Developer Options > <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101897099-fd1c3a80-3be4-11eb-9fdb-8d9ac4a205e7.jpg"> USB Debugging ON <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101897125-05747580-3be5-11eb-8246-38596233e028.jpg">
> 
> Step 5 - Go to command prompt (if you've not set your ADB as [Environment PATH] then open it from the folder you had adb in) and type [adb devices] to make sure you can find your phone. <img alt="adb device" width="600" src="https://user-images.githubusercontent.com/3746534/101900236-1f648700-3bea-11eb-9b7f-7f580a7a61d9.PNG">
> 
> Step 6 - Start debug logging in your SDMaid App Follow the steps in [HERE](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) to access the debug screen. If you do it right, you'll see this. Then, press [RECORD DEBUG LOG]. <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101905171-f516c780-3bf1-11eb-8fd6-75686554b400.jpg">
> 
> Step 6 - Return to your PC command prompt and type [adb logcat -f /storage/emulated/0/meow.txt] (meow.txt is just name of my choice OwO) <img alt="adb logcat1" width="600" src="https://user-images.githubusercontent.com/3746534/101903321-0f9b7180-3bef-11eb-89bf-5a7d84f05bd8.PNG">
> 
> Step 7 - Recreate the problem Perform whatever is it you're doing to cause the problem. (You have to start logging from when it was ok until you created the problem to make it count) <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101903978-1a0a3b00-3bf0-11eb-98a8-3952a6bca172.jpg"> (Picture is just for reference only, not submission material)
> 
> Step 8 - Press Ctrl + C on the command prompt to stop logging <img alt="adb logcat" width="600" src="https://user-images.githubusercontent.com/3746534/101903273-feeafb80-3bee-11eb-9deb-dfeb1db5c799.PNG">
> 
> Step 9 - Find the files in your phone in the previously mentioned directory (/storage/emulated/0/meow.txt) and SDMaid's log folder (/storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_somenumbers1231231.txt) using the File Manager. <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101904021-2b534780-3bf0-11eb-9026-8919e369dc66.jpg"> <img alt="" width="400" src="https://user-images.githubusercontent.com/3746534/101905817-ff859100-3bf2-11eb-96d6-dac7efe4fba5.jpg">
> 
> Step 10 - Send it here with the following format: OS Version: (Insert MIUI version and Android version) SDMaid Version: (Insert SDMaid version) System Language: (what is the language you were using? (and optionally if you know, you can include the locale code)) [Then drag and drop the files to upload the file into the box.] Example: <img alt="uploadgithub" width="600" src="https://user-images.githubusercontent.com/3746534/101906030-4b383a80-3bf3-11eb-9f8f-3cb022dd5de9.PNG">
> 
> Should we need more info from you, we'll ask from you on this same thread. Your contribution is greatly appreciated, thanks for helping :)

Thanks a lot, bro!! It works.
