### ISSUE TITLE
Support for /oem (remount failure)

### ISSUE THREAD

**Issue by randomname1234** [d4rken/sdmaid-public#441]
Device: Sony Xperia Z4 tablet (SGP712)
Android version: 6.0.1, rom stock v. 32.2.A.0.253
Root: yes with superSU 2.76
Log: [http://hastebin.com/veqetuyese.md](http://hastebin.com/veqetuyese.md)

When trying to delete files in `/oem/deletable-app/` sdmaid shows '1 error' and doesn't delete anything (even if I change permissions of that file to 777). Anywhere than there I get '1 error' but sdmaid remove the file (like in `/system/vendor/`)

**Comment by d4rken** [comment]
`/oem` is a distinct partition SD Maid is not yet familiar with.
Can you tell me more about it's purpose?

Can you give me a log of its content (e.g. explorer>save directory structure)?
I'm interested in whether there are any symlinks.

We also need to know whether apps are directly sourced from that location or whether `/oem` is just used to copy back preinstalled apks after a factory reset.

Actual deletion fails because SD Maid doesn't know what to remount.
```
Error:rm: can't remove '/oem/deletable-app/com.kobobooks.android/com.kobobooks.android.apk': Read-only file system
```



btw perfect ticket :heart:

**Comment by randomname1234** [comment]
Basically the core /system partition is controlled by Google. OEMs are not allowed to customize it. 
All OEM customizations go into /oem. For example I have the bootanimation there.

**Comment by d4rken** [comment]
Similar to #410.
Support for this would mean adding a module to the storage manager (to add `/oem`) and module to forensics (to detect when an item is located in that location).

I'll mail you a test version to the mail from [this post](https://github.com/d4rken/sdmaid-public/issues/410#issuecomment-226946068) when I implemented this, ok?

**Comment by d4rken** [comment]
> Basically the core /system partition is controlled by Google. OEMs are not allowed to customize it. 
> All OEM customizations go into /oem. For example I have the bootanimation there.

So apks are directly used from there, like from /system? Meaning it doesn't copy apks from there to /data?

**Comment by randomname1234** [comment]
That's not it, apks are also in '/data' but it looks like I'm able to uninstall audiorecorder so I think apps in '/oem/deletable-app' are "system app" which I Can uninstall without root privileges. 

For the email yeah, you can use that but I'm actually on holiday so I don't have wifi or a stable connection to test it, sorry :(

**Comment by d4rken** [comment]
No worries, thanks for your contribution.
