### ISSUE TITLE
Bug: AppControl не находит приложение.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4444]
### What happened?
После установки приложения com.da.fxdirector прошло больше 10 минут, но при сканировании в AppControl приложение так и не отображается, как будто оно не установлено. Папка приложения, находящаяся в Android/data, помечена фильтром CorpseFinder. Закрытие и открытие SD Maid не помогло.

[sdmaid_logfile_1608467211123.txt.zip](https://github.com/d4rken/sdmaid-public/files/5720916/sdmaid_logfile_1608467211123.txt.zip)

### SD Maid
Version: `5.0.3 (50003)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Meizu/meizu_M8/meizuM8:8.1.0/O11019/1573209132:user/release-keys`

**Comment by Ingood5** [comment]
В течение получаса после установки приложения AppControl так и не находил его. После принудительной остановки SD Maid проблема исчезла.

**Comment by d4rken** [comment]
Duplicate of #3879
