### ISSUE TITLE
Bug: pathes for db's

### ISSUE THREAD

**Issue by meronicly** [d4rken/sdmaid-public#4445]
### What happened?
cant add path for databases in settings

### What did you expect to happen?
selected path and it must be saved

### How can I reproduce the issue?
sd maid>settings>databases>directories>+>select>✓>*nothing appears*

### Comments
hi
### SD Maid
Version: `5.0.4 (50004)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/coral/coral:10/QQ3A.200805.001/6578210:user/release-keys`

**Comment by d4rken** [comment]
Please provide a video/screenshots reproducing the issue.

**Comment by meronicly** [comment]
https://user-images.githubusercontent.com/76413055/103477863-6b5eb200-4dcb-11eb-9d3e-20faf288036a.mp4

**Comment by meronicly** [comment]
> Please provide a video/screenshots reproducing the issue.

https://streamable.com/ygu3or
video

**Comment by d4rken** [comment]
The paths you are trying to add are already covered by a path that is already added.

You want to add `/storage/emulated/0/Notifications` but `/storage/emulated/0` is already added, and this includes all subdirectories.

**Comment by meronicly** [comment]
> The paths you are trying to add are already covered by a path that is already added.
> 
> You want to add `/storage/emulated/0/Notifications` but `/storage/emulated/0` is already added, and this includes all subdirectories.

I'm sorry I didn't notice this feature. everything is working. can you please delete the post?
