### ISSUE TITLE
При удалении приложения SD Maid не предупреждает, что удалит остатки.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4462]
Если удалять одно или несколько приложений в AppControl из списка, а не из окна приложения в AppControl, то SD Maid не предупреждает, что удалит остатки. 

![S01226-17121776](https://user-images.githubusercontent.com/60130882/103153100-fffb5b80-479e-11eb-82bf-c9dd547052e8.png)
![S01226-17114950](https://user-images.githubusercontent.com/60130882/103153102-012c8880-479f-11eb-8149-19afc8a68ee9.png)

**Comment by d4rken** [comment]
SD Maid should only remove leftovers if the option is enabled in the settings.

Did you enable that setting?

I think that if the user manually enabled the setting, then it is not necessary to mention it each time.

**Comment by Ingood5** [comment]
SD Maid удаляет остатки, которые помечены как не keeper, даже если опция в настройках отключена. Нужно уведомлять об удалении не keeper?

**Comment by d4rken** [comment]
No that's correct. Uninstalling through has SD Maid has always removed some leftovers.

**Comment by Ingood5** [comment]
1. Нет необходимости добавлять предупреждение об удалении не keeper?

2. Если удалять внутри приложения, появляется уведомление:
Удаление приложения и всех соответствующих остатков.

При включении английского языка:
Uninstalls the app and deletes any leftovers.

По смыслу получается что всегда удаляются все остатки.
Не нужно как-нибудь изменить текст, чтобы было понятно, что удаляемые остатки зависят от настроек? Или сделать чтобы при изменении настроек менялся текст?

**Comment by d4rken** [comment]
AppCleaner always executes something like CorpseFinder after uninstalling an app, if a user does not want that they would have to delete the app without SD Maid, through the system.

Data marked as "keeper" is guarded by an extra AppControl option that is not enabled by default.
