### ISSUE TITLE
Only some databases are found

### ISSUE THREAD

**Issue by elhennig** [d4rken/sdmaid-public#448]
With 4.2.13 I have the problem on my CandySix ROM that only 8 databases are found, even if there should be a lot more.
The search path is set to 
- /data/data
- /storage/emulated/0/Android/data
- /storage/[EXIT-SDCARD-ID]/Android/data

The "Follow Symlinks" option is set, running apps are not skipped.

**Comment by d4rken** [comment]
Sounds like SD Maid doesn't have root. Can you confirm that SD Maid has root access?

If you are certain that isn't the cause, please record a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by elhennig** [comment]
I was pretty sure it had root access. Other apps like Kernel Adiutor oder Titanium Backu worked well.
But after your hint I checked again and the su binary was installed, but the supersu app was missing. So the state of the root installation was not ok. After fixing this, SD Maid works again as expected. Strange thing is that SD Maid (or any other app) did not complain about missing root.
Thanks a lot!

**Comment by d4rken** [comment]
SD Maid treats root as optional if none is detected, some features are just disabled.
I would have expected TiBu to complain and not work though, weird.
