### ISSUE TITLE
AppCleaner : Enable ACS support for MIUI (Android 8)

### ISSUE THREAD

**Issue by haaaaaaaan** [d4rken/sdmaid-public#4482]
https://cdn.discordapp.com/attachments/793807018196598804/793823878057164810/sdmaid_logfile_1609329406114.txt.zip

My device : Redmi 5 Plus
My OS : 8.1.0 (Oreo)
MIUI Version : MIUI Global 11.0.2 | Stable
Locale : en_US

**Comment by JeffHorinzon** [comment]
Note to D4rken:
Clear data -> Clear cache -> OK

**Comment by d4rken** [comment]
@haaaaaaaan Can you share a log where SD Maid just loops and hangs?

The above log shows me what the UI looks like, but I need one where SD Maid tries the current method to see if SD Maid picks the right specification.

**Comment by haaaaaaaan** [comment]
https://cdn.discordapp.com/attachments/793807018196598804/794003658895392778/sdmaid_logfile_1609375199555.txt.zip

here it is @d4rken

**Comment by d4rken** [comment]
Thanks. Your last log confirms that SD Maid tries AOSP APi 14 to 28 Specs instead of MIUI, I've changed the Android version requirement from P to Oreo for MIUI 11 Specs, please report back after the next update.
