### ISSUE TITLE
system clean can not clean Android/data of PUBLIC_DATA on android 11

### ISSUE THREAD

**Issue by redjumper** [d4rken/sdmaid-public#4483]
Hi, pixel 2 xl, rooted with android 11 stock rom, and sd maid has updated to 5.0.6.  I notice the system clean can not clean Android/data of PUBLIC_DATA anymore, while the app clean still can.
Below is debug log.
[sdmaid_logfile_1609382008962.txt.zip](https://github.com/d4rken/sdmaid-public/files/5756346/sdmaid_logfile_1609382008962.txt.zip)

**Comment by d4rken** [comment]
```
1609382011843  V/RXS:Harvester:Error: find: No /storage/emulated/0/Android/data: Permission denied
```

I think the SystemCleaner does not understand that on Android 11 we need to use root to read `Android/data` :thinking:

**Comment by d4rken** [comment]
SystemCleaner will prefer using root when it's available and the Android Version is 11+.
