### ISSUE TITLE
AppCleaner: ACS cache cleaning support for FuntouchOS

### ISSUE THREAD

**Issue by josephmalonda** [d4rken/sdmaid-public#4487]
- **Device**: Vivo S1 Pro (vivo 1920)
- **Android version**: FuntouchOS_10 (PD1945F_EX_A_6.8.27) | Android 10
- **Language**: English
- **Additional info**: All set to default settings (e.g. font size).
- **Debug log file _with debug accessibility service_**: [sdmaid_logfile_1609477876835.txt.zip](https://github.com/d4rken/sdmaid-public/files/5758651/sdmaid_logfile_1609477876835.txt.zip)

**Comment by d4rken** [comment]
Added support for this, but I don't have such a device to test with.
Please provide feedback after the next update.

**Comment by JeffHorinzon** [comment]
Note to D4rken: Video leading to "Clear cache button"
https://cdn.discordapp.com/attachments/794422672690905088/798528868402593812/Screenrecording_20210112_202745.mp4

**Comment by josephmalonda** [comment]
- **Debug log file** **_without debug accessibility service_**: [sdmaid_logfile_1610456699006.txt.zip](https://github.com/d4rken/sdmaid-public/files/5802238/sdmaid_logfile_1610456699006.txt.zip)

**Comment by d4rken** [comment]
[sdmaid_logfile_1610601449656.txt.zip](https://github.com/d4rken/sdmaid-public/files/5824284/sdmaid_logfile_1610601449656.txt.zip)

Vivio has very nested layout, the ACCCrawler reached the nesting cap at `3` but Vivio needed `4`.
