### ISSUE TITLE
feature request: multiple users support

### ISSUE THREAD

**Issue by redjumper** [d4rken/sdmaid-public#4490]
Android supports multiple users on a single Android device by separating user accounts and application data, there are some apps using this [android for work](https://developer.android.com/about/versions/nougat/android-7.0#android_for_work) feature to provide an isolated space that can install or clone apps into. Private_data of the new user may be /data/user/10, and the public_data may be /storage/emulated/10/.
Current sd maid can't clean the files under these multiple users directory even if the device is rooted, can you add support for multiple users cleaning when rooted. Thanks

**Comment by Sridhar-Ananthanarayanan** [comment]
Oh I see. Is this what you are referring to?

![i_20210107_083133](https://user-images.githubusercontent.com/54448474/103845786-c857b200-50c2-11eb-98c8-f5f2ea583d63.png)

I have been wondering the same. SD Maid doesn't clean the app cache in secondary users.

**Comment by d4rken** [comment]
Dup, closing in favor of #3430 please collect discussions there.
