### ISSUE TITLE
Bug: faulty or repeat purchase

### ISSUE THREAD

**Issue by maxninety** [d4rken/sdmaid-public#4494]
### What happened?
I bought the pro version twice I want a refund for at least one.

### What did you expect to happen?
I bought the pro version and then I bought the same but from the app I thought it was an even more pro version. But no. It was the same, so I want a refund for a single purchase. Because I really like this app

### How can I reproduce the issue?
Returning the money for the purchase because it is defective or the same, and due to an error in the application.

### Comments
I like is application, but what a pity that the support is the Worst. I've been trying to contact for days and they don't respond.
### SD Maid
Version: `5.0.6 (50006)`
Pro: `isPro=true || isComplete=true (unl=true, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `HUAWEI/INE-LX1/HWINE:9/HUAWEIINE-LX1/9.1.0.317C432:user/release-keys`

**Comment by d4rken** [comment]
I'm sorry I did not yet answer your email but I'll get to it.
Payment related issues should only be handled through support@darken.eu
This is unlikely to be a bug in the code. Most likely you bought both upgrade options:
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#what-is-the-difference-between-the-purchase-options

**Comment by maxninety** [comment]
Yes indeed, I have bought both.
