### ISSUE TITLE
Cannot control Autostart condition of some app

### ISSUE THREAD

**Issue by LC-BX** [d4rken/sdmaid-public#450]
Hi my english is poor so pls bear with me.
The SD maid is wonderful. But some app have figured out some way to prevent the Maid to change  their Autostart condition.
They have used the symbol $ among their Class string, and I believe that's their trick. 
So if you please fix that issue and so that I can kill the Autostart of those bastards!
Thanks

**Comment by LC-BX** [comment]
oh my version is 4.2.6 beta

**Comment by d4rken** [comment]
The `$` related to anonymous inner classes, it is there not to prevent anything, but it needs to be accounted for.
There was a bug regarding this but I believe this was already fixed, please try the latest version which is currently v4.2.13.
http://sdmaid.darken.eu/download

**Comment by LC-BX** [comment]
Ah man, your advice works like charm! 
The newest version works just fine. Thx Thx!
