### ISSUE TITLE
В исключениях не хватает пометок, каким приложениям принадлежат папки

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4507]
В исключениях не хватает значка приложения возле каждой исключеной папки. Особенно если исключенных папок много и они находятся в Android/data, особенно если по именам папок не понятно, какому приложению они принадлежат. Можно запутаться.

![S10110-08315725(1)](https://user-images.githubusercontent.com/60130882/104115314-0bae5c80-531f-11eb-99d1-fd4973c5f058.png)

Можно или добавить возле каждой папки значок, или имена приложений, если они установлены, или и то и то. Если добавлять пометку ко всем папкам проблематично, можно помечать только папки из Android/data.

**Comment by d4rken** [comment]
Exceptions are just strings being matched. For SD Maid to add icons there, we would need to do additional matching to determine if an exclusion matches something of an app. So we would have to do a reverse lookup on the path.

That's out of scope for this.
