### ISSUE TITLE
Bug: Clearing app cache

### ISSUE THREAD

**Issue by NoiseBox20** [d4rken/sdmaid-public#4508]
### What happened?
App not clearing cache on not rooted device, with accessibility enabled.

### What did you expect to happen?
After enabled accessibility, app able to clear cache.

### How can I reproduce the issue?
Everytime I clean app cache with SD Maid

### Comments
I think this has something to do with un rooted device and android 10, is there any work around?
### SD Maid
Version: `5.0.6 (50006)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a6pltedx/a6plte:10/QP1A.190711.020/A605GDXU8CTI2:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log of the issue:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by NoiseBox20** [comment]
[sdmaid_logfile_1611036929013.txt.zip](https://github.com/d4rken/sdmaid-public/files/5834029/sdmaid_logfile_1611036929013.txt.zip)
