### ISSUE TITLE
problem cleaning apps "OPPO".

### ISSUE THREAD

**Issue by jasongouzien-off** [d4rken/sdmaid-public#4512]
Hello D4RKEN, I am very happy with the app you created, 
I even prefer it to CCleaner.
However, I have a problem with cleaning applications.

I don't really know where this bug could come from.

![Screenshot_2021-01-11-06-49-45-70_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/54846106/104150534-648efb00-53da-11eb-934e-5bd52a547b1e.jpg)

Hoping to have a solution by then.
Sincerely, Jason.

**Comment by d4rken** [comment]
Which SD Maid update?

**Comment by jasongouzien-off** [comment]
SD MAID 5.0.7 PREMIUM

**Comment by d4rken** [comment]
Not a bug, but missing support. This AppCleaner feature requires specific instructions for each ROM and language. 

This should be supported on 5.0.7.

Please provide a debug log of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by TheMysticS** [comment]
> Hello D4RKEN, I am very happy with the app you created,
> I even prefer it to CCleaner.
> However, I have a problem with cleaning applications.
> 
> I don't really know where this bug could come from.
> 
> ![Screenshot_2021-01-11-06-49-45-70_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/54846106/104150534-648efb00-53da-11eb-934e-5bd52a547b1e.jpg)
> 
> Hoping to have a solution by then.
> Sincerely, Jason.

Have you enabled Accessibility Permissions for SD Maid under Settings?

CCleaner is junk app from a company gone greedy.
