### ISSUE TITLE
Bug: App cleaner cache is not getting cleared in non rooted redmi note 7 pro device

### ISSUE THREAD

**Issue by Aadil0** [d4rken/sdmaid-public#4513]
### What happened?
Even though accessibility permission also given

### What did you expect to happen?
I need a fix for this issues/bug

### How can I reproduce the issue?
For this purpose only i have purchased your app 

### Comments
Please fix it are give solution
### SD Maid
Version: `5.0.7 (50007)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `Unknown`
Fingerprint: `xiaomi/violet/violet:10/QKQ1.190915.002/V12.0.4.0.QFHINXM:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log of the issue
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Aadil0** [comment]
**As you have asked debug log**

Device name : Xiaomi Redmi note 7 pro 
Android version: stock android 10
MIUI Version : MIUI global 12.0.4
Root status : unroot
SD maid version :5.0.7
SD maid un locker version: 4.4.1
[sdmaid_logfile_1610795588377.txt.zip](https://github.com/d4rken/sdmaid-public/files/5824307/sdmaid_logfile_1610795588377.txt.zip)

What issue i am facing is when i click on AppCleaner it stars searching at the end clicking delete button it asks250MB  are some value can be freed after clicking on details it shows no of apps what i have installed then i proceed to delete option only 2mb is cleared and again pressed delete option one pop up is coming in which  (you have activated features that use sdmaid's accessibility service. the service is enabled. but not running .try restarting the device ) and i restarted my device and did same procedure but it is showing as before please fix this issues asap because i purchased this only for the purpose to clear app cache data unless it is not happening

**Comment by d4rken** [comment]
Enable this option:

https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service

**Comment by Aadil0** [comment]
I did as you have said still it not clearing

**Comment by d4rken** [comment]
The log shows that the accessibility option is not being triggered, it's either not enabled in SD Maids settings (check settings), not enabled in the system (check system settings) or not running (try device reboot).

**Comment by JeffHorinzon** [comment]
@Aadil0 Maybe check #4386
