### ISSUE TITLE
Android TV 10 (Google TV)

### ISSUE THREAD

**Issue by Tbo29** [d4rken/sdmaid-public#4523]
Granted accessibility, storage and usage permissions. Scanning the cache works and SD Maid finds correctly all the application caches. Then when giving the delete command it opens the app page of each application with cache, but does clean nothing.

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Tbo29** [comment]
[sdmaid_logfile_1610839647844.txt](https://github.com/d4rken/sdmaid-public/files/5825291/sdmaid_logfile_1610839647844.txt)

**Comment by d4rken** [comment]
Same as #4149

**Comment by d4rken** [comment]
Will close this and post an answer there.
