### ISSUE TITLE
Usefulness of exclusion for AppControl

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4526]
1. При добавлении исключения есть галочка "AppControl". Для чего она нужна? Если ее поставить, исключенная папка все равно отображаются в приложении, которому она принадлежит.

2. Для чего при добавлении исключения нужен пункт "регулярное выражение"?

**Comment by d4rken** [comment]
It's a good question.
I will have to check the code, but I think an exclusion will affect application uninstalls through the AppControl tool

**Comment by Ingood5** [comment]
> Для чего при добавлении исключения нужен пункт "регулярное выражение"?

?

**Comment by d4rken** [comment]
To give the use more powerful options for excluding files.

Maybe you want to exclude and received PDF files from WhatsApp? 
Normal exclusions don't allow that. With regular expressions you can do something like `.+/Media/.+/.+\.pdf`

**Comment by d4rken** [comment]
> It's a good question.
> I will have to check the code, but I think an exclusion will affect application uninstalls through the AppControl tool

Actually the exclusions don't affect the uninstall. The exclusions can be used to exclude apps from scan by using the packagename. So it's mostly interesting when storage size is scanned and an app should be excluded, maybe because it takes too long to scan.

**Comment by Ingood5** [comment]
Как это работает? Возможно здесь ошибка. Добавил папку из Android/data, а приложение все равно отображается в AppControl.

**Comment by Ingood5** [comment]
Что будет, если добавить в исключение AppControl папку из подводника? Я добавил, приложение все равно появляется в списке после сканирования.

**Comment by d4rken** [comment]
Can you show the exclusion?
Exclusions by packagename should work and remove apps from AppControl.

**Comment by Ingood5** [comment]
Добавляется полное имя папки. 

![Screenshot_2022-09-16-11-53-05-159_eu thedarken sdm](https://user-images.githubusercontent.com/60130882/190599025-7e89ca2d-2b26-4744-846e-da82cf6c3a4e.jpg)

**Comment by d4rken** [comment]
Exclusions by path have no effect in the appcontrol tool.

**Comment by d4rken** [comment]
I think this is too niche to add.
The this works is also very difficult to understand for most users to find use for it.
Thanks for the feedback though :+1:
