### ISSUE TITLE
Bug: RedMagic 5G phone

### ISSUE THREAD

**Issue by RieraMig99** [d4rken/sdmaid-public#4527]
### What happened?
The cache doesn't get delete on this phone

### What did you expect to happen?
The cache would be deleted the same as my samsung galaxy s8 plus

### How can I reproduce the issue?
Using a RedMagic 5G Phone try cleaning the cache by itself or by the app but the app can't find the right buttons

### Comments
Do you want a screenshot of how the settings of the cache are placed?
### SD Maid
Version: `5.0.8 (50008)`
Pro: `isPro=true || isComplete=true (unl=true, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `nubia/NX659J/NX659J:10/QKQ1.200405.002/nubia.20201101.042008:user/release-keys`

![Screenshot_2021-01-17-21-16-37-818](https://user-images.githubusercontent.com/77597265/104865237-75270000-5909-11eb-9096-29812f9268b6.png)
![Screenshot_2021-01-17-21-16-30-334](https://user-images.githubusercontent.com/77597265/104865241-76f0c380-5909-11eb-8a0e-daa7c27e2dc4.png)

**Comment by d4rken** [comment]
Please provide a debug log of SD Maid getting stuck in a scan, you don't need to wait until SD Maid is finished, you can abort once 2-3 apps have been retried and skipped.

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by RieraMig99** [comment]
[Uploading sdmaid_logfile_1611719967559.txt…]()

**Comment by d4rken** [comment]
Added preliminary support for this.
Check back after v5.0.9, if it does not work correctly, please provide another log.
