### ISSUE TITLE
Requirements for enabling Accessibility Service...

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/sdmaid-public#4533]
Can you clarify when Accessibility Service permission is required (if clearing Default App Cache is selected under AppCleaner settings)?

I have 3 devices as follows:

1. UN-rooted device running on Android 8: Accessibility Service **NOT** required for PRIMARY user. But Accessibility service **IS REQUIRED** for secondary users.

2. Rooted device running on Android 9: Accessibility Service **NOT** required for PRIMARY user (haven't tried secondary users).

3. UN-rooted device running on Android 11: Accessibility Service **required for ALL** users.

I have checked your HELP page, but it isn't clear.

Thanks.

**Comment by d4rken** [comment]
ACS is not required on rooted devices (if SD Maid has root permission).

Without root, ACS is required for Android 6.0+ to clear default caches.

> UN-rooted device running on Android 8: Accessibility Service NOT required for PRIMARY user. But Accessibility service IS REQUIRED for secondary users.

This seems unusual. Can you post a log of this? I expect ACS to be needed, or the default (private) caches were not really cleared.

> if clearing Default App Cache is selected under AppCleaner settings)?

That's a good point, I'm not sure if SD Maid disables the requirement if the default cache filter is disabled :thinking:
