### ISSUE TITLE
Possibility of deactivating sd maid starting with the system

### ISSUE THREAD

**Issue by gallegonovato** [d4rken/sdmaid-public#4536]
Good afternoon:

First of all, thank you very much for your application and for all the effort you put into it. As well as the constant improvements it provides us with.

My doubt or suggestion. Is if it is possible to add an option for Sd Maid not to start with the mobile system. 

That is, it starts when you press it. But not from the beginning of the mobile or with the operating system of the mobile. 

As I see for example in sd maid, application control. That the feature can't be disabled and I don't see the option through the different configuration menus. 

I appreciate very much your time and help and I don't know if it could be feasible what I propose.

Receive a warm hug

**Comment by d4rken** [comment]
SD Maid will already deactivate it's own boot receivers when functions such as the scheduler are not used.

**Comment by gallegonovato** [comment]
Good evening @d4rken 

I get that it always runs with the system and I have no way to disable it.

Even if I am not using it

Best regards
