### ISSUE TITLE
I can get access to the pro version

### ISSUE THREAD

**Issue by corey74** [d4rken/sdmaid-public#455]
Can somebody please email me MJ why at gmail.com the pro version app of the drunk and made so I can try to use it and share it with the family and show them what's going on with it since I am a beta tester

**Comment by d4rken** [comment]
Just being a beta tester doesn't qualify for a free copy of SD Maid.
Promo codes are available for substantial contributions (bug reports / translations), in these cases the volunteers should just send me a quick mail.

**Comment by corey74** [comment]
Ok mjy740@gmail.com
