### ISSUE TITLE
Clutterreport: /storage/emulated/0/.chat_temp (new)

### ISSUE THREAD

**Issue by Aubseyhbic** [d4rken/sdmaid-public#4550]
### Target
Target: `/storage/emulated/0/.chat_temp`
Prefix-free: `.chat_temp`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Font Server`
Packagename: `com.hy.system.fontserver`
Version: `5.1.4 (50010040)`

### Current owners
None

### SD Maid
Version: `5.0.4 (50004)`

### Device
Fingerprint: `lge/mh5lm_g/mh5lm:9/PKQ1.190414.001/203311754338b:user/release-keys`

### Comment
`my text messages show up here then diaper`

**Comment by d4rken** [comment]
This is not the correct owner, can't add it.
