### ISSUE TITLE
Clutterreport: /storage/emulated/0/vlc_media.db (new)

### ISSUE THREAD

**Issue by jtyrell321** [d4rken/sdmaid-public#4558]
### Target
Target: `/storage/emulated/0/vlc_media.db`
Prefix-free: `vlc_media.db`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `VLC`
Packagename: `org.videolan.vlc`
Version: `3.3.2 (13030207)`

### Current owners
None

### SD Maid
Version: `5.0.8 (50008)`

### Device
Fingerprint: `OnePlus/OnePlus8TMO/OnePlus8TMO:10/QKQ1.191222.002/2011102152:user/release-keys`

**Comment by d4rken** [comment]
When is this created?
