### ISSUE TITLE
Not cleaning cashe without root access

### ISSUE THREAD

**Issue by Nokono** [d4rken/sdmaid-public#4573]
Closed

**Comment by d4rken** [comment]
Make sure you have enabled https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service
If it does not work, please provide a debuglog:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Nokono** [comment]
The bug report is sent to your e-mail. Thank you!

**Comment by d4rken** [comment]
What's the subject of you mail? I currently have a pretty packed inbox and have not managed to go through every email.

**Comment by Nokono** [comment]
You have corrected the issue already, thank you. It is  closed
