### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/.omega.key (FP)

### ISSUE THREAD

**Issue by jpzex** [d4rken/sdmaid-public#4590]
### Target
Target: `/storage/emulated/0/Download/.omega.key`
Prefix-free: `Download/.omega.key`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `99`
Packagename: `com.taxis99`
Version: `6.17.0 (1004)`

### Current owners
Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `8.1.0 (27)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `8.1.0 (27)`

Appname: `Android System`
Packagename: `android`
Version: `8.1.0 (27)`

### SD Maid
Version: `5.0.8 (50008)`

### Device
Fingerprint: `motorola/cedric/cedric:7.0/NPPS25.137-15-11/11:user/release-keys`

### Comment
`I frozen many apps I suspected would create this file and I was unfreezing and testing each one until this one appears to create this file. Whenever I erase this file, the app creates again on the next opening.`

**Comment by d4rken** [comment]
Nice find!

**Comment by d4rken** [comment]
Have you looked inside the file with a text editor?

**Comment by jpzex** [comment]
The file contains a sort of key or identification. Whenever I delete the file it is generated again with the same content inside it.
