### ISSUE TITLE
Bug: Failed to clear application cache

### ISSUE THREAD

**Issue by rafidardanu** [d4rken/sdmaid-public#4603]
### What happened?
Every time I scan all the trash in the application section, it always fails to clean, even though I have allowed all the permissions

### What did you expect to happen?
I hope for help to solve the problem, I really need help to solve the issue, be the best

### How can I reproduce the issue?
What I want to say is, when I scan and then clear the app cache it should clear all cache

### Comments
Thank you for your help, warm greetings from clients
### SD Maid
Version: `5.0.8 (50008)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `POCO/surya_id/surya:10/QKQ1.200512.002/V12.0.5.0.QJGIDXM:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log and make sure you have enabled this:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
