### ISSUE TITLE
Clutterreport: /storage/emulated/0/LuckyPatcher

### ISSUE THREAD

**Issue by mdshaan** [d4rken/sdmaid-public#4605]
### Target
Target: `/storage/emulated/0/LuckyPatcher`
Prefix-free: `LuckyPatcher`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Luскy_Patcher  `
Packagename: `ru.vvskxgli.wdpyckzne`
Version: `9.3.5 (1695)`

### Current owners
Appname: `?`
Packagename: `com.forpda.lp`
Version: ` (-1)`

Appname: `?`
Packagename: `com.android.vending.billing.InAppBillingService.LACK`
Version: ` (-1)`

Appname: `?`
Packagename: `com.dimonvideo.luckypatcher`
Version: ` (-1)`

Appname: `?`
Packagename: `com.android.vending.billing.InAppBillingService.CRAC`
Version: ` (-1)`

Appname: `?`
Packagename: `com.chelpus.lackypatch`
Version: ` (-1)`

Appname: `?`
Packagename: `com.android.protips`
Version: ` (-1)`

Appname: `?`
Packagename: `com.android.vending.billing.InAppBillingService.LOCK`
Version: ` (-1)`

Appname: `?`
Packagename: `com.android.vending.billing.InAppBillingService.LUCK`
Version: ` (-1)`

Appname: `?`
Packagename: `com.android.vending.billing.InAppBillingService.CLON`
Version: ` (-1)`

### SD Maid
Version: `5.0.7 (50007)`

### Device
Fingerprint: `Xiaomi/beryllium/beryllium:10/QKQ1.190828.002/V12.0.3.0.QEJMIXM:user/release-keys`

**Comment by jpzex** [comment]
Lucky Patcher latest APKs are generated in device with random APK name, maybe this folder should always be a keeper despite the LP being present or not (because you may not find it).

**Comment by d4rken** [comment]
Is there a pattern? `ru.\.+?`

The name is always "Lucky-Patcher"?

**Comment by jpzex** [comment]
The package name varies too, some unusual character in the place of the r, y and a, maybe greek letter. Can you create a rule for the folder independent of package presence?

**Comment by d4rken** [comment]
We would need to assign it some package, it's possible to assign another app as custodian then, sd maid does not suggest it as corpse, but which? The system?

**Comment by jpzex** [comment]
Idk, I guess the system is not a good candidate because it can live without this data no problem, and also as this should be a keeper, I would say to leave it as com.forpda.lp as it was the first name of Lucky Patcher package.

**Comment by patpolster** [comment]
> ### Target
> 
> Target: `/storage/emulated/0/LuckyPatcher`
> Prefix-free: `LuckyPatcher`
> Path-prefix: `/storage/emulated/0/`
> Type: `DIRECTORY`
> Location: `SDCARD`
> Current keeper state: `false`
> Suggested keeper state: `true`
> ### Suggested owners
> 
> Appname: `Luскy_Patcher `
> Packagename: `ru.vvskxgli.wdpyckzne`
> Version: `9.3.5 (1695)`
> ### Current owners
> 
> Appname: `?`
> Packagename: `com.forpda.lp`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.android.vending.billing.InAppBillingService.LACK`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.dimonvideo.luckypatcher`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.android.vending.billing.InAppBillingService.CRAC`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.chelpus.lackypatch`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.android.protips`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.android.vending.billing.InAppBillingService.LOCK`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.android.vending.billing.InAppBillingService.LUCK`
> Version: ` (-1)`
> 
> Appname: `?`
> Packagename: `com.android.vending.billing.InAppBillingService.CLON`
> Version: ` (-1)`
> ### SD Maid
> 
> Version: `5.0.7 (50007)`
> ### Device
> 
> Fingerprint: `Xiaomi/beryllium/beryllium:10/QKQ1.190828.002/V12.0.3.0.QEJMIXM:user/release-keys`
