### ISSUE TITLE
Clutterreport: /storage/emulated/0/Instander (new)

### ISSUE THREAD

**Issue by RKealohi** [d4rken/sdmaid-public#4611]
### Target
Target: `/storage/emulated/0/Instander`
Prefix-free: `Instander`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Instander`
Packagename: `com.instander.android`
Version: `166.0.0.41.245 (255959606)`

### Current owners
None

### SD Maid
Version: `5.0.6 (50006)`

### Device
Fingerprint: `TCL/REVVL_2_PLUS_6062Z/A70AXLTMO:8.1.0/OPM1.171019.011/v1AIT-0:user/release-keys`

**Comment by M6eer9595848494** [comment]
#4653
