### ISSUE TITLE
tTwo issues about APKs Scan

### ISSUE THREAD

**Issue by Conceal945** [d4rken/sdmaid-public#4620]
1. For the way of matching apk, matching ".apk" suffix alone is not enough, I hope we can consider hex-based file header recognition.
2. Due to the update of the Android version, I would like to support the scanning of Apks in the PUBLIC_DATA

**Comment by d4rken** [comment]
> For the way of matching apk, matching ".apk" suffix alone is not enough, I hope we can consider hex-based file header recognition.

What usecase would this solve?

> Due to the update of the Android version, I would like to support the scanning of Apks in the PUBLIC_DATA

What change are you referring to?

**Comment by Conceal945** [comment]
The Change is that all apks will be stored in PUBLIC_DATA and it happened in Android R.


Matching the hex file header is good for avoiding missing scans, because some applications do not regulate the apk naming in their own update channels, and at the same time, installation packages downloaded from some websites may also have such problems. For example, the file name is a string of base64 with no suffix, and the name "dl.php".


---Original---

**Comment by d4rken** [comment]
> The Change is that all apks will be stored in PUBLIC_DATA and it happened in Android R.

Can you point me to documentation that says that? This would be news to me.

**Comment by Conceal945** [comment]
Android R implements the sandboxing mechanism that was implemented back on Q. This means that old rules in your program cannot be matched to new paths. Previously /sdcard/Target/files, now /sdcard/Android/data/pkgname/sdcard/Target/files. all files are redirected to their own directory. So there are only a few canonical directories in the root directory now. Also these apk's that should have been stored in the old location have been put in the new location. So the built-in app cleanup rules are forced to be improved as well.

**Comment by Conceal945** [comment]
For most programs, they will put the downloaded apk in /Download, which is the Android canonical directory and can be accessed even without storage permissions, but for non-canonical apps, they will not put it in /Download.



---Original---

**Comment by Conceal945** [comment]
example



---Original---

**Comment by Conceal945** [comment]
---Original---

**Comment by d4rken** [comment]
The sandboxing mechanism has nothing to do with the storage location of APKs. Unless you have some official documentation about this I'd have to close this.
