### ISSUE TITLE
Clutterreport: /storage/emulated/0/.vivo/pushsdk/config/config.txt (new)

### ISSUE THREAD

**Issue by 3xploiton3** [d4rken/sdmaid-public#4622]
### Target
Target: `/storage/emulated/0/.vivo/pushsdk/config/config.txt`
Prefix-free: `.vivo/pushsdk/config/config.txt`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `5.0.8 (50008)`

### Device
Fingerprint: `xiaomi/whyred/whyred:8.1.0/OPM1.171019.011/V9.5.11.0.OEIMIFA:user/release-keys`

### Comment
`from easyshare apps by vivo`

**Comment by d4rken** [comment]
What's the package name?

**Comment by 3xploiton3** [comment]
https://play.google.com/store/apps/details?id=com.vivo.easyshare&hl=en&gl=US

com.vivo.easyshare
