### ISSUE TITLE
Beta 5.0.10 force close on every device

### ISSUE THREAD

**Issue by Tbo29** [d4rken/sdmaid-public#4644]
[As](url) title. As soon as I click scan, it crashes. Tried on different devices. 

<details>
<summary>Details</summary>

</details>
[sdmaid_logfile_1614011251007.txt](https://github.com/d4rken/sdmaid-public/files/6023467/sdmaid_logfile_1614011251007.txt)

**Comment by d4rken** [comment]
Thank you, should be fixed with 5.0.11.
