### ISSUE TITLE
Clutterreport: /system/framework/framework-res.apk (FP)

### ISSUE THREAD

**Issue by sashko2004-57** [d4rken/sdmaid-public#4645]
### Target
Target: `/system/framework/framework-res.apk`
Prefix-free: `framework/framework-res.apk`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Система Android`
Packagename: `android`
Version: `6.0.1 (23)`

### Current owners
None

### SD Maid
Version: `5.0.8 (50008)`

### Device
Fingerprint: `Xiaomi/wt88047/wt88047:5.1.1/LMY47V/6.1.28:user/release-keys`

### Comment
Это apk-файл приложения "Система Android"

**Comment by d4rken** [comment]
System APK clutter matches are not supported.
