### ISSUE TITLE
Clutterreport: /system/build.prop (FP)

### ISSUE THREAD

**Issue by kopbI4** [d4rken/sdmaid-public#4649]
### Target
Target: `/system/build.prop`
Prefix-free: `build.prop`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `GetApps`
Packagename: `com.xiaomi.mipicks`
Version: `15.6.0 (4001560)`

### Current owners
None

### SD Maid
Version: `5.0.9 (50009)`

### Device
Fingerprint: `Redmi/begonia_ru/begonia:10/QP1A.190711.020/V12.0.7.0.QGGRUXM:user/release-keys`

**Comment by Pablo403-60** [comment]
Hi thank you I lost my life because this guy please help I don't know what to do next??
