### ISSUE TITLE
Duplicates scan fails with "read failed: EIO (I/O error)"

### ISSUE THREAD

**Issue by Fabiuz99** [d4rken/sdmaid-public#465]
I was looking forma duplicated files but the scan lasted a few seconds and then this Error appeared.
I am on 5.1.1
![screenshot_2016-08-17-18-34-34](https://cloud.githubusercontent.com/assets/12954989/17781615/509f0ebc-6570-11e6-90ad-8b45b5ec5274.png)

**Comment by d4rken** [comment]
Did you change the default searchpathes?
Note that the Duplicates tool does currently not support search in areas that require root permission.
E.g. a reinstall would restore the default searchpathes, try that first.

If that's not it please record a debug log it will show where the error comes from:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Fabiuz99** [comment]
Hi, I have clean flashed my ROM again and the problem  disappeared. I have clean flashed because I nave tried to reinstall it but the problem was noto gone

**Comment by d4rken** [comment]
That's good news and bad news :grin:.
Good that it works now, bad that we won't know what caused it.

If you find out more feel free to add it to this ticket.

**Comment by d4rken** [comment]
Same error was also reported by another user.
He later found out his sdcard was faulty, replacing the sdcard fixed it.

```
ROM: lge/p1_global_com/p1:6.0/MRA58K/1620215065b6f:user/release-keys/de_DE
SD Maid: 4.2.13[40213]
Unlocker: 4.0.7[40007]
Root: false
Storage: /storage/6CE9-4FD0
Storage: /storage/emulated/0
```

https://cloud.githubusercontent.com/assets/1439229/17831242/f047fa18-66e3-11e6-83c8-794b56e41da1.png

@Fabiuz99 You might want to check your sdcard.
