### ISSUE TITLE
Clutterreport: /storage/emulated/0/Books (FP)

### ISSUE THREAD

**Issue by ajwsert** [d4rken/sdmaid-public#4660]
### Target
Target: `/storage/emulated/0/Books`
Prefix-free: `Books`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Moon+ Reader Pro`
Packagename: `com.flyersoft.moonreaderp`
Version: `6.5 (605002)`

### Current owners
Appname: `Sistema Android`
Packagename: `android`
Version: `10 (29)`

Appname: `?`
Packagename: `com.prestigio.ereader`
Version: ` (-1)`

### SD Maid
Version: `5.0.8 (50008)`

### Device
Fingerprint: `Redmi/joyeuse_global/joyeuse:10/QKQ1.191215.002/V12.0.2.0.QJZMIXM:user/release-keys`

**Comment by d4rken** [comment]
Moon reader owns `Books/MoonReader` as far as I can tell, not the whole `Books/`.
