### ISSUE TITLE
Einstellungen lassen sich nicht öffnen

### ISSUE THREAD

**Issue by Sammyaskan** [d4rken/sdmaid-public#4667]
Leider lassen sich die Einstellungen nicht mehr öffnen.

https://user-images.githubusercontent.com/79868238/109541586-43868480-7ac4-11eb-847d-fa8a091b6c55.mp4

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
