### ISSUE TITLE
Clutterreport: /storage/emulated/0/.clock/.nomedia (new)

### ISSUE THREAD

**Issue by natthesilence** [d4rken/sdmaid-public#4673]
### Target
Target: `/storage/emulated/0/.clock/.nomedia`
Prefix-free: `.clock/.nomedia`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Dcoder`
Packagename: `com.paprbit.dcoder`
Version: `3.2.9 (284)`

### Current owners
None

### SD Maid
Version: `5.0.8 (50008)`

### Device
Fingerprint: `HUAWEI/EVR-L29/HWEVR:10/HUAWEIEVR-L29/10.1.0.247C636:user/release-keys`

**Comment by d4rken** [comment]
Do you have more information about this?
