### ISSUE TITLE
Clutterreport: /storage/emulated/0/.a.dat (new)

### ISSUE THREAD

**Issue by korsto** [d4rken/sdmaid-public#4686]
### Target
Target: `/storage/emulated/0/.a.dat`
Prefix-free: `.a.dat`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Official TWRP App`
Packagename: `me.twrp.twrpapp`
Version: `1.22 (35)`

### Current owners
None

### SD Maid
Version: `5.0.11 (50011)`

### Device
Fingerprint: `samsung/a51nsxx/a51:11/RP1A.200720.012/A515FXXU4DUB1:user/release-keys`

**Comment by d4rken** [comment]
what is in this file?
