### ISSUE TITLE
Bug: Значки мигают не синхронно.

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4691]
### What happened?
Лучше сделать, чтобы значки приложений в проводнике мигали синхронно.

[VIDEO.zip](https://github.com/d4rken/sdmaid-public/files/6107571/VIDEO.zip)

### SD Maid
Version: `5.0.11 (50011)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.7.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
Not perfect, but out of scope.
The effort/hours required to make them blink in sync is not worth it, sorry.
