### ISSUE TITLE
Clutterreport: /storage/emulated/0/magovideo (new)

### ISSUE THREAD

**Issue by Kris-huboss** [d4rken/sdmaid-public#4694]
### Target
Target: `/storage/emulated/0/magovideo`
Prefix-free: `magovideo`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `DRParser Mode`
Packagename: `com.sec.android.app.parser`
Version: `11.0.00.1 (1100000001)`

### Current owners
None

### SD Maid
Version: `5.0.11 (50011)`

### Device
Fingerprint: `samsung/a11qub/a11q:10/QP1A.190711.020/A115MUBU1ATK6:user/release-keys`

**Comment by d4rken** [comment]
What is inside of this folder?

**Comment by Pablo403-60** [comment]
if u mean samsung tv what i have? I cant downloaded a nothing at all and i though i will need sd maid like for xiaomi phone but its say invalid request downloading its not supported!!!!!!!!! matthias<--->Im getting sick and crazy this shit bag is my worst nightmare!!!!!!!®¿?ø Thank you mate!$%©

**Comment by d4rken** [comment]
Not enough info.
