### ISSUE TITLE
android.process.acore

### ISSUE THREAD

**Issue by thehardins** [d4rken/sdmaid-public#470]
Please Help .. This keeps coming up after I ran explorer

**Comment by d4rken** [comment]
I have no idea what you mean.
Please provide additional information.

**Comment by thehardins** [comment]
My phone reset it's self.. Came back on fine.. But I kept getting android.process.acore popping up on screen every couple seconds.. Thank You.. Sorry to Bother You

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 29, 2016 at 4:53 PM, Matthias Urhahn<notifications@github.com> wrote:   
I have no idea what you mean.
Please provide additional information.
