### ISSUE TITLE
CorpseFinder fails to detect directory and it's content

### ISSUE THREAD

**Issue by Solomon1732** [d4rken/sdmaid-public#472]
The directory is phoneclean that belonged to the app phone clean that has been uninstalled from the device before running CorpseFinder.

Steps to reproduce:
1) Install phone clean
2) Uninstall phone clean
3) Run CorpseFinder
4) Check that said directory wasn't found by CorpseFinder and search for it with the system file explorer to verify that the directory exists in the system

App package name: com.cyou.clean
App in Google Play: https://play.google.com/store/apps/details?id=com.cyou.clean
Directory path: /storage/emulated/0/phoneclean
Android version: 6.0 Marshmallow
Phone type: LG G4 Beat

**Comment by d4rken** [comment]
Will add a new entry for this, once SD Maids file forensics can determine the ownership, the other tools deal with it automatically.

**Comment by d4rken** [comment]
Commited to v4.3.0 branch
