### ISSUE TITLE
Filter for AppCleaner

### ISSUE THREAD

**Issue by Edfgdz** [d4rken/sdmaid-public#4722]
Look like some apps have files in /storage/emulated/0 path in AppCleaner after scanning.

For example like this.

![Screenshot_2021-03-20-18-33-40-604_eu thedarken sdm](https://user-images.githubusercontent.com/26460124/111867015-4b8f6100-89ac-11eb-9cf0-59ddc95c2fbf.jpg)

If some users find some files in /storage/emulated/0 path in AppCleaner should be deleted then those users could create UserFilters for /storage/emulated/0 paths files in AppClener.

However at present it is hard for those users to find out which apps have files in /storage/emulated/0 paths in AppCleaner if their installed apps too much.

So is it possible to add filter sidebar for users to let them could filter out those apps having paths in /storage/emulated/0 and make them could create rules faster?

Maybe that filter sidebar could be put in right side like Exclusions Sidebar.

**Comment by d4rken** [comment]
Why would the user not delete them through AppCleaner? Creating extra filters to delete them with a different tool seems like unnecessary work.

**Comment by Edfgdz** [comment]
Because Some useless files will scanned out each time in AppCleaner when user use AppCleaner function,it means user need to find out those files in AppCleaner and delete them again and again.

But if when user add those files into SystemCleaner userfilters,it would be different, when user create userfilters for useless files in AppCleaner and when they use sd maid next time,user could scan device using SystemCleaner function to clean rubbish files then using AppCleaner,so in this situation something would happen.

Use SystemCleaner and Clean files>Use AppCleaner and add those files into SystemCleaner>Next time Use SystemCleaner>Next time use AppCleaner and scanned out useless files will be less because some regular files have been added to SystemCleaner cleared fristly.

So in this process,if user choose use SystemCleaner then use AppCleaner and add those files into Userfilters,this process will be look like one Virtuous circle because when user add those files into SystemCleaner and when they follow SystemCleaner>AppCleaner this process,more and more useless files will be deleted in SystemCleaner this Automatical action and what they need to do will be less each time in AppCleaner.

So i mean filter function in AppCleaner is to filter out those results having files in /storage/emulated/0 paths 
and user could create userfilters for them especially for when their phones not rooted

**Comment by Edfgdz** [comment]
I think there is another thing,user can't touch delete button directly after they scan devices using AppCleaner because some files scanned out in AppCleaner could be useful to them,so when they add useless files into SystemCleaner,that function can also help them add useful files into Exclusion.

**Comment by Edfgdz** [comment]
I find this is one setting called Show inaccessible items in AppCleaner options. 

Look like it is what i want to seek so i think i could close this issue now.
