### ISSUE TITLE
Appcleaner not working on Pixel 4 running Android 11

### ISSUE THREAD

**Issue by SykoviT** [d4rken/sdmaid-public#4727]
Appcleaner does find 5 Gb of data to clear, but can't delete cache contents. It keeps trying to delete data a few times, then goes to the next app. At the end, nothing has been deleted. I did enabled accessibility options.

**Comment by d4rken** [comment]
Please provide a debuglog of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by d4rken** [comment]
Not enough info.
