### ISSUE TITLE
Bug: AppCleaner - ACS gets stuck at Media Storage

### ISSUE THREAD

**Issue by spiritETG** [d4rken/sdmaid-public#4739]
Hi hi hi~ Fellow Samsung users, I heard ya!  I've been there too.

Let's get straight to the point.  It got stuck at Media Storage.  Why? Because SDMaid couldn't read the fact that both Clear Cache and Clear Data were greyed out.  So, let's make this heard and fixed.

Here's the data he might need:
OS - Samsung OneUI 3.1, Android 11 (Tested with Samsung Galaxy Note 10+)
Logfile (Note: Media Storage is last to clear by ACS) - [sdmaid_logfile_1616784423790.txt](https://github.com/d4rken/sdmaid-public/files/6213824/sdmaid_logfile_1616784423790.txt)
Screenshot of affected app - 
<img src="https://user-images.githubusercontent.com/3746534/112681885-464d7d00-8eaa-11eb-8597-bc045be29993.png" width="250">
<img src="https://user-images.githubusercontent.com/3746534/112681212-5749be80-8ea9-11eb-9c9d-64ad51154eea.png" width="250">

What's expected to work - SDMaid should be skipping the said app

Reference to Darken (other apps with both options clickable and data greyed) - 
With 'Clear Data' greyed out v
<img src="https://user-images.githubusercontent.com/3746534/112681548-ddfe9b80-8ea9-11eb-82e7-733c6c0a8b8c.png" width="250">

With both options clickable v
<img src="https://user-images.githubusercontent.com/3746534/112681677-02f30e80-8eaa-11eb-93eb-7aab574637d3.png" width="250">

**Comment by d4rken** [comment]
Covered by #5077
