### ISSUE TITLE
Recurring empty folder

### ISSUE THREAD

**Issue by sourkarm2** [d4rken/sdmaid-public#474]
Recurring empty folder deletion is not effective. Even it is not able to delete single level empty folders properly.

**Comment by d4rken** [comment]
Nested empty folders are a known limitation, see #201.

Do you have an example or a log of a simple empty directory not being deleted?

**Comment by d4rken** [comment]
Any update on this?

**Comment by Solomon1732** [comment]
I have seen that even though I delete manually empty directories, they are created later by various apps (facebook, whatsapp, etc.) Perhaps it's the same case for you?
