### ISSUE TITLE
Opening Stastics Slows App to Error

### ISSUE THREAD

**Issue by marksjc** [d4rken/sdmaid-public#4741]
Was trying to view stats to ensure sched cleaning was happening as configured.  Sta Stats start with 2 moving circles moving together but with variable speed (as as pair).  The circle drawing can appear to slow or even stop.  The stop effect may due to timing or other reasons actually disappear leaving black space.  There seems to be 2 other states that are futher in the process but also cause hang: 1 larger circle with no screen division or Black Screen of Coma when the only thing visible is that top pull down of the phone (date/time/symbols known to carrier/battery % on my rooted/Magisk Samsung e10 (G970F) exnos/Eur&ME.  Affect so pronounced response to back button give and recent apps button sluggish.  System panel 2 d
S hows relatively high CPU use for SDM at over 14% with total less then 25% and no visible mem or storage issues.  I did try clearing SM casche but no improvement.  i killed SD manually in  SysPan2 and app reverted to normal appearanc but not able to retest out of time, note that manual kill just before this narrative resolved appearance (menu) but same: slow, stop. The Google style App not working wait  stop report came up but only when control panel for SD panel open.  I'm thinking feedback may have overwhelmed lesser developers and G made those popup only on certain states like control panel open. I get them rarely and it's hard to believe app quality has increased.  Apples iPhone app quality is terrible unless more than $10 price apparently.  I guess cheap shit OK but don't impact the brand with junk that pa
Pisses off the elite, since we've taken the audio out away and sealed in batteries w/o waterproof) years ago and never had memory slot, and they still paid, shipped undersized chargers for years (then told them to use what they had !): Don't mess with our voodoo or store doors will close.

**Comment by d4rken** [comment]
Please provide a debug log.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

The statistics data is not loaded on the main thread, so if the animation is stuttering, there may be an issue with your storage.
If SD Maid is on an external sdcard try moving it to internal.

**Comment by dragonGod97677** [comment]
Maybe the statistics log/database is just too big now thus sd maid stops loading it and starts to stuttering

**Comment by marksjc** [comment]
Duped on #4887 with improved description and requested debug log attached.

**Comment by kgblee** [comment]
marksjc ***@***.***> 於 2021年5月30日 週日 09:50 寫道：
