### ISSUE TITLE
Bug: Unable to plan in planner

### ISSUE THREAD

**Issue by MartinL0815** [d4rken/sdmaid-public#4743]
### What happened?
I wanted to setup the regular use of planned actions, how often

### What did you expect to happen?
I expected to be able to set the timely distance of the scheduled cleanup

### How can I reproduce the issue?
I choose the planet but can't setup there scheduling

### SD Maid
Version: `5.1.0 (50100)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `google/redfin/redfin:11/RQ2A.210305.006/7119741:user/release-keys`

![Screenshot_20210328-072636](https://user-images.githubusercontent.com/525700/112743475-f2b95d00-8f97-11eb-888b-e4ba87e36d44.png)

**Comment by d4rken** [comment]
Can you provide a debuglog of this?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by MartinL0815** [comment]
Here the log file in a zip archive. Was too large without.

**Comment by MartinL0815** [comment]
Here the compressed debug log file.

**Comment by MartinL0815** [comment]
Hhm, SD maid didn't provide ways to get the log file to you.
Since the attachment didn't arrive here and I can't attach the 39 MB file here … how to get the log file to you?

**Comment by d4rken** [comment]
39MB sounds a bit  large if you are just recording this bug, in any case, you can mail it (or a link to Google Drive) to support@darken.eu (please reference this issue ticket in the subject), if you don't want to post here.

**Comment by Leeeooo19888** [comment]
...

**Comment by d4rken** [comment]
Not enough info 😦 , didn't get any debug log.
