### ISSUE TITLE
Bug: Systemcleaner doesn't search empty folders in sdcard

### ISSUE THREAD

**Issue by AevaZack** [d4rken/sdmaid-public#4750]
### What happened?
Systemcleaner doesn't searching for empty folders on sdcard

### What did you expect to happen?
It's not cleaning sdcard empty folders

### How can I reproduce the issue?
Just make sure you have an sdcard inserted into device create a empty folder go to systemcleaner it doesn't search empty folders on sdcard  and delete it

### Comments
Just tell is this how it works or I have to change something 
### SD Maid
Version: `5.1.0 (50100)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/redfin/redfin:11/RQ2A.210305.006/7119741:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
