### ISSUE TITLE
Clutterreport: /storage/emulated/0/gacg (new)

### ISSUE THREAD

**Issue by geoffsterr** [d4rken/sdmaid-public#4757]
### Target
Target: `/storage/emulated/0/gacg`
Prefix-free: `gacg`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Galaxy Gift`
Packagename: `com.samsung.privilege`
Version: `8.2.1 (125)`

### Current owners
None

### SD Maid
Version: `5.1.0 (50100)`

### Device
Fingerprint: `samsung/d2sxx/d2s:11/RP1A.200720.012/N975FXXU6FUBD:user/release-keys`

**Comment by d4rken** [comment]
Can you tell me more about this?

**Comment by geoffsterr** [comment]
> Can you tell me more about this?

Hey,

yeah I noticed this folder appear which was kinda strange to place it there.

I checked all my logs and narrow it down to 3 apps that run at the time stamp

I deleted and reinstalled one by one from play store and found it was put there by the Samsung Thailand galaxy gift app.

I can send you the APK for it if you want.

The link to that app is
https://play.google.com/store/apps/details?id=com.samsung.privilege

I logged out and in to app today again, and the folder is back, the best I can work out is it's encrypting something and sending or receiving it

**Comment by geoffsterr** [comment]
![Screenshot_20210411-001559_My Files](https://user-images.githubusercontent.com/78266966/114278702-35306e80-9a5b-11eb-9c69-c07c9a6c143b.jpg)
![Screenshot_20210411-001607_My Files](https://user-images.githubusercontent.com/78266966/114278708-3e214000-9a5b-11eb-848e-ddc88e62dc25.jpg)

**Comment by d4rken** [comment]
What is inside those text files?

**Comment by geoffsterr** [comment]
a string of numbers and letters I'm assuming the keys
