### ISSUE TITLE
Bug: App Cleaner not working on Vivo Funtouch 11

### ISSUE THREAD

**Issue by ianz56** [d4rken/sdmaid-public#4758]
### What happened?
I have clicked on cleanup but SD Maid looks like it can't touch the Storage and Cache options, and in Indonesian it can't even touch "Penyimpanan & Cache"

### What did you expect to happen?
I expected the app cleaner can work either in English or Indonesian

### How can I reproduce the issue?
I clicked clean up but it couldn't work like it couldn't touch

### SD Maid
Version: `5.1.0 (50100)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `Unknown`
Fingerprint: `vivo/2026/2026:10/QP1A.190711.020/compiler03232317:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debuglog of this.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by ianz56** [comment]
Okay, thank you
Here's the link from the log https://drive.google.com/file/d/18zABW77Co3nP8hJJYJIBlk1ISvPD9VMs/view?usp=drivesdk
