### ISSUE TITLE
Clutterreport: /storage/emulated/0/.adjson_data.txt (new)

### ISSUE THREAD

**Issue by jamea1986** [d4rken/sdmaid-public#4766]
### Target
Target: `/storage/emulated/0/.adjson_data.txt`
Prefix-free: `.adjson_data.txt`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Adapt Sound`
Packagename: `com.sec.hearingadjust`
Version: `9.0.56 (905600000)`

### Current owners
None

### SD Maid
Version: `5.0.11 (50011)`

### Device
Fingerprint: `samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXSFFUB3:user/release-keys`

**Comment by d4rken** [comment]
Can you tell me more about this?
