### ISSUE TITLE
Won't clean

### ISSUE THREAD

**Issue by submisery** [d4rken/sdmaid-public#4778]
Since update to android 11 there is two files I will attach that sdmaid isn't cleaning. 
![Screenshot_20210414-105502_SD Maid](https://user-images.githubusercontent.com/82524833/114731941-20c8cc00-9d10-11eb-865e-9b3f639a9076.jpg)

**Comment by d4rken** [comment]
Did you enable https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#accessibility-service
