### ISSUE TITLE
ZIP - can not unzip on external sd

### ISSUE THREAD

**Issue by dukelc** [d4rken/sdmaid-public#478]
Can not unzip on external sd. (exfat) 
On internal the same file - unziping as it should.

Phone galaxy s4 i9505
Android 6.0.1

Logs should be in bug repport.

**Comment by d4rken** [comment]
Can you record a debug log?

When you turn on debug mode (i.e. during a debug run setting to debuglevel 2), in Overview, tap the entry for the external storage, what access mode does it display (bottom)?

**Comment by dukelc** [comment]
I dont know where to turn debug on. Cant find it in last versions. Sry. 
![screenshot_20160903-191338](https://cloud.githubusercontent.com/assets/16635770/18226556/904a5104-720c-11e6-80fe-de2ac774facf.png)

**Comment by dukelc** [comment]
![1](https://cloud.githubusercontent.com/assets/16635770/18226746/e650ad88-7210-11e6-82d5-c7e70d09e24d.png)

[sdmaid_logfile_1472925011070.zip](https://github.com/d4rken/sdmaid-public/files/453511/sdmaid_logfile_1472925011070.zip)

**Comment by d4rken** [comment]
Long press the settings entry.

See https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug for more info on that stuff.

Thanks for the log will check it later.

**Comment by d4rken** [comment]
Good catch.
Right... Just looked at the code again and that is just not implemented...
Normal sdcard can use java based OutputStream.
External sdcard access needs either unzipping via root or using an outputstream that we get from Androids Storage Access Framework....

:frowning: will have to look into that.

**Comment by d4rken** [comment]
Also saw that SD Maid does not log unzipping errors, added that for the next update.

**Comment by d4rken** [comment]
Should work in the next version, a bit more work than I thought because if the user skipped the secondary storage setup and tries to extract something that requires it we have to abort and ask the user to complete the setup.
