### ISSUE TITLE
Bug: Lost Pro Version

### ISSUE THREAD

**Issue by Mass-Reports** [d4rken/sdmaid-public#4787]
### What happened?
Did a fresh reset on device. No longer can restore my purchase..(with original subscription account) 

### What did you expect to happen?
Restoration of Pro Version from app store

### How can I reproduce the issue?
Have no clue what actually happened

### Comments
Best cleaner out there!!
### SD Maid
Version: `5.1.0 (50100)`
Pro: `isPro=false || isComplete=true (unl=false, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `motorola/sofia_retail/sofia:10/QPMS30.80-63-6-8-5/a1e5d:user/release-keys`

**Comment by d4rken** [comment]
Please see:
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#google-play-is-not-showing-the-purchase
