### ISSUE TITLE
Released the update

### ISSUE THREAD

**Issue by am96t** [d4rken/sdmaid-public#4790]
Please hurry to release the stable 5.1.1 because it is a very bad app with Android 11.  And the OnePlus device in particular

**Comment by d4rken** [comment]
Feel free to use the beta.

**Comment by am96t** [comment]
App Cleaner does not delete anything.  You have opened up a second topic and shared an issue report with which you can confirm

**Comment by am96t** [comment]
> لا تتردد في استخدام الإصدار التجريبي.

App Cleaner does not delete anything.  You have opened up a second topic and shared an issue report with which you can confirm
