### ISSUE TITLE
Bug: Application Cleaner does not work

### ISSUE THREAD

**Issue by am96t** [d4rken/sdmaid-public#4800]
## What happened?
Application Cleaner does not work

### What did you expect to happen?
When I clean up and the deletion starts and I wait for him for a while and he doesn't delete anything

### How can I reproduce the issue?
Cache data needs to be accessed and deleted

### Comments
On the basis that he deletes and does himself he deletes and does not delete.  And all that was required of the requirements and did not work

Oneplus 7t pro . Oxygen 11 . hd01aa . Android 11
Model 1910

### SD Maid
Version: `5.1.1 (50101)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OnePlus/OnePlus7TPro/OnePlus7TPro:11/RKQ1.201022.002/2104060845:user/release-keys`

[sdmaid_logfile_1619401416412.txt.zip](https://github.com/d4rken/sdmaid-public/files/6373750/sdmaid_logfile_1619401416412.txt.zip)

**Comment by TheMysticS** [comment]
I think the cache cleaner will clean cache only if you grant Accessibility permissions to SD Maid. Without this permission, SD Maid can clean cache only with root permissions.

**Comment by am96t** [comment]
I am not new to programming.  And I gave him all the powers, and it did not help

**Comment by am96t** [comment]
![Screenshot_20210506-000932](https://user-images.githubusercontent.com/82843865/117209953-bf23eb00-adff-11eb-8f58-a220bfb3391a.jpg)
![Screenshot_20210506-001101](https://user-images.githubusercontent.com/82843865/117209972-c5b26280-adff-11eb-974f-950091841a48.jpg)
![Screenshot_20210506-001115](https://user-images.githubusercontent.com/82843865/117209980-c8ad5300-adff-11eb-8b70-c188fc8e2362.jpg)



Thus it appears and does not delete anything
