### ISSUE TITLE
Application cache is not cleared

### ISSUE THREAD

**Issue by am96t** [d4rken/sdmaid-public#4812]
Can I solve my problem with Oneplus 7t Pro In Android 11. Professional App Cleaner does not work and starts deleting, wait for it to complete and the cache remains the same.

**Comment by am96t** [comment]
I worked all the required conditions and was not met

**Comment by d4rken** [comment]
Please provide a debug log.

**Comment by am96t** [comment]
[sdmaid_logfile_1620182413372.txt.zip](https://github.com/d4rken/sdmaid-public/files/6424852/sdmaid_logfile_1620182413372.txt.zip)

**Comment by am96t** [comment]
> الرجاء تقديم سجل تصحيح.

[sdmaid_logfile_1620182413372.txt.zip](https://github.com/d4rken/sdmaid-public/files/6424853/sdmaid_logfile_1620182413372.txt.zip)

**Comment by TheMysticS** [comment]
I think the cache cleaner will clean cache only if you grant Accessibility permissions to SD Maid. Without this permission, SD Maid can clean cache only with root permissions.

**Comment by am96t** [comment]
I am not new to programming.  And I gave him all the powers, and it did not help

**Comment by am96t** [comment]
And the cleaning time was very long.  Nothing was cleaned.  This is the correction record above

**Comment by am96t** [comment]
![Screenshot_20210506-001115](https://user-images.githubusercontent.com/82843865/117210286-26da3600-ae00-11eb-915d-27dd8e3a3dd0.jpg)
![Screenshot_20210506-001101](https://user-images.githubusercontent.com/82843865/117210288-280b6300-ae00-11eb-8523-0b0cd7bebf02.jpg)
![Screenshot_20210506-000932](https://user-images.githubusercontent.com/82843865/117210292-28a3f980-ae00-11eb-9c2f-bc3e1a89bfce.jpg)



Thus it appears and does not delete anything

**Comment by am96t** [comment]
[sdmaid_logfile_1620182413372.txt.zip](https://github.com/d4rken/sdmaid-public/files/6594916/sdmaid_logfile_1620182413372.txt.zip)

**Comment by am96t** [comment]
[sdmaid_logfile_1620139897223.txt.zip](https://github.com/d4rken/sdmaid-public/files/6594918/sdmaid_logfile_1620139897223.txt.zip)

**Comment by am96t** [comment]
### What happened?
When I press the clean apps button and it starts cleaning, I wait for it to complete and see that it does not delete anything

### What did you expect to happen?
In the end, I see that it does not delete and the cache data remains the same

### How can I reproduce the issue?
The application must delete the cache data

### Comments
I have been suffering since previous versions with misuse and not deleting app cache.  It worked all the required powers.  My OnePlus 7T Pro.  Based on the latest Android 11 version.  Oxygen 11 global.  model 1910

[sdmaid_logfile_1620139897223.txt.zip](https://github.com/d4rken/sdmaid-public/files/6422071/sdmaid_logfile_1620139897223.txt.zip)


### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OnePlus/OnePlus7TPro/OnePlus7TPro:11/RKQ1.201022.002/2104060845:user/release-keys`

**Comment by am96t** [comment]
![Screenshot_20210608-020834](https://user-images.githubusercontent.com/82843865/121098519-aba0e100-c7fe-11eb-9f0d-58b9b0a11022.jpg)
![Screenshot_20210608-020817](https://user-images.githubusercontent.com/82843865/121098521-ad6aa480-c7fe-11eb-8b3f-2db3ec1a2cf4.jpg)

The cleaning time is very long and at the end nothing is deleted and these are screenshots of deleting the storage memory .. Correction record and all information above @d4rken

**Comment by am96t** [comment]
In the last picture
1 App size 
2 User data 
3 Cache 
4 Total

**Comment by d4rken** [comment]
Thanks for all the details, I'll look into it as soon as I have time.

**Comment by am96t** [comment]
Thank you, I hope so @d4rken

**Comment by am96t** [comment]
> Thanks for all the details, I'll look into it as soon as I have time.

Thank you, I hope so @d4rken

**Comment by d4rken** [comment]
The log does not contain the AppCleaner deletion.
You need to start the recording, perform the operation, then stop the recording.

**Comment by am96t** [comment]
> The log does not contain the AppCleaner deletion.
> You need to start the recording, perform the operation, then stop the recording.

[sdmaid_logfile_1623758324292.txt.zip](https://github.com/d4rken/sdmaid-public/files/6655559/sdmaid_logfile_1623758324292.txt.zip)

@d4rken

**Comment by am96t** [comment]
> The log does not contain the AppCleaner deletion.
> You need to start the recording, perform the operation, then stop the recording.

[sdmaid_logfile_1623773874443.txt.zip](https://github.com/d4rken/sdmaid-public/files/6657151/sdmaid_logfile_1623773874443.txt.zip)

@d4rken

**Comment by d4rken** [comment]
According to the log, SD Maid was still in english, or at least the systems primary language was english, not sure why that is, but from the log I could see that the label SD Maid would look for in Arabic was new.

```
                "التخزين وذاكرة التخزين المؤقت", <--- previously
                // OnePlus/OnePlus7TPro/OnePlus7TPro:11/RKQ1.201022.002/2105071700:user/release-keys
                "مساحة التخزين وذاكرة التخزين المؤقت" <--- your device
```

Please report back after 5.1.5 is available (maybe this weekend).

**Comment by am96t** [comment]
Hello dear, I did a reboot of the phone and then made a new debug log.. I need the application very necessary and my phone is not accepted without it and I have 6 months waiting.. to do it for me please
@d4rken 

[sdmaid_logfile_1623957502505.txt.zip](https://github.com/d4rken/sdmaid-public/files/6672731/sdmaid_logfile_1623957502505.txt.zip)

**Comment by am96t** [comment]
> According to the log, SD Maid was still in english, or at least the systems primary language was english, not sure why that is, but from the log I could see that the label SD Maid would look for in Arabic was new.
> 
> ```
>                 "التخزين وذاكرة التخزين المؤقت", <--- previously
>                 // OnePlus/OnePlus7TPro/OnePlus7TPro:11/RKQ1.201022.002/2105071700:user/release-keys
>                 "مساحة التخزين وذاكرة التخزين المؤقت" <--- your device
> ```
> 
> Please report back after 5.1.5 is available (maybe this weekend).



> According to the log, SD Maid was still in english, or at least the systems primary language was english, not sure why that is, but from the log I could see that the label SD Maid would look for in Arabic was new.
> 
> ```
>                 "التخزين وذاكرة التخزين المؤقت", <--- previously
>                 // OnePlus/OnePlus7TPro/OnePlus7TPro:11/RKQ1.201022.002/2105071700:user/release-keys
>                 "مساحة التخزين وذاكرة التخزين المؤقت" <--- your device
> ```
> 
> Please report back after 5.1.5 is available (maybe this weekend).

I sent you a new debug log, end of 505, I think this log will do more than the one before

@d4rken Thank you very much for your effort ❤️

**Comment by am96t** [comment]
> According to the log, SD Maid was still in english, or at least the systems primary language was english, not sure why that is, but from the log I could see that the label SD Maid would look for in Arabic was new.
> 
> ```
>                 "التخزين وذاكرة التخزين المؤقت", <--- previously
>                 // OnePlus/OnePlus7TPro/OnePlus7TPro:11/RKQ1.201022.002/2105071700:user/release-keys
>                 "مساحة التخزين وذاكرة التخزين المؤقت" <--- your device
> ```
> 
> Please report back after 5.1.5 is available (maybe this weekend).

I sent you a new debug log, end of 505, I think this log will do more than the one before

@d4rken Thank you very much for your effort ❤️

**Comment by am96t** [comment]
Mr. Matthias Urhahn, do you hear me
@d4rken

**Comment by am96t** [comment]
#4808

**Comment by am96t** [comment]
Mr. Matthias Urhahn @d4rken ، I am waiting for an answer from you, what happened?
The log I sent you last reads right

**Comment by am96t** [comment]
I have a lot of work and I have freed up to complete this problem

**Comment by am96t** [comment]
I have 6 months unable to use the app and two months ago I have been waiting for my issue to be resolved and there is no answer so far

> I submitted a new record..

@d4rken !

**Comment by am96t** [comment]
[sdmaid_logfile_1623957502505.txt.zip](https://github.com/d4rken/sdmaid-public/files/6680396/sdmaid_logfile_1623957502505.txt.zip)

**Comment by d4rken** [comment]
Thanks for the logs.
Please wait for the next update and record a new log if it does not work yet and post it here.

**Comment by am96t** [comment]
> Thanks for the logs.
> Please wait for the next update and record a new log if it does not work yet and post it here.

Sorry to bother you sir.  But imagine my favorite app is not working for me.. This platform log is in Arabic
@d4rken

**Comment by am96t** [comment]
Did you look at the last record?
@d4rken

**Comment by am96t** [comment]
Done successfully, thanks

**Comment by am96t** [comment]
But there is an application in the system in which the cache is not deleted, how do I tell you that

**Comment by am96t** [comment]
Done successfully, thanks
