### ISSUE TITLE
Bug: Caches not being cleared/deleted

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#4817]
### What happened?
AppCleaner can't clear app caches on Oppo A3s

### What did you expect to happen?
AppCleaner should clean app caches but doesn't clear it, even just one app cache, accessibility permission is granted and tried rebooting the device and still doesn't clear the cache

### How can I reproduce the issue?
You'll need Oppo A3s device and let AppCleaner finished scanning and press delete

### Comments
Device details: Oppo A3s (CPH1803), ColorOS V5.2.1 based on Android 8.1.0
### SD Maid
Version: `5.1.2 (50102)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OPPO/CPH1803/CPH1803:8.1.0/OPM1.171019.026/1595220200:user/release-keys`

**Comment by am96t** [comment]
Also I have two devices and app cleaner doesn't work with them.  oneplus 7t pro.  Built on Android 11

**Comment by d4rken** [comment]
Please provide a debug log for this.

**Comment by dragonGod97677** [comment]
[sdmaid_logfile_1620179626609.txt](https://github.com/d4rken/sdmaid-public/files/6424745/sdmaid_logfile_1620179626609.txt)

**Comment by d4rken** [comment]
According to the debug log ColorOS Android 8.1 already uses the newer UI layout, SD Maid was only using for Android 9.0+.
I've lowered the cutoff to 8.0 for the next update.
