### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android (FP)

### ISSUE THREAD

**Issue by Grivankoss** [d4rken/sdmaid-public#4819]
### Target
Target: `/storage/emulated/0/Android`
Prefix-free: `Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Mobile Legends: Bang Bang`
Packagename: `com.mobile.legends`
Version: `1.5.70.6241 (15706241)`

### Current owners
~~Appname: `Система Android`~~
~~Packagename: `android`~~
~~Version: `8.1.0 (27)`~~

### SD Maid
Version: `5.0.11 (50011)`

### Device
Fingerprint: `HONOR/DUA-L22RU/HWDUA-M:8.1.0/HONORDUA-L22/1.0.0.156(C10):user/release-keys`

**Comment by dragonGod97677** [comment]
Mobile legends doesn't own the android folder
