### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/gF8tcmVh.apk.part (FP)

### ISSUE THREAD

**Issue by hjb17710530** [d4rken/sdmaid-public#482]
### Target
Target: `/storage/emulated/0/Download/gF8tcmVh.apk.part`
Prefix-free: `Download/gF8tcmVh.apk.part`
Path-prefix: `/storage/emulated/0/`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Flyme系统服务`~~
~~Packagename: `android`~~
~~Version: `5.1-1472436137 (22)`~~

### SD Maid
Version: `4.3.0 (40300)`

### Device
Fingerprint: `Meizu/meizu_m3note/m3note:5.1/LMY47I/1472436137:user/release-keys`

**Comment by d4rken** [comment]
The system (`android`) is the default owner of all directories that are created on an empty stock ROM.
This includes the Download directory and it's children.
