### ISSUE TITLE
sd maid error

### ISSUE THREAD

**Issue by frostjoker21** [d4rken/sdmaid-public#4821]
sd maid is stuck on this 
![Screenshot_20210504-153336_SD Maid](https://user-images.githubusercontent.com/83597735/116967805-20f43000-acee-11eb-9555-48f52cbd8862.jpg)

**Comment by d4rken** [comment]
Please provide a debug log.

SD Maid seems to need SAF based access for scanning your storage ( you likely have Android 11?), this may be very slow, but it's currently the only way to access certain areas.
