### ISSUE TITLE
Power consumption

### ISSUE THREAD

**Issue by rojinvgeorge** [d4rken/sdmaid-public#4822]
device:Realme 3 pro
Stock android 10
Device not rooted
Sdmaid version 5.0.11
Unlocked version 4.4.1
Id:2ad5e96c-abe9-489e-8bb4-728248f0b206
*This application consuming more battery 
*After I checked by device phone usage graph I found this application is consuming more battery
*I stopped the force of the application but nothing changes.
*Yes,it is always happening
Log:https://drive.google.com/file/d/1abmk2xls_fjZZTWW0wWacPPlTIs61tUm/view?usp=drivesdk

**Comment by d4rken** [comment]
SD Maid will consume a lot of power when you run it.
If you don't run it no power is consumed.

Please share more details.

**Comment by rojinvgeorge** [comment]
Sir, I think this application only run in night... because I enabled scheduler in night time.but it consumes more battery
