### ISSUE TITLE
Bug: Cache App Cleaner does not delete anything

### ISSUE THREAD

**Issue by am96t** [d4rken/sdmaid-public#4825]
### What happened?
When I press the clean apps button and it starts cleaning, I wait for it to complete and see that it does not delete anything

### What did you expect to happen?
In the end, I see that it does not delete and the cache data remains the same

### How can I reproduce the issue?
The application must delete the cache data

### Comments
I have been suffering since previous versions with misuse and not deleting app cache.  It worked all the required powers.  My OnePlus 7T Pro.  Based on the latest Android 11 version.  Oxygen 11 global.  model 1910

[sdmaid_logfile_1620139897223.txt.zip](https://github.com/d4rken/sdmaid-public/files/6422071/sdmaid_logfile_1620139897223.txt.zip)

### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OnePlus/OnePlus7TPro/OnePlus7TPro:11/RKQ1.201022.002/2104060845:user/release-keys`

**Comment by TheMysticS** [comment]
I think the cache cleaner will clean cache only if you grant Accessibility permissions to SD Maid. Without this permission, SD Maid can clean cache only with root permissions.

**Comment by am96t** [comment]
And the cleaning time was very long.  Nothing was cleaned.  This is the correction record above

**Comment by am96t** [comment]
I am not new to programming. And I gave him all the powers, and it did not help

**Comment by am96t** [comment]
> I think the cache cleaner will clean cache only if you grant Accessibility permissions to SD Maid. Without this permission, SD Maid can clean cache only with root permissions.

I am not new to programming. And I gave him all the powers, and it did not help

**Comment by am96t** [comment]
![Screenshot_20210506-001115](https://user-images.githubusercontent.com/82843865/117210426-525d2080-ae00-11eb-8035-7b29ab37a6f6.jpg)
![Screenshot_20210506-001101](https://user-images.githubusercontent.com/82843865/117210429-538e4d80-ae00-11eb-8da9-ca2bad069f57.jpg)
![Screenshot_20210506-000932](https://user-images.githubusercontent.com/82843865/117210431-5426e400-ae00-11eb-90bb-3bb868bac0f3.jpg)



Thus it appears and does not delete anything

**Comment by dragonGod97677** [comment]
Same as my issue https://github.com/d4rken/sdmaid-public/issues/4817

**Comment by am96t** [comment]
@d4rken help

**Comment by dragonGod97677** [comment]
@am96t don't mention d4rken went not needed, im 
sure he already doing something

**Comment by am96t** [comment]
> @am96t don't mention d4rken when not needed, im
> sure he already doing something. Just wait

Ok, thank you

**Comment by am96t** [comment]
> نفس [مشكلتي رقم 4817](https://github.com/d4rken/sdmaid-public/issues/4817) لكن جهاز مختلف

We hope that the problems will be solved

**Comment by SaberAkiyama** [comment]
Mine was same. I checked "Show inaccessible items" and checked "Accessibility Service", scan and run in AppCache, and it's skipped the app are inaccessible. Others are cleaned.

By the way, mine was a different device.

**Comment by am96t** [comment]
> Mine was same. I checked both "Show inaccessible items" and "Accessibility Service", scan and run in AppCache, and it's skipped the app are inaccessible (known as "private cache data"). Others are cleaned.
> 
> By the way, mine was a different device.


I am not new to programming. And I gave him all the powers, and it did not help

Thank you, I have a second device that is cleaning and it's normal

**Comment by am96t** [comment]
4 months ago, I did not use the app.  About a month ago I sent the problem.  where are you?
@d4rken

**Comment by dragonGod97677** [comment]
> 4 months ago, I did not use the app. About a month ago I sent the problem. where are you?
@am96t 
Hey am96t, i already said last may 12, mention only d4rken when really needed, programming is not fast and easy, d4rken is thankful for me and you and others reporting bugs for him to fix (im sure for it even i didn't talk to him  personally or online), just wait for the app get updated, and once it get updates, download it and try, if still doesn't work, just comment here and if he ask for something follow it also don't do closing, reopen, closing a issue here, i been receiving an email that this issue is being closed then reopened then closed, it's annoying

**Comment by d4rken** [comment]
@dragonGod97677 :point_up: is correct.

I just currently lack time to work on all issues. Android keeps constantly changing :cold_sweat:. I can't give any ETAs.
The best thing to do is to just open a ticket with enough information for me to fix it, and provide additional details if asked for (usually a debug log). I'm very happy about the active participation from a few of the regulars here :heart:.

The worst thing to do is opening/closing tickets, creating duplicates, or messaging me on multiple fronts. 
It just unnecessarily consumes my time. 
Please be nice, I don't want to have to exclude anyone unnecessarily.

**Comment by d4rken** [comment]
There is now information spread through multiple tickets for the same issue...

@d4rken ref #4812

**Comment by am96t** [comment]
Hello dear .. We apologize for any inconvenience .. But this is my favorite and I am unable to do without it .. And 6 months unable to use it
@d4rken  @dragonGod97677

**Comment by dragonGod97677** [comment]
> Hello dear.. we apologize for any inconvenience.. but this is my favorite app and I can't do without it.. and 6 months unable to use it.


@am96t well we dont have any choice but to wait for the update, there's another option of clearing cache which is doing it manually

 What im doing right now while waiting for the update is using sd maid app cleaner to scan which app is having big cache and then  i clear it via settings

**Comment by rbrband** [comment]
Tedious multi-scan apps, ends, zero delete. New device TCL A3 A509DL. Accessibilility feature and file access enabled. SD Maid insists upon both internal men and SD card both being enabled--both are then "skipped, " anyway  All I desire is app caches and internal to be enabled and then to be cleaned. Considering just uninstalling. $10 pro version. Android 11.
