### ISSUE TITLE
Bug: Too much time cleaning

### ISSUE THREAD

**Issue by Imwaycloud** [d4rken/sdmaid-public#4826]
### What happened?
It takes almost 4X the time to clean, comparing it with One UI 2.5.

### What did you expect to happen?
It took a lot to clean apps, and it got stuck on some.

### How can I reproduce the issue?
Cleaning on One UI 2.5 vs One UI 3.1. Using a Galaxy A50 without root.

### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a50ub/a50:11/RP1A.200720.012/A505GUBU7CUC2:user/release-keys`

Install ID: f95d2737-f2f0-45cb-a03c-522e39f7a01f
Model number: Galaxy A50
Android versión: 11 (One UI 3.1)

**Comment by Imwaycloud** [comment]
[sdmaid_logfile_1620136479545.txt.zip](https://github.com/d4rken/sdmaid-public/files/6422181/sdmaid_logfile_1620136479545.txt.zip)

**Comment by patpolster** [comment]
> ### What happened?
> 
> It takes almost 4X the time to clean, comparing it with One UI 2.5.
> ### What did you expect to happen?
> 
> It took a lot to clean apps, and it got stuck on some.
> ### How can I reproduce the issue?
> 
> Cleaning on One UI 2.5 vs One UI 3.1. Using a Galaxy A50 without root.
> ### Comments
> ### SD Maid
> 
> Version: `5.1.4 (50104)`
> Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`
> ### Device
> 
> Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
> Fingerprint: `samsung/a50ub/a50:11/RP1A.200720.012/A505GUBU7CUC2:user/release-keys`
> 
> Install ID: f95d2737-f2f0-45cb-a03c-522e39f7a01f
> Model number: Galaxy A50
> Android versión: 11 (One UI 3.1)

**Comment by d4rken** [comment]
Did the Android version change?

If One UI 3.1 is Android 11, and One UI 2.5 is Android 10 or lower, then the slow down is caused by Google restricting file access further via scoped storage. The remaining ways to access files (through storage access framework SAF) is 100x slower than the previous options that were available.

Additional permissions may become available this month, and I'll see if that makes it faster, but currently there is nothing to be done from my end. You can skip granting SD Maid SAF permission, then it will be faster, but SD Maid will find less :shrug:

**Comment by Imwaycloud** [comment]
> Did the Android version change?
> 
> If One UI 3.1 is Android 11, and One UI 2.5 is Android 10 or lower, then the slow down is caused by Google restricting file access further via scoped storage. The remaining ways to access files (through storage access framework SAF) is 100x slower than the previous options that were available.
> 
> Additional permissions may become available this month, and I'll see if that makes it faster, but currently there is nothing to be done from my end. You can skip granting SD Maid SAF permission, then it will be faster, but SD Maid will find less :shrug: 
> 

Yeah the Android versión change, android 11 is One UI 3.1.

Damn, I didn't know that. :(
No problem then, hope that maybe the additional permissions help a little. Thanks for your hard work.

**Comment by NikhilSudhakaranVG** [comment]
After updating to sdmaid 5.1.4 facing the same issue on ONEUI 3.1. system cleaner function taking too much time

**Comment by Imwaycloud** [comment]
> After updating to sdmaid 5.1.4 facing the same issue on ONEUI 3.1. system cleaner function taking too much time

Sorry but it's not fault of the dev.
