### ISSUE TITLE
IOException thrown when trying to get back from directory /storage/emulated/0 in SystemExplorer

### ISSUE THREAD

**Issue by Solomon1732** [d4rken/sdmaid-public#483]
When in head directory (mentioned above) I expect the "back" button to open the menu, and then exit with more presses (like in the other places in the app). Instead it throws and IOException.

Steps to reproduce:

1) Enter SystemExplorer
2) Go to said directory (if not there)
3) Press the green button
4) Press the Android "back" button

At this point an exception should be thrown.
![screenshot_2016-09-07-13-00-35](https://cloud.githubusercontent.com/assets/16454223/18308852/04f84372-74ff-11e6-9043-b39f8642f314.png)

It shows up even if the "explore" (green) button has not been pressed:
![screenshot_2016-09-07-13-01-34](https://cloud.githubusercontent.com/assets/16454223/18308874/1eab307c-74ff-11e6-8624-13432d181c70.png)

Shows up when manually opening the menu:
![screenshot_2016-09-07-13-02-18](https://cloud.githubusercontent.com/assets/16454223/18308893/30456244-74ff-11e6-9761-08fbbd5326a7.png)

Android type: android 6 marshmallow
Phone type: LG G4 beat
Directory path: /storage/emulated/0
SD Maid version: 4.2.13

**Comment by d4rken** [comment]
I agree the current behavior isn't optiomal.
If the open the navigationdrawer on IOExceptions though wouldn't that seem confusing to the user?

**Comment by Solomon1732** [comment]
Should the user be exposed to exceptions?
I know I don't want to be exposed. Imagine having an exception message
popping up while playing Call of Duty, or using Gmail. Such an exception
might be confusing if you have no idea what an exception means. As a user
you also don't need to know such a thing exists.
Exceptions are excellent for developers, but most people aren't developers.

My intuitive expectation is for the menu to open if I'm in the root (or
this case's equivalent: /storage/emulated/0/).
Another response might be some message to the user informing them "sorry
bub, but that's as back as you can go."
This is my opinion. Perhaps a discussion would help to think of a response
more optimal than what is currently implemented?

**Comment by d4rken** [comment]
> Should the user be exposed to exceptions? I know I don't want to be exposed. 

If someone isn't possible it should be made visible to the user. I'm always in favor in making a maximum of information available.

> Imagine having an exception message popping up while playing Call of Duty, or using Gmail. Such an exception might be confusing if you have no idea what an exception means. 

A message popup is something different from a snackbar, the first keeps you from interacting which other UI elements while the snackbar does not.

> As a user you also don't need to know such a thing exists. Exceptions are excellent for developers, but most people aren't developers.

Users still need to know about errors, I agree the message is not optimal and could be replaced with "Error: something".

> My intuitive expectation is for the menu to open if I'm in the root (or this case's equivalent: /storage/emulated/0/). Another response might be some message to the user informing them "sorry bub, but that's as back as you can go." This is my opinion. Perhaps a discussion would help to think of a response more optimal than what is currently implemented?

The thing is only `/storage/emulated` is off limits, the user can press go to `/` other `/system` so it's not as far as the user can go. How far actually depends on each ROM and might be quite arbitrary...

Hm so what shall we do?

- [ ] Reword the error message

Maybe try to "jump" not accessible error messages? So if `/storage/emulated` is off limits, retry with `/storage` or `/` and once we are at `/` the default back button behavior kicks in anyways.

**Comment by Solomon1732** [comment]
Maybe both? Printing something like "/storage/emulated is not accessible,
go to /storage instead?" and giving the user a choice?

From the discussion I can see there are at least five ways to handle it:
1) Leave it as it is
2) Changing the error message
3) "Silently" jumping over /storage/emulated
4) Printing a changed error message and prompting the user with a choice to
stay in the current directory or jumping to /storage
5) Jumping without user choice and explaining the reason for it in a
snackbar (or something along the line)

**Comment by d4rken** [comment]
Just removed the IO Exception text for now, not happy with any of the alternatives.

**Comment by Solomon1732** [comment]
Seems it's the same problem trying to step from / to /emulated

**Comment by d4rken** [comment]
Yeah there are multiple locations with this behavior.

Maybe in an extra ticket we could think about allowing the explorer to "enter" these directories but display a "permission denied" in the main window instead of a list.
