### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download (FP)

### ISSUE THREAD

**Issue by Naser-Mehrgan80** [d4rken/sdmaid-public#4832]
### Target
Target: `/storage/emulated/0/Download`
Prefix-free: `Download`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `فايلهای شخصی`
Packagename: `com.sec.android.app.myfiles`
Version: `2.0.6 (1010)`

### Current owners
Appname: `سیستم Android`
Packagename: `android`
Version: `5.1.1-J320FXXU0AQL1 (22)`

~~Appname: `?`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: ` (-1)`~~

Appname: `مدیر بارگیری`
Packagename: `com.android.providers.downloads`
Version: `5.1.1-J320FXXU0AQL1 (22)`

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `samsung/j3xltejt/j3xlte:5.1.1/LMY47V/J320FXXU0AQL1:user/release-keys`

### Comment
`My files are hidden in the download folder and are not accessible please help me`

**Comment by dragonGod97677** [comment]
No, this site is only for issue tracking.
