### ISSUE TITLE
Great app but, thumbnails are not being wiped.. 

### ISSUE THREAD

**Issue by Matt8119** [d4rken/sdmaid-public#484]
I am using the cleaner in ES file explorer pro to clear out thumbnails in /storage/emulated/0/DCIM/.   How about adding this as an option in the tools menue as an option to clean out. I'm averaging 800mb to 1 gigabyte a day each time I it cleared out...

**Comment by dukelc** [comment]
Delete folder thumbnails. Create file .thumbnails and newer have to clean it. Easy.

**Comment by dukelc** [comment]
![1](https://cloud.githubusercontent.com/assets/16635770/18327765/434c155c-754c-11e6-9010-9b98cbb7be64.png)

You have checket thumbnails to delete in system cleaner?

And btw. - Why you not just delete thumbnail folder, create file .thumbnail and have never to clean it again?

**Comment by d4rken** [comment]
I think this is solved, otherwise reopen.
