### ISSUE TITLE
[Query]SD Maid Pro unlocker for both mobile & Shield

### ISSUE THREAD

**Issue by onlytanmoy** [d4rken/sdmaid-public#4842]
Hiya @d4rken hope you are doing well. I got a query regarding purchasing the SD Maid app.
Please read my post in the below sdmaid subreddit

https://www.reddit.com/r/sdmaid/comments/n9ak98/sd_maid_on_shield_tv_pro/gxn85jd/?context=3

As the other user mentioned there- can I purchase a serial key such that I can use the Pro version of SD Maid in both my android phone and Shield TV device?

**Comment by d4rken** [comment]
You can obtain a key via apps.darken.eu and then grap the apk directly via https://sdmaid.darken.eu/download/
