### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.android.vending (FP)

### ISSUE THREAD

**Issue by texasred593** [d4rken/sdmaid-public#4846]
### Target
Target: `/storage/emulated/0/Android/data/com.android.vending`
Prefix-free: `com.android.vending`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Google Partner Setup`
Packagename: `com.google.android.partnersetup`
Version: `100.327071041 (1184)`

Appname: `3 Button Navigation Bar`
Packagename: `com.android.internal.systemui.navbar.threebutton`
Version: `1.0 (1)`

### Current owners
~~Appname: `Google Play Store`~~
~~Packagename: `com.android.vending`~~
~~Version: `25.2.22-21 [0] [PR] 371378105 (82522210)`~~

### SD Maid
Version: `5.0.11 (50011)`

### Device
Fingerprint: `motorola/guamna_retail/guamna:10/QZAS30.Q4-39-35-4/e50cb:user/release-keys`

**Comment by dragonGod97677** [comment]
/storage/emulated/0/Android/data/com.android.vending is owned only by google play store, close this issue
