### ISSUE TITLE
owners/system/product/bin /system/product/lib64 /system/product/usr /system/product/etc /system/product/priv-app /system/product/framework /system/product/build.prop /system/product/lib /system/product/app /system/product/overlay: /system/fonts (FP)

### ISSUE THREAD

**Issue by Shi1192** [d4rken/sdmaid-public#4847]
### Target
Target: `/system/fonts`
Prefix-free: `fonts`
Path-prefix: `/system/`
Type: `DIRECTORY`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `External Storage`
Packagename: `com.android.externalstorage`
Version: `10 (29)`

### Current owners
None

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `xiaomi/daisy/daisy_sprout:10/QKQ1.191002.002/V11.0.18.0.QDLMIXM:user/release-keys`

**Comment by dragonGod97677** [comment]
No, com.android.externalstorage doesn't own any files outside of its private folder
