### ISSUE TITLE
Clutterreport: /data/data/com.keramidas.TitaniumBackup

### ISSUE THREAD

**Issue by zputnyq** [d4rken/sdmaid-public#4861]
Target
Target: /data/data/com.keramidas.TitaniumBackup
Prefix-free: com.keramidas.TitaniumBackup
Path-prefix: /data/data/
Type: DIRECTORY
Location: 
Current keeper state: 
Suggested keeper state: 

Suggested owners
Appname: Titanium Backup
Packagename: com.keramidas.TitaniumBackup
Version: 8.4.0.2

SD Maid
Version: 5.1.4 (50104)

Device
Fingerprint: Sony/MSM8916_for_arm64/tulip_ss:6.0.1/1.0.J.0.0/174:user/test-keys

Comment
Titanium backup seems no longer gets updated. On its release v 8.4.0.2 which might be its latest release, there is probably an uninstallation bug that causes a leftover in /data/data. This leftover also causes a failure on its re-installation.

**Comment by d4rken** [comment]
This should already be picked up by default, ,is that not working?

**Comment by zputnyq** [comment]
Yes that's not working.

**Comment by zputnyq** [comment]
My mistake, it's working. Probably something happen on my device at that time so the cleaning didn't work.

**Comment by d4rken** [comment]
SD Maid may not have known yet that the TiBu was uninstalled, restarting SD Maid may have helped.

**Comment by zputnyq** [comment]
Ok, thx for this information
