### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/recovery.img (FP)

### ISSUE THREAD

**Issue by bshurtle** [d4rken/sdmaid-public#487]
### Target
Target: `/storage/emulated/0/Download/recovery.img`
Prefix-free: `Download/recovery.img`
Path-prefix: `/storage/emulated/0/`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `InstallerOpt`
Packagename: `net.fypm.InstallerOpt`
Version: `1.0.6 (84) (1095)`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `6.0.1 (23)`~~

### SD Maid
Version: `4.3.0 (40300)`

### Device
Fingerprint: `samsung/on5ltemtr/on5ltemtr:6.0.1/MMB29K/G550T1UVU1APF1:user/release-keys`

**Comment by d4rken** [comment]
Thanks for the report, but I don't think `InstallerOpt` owns this file.
It seems to be an XposedModule dealing with the packageinstaller anod not anything recovery related.
