### ISSUE TITLE
Clutterreport: /storage/emulated/0/Pictures/facebook

### ISSUE THREAD

**Issue by kshitijpatil** [d4rken/sdmaid-public#4873]
### Target
Target: `/storage/emulated/0/Pictures/facebook`
Prefix-free: `Pictures/facebook`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Facebook`
Packagename: `com.facebook.katana`
Version: `318.0.0.39.154 (283621045)`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.facebook.lite`~~
~~Version: ` (-1)`~~

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `google/sargo/sargo:11/RQ2A.210505.002/7246365:user/release-keys`

**Comment by nkr4449** [comment]
> ### Target
> Target: `/storage/emulated/0/Pictures/facebook`
> Prefix-free: `Pictures/facebook`
> Path-prefix: `/storage/emulated/0/`
> Type: `DIRECTORY`
> Location: `SDCARD`
> Current keeper state: `true`
> Suggested keeper state: `true`
> 
> ### Suggested owners
> Appname: `Facebook`
> Packagename: `com.facebook.katana`
> Version: `318.0.0.39.154 (283621045)`
> 
> ### Current owners
> ~~Appname: `?`~~
> ~~Packagename: `com.facebook.lite`~~
> ~~Version: ` (-1)`~~
> 
> 
> ### SD Maid
> Version: `5.1.4 (50104)`
> 
> ### Device
> Fingerprint: `google/sargo/sargo:11/RQ2A.210505.002/7246365:user/release-keys`
> 
>
