### ISSUE TITLE
Bug: AppCleaner not deleting files

### ISSUE THREAD

**Issue by bkmillerjr** [d4rken/sdmaid-public#4875]
### What happened?
I have SDMaid Pro. Quick Access is the set Default (with 2-step option to Remove identified files).  When completed, Remove has cleared all identified files EXCEPT those identified by AppCleaner.

### What did you expect to happen?
AppCleaner "scanned/removable" files' size continues to increase, while the deleted files' size is relatedly Zero.  When SDMaid worked as expected, "All" or "Most" files identified for removal would, in-fact, be reoved. 

### How can I reproduce the issue?
My attempts at "debug recording and submission" have failed.

### Comments
GitHub.com provides competent and well-written/illustrated support by exerts.  "User Competence" is beyond GitHub.com's control!! I fit into the "Novice/Beginner" Category, if lucky. So, does an  "SDMaid for Idiots" source I might try?
### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `motorola/river/river:10/QPUS30.52-23-13-4/d00bb5:user/release-keys`

**Comment by d4rken** [comment]
Without a debuglog there is not much I can do here.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
