### ISSUE TITLE
Bug: AppCleaner not cleaning up

### ISSUE THREAD

**Issue by MazeWolf** [d4rken/sdmaid-public#4877]
### What happened?
AppCleaner mentioned 1.71 GB could be cleaned. After pressing "Clean" only 259 MB were cleaned

### What did you expect to happen?
The expected amount of space displayed to be cleaned shall be cleaned up. 

### How can I reproduce the issue?
Go to "Quick menu" try to clean up and see what happens

### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Sony/H8324/H8324:10/52.1.A.3.49/052001A003004902006556692:user/release-keys`

**Comment by JeffHorinzon** [comment]
Hi, friendly volunteer Spirit here!
Just to make sure you've checked this:
1) Have you turned on Accessibility Service on the AppCleaner settings?

If you have, do let me know your device name (optionally, also it's cute Codename manufacturers give to each model xD) and your OS version
For example: 
Redmi Note 7 (Lavender)
MIUI 12.0.1, Android 10

I hope to be able to help you somehow until the developer himself attends to you.  Thanks for understanding :3

**Comment by JeffHorinzon** [comment]
> Hi, friendly volunteer Spirit here!
> Just to make sure you've checked this:
> 1) Have you turned on Accessibility Service on the AppCleaner settings?
> 
> If you have, do let me know your device name (optionally, also it's cute Codename manufacturers give to each model xD) and your OS version
> For example: 
> Redmi Note 7 (Lavender)
> MIUI 12.0.1, Android 10
> 
> I hope to be able to help you somehow until the developer himself attends to you.  Thanks for understanding :3

Forgive me for being an idiot.  I just noticed the [Fingerprint] section.  A Sony user huh.  I suppose Darken might have not brought Accessibility support to it before.  
Here's an explanation to it: https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting


You may need to record an ACS Debug Log and submit it here.  Where he can obtain the data and bring support to your OS and device.
Here's a read up of what you will need to gather exactly.  Lemme know if you need assistance :3
https://github.com/d4rken/sdmaid-public/issues/2802

**Comment by MazeWolf** [comment]
No problem. I feel like an idiot for not finding the accessibility service setting by myself and activating it :) 
Now the app's caches are cleaned up nicely.

Thank you so much for friendly and timely response.
