### ISSUE TITLE
Bug: com.google.android.cellbroadcastreciever causes AppCleaner hang on S21 Ultra

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#4881]
### What happened?
Ran the AppCleaner as normal on a new phone, and it got stuck on Wireless Emergency Alerts. I had to cancel to stop it.

### What did you expect to happen?
The item should be skipped as an exclude as the "clear cache" button is permanately disabled.

### How can I reproduce the issue?
Get an S21 with the latest updates (May 2021 Android 11) and run the AppCleaner.

### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/p3quew/p3q:11/RP1A.200720.012/G998U1UEU3AUDD:user/release-keys`

**Comment by d4rken** [comment]
Covered by ##5077
