### ISSUE TITLE
Bug: AppCleaner gets stuck on com.google.android.providers.media.module (S21 Ultra, May 2021 update)

### ISSUE THREAD

**Issue by mcl21014** [d4rken/sdmaid-public#4884]
### What happened?
AppCleaner hangs up on com.google.android.providers.media.module in the exact same way as with Wireless Emergency Alerts. Cleaning does not proceed 

### What did you expect to happen?
Cleaning should progress as normal.

### How can I reproduce the issue?
Get an S21 and use it for a while (had mine for a week until this happened) and run the AppCleaner. Unsure of exactly how to get SD Maid to notice this. Try setting AC minimum size to 0 bytes.

### Comments
Samsung bugs suck.
### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/p3quew/p3q:11/RP1A.200720.012/G998U1UEU3AUDD:user/release-keys`

**Comment by JeffHorinzon** [comment]
Just saying
Same problem as #4739

**Comment by dragonGod97677** [comment]
Im just referencing my issue #5077 as this is not a bug, seems on Android 11+, android doesn't want apps or the user clear cache or data on that app

Also #4881

**Comment by d4rken** [comment]
Covered by the #5077 fix
