### ISSUE TITLE
The op/s speed of the system cleaner is too slow.

### ISSUE THREAD

**Issue by rockybear67** [d4rken/sdmaid-public#4886]
The model I'm using is the Galaxy Note 20 Ultra model, and it was fine in Android 10 version, but after updating to version 11, the search speed of the system cleaner was completely slow.

I checked it to see if it was a problem with the memory speed of my phone, but the memory speed was normal.  Could it be a bug that caused the system cleaner's search speed to be slow?  Or is there another reason?

The search speed is so slow that I think that 100 million years have passed when it was all completed.

![Screenshot_20210529-034430_SD Maid](https://user-images.githubusercontent.com/7418669/120059654-d320dc80-c08d-11eb-8c27-1105f8ef4805.png)

**Comment by pepperary** [comment]
mee too, I have the same issue. I am a user using Galaxy s20 and Android 11. The system clean function took too long, so I can't use sd maid app.

**Comment by rockybear67** [comment]
> mee too, I have the same issue. I am a user using Galaxy s20 and Android 11. The system clean function took too long, so I can't use sd maid.

It seems that the developers had a plan to make us old and kill us.  I've already asked my friends to pre-order the mummy coffin as well.

**Comment by JavkhlanK** [comment]
That's an issue of Android 11. It enforces a new storage model (scoped storage), which makes regular file operations except those in known media locations (/Internal storage/Android/media/<package name>/... for example) awfully slow. There isn't much app developers can do, sadly.

**Comment by d4rken** [comment]
@JavkhlanK Is correct. The new method (SAF based) is much slower, but that's because no other way has been left by Google.

The choice is basically between "slow" and "don't scan everything".

Same report here #4826

Change was added here #4571.

I'm still exploring other options, but it's an uphill battle :frowning_face:.

**Comment by krzysztof293** [comment]
czw., 3 cze 2021, 19:45 użytkownik Matthias Urhahn ***@***.***>
napisał:

**Comment by d4rken** [comment]
5.1.6 should improve this a lot.
