### ISSUE TITLE
Track and remove orphan folders

### ISSUE THREAD

**Issue by colemar** [d4rken/sdmaid-public#490]
Certain apps when uninstalled leave behind a folder (not empty) in the root of the main storage.
Example: GetThemAll (com.fvd) creates `/storage/emulated/0/GetThemAll`, which is not removed by standard Android uninstall procedure.  SD Maid cannot detect it either.
I understand that often this kind of folder contains data which is valuable even after app uninstall, nonetheless some kind of warning would be nice.

Possibly related to #366

**Comment by d4rken** [comment]
The only way to currently track these is through a manual database. The database already exist but can obviously never know about all of these cases.

Please download the latest version (v4.3.2), enable experimental features and then you tap the "?" question marks in SD Maids explorer tool to generate "clutter reports" (e.g. #491 ).

I confirm these and add them with the next update.

Reporting and adding these entries not only allows SD Maid to detect them as corpses, but while the app is still installed, other tools such as the database tool, app cleaner or app control will also make us of this information.
