### ISSUE TITLE
Clutterreport: /storage/emulated/0/ViPER4Android

### ISSUE THREAD

**Issue by HankAviator** [d4rken/sdmaid-public#491]
### Target
Target: `/storage/emulated/0/ViPER4Android`
Prefix-free: `ViPER4Android`
Path-prefix: `/storage/emulated/0/`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `ViPERFX`
Packagename: `com.audlabs.viperfx`
Version: `2.5.0.5 (2505)`

### Current owners
None
### SD Maid
Version: `4.3.2 (40302)`

### Device
Fingerprint: `oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys`

**Comment by HankAviator** [comment]
The app's original name was `ViPER4Android`. The recent version changed to `ViPERFX`. Directory yet has not been modified.

**Comment by d4rken** [comment]
That would explain it. Sounds like a bug though, maybe message the developer?

**Comment by HankAviator** [comment]
I guess it'll be kept in the foreseeable future, this app's previous update was one year ago I assume. I'll keep you updated once it has changed again. Shall we add it to the database for now? Though I know it's a 'friendly fire'))

**Comment by HankAviator** [comment]
I'll email the developer as well tomorrow and see what he plans. Stay tuned.

**Comment by HankAviator** [comment]
Forgot to say, the previous version package name was `com.vipercn.viper4android_v2`. These are two different apps but still share the same data storage, as noted in report.

**Comment by d4rken** [comment]
Right, got 5 apps now for the folder.
```
{
  "pkgs": [
	"com.audlabs.viperfx",
	"com.vipercn.viper4android",
	"com.vipercn.viper4android_v2",
	"com.vipercn.viper4android_v2_fx",
	"com.vipercn.viper4android.xhifi"
  ],
  "mrks": [{"loc": "SDCARD", "path": "ViPER4Android"}]
}
```

 > Shall we add it to the database for now? Though I know it's a 'friendly fire'))

The more the better, it just needs one app<>file entry to have SD Maid match them, adding more for the same folder just decreases the change for false positives. So it's  "all or nothing".
