### ISSUE TITLE
Whatsapp folder has changed under Android 11

### ISSUE THREAD

**Issue by daywalk3r666** [d4rken/sdmaid-public#4910]
The WhatsApp folder is now under storage/android/media/com.whatapp
![Screenshot_20210605-082411_Trebuchet](https://user-images.githubusercontent.com/15938117/120914172-809e7c00-c69c-11eb-8b58-d066afe3d8d9.png)

SD Maid
Version: 5.1.4 (50104)

Device
LOS 18.1 Official OP5T

**Comment by d4rken** [comment]
Should work now, seems to be just moved.
Let me know if I missed something after the next update.

**Comment by jpabloud** [comment]
Looks like isn't working, it just detects private default cache and Cached Voiced Messages but is not detecting sent or received  pictures & videos with their respective settings enabled.

SD Maid version: 5.1.5

Device:
Samsung A71 OneUI 3.1 (Android 11)
