### ISSUE TITLE
Clutterreport: /storage/emulated/0/PHXBrowser/.cache/newqimage.thumbnail/v2.ols100.1 (new)

### ISSUE THREAD

**Issue by ahdhlh** [d4rken/sdmaid-public#4912]
### Target
Target: `/storage/emulated/0/PHXBrowser/.cache/newqimage.thumbnail/v2.ols100.1`
Prefix-free: `PHXBrowser/.cache/newqimage.thumbnail/v2.ols100.1`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Phoenix`
Packagename: `com.transsion.phoenix`
Version: `6.0.3.2730 (2730)`

### Current owners
None

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `samsung/r7naxx/r7:11/RP1A.200720.012/N770FXXU7EUE2:user/release-keys`

**Comment by niniphon** [comment]
.
