### ISSUE TITLE
Bug: [PRO] AppCleaner in Slovak language [sk] cannot hit clear cache button

### ISSUE THREAD

**Issue by petonemec** [d4rken/sdmaid-public#4913]
### Bug info
Problem found on Samsung Galaxy A40 in Slovak language (slovenčina - Slovensko).
AppCleaner goes through detected apps and opens each storage data screen, but cannot identify/hit the button "Vymazať vyrov. pamäť" for clearing the app's cache files.
Tried forcing [sk] or [sk_SK] language in SD Maid PRO without any success.
After switching phone language to English, everything works fine.

### Device info
Install ID: 17525531-7001-4d40-b18a-40e9077645a3
ROM: samsung/a40xx/a40:11/RP1A.200720.012/A405FNXXU3CUD3:user/release-keys/sk
SD Maid: 5.1.4[50104]
Pro: 1 položka ('upgrade.sdmaid.pro')
Root: false
Storage: /storage/emulated/0 (SAF-match=true)
Storage: /storage/0000-0000 (SAF-match=true)

**Comment by d4rken** [comment]
Can you provide a debuglog of it failing? https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by petonemec** [comment]
Hello,
thank you for your response.
The debuglog file is attached.

Keep up the good work.
Regards,
Peter Nemec

Dňa ne 13. 6. 2021, 12:44 Matthias Urhahn ***@***.***>
napísal(a):
