### ISSUE TITLE
AppCleaner Issues

### ISSUE THREAD

**Issue by JandNL** [d4rken/sdmaid-public#4916]
We have the latest versions of both Android and SDMaid.

When we run AppCleaner, we keep getting the message that although we have enabled accessibility, the service is not running and we should restart the device.

We have done this several times and also uninstalled and reinstalled the app.  The problem remains.  Please fix this!

**Comment by d4rken** [comment]
As far as I know, this is a ROM issue and not something I can fix on my end.
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting
