### ISSUE TITLE
Clutterreport: /storage/emulated/0/log (new)

### ISSUE THREAD

**Issue by MrJupiter65** [d4rken/sdmaid-public#4921]
### Target
Target: `/storage/emulated/0/log`
Prefix-free: `log`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `PowerDirector`
Packagename: `com.cyberlink.powerdirector.DRA140225_01`
Version: `8.2.0 (94539)`

### Current owners
None

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `ZTE/Z839/sweet:7.1.1/NMF26V/20191022.202108:user/release-keys`

**Comment by d4rken** [comment]
Can you provide more details on this?

**Comment by dragonGod97677** [comment]
I tried PowerDirector app my self for a few minutes, the app doesn't created that folder and thus not the owner of that folder
