### ISSUE TITLE
Secure wipe (feature request?)

### ISSUE THREAD

**Issue by johnsmithtetley** [d4rken/sdmaid-public#4932]
Is it possible to have a feature where the files being deleted are done so to industry standard or at least have an option of enabling this? 
I.e. HMG Infosec Standard 5, Higher Standard,
NSA 130-1, DoD 5220 etc. 

Kind regards

**Comment by d4rken** [comment]
Technically possible, with root, yes, but out of scope for this project.

**Comment by johnsmithtetley** [comment]
Okay thanks for responding.
