### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by am96t** [d4rken/sdmaid-public#4933]
How to send definitions? and what are the benefits of them?

When will 5.1.5 be released?

**Comment by dragonGod97677** [comment]
@am96t oh my goodness, dude, if you have questions don't open an issue here, also the developer, can't give to you or me or others when the next version will be released

Please be patient
Close this issue, thank you

**Comment by dragonGod97677** [comment]
Also i wanna answer your question but im kinda lost the proper words

**Comment by d4rken** [comment]
Not every file<>app relation ship, i.e. "which files belong to which app", can be recognized by SD Maid through automatic means.

A clutter report is for adding a new unknown app<>file relation to SD Maids database.

Clutter reports can be send from CorpseFinder results or by pressing the `?` icon in the explorer.

Please review other clutter reports to understand which reports are useful and which are not, before sending in new ones:
https://github.com/d4rken/sdmaid-public/issues?q=is%3Aissue+label%3A%220+c%3A+Definitions%22+is%3Aclosed

As example, reports by @Ingood5 are very good.
