### ISSUE TITLE
Reconsider my problem

### ISSUE THREAD

**Issue by am96t** [d4rken/sdmaid-public#4937]
Hello dear, I did a reboot of the phone and then made a new debug log I think this record is more useful than the previous one .. I need the application very necessary and my phone is not accepted without it and I have 6 months waiting and I closed my problem .. to do it for me please

Thank you

my problem number : #4812 
Milestone 5.1.5

new debug log

[sdmaid_logfile_1623957502505.txt.zip](https://github.com/d4rken/sdmaid-public/files/6674899/sdmaid_logfile_1623957502505.txt.zip)

**Comment by dragonGod97677** [comment]
comment that log file to your mentioned issue and close this one thank you

Please be patient for the update
Im also just waiting and also needed the app but nothing will happen if you or i just keep creating duplicate issue and keep asking for when is the update
I

**Comment by am96t** [comment]
> comment that log file to your mentioned issue and close this one thank you
> 
> Please be patient for the update
> Im also just waiting and also needed the app but nothing will happen if you or i just keep creating duplicate issue and keep asking for when is the update

Thank you for helping the developer in his busy time.  But my case is already closed and he can't see it.  And it's in turn 5.1.5
I also shared the record there

**Comment by dragonGod97677** [comment]
No, he can still see the all closed issues, if you already sent your latest debug log in your previous issue close this one

**Comment by dragonGod97677** [comment]
The Milestone named 5.1.5 is the next version of SD maid will be released soon, just wait for it
It has the fix for our issues


Im reminding you please be patient and don't add issues if the new is the same old one
