### ISSUE TITLE
Bug: AppCleaner again

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#4939]
### What happened?
Yay it clears but another problem on it

### What did you expect to happen?
Normal private app cache cleaning

### How can I reproduce the issue?
Need Oppo A3s ColorOS 5.2.1 based on Android 8.1.0 

### Comments
It clears app cache but only 1 or 2 apps. I started a scan, press delete, SD maid ask for the accessibility permission and i gave it, and i return to the AppCleaner screen, press delete again, now deletes the app public cache then started on private app cache, it deletes one ( or 2 ) app private caches and to the next app, it opens the app's storage usage screen and it stays there for an almost minute and goes to the next app and same happens, now i stopped the cleaning and tried rescanning and saw that the third app (or second app), cache was not cleared (I'll upload a video and debug log later) 
### SD Maid
Version: `5.1.5 (50105)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OPPO/CPH1803/CPH1803:8.1.0/OPM1.171019.026/1595220200:user/release-keys`

**Comment by dragonGod97677** [comment]
[sdmaid_logfile_1624152497678.txt](https://github.com/d4rken/sdmaid-public/files/6681612/sdmaid_logfile_1624152497678.txt)

**Comment by dragonGod97677** [comment]
https://www29.zippyshare.com/v/AfhKmzj5/file.html the video

**Comment by d4rken** [comment]
> https://www29.zippyshare.com/v/AfhKmzj5/file.html the video is more than 10MB so i uploaded in zippyshare

Can't access that.

**Comment by dragonGod97677** [comment]
> > https://www29.zippyshare.com/v/AfhKmzj5/file.html the video is more than 10MB so i uploaded in zippyshare
> 
> Can't access that.

Do you still want to see the video d4rken?  If you want, i can upload it to YouTube now

**Comment by d4rken** [comment]
Yes please.
The log shows that SD Maid doesn't think the screen with the "Clear cache" button is the right one.
Usually SD Maid tries to find the name of the app target on that screen.

If a video is problematic, screenshots may also work.

**Comment by dragonGod97677** [comment]
https://youtu.be/Oq60ofizjtQ here you go @d4rken

**Comment by dragonGod97677** [comment]
Here's s new log file that idk, might help [sdmaid_logfile_1624296233211.txt.zip](https://github.com/d4rken/sdmaid-public/files/6688500/sdmaid_logfile_1624296233211.txt.zip)

**Comment by d4rken** [comment]
SD Maid needs a way to determine that the OS has now opened the right window as this can take some time depending on ROM settings & animations.
Usually it's the apps name or package name. It seems on your ROM, nothing like that is available, but there is a very recognizable ID which is `com.android.settings:id/clear_cache_button` that SD Maid will look for now.

**Comment by d4rken** [comment]
Let me know how it works after this update is available.
