### ISSUE TITLE
Clutterreport: /storage/emulated/0/Samsung (FP)

### ISSUE THREAD

**Issue by Seeyou19** [d4rken/sdmaid-public#4945]
### Target
Target: `/storage/emulated/0/Samsung`
Prefix-free: `Samsung`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System WebView`
Packagename: `com.google.android.webview`
Version: `91.0.4472.101 (447210133)`

### Current owners
Appname: `Galaxy Store`
Packagename: `com.sec.android.app.samsungapps`
Version: `4.5.27.9 (452709110)`

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `samsung/a21tfn/a21:10/QP1A.190711.020/S215DLUDS3AUC1:user/release-keys`

**Comment by dragonGod97677** [comment]
Uh no, google android system webview doesn't own or creates a folder on user storage
