### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android (FP)

### ISSUE THREAD

**Issue by Adamfarrier** [d4rken/sdmaid-public#4946]
### Target
Target: `/storage/emulated/0/Android`
Prefix-free: `Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `11 (30)`~~

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `T-Mobile/5062Z/Porto:11/RKQ1.201202.002/2C65-0:user/release-keys`

**Comment by dragonGod97677** [comment]
Why removing android as owner of that folder?
