### ISSUE TITLE
Not cleaning properly the whatsapp folder.

### ISSUE THREAD

**Issue by jpabloud** [d4rken/sdmaid-public#4949]
As I said at issue #4910 :

Looks like the change of the whatsapp folder isn't working, it just detects private default cache and Cached Voiced Messages but is not detecting sent or received pictures & videos with their respective settings enabled.

![Screenshot_20210624-200700_SD Maid](https://user-images.githubusercontent.com/6853366/123353727-c7f38c00-d527-11eb-9ff0-cb1e5e8e122a.jpg)

SD Maid version: 5.1.5

Device:
Samsung A71 OneUI 3.1 (Android 11)

**Comment by jpabloud** [comment]
This isn't working for me, take a look at the screenshots.

![Screenshot_20210809-154400_SD Maid](https://user-images.githubusercontent.com/6853366/128772209-72b407b8-dc5c-4f76-bb8a-a9a1f27e09a8.jpg)
![Screenshot_20210809-154425_SD Maid](https://user-images.githubusercontent.com/6853366/128772214-c6df8456-01cf-47f9-b8db-12ad6af133ec.jpg)
![Screenshot_20210809-154432_SD Maid](https://user-images.githubusercontent.com/6853366/128772219-9d4f5a7f-ad29-4759-9588-79485f845b6f.jpg)
![Screenshot_20210809-154506_SD Maid](https://user-images.githubusercontent.com/6853366/128772220-d366d704-069e-440c-ad72-8592cd1b7c82.jpg)

**Comment by d4rken** [comment]
Thanks, I think I got it now. Let me know after the next update.

**Comment by jpabloud** [comment]
Now it's working fine, excellent job and thank you.

![Screenshot_20210810-191226_SD Maid](https://user-images.githubusercontent.com/6853366/128950847-f01bc682-3a85-4f1b-813e-e1b54f56f6dc.jpg)
![Screenshot_20210810-191238_SD Maid](https://user-images.githubusercontent.com/6853366/128950867-2c878368-f56c-43ac-8486-50ccee4afbd4.jpg)
