### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.eamobile.bejeweled2_carrier_wf (FP)

### ISSUE THREAD

**Issue by bb010g** [d4rken/sdmaid-public#4953]
### Target
Target: `/storage/emulated/0/Android/data/com.eamobile.bejeweled2_carrier_wf`
Prefix-free: `com.eamobile.bejeweled2_carrier_wf`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Bejeweled 2`
Packagename: `com.eamobile.bejeweled2_full_azn`
Version: `2.0.20 (2002000)`

### Current owners
Appname: `?`
Packagename: `com.eamobile.bejeweled2_carrier_wf`
Version: ` (-1)`

### SD Maid
Version: `5.1.4 (50104)`

### Device
Fingerprint: `google/redfin/redfin:11/RQ3A.210605.005/7349499:user/release-keys`

**Comment by Arimjj** [comment]
> ### Objetivo
> Destino: Sin `/storage/emulated/0/Android/data/com.eamobile.bejeweled2_carrier_wf`
> prefijo : Prefijo de `com.eamobile.bejeweled2_carrier_wf`
> ruta: `/storage/emulated/0/Android/data/`
> Tipo: `DIRECTORY`
> Ubicación: `PUBLIC_DATA`
> Estado de guardián actual: `false`
> Estado de guardián sugerido:`false`
> 
> ### Propietarios sugeridos
> Nombre de la aplicación: `Bejeweled 2`
> Nombre del paquete: `com.eamobile.bejeweled2_full_azn`
> Versión:`2.0.20 (2002000)`
> 
> ### Propietarios actuales
> Nombre de la aplicación: `?`
> Nombre del paquete: `com.eamobile.bejeweled2_carrier_wf`
> Versión:` (-1)`
> 
> ### SD Maid
> Versión: `5.1.4 (50104)`
> 
> ### Dispositivo
> Huella dactilar: `google/redfin/redfin:11/RQ3A.210605.005/7349499:user/release-keys`
