### ISSUE TITLE
Inconsistent colors with system in darkmode

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#4954]
### What happened?
                                   
Должны ли быть эти изменения при включении темной темы на устройстве? Цвета кнопок "сканировать" в главном меню и в каждом инструменте становятся более темными, цвет пробегающей полоски становится более темным (анимация сканирования), цвет вертикальной полоски в быстром меню становится белым.

![IMG_20210621_144916](https://user-images.githubusercontent.com/60130882/123726407-93b9fb80-d898-11eb-85f6-bd08a92a3c1f.jpg)
![IMG_20210621_145047](https://user-images.githubusercontent.com/60130882/123726410-94eb2880-d898-11eb-92fb-aba09cb72f5e.jpg)
![IMG_20210621_145107](https://user-images.githubusercontent.com/60130882/123726411-9583bf00-d898-11eb-8805-e82e3278597e.jpg)

### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.10.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
Not sure how to fix this, on my Pixel devices, the colors are not affected by the systems "light/dark" mode settings :thinking:

**Comment by Ingood5** [comment]
Это ошибка не зависит от вас?

**Comment by d4rken** [comment]
Seems ROM related, not something I can easily fix on my end.
