### ISSUE TITLE
Bug: SD Maid prevents screen timeout

### ISSUE THREAD

**Issue by ctp9** [d4rken/sdmaid-public#4962]
### What happened?
When SD Maid is open - my phone's screen timeout duration gets ignored/prevented.

### What did you expect to happen?
Screen should turn off at specified timeout regardless of SD Maid being open.

### How can I reproduce the issue?
Open SD Maid and perhaps screen timeout will be inhibited/prevented on test devices also.

### Comments
Seriously please fix this or add an option to allow/prevent screen timeout - let your users decide for themselves what they want to do. Thank you.
### SD Maid
Version: `5.1.4 (50104)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/z3qcsw/z3q:11/RP1A.200720.012/G988WVLS2DUE1:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log of this.
SD Maid should only keep the screen on, while operations are running.
If SD Maid is working, the screen needs to be kept on to keep app priority high, otherwise the system may kill the app if the lock screen turns on.

**Comment by Akhilesh-T** [comment]
Why can't SD Maid run on priority in the background? 😑

**Comment by dragonGod97677** [comment]
> Please provide a debug log of this.
> SD Maid should only keep the screen on, while operations are running.
> If SD Maid is working, the screen needs to be kept on to keep app priority high, otherwise the system may kill the app if the lock screen turns on.

[sdmaid log](https://github.com/d4rken/sdmaid-public/files/6977361/sdmaid_logfile_1628788678510.txt)

Here @d4rken , tested in version 5.1.7 and set my phone's auto screen off to 15 second and maked sure no other apps locking screen auto off

Actually, been experiencing this issue and present since older/previous versions of SD Maid

**Comment by ctp9** [comment]
This is still an issue - screen timeout is completely ignored and screen stays on indefinitely while SD Maid is in focus.

**Comment by dragonGod97677** [comment]
Update: even on the latest beta, 5.1.9,  when SD Maid is idling, wake lock
is on, screen won't sleep, i checked before testing it, making sure no more
other apps are running on the background using wake lock.

**Comment by d4rken** [comment]
Please check again after the next update.
It should now be only when SD Maid is working.
