### ISSUE TITLE
Pro Version not fully Pro

### ISSUE THREAD

**Issue by codejp3** [d4rken/sdmaid-public#4963]
Just did a fresh wipe and upgrade to android 11 and installed a few essential apps like SD Maid of course. I have the Pro Unlocker app (google play store) which shows the congratulations for purchasing message. SD Maid opens and shows as SD Maid 5.1.4 Pro Version. But the settings menu still asks me to activate the pro version, and the option to hide the unlocker isn't shown.

Actions seem to be unlocked, but settings are not. It's mostly Pro, not completely Pro.

I've tried uninstalling just the unlocker, both SD Maid and the unlocker, and clearing cache/data for both. No luck so far but I'll keep trying.

**Comment by codejp3** [comment]
So as far as I can tell, 100% of the pro features are working. The only not working is the setting to hide the pro unlocker app after activation. Instead I keep seeing the "all paths lead to the pro version" setting that displays the in-app/unlocker restore options, even after activation.

Maybe this isn't a bug, but a change with the code since I last used it.

Only other things I've tried are to put both the app and unlocker on internal memory because the deault put the app on external. No effect.

Signed up for beta and going to try that just for good measure.

If this is a bug, let me know what you need from me to resolve it.

If this isn't a bug, then consider the missing "hide unlocker" setting as a feature request.

**Comment by d4rken** [comment]
Unfortunately not a bug, but neither a feature request I can do.

Google considers "hiding from the launcher" a malicious feature and it's no longer possible on newer Android versions.
Your only option is to use a 3rd party launcher that offers "app hiding" as feature.
