### ISSUE TITLE
Log of files deleted...

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/sdmaid-public#4966]
Hello @d4rken 

**Can you enable logging of files (sorted by size - largest to smallest) deleted every time SD Maid is run using Quick Access?**

Sometimes, the result can be unexpected in terms of size of files deleted in each category. This feature will be helpful to see which files were deleted during the current (or last) run, and the locations from where they were deleted.

An option to automatically clear the logs upon exit (or 24/ 48/ 72 hours) would make it even better.

Thanks.

**Comment by d4rken** [comment]
Something like this?
https://github.com/d4rken/sdmaid-public/wiki/Statistics

**Comment by TheMysticS** [comment]
I have been using SD Maid for well over 5 years (even longer may be) and never noticed this statistics section :)

This is exactly what I requested. However, you could consider providing a quick access to the deleted files log for each tool in the Quick Access section, like an "i" button next to the re-run (circular arrow) button. Clicking on it will simply filter the log of files that were deleted in the current (or last) run, sorted by size in descending order.

**Comment by d4rken** [comment]
> This is exactly what I requested. 

:heart: 

> This is exactly what I requested. However, you could consider providing a quick access to the deleted files log for each tool in the Quick Access section, like an "i" button next to the re-run (circular arrow) button. Clicking on it will simply filter the log of files that were deleted in the current (or last) run, sorted by size in descending order.

For most users this is something rarely looked at, I think it does not warrant adding a shortcut to every screen, sorry :frowning:.
