### ISSUE TITLE
App cleaner not working

### ISSUE THREAD

**Issue by SykoviT** [d4rken/sdmaid-public#4972]
Please see vid: 
https://drive.google.com/file/d/1jxBWi0eYNKxptxlF3X5AfmdZJ5QCu-1y/view?usp=drivesdk

**Comment by d4rken** [comment]
Please provide a debug log.
I can't access the video (permission denied).

**Comment by dragonGod97677** [comment]
![Screenshot_2021-07-10-11-22-31-04](https://user-images.githubusercontent.com/38875906/125150281-3a43ad80-e171-11eb-8455-518f73bc02e4.png)
