### ISSUE TITLE
Clutterreport: /system/bin (FP)

### ISSUE THREAD

**Issue by ngocphung1234** [d4rken/sdmaid-public#4975]
### Target
Target: `/system/bin`
Prefix-free: `bin`
Path-prefix: `/system/`
Type: `DIRECTORY`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `APP Enhancement Services`
Packagename: `com.coloros.gamespace`
Version: `7.0.4 (700004)`

### Current owners
None

### SD Maid
Version: `5.1.5 (50105)`

### Device
Fingerprint: `OPPO/CPH2239T2/OP4F2F:10/QP1A.190711.020/1622468582:user/release-keys`

**Comment by dragonGod97677** [comment]
No, that app does not own that folder, close this issue
