### ISSUE TITLE
Clutterreport: /system/framework/boot-framework.vdex (FP)

### ISSUE THREAD

**Issue by ngocphung1234** [d4rken/sdmaid-public#4976]
### Target
Target: `/system/framework/boot-framework.vdex`
Prefix-free: `framework/boot-framework.vdex`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Bộ nhớ ngoài`
Packagename: `com.android.externalstorage`
Version: `10 (29)`

### Current owners
None

### SD Maid
Version: `5.1.5 (50105)`

### Device
Fingerprint: `OPPO/CPH2239T2/OP4F2F:10/QP1A.190711.020/1622468582:user/release-keys`

**Comment by dragonGod97677** [comment]
The app with package name com.android.externalstorage doesn't own that file
