### ISSUE TITLE
Storage analyzer (old Biggest Files) no longer able to scan custom folders

### ISSUE THREAD

**Issue by someone755** [d4rken/sdmaid-public#498]
I often used this feature to see which files inside /system take up a lot of space. On OEM "skinned" firmware, nandroid backups can become a pain because even the system partition is over 2GB in size, but if one knows what they're doing, it is possible to delete hundreds of megabytes of useless data, and thus slim down the backup. 

But this feature is no longer present (well, it is, but only for userdata and possible external memory cards), and I have to use a file explorer to guess the location of large files. Can we please at least get the option of including /system into the scan?

**Comment by d4rken** [comment]
So just list "/system" in the home view of the storage analyzer?

Should this be done by default or something that is turned on in settings...
Showing it directly gives the impression that the "normal" user has to care about how full `/system` is which would be missleading. If we make this an option, any other storage location to include?

**Comment by someone755** [comment]
I haven't used SD Maid in a while (top notch app though), so I was surprised to see there is now a default view. I was hoping there would be something to add /system to the section in the app's settings but came to the conclusion only /data and external cards are available.

Leaving the defaults as-is, and hiding extra partitions/folders into the settings sounds sensible. As far as I'm concerned only /system is missing, but that's because I only ever scan that. Maybe other users could recommend more directories but that's all from me.

**Comment by d4rken** [comment]
Next update :).
![2016-09-17 23 49 03](https://cloud.githubusercontent.com/assets/1439229/18611711/2de5aa5e-7d42-11e6-9bca-8f08e3a38fc8.png)

**Comment by someone755** [comment]
Thanks a heap man!

(It's not easy building kernels for different ROMs when those ROMs have huge /system partitions, you're making my life so much easier!)
