### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM (FP)

### ISSUE THREAD

**Issue by Angahari** [d4rken/sdmaid-public#4982]
### Target
Target: `/storage/emulated/0/DCIM`
Prefix-free: `DCIM`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `3 Button Navigation Bar`
Packagename: `com.android.internal.systemui.navbar.threebutton`
Version: `1.0 (1)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `11 (30)`

Appname: `?`
Packagename: `com.meizu.media.gallery`
Version: ` (-1)`

### SD Maid
Version: `5.1.5 (50105)`

### Device
Fingerprint: `samsung/a50xser/a50:11/RP1A.200720.012/A505FNPUU8CUE4:user/release-keys`

**Comment by dragonGod97677** [comment]
Why would that app com.android.internal.systemui.navbar.threebutton own that folder? 🤔

**Comment by dragonGod97677** [comment]
I don't think so
