### ISSUE TITLE
Clutterreport: /storage/emulated/0/snaptube/.config (FP)

### ISSUE THREAD

**Issue by Angahari** [d4rken/sdmaid-public#4984]
### Target
Target: `/storage/emulated/0/snaptube/.config`
Prefix-free: `snaptube/.config`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Calendar storage`
Packagename: `com.android.providers.calendar`
Version: `12.1.00.5 (1210000005)`

### Current owners
Appname: `?`
Packagename: `com.snaptube`
Version: ` (-1)`

Appname: `Snaptube`
Packagename: `com.snaptube.premium`
Version: `5.20.1.5201501 (5201501)`

### SD Maid
Version: `5.1.5 (50105)`

### Device
Fingerprint: `samsung/a50xser/a50:11/RP1A.200720.012/A505FNPUU8CUE4:user/release-keys`

**Comment by dragonGod97677** [comment]
Calendar storage (com.android.providers.calendar) doesn't own that folder
