### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/media/Downloaded APK's (FP)

### ISSUE THREAD

**Issue by 74971030177** [d4rken/sdmaid-public#4991]
> `###` Target

Target: `/storage/emulated/0/Android/media/Downloaded APK's`
Prefix-free: `Downloaded APK's`
Path-prefix: `/storage/emulated/0/Android/media/`
Type: `DIRECTORY`
Location: `PUBLIC_MEDIA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: 
Packagename:
Version: `4.35.51 (43551230)`

Appname: ?
Packagename:com.google.android.youtube AND com.google.android.apps.youtube.music doesn't create that kind of folder
Version: `14.49.51 (1449513000)`

### SD Maid
Version: `5.1.5 (50105)`

### Device
Fingerprint: `motorola/malta/malta:10/QOF30.569-12/0e22e:user/release-keys`

### Comment
`delete all Downloadedl APK files`include media And Downloaded PDF files

**Comment by dragonGod97677** [comment]
There's incorrect information in "Current owners"

 Current owners
Appname: ?
Packagename: Downloaded APK's
Version: (-1)


Also apps with package name 

com.google.android.youtube  AND  com.google.android.apps.youtube.music doesn't create that kind of folder

**Comment by 74971030177** [comment]
Like a virgin!
