### ISSUE TITLE
Bug: AppCleaner

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#4992]
### What happened?
It was cleaning caches now but that was i thought.
After SD maid do the app cache cleaning, i checked some apps that was cleaned if it was, but it wasn't.

### What did you expect to happen?
Fully clear an app cache        

### How can I reproduce the issue?
You'll just need an OPPO phone running android 8.1

### Comments

Here's the files that might help you speed up the fix

[video](https://drive.google.com/file/d/1fm7-zlyFNoS6hq6ljgZr42o7dcfVlf5y/view?usp=sharing)

[Log File](https://github.com/d4rken/sdmaid-public/files/6836387/sdmaid_logfile_1626616770048.txt.zip)

### SD Maid
Version: `5.1.6 (50106)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OPPO/CPH1803/CPH1803:8.1.0/OPM1.171019.026/1595220200:user/release-keys`

**Comment by dragonGod97677** [comment]
[updated debug log](https://github.com/d4rken/sdmaid-public/files/6878134/sdmaid_logfile_1627302473222.txt.zip)

**Comment by d4rken** [comment]
`1627302474246  D/Debug:SysInfoModule: isArmed: false`

![Screenshot from 2021-08-09 20-53-38](https://user-images.githubusercontent.com/1439229/128758869-01c349a5-5385-4857-a12b-eacc553d49c4.png)


You put SD Maid into demo mode.

**Comment by dragonGod97677** [comment]
> `1627302474246 D/Debug:SysInfoModule: isArmed: false`
> 
> ![Screenshot from 2021-08-09 20-53-38](https://user-images.githubusercontent.com/1439229/128758869-01c349a5-5385-4857-a12b-eacc553d49c4.png)
> 
> You put SD Maid into demo mode.

I tested it with demo mode true as you said and it clears app cache now, thanks!
