### ISSUE TITLE
Bug: Can't auto run clean on Note 20 ultra 5g/ android 11

### ISSUE THREAD

**Issue by thaitruongdien** [d4rken/sdmaid-public#4993]
## What happened?
Can't auto clean app on Note 20 ultra 5g/ android 11. 

### What did you expect to happen?
I Can auto clean app on Note 20 ultra 5g/ android 11. 

### How can I reproduce the issue?
Please fix it. Along times app, Can't auto run clean mobile

### Comments
Android 11 restore defaul setting on app
### SD Maid
Version: `5.1.6 (50106)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/c2sxxx/c2s:11/RP1A.200720.012/N986BXXU2DUF8:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log
