### ISSUE TITLE
Bug: Sqlite binary unavailable

### ISSUE THREAD

**Issue by RevCyberTrucker** [d4rken/sdmaid-public#4994]
Sorry if this is redundant, I searched and the closest bug report is 3 years old. 

Samsung S20 Ultra 5g
Non rooted
Unsure if it can be duplicated

 Log file is over 200+ pages long, so I am providing a link instead of pasting text. 

Log file: https://drive.google.com/file/d/189XJ6z5tqMwuA8UDsEDIFVy_BYGwAn19/view?usp=drivesdk

**Comment by richaardvark** [comment]
Same issue for non-rooted Samsung Galaxy A10e.

**Comment by d4rken** [comment]
This is unfortunately a known issue on newer Android versions.
Restrictions on new Android versions force me to change how SD Maid executes the binary, but on some ROMs moving SD Maid, also moves the binary to a place where SD Maid can't execute this.

I can't fix this without breaking support for older versions or vastly complicating SD Maids code.
Currently it will have to stay like this.
