### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by goensnap** [d4rken/sdmaid-public#4997]
### What happened?
When checked device overview, all good but the processor speed. Only showing 0.00MHz

### What did you expect to happen?
I expect it to show the correct result

### How can I reproduce the issue?
Just open the overview tab and then press the refresh button and you gonna get the result of your device information

### Comments
Amazing app
### SD Maid
Version: `5.1.6 (50106)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `asus/WW_Phone/ASUS_X00IDB:8.1.0/OPM1.171019.011/15.2016.1907.519-0:user/release-keys`

**Comment by d4rken** [comment]
Can you provide a debug log?
Generally the processor speed is just some UI sugar, it serves no practical purpose and I might just remove it.

**Comment by d4rken** [comment]
The parsing is likely  just off on the device, but without a debuglog I can't fix this, as I don't own that device.
