### ISSUE TITLE
Clutterreport: /system/priv-app/SystemUI/oat/arm/SystemUI.odex (FP)

### ISSUE THREAD

**Issue by Slashtag1** [d4rken/sdmaid-public#4999]
### Target
Target: `/system/priv-app/SystemUI/oat/arm/SystemUI.odex`
Prefix-free: `SystemUI/oat/arm/SystemUI.odex`
Path-prefix: `/system/priv-app/`
Type: `FILE`
Location: `SYSTEM_PRIV_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `10 (29)`

### Current owners
Appname: `System UI`
Packagename: `com.android.systemui`
Version: `10 (29)`

### SD Maid
Version: `5.1.5 (50105)`

### Device
Fingerprint: `samsung/a01qtfn/a01q:10/QP1A.190711.020/S111DLUDU5AUD1:user/release-keys`

**Comment by dragonGod97677** [comment]
My comment here same as on #5000
