### ISSUE TITLE
When open a folder from AppControl, cannot go back to same place in AppControl

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#500]
When the user views the folders used by an app via AppControl, and then clicks on one, the Explorer is opened.  Once this happens, it is not possible to go back to the same position in AppControl.

To get back to the same position, the user has to reload AppControl, find the same app, calculate the size again, and then (IIRC) expand the size UI within AppControl.

**Comment by d4rken** [comment]
Going back from Explorer to AppControl should still show the previous data in AppControl.
What device do you have? This sounds like aggressive memory regaining by the system.

In the general UI flow, just pressing the backbutton would obvious be better, but I'm not sure if I can make this easily work in SD Maids current UI structure.

**Comment by Gitoffthelawn** [comment]
Yes, pressing the back button is ideal... but I can see how that will be a challenge to implement. The device has 1GB of RAM.

**Comment by d4rken** [comment]
Can you record a debug log of this happening?

**Comment by Gitoffthelawn** [comment]
Yes, I can do that for you!  Do you want a Logcat or a different form of log?  Just let me know.

**Comment by Gitoffthelawn** [comment]
Also, if you can, write a few steps for what the behavior *should* be for AppControl when going into Explorer (and back).  That way, I can confirm the issue before gathering logs.

**Comment by d4rken** [comment]
A debug log from SD Maid or a logcat but with SD Maids debug level set to "2".

* Go to AppControl
* Scan AppControl
* Enter app details
* Click scan in app details
* Expand size info and click a path
* SD Maid switches to the explorer and opens the path

If you now go back to AppControl, you should see still see the app list without refreshing again, and if you enter the same app details again, you should also not have to press "scan" again to view storage details.

**Comment by Gitoffthelawn** [comment]
I must be momentarily myopic... where is the option to turn on debug logging within SD Maid?

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by d4rken** [comment]
Any update on this? The general UI flow is not easily changeable, but if you provide a debug log I could check why you have to reload the data again

**Comment by Gitoffthelawn** [comment]
I will check to see if it still happens with latest version.
