### ISSUE TITLE
Clutterreport: /system/priv-app/SystemUI/oat/arm/SystemUI.vdex (FP)

### ISSUE THREAD

**Issue by Slashtag1** [d4rken/sdmaid-public#5000]
### Target
Target: `/system/priv-app/SystemUI/oat/arm/SystemUI.vdex`
Prefix-free: `SystemUI/oat/arm/SystemUI.vdex`
Path-prefix: `/system/priv-app/`
Type: `FILE`
Location: `SYSTEM_PRIV_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `System UI`
Packagename: `com.android.systemui`
Version: `10 (29)`

### Current owners
Appname: `System UI`
Packagename: `com.android.systemui`
Version: `10 (29)`

### SD Maid
Version: `5.1.5 (50105)`

### Device
Fingerprint: `samsung/a01qtfn/a01q:10/QP1A.190711.020/S111DLUDU5AUD1:user/release-keys`

**Comment by dragonGod97677** [comment]
Why would you Suggested keeper state: true that file when system partition is always kept read-only or even you are rooted your device, sd maid won't even gonna pick that file unless system ui app is uninstalled
