### ISSUE TITLE
Bug: Frozen app

### ISSUE THREAD

**Issue by JeraldBrk** [d4rken/sdmaid-public#5003]
![Screenshot_20210723-171817_SD Maid](https://user-images.githubusercontent.com/87882211/126850182-9d82dfa4-680b-4017-95f9-785b52f12a38.jpg)
![Screenshot_20210723-171808_SD Maid](https://user-images.githubusercontent.com/87882211/126850185-2f45a0d8-8e75-4f1e-8f9e-e67089bc11de.jpg)
![Screenshot_20210723-171615_SD Maid](https://user-images.githubusercontent.com/87882211/126850187-b4754d36-a867-4c24-98c5-8100bc3665f9.jpg)
![Screenshot_20210723-164657_SD Maid](https://user-images.githubusercontent.com/87882211/126850188-5e1f847c-ba3c-4eae-b6fe-2a3c7170c486.jpg)
### What happened?
App doesn't clear cache or anything.. Automatic cleaning of the app does not work. 

### What did you expect to happen?
After the update I presented faults and no clean is frozen

### How can I reproduce the issue?
It's a frustration. I used it but now I think I'll stop using it doesn't help me. 

### Comments
I need your support please, the app says clean cache and junk files at startup everything worked well for me lately not and I don't know why. Please help me thank you very much and I remain attentive. 
### SD Maid
Version: `5.1.6 (50106)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a20ub/a20:11/RP1A.200720.012/A205GUBU9CUF2:user/release-keys`

**Comment by d4rken** [comment]
I currently can't see what the issue on your screenshots.
Please provide a debuglog.
