### ISSUE TITLE
Clutterreport: /storage/AF50-08F2 (FP)

### ISSUE THREAD

**Issue by AshleyD8713** [d4rken/sdmaid-public#5008]
### Target
Target: `/storage/AF50-08F2`
Prefix-free: `/storage/AF50-08F2`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Services Library`
Packagename: `com.google.android.ext.services`
Version: `q_pr1-release_aml_291900801 (291900801)`

### Current owners
None

### SD Maid
Version: `5.1.6 (50106)`

### Device
Fingerprint: `lge/mdh30lm/mdh30lm:10/QKQ1.200730.002/211681419b00d:user/release-keys`

### Comment
`hacked my phone`

**Comment by AshleyD8713** [comment]
This is a secondary storage installed on my phone which was able to access my calls, messages, bank info everything. This person acted as if they were me and even tried to take out loans etc in my name. Any suggestions?? What can I do?? Who can I report this to?? I really need help. I even looked up my experian report and alot of that is at risk as well. Please help.

**Comment by dragonGod97677** [comment]
If someone is harrassing/spamming you or like you said, hacked you, we can't help you, contact your local authorities instead and also that app with the package name 'com.google.android.ext.services' never owned any external SD card folders

**Comment by dragonGod97677** [comment]
Please close this issue
