### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1474190932070.log (FP)

### ISSUE THREAD

**Issue by DO97** [d4rken/sdmaid-public#501]
### Target
Target: `/storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1474190932070.log`
Prefix-free: `eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1474190932070.log`
Path-prefix: `/storage/emulated/0/Android/data/`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `SD Maid`~~
~~Packagename: `eu.thedarken.sdm`~~
~~Version: `4.3.2 (40302)`~~

### SD Maid
Version: `4.3.2 (40302)`

### Device
Fingerprint: `samsung/zeroltexx/zerolte:6.0.1/MMB29K/G925FXXS4DPH2:user/release-keys`

**Comment by DO97** [comment]
There are some private informations that I should delete?
Overview:
![screenshot_20160918-113754](https://cloud.githubusercontent.com/assets/17525578/18614718/94d4b992-7d94-11e6-8087-83c2be1f2b25.png)
Storage analyzer:
![screenshot_20160918-113859](https://cloud.githubusercontent.com/assets/17525578/18614723/a65c1d4a-7d94-11e6-92ea-c5c9fe62decf.jpg)

**Comment by d4rken** [comment]
Why a clutter report saying SD Maid does not own it's own files?

What private files?

**Comment by d4rken** [comment]
The screenshots would better fit here
https://github.com/d4rken/sdmaid-public/issues/502

**Comment by jameel45** [comment]
[Uploading Downloads Help.pdf…]()

**Comment by jameel45** [comment]
> There are some private informations that I should delete? Overview: ![screenshot_20160918-113754](https://cloud.githubusercontent.com/assets/17525578/18614718/94d4b992-7d94-11e6-8087-83c2be1f2b25.png) Storage analyzer: ![screenshot_20160918-113859](https://cloud.githubusercontent.com/assets/17525578/18614723/a65c1d4a-7d94-11e6-92ea-c5c9fe62decf.jpg)

https://github.com/d4rken-org/sdmaid/issues/501#issuecomment-247837766
