### ISSUE TITLE
Root permission and drop box pck installer

### ISSUE THREAD

**Issue by Unitedas1** [d4rken/sdmaid-public#5021]
I have an issue of removing a fake drop box app that shows its a package installer. Emulated apps keep reinstalling because of root permission. How can I clean up my phone properly. I use SD Maid but I am prevented from accessing the root permission.

**Comment by d4rken** [comment]
SD Maid is not an anti malware tool.
If a malicious app has root, then the only sure way to regain control, is to reflash the ROM.
