### ISSUE TITLE
Clutterreport: /data/user/0/com.google.android.googlequicksearchbox/files/datadownload/shared/public (FP)

### ISSUE THREAD

**Issue by cronprog** [d4rken/sdmaid-public#5030]
### Target
Target: `/data/user/0/com.google.android.googlequicksearchbox/files/datadownload/shared/public`
Prefix-free: `com.google.android.googlequicksearchbox/files/datadownload/shared/public`
Path-prefix: `/data/user/0/`
Type: `DIRECTORY`
Location: `PRIVATE_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `Google`
Packagename: `com.google.android.googlequicksearchbox`
Version: `12.31.7.29.arm64 (301162102)`

### SD Maid
Version: `5.1.6 (50106)`

### Device
Fingerprint: `google/redfin/redfin:11/RQ3A.210805.001.A1/7474174:user/release-keys`

### Comment
``Hello. My name is Igor Baumgarten. I want to inform you that the Google application downloads 200 megabytes + useless files, this happens when you first install or update. These files are later useless, I suggest adding files along this path to cleanup! Thank you`

**Comment by d4rken** [comment]
Can you share more information, why can this be deleted?

**Comment by glowinthedark** [comment]
these files are the voices for Google Text-to-Speech (TTS)
