### ISSUE TITLE
Bug : /data/user/0/com.instagram.android/ cache/private _default _cache

### ISSUE THREAD

**Issue by nikgrover** [d4rken/sdmaid-public#5035]
The application is unable to delete the full cache of instagram , it only deletes the 1/4th of the cache data of the application and if tries to delete the cache via the application individually , it just presents that the data is deleted , but its not.

**Comment by d4rken** [comment]
Please provide a debug log of this happening:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
