### ISSUE TITLE
Clutterreport: /storage/6C98-52AB/obb/locales/mega (new)

### ISSUE THREAD

**Issue by farouk8890** [d4rken/sdmaid-public#5037]
### Target
Target: `/storage/6C98-52AB/obb/locales/mega`
Prefix-free: `obb/locales/mega`
Path-prefix: `/storage/6C98-52AB/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Setup`
Packagename: `com.google.android.setupwizard`
Version: `228.6024884 (228)`

Appname: `MEGA888`
Packagename: `com.mega888.Release`
Version: `1.2 (1)`

### Current owners
None

### SD Maid
Version: `5.1.8 (50108)`

### Device
Fingerprint: xiaomi/lavender/lavender:9/PKQ1.180904.001/V11.0.6.0.PFGMIXM:user/release-keys

**Comment by d4rken** [comment]
Not sure this is correct, can you tell me more?

**Comment by farouk8890** [comment]
> Not sure this is correct, can you tell me more?

=Whatsapp me
