### ISSUE TITLE
Accessibility service on Android 4.2

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#5042]
На Андроиде 4.2 я использую SD Maid 4.15.15. В настройках телефона можно включить службу специальных возможностей для SD Maid. Для чего именно она нужна? На Андроиде 4.2 для очистки скрытого кэша нет необходимости открывать окно настроек каждого приложения и нажимать кнопку "Очистить кэш", кэш и без этого очищается.

**Comment by d4rken** [comment]
> On Android 4.2, I am using SD Maid 4.15.15. You can enable accessibility service for SD Maid in your phone settings. What exactly is it for? On Android 4.2, to clear the hidden cache, there is no need to open the settings window of each application and press the "Clear cache" button, the cache is cleared without it.

It has no functionality, it's just not hidden.
Even if enabled, SD Maid will not make use of it.

I had some plans to use it for other automation, even on earlier Android versions, but getting it to work on all different devices is more effort than I'd like.

I'm not sure if I can hide the option, without creating two different APKs :thinking:

**Comment by Ingood5** [comment]
На Андроиде 4.2 не скроете, SD Maid его уже не поддерживает 😀

**Comment by d4rken** [comment]
Well, there is not much to be done :man_shrugging:.
It is like it is :grin:
