### ISSUE TITLE
Improve AppCleaner support on latest vivo devices with Funtouch OS

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#5045]
[sdmaid_logfile_1629189098181.txt.zip](https://github.com/d4rken/sdmaid-public/files/6998459/sdmaid_logfile_1629189098181.txt.zip)

    Device details
Device: Vivo Y20s [G] (V2038)
ROM: Funtouch OS
ROM Version And Build Info: Funtouch OS 11 Global based on Android 11, Build PD2066DF_EX_A_1.11.1

**Comment by d4rken** [comment]
> Retry count 1. Reason: eu.thedarken.sdm.accessibility.core.crawler.CrawlerException: No matching node found for Spec(parent=AppCleaner:ACS:VivoAPI29PlusSpecs, label=Find & click 'Storage' (targets=[Internal storage, Storage, Storage space, Storage & memory]), pkg=com.google.android.youtube)


```
47610  V/AppCleaner:ACS:CrawlerHelp: crawl():-----------11: className=android.widget.LinearLayout, text=null, isClickable=true, isEnabled=true, viewIdResourceName=null, pkgName=com.android.settings
1629189147610  V/AppCleaner:ACS:CrawlerHelp: crawl():------------12: className=android.widget.RelativeLayout, text=null, isClickable=false, isEnabled=true, viewIdResourceName=null, pkgName=com.android.settings
1629189147610  V/AppCleaner:ACS:CrawlerHelp: crawl():-------------13: className=android.widget.TextView, text=Storage & cache, isClickable=false, isEnabled=true, viewIdResourceName=android:id/title, pkgName=com.android.settings
1629189147610  V/AppCleaner:ACS:CrawlerHelp: crawl():-------------13: className=android.widget.TextView, text=2.16 GB used in internal storage, isClickable=false, isEnabled=true, viewIdResourceName=android:id/summary, pkgName=com.android.settings
```

They keep coming up with new labels for the same option, every time :joy:.

The current API 29 Vivo specs are based on the old Vivo specs, though, so the priority order is:
VivoApi29Specs > VivoSpecs > AOSP14to28Specs

I'll change it to
VivoApi29Specs > AOSP29PlusSpecs

as AOSP29 has the same label, this might automatically give us support for all other languages if Vivo re-used the AOSP labels.
