### ISSUE TITLE
Automate Telegram app cache clearing

### ISSUE THREAD

**Issue by Bluscream** [d4rken/sdmaid-public#5049]
If sdmaid would do this before appcleaner runs that would really decrease required time for it

These buttons where found with Automagic4Android for the telegram plus app (Sadly i couldnt find any button IDs with it)
```
click("Open navigation menu");
click("Settings");
click("Data and Storage");
click("Storage Usage");
click("Clear Telegram Cache");
click("Clear Cache");
click("Clear Local Database");
click("CLEAR");
```

**Comment by d4rken** [comment]
While probably pretty cool for this use-case, it is too specific to include in SD Maid.
Keeping the ACS method working with different ROMs is tedious enough, and ROMs change less often than apps :fearful:. 
Not going to add this, sorry.

(I've deleted the log file you attached due as it contained a phone number)

**Comment by Bluscream** [comment]
Too bad. I wouldnt have suggested it if it didnt reduce my clean time from 14 minutes to 2 minutes

**Comment by d4rken** [comment]
12 Minutes just for Telegram? Can you share a debug log of that?
Seems awfully long. While single file deletion via SAF on newer Android version is not super fast, SD Maid should still be able to optimize the deletion process, maybe there is something not working as well as it could :thinking:.

**Comment by Bluscream** [comment]
> 12 Minutes just for Telegram? Can you share a debug log of that?

would i need to use adb for that?

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
