### ISSUE TITLE
Scheduler doesn`t start after rebooting

### ISSUE THREAD

**Issue by squromiv** [d4rken/sdmaid-public#5054]
Android 8.1.0 Root
SD Maid 5.1.8 pro, 
Application is excluded from battery optimization etc.
![Screenshot_20210823-092222_SD Maid](https://user-images.githubusercontent.com/15985877/130453115-2cb64f4c-61a7-4288-a37e-afd7245169d5.jpg)
It looks like I have the issue, that was [mentioned on reddit](https://www.reddit.com/r/sdmaid/comments/8sf5n3/scheduler_never_works/).  Generally, scheduler works. But after rebooting the device, I see SD Maid app among running services and scheduler does nothing. I have no such a problem with other software for automation.

**Comment by d4rken** [comment]
If SD Maid is moved to external storage, this could break it.

If that isn't the case, please provide a debug log.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

You can start the recording and then restart the device. Do not open SD Maid until you are sure that the device is completely done booting.
Then open SD Maid and send me the log.
