### ISSUE TITLE
APP CLEANER AUTO FEATURE (MALFUNCTIO)

### ISSUE THREAD

**Issue by En52736** [d4rken/sdmaid-public#5057]
![Screenshot_2021-08-24-22-31-07-883_eu thedarken sdm](https://user-images.githubusercontent.com/30790585/130635833-c134ef06-0ff2-4cbe-aaa7-32982f1472b8.jpg)
![Screenshot_2021-08-24-22-29-58-206_com android settings](https://user-images.githubusercontent.com/30790585/130635844-dfe7affd-c21c-4163-9def-fc95e80d8db0.jpg)

**Comment by d4rken** [comment]
This is a ROM issue and not something I can fix.

**Comment by En52736** [comment]
Ok 😊 thanks
