### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM/Screenshots

### ISSUE THREAD

**Issue by Ttp5111** [d4rken/sdmaid-public#5064]
### Target
Target: `/storage/emulated/0/DCIM/Screenshots`
Prefix-free: `DCIM/Screenshots`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Shared Library`
Packagename: `com.google.android.ext.shared`
Version: `1 (1)`

### Current owners
Appname: `?`
Packagename: `com.samsung.android.app.smartcapture`
Version: ` (-1)`

### SD Maid
Version: `5.1.6 (50106)`

### Device
Fingerprint: `OPPO/CPH2197T2/OP4F39L1:11/RKQ1.201217.002/1626274312368:user/release-keys`

**Comment by 23582** [comment]
![1630118006719](https://user-images.githubusercontent.com/89639156/131203572-4156efa8-b813-441f-8e40-8137c16d7385.png)

**Comment by 23582** [comment]
OPPO/CPH2197T2/OP4F39L1:11/RKQ1.201217.002/1626274312368:user/release-keys
