### ISSUE TITLE
![1630118006719](https://user-images.githubusercontent.com/89639156/131203572-4156efa8-b813-441f-8e40-8137c16d7385.png)

### ISSUE THREAD

**Issue by Ttp5111** [d4rken/sdmaid-public#5066]
![1630118006719](https://user-images.githubusercontent.com/89639156/131203572-4156efa8-b813-441f-8e40-8137c16d7385.png)

_Originally posted by @23582 in https://github.com/d4rken/sdmaid-public/issues/5064#issuecomment-907554205_

**Comment by 23582** [comment]
> ![1630118006719](https://user-images.githubusercontent.com/89639156/131203572-4156efa8-b813-441f-8e40-8137c16d7385.png)
> 
> _Originally posted by @23582 in https://github.com/d4rken/sdmaid-public/issues/5064#issuecomment-907554205_
