### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data (FP)

### ISSUE THREAD

**Issue by Ttp5111** [d4rken/sdmaid-public#5067]
### Target
Target: `/storage/emulated/0/Android/data`
Prefix-free: `Android/data`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `ColorOS System`
Packagename: `oplus`
Version: `8.0 (80)`

### Current owners
Appname: `ระบบ Android`
Packagename: `android`
Version: `11 (30)`

### SD Maid
Version: `5.1.8 (50108)`

### Device
Fingerprint: `OPPO/CPH2197T2/OP4F39L1:11/RKQ1.201217.002/1626274312368:user/release-keys`

**Comment by Anuwatrodcharoen** [comment]
> ### Target
> Target: `/storage/emulated/0/Android/data`
> Prefix-free: `Android/data`
> Path-prefix: `/storage/emulated/0/`
> Type: `DIRECTORY`
> Location: `SDCARD`
> Current keeper state: `false`
> Suggested keeper state: `true`
> 
> ### Suggested owners
> Appname: `ColorOS System`
> Packagename: `oplus`
> Version: `8.0 (80)`
> 
> ### Current owners
> Appname: `ระบบ Android`
> Packagename: `android`
> Version: `11 (30)`
> 
> 
> ### SD Maid
> Version: `5.1.8 (50108)`
> 
> ### Device
> Fingerprint: `OPPO/CPH2197T2/OP4F39L1:11/RKQ1.201217.002/1626274312368:user/release-keys`
> 
>

**Comment by Anuwatrodcharoen** [comment]
.
