### ISSUE TITLE
Need to Exclude some apps by default on AppCleaner

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#5077]
Because These and some of the apps :
1)Cache and data can't be cleared on App Info Settings page.
2)App's App Info Settings page can't be opened

Device Information:

Nokia G10, Android One, Android 11, with July 2021 Security Patch

[sdmaid_logfile](https://github.com/d4rken/sdmaid-public/files/7080956/sdmaid_logfile_1630206294900.txt.zip)

I'll attach the screenshots later (within the day), that lists what app to be excluded by default and possibly add new debug log too.

**Comment by d4rken** [comment]
> Cache and data can't be cleared on App Info Settings page.

Because the clear cache button is greyed out?

> App's App Info Settings page can't be opened

What happens when SD Maid tries? What happens when you manually try it?

**Comment by dragonGod97677** [comment]
> Because the clear cache button is greyed out?
Yes, Both Buttons, Clear Data and Clear Cache is grayed out

> What happens when SD Maid tries? What happens when you manually try it?
When SD Maid tries to open the app's app info settings page, it returns to the last app opened, and that is SD Maid.
And when i want to open it manually, i can't, the app is not even listed on the app list settings page but SD Maid sees it installed.

**Comment by dragonGod97677** [comment]
Sorry if i reply very late, i was about to reply last night with a screenshot and videos included but, my sister is using the phone(it's her phone btw)

**Comment by dragonGod97677** [comment]
https://youtu.be/3s_GbIUPYXQ the video

And updated 
[Debug log](https://github.com/d4rken/sdmaid-public/files/7087886/sdmaid_logfile_1630463258629.txt.zip)

**Comment by dragonGod97677** [comment]
Hey darken, any update?

**Comment by d4rken** [comment]
Thanks for the extra infos, it's enough for me to work with.
It's a bit problematic as there is also the case where the buttons are only greyed out because the system is still calculating sizes. That's likely the case SD Maid is currently executing: "Ok system is not ready yet, let's wait a bit longer".

A simple exclusion for these packages would be a bit broad, as on some ROMs these apps behave like others.

I'm not sure yet what the best solution would be.

**Comment by d4rken** [comment]
It's all system apps though, right? `OsuLogin` doesn't have anything to do with the game `OSU!`?

**Comment by dragonGod97677** [comment]
> It's all system apps though, right? `OsuLogin` doesn't have anything to do with the game `OSU!`?

Ah yeah, and also, no it's done calculating the space used, it's really grayed out

**Comment by dragonGod97677** [comment]
> Thanks for the extra infos, it's enough for me to work with.
> It's a bit problematic as there is also the case where the buttons are only greyed out because the system is still calculating sizes. That's likely the case SD Maid is currently executing: "Ok system is not ready yet, let's wait a bit longer".
> 
> A simple exclusion for these packages would be a bit broad, as on some ROMs these apps behave like others.
> 
> I'm not sure yet what the best solution would be.


no it's done calculating the space used, it's really grayed out

**Comment by d4rken** [comment]
I've added them as AppCleaner default exclusions for Android 11+
