### ISSUE TITLE
Feedback about: AppCleaner Custom accessibility sequence

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#5078]
Actually this function is quite useful to me, i can use this to batch delete app data, not just clear app cache by default, it's easy to add the sequences, and it works!

**Comment by d4rken** [comment]
:heart:

**Comment by d4rken** [comment]
@dragonGod97677 I liked your idea. Beta v5.2.0 is out now and has a new "Custom action" that allows you to do this on every app you can select via AppControl.

https://www.youtube.com/watch?v=4aR7H3Cihk8
