### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.hiqrecorder.full/files/Recordings (FP)

### ISSUE THREAD

**Issue by nmalviy** [d4rken/sdmaid-public#5088]
### Target
Target: `/storage/emulated/0/Android/data/com.hiqrecorder.full/files/Recordings`
Prefix-free: `com.hiqrecorder.full/files/Recordings`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Hi-Q MP3 Recorder`
Packagename: `com.hiqrecorder.full`
Version: `2.8.1 (17000681)`

### Current owners
Appname: `Hi-Q MP3 Recorder`
Packagename: `com.hiqrecorder.full`
Version: `2.8.1 (17000681)`

### SD Maid
Version: `5.1.8 (50108)`

### Device
Fingerprint: `samsung/f41dd/f41:11/RP1A.200720.012/F415FXXU1BUG2:user/release-keys`

### Comment
`recordings important`

**Comment by nmalviy** [comment]
I am not able to see the files of the hi q recorder but I can play them from the player

**Comment by d4rken** [comment]
Sd maid already knows the correct owner here.
The keeper state can't be enforced because it's a default area being deleted by the system on uninstalls.
