### ISSUE TITLE
Bug: An Explorer 'Setting' crashes app in Android 5.0.2

### ISSUE THREAD

**Issue by Siva981** [d4rken/sdmaid-public#5092]
### What happened?
In Android 5.0.2, if "Mark items that match an App Cleaner filter" under 'Settings --> Explorer' is unchecked (NOT selected), then the app crashes whenever the Explorer tries to open any folder. It crashes even when trying to open 'storage/emulated/0'. Explorer starts to work gain ONLY if we go back and check (select) the aforementioned setting under 'Settings --> Explorer'.

### What did you expect to happen?
Explorer should load pages normally even if this setting is unchecked (not selected).

### How can I reproduce the issue?
In Android 5.0.2, try to open any folder using Explorer, while the "Mark items that match an App Cleaner filter" setting, under 'Settings --> Explorer' is unchecked (not selected).

### Comments
I am unable to use Explorer because of this issue, which seems to have been introduced by the latest update to the app. I am in version 5.1.8. 
### SD Maid
Version: `5.1.8 (50108)`
Pro: `isPro=true || isComplete=false (unl=true, iap=null, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `SWIPE/Elite_Plus/evoque_cn:5.0.2/LRX22G/v6FB1-0:user/release-keys`

**Comment by d4rken** [comment]
I think I fixed this in 5.1.9, could you try the beta to confirm?

**Comment by Siva981** [comment]
Yeah, it works alright in the Beta. Are you going to be making any more updates to this beta before releasing it? Should I keep the beta, or revert back to 5.1.8 and wait for 5.1.9 to be released on Google Play Store?

**Comment by d4rken** [comment]
You can keep it installed.
