### ISSUE TITLE
Crashes on opening any folder from Android/data

### ISSUE THREAD

**Issue by FonsecaXp** [d4rken/sdmaid-public#5099]
Device: POCO X3
Android 11 MIUI 12.5.2
No Root no bootloader unlocked
SD Maid 5.1.8 Unlocker 4.4.1

SDMaid crashes when opening Folders From android/data when using storage analyser

[Log file](https://cdn.discordapp.com/attachments/572061295327838209/885157795383607346/sdmaid_logfile_1631108385034.txt.zip)

**Comment by d4rken** [comment]
Should be fixed with the next update.
The sub-scan of e.g. internal storage should also show the correct size of  the `Android` folder then.
