### ISSUE TITLE
Bug: All My Files were deleted

### ISSUE THREAD

**Issue by AAA9331** [d4rken/sdmaid-public#5101]
### What happened?
I was uding this app "sd maid" and by wrong it delete my photos and videos and everything so i want backing down this decision right now and recovering my files back 

### What did you expect to happen?
I accepted that the app will not let me delete this important files and warning me that what i do is dangerous 

### How can I reproduce the issue?
By backing down the last  operations in the app 

### Comments
I want my data back now!!!
### SD Maid
Version: `5.1.8 (50108)`
Pro: `isPro=false || isComplete=true (unl=false, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `HUAWEI/LDN-L21B/HWLDN-Q:8.0.0/HUAWEILDN-L21/166(C185):user/release-keys`

**Comment by AAA9331** [comment]
Some one help me please 💔💔

**Comment by AAA9331** [comment]
Some one help me please 💔💔

**Comment by dragonGod97677** [comment]
SD Maid never deletes files automatically unless it was set by the user and also once a user sets automation to delete, it will only delete, safe to delete files, also take note about it, when you have an important app has a important files too and the app was uninstalled but the files remains in your device storage, And started CorpseFinder function, it will get picked up and deleted only when the user presses delete on CorpseFinder or automated, it will really get deleted, so the developer will not be take any responsibility for the deleted files

**Comment by d4rken** [comment]
For recovery options, see:
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#recover-deleted-files

If you think this is not user error, but a bug, please provide instructions to reproduce and re-open this ticket.
