### ISSUE TITLE
Clutterreport: /system/app/DownloadProviderDrmAddon/DownloadProviderDrmAddon.apk (FP)

### ISSUE THREAD

**Issue by Abdallahabuhaswah** [d4rken/sdmaid-public#5113]
### Target
Target: `/system/app/DownloadProviderDrmAddon/DownloadProviderDrmAddon.apk`
Prefix-free: `DownloadProviderDrmAddon/DownloadProviderDrmAddon.apk`
Path-prefix: `/system/app/`
Type: `FILE`
Location: `SYSTEM_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `وحدة تخزين خارجية`
Packagename: `com.android.externalstorage`
Version: `9 (28)`

### Current owners
Appname: `إدارة التنزيل`
Packagename: `addon.sprd.downloadprovider`
Version: `1.0 (1)`

### SD Maid
Version: `5.1.9 (50109)`

### Device
Fingerprint: `Itel/SP557/itel-W5505:9/PPR1.180610.011/OP-V014-20210309:user/release-keys`

**Comment by dragonGod97677** [comment]
Uh no, app with the package name com.android.externalstorage doesn't own DownloadProviderDrmAddon.apk file
