### ISSUE TITLE
App Cache Cleaner hangs on Android 11 on 2 system apps

### ISSUE THREAD

**Issue by JustDew** [d4rken/sdmaid-public#5117]
Media Storage and Wireless Emergency Alerts both hang for about 30 seconds each while App [Cache] Cleaner runs.

It would be helpful to at least Ignore those 2 apps from being cleaned, as both have less than 400KB of cache combined anyways

**Comment by d4rken** [comment]
What device, ROM and SD Maid version?

Does an exclusion do as workaround for now?
https://github.com/d4rken/sdmaid-public/wiki/Exclusions

**Comment by JustDew** [comment]
> What device, ROM and SD Maid version?
> 
> Does an exclusion do as workaround for now?
> https://github.com/d4rken/sdmaid-public/wiki/Exclusions

Galaxy S20 Ultra, Stock ROM on Android 11, SD Maid version 5.1.9

Aaaah yeah exclusion works fine! I just didn't know the Pin icon represented 'exclude.' I would suggest a change to that. But that works well!

**Comment by d4rken** [comment]
>  I would suggest a change to that. But that works well!

Change to what?

**Comment by JustDew** [comment]
> 
> 
> > I would suggest a change to that. But that works well!
> 
> Change to what?

The Pin icon to represent "exclude"

I saw the Pin there, but didn't think to click it to do that. I had assumed it meant Pin "to the top" or some kind of "inclusion" when it meant the opposite

**Comment by d4rken** [comment]
Yes, but what icon represents "exclude" :smile: ?

**Comment by JustDew** [comment]
> 
> 
> Yes, but what icon represents "exclude" 😄 ?

Currently, a Pin represents "Exclude" from the App Cleaner list. To me: a Pin represents something to keep above all else and not 'Exclude'
[https://i.imgur.com/S7dxbRN.jpg](url)

**Comment by d4rken** [comment]
I know what currently represents it :wink:.

> I would suggest a change to that. But that works well!

You suggested to change it, but change it to what?

The original idea was:
SD Maid shows the list of everything that should be removed, so if something should not be removed, "pin it" so it stays.
