### ISSUE TITLE
Bug: System cleaner doesnt work

### ISSUE THREAD

**Issue by Idansh12** [d4rken/sdmaid-public#5118]
### What happened?
I tried to run the system cleaner but its failed

### What did you expect to happen?
I expect the system cleaner to operate like it should

### How can I reproduce the issue?
I opened a Reddit post about that issue and you said its maybe an android 11 issue

### SD Maid
Version: `5.1.9 (50109)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/x1sxx/x1s:11/RP1A.200720.012/G980FXXU9DUH2:user/release-keys`

**Comment by d4rken** [comment]
Can you provide a debug log of this?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

When trying to reproduce this, it looks like you didn't grant access during setup, could that be?

**Comment by Idansh12** [comment]
Hey
The issue is fixed somehow..
Tnx anyway!

בתאריך יום א׳, 26 בספט׳ 2021, 10:52, מאת Matthias Urhahn ‏<
***@***.***>:
