### ISSUE TITLE
Report owner doesn't work when GitHub app is installed

### ISSUE THREAD

**Issue by Avamander** [d4rken/sdmaid-public#5119]
Just as the title says, when the GitHub Android app is installed, reporting a remnant folder doesn't do more than open a blank issue form.

**Comment by d4rken** [comment]
Hm, I still get the app chooser and can pick either github app or the browser.
Did you select a default action?

**Comment by d4rken** [comment]
K, think I got it. It will still force a browser picker even if Github was previously selected as default app.
