### ISSUE TITLE
CorpseFinder dalvik-cache matching on Android 11+

### ISSUE THREAD

**Issue by Kotobober** [d4rken/sdmaid-public#5144]
I created two files `product@app@Test@Test.apk@classes.dex` and `product@app@Test@Test.apk@classes.art`
 under path `/data/dalvik-cache/arm64`, should SD maid delete them? I have dalvik cleaning enabled, but the program did not find these files. I have a lot of files in the dalvik folder, many refer to programs frozen six months ago. Is this normal?

[Screenshot_2021-10-18-23-29-15-764_com speedsoftware rootexplorer](https://user-images.githubusercontent.com/92755209/137798236-c4abbd47-8c67-472f-8ebd-ce2c3d0b1b90.jpg)
[Screenshot_2021-10-18-23-36-28-225_eu thedarken sdm](https://user-images.githubusercontent.com/92755209/137798717-a971d2f1-c50b-41d8-97c9-e584bbf06ab9.jpg)

[Log ](https://drive.google.com/file/d/1-_r1KvQuJFL7sWXH76vCK_iyJ3SJchjX/view?usp=drivesdk) 

[sdmaid_logfile_1634582214039.txt.zip](https://github.com/d4rken/sdmaid-public/files/7391164/sdmaid_logfile_1634582214039.txt.zip)

**Comment by d4rken** [comment]
This is indeed currently not working as it doesn't support some Android 11 specific matching.
