### ISSUE TITLE
Mount applet fails root test  on OnePlus 7 Pro with Lineage 18.1

### ISSUE THREAD

**Issue by PianCat** [d4rken/sdmaid-public#5163]
### What happened?
I have granted the root permission required by SD mail, but it does not work normally. When I check the device status, I find the mount error of the applet

### What did you expect to happen?
I don't know what happened, so I'm confused

### How can I reproduce the issue?
This problem is very strange. I have cleaned and installed magisk again, but it still has no effect. Maybe I can help you capture the log

### SD Maid
Version: `5.3.1 (50301)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `Unknown` (Actually, I own the Magisk Root)
Fingerprint: `google/redfin/redfin:12/SP1A.210812.015/7679548:user/release-keys`

**Comment by d4rken** [comment]
I've not heard feed back from others about this so it seems to be an isolated issue and not a general incompatibility, if this is just a local issue it does not warrant altering SD Maids check.

Closing until information showing otherwise.
