### ISSUE TITLE
Bug: OPPO system cache questions

### ISSUE THREAD

**Issue by Azixe3** [d4rken/sdmaid-public#5166]
### What happened?
Oppo system will get stuck in the application screen when using the accessibility mode to delete cache again, because OPPO color os delete cache has to click into it again

### What did you expect to happen?
Correct work                         

### How can I reproduce the issue?
Just a color os newer phone on the line.

### Comments
None
### SD Maid
Version: `5.3.1 (50301)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `Unknown`
Fingerprint: `OPPO/CPH1919/OP4845:11/RKQ1.200928.002/1629116326651:user/release-keys`

**Comment by d4rken** [comment]
Can you provide a debuglog?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
