### ISSUE TITLE
Cleaner not working

### ISSUE THREAD

**Issue by sweetcock69** [d4rken/sdmaid-public#5167]
> What happened?

Files not getting deleted after performing a clean

> How can I reproduce the issue?

Scan and clean

> SD Maid

SD Maid
5.3.1 (50301) [34975850d, 2021-10-27T13:07:26Z]
Pro Version (Unlocker app)
Unlocker: 4.4.1 (40401)
Experimental mode
true

> Rooted

Su binary
MAGISKSU ea75a09f ([ea75a09f:MAGISKSU])

Arrow OS 12

> ID : 0d59f08f-e0a5-48f7-bab0-c1eff6ef3125

Note : Watch the video.

[sdmaid_logfile_1635651888449.txt.zip](https://github.com/d4rken/sdmaid-public/files/7448046/sdmaid_logfile_1635651888449.txt.zip)

https://user-images.githubusercontent.com/50311435/139566749-a9c98c98-1f18-4f6a-a131-24a64b720173.mp4

**Comment by d4rken** [comment]
could you please check the debug menu and make sure SD Maid is armed?
It should be `Armed: true` and the log says `D/Debug:SysInfoModule: isArmed: false`
:thinking: 

I think you put SD Maid accidentally in test mode...

**Comment by sweetcock69** [comment]
thanks. working fine now
