### ISSUE TITLE
Android 12 storage permissions issue

### ISSUE THREAD

**Issue by Aashishkebab** [d4rken/sdmaid-public#5169]
SD Maid claims "a secondary storage was detected" and asks me to grant access to its path.

However, there is no secondary storage on my device, thus I cannot do this, and the app doesn't work because everything is blocked.

**Comment by d4rken** [comment]
Please provide more details.
Which SD Maid update?

A video and debug log would be good too.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

Thanks!

**Comment by Aashishkebab** [comment]
Currently on version 5.2.2.

Screen recording. It'll ask these questions every time I uninstall an app, since I have Uninstall Watcher turned on.

I can try a debug log for next time, but I'm not sure it'll be particularly helpful as it's a permissions thing.

https://photos.app.goo.gl/2z7VQnedYxFNaPuA7

**Comment by d4rken** [comment]
Try the latest beta, it's not perfect yet, but it should fix this.
