### ISSUE TITLE
Bug: Storage Analyzer Issue

### ISSUE THREAD

**Issue by FXCROG** [d4rken/sdmaid-public#5172]
### What happened?
I updated to 5.3.3.Storage Analyzer shows nothing in /data.This issue doesn't exist in 5.3.2 and earlier.     Redmi Note 5 Pro@Android 10 with Root Access.

### What did you expect to happen?
Storage Analyzer works fine with /data.Just like 5.3.2.

### How can I reproduce the issue?
Use SD Maid 5.3.3 at an Android 9 or 10 device with Root Access.Storage Analyzer shows nothing in /data.When you switch back to 5.3.2.Issue disappear.

### SD Maid
Version: `5.3.3 (50303)`
Pro: `isPro=true || isComplete=false (unl=true, iap=null, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/coral/coral:10/QQ2A.200501.001.B2/6352890:user/release-keys`

**Comment by d4rken** [comment]
Can you provide a debug log?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

This may be related to changes i made to get SD Maid to pick up `/data_mirror` on Android 11+.

**Comment by FXCROG** [comment]
Here is my debug log.

[sdmaid_logfile_1635845479671.txt](https://github.com/d4rken/sdmaid-public/files/7459466/sdmaid_logfile_1635845479671.txt)

**Comment by d4rken** [comment]
Thanks.

SD Maid is picking the wrong permission (`NORMAL`) instead of `ROOT` to read `/data`, likely because `/data` is readable without root, just the subdirectories not.

Will fix with next update.

**Comment by d4rken** [comment]
@FXCROG Does it happen everytime?
I'm trying to reproduce on a Pixel2@Android10 and it works.

Could you record a debuglog containing a cold-start of SD Maid (force-stop after starting log)?
I'd like to see the detected storage types.

**Comment by d4rken** [comment]
Got it :partying_face:

**Comment by FXCROG** [comment]
> @FXCROG Does it happen everytime? I'm trying to reproduce on a Pixel2@Android10 and it works.
> 
> Could you record a debuglog containing a cold-start of SD Maid (force-stop after starting log)? I'd like to see the detected storage types.

Here is another debug log.
[sdmaid_logfile_1635870336849.txt](https://github.com/d4rken/sdmaid-public/files/7462396/sdmaid_logfile_1635870336849.txt)

Hope you can fix this as soon as possible.Because I use "SD Maid Storage Analyzer+Root Access" to clean /data every day.

Thanks.           :)
