### ISSUE TITLE
QuickAccess AppCleaner ACS hint not displayed when pressing the bottom button bar

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#5178]
If the AppCleaner is the only tool that has found anything after a search, and the user presses the bottom button bar, then we should show the same dialog with instructions regarding the ACS that we show if the individual delete button is clicked.

I think the code is already ready for this, we would just have to filter out empty tasks when the button bar is pressed :thinking:

**Comment by neloy20** [comment]
App deleted not work
