### ISSUE TITLE
Small SDMaid icon won't disappear

### ISSUE THREAD

**Issue by selimovd** [d4rken/sdmaid-public#5181]
Since the last usage of SD Maid I always see a tiny icon on my screen and I have no idea how I can make it dissappear. Please see the Screenshot for an example
![Screenshot_20211110-223700~2](https://user-images.githubusercontent.com/33289808/141362613-ce84fd9a-a574-4ebc-a610-96c0124b87d3.png)

And help is appreciated

**Comment by d4rken** [comment]
This is an option in the system's accessibility settings. You activiated two toggles, but you just need the first one, the second one creates this "on demand" accessibility option, just disable it again.

**Comment by selimovd** [comment]
I'm an idiot. Didn't look at the andoid settings, only in the SD Maid settings. Sorry for that and thank you for the help, that worked.
Thank you and wish you a great weekend
