### ISSUE TITLE
Support `Android/data` access on Android 11&12 without root

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#5183]
Rel #5180 #5182

A workaround may still be possible on Android 11.

tbc

**Comment by d4rken** [comment]
I got it to work. SAF based access to `Android/data` for all public storages.

Kudos to the devs of X-Plore file manager :beers:! A user reported that their app can still access `Android/data`.
Just using it was enough to spark the fire on how it's done.

The issue on Android 11+ is that, if you raise the target API to 30, getting SAF access to the parent of `Android/data` (e.g. `Android`), does not show `data` when calling `listFiles()`.
I'm not actually sure if  you can handcraft the uri based on the tree-uri from e.g. `Android` as you can't select a parent of `Android/data` in the SAF path picker (neither `/sdcard/` nor `/sdcard/Android`).

But here's the trick: You can supply a hand-crafted document uri to the SAF path picker via the `EXTRA_INITIAL_URI` intent extra, and it will open on `Android/data` and let you select it, granting access. :mage:.

**Comment by eodrap** [comment]
Thanks @d4rken for your work on this. I have a OnePlus Nord running Android 11, and in the 5.3.6 beta I am prompted to allow access to `/storage/emulated/0/Android/data`. When trying to allow this, a file picker opens in the directory, I can allow access but it remains inaccessible to SD Maid. If I use the Advanced Settings option to add storage, I can grant access to the `Android/data` directory but this doesn't permit access.

**Comment by d4rken** [comment]
@eodrap Thanks for the feedback. I've looked into it and it is a OnePlus specific issue.
One Plus has a feature called "Parallel Storage" due to which the system returns the internal storage twice, once what SD Maid expects, and the other one being the "Parallel Storage". SD Maid fails to handle that as both storages have the same "URI" and I expected that there can't be two storages with the same URI.

I've added handling for this in the next update (5.3.7), if it's not fixed then, please make a new ticket with a debug log :+1:

**Comment by eodrap** [comment]
Thanks @d4rken - I can confirm your latest changes have fixed this. Thanks so much.
