### ISSUE TITLE
Deletion of old WhatsApp backup s

### ISSUE THREAD

**Issue by deblood3** [d4rken/sdmaid-public#5185]
I have setup app cleaner to delete old WhatsApp backups older than 1 day.  I just noticed yesterday, when l ran app cleaner, old Whatsapp backups were not getting deleted.

Upon examination, l found out WhatsApp have recently changed their backup extension to .crypt15. 

I am bringing this to you attention for action.

Thanks
Alfred. 

[SmartSelect_20211116-064802_My Files](https://user-images.githubusercontent.com/1439229/141991304-67e44c18-fe0d-4f91-a8f1-614112b82810.jpg)

**Comment by deblood3** [comment]
Just letting you know that old WhatsApp backups with extension of crypt15 are still not getting deleted when l ran app cleaner.

**Comment by d4rken** [comment]
Should be fixed with the next update.

**Comment by deblood3** [comment]
Thanks!!!

Alfred Yeboah

**Comment by deblood3** [comment]
Issue fixed after latest update ( ver 5.3.1.4)

Thanks,

Alfred Yeboah
