### ISSUE TITLE
AppCleaner ACS matching fails

### ISSUE THREAD

**Issue by Alawshe42** [d4rken/sdmaid-public#5192]
I first bought this in 2008 , and have been charged 2 times again because it wouldnt restore. Now when scanning and trying to delete  caches till it clears and says zero, now its saying can't delete, also when deleting for app cleaner, its like so so slow ,like it pops up different things. If it says 158 its literally a slow count to 158.

**Comment by d4rken** [comment]
Please full out the bugreport form correctly next time.

> I first bought this in 2008 , and have been charged 2 times again because it wouldnt restore.

SD Maid was created in 2011. I don't do any "charging" this is done by Google. Contact Google Payments or your bank if there is an issue. Most likely you confused upgrades or logged in with the wrong Google account.

> Now when scanning and trying to delete caches till it clears and says zero, now its saying can't delete, also when deleting for app cleaner, its like so so slow ,like it pops up different things. If it says 158 its literally a slow count to 158.

I can fix this if you provide a debug log of it:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
