### ISSUE TITLE
Bug: Is there a way to get back my root access?

### ISSUE THREAD

**Issue by secret-pan** [d4rken/sdmaid-public#5198]
### What happened?
I can't really access the full data storage with SD maid.

### What did you expect to happen?
I was hoping SD maid could get access to my original system. I think right now it's just emulated. Do you know what I mean? Sorry for my bad english, its not my first language. I hope you could help me somehow. Thanks a lot! ☺️

### How can I reproduce the issue?
I downloaded a new ROM, installed it and since then I can't really get back to my original system. I don't know how to bettet to explain it. If I can give you any useful information, please ask me. I am a total newbie.

### Comments
Right now I feel frustrated about the situation. 😅
### SD Maid
Version: `5.3.5 (50305)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `realme/RMX2075EEA/RMX2075L1:11/RKQ1.200710.002/1634955735587:user/release-keys`

**Comment by d4rken** [comment]
This is unrelated to SD Maid and not something I can help you with, sorry.

Try xda-developers.com and a sub forum specific to your device.
