### ISSUE TITLE
On versions above 5.2.2 in AppControl➔app➔size nonexistent paths appeared on the memory card zero size. Shield Tablet Android 7.0

### ISSUE THREAD

**Issue by master1274** [d4rken/sdmaid-public#5202]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android 10]

**Additional context**
[Screenshot_20211118-124323](https://user-images.githubusercontent.com/20639709/142890000-332cdc60-1e5a-4ae4-b886-bf69d070c295.png)
[Screenshot_20211118-124913](https://user-images.githubusercontent.com/20639709/142890046-30e4b475-a409-48c1-9c39-20def0c6c7d1.png)

**Comment by d4rken** [comment]
Can you provide a debuglog?

Does your device have an sdcard?

So the issue would be that SD Maid shows paths to folders that don't exist?

The paths look actually correct in the sense that, "if they exist", they would belong to this app.

But it's confusing and I agree that if they don't exist, it should not be shown :thinking:

**Comment by d4rken** [comment]
Please report back after the next update.

**Comment by master1274** [comment]
Thanks, 5.3.7 is fixed.

**Comment by master1274** [comment]
I apologize, there were problems with the mail, no notifications were
received. The problem has been fixed in update 5.3.7. Thanks for
participating.

вт, 23 нояб. 2021 г., 14:42 Matthias Urhahn ***@***.***>:
