### ISSUE TITLE
accessibility service is not working correctly

### ISSUE THREAD

**Issue by WoTflix** [d4rken/sdmaid-public#5211]
Hello @d4rken 
**Describe the bug**
SD Maid accessibility service is not working correctly. You have activated features that use the SD Maid accessibility service. The service is enabled but not started.

**To Reproduce**
1. Open the sd maid
2. Click on scan AppCleaner
3. Click clear AppCleaner
4. AppCleaner does not clear when clicking clear

**Expected behavior**
The accessibility cleaner should run through the app list cleaning each app as expected.
**Screenshots**

**Debug log**
[1](https://1drv.ms/u/s!AlSbX6ZNxNVigQlq6aVMSKSKlO5g?e=GpPtmx) 
[2](https://1drv.ms/u/s!AlSbX6ZNxNVigQryNRvEbh4q_W25?e=gyUudy) 
**Smartphone (please complete the following information):**
 - Device: CUBOT NOTE 9
 - OS: Android 11

**Additional context**
The first run cleans up every app, but the second run after a while doesn't clean up every app

**Comment by d4rken** [comment]
This is a ROM issue related to battery optimizations, there is no fix on my end AFAIK.
Also see: https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting
