### ISSUE TITLE
Lost pro features!

### ISSUE THREAD

**Issue by florincristea** [d4rken/sdmaid-public#5213]
Hi! After update the app from Google Play Store to 5.3.8 version, i lost premium features! I Have a Motorola Edge 20 Pro with Android 11 stock! Thank you!

**Comment by d4rken** [comment]
There are 3 upgrade options, which one are you using?
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#upgrade-options

**Comment by florincristea** [comment]
Solved! Uninstall, i clear all data from Play Store and install it again! Thank you!
