### ISSUE TITLE
Restore File Extensions...

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/sdmaid-public#5216]
Can you provide a feature that will scan and list files without extensions, and provide the option to (automatically) add extension to files that don't have them?

This is especially useful for files inside the WhatsApp folder. WhatsApp tends to rename several files with a generic name without an extension, like DOC-20211205-WA0001, which makes it impossible to identify or find using the search feature.

**Comment by d4rken** [comment]
Hm, where does this fit, Explorer?
Does this need to be recursive?
Does Android offer a build-in way to identify the file types? :thinking:

**Comment by TheMysticS** [comment]
> Hm, where does this fit, Explorer? Does this need to be recursive? Does Android offer a build-in way to identify the file types? 🤔

SD Maid is able to identity files correctly even when some of them don't have an extension. 

For example, if i download an apk and share it on WhatsApp, the apk file is renamed to DOC-20211205-WA0003 or something like that. 

Now if i run Duplicates cleaner, it deletes the file in the downloads folder, while retaining the one in WhatsApp sent folder (since I have configured to retain deeply nested files).

After running Duplicates cleaner, I am unable to find the apk since both the name and extension in the retained file is gone (the apk now has the generic whatsapp filename as stated above without an extension).

SD Maid is able to identity files, even if their names and extensions have changed. So you would know better.

This can be integrated with the Explorer feature or as a separate utility, if required.
