### ISSUE TITLE
Bug: Accessibility service gets always killed when app is in the background

### ISSUE THREAD

**Issue by COUPON4Vitamins** [d4rken/sdmaid-public#5224]
### What happened?
It's very annoying having to restart every time the accessibility service when I'm opening SD Maid

### What did you expect to happen?
The accessibility service should be kept alive always unless stopped by myself

### How can I reproduce the issue?
Whenever I leave SD Maid the accessibility service gets killed after a few minutes

### Comments
Please fix so that the accessibility service doesn't get killed in the background by the OS. A persistent notification would help!
### SD Maid
Version: `5.3.10 (50310)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `BMXC/M107-EEA/M107-EEA:9/PPR1.180610.011/vMA110002:user/release-keys`

**Comment by d4rken** [comment]
That's mostly an OS issue, not an SD Maid issue, see here:
https://github.com/d4rken/sdmaid-public/issues/4386#issuecomment-753662688

For ROMs where the OS is not killing the service, showing a constant  notification would probably be annoying.

**Comment by d4rken** [comment]
The only case I could fix from my end would be crashes, but afaict the ACS service is not crashing, or do you see any related stacktraces in logcat?

**Comment by COUPON4Vitamins** [comment]
SD Maid itself does not crash. But you could make an optional persistent notification option in General Settings which is not set by default on. So only peeps with this problem will enable the persistent notification and no one else would complain. Pls consider since so many Android devices now are very aggressive with killing apps in the background.

**Comment by COUPON4Vitamins** [comment]
WOOHOO finally found the solution! I just cleared all storage in app info to reset SD Maid and since then the Accessibility Service isn't killed anymore! Why didn't i think that sooner lol
