### ISSUE TITLE
This service is malfunctioning

### ISSUE THREAD

**Issue by WoTflix** [d4rken/sdmaid-public#5225]
**Describe the bug**
This service is malfunctioning

**To Reproduce**

https://user-images.githubusercontent.com/95138610/145197252-0e72c786-45f9-43fb-af05-0335bb03a730.mp4

**Expected behavior**
The accessibility cleaner should run through the app list cleaning each app as expected.

**Screenshots**
![Screenshot_20211208-125359](https://user-images.githubusercontent.com/95138610/145198150-af481b2e-275f-4e5e-8d40-3b4bcd14eaca.png)
![Screenshot_20211208-124929](https://user-images.githubusercontent.com/95138610/145198243-5dd909ab-1fc4-4ccc-a0ce-266660f936be.png)
![Screenshot_20211208-124954](https://user-images.githubusercontent.com/95138610/145198306-87eb44cf-0c39-4afb-b58b-ec79a60e534d.png)

**Debug log**
[sdmaid_logfile_1638960897167.txt.zip](https://github.com/d4rken/sdmaid-public/files/7675551/sdmaid_logfile_1638960897167.txt.zip)

**Smartphone (please complete the following information):**
 - Device: CUBOT NOTE 9
 - OS: Android 11

**Additional context**

**Comment by d4rken** [comment]
The system may say that the service is malfunctioning, but it could be the system itself causing it.

Please check that battery optimizations are not causing the system to kill the service:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting

I checked SD Maids log and there is no error.

Can you see an error from the system in logcat?

**Comment by WoTflix** [comment]
> The system may say that the service is malfunctioning, but it could be the system itself causing it.
> 
> Please check that battery optimizations are not causing the system to kill the service: https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting
> 
> I checked SD Maids log and there is no error.
> 
> Can you see an error from the system in logcat?

No

**Comment by d4rken** [comment]
Currently nothing to do on my end, this looks like the system just killing the service for which the linked troubleshooting section applies, if you have any instructions I can add there, let me know :coffee:

**Comment by d4rken** [comment]
This used fixed it by clearing SD Maids data, but I think this is just "turn it off and on again" there is nothing in SD Maids storage that should affect this:
https://github.com/d4rken/sdmaid-public/issues/5224#issuecomment-1013388064
