### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1474573195748.log (FP)

### ISSUE THREAD

**Issue by DO97** [d4rken/sdmaid-public#523]
Missing feature. Samsung private mode detection.
![screenshot_20160922-214418](https://cloud.githubusercontent.com/assets/17525578/18763921/a046091a-810f-11e6-9903-a38255087544.jpg)

### Target
Target: `/storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1474573195748.log`
Prefix-free: `eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1474573195748.log`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `SD Maid`
Packagename: `eu.thedarken.sdm`
Version: `4.3.3 (40303)`

### Current owners
Appname: `SD Maid`
Packagename: `eu.thedarken.sdm`
Version: `4.3.3 (40303)`

### SD Maid
Version: `4.3.3 (40303)`

### Device
Fingerprint: `samsung/zeroltexx/zerolte:6.0.1/MMB29K/G925FXXS4DPH2:user/release-keys`

I bet that there's something wrong, sorry.
There are some private information that I should delete or it's all OK?

**Comment by d4rken** [comment]
Please don't use the clutter report tool to create issue tickets that are not clutter reports.

Yes the debug log may contain private information in form of the file names on your device.

If you are not ok with that, you can also email me (support mail) the debug log and I'll pull the necessary information from it.
