### ISSUE TITLE
Does not clear cache on click "Debug Accessibility Service"

### ISSUE THREAD

**Issue by WoTflix** [d4rken/sdmaid-public#5247]
**Describe the bug**
Does not clear cache on click "Debug Accessibility Service"

**To Reproduce**

https://user-images.githubusercontent.com/95138610/147120750-a7e1f8db-16f2-49ac-8598-44d4ad1d0037.mp4

**Debug log**
[sdmaid_logfile_1640188047835.txt.zip](https://github.com/d4rken/sdmaid-public/files/7763758/sdmaid_logfile_1640188047835.txt.zip)

**Smartphone (please complete the following information):**
 - Device: CUBOT NOTE 9
 - OS: Android 11

**Comment by d4rken** [comment]
This is not supposed to work like this.
The debug accessibility option is used for a human to manually showing an interaction.
