### ISSUE TITLE
Clutterreport: /d (new)

### ISSUE THREAD

**Issue by koyb** [d4rken/sdmaid-public#526]
### Target
Target: `/d`
Prefix-free: `/d`
Path-prefix: ``
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `cn.com.zte.settings.patch`
Packagename: `cn.com.zte.settings.patch`
Version: `4.4.4-20150821.163315.3491 (19)`

### Current owners
None
### SD Maid
Version: `4.3.2 (40302)`

### Device
Fingerprint: `ZTE/ZTE_WELLINGTON/wellington:4.4.4/KTU84P/20150821.163315.3491:user/release-keys`

### Comment
`need to unblock`

**Comment by d4rken** [comment]
?
