### ISSUE TITLE
Add language support

### ISSUE THREAD

**Issue by WoTflix** [d4rken/sdmaid-public#5266]
Locale/language: Russian (ru_RU) Version: Android 11 Device: CUBOT NOTE 9
![Screenshot_20211229-220331](https://user-images.githubusercontent.com/95138610/147701890-ac8118aa-6674-4ea0-949d-6f2b429c054e.png)
Item 1 `Память и кэш`
![Screenshot_20211229-221305](https://user-images.githubusercontent.com/95138610/147702061-8c6a9296-808f-4f35-8d9e-e7e208ee183e.png)
Item 2 `ОЧИСТИТЬ КЕШ`

**Comment by d4rken** [comment]
Could you provide a short debug log of SD Maid failing 1-2 apps?

**Comment by WoTflix** [comment]
> Could you provide a short debug log of SD Maid failing 1-2 apps?

[sdmaid_logfile_1640859791787.txt.zip](https://github.com/d4rken/sdmaid-public/files/7792514/sdmaid_logfile_1640859791787.txt.zip)

https://user-images.githubusercontent.com/95138610/147743450-c539abcb-e4c9-451c-9ccb-307c7b5bb1da.mp4

**Comment by WoTflix** [comment]
[sdmaid_logfile_1640859791787.txt.zip](https://github.com/d4rken/sdmaid-public/files/7797640/sdmaid_logfile_1640859791787.txt.zip)

https://user-images.githubusercontent.com/95138610/147850240-3ef765d7-dc0d-420b-9490-b0cfa9cd89f2.mp4

**Comment by d4rken** [comment]
Thanks, should work with the next update :+1:
