### ISSUE TITLE
phone rebooting repeatedly after running scheduled tasks

### ISSUE THREAD

**Issue by gacouchx** [d4rken/sdmaid-public#5267]
**Describe the bug**
After App Cleaner and System Cleaner run on schedule, phone repeatedly rebooted, and misbehaved badly, until I removed those tasks from schedule. I couldn't even open my "Settings" without the phone suddenly rebooting. After removing recently installed apps, the problem persisted until I stopped the two functions mentioned above, in SDMaid. I've had SDMaid on my phone, and scheduled to do the same maintenance for at least a couple of years, with no problems. This all started approximately 2 to 3 weeks ago.

**To Reproduce**
Run scheduled maintenance that includes App Cleaner and System Cleaner

**Expected behavior**
That the app would rubber the scheduled maintenance without any issues from the phone. 

**Smartphone (please complete the following information):**
 - Device: LG X Venture
 - OS: Android 7

**Comment by d4rken** [comment]
Is your device rooted?

Without root, any ROM reboot situations are bugs in the ROM itself and rarely fixable on my end.

Please provide a debug log and narrow down whether it's caused by AppCleaner or SystemCleaner.

**Comment by d4rken** [comment]
Note that sudden reboots could also be caused by a dying sdcard.

**Comment by gacouchx** [comment]
Actually I'm beginning to think it's a faulty battery. Tho stopping those2 
processes helped, it only did for about 4 days. Now it's back to doing it 
again.
I apologize for thinking it had anything to do with SD Maid.

On December 30, 2021 4:17:47 AM Matthias Urhahn ***@***.***> 
wrote:
>
> Note that sudden reboots could also be caused by a dying sdcard.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


____________________________________________________________
Choose to be safer online.
Opt-in to Cyber Safety with NortonLifeLock.
Plans starting as low as $6.95 per month.*
https://store.netzero.net/account/showService.do?serviceId=nz-nLifeLock&utm_source=mktg&utm_medium=taglines&utm_campaign=nzlifelk_launch&utm_content=tag695&promoCode=A34454
