### ISSUE TITLE
Running apps can't be determined on Android N

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#527]
Since Lollipop we can't use the API to get running apps.
And now since Nougat we can't use proc to determine running apps.

😢 

Possibly solutions:
- On rooted devices use root for this (currently not doing that)
- On unrooted devices ask the user to grant permission to access USAGE_STATS

**Comment by d4rken** [comment]
- [x] If root is available, use a root shell to determine running apps.

**Comment by AndreaCioccarelli** [comment]
Google have restricted the "proc" usage. Try something different

**Comment by d4rken** [comment]
@AndreaCioccarelli That's what I said in my post...

**Comment by d4rken** [comment]
Well isn't so easy... but

* We fall back to use `getRunningServices()` if `/proc` unavailable and we can't have root
* If `getRunningServices()` is returning empty, or it just contains our app (e.g. faked like `getRunningAppProcesses()`, then we query the `UsageStatsManager` for the last 3 seconds.

Querying the `UsageStatsManager` requires additional permission which are currently only requested if experimental features are turned on, as I don't know an Android version yet where `getRunningServices()` breaks (and we don't want to slap the user with another permission request).

The issue with determing running apps via the `UsageStatsManager` is that it does not always updates it's data so you either have to force it to update (e.g. switch apps, go home screen), which doesn't work for background operations, or we have to increase the interval so much that it's too inaccurate to determine currently running apps...

**Comment by d4rken** [comment]
Actually scrapping the usage stats based lookup again, just doesn't work reliably for background operations, and! there are issues with Samsung devices... *sigh*.
