### ISSUE TITLE
Clutterreport: /storage/F4DA-8453/.eCtcQjbu1dgnvtFnvnr6yepTp1M=/.nomedia (new)

### ISSUE THREAD

**Issue by PETE95x** [d4rken/sdmaid-public#5270]
### Target
Target: `/storage/F4DA-8453/.eCtcQjbu1dgnvtFnvnr6yepTp1M=/.nomedia`
Prefix-free: `.eCtcQjbu1dgnvtFnvnr6yepTp1M=/.nomedia`
Path-prefix: `/storage/F4DA-8453/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android Services Library`
Packagename: `com.google.android.ext.services`
Version: `aml_ext_301900200 (301900200)`

### Current owners
None

### SD Maid
Version: `5.3.10 (50310)`

### Device
Fingerprint: `Alcatel/6025H_EEA/HONG_KONG:11/RP1A.200720.011/9MBA:user/release-keys`

**Comment by PETE95x** [comment]
I am new to SDMaid and I am attempting to use it's features!

**Comment by d4rken** [comment]
Please only use the clutter report function if you know what you are doing :wink: 
Use it to report a false positiv, a file that SD Maid missidentifies as belonging to the wrong app.

Happy new year
