### ISSUE TITLE
Accessibility service not working on Pixel devices since March Android update

### ISSUE THREAD

**Issue by Fizzle147** [d4rken/sdmaid-public#5272]
**Describe the bug**
AppCleaner becomes hung up while trying to utilize Accessibility service to clear app caches - can't seem to identify correct location on screen of "Storage and cache" item on Android 12.

**To Reproduce**
1. Run AppCleaner
2. Screen overlay appears, phone navigates to "App info" screen for app with largest current cache
3. Instead of proceeding to navigate to "Storage and cache" to clear the app's cache, the "App info" screen for the given app hangs for a second and then reloads without having the cache cleared.
4. This repeats until AppCleaner gives up.

**Expected behavior**
Expected AppCleaner to successfully navigate to given app's "App info" screen, then to "Storage and cache" screen, and then hit "Clear cache" button before moving on to the next app to be cleaned.

**Screenshots**
[Screen recording of failure](https://imgur.com/a/VUmzq0h) 

**Debug log**
[sdmaid_logfile_1641173281418.txt.zip](https://github.com/d4rken/sdmaid-public/files/7800068/sdmaid_logfile_1641173281418.txt.zip)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12

**Additional context**
Attempted to use "Custom accessibility sequence" setting to direct automation, but it did not work.

**Comment by d4rken** [comment]
I first thought this was a labeling issue but it seems to be a system issue, it's telling SD Maid that there is now root window:

```java
No valid root-node found: eu.thedarken.sdm.accessibility.core.crawler.CrawlerException: Root node is currently null
```

Not much I can do here afaik.

**Comment by palfiszabolc** [comment]
Same problem for me.

**Comment by d4rken** [comment]
@palfiszabolc Same device? Please provide a debug log.

If it's a different device, open a new ticket.

**Comment by vladrevers** [comment]
Pixel 4a, Android 12L, same problem and error, based on the log.

**Debug log**
[sdmaid_logfile_1643876917289.txt](https://github.com/d4rken/sdmaid-public/files/7992973/sdmaid_logfile_1643876917289.txt)

**Comment by d4rken** [comment]
Hm not much I can do about that error AFAIK, is this a permanent state or does rebooting help? Or turning the service on/off?

**Comment by vladrevers** [comment]
> a permanent state or does rebooting help? Or turning the service on/off?

permanent

**Comment by d4rken** [comment]
AFAIK this is a device issue that I can't fix on my end, if someone shares instructions on how to fix this state I can add them to documetnation.

**Comment by vladrevers** [comment]
> if someone shares instructions on how to fix this state

Everything magically works if you turn on the "Select to speak" or "Talkback" function.

![Screenshot_20220220-230926](https://user-images.githubusercontent.com/56305121/154864570-746fb3ec-c5e9-40b1-972e-fa668e1971c5.png)

![Screenshot_20220220-230932](https://user-images.githubusercontent.com/56305121/154864581-a35bc7f9-7f73-422e-9cf0-c28ce8cdec97.png)

**Comment by d4rken** [comment]
Curious, so enabling either options works?

Can you get me debug logs again?
* Both off
*  "Select to speak"  on
* "Talkback"  on

Trying to clean a single app while recording the log is sufficient.

Thinking out loud: Maybe SD Maid can request an option similar to these, to trigger the fix on its on :thinking: 
Biggest hurdle is currently though that I'm unable to reproduce.

**Comment by vladrevers** [comment]
@d4rken
> so enabling either options works?

Yes, but it is preferable to "Select To Speak", with it there are no extra sounds, vibrations, difficulties in control, as with "Talkback"

> Can you get me debug logs again?

- [sdmaid_logfile_bothOff.txt](https://github.com/d4rken/sdmaid-public/files/8110300/sdmaid_logfile_bothOff.txt)
- [sdmaid_logfile_selectToSpeakOn.txt](https://github.com/d4rken/sdmaid-public/files/8110301/sdmaid_logfile_selectToSpeakOn.txt)
- [sdmaid_logfile_TalkBackOn.txt](https://github.com/d4rken/sdmaid-public/files/8110307/sdmaid_logfile_TalkBackOn.txt)

**Comment by mcl21014** [comment]
I attempted to check the AppCleaner with TalkBack enabled under Accessibility, but it was a nightmare to navigate the phone. I did, however, enable the Select to Speak option under Accessibility and AppCleaner worked without issue. Also we're due for one more 12 L beta before the final release drops.

Device: Pixel 6 Pro
Android version: 12L beta 3

**Comment by vasudev-gm** [comment]
> @d4rken
> 
> > so enabling either options works?
> 
> Yes, but it is preferable to "Select To Speak", with it there are no extra sounds, vibrations, difficulties in control, as with "Talkback"
> 
> > Can you get me debug logs again?
> 
>     * [sdmaid_logfile_bothOff.txt](https://github.com/d4rken/sdmaid-public/files/8110300/sdmaid_logfile_bothOff.txt)
> 
>     * [sdmaid_logfile_selectToSpeakOn.txt](https://github.com/d4rken/sdmaid-public/files/8110301/sdmaid_logfile_selectToSpeakOn.txt)
> 
>     * [sdmaid_logfile_TalkBackOn.txt](https://github.com/d4rken/sdmaid-public/files/8110307/sdmaid_logfile_TalkBackOn.txt)
@vladrevers Thanks for the workaround.
Same issue on Pixel 4a after Android 12L update. Only workaround is Adding accessibility shortcut for Select to Speak afterwards everything is working for now.
@d4rken Should we/Pixel users file it as an issue in google issue tracker?

**Comment by d4rken** [comment]
> @d4rken Should we/Pixel users file it as an issue in google issue tracker?

I've filed a report here: https://issuetracker.google.com/issues/223809542

I also noticed that if i disable the overlay and then manually click SD Maid once into a "deeper page" of the app details, and then return back to the top level screen where SD Maid is stuck on, then it works and data is returned for the screen.

It looks like some kind of refresh/caching issue bug that Google introduced?

I couldn't reproduce it on a Pixel 6, though, only on my Pixel 5 since the latest security update.

**Comment by adrawdet** [comment]
Running into the same issue as well.

Pixel 6, Android 12.1.
Let me know if you need anymore logs.

[sdmaid_logfile_1648041344481.txt.zip](https://github.com/d4rken/sdmaid-public/files/8335294/sdmaid_logfile_1648041344481.txt.zip)

**Comment by d4rken** [comment]
Another workaround I've found is to enable the accessibility service of certain other apps, e.g. [Microsofts Authenticator app](https://play.google.com/store/apps/details?id=com.azure.authenticator). Just enabling their service in system settings is enough to fix the issue. 

I have not yet been able to find out what exactly their service does on launch, that acts as a workaround for this issue.

**Comment by d4rken** [comment]
For giggles I added a second service to SD Maid and it fixed the issue :thinking: , I'm narrowing in on a solution :partying_face: . Just need a bit more time...

**Comment by d4rken** [comment]
I updated Google's ticket with a deeper explanation and a test app on how to reproduce it, not much more I can do on that front, still no idea why this changed with the update, could be that it actually was a "security issue" and they previously didn't check this flag even though they should?

In any case, by altering the service flags, this should work again, so we have a workaround :).

Fix in next update (likely sometime this week when I get a few  quiet hours).
