### ISSUE TITLE
Clutterreport: /data/local/tmp/shizuku_starter (new)

### ISSUE THREAD

**Issue by George-Seven** [d4rken/sdmaid-public#5298]
### Target
Target: `/data/local/tmp/shizuku_starter`
Prefix-free: `local/tmp/shizuku_starter`
Path-prefix: `/data/`
Type: `FILE`
Location: `DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Shizuku`
Packagename: `moe.shizuku.privileged.api`
Version: `12.4.3.r713.e5d22d5 (713)`

### Current owners
None

### SD Maid
Version: `5.3.10 (50310)`

### Device
Fingerprint: `Redmi/excalibur_in/excalibur:10/QKQ1.191215.002/V12.0.4.0.QJXINXM:user/release-keys`

**Comment by d4rken** [comment]
Unsupported location.
