### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/.Trash (FP)

### ISSUE THREAD

**Issue by irameltzer** [d4rken/sdmaid-public#5299]
### Target
Target: `/storage/emulated/0/Android/.Trash`
Prefix-free: `Android/.Trash`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `My Files`
Packagename: `com.sec.android.app.myfiles`
Version: `13.0.00.434 (1300005434)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `12 (31)`

### SD Maid
Version: `5.3.10 (50310)`

### Device
Fingerprint: `samsung/p3sxxx/p3s:12/SP1A.210812.016/G998BXXU4BULF:user/release-keys`

### Comment
`Samsung Trash folder, might contain user deleted items `

**Comment by Sfwilly72** [comment]
Fushadeyoulyingcheater
