### ISSUE TITLE
Clutterreport: /system/priv-app/Accessibility/Accessibility.apk (FP)

### ISSUE THREAD

**Issue by Pirunchy75** [d4rken/sdmaid-public#5304]
### Target
Target: `/system/priv-app/Accessibility/Accessibility.apk`
Prefix-free: `Accessibility/Accessibility.apk`
Path-prefix: `/system/priv-app/`
Type: `FILE`
Location: `SYSTEM_PRIV_APP`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Actualizar configuración`
Packagename: `com.samsung.android.providers.carrier`
Version: `1.0.31 (103100000)`

Appname: `Ajustes`
Packagename: `com.samsung.android.SettingsReceiver`
Version: `11 (30)`

Appname: `Aplicaciones`
Packagename: `com.samsung.android.app.appsedge`
Version: `7.1.36.0 (713605000)`

### Current owners
Appname: `Accesibilidad`
Packagename: `com.samsung.accessibility`
Version: `12.1.02.2 (1210202000)`

### SD Maid
Version: `5.3.10 (50310)`

### Device
Fingerprint: `samsung/a22nnxx/a22:11/RP1A.200720.012/A225FXXU1AUF2:user/release-keys`

**Comment by richarddoratiotofy-del** [comment]
> ### Target
> Target: `/system/priv-app/Accessibility/Accessibility.apk` Prefix-free: `Accessibility/Accessibility.apk` Path-prefix: `/system/priv-app/` Type: `FILE` Location: `SYSTEM_PRIV_APP` Current keeper state: `false` Suggested keeper state: `true`
> 
> ### Suggested owners
> Appname: `Actualizar configuración` Packagename: `com.samsung.android.providers.carrier` Version: `1.0.31 (103100000)`
> 
> Appname: `Ajustes` Packagename: `com.samsung.android.SettingsReceiver` Version: `11 (30)`
> 
> Appname: `Aplicaciones` Packagename: `com.samsung.android.app.appsedge` Version: `7.1.36.0 (713605000)`
> 
> ### Current owners
> Appname: `Accesibilidad` Packagename: `com.samsung.accessibility` 

[manual_xadrez.pdf](https://github.com/user-attachments/files/23436031/manual_xadrez.pdf)
