### ISSUE TITLE
Clutterreport: /system/app/CityVideo-phone-signed-aligned (FP)

### ISSUE THREAD

**Issue by INFAMOUSBLISS** [d4rken/sdmaid-public#531]
### Target
Target: `/system/app/CityVideo-phone-signed-aligned`
Prefix-free: `CityVideo-phone-signed-aligned`
Path-prefix: `/system/app/`
Location: `SYSTEM_APP`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Application installer`
Packagename: `com.sec.android.preloadinstaller`
Version: `5.1.1-G530WVLU1APG2 (22)`

### Current owners
None
### SD Maid
Version: `4.3.2 (40302)`

### Device
Fingerprint: `samsung/gprimeltevl/gprimeltecan:5.1.1/LMY47X/G530WVLU1APG2:user/release-keys`

**Comment by INFAMOUSBLISS** [comment]
This is invasion of privacy fucking cops

**Comment by d4rken** [comment]
Can you elaborate?

I don't think `com.sec.android.preloadinstaller` owns `/system/app/CityVideo-phone-signed-aligned`.

**Comment by INFAMOUSBLISS** [comment]
Yes but really I did not

**Comment by INFAMOUSBLISS** [comment]
How do I take it off or block it
