### ISSUE TITLE
Clutterreport: /storage/emulated/0/VidMate

### ISSUE THREAD

**Issue by Loafie1** [d4rken/sdmaid-public#5311]
### Target
Target: `/storage/emulated/0/VidMate`
Prefix-free: `VidMate`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `VidMate`
Packagename: `com.video.fun.app`
Version: `4.5202 (45202)`

### Current owners
Appname: `?`
Packagename: `com.nemo.vidmate`
Version: ` (-1)`

### SD Maid
Version: `5.3.11 (50311)`

### Device
Fingerprint: `HUAWEI/PPAH-L02/HWPPA-H:10/HUAWEIPPA-LX2/10.1.1.218C185:user/release-keys`

**Comment by Csarica** [comment]
> @d4rken
