### ISSUE TITLE
Doesn't work on Android 12, MIUI 13

### ISSUE THREAD

**Issue by xiaomiui69** [d4rken/sdmaid-public#5314]
**Describe the bug**
App Cleaner stuck when cleaning. 

**To Reproduce**
1. Scan in QuickAccess Tab
2. Click App Cleaner
3. Tap trash icon
4. Stuck

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi Note 10 Pro]
 - OS: [e.g. Android 12]

**Additional context**

**Comment by d4rken** [comment]
Please provide a debug log and more details.
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by d4rken** [comment]
An unrelated user send in a debug log, SD Maid used AOSP matching instead of trying MIUI V12 matching, while it's not guaranteed that that will work with V13, it will be tried now.

**Comment by xiaomiui69** [comment]
It's fixed. Thanks!
