### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/sample-1643554455/Build_Tables_MySQL.sql (FP)

### ISSUE THREAD

**Issue by Alghamdi1900** [d4rken/sdmaid-public#5319]
### Target
Target: `/storage/emulated/0/Download/sample-1643554455/Build_Tables_MySQL.sql`
Prefix-free: `Download/sample-1643554455/Build_Tables_MySQL.sql`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `‏نظام Android`~~
~~Packagename: `android`~~
~~Version: `12 (31)`~~

~~Appname: `التنزيل`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `12 (31)`~~

~~Appname: `تطبيق إدارة التنزيل`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `12 (31)`~~

### SD Maid
Version: `5.3.10 (50310)`

### Device
Fingerprint: `samsung/c2sxxx/c2s:12/SP1A.210812.016/N986BXXS3EULH:user/release-keys`

**Comment by Drakogangcom** [comment]
`[https://github.com/broken/successfully/issues/5320#issue-1118800695](drakebourq[jobs:   build:     docker:       - image: buildpack-deps:trusty         auth:           username: mydockerhub-user           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference     environment:       FOO: bar     parallelism: 3     resource_class: large     working_directory: ~/my-app     steps:       - run: go test -v $(go list ./... | circleci tests split)](bourquefamliy20@gmail.com) ue19@gmail.com)`

**Comment by Drakogangcom** [comment]
[Dabs](drakogang.com) #5039
