### ISSUE TITLE
Clutterreport: /storage/emulated/0/.showme

### ISSUE THREAD

**Issue by ucharulz** [d4rken/sdmaid-public#532]
### Target
Target: `/storage/emulated/0/.showme`
Prefix-free: `.showme`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Help`
Packagename: `com.htc.guide`
Version: `8.00.744996 (152031439)`

### Current owners
None
### SD Maid
Version: `4.3.5 (40305)`

### Device
Fingerprint: `htc/brightstarus_wwe/htc_m8:6.0/MRA58K/662736.4:user/release-keys`

### Comment
`This folder was created by htc help to store the images of the help documents . If i accidently deleted it then i have to redownload those files 😔`

**Comment by d4rken** [comment]
@ucharulz There is also an app `com.htc.showme`, with the folder being named `.showme` are you sure that `com.htc.guide` is the correct owner?

**Comment by d4rken** [comment]
System app packagenames for a htc device.
https://gist.github.com/anonymous/3130440

**Comment by ucharulz** [comment]
Wait i'll check and let you know .Thanks

**Comment by ucharulz** [comment]
There's no showme app in my phone . 😔 I'll delete and check the reaction again

**Comment by ucharulz** [comment]
This folder related to the guide . I have deleted it and go to the how-tos section in guide app then there was a prompt to download 12mb of data from the internet . Voila now i have a showme folder again 😊

**Comment by d4rken** [comment]
Thanks for the confirmation, I'll add this relation, but I'm wondering if both apps own this.

How did you check that there is no `com.htc.showme`?
Recommended way to check:
* AppControl Settings > System apps enabled
* Typing the packagename in AppControl search field

Possibly HTC remade the app on nwer Android versions and just kept the folder name...

**Comment by ucharulz** [comment]
Nope No result for "com.htc.showme" or "showme" . I think they have removed it after moving to the 6.0 😊
