### ISSUE TITLE
Bug: Files manager can't access all files in /data/data..Android 12+Root access.

### ISSUE THREAD

**Issue by FXCROG** [d4rken/sdmaid-public#5326]
### What happened?
Files Manager can only access GMS and SD Maid folders in /data/data.I think it is related to Android 12 changes.

### What did you expect to happen?
Files Manager can access all files in /data/data. Android 12 + Root access.

### How can I reproduce the issue?
Android 12 + Root access.SD Maid Files Manager.Go to /data/data.You can only see GMS and SD Maid folders.
![Screenshot_20220205-154406_SD Maid](https://user-images.githubusercontent.com/93569720/152633482-3449a5de-d3d3-4c73-b498-2d17ee80b8fd.png)

### SD Maid
Version: `5.3.11 (50311)`
Pro: `isPro=true || isComplete=false (unl=true, iap=null, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `google/redfin/redfin:12/SQ1A.220105.002/7961164:user/release-keys`

**Comment by d4rken** [comment]
That's normal. On Android 11+ the storage layout has changed to increase privacy/security (:shrug:). Apps can only see themselves in `/data/data` (with a few exceptions). `/data/data` is now a modified perspective of `/data_mirror`.

You should find all apps in `/data_mirror/data_ce/`.

**Comment by FXCROG** [comment]
> That's normal. On Android 11+ the storage layout has changed to increase privacy/security (🤷). Apps can only see themselves in `/data/data` (with a few exceptions). `/data/data` is now a modified perspective of `/data_mirror`.
> 
> You should find all apps in `/data_mirror/data_ce/`.

I went to /data_mirror/data_ce/null/0.Problem solved.Thanks.
