### ISSUE TITLE
Most of /data/data/ is invisible

### ISSUE THREAD

**Issue by Nemris** [d4rken/sdmaid-public#5331]
**Describe the bug**
When using the Explorer, there are only two directories visible inside `/data/data/`: `com.google.android.gms` and `eu.thedarken.sdm`.
This extends to custom SystemCleaner filters that operate on apps' private data, making them unusable.

**To Reproduce**
1. Open Explorer from the side bar.
2. Move to `/data/data/`.
3. Observe that apps' private data is not shown, save for GMS and SDM.

**Expected behavior**
The apps' private data should be visible inside `/data/data/`, as they are under other root-capable file managers.
Additionally, custom SystemCleaner filters that operate on apps' private data should work, provided their logic is sound.

**Screenshots**
![Screenshot_20220207-131550_SD Maid](https://user-images.githubusercontent.com/16035414/152787460-626126e9-c36a-4806-94d2-1493ae063f43.png)

**Debug log**
[sdmaid_logfile_1644235976590.txt.zip](https://github.com/d4rken/sdmaid-public/files/8015148/sdmaid_logfile_1644235976590.txt.zip)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A40 (SM-A405FN)
 - OS: Android 11 (One UI 3.1)

**Comment by d4rken** [comment]
On Android 11+ the content of `/data/data` is filtered for security/privacy, the actual content can be found under `/data_mirror`, but you are right, with the SystemCleaner filters it can be annoying, I'll look into a workaround.

**Comment by Nemris** [comment]
I can confirm that both `/data_mirror/data_ce/null/0/` and `/data_mirror/data_de/null/0/` appear to show app data, yes.

The interesting question is - why do apps such as (the closed-source) Total Commander and (the open-source) Termux appear to show `/data/data/` just fine with root privileges? Maybe it'll be useful for your workaround.
