### ISSUE TITLE
Malfunctioning Accessibility Service

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/sdmaid-public#5335]
Good day,

The AppCleaner function often fails to clean app cache and this is what is seen under Settings:

[Screenshot_20220208-182239](https://user-images.githubusercontent.com/54448474/152992200-6303e82d-6ebd-40dd-a4a8-b036dd4ecf33.jpg)

[Screenshot_20220208-182256](https://user-images.githubusercontent.com/54448474/152992226-23ea7390-fdc9-4a80-9455-0240a1a466ea.jpg)

Switching off the permission and switching it ON again seem to help. But this keeps happening repeatedly.

I'm using OnePlus 8T running on OOS 11.0.11.11.

**Comment by d4rken** [comment]
This is mostly a ROM issue and not something I can fix, as far as I know.

Here are some tricks:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting

Often it's related to overly restrictive system settings regarding permissions or battery optimizations.
