### ISSUE TITLE
Possible bug running under lineageOS

### ISSUE THREAD

**Issue by TJMcK** [d4rken/sdmaid-public#5339]
I'm not sure if this app is responsible for my current problem, but it is the only app that I have installed that could influence the LineageOS updater. (Whenever I click install the new version of LineageOS, the updater crashes). 

There may be certain settings available to solve this problem, but I'm not aware of them.

I would uninstall and try updating without the SD Maid, but I have purchased the pro version and don't want to have to pay again.

**Comment by d4rken** [comment]
> I'm not sure if this app is responsible for my current problem, but it is the only app that I have installed that could influence the LineageOS updater. (Whenever I click install the new version of LineageOS, the updater crashes).

Your first step should be to try to get the stack trace of the updater crash via `logcat`. If you share that I might be able to tell you if it could be related to SD Maid.

> I would uninstall and try updating without the SD Maid, but I have purchased the pro version and don't want to have to pay again.

The purchase is not lost on uninstall, it's tied to your email. Why do you think you would lose it?
