### ISSUE TITLE
Bug: SystemCleaner Scan Unusably Slow on SM-T290 Running Android 11

### ISSUE THREAD

**Issue by Oeconomist** [d4rken/sdmaid-public#5341]
### What happened?
SystemCleaner scan is unusably slow on an SM-T290 (Samsung Galaxy Tab A 8.0" 2019) running Android 11.

### What did you expect to happen?
Same swift performance as on other devices and on tablet before update to Android 11.

### How can I reproduce the issue?
Use SystemCleaner on SM-T290 running Android 11.

### SD Maid
Version: `5.3.12 (50312)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/gtowifixx/gtowifi:11/RP1A.200720.012/T290XXU3CUK4:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debuglog of the scan:

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
