### ISSUE TITLE
Deletion of Old Whatsapp backup files

### ISSUE THREAD

**Issue by deblood3** [d4rken/sdmaid-public#5342]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android 10]

**Additional context**

Still having issues with deletion of old Whatsapp backup files with extension of db.crypt15 when l ran appcleaner

I have been manually deleting the old backups when l ran appcleaner. 

Just checking if you are still aware and when a fix will be in.

Thanks
Alfred

**Comment by d4rken** [comment]
Please don't create new tickets for existing issues.

I've not found time to look into it, I hope to have some time on the weekend.

Dup of #5185

**Comment by deblood3** [comment]
I am having difficulty in attaching the log files(s) to the ticket in
GitHub, with either the compressed file or extracted file.

I selected the attached icon, but both files are greyed out when l try to
select either of the files.

So decided to send compressed file directly to you via email


Alfred Yeboah
