### ISSUE TITLE
Pls add deleting WeChat xlog files - these not only take up several GB of space but might be even spy files for China 

### ISSUE THREAD

**Issue by COUPON4Vitamins** [d4rken/sdmaid-public#5353]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by COUPON4Vitamins** [comment]
I use Wechat slot for work so cannot get rid of it.

**Comment by COUPON4Vitamins** [comment]
I created a filter myself to delete these pesky files everyday. But i think it's very important that each Wechat user deletes them !

**Comment by d4rken** [comment]
Please provide more details, especially paths, and example files.
