### ISSUE TITLE
Clutterreport: /storage/B6F8-1904/backups

### ISSUE THREAD

**Issue by ArthoRoys** [d4rken/sdmaid-public#536]
### Target
Target: `/storage/B6F8-1904/backups`
Prefix-free: `backups`
Path-prefix: `/storage/B6F8-1904/`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `ES File Explorer`
Packagename: `com.estrongs.android.pop`
Version: `4.1.3.1 (536)`

### Current owners
None
### SD Maid
Version: `4.3.0 (40300)`

### Device
Fingerprint: `samsung/ms013gxx/ms013g:4.4.2/KOT49H/G7102XXUBOB1:user/release-keys`

**Comment by d4rken** [comment]
What function in ES Explorer creates this?

**Comment by david082321** [comment]
@d4rken 
backup apk
https://github.com/d4rken/sdmaid-public/issues/555
