### ISSUE TITLE
Bug: Accessibility service stops working frequently

### ISSUE THREAD

**Issue by androidfreak** [d4rken/sdmaid-public#5360]
### What happened?
Accessibility service stops working frequently and requires a reboot of the device every few hours.

### What did you expect to happen?
The appcleaner module doesn't clean all apps

### How can I reproduce the issue?
This happens frequently and I don't know how to reproduce

### SD Maid
Version: `5.3.14 (50314)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `POCO/karna_in/karna:11/RKQ1.200826.002/V12.5.4.0.RJGINXM:user/release-keys`

**Comment by d4rken** [comment]
Check:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting

Maybe related to #5272 ?
