### ISSUE TITLE
Checksum window pops up every time SD Maid expands

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#5378]
### What happened?
Если вычислить контрольные суммы и нажать на другое место экрана, чтобы окно с контрольным суммами закрылось, то после сворачивания и разворачивания SD maid окно каждый раз опять появляется.

                                  
### SD Maid
Version: `5.3.10 (50310)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.14.0.QCDRUXM:user/release-keys`

**Comment by d4rken** [comment]
Similar issue as #4154

A bit difficult to fix due to SD Maids old code base, but #5378 and #4154 should be fixed now.
