### ISSUE TITLE
Bug: SD Maid Looping

### ISSUE THREAD

**Issue by NAVI1237** [d4rken/sdmaid-public#5389]
### What happened?
SD Maid is looping when using accesibility

### What did you expect to happen?
Clear the cache of Applications using the accessibility option

### How can I reproduce the issue?
Using accessibility option for cleaning cache

### Comments
I have a OPPO A53 (CPH2127) 
### SD Maid
Version: `5.3.15 (50315)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OPPO/CPH2127/OP4EFDL1:11/RKQ1.201217.002/1636604258585:user/release-keys`

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log
