### ISSUE TITLE
Clutterreport: /storage/emulated/0/.fileManager (FP)

### ISSUE THREAD

**Issue by cme813** [d4rken/sdmaid-public#5392]
### Target
Target: `/storage/emulated/0/.fileManager`
Prefix-free: `.fileManager`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `ANT HAL Service`
Packagename: `com.dsi.ant.server`
Version: `5.0.0_hidl_1 (50000)`

Appname: `3 Button Navigation Bar`
Packagename: `com.android.internal.systemui.navbar.threebutton`
Version: `1.0 (1)`

Appname: `Adreno Graphics Drivers`
Packagename: `com.qualcomm.qti.gpudrivers.lito.api30`
Version: `0.1.0 (4096)`

Appname: `Android Services Library`
Packagename: `com.google.android.ext.services`
Version: `aml_ext_311313000 (311313000)`

### Current owners
Appname: `File Manager`
Packagename: `com.oneplus.filemanager`
Version: `2.6.4.1.210721121901.e308cc0 (320200613)`

### SD Maid
Version: `5.3.14 (50314)`

### Device
Fingerprint: `OnePlus/OnePlusN10METRO/OnePlusN10METRO:11/RKQ1.201217.002/2201111735:user/release-keys`

### Comment
`eval
exec`

**Comment by dragonGod97677** [comment]
Those suggested owners are wrong
