### ISSUE TITLE
Add a option to turn off statistics limit

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#5393]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want a option to completely turn off sd maid statistics limit.

**Describe alternatives you've considered**
None

**Additional context**
Also disable auto statistics resetting when opening settings>statistics 
![Screenshot_2022-03-12-11-02-39-55](https://user-images.githubusercontent.com/38875906/158001281-a844e66d-c205-46ef-b500-c079a76d59e5.png)

**Comment by d4rken** [comment]
> Also disable auto statistics resetting when opening settings>statistics

What do you mean by that?

**Comment by dragonGod97677** [comment]
> > Also disable auto statistics resetting when opening settings>statistics
> 
> What do you mean by that?

When i open settings>statistics there's a popup notification that statistics were resetting and when i check the statistics, it was indeed reseted

**Comment by d4rken** [comment]
The UI default was "3", the code default was "21" days, that's why truncation was triggered when the screen is entered. It does not delete all data, just enough to match the current limit (21).

I've increased the maximum days to 365.
