### ISSUE TITLE
Bug: Phone compromised or mirrored

### ISSUE THREAD

**Issue by Barelybagel1281** [d4rken/sdmaid-public#5394]
### What happened?
Something with emails and passwords being compromised 

### What did you expect to happen?
Give to authorities for prosecution 

### How can I reproduce the issue?
Just download feedback and it should help

### Comments
Please
### SD Maid
Version: `5.3.15 (50315)`
Pro: `isPro=false || isComplete=true (unl=false, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/y2qsqw/y2q:12/SP1A.210812.016/G986USQS2EVB3:user/release-keys`

**Comment by d4rken** [comment]
This is not the 🚨🚓

**Comment by Barelybagel1281** [comment]
I know that just wanted insight.
