### ISSUE TITLE
UI: Show/Hide tabs & Quick Access

### ISSUE THREAD

**Issue by NeoBeum** [d4rken/sdmaid-public#540]
Tools that are Unchecked in SETTINGS>GENERAL SETTINGS>SHOW/HIDE TABS, but Checked in SETTINGS>QUICK ACCESS, will prevent display of scan results/detailed results for the tool visible on the launch page of Quick Access at start up.

**Comment by d4rken** [comment]
What behavior would you expect in this case?

**Comment by NeoBeum** [comment]
Ah. Ok, was the show hide tabs intended to completely disable the specific tool?

I was expecting it to just hide the tool from the slide out menu, so that certain tools can be hidden from the slide out menu, but be visible and able to be viewed if enabled through Quick Access

**Comment by d4rken** [comment]
No real intentions, I overlooked your use case completely until now.
I'll look into what it takes to open the page even if it is hidden.

**Comment by NeoBeum** [comment]
That's great, thanks.

It'll turn Quick Access, in to a really, quick access - where you can access a tool, to do quick cleanups, without it cluttering the slide out menu. That's what I was thinking Quick Access was there for.
