### ISSUE TITLE
Clutterreport: /storage/emulated/0/MIUI/Gallery/cloud/.trashBin (FP)

### ISSUE THREAD

**Issue by Avamander** [d4rken/sdmaid-public#5400]
### Target
Target: `/storage/emulated/0/MIUI/Gallery/cloud/.trashBin`
Prefix-free: `MIUI/Gallery/cloud/.trashBin`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Gallery`
Packagename: `com.miui.gallery`
Version: `3.3.3.8-global (399464)`

### SD Maid
Version: `5.3.15 (50315)`

### Device
Fingerprint: (Request URI too long, truncated) Xiaomi Mi 9

**Comment by jirayupiwon8** [comment]
> ### Target
> Target: `/storage/emulated/0/MIUI/Gallery/cloud/.trashBin` Prefix-free: `MIUI/Gallery/cloud/.trashBin` Path-prefix: `/storage/emulated/0/` Type: `DIRECTORY` Location: `SDCARD` Current keeper state: `true` Suggested keeper state: `false`
> 
> ### Suggested owners
> Appname: `Gallery` Packagename: `com.miui.gallery` Version: `3.3.3.8-global (399464)`
> 
> ### SD Maid
> Version: `5.3.15 (50315)`
> 
> ### Device
> Fingerprint: (Request URI too long, truncated) Xiaomi Mi 9

**Comment by d4rken** [comment]
This should already be covered by the AppCleaner Recycle/Trashbin Filter, is that not working?

**Comment by Dmdcj** [comment]
![Screenshot_2024-08-05-21-51-22-072_com android htmlviewer](https://github.com/user-attachments/assets/f92ea9c6-a7d9-4978-8867-7a2f195b7624)
