### ISSUE TITLE
Appcleaner not working properly after update huawei Emui 12

### ISSUE THREAD

**Issue by thafseefnp** [d4rken/sdmaid-public#5401]
Dear SD Made Developers,

Find the attached screen recorder for your reference. I have updated my device fromhuawei nova 7i EMUI 10.1 to EMUI 12. this is latest version of the updates. after update i have been facing the issues of running AppCleaner Feature from the app.
kindly fix this problem and thankyou for your wonderful app forever.

**Comment by d4rken** [comment]
I don't see a screen recording, but preferably, provide a debulog of the issue:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by thafseefnp** [comment]
i have uploaded this screen recorder in the drive. 
this is the link for your reference.

https://drive.google.com/file/d/1_CQ0Wi6MHGz64EmDuX51eO2ajyG68pAT/view?usp=drivesdk

> I don't see a screen recording, but preferably, provide a debulog of the issue: https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by thafseefnp** [comment]
#

https://user-images.githubusercontent.com/101526003/158325309-7a75ba65-da57-4d7c-bba0-9c5ec7a3ca2d.mp4

**Comment by thafseefnp** [comment]
> I don't see a screen recording, but preferably, provide a debulog of the issue: https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

i have just uploaded here

**Comment by thafseefnp** [comment]
[sdmaid_logfile_1647328841349.txt.zip](https://github.com/d4rken/sdmaid-public/files/8251036/sdmaid_logfile_1647328841349.txt.zip)

**Comment by adrawdet** [comment]
Encountering the same issue on the pixel 6 running 12.1

**Comment by d4rken** [comment]
Hm SD Maid seems too fast here, I think we have to wait for "Computing..." to be done.

I have a pattern called "node recovery" which currently just scrolls the screen, I think we could check for ellipsis characters and if found add a short delay, then recheck the screen.

**Comment by d4rken** [comment]
Please report back after the next update
