### ISSUE TITLE
Schedule and processing

### ISSUE THREAD

**Issue by Panas1989** [d4rken/sdmaid-public#5404]
**Describe the bug**
Scheduling and cleaning cleaning all the time processing and does not clean the device

**To Reproduce**

**Expected behavior**
The schedule is not working properly it's time to clean all the time processing and nothing happens

**Screenshots**
![Screenshot_2022-03-14-10-16-59-239_eu thedarken sdm](https://user-images.githubusercontent.com/100944730/158132032-2f73324e-adae-4751-9660-38c99e8b67c0.jpg)

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: Redmi note 10 pro
 - OS: [e.g. Android 12

**Additional context**
Add any other context about the problem here
![Screenshot_2022-03-14-10-16-59-239_eu thedarken sdm](https://user-images.githubusercontent.com/100944730/158131865-fc4e552f-7104-4a85-882c-0b6f926a37ab.jpg)
.

**Comment by d4rken** [comment]
Please provide a debug log.
Note that the system may delay execution for a few minutes in some cases.
Press the play button in the toolbar, if it works then everything is likely okay.

**Comment by Panas1989** [comment]
[sdmaid_logfile_1647279386307.txt.zip](https://github.com/d4rken/sdmaid-public/files/8247271/sdmaid_logfile_1647279386307.txt.zip)

**Comment by Panas1989** [comment]
Hey!  The problem did not disappear all the time processing the whole day and nothing happens.
[sdmaid_logfile_1647421273751.txt.zip](https://github.com/d4rken/sdmaid-public/files/8260420/sdmaid_logfile_1647421273751.txt.zip)
