### ISSUE TITLE
AppCleaner stuck on Settings page 

### ISSUE THREAD

**Issue by dasMichal** [d4rken/sdmaid-public#5405]
**Describe the bug**
AppCleaner using accessibility mode is stuck on the settings page of the apps to clean. It flashes and then restarts the setting page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to AppCleaner
2. Click on Scan
3. Wait for Scan to finish
4. Click on Delete.

**Expected behaviour**
Expected to have SD Maid go through the List of apps to clean and use the accessibility feature to clean the cache of the app.

**Screenshots**

https://user-images.githubusercontent.com/57588949/158490098-cb699304-6f78-4f1d-a325-44c930b8ab7c.mp4

**Debug log**
[sdmaid_logfile_1647386577295.txt](https://github.com/d4rken/sdmaid-public/files/8257891/sdmaid_logfile_1647386577295.txt)

**Smartphone (please complete the following information):**
- Device: Pixel 3a
- OS: Android 12, March security update

**Additional context**
Maybe it's an Android thing too, can't delete the cache of some apps even by hand.

**Comment by dasMichal** [comment]
Just a heads-up, the fix described here https://github.com/d4rken/sdmaid-public/issues/5272#issuecomment-1046322459 fixed it for me.

Should I attach another debug log?

**Comment by d4rken** [comment]
I think we can close this in favour of #5272. An extra debug log would only be needed if you think it's not related to Google's last security update. If so, just reopen this.
