### ISSUE TITLE
Bug: AppCleaner stuck

### ISSUE THREAD

**Issue by SerGutsalyuk** [d4rken/sdmaid-public#5406]
### What happened?
AppCleaner stuck on Settings page

### What did you expect to happen?
Just  started clearing from the menu

### How can I reproduce the issue?
System language - Ukrainian / Go to AppCleaner / Click on scan/ Click on delete.

### Comments
the application cleaner does not work, it hangs on each of the applications with the next skip due to the impossibility of cleaning when the system language is Ukrainian (when the system language is Russian - EVERYTHING WORKS).
### SD Maid
Version: `5.3.15 (50315)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/beyond0qltezh/beyond0q:12/SP1A.210812.016/G9700ZHU6GVB1:user/release-keys`

**Comment by SerGutsalyuk** [comment]
https://user-images.githubusercontent.com/5267918/158603343-d4e21166-94d6-4227-bab0-8ef17d420028.mp4

System language is Ukrainian

**Comment by SerGutsalyuk** [comment]
https://user-images.githubusercontent.com/5267918/158603821-71dc834e-589b-445f-8b62-3cd64096e4c3.mp4


System language is Russian.
It's Work..

**Comment by Panas1989** [comment]
Hi! I had such a problem when I updated the device to Android 12 miui 13, then it was fixed in version sd maid 5.3.15, but another problem appeared - the scheduler is constantly processing and nothing happens all the time processing and nothing!

**Comment by SerGutsalyuk** [comment]
> SD Maid is likely missing the right labels for Ukrainian, if you can provide me with a debug log of this, it should be an easy fix for me.
> 
> See: https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log


[sdmaid_logfile_1647441596189.txt.zip](https://github.com/d4rken/sdmaid-public/files/8263846/sdmaid_logfile_1647441596189.txt.zip)
`

**Comment by d4rken** [comment]
Fixed in next update
