### ISSUE TITLE
Scheduling and cleaning cleaning all the time processing and does not clean the device

### ISSUE THREAD

**Issue by Panas1989** [d4rken/sdmaid-public#5407]
**Describe the bug**
Scheduling and cleaning cleaning all the time processing and does not clean the device

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug log**
Record a [debug log]
[sdmaid_logfile_1647421273751.txt.zip](https://github.com/d4rken/sdmaid-public/files/8267077/sdmaid_logfile_1647421273751.txt.zip)
[sdmaid_logfile_1647452540439.txt.zip](https://github.com/d4rken/sdmaid-public/files/8267079/sdmaid_logfile_1647452540439.txt.zip)

**Smartphone (please complete the following information):**
 - Device: Redmi note 10 pro
 - OS: [e.g. Android 12

**Additional context**

https://user-images.githubusercontent.com/100944730/158696288-bb79fcbd-3fdb-4bbf-9d6b-d0573f7d9d84.mp4

**Comment by aseeily25** [comment]
#[
Duplicate of #
زءزؤ
](url)
