### ISSUE TITLE
Bug: Deleted my private files.

### ISSUE THREAD

**Issue by Mohnish1702** [d4rken/sdmaid-public#5408]
### What happened?
I made some files private from my MI file manager but since I ran this app it deleted all of them.

### What did you expect to happen?
It shouldn't have deleted my private files.

### How can I reproduce the issue?
Make some files private from MI phone file manager and scan via this app and run the deletion process.

### SD Maid
Version: `5.3.15 (50315)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Xiaomi/umi_in/umi:11/RKQ1.200826.002/V12.5.4.0.RJBINXM:user/release-keys`

**Comment by d4rken** [comment]
What was the path of these files and which tool deleted them?

Also see
Recovery:
https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#recover-deleted-files

Exclusions:
https://github.com/d4rken/sdmaid-public/wiki/Exclusions

**Comment by dragonGod97677** [comment]
@Mohnish1702 Can you open statistics and tap

![Screenshot_2022-03-25-00-40-36-55](https://user-images.githubusercontent.com/38875906/159966676-0b7d61af-5810-41cb-8276-31ee37040e48.png)
The i icon next were when the deletion happened


and then screenshot it like this BUT screenshot ONLY WHERE you can see anything that relates only to Mi File Manager
![Screenshot_2022-03-25-00-44-02-44](https://user-images.githubusercontent.com/38875906/159967335-1e0b552c-98a8-44ff-a78a-9a55f6f6f5ff.png)


And send it here so darken may see what folder to be added to default exclusions.
Then also, for the time being, you will see what folder to be added on exclusion manually
