### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.android.providers.media/thumbnail_cache/thumbnail.db (FP)

### ISSUE THREAD

**Issue by Ahmedvedo** [d4rken/sdmaid-public#5417]
### Target
Target: `/storage/emulated/0/Android/data/com.android.providers.media/thumbnail_cache/thumbnail.db`
Prefix-free: `com.android.providers.media/thumbnail_cache/thumbnail.db`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Backup`
Packagename: `com.huawei.KoBackup`
Version: `10.1.1.700 (210101700)`

Appname: `Android Setup`
Packagename: `com.google.android.apps.restore`
Version: `1.0.276093695 (8558)`

Appname: `Android system`
Packagename: `android`
Version: `9 (28)`

### Current owners
Appname: `Media Storage`
Packagename: `com.android.providers.media`
Version: `9 (906)`

### SD Maid
Version: `5.3.15 (50315)`

### Device
Fingerprint: `HUAWEI/INE-LX1r/HWINE:9/HUAWEIINE-LX1r/9.1.0.319C185:user/release-keys`

**Comment by dragonGod97677** [comment]
Suggested owners is wrong

That file is Owned by Media Storage Only because the file is in Media Storage's public directory
