### ISSUE TITLE
Bug: Fix AppCleaner speed 

### ISSUE THREAD

**Issue by ypdlng** [d4rken/sdmaid-public#5418]
### What happened?
Used to take 3-5 seconds per app, now 10x slower, refreshing each page a good 5-10 times before it moves along

### What did you expect to happen?
Moves from one app detail page to the next instantaneously

### How can I reproduce the issue?
Try it on Google Pixel 3A or 4A, not sure if specific to device but it's happening on both of mine

### Comments
Please fix! I used this feature more than once weekly but now I avoid it because it renders my phone untouchable for 15min while AppCleaner is slowly running
### SD Maid
Version: `5.3.15 (50315)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `google/sargo/sargo:12/SP2A.220305.012/8177914:user/release-keys`

**Comment by d4rken** [comment]
Same issue as #5272 afaict.
