### ISSUE TITLE
Reports are not sent through the MIUI browser

### ISSUE THREAD

**Issue by Ingood5** [d4rken/sdmaid-public#5419]
### What happened?
Отправил отчёт по папке, из предложенных браузеров выбрал MIUI, в нем вместо сайта GitHub открылась главная страница браузера. Повторяется каждый раз.

### What did you expect to happen?
Должен был открыться сайт GitHub с заполненной формой для отправки отчёта

### How can I reproduce the issue?
В SD maid отправить отчёт по папке. Когда смартфон предложит выбрать браузер - выбрать браузер MIUI

### SD Maid
Version: `5.3.15 (50315)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Redmi/dandelion_ru/dandelion:10/QP1A.190711.020/V12.0.14.0.QCDRUXM:user/release-keys`

[sdmaid_logfile_1648379717777.txt.zip](https://github.com/d4rken/sdmaid-public/files/8357462/sdmaid_logfile_1648379717777.txt.zip)

**Comment by d4rken** [comment]
Do other browsers work?

The issue data is passed via url parameters.

Can you open this link in the MIUI browser?

https://github.com/d4rken/sdmaid-public/issues/new?title=Clutterreport%3A%20%2Fstorage%2Femulated%2F0%2Fboot.img%20(new)&body=%23%23%23%20Target%0ATarget%3A%20%60%2Fstorage%2Femulated%2F0%2Fboot.img%60%0APrefix-free%3A%20%60boot.img%60%0APath-prefix%3A%20%60%2Fstorage%2Femulated%2F0%2F%60%0AType%3A%20%60FILE%60%0ALocation%3A%20%60SDCARD%60%0ACurrent%20keeper%20state%3A%20%60false%60%0ASuggested%20keeper%20state%3A%20%60false%60%0A%0A%23%23%23%20Suggested%20owners%0AAppname%3A%20%60ADS-B%20Companion%60%0APackagename%3A%20%60eu.darken.adsbc%60%0AVersion%3A%20%600.0.1%20(100)%60%0A%0A%23%23%23%20Current%20owners%0ANone%0A%0A%23%23%23%20SD%20Maid%0AVersion%3A%20%605.3.16%20(50316)%60%0A%0A%23%23%23%20Device%0AFingerprint%3A%20%60google%2Fwalleye%2Fwalleye%3A10%2FQQ3A.200805.001%2F6578210%3Auser%2Frelease-keys%60%0A%0A

**Comment by d4rken** [comment]
From your bugreport, this is the link:

https://github.com/d4rken/sdmaid-public/issues/new?title=Clutterreport%3A%20%2Fstorage%2Femulated%2F0%2Fdata%20(new)&body=%23%23%23%20Target%0ATarget%3A%20%60%2Fstorage%2Femulated%2F0%2Fdata%60%0APrefix-free%3A%20%60data%60%0APath-prefix%3A%20%60%2Fstorage%2Femulated%2F0%2F%60%0AType%3A%20%60DIRECTORY%60%0ALocation%3A%20%60SDCARD%60%0ACurrent%20keeper%20state%3A%20%60false%60%0ASuggested%20keeper%20state%3A%20%60false%60%0A%0A%23%23%23%20Suggested%20owners%0AAppname%3A%20%603%20Button%20Navigation%20Bar%60%0APackagename%3A%20%60com.android.internal.systemui.navbar.threebutton%60%0AVersion%3A%20%601.0%20(1)%60%0A%0A%23%23%23%20Current%20owners%0ANone%0A%0A%23%23%23%20SD%20Maid%0AVersion%3A%20%605.3.15%20(50315)%60%0A%0A%23%23%23%20Device%0AFingerprint%3A%20%60Redmi%2Fdandelion_ru%2Fdandelion%3A10%2FQP1A.190711.020%2FV12.0.14.0.QCDRUXM%3Auser%2Frelease-keys%60%0A%0A%23%23%23%20Comment%0A%60hello%20hello%20hello%20hello%60%0A

**Comment by Ingood5** [comment]
Обе ссылки в браузере MIUI успешно открываются

**Comment by d4rken** [comment]
I think this is a bug in the MIUI browser and not much I can do from my end :frowning:
