### ISSUE TITLE
Clutterreport: /storage/1F4E-2416/eBooks

### ISSUE THREAD

**Issue by jaswinder77** [d4rken/sdmaid-public#5435]
### Target
Target: `/storage/1F4E-2416/eBooks`
Prefix-free: `eBooks`
Path-prefix: `/storage/1F4E-2416/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.android.aldiko`
Version: ` (-1)`

Appname: `?`
Packagename: `org.coolreader.donation.silver`
Version: ` (-1)`

Appname: `?`
Packagename: `org.coolreader.newui`
Version: ` (-1)`

Appname: `?`
Packagename: `org.coolreader`
Version: ` (-1)`

Appname: `?`
Packagename: `org.coolreader.donation.bronze`
Version: ` (-1)`

Appname: `?`
Packagename: `com.aldiko.android`
Version: ` (-1)`

Appname: `?`
Packagename: `com.adobe.digitaleditions`
Version: ` (-1)`

### SD Maid
Version: `5.3.15 (50315)`

### Device
Fingerprint: `motorola/blackjack/blackjack:10/QODS30.163-7-27/f57bc:user/release-keys`

### Comment
`I had downloaded these ebooks and audiobooks myself.`

**Comment by d4rken** [comment]
Then there is nothing to be done
