### ISSUE TITLE
AppCleaner don't delete the cache apps

### ISSUE THREAD

**Issue by SalvatoreAranzulla** [d4rken/sdmaid-public#5436]
**Describe the bug**
I go to quick access, to do a cleaning, after finishing the scan.  I click on the red button and when it gets to the point that it needs to clear the cache, it stops 20/30 seconds and switches to another app, without clearing the cache of the previous app

**To Reproduce**
1. Go to quick access
2. Click on scan and after red button
3.  Wait the AppCleaner

**Screenshots**
![Screenshot_2022-03-31-12-27-00-71_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/98517992/161035816-b445551e-d2b8-4723-9025-3a1d64408e53.jpg)
![Screenshot_2022-03-31-12-27-04-87_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/98517992/161035824-d3845d60-dbfd-4f31-8f3f-1f113663c3ef.jpg)
![Screenshot_2022-03-31-12-27-44-85_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/98517992/161035835-d5cff64e-192f-4c55-ba71-4f737070318b.jpg)

**Debug log**
how?

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 12

**Comment by d4rken** [comment]
Please provide a debug log of this
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by fededroid93** [comment]
I have the same problem on OnePlus 8T after the update to A12. I attached the debug log. Thank you 

[sdmaid_logfile_1651393443022.txt](https://github.com/d4rken/sdmaid-public/files/8598524/sdmaid_logfile_1651393443022.txt)

**Comment by d4rken** [comment]
I think these issues are fixed. If not, please open a new ticket with a new log with the latest version.
