### ISSUE TITLE
AppCleaner doesnt work correctly in A12 traditional Chinese

### ISSUE THREAD

**Issue by Iplayolg** [d4rken/sdmaid-public#5438]
**Describe the bug**
In android 12 traditional Chinese without root, AppCleaner cant tap the correct label to clean cache. It should tap 儲存空間和快取（Storage & cache）then 
清除快取（Clear cache）

**To Reproduce**
1. Go to AppCleaner
2. Click on the green circle arrow icon to scan
3. Click on the red recycle bin icon to clean cache
4. See error, sdmaid try to find right label to work but failed after 5 times or more on per app, then go to next app

**Expected behavior**
It should tap on the 儲存空間和快取 then the 清除快取

**Screenshots**
![Screenshot_20220404-143328_設定](https://user-images.githubusercontent.com/102944870/161486598-116f8d67-73f9-4d29-97c2-b81241d071db.png)
![Screenshot_20220404-143337_設定](https://user-images.githubusercontent.com/102944870/161486607-4be2f656-b063-4649-8397-bb0317920c94.png)

**Debug log**
[sdmaid_logfile_1649052289757.txt.zip](https://github.com/d4rken/sdmaid-public/files/8407222/sdmaid_logfile_1649052289757.txt.zip)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 4X (mido)
 - OS: Android 12 (LOS aosp)

**Additional context**

**Comment by d4rken** [comment]
I checked the log and SD Maid is already looking for the terms you mentioned, the issue is that SD Maid is not getting any data from the system:

```java
D/ACC:ACCrawler: No valid root-node found: eu.thedarken.sdm.accessibility.core.crawler.CrawlerException: Root node is currently null
```

this is the same error as the Pixel devices are having in #5272 
Did you device get a system update recently?

**Comment by Iplayolg** [comment]
It's a redmi note 4/x custom android 12.1 rom updated recently. The latest
official rom from xiaomi is only android 7.


Matthias Urhahn ***@***.***> 於 2022年4月9日 週六 23:08 寫道：

**Comment by d4rken** [comment]
Please check again with the current v5.3.19

**Comment by Iplayolg** [comment]
I have tried and it works, thanks

Matthias Urhahn ***@***.***> 於 2022年5月2日 週一 02:45 寫道：
