### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/com.whatsapp/msgstore-2021-06-15.1.db.crypt14 (FP)

### ISSUE THREAD

**Issue by lianlianyee** [d4rken/sdmaid-public#5440]
### Target
Target: `/storage/emulated/0/Android/com.whatsapp/msgstore-2021-06-15.1.db.crypt14`
Prefix-free: `Android/com.whatsapp/msgstore-2021-06-15.1.db.crypt14`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `WhatsApp`
Packagename: `com.whatsapp`
Version: `2.22.7.74 (220774004)`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `10 (29)`~~

### SD Maid
Version: `5.3.17 (50317)`

### Device
Fingerprint: `samsung/a9y18qltexx/a9y18qlte:10/QP1A.190711.020/A920FXXS5CUJ1:user/release-keys`

**Comment by d4rken** [comment]
Please provide mehr details, this is not a standard location for WhatsApp data

**Comment by Esssmvcs** [comment]
>
