### ISSUE TITLE
AppCleaner Is Not Clearing Everything

### ISSUE THREAD

**Issue by GrantDR** [d4rken/sdmaid-public#5443]
Device: Samsung Galaxy Note8
Android Version: 9
Rooted or Unrooted? Unrooted
SD Maid Version: v5.3.15
Install ID: ca09ec58-66ba-4445-b9d6-2c87fdda0213

What happened? AppCleaner is not functioning as it used it. It will search my device and tell me that there is > 4GB of data. When I then start AppCleaner, it runs but only removes about ~35MB of data
 then stops. It did not used to do this and would instead clean the full amount. 
What did you expect to happen? I expected AppCleaner to run through the apps it found and clear out data. Instead it stalls and remains at the SD Maid main menu.
What actions did you take? Re-installed the app, but that did not work.
Can you reproduce it, i.e. does this happen everytime? Yes.

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by GrantDR** [comment]
@d4rken Apologies. I didn't see the notification for your earlier comment. I have the debug file. Is it too late to reopen this?

**Comment by d4rken** [comment]
Check the latest beta first, 5.3.20, if it still happens, make a debug log for it.

**Comment by GrantDR** [comment]
Looks like it's fixed in that version. Thank you.
