### ISSUE TITLE
SD Maid not clearing apps (or atleast it's trying to)

### ISSUE THREAD

**Issue by CyjKun** [d4rken/sdmaid-public#5449]
Whenever app cleaner is running it would just try and find where the storage > clear cache section is. 

i've tried using the custom accessibility part where you input the custom path to search but to no avail. (the path is: Storage & cache > Clear cache)

im also attaching the recorded video and log
[sdmaid_logfile_1649513367376.txt.zip](https://github.com/d4rken/sdmaid-public/files/8457119/sdmaid_logfile_1649513367376.txt.zip)

https://user-images.githubusercontent.com/26156549/162578429-a2967405-7f09-45cf-bf60-27dce9936001.mp4

**Comment by d4rken** [comment]
If this is a Pixel device, this might be #5272 ?

**Comment by CyjKun** [comment]
looks like it. i also tried the workaround. works perfectly. thank you
