### ISSUE TITLE
Clutterreport: /storage/extSdCard/Inspeckage (new)

### ISSUE THREAD

**Issue by david082321** [d4rken/sdmaid-public#545]
### Target
Target: `/storage/extSdCard/Inspeckage`
Prefix-free: `Inspeckage`
Path-prefix: `/storage/extSdCard/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Inspeckage`
Packagename: `mobi.acpm.inspeckage`
Version: `2.0 (6)`

### Current owners
None
### SD Maid
Version: `4.3.6 (40306)`

### Device
Fingerprint: `samsung/fortunaltezt/fortunaltezt:4.4.4/KTU84P/G530YZTU1APG1:user/release-keys`

**Comment by d4rken** [comment]
Nice! This helps SD Maid a lot, because all tools make use of the clutter database.
