### ISSUE TITLE
Clutterreport: /storage/E005-AEC3/Android/data/com.folderv.file/cache/meida/thumb.db (FP)

### ISSUE THREAD

**Issue by drone691** [d4rken/sdmaid-public#5470]
### Target
Target: `/storage/E005-AEC3/Android/data/com.folderv.file/cache/meida/thumb.db`
Prefix-free: `com.folderv.file/cache/meida/thumb.db`
Path-prefix: `/storage/E005-AEC3/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `فايل‌ها`
Packagename: `com.huawei.hidisk`
Version: `10.6.1.318 (100601318)`

### Current owners
Appname: `FV File Explorer`
Packagename: `com.folderv.file`
Version: `1.7.5 (410)`

### SD Maid
Version: `5.3.16 (50316)`

### Device
Fingerprint: `HUAWEI/AGR-L09/HWAGR:10/HUAWEIAGR-L09/10.1.0.237C185:user/release-keys`

**Comment by Weerrre** [comment]
čet, 14. tra 2022. 18:39 Matthias Urhahn ***@***.***> je
napisao:
