### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/AB Friends(com.rovio.angrybirdsfriends)-3.3.2(12527)-AngryBirds_2.apk.apk (FP)

### ISSUE THREAD

**Issue by milad55m** [d4rken/sdmaid-public#5473]
> ### Target

Target: `/storage/emulated/0/Download/AB Friends(com.rovio.angrybirdsfriends)-3.3.2(12527)-AngryBirds_2.apk.apk`
Prefix-free: `Download/AB Friends(com.rovio.angrybirdsfriends)-3.3.2(12527)-AngryBirds_2.apk.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `‏سیستم Android`
Packagename: `android`
Version: `5.1-1628758229 (21)`

Appname: `دانلودها`
Packagename: `com.android.providers.downloads.ui`
Version: `5.1-1628758229 (21)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `5.1-1628758229 (21)`

### SD Maid
Version: `5.3.17 (50317)`

### Device
Fingerprint: `alps/full_b906/b906:5.1/LRX21M/1628758229:user/test-keys`

### Comment
`برنامه پاک شده و نصب هم نمیشود`

**Comment by Weerrre** [comment]
pet, 15. tra 2022. 02:02 milad55m ***@***.***> je napisao:
