### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.rovio.baba/no_backup/vungle_cache (FP)

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#5485]
### Target
Target: `/storage/emulated/0/Android/data/com.rovio.baba/no_backup/vungle_cache`
Prefix-free: `com.rovio.baba/no_backup/vungle_cache`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `Angry Birds 2`
Packagename: `com.rovio.baba`
Version: `2.64.0 (25047538)`

### SD Maid
Version: `5.3.18 (50318)`

### Device
Fingerprint: `OPPO/CPH1803/CPH1803:8.1.0/OPM1.171019.026/1595220200:user/release-keys`

### Comment
`this folder contains the ads resources, you know where ads are saved in user's device first and then showing up to user's face. This should be added to AppCleaner.`

**Comment by aburaean199** [comment]
شكرا
