### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/obb/com.higgs.slotsmash/main.3490.com.higgs.slotsmash.obb (FP)

### ISSUE THREAD

**Issue by Ataljkaa** [d4rken/sdmaid-public#5487]
### Target
Target: `/storage/emulated/0/Android/obb/com.higgs.slotsmash/main.3490.com.higgs.slotsmash.obb`
Prefix-free: `com.higgs.slotsmash/main.3490.com.higgs.slotsmash.obb`
Path-prefix: `/storage/emulated/0/Android/obb/`
Type: `FILE`
Location: `PUBLIC_OBB`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Slotsmash™`
Packagename: `com.higgs.slotsmash`
Version: `3.49 (3490)`

### Current owners
Appname: `Slotsmash™`
Packagename: `com.higgs.slotsmash`
Version: `3.49 (3490)`

### SD Maid
Version: `5.3.19 (50319)`

### Device
Fingerprint: `Blackview/A55_EEA/A55:11/RP1A.200720.011/1637317982:user/release-keys`

**Comment by ataljka** [comment]
> ### Target
> Target: `/storage/emulated/0/Android/obb/com.higgs.slotsmash/main.3490.com.higgs.slotsmash.obb` Prefix-free: `com.higgs.slotsmash/main.3490.com.higgs.slotsmash.obb` Path-prefix: `/storage/emulated/0/Android/obb/` Type: `FILE` Location: `PUBLIC_OBB` Current keeper state: `false` Suggested keeper state: `false`
> 
> ### Suggested owners
> Appname: `Slotsmash™` Packagename: `com.higgs.slotsmash` Version: `3.49 (3490)`
> 
> ### Current owners
> Appname: `Slotsmash™` Packagename: `com.higgs.slotsmash` Version: `3.49 (3490)`
> 
> ### SD Maid
> Version: `5.3.19 (50319)`
> 
> ### Device
> Fingerprint: `Blackview/A55_EEA/A55:11/RP1A.200720.011/1637317982:user/release-keys`
