### ISSUE TITLE
Bug: Device restarted after cleaning

### ISSUE THREAD

**Issue by buzzing-bee** [d4rken/sdmaid-public#5493]
### What happened?
Once cleaned, device hung and then restarted

### What did you expect to happen?
Uaing the default setting of the app, once cleaned and then finish as usual

### How can I reproduce the issue?
Not sure as the issue come and goes. Most of the times it works, while some of it is bugged

### Comments
Probably only happen at my device only
### SD Maid
Version: `5.3.19 (50319)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `asus/WW_X00TD/ASUS_X00T_2:9/PKQ1/16.2017.2009.087-20200826:user/release-keys`

**Comment by d4rken** [comment]
This sounds like a ROM instability/bug.
If this has suddenly started, it may be a sign of a dying sdcard, backup your data and try a different card or without it.
