### ISSUE TITLE
App Cleaner loops through all Apps since Version 5.3.20

### ISSUE THREAD

**Issue by TheFly4242** [d4rken/sdmaid-public#5496]
**Describe the bug**
App Cleaner loops through all Apps since Version 5.3.20

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: Realme RMX2001
 - OS: 11

**Additional context**

**Comment by d4rken** [comment]
Please provide a debug log and send me your system settings APK.
