### ISSUE TITLE
App cache cleaning no longer works

### ISSUE THREAD

**Issue by Spacenomad33** [d4rken/sdmaid-public#5497]
**Describe the bug**
Toggling the accessibility service on and off doesn't help

**To Reproduce**
Run quick access and press 'confirm' when it asks to start the cleaning process.

**Expected behavior**
I expected the app cache cleaning process to start, as it always has.

**Screenshots**

**Debug log**
[sdmaid_logfile_1651514894238.txt.zip](https://github.com/d4rken/sdmaid-public/files/8605230/sdmaid_logfile_1651514894238.txt.zip)

A screen recording of the issue:

https://user-images.githubusercontent.com/88446610/166301590-35a31d08-5e0f-45f7-bd82-e46da2296687.mp4

**Smartphone (please complete the following information):**
 - Device: Tecno Spark 6
 - OS: Android 10

**Additional context**

**Comment by dragonGod97677** [comment]
You need to add a debug log

**Comment by erdnapink** [comment]
After updating my OnePlus 8 pro to Android 12, my SDmaid pro the app cleaner doesn't work correctly and the time needed to clean, not, is very long! I'm now cleaning for example the caches by hand.
![Screenshot_2022-05-02-18-09-37-22_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/104785164/166290620-546dfacf-59b2-4ac4-8560-0c836ee55fda.jpg)

**Comment by d4rken** [comment]
> After updating my OnePlus 8 pro to Android 12, my SDmaid pro the app cleaner doesn't work correctly and the time needed to clean, not, is very long! I'm now cleaning for example the caches by hand. [Screenshot_2022-05-02-18-09-37-22_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/104785164/166290620-546dfacf-59b2-4ac4-8560-0c836ee55fda.jpg)

Please make a new ticket, specific to your device (OnePlus) and upload your system settings apk. You can extract it using SD Maid's AppControl tool.

**Comment by d4rken** [comment]
I can't tell from the log, but the ACS option is neither not enabled or the service not launched.
Reboot the device, go into AppCleaner settings, and disable/enable it again.
Currently looks like a ROM issue, if you had already done this, also see:

https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting

**Comment by Spacenomad33** [comment]
> I can't tell from the log, but the ACS option is neither not enabled or the service not launched.
> Reboot the device, go into AppCleaner settings, and disable/enable the accessibility service again.
> Currently looks like a ROM issue, if you had already done this, also see:
> 
> https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting

Sorry for the late response. I didn't get around to restarting my phone until today. I tried it again and this time it worked! I guess it just needed a system reboot to get over whatever was bugging out with it before.
