### ISSUE TITLE
Bug: since the latest update, I can't access settings.

### ISSUE THREAD

**Issue by mott69** [d4rken/sdmaid-public#5498]
### What happened?
app restart without previous settings.

### What did you expect to happen?
my previous settings .. no animations and run and done once

### How can I reproduce the issue?
pressing settings does nothing at all.

### Comments
this was a good app and I preferred it over Google files but with settings .....
### SD Maid
Version: `5.3.20 (50320)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `motorola/borneo_a/borneo:11/RZBS31.Q2-143-27-7/3f699:user/release-keys`

**Comment by d4rken** [comment]
I'm not sure what you mean, can you post a video?
