### ISSUE TITLE
Bug: Automation in app cleaner

### ISSUE THREAD

**Issue by Shhadow337** [d4rken/sdmaid-public#5507]
### What happened?
Automation in app cleaner don't work properly in Android 12 One Plus 8T

### What did you expect to happen?
To clean up my apps with app cleaner

### How can I reproduce the issue?
Just using app cleaner, like always

### Comments
Automation in app cleaner don't work properly after update to Android 12 One Plus 8T
### SD Maid
Version: `5.3.20 (50320)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OnePlus/OnePlus8T_EEA/OnePlus8T:12/SKQ1.210216.001/R.GDPR.202204222157:user/release-keys`

**Comment by Panas1989** [comment]
Hello! The cleaning planner for changing the region of Great Britain helped me!

**Comment by Shhadow337** [comment]
> Hello! The cleaning planner for changing the region of Great Britain helped me!

I don't really understand what you mean - i've searched options in sd maid already, but nothing special there.
Any instructions to do what you said?

**Comment by d4rken** [comment]
Please upload your systems settings apk, you can usually export it via SD Maids AppControl: `com.android.settings`

and provide a debug log of the cleaning failing:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by frebergguru** [comment]
It does not work properly on OnePlus 9 Pro either, it uses over 30 minuttes! and don't clean up much either.
I did stop the cleaning process after about 40 or 50 minuttes though.

See attached debug log.

I tried to upload the system settings apk too, but GitHub won't allow me, even if it is compress with gunzip.

[sdmaid_logfile_1651761511446.txt.zip](https://github.com/d4rken/sdmaid-public/files/8632405/sdmaid_logfile_1651761511446.txt.zip)

**Comment by d4rken** [comment]
> I tried to upload the system settings apk too, but GitHub won't allow me, even if it is compress with gunzip.

Can you use some file hoster? Dropbox? Or just remove the file ending and try Github again.

**Comment by frebergguru** [comment]
Uploaded it to wetransfer.

https://we.tl/t-mcSjtvYlNx

**Comment by d4rken** [comment]
Thanks, should be fixed in the next update.

**Comment by frebergguru** [comment]
It stil don't work in v5.3.21.

**Comment by d4rken** [comment]
Please provide another debug log :bow:

**Comment by frebergguru** [comment]
[sdmaid_logfile_1652734708845.txt.zip](https://github.com/d4rken/sdmaid-public/files/8703479/sdmaid_logfile_1652734708845.txt.zip)

There you have it.:-) I did once again stop it after several minuttes.

115.1MB uncompressed.

**Comment by d4rken** [comment]
Running it until 1-2 apps are skipped is enough. The rest is just SD Maid retrying the same pattern on a different screen.

I have made some changes. If you want to try a test version before the next beta, send me a quick mail or come on discord.
