### ISSUE TITLE
Bug: Unable to run App Cleaner to clean cache 

### ISSUE THREAD

**Issue by CaptainKnox** [d4rken/sdmaid-public#5508]
### What happened?
Clicked on run and clean as usual. All functions worked properly except App Cleaner. The overlay window came up but the function was unable to clean cache.

### What did you expect to happen?
Normally, the overlay window comes up and cache is cleaned.

### How can I reproduce the issue?
I am on ColorOS 12.1. This issue can be reproduced by running App Cleaner. I have accessibility service turned on.

### Comments
My device is unrooted and I can also provide a screen recording of the issue if required.
### SD Maid
Version: `5.3.20 (50320)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `OPPO/CPH2023/OP4BA1L1:12/RKQ1.211103.002/Q.202204142355:user/release-keys`

**Comment by CaptainKnox** [comment]
https://user-images.githubusercontent.com/29699930/166892040-641d3665-60e3-4b60-a1e4-758d3ca73bb5.mp4

**Comment by CaptainKnox** [comment]
Here's the link to the screen recording
https://drive.google.com/file/d/1FnrmSGS7ssuH6f-_oDdq6AE8QGM1aYP1/view?usp=drivesdk

**Comment by d4rken** [comment]
Please upload your systems settings apk, you can usually export it via SD Maids AppControl: `com.android.settings`

and provide a debug log of the cleaning failing:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by drhackstorm** [comment]
Same issue here with EMUI 12

**Comment by stefanos-apostolopoulos** [comment]
I have the same issue. My device is Samsung A5 2017 with android 8 unrooted . The phone language is set to greek. The app cleaner scroll down twice to find storage (Αποθήκευση). I looked in settings and I found solution. Maybe this fix your problem too. So first go in app settings > Appcleaner> scroll all the way down to Custom accesibility sequence.
There write at first line the exact label from your device. For example the storage which is the first step in my device is Αποθήκευση (greek) then hit enter to go to new line and write the exact label for clear cache in my case ΕΚΚΑΘ. ΜΝΗΜΗΣ CACHE .  After that you are ready to go.

**Comment by drhackstorm** [comment]
> I have the same issue. My device is Samsung A5 2017 with android 8 unrooted . The phone language is set to greek. The app cleaner scroll down twice to find storage (Αποθήκευση). I looked in settings and I found solution. Maybe this fix your problem too. So first go in app settings > Appcleaner> scroll all the way down to Custom accesibility sequence. There write at first line the exact label from your device. For example the storage which is the first step in my device is Αποθήκευση (greek) then hit enter to go to new line and write the exact label for clear cache in my case ΕΚΚΑΘ. ΜΝΗΜΗΣ CACHE . After that you are ready to go.

Thanks for your response,
But I already did that with no result

**Comment by stefanos-apostolopoulos** [comment]
> > I have the same issue. My device is Samsung A5 2017 with android 8 unrooted . The phone language is set to greek. The app cleaner scroll down twice to find storage (Αποθήκευση). I looked in settings and I found solution. Maybe this fix your problem too. So first go in app settings > Appcleaner> scroll all the way down to Custom accesibility sequence. There write at first line the exact label from your device. For example the storage which is the first step in my device is Αποθήκευση (greek) then hit enter to go to new line and write the exact label for clear cache in my case ΕΚΚΑΘ. ΜΝΗΜΗΣ CACHE . After that you are ready to go.
> 
> Thanks for your response, But I already did that with no result

Are you sure you typed the 2 steps correctly? Because I didn't at first and it didn't worked. Look these 3 screenshots to see what I mean
Storage label https://i.imgur.com/OsupQH9.jpg thìs worked with first try 

Clear cache https://i.imgur.com/KDJ4vcj.jpg at this step I didn't wrote it exact as my device shows it and it was stuck.

And in app this is how I wrote them https://i.imgur.com/1oNWWjb.jpg

So can your try again ?

**Comment by drhackstorm** [comment]
> > > I have the same issue. My device is Samsung A5 2017 with android 8 unrooted . The phone language is set to greek. The app cleaner scroll down twice to find storage (Αποθήκευση). I looked in settings and I found solution. Maybe this fix your problem too. So first go in app settings > Appcleaner> scroll all the way down to Custom accesibility sequence. There write at first line the exact label from your device. For example the storage which is the first step in my device is Αποθήκευση (greek) then hit enter to go to new line and write the exact label for clear cache in my case ΕΚΚΑΘ. ΜΝΗΜΗΣ CACHE . After that you are ready to go.
> > 
> > 
> > Thanks for your response, But I already did that with no result
> 
> Are you sure you typed the 2 steps correctly? Because I didn't at first and it didn't worked. Look these 3 screenshots to see what I mean Storage label https://i.imgur.com/OsupQH9.jpg thìs worked with first try
> 
> Clear cache https://i.imgur.com/KDJ4vcj.jpg at this step I didn't wrote it exact as my device shows it and it was stuck.
> 
> And in app this is how I wrote them https://i.imgur.com/1oNWWjb.jpg
> 
> So can your try again ?

Thanks again for your support
Be sure that I already did exactly as you say from day one I have this problem, but it seems that the new  app version has some difficulties with new UI versions as EMUI or Oxygen Os  or Color Os.

**Comment by d4rken** [comment]
> Please upload your systems settings apk, you can usually export it via SD Maids AppControl: `com.android.settings`
> 
> and provide a debug log of the cleaning failing: https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

:point_up:

**Comment by drhackstorm** [comment]
[Log file](https://drive.google.com/file/d/1uWMSEq5PM_1jt95bQs-6UvWsHSDUPTaO/view?usp=drivesdk)
This is the log file

>

**Comment by d4rken** [comment]
@CaptainKnox's issue should be fixed with #5507 and #5499, it was Oppo specific.

@drhackstorm Your issue is different, I have fixed the custom sequence not working. The nesting level was not deep enough, the default lookup for the next clickable parent element was only 3-levels, but for your system setting it needs to be at least 6-levels.

It would be better to add default support for your ROM though. If you can, make a new ticket for your specific ROM and provide your system settings apk + a debug log of the AppCleaner without the custom sequence.

**Comment by d4rken** [comment]
@stefanos-apostolopoulos Same for you, if you want default support for your ROM, make a new ticket, provide a debuglog and the system settings apk.
