### ISSUE TITLE
Clutterreport: /storage/emulated/0/Huawei/CloudDrive/.thumbnail/category/676eb5da7aab9d04ed2f0d35a1b36c94.cache (new)

### ISSUE THREAD

**Issue by popb1** [d4rken/sdmaid-public#5509]
### Target
Target: `/storage/emulated/0/Huawei/CloudDrive/.thumbnail/category/676eb5da7aab9d04ed2f0d35a1b36c94.cache`
Prefix-free: `Huawei/CloudDrive/.thumbnail/category/676eb5da7aab9d04ed2f0d35a1b36c94.cache`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Chrome`
Packagename: `com.android.chrome`
Version: `100.0.4896.127 (489612733)`

### Current owners
None

### SD Maid
Version: `4.15.4 (41504)`

### Device
Fingerprint: `HUAWEI/STK-L21MDV/HWSTK-HF:10/HUAWEISTK-L21/10.0.0.274C185:user/release-keys`

**Comment by dragonGod97677** [comment]
Nope, that doesn't owned by chrome

**Comment by dragonGod97677** [comment]
> Nope, that doesn't owned by chrome

Same as #5510
