### ISSUE TITLE
Bug: Add on App visible in Apps menu

### ISSUE THREAD

**Issue by faizm1243** [d4rken/sdmaid-public#5517]
### What happened?
Add on App used to be hidden but now it is visible in my  app Drawer. Pls Fix it

### What did you expect to happen?
Add on app should be invisible and not show in the App Drawer as seeing two app icon next to each other and one does nothing is pretty annoying. 

### How can I reproduce the issue?
Just install the Add on App from Play Store. 

### Comments
Fix it or give back my refund or convert it to in App purchase. I don't know i just don't  want Two app icon in my app Drawer. 
### SD Maid
Version: `5.3.20 (50320)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `Unknown`
Fingerprint: `iQOO/2012i/2012:12/SP1A.210812.003/compiler04072321:user/release-keys`

**Comment by d4rken** [comment]
Limitation of newer Android versions.

https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#upgrade-options

**Comment by faizm1243** [comment]
Kindly Provide me a Licence Key to Upgrade the app without Unlocker App, as
i am already a subscriber
