### ISSUE TITLE
Bug: Samsung themes deleted

### ISSUE THREAD

**Issue by hjymnol** [d4rken/sdmaid-public#5528]
### What happened?
Samsung themes that i download from samsung theme app got deleted after running sd maid quick access

### What did you expect to happen?
Themes should not be deleted by cleaning

### How can I reproduce the issue?
Download theme from samsung themes app and apply , run sd maid quick access

### SD Maid
Version: `5.3.20 (50320)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=ROOTED)`
Fingerprint: `samsung/a21snnxx/a21s:11/RP1A.200720.012/A217FXXS8CVD1:user/release-keys`

**Comment by d4rken** [comment]
Need more info, and a debug log.
What paths?
