### ISSUE TITLE
Clutterreport: /storage/extSdCard/DCIM/Camera (FP)

### ISSUE THREAD

**Issue by david082321** [d4rken/sdmaid-public#553]
### Target
Target: `/storage/extSdCard/DCIM/Camera`
Prefix-free: `DCIM/Camera`
Path-prefix: `/storage/extSdCard/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `相機`
Packagename: `com.sec.android.app.camera`
Version: `3.0 (1)`

### Current owners
Appname: `Android 系統`
Packagename: `android`
Version: `4.4.4-G530YZTU1APG1 (19)`

### SD Maid
Version: `4.3.6 (40306)`

### Device
Fingerprint: `samsung/fortunaltezt/fortunaltezt:4.4.4/KTU84P/G530YZTU1APG1:user/release-keys`

### Comment
`!!! if the phone's Brand is Samsung, then use this. (this icon is better) !!!`

**Comment by david082321** [comment]
if the phone's Brand is Samsung, then use this. (this icon is better)

**Comment by d4rken** [comment]
This is not about icons though, it's solely about which apps owns which folder.
In this case the I would still say that if "android" is present it does also own the folder, and if both apps are present, then both own this folder.

**Comment by d4rken** [comment]
It's about accuracy, so DCIM is owned by the system and "DCIM/Camera" by the camera app.
This overlaps so if "DCIM" is owned by the system "DCIM/Camera" is also owned by it :).
