### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.bandainamcoent.dblegends_ww (FP)

### ISSUE THREAD

**Issue by Zane27s** [d4rken/sdmaid-public#5531]
### Target
Target: `/storage/emulated/0/Android/data/com.bandainamcoent.dblegends_ww`
Prefix-free: `com.bandainamcoent.dblegends_ww`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `DB LEGENDS`
Packagename: `com.bandainamcoent.dblegends_ww`
Version: `4.3.0 (216)`

### Current owners
Appname: `DB LEGENDS`
Packagename: `com.bandainamcoent.dblegends_ww`
Version: `4.3.0 (216)`

### SD Maid
Version: `5.3.19 (50319)`

### Device
Fingerprint: `samsung/j7topeltetfnvzw/j7topeltetfnvzw:8.0.0/R16NW/S767VLUDU2ARI3:user/release-keys`

**Comment by d4rken** [comment]
Default matches (equal to the package name) in Android/data are not candidates for "keeper" state due to the system ignoring this when using default uninstall routines.
