### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/Google Play Services for AR(com.google.ar.core)-1.31.221020223(221020223)-split_config.xxhdpi.apk (FP)

### ISSUE THREAD

**Issue by Esssmvcs** [d4rken/sdmaid-public#5532]
### Target
Target: `/storage/emulated/0/Download/Google Play Services for AR(com.google.ar.core)-1.31.221020223(221020223)-split_config.xxhdpi.apk`
Prefix-free: `Download/Google Play Services for AR(com.google.ar.core)-1.31.221020223(221020223)-split_config.xxhdpi.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
~~Appname: `İndirilenler`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `8.0.0 (26)`~~

~~Appname: `İndirme Yöneticisi`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `8.0.0 (26)`~~

~~Appname: `Android Sistemi`~~
~~Packagename: `android`~~
~~Version: `8.0.0 (26)`~~

### SD Maid
Version: `5.3.19 (50319)`

### Device
Fingerprint: `samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXS8ETCA:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
