### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.pubg.newstate.samsung (FP)

### ISSUE THREAD

**Issue by akshaykhadse** [d4rken/sdmaid-public#5539]
### Target
Target: `/storage/emulated/0/Android/data/com.pubg.newstate.samsung`
Prefix-free: `com.pubg.newstate.samsung`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `?`
Packagename: `com.pubg.newstate.samsung`
Version: ` (-1)`

### SD Maid
Version: `5.3.19 (50319)`

### Device
Fingerprint: `samsung/gts8pwifixx/gts8pwifi:12/SP1A.210812.016/X800XXU2AVD6:user/release-keys`

### Comment
`These should be deleted`

**Comment by d4rken** [comment]
Please provide a log of the corpsefinder scan not deleting/finding it.
