### ISSUE TITLE
Clutterreport: /storage/extSdCard/backups

### ISSUE THREAD

**Issue by david082321** [d4rken/sdmaid-public#555]
### Target
Target: `/storage/extSdCard/backups`
Prefix-free: `backups`
Path-prefix: `/storage/extSdCard/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `ES檔案瀏覽器`
Packagename: `com.estrongs.android.pop`
Version: `4.1.4 (539)`

### Current owners
None
### SD Maid
Version: `4.3.6 (40306)`

### Device
Fingerprint: `samsung/fortunaltezt/fortunaltezt:4.4.4/KTU84P/G530YZTU1APG1:user/release-keys`

### Comment
`Backup apk`

**Comment by d4rken** [comment]
You can suggest multiple owners at once btw 😉 
Also if you long press and existing owner it will suggest to remove it.
