### ISSUE TITLE
White List 

### ISSUE THREAD

**Issue by Vanillma** [d4rken/sdmaid-public#5553]
**Is your feature request related to a problem? Please describe.**
---------> Problem <----------
I use Termux and the packages installed with it. After installing several packages, I realized that the volume of Termux is 1.5 GB and it contains a large number of small files of installed packages.
Then when using appCleaner & DatabaseCleaner
I realized that due to the large volume of termux files ... it takes a long time to scan
----------> Problem <----------
**Describe the solution you'd like**
-----> Description <-----
Add a section called "whitelist" that prevents the files from being scanned by database & cleaner by adding a file path. Path Example
/data/data/com.example
-----> Description <-----
**Describe alternatives you've considered**
-----> Alternative <-----
The developers and maintainers of the project may have a better idea in terms of programming to implement this feature ... I tried to describe the problem and the need that arose 
-----> Alternative <-----
**Additional context**

**Comment by d4rken** [comment]
Is this not working?
https://github.com/d4rken/sdmaid-public/wiki/Exclusions

**Comment by Vanillma** [comment]
> Is this not working? https://github.com/d4rken/sdmaid-public/wiki/Exclusions

Yes ... I just learned, it works great !!
I wondered why such a feature does not exist!
Most of the time I just use "quick access" ... then I went through the settings and found nothing !!
I thought that at the bottom of the tool list, there is only a scheduling tool !!!
But part of my mistake is with the icon selection
In my opinion, it is better not to display the "deprivation" section with a pin, because it does not mean deprivation at all!
Anyway, thank you very much ... I thought I knew everything about Rajab sd maid and I do not need to read documents (considering that I have been using it for many years and it is always the first program that I install after rooting Android)

**Comment by Vanillma** [comment]
> Is this not working? https://github.com/d4rken/sdmaid-public/wiki/Exclusions

Yes ... I just learned, it works great !!
I wondered why such a feature does not exist!
Most of the time I just use "quick access" ... then I went through the settings and found nothing !!
I thought that at the bottom of the tool list, there is only a scheduling tool !!!
But part of my mistake is with the icon selection
In my opinion, it is better not to display the " exclusion" section with a pin, because it does not mean exclusion at all!
Anyway, thank you very much ... I thought I knew everything about sd maid and I do not need to read documents (considering that I have been using it for many years and it is always the first program that I install after rooting Android)

**Comment by d4rken** [comment]
> In my opinion, it is better not to display the exclusion section with a pin, because it does not mean exclusion at all!

Suggest a better icon :shrug:

**Comment by Vanillma** [comment]
> > In my opinion, it is better not to display the exclusion section with a pin, because it does not mean exclusion at all!
> 
> Suggest a better icon 🤷

Hello again, I hope you are well😃
You are right ... choosing an icon is hard work😶
First of all, thank you for your suggestion ... but unfortunately I do not have good taste!
I did a Google search and found a bunch of different icons ... But I'm not really sure if they are suitable, in the end it is up to you (as the developer) to choose from them😬.

**Comment by d4rken** [comment]
Well I chose the current icon, without someone suggesting a better one, it will stay like it is :slightly_smiling_face:.
