### ISSUE TITLE
Wrong info about free space and total space

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/sdmaid-public#5575]
I'm using a Samsung phone running on Android 12. The internal storage in my phone is 512 GB, but SD Maid incorrectly reports it as 496 GB. Likewise, the free space reported too is incorrect.

![Screenshot_20220620-110404_SD Maid](https://user-images.githubusercontent.com/54448474/174532924-ed7dbd03-e2e7-40f5-9dd4-c834b9b6e523.png)

Kindly fix this calculation error.

The stock file manager reports 195 GB used out of 512 GB. Which means that the free space available currently is 317 GB. This app is reporting 340 GB free, which is an unexplained difference of 23 GB.

**Comment by d4rken** [comment]
The stock file manager is likely lying. No 512GB storage device actually has 512GB of usable storage. A 512GB storage device, after formatting and file systems etc. probably has around 490GB of usable storage space.

SD Maid also does not list the the whole storage size, but the size of the ***partition*** the storage area resides on.

Afaict, this looks correct on SD Maids end.

**Comment by TheMysticS** [comment]
In that case, it is 512 - 496 = 16 GB of space not available on internal storage.

But when we see the difference in free space, it is 23 GB. What about this difference of 7 GB? SD Maid is reporting significantly higher amount of free space as being available.

I have checked the storage details using multiple apps, and surprisingly all of them report different numbers for each category. Not sure which one is correct. Since the stock file manager is a system app, I thought it is more likely reporting the correct numbers.

With all that said, is it possible to implement a proper storage analyser within SD Maid that will also list storage used by each type of file like Images, Videos, etc.?

Thanks.

**Comment by d4rken** [comment]
> But when we see the difference in free space, it is 23 GB. What about this difference of 7 GB? SD Maid is reporting significantly higher amount of free space as being available.

Probably split off 7GB for a different partition.
https://android.stackexchange.com/questions/5232/how-can-i-view-the-android-internal-partition-table

> I have checked the storage details using multiple apps, and surprisingly all of them report different numbers for each category. Not sure which one is correct. Since the stock file manager is a system app, I thought it is more likely reporting the correct numbers.

That's because storage on Android is a mess. For many tools, it may be subjective choices by the developers implementing it in a specific way, or just making mistakes as storage is so very complex on Android.
For the internal file manager, Samsung has just made it easier for themselves. Less questions from users if their "512GB" phone does not show "496GB" :shrug:.

* https://www.crucial.com/support/articles-faq-ssd/ssd-showing-smaller-than-advertised
* https://www.google.com/search?q=linux+filesystem+overhead

> With all that said, is it possible to implement a proper storage analyser within SD Maid that will also list storage used by each type of file like Images, Videos, etc.?

Not without root, and probably requires a lot of ROM specific code, as every manufacturer cooks their own special soup with regards to storage.

**Comment by TheMysticS** [comment]
If that 7 GB is for a different partition, I guess it isn't available for the user for his files. As such, shouldn't SD maid have a way to figure this out and report free storage accordingly?

As with storage analyser, check this out:

https://play.google.com/store/apps/details?id=com.cls.partition

This app reports figures that are close to what the stock file manager reports. It also has a custom category where user can define the file extensions to be checked for inclusion there. Ideally, there should have been multiple custom categories, so users have better control over their files and their device storage. This app doesn't require root. Nor do other apps that perform similar function.

**Comment by dragonGod97677** [comment]
Hey @TheMysticS if you wanna know the real available usable storage on your device(s), use this app 
![Screenshot_2022-06-26-09-59-57-13](https://user-images.githubusercontent.com/38875906/175796228-a63b59ae-3631-4391-be2c-d47d81ce11b3.png)


My device said I have a total of 16GB but actually, i can only use 8.92GB of the 16GB, which is also not exactly 16GB because probably after formatting the storage(not by me of course)
![Screenshot_2022-06-26-10-03-32-52](https://user-images.githubusercontent.com/38875906/175796321-2561555d-7223-4022-b5e8-65caaeb41639.png)


This is actually 16GB, but it currently reports to me 32GB because i expanded the internal storage by formatting my 32GB SD Card as internal.
![Screenshot_2022-06-26-10-07-10-47](https://user-images.githubusercontent.com/38875906/175796355-6f04d60a-7329-4c45-a5c3-264fe619c057.png)

**Comment by TheMysticS** [comment]
@dragonGod97677 

Thanks for the details. This app is very neat and very well made. Free storage that it reports matches exactly with what the stock file manager is reporting.

@d4rken 

That 7 GB which we talked about earlier: could it be SWAP? I have allocated 8 GB to 'RAM Plus' on my Samsung phone. So that space is pretty much available for the user if he chooses to turn off this feature.

**Comment by dragonGod97677** [comment]
> @dragonGod97677
> 
> Thanks for the details. This app is very neat and very well made. Free storage that it reports matches exactly with what the stock file manager is reporting.
Your welcome and yes, it reports correct free space and your exact space you (user) can use


> @d4rken
> 
> That 7 GB which we talked about earlier: could it be SWAP? I have allocated 8 GB to 'RAM Plus' on my Samsung phone. So that space is pretty much available for the user if he chooses to turn off this feature. Which also means that it isn't space used by another partition, as suspected earlier.

My opinion on this: probably its the SWAP memory

**Comment by TheMysticS** [comment]
Check this out:

DiskInfo

![Screenshot_20220626-111929_DiskInfo](https://user-images.githubusercontent.com/54448474/175801403-75858e44-f216-4b12-8107-a1af40940ea5.jpg)


Stock File Manager

![Screenshot_20220626-112051_My Files](https://user-images.githubusercontent.com/54448474/175801413-b2021177-58df-4644-8c67-abe4ae3790ec.png)


SD Maid

![Screenshot_20220626-112008_SD Maid](https://user-images.githubusercontent.com/54448474/175801422-14119ace-6fc3-4678-a67d-ee4fa317ddb1.png)


The DiskInfo app is reporting RAM also correctly. It is saying 9.9 GB as total RAM because 2.1 GB is reserved for the system:

![Screenshot_20220626-112238_Device care](https://user-images.githubusercontent.com/54448474/175801453-27900f3b-c99e-487b-99cf-b6c181516384.png)


It is a beautiful app too. 😍😍

**Comment by dragonGod97677** [comment]
Hm... can you tap the primary storage on sd maid overview and send a
screenshot?

**Comment by TheMysticS** [comment]
Here it is:

![Screenshot_20220626-112855_SD Maid](https://user-images.githubusercontent.com/54448474/175801589-094b32ad-2607-4bae-b45b-4d7bd0f57db1.png)

**Comment by dragonGod97677** [comment]
OH I ALREADY KNOW WHY THAT IS HAPPENING

**Comment by dragonGod97677** [comment]
![Screenshot_2022-06-26-14-02-05-22](https://user-images.githubusercontent.com/38875906/175801688-79fc26fc-bcd7-45aa-8d84-a43ecc225de9.png)

**Comment by TheMysticS** [comment]
> OH I ALREADY KNOW WHY THAT IS HAPPENING

Can you let us know what that is?

**Comment by TheMysticS** [comment]
I'm not sure if the difference is because of units of measurement. Because if that is true, then what about the SWAP space allocated?

DiskInfo is showing both separately, and i don't think the swap space shown is part of the Data partition which is calculated separately.

**Comment by dragonGod97677** [comment]
> I'm not sure if the difference is because of units of measurement. Because if that is true, then what about the SWAP space allocated?
> 
> DiskInfo is showing both separately, and i don't think the swap space shown is part of the Data partition which is calculated separately.

It is like that because of different measurements and as for SWAP, it is already in the /data partition

**Comment by TheMysticS** [comment]
> > I'm not sure if the difference is because of units of measurement. Because if that is true, then what about the SWAP space allocated?
> > DiskInfo is showing both separately, and i don't think the swap space shown is part of the Data partition which is calculated separately.
> 
> It is like that because of different measurements and as for SWAP, it is already in the /data partition

Updated my previous comment. I think you have figured it out correctly.

**Comment by dragonGod97677** [comment]
SD maid just doesn't shows up the swap and i guess it won't be necessarily to show it up right?

**Comment by TheMysticS** [comment]
> SD maid just doesn't shows up the swap and i guess it won't be necessarily to show it up right?

So the unit of measurement must be stated correctly.

What is the short form for Gibibyte?

**Comment by dragonGod97677** [comment]
> > SD maid just doesn't shows up the swap and i guess it won't be necessarily to show it up right?
> 
> So the unit of measurement must be stated correctly.
> 
> What is the short form for Gibibyte?

 it's GiB
And Gigabyte is GB

**Comment by TheMysticS** [comment]
> > > SD maid just doesn't shows up the swap and i guess it won't be necessarily to show it up right?
> > 
> > 
> > So the unit of measurement must be stated correctly.
> > What is the short form for Gibibyte?
> 
> it's GiB And Gigabyte is GB

@d4rken 

Please correct the numbers to report them in GB, and not GiB. Thanks.

**Comment by TheMysticS** [comment]
DiskInfo in SI:

![Screenshot_20220626-114612_DiskInfo](https://user-images.githubusercontent.com/54448474/175802126-6207af7e-fc5c-49ec-8cc5-85360884030d.jpg)

**Comment by TheMysticS** [comment]
Thanks to @dragonGod97677 for figuring this out.

@d4rken 

You may please close this issue.

But do consider the storage analyser feature i wrote about earlier. Thanks.

**Comment by dragonGod97677** [comment]
> It is Samsung's fault. They are reporting the numbers in GiB, but showing the unit as GB.

Samsung does make good phone but can be a headache sometimes, specially on software part
