### ISSUE TITLE
Bug: App cleaner not working

### ISSUE THREAD

**Issue by hamzaharoon1314** [d4rken/sdmaid-public#5577]
### What happened?
I have Samsung Galaxy S7 with PixelExperience Rom

### What did you expect to happen?
I should clean the apps but it just try again and again and than skip to next app without cleaning 

### How can I reproduce the issue?
Run the Cleaner and let it clean and you'll notice it's not working 

### SD Maid
Version: `5.3.23 (50323)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU2ERD5:user/release-keys`

**Comment by hamzaharoon1314** [comment]
[sdmaid_logfile_1655924725003.txt.zip](https://github.com/d4rken/sdmaid-public/files/8960670/sdmaid_logfile_1655924725003.txt.zip)

**Comment by hamzaharoon1314** [comment]
System Apk file
https://www.dropbox.com/s/e90ogwsla11yeri/Settings%20%5B12%5D.apk?dl=0

**Comment by d4rken** [comment]
Can't confirm this.
I think it's a ROM issue:
It's an Android 8 ROM: `samsung/heroltexx/herolte:8.0.0`
But it says it's Android 12: `ro.build.version.release=12`
