### ISSUE TITLE
Maid hung over, partied to hard, no working

### ISSUE THREAD

**Issue by mcgeheese123** [d4rken/sdmaid-public#5580]
**Describe the bug**

**To Reproduce**
1. Open maid, scan, maid no work 

**Expected behavior**
A clear and concise description of what you expected to happen regular cleaning as usual

**Screenshots**

**Debug log**
Record a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log) while reproducing the problem and attach the zip file here.

**Smartphone (please complete the following information):**
 - Device: moto g7
 - OS: [e.g. Android 11

**Additional context**
Add any other context about the problem here. Can't seem to attach zip here, can email. Saved to drive.

**Comment by dragonGod97677** [comment]
Incomplete explanation and please include debug log
