### ISSUE TITLE
About storage

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/sdmaid-public#5584]
Why sd maid just shows only one storage on Overview, it doesn't shows the system, data and even cache partition like the older version.
![Screenshot_2022-06-26-10-16-47-67](https://user-images.githubusercontent.com/38875906/175796572-b35a7745-6903-436b-9e4a-435f2ced90fb.png)

**Comment by TheMysticS** [comment]
Use DiskInfo app 😀😀

https://play.google.com/store/apps/details?id=com.drhowdydoo.diskinfo

**Comment by dragonGod97677** [comment]
> Use DiskInfo app 😀😀
> 
> https://play.google.com/store/apps/details?id=com.drhowdydoo.diskinfo

Im already using it, i just wanna know why he removed the other partitions on overview

**Comment by dragonGod97677** [comment]
> > > Use DiskInfo app 😀😀
> > > https://play.google.com/store/apps/details?id=com.drhowdydoo.diskinfo
> > 
> > 
> > Im already using it, i just wanna know why he removed the other partitions on overview
> 
> That was just a joke. You are the one who told me about this app, remember?

Yes and yes i knew it was a joke, i just did forget to add a emoji XD

anyway...Closing this now since i got the answer, thanks d4rken
