### ISSUE TITLE
Clutterreport: /storage/emulated/0/Stash

### ISSUE THREAD

**Issue by spacebar808** [d4rken/sdmaid-public#5589]
### Target
Target: `/storage/emulated/0/Stash`
Prefix-free: `Stash`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
~~Appname: `?`~~
~~Packagename: `com.m0216.stash`~~
~~Version: ` (-1)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `samsung/p3sxeea/p3s:12/SP1A.210812.016/G998BXXU5CVF2:user/release-keys`

### Comment
`This is a folder of photos.`

**Comment by d4rken** [comment]
I agree with @dragonGod97677
