### ISSUE TITLE
Clutterreport: /storage/extSdCard/Miaosila (new)

### ISSUE THREAD

**Issue by david082321** [d4rken/sdmaid-public#559]
### Target
Target: `/storage/extSdCard/Miaosila`
Prefix-free: `Miaosila`
Path-prefix: `/storage/extSdCard/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `MissEvan`
Packagename: `cn.missevan`
Version: `3.1.8 (31)`

### Current owners
None
### SD Maid
Version: `4.3.6 (40306)`

### Device
Fingerprint: `samsung/fortunaltezt/fortunaltezt:4.4.4/KTU84P/G530YZTU1APG1:user/release-keys`

**Comment by d4rken** [comment]
What type of data does this contain that it is a keeper?

**Comment by david082321** [comment]
mp3
