### ISSUE TITLE
Clutterreport: /system/etc/default-permissions/default-permissions-com.motorola.bug2go.xml (FP)

### ISSUE THREAD

**Issue by Lilchiller50** [d4rken/sdmaid-public#5597]
### Target
Target: `/system/etc/default-permissions/default-permissions-com.motorola.bug2go.xml`
Prefix-free: `etc/default-permissions/default-permissions-com.motorola.bug2go.xml`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Carrier Location Access`
Packagename: `com.motorola.nfwlocationattribution`
Version: `11 (30)`

### Current owners
None

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `motorola/ellis_trac/ellis:11/RRHS31.Q3-46-110-2/74844:user/release-keys`

**Comment by dragonGod97677** [comment]
Uh no
