### ISSUE TITLE
Clutterreport: /system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk (FP)

### ISSUE THREAD

**Issue by Lilchiller50** [d4rken/sdmaid-public#5598]
### Target
Target: `/system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk`
Prefix-free: `GooglePackageInstaller/GooglePackageInstaller.apk`
Path-prefix: `/system/priv-app/`
Type: `FILE`
Location: `SYSTEM_PRIV_APP`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Package installer`~~
~~Packagename: `com.google.android.packageinstaller`~~
~~Version: `11-7276604 (30)`~~

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `motorola/ellis_trac/ellis:11/RRHS31.Q3-46-110-2/74844:user/release-keys`

**Comment by dragonGod97677** [comment]
Spam
