### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/.trashed-1658820394-pdf.pdf (FP)

### ISSUE THREAD

**Issue by godfauther2001** [d4rken/sdmaid-public#5599]
### Target
Target: `/storage/emulated/0/Download/.trashed-1658820394-pdf.pdf`
Prefix-free: `Download/.trashed-1658820394-pdf.pdf`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `AIO Launcher`
Packagename: `ru.execbit.aiolauncher`
Version: `4.4.4 (901448)`

Appname: `APK Extractor Pro`
Packagename: `com.magdalm.apkextractor`
Version: `14.5.0 (1450)`

Appname: `APK Explorer & Editor`
Packagename: `com.apk.editor`
Version: `v0.22 (22)`

Appname: `Admin`
Packagename: `com.google.android.apps.enterprise.cpanel`
Version: `2022030600 (2022030600)`

### Current owners
Appname: `Downloads`
Packagename: `com.android.providers.downloads.ui`
Version: `12 (31)`

Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `12.0.1 (1200001)`

Appname: `Android System`
Packagename: `android`
Version: `12 (31)`

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `OnePlus/OnePlus9ProTMO/OnePlus9ProTMO:12/SKQ1.210216.001/R.202204081820:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggested new file owners

**Comment by d4rken** [comment]
`.trashed-1658820394-pdf.pdf` sounds like a worthy target for deletion, but I agree with @dragonGod97677 the suggested owners seem wrong.
