### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.evenwell.camera2/files/Pictures (FP)

### ISSUE THREAD

**Issue by tsilem63701** [d4rken/sdmaid-public#5603]
### Target
Target: `/storage/emulated/0/Android/data/com.evenwell.camera2/files/Pictures`
Prefix-free: `com.evenwell.camera2/files/Pictures`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Camera`
Packagename: `com.evenwell.camera2`
Version: `11.0031.42 (11003142)`

### Current owners
Appname: `Camera`
Packagename: `com.evenwell.camera2`
Version: `11.0031.42 (11003142)`

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `ATT/Zion_01N0/ZON:11/RP1A.200720.011/01N0_1_600:user/release-keys`

**Comment by dragonGod97677** [comment]
SD maid already knows that folder is owned by camera
