### ISSUE TITLE
Clutterreport: /system/build.prop (FP)

### ISSUE THREAD

**Issue by Nvrcenmenbatman** [d4rken/sdmaid-public#5608]
### Target
Target: `/system/build.prop`
Prefix-free: `build.prop`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `SD Maid`
Packagename: `eu.thedarken.sdm`
Version: `5.3.23 (50323)`

### Current owners
None

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `motorola/ellis_t/ellis:11/RRHS31.Q3-46-110-7/5cde8:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid suggestion, though, can you explain how/when did sd maid own that file?

**Comment by d4rken** [comment]
Invalid and /system is out of scope

**Comment by Nvrcenmenbatman** [comment]
I must have accidentally checked the pre marked suggestion box
