### ISSUE TITLE
AppControl: Label Colours

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/sdmaid-public#5610]
![iMarkup_20220714_210355](https://user-images.githubusercontent.com/54448474/179021853-09a617e3-fc72-4775-ba55-2adf26d6a902.png)

1. The colours for Running Apps, Stopped Apps and No Internet Permissions labels are somewhat close to each other, being different shades of green. Can we have different colours to make them more prominent? Orange, Pink, Violet, etc. are some unused colours.

2. SD Maid is showing apps from both Main Profile and Work Profile on this screen, without any indicator (briefcase icon) for apps from Work Profile. Can this icon be added to apps from Work Profile, and also a filter for the same?

Thanks.

**Comment by d4rken** [comment]
> The colours for Running Apps, Stopped Apps and No Internet Permissions labels are somewhat close to each other, being different shades of green. Can we have different colours to make them more prominent? Orange, Pink, Violet, etc. are some unused colours.

Suggestions? The "no internet" is "good", so a positive color like green is suitable?

![Screenshot from 2022-07-15 12-10-43](https://user-images.githubusercontent.com/1439229/179202947-c931e869-a603-469f-a485-3b9ccdd7e0f8.png)

![Screenshot from 2022-07-15 12-11-23](https://user-images.githubusercontent.com/1439229/179203052-7f564865-b9d9-4977-b8e1-3dfc0f1c2274.png)
![Screenshot from 2022-07-15 12-11-17](https://user-images.githubusercontent.com/1439229/179203057-a654eccd-3726-40b4-80e4-fd6ddcc6fe9e.png)
![Screenshot from 2022-07-15 12-11-11](https://user-images.githubusercontent.com/1439229/179203059-4398ce53-f055-442e-8ab8-cd944355b3ec.png)


> SD Maid is showing apps from both Main Profile and Work Profile on this screen, without any indicator (briefcase icon) for apps from Work Profile. Can this icon be added to apps from Work Profile, and also a filter for the same?

Maybe, I have to look into this. Can you split this off into a new ticket, e.g. "Detect work profile apps in AppControl"?

**Comment by TheMysticS** [comment]
I think you should consider changing the colour of System label from Red to Orange, just as it is in the screenshot below:

![Screenshot_2022-07-15-16-06-39-19_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/54448474/179208321-9060cdea-1040-4cc5-b0de-8db0339ec4e7.jpg)

Stopped label should have red colour.
Running label can use a darker shade of green, to keep the separation with No Internet label more prominent.

Here are two additional colour suggestions:

1. Copper: #B87333
2. Pink: #F81894

As suggested earlier, if an app with no internet permission uses a SharedUserID, AND one of those apps with the same ID has internet permissions, then the colour of such apps must change from green to one of the above (or any other colour of your choice) to indicate this fact.

I'll create a new ticket for the Work Profile badge.

**Comment by TheMysticS** [comment]
Some more beautiful colours:

![Elegant Neutral](https://user-images.githubusercontent.com/54448474/179213162-601c6392-f215-4af6-8f88-a98d8626b951.jpg)

**Comment by TheMysticS** [comment]
These GitHub colours are good too:

![Screenshot_20220715-174123_Edge](https://user-images.githubusercontent.com/54448474/179220978-d141ece5-8098-4472-b2d7-826240a0a1dc.png)

![Screenshot_20220715-174408_Edge](https://user-images.githubusercontent.com/54448474/179220994-0da871e9-f837-44d6-acfd-1dd5ba1d26de.png)

**Comment by d4rken** [comment]
I've adjusted the colors for the next update.
