### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download (FP)

### ISSUE THREAD

**Issue by DownToTry** [d4rken/sdmaid-public#5622]
### Target
Target: `/storage/emulated/0/Download`
Prefix-free: `Download`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `8.1.0 (27)`

~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `8.1.0 (27)`~~

~~Appname: `Download manager`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `8.1.0 (27)`~~

### SD Maid
Version: `5.3.15 (50315)`

### Device
Fingerprint: `samsung/j2corepltemtr/j2corepltemtr:8.1.0/M1AJQ/J260T1UVS9AUG1:user/release-keys`

**Comment by dragonGod97677** [comment]
Invalid
