### ISSUE TITLE
Bug: App Control Bug

### ISSUE THREAD

**Issue by Cawca-Fr** [d4rken/sdmaid-public#5623]
In app control fonction when clicking on the app who have the '' no Internet access '' tag the app force close.

**Comment by d4rken** [comment]
Can you share a debug log of this?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Cawca-Fr** [comment]
> Can you share a debug log of this? https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

[sdmaid_logfile_1658517973072.txt](https://github.com/d4rken/sdmaid-public/files/9170267/sdmaid_logfile_1658517973072.txt)
[sdmaid_logfile_1658517973072.txt.zip](https://github.com/d4rken/sdmaid-public/files/9170268/sdmaid_logfile_1658517973072.txt.zip)

**Comment by d4rken** [comment]
Should be fixed with the next update.

**Comment by RektException** [comment]
Forced close without internet message. Samsung s21 ultra. Up to date.

**Comment by d4rken** [comment]
@RektException Are you sure you are on 5.4.1? Please provide a crash log.
