### ISSUE TITLE
Clutterreport: /data/app/~~g0MD29CPahsLDPwKkmlY4A==/com.google.android.gm-zjGUqBRuK5fY50eK0geSbw==/oat (new)

### ISSUE THREAD

**Issue by Porn836** [d4rken/sdmaid-public#5630]
### Target
Target: `/data/app/~~g0MD29CPahsLDPwKkmlY4A==/com.google.android.gm-zjGUqBRuK5fY50eK0geSbw==/oat`
Prefix-free: `app/~~g0MD29CPahsLDPwKkmlY4A==/com.google.android.gm-zjGUqBRuK5fY50eK0geSbw==/oat`
Path-prefix: `/data/`
Type: `DIRECTORY`
Location: `DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Gmail`
Packagename: `com.google.android.gm`
Version: `2022.07.10.460851506.Release (63374588)`

### Current owners
None

### SD Maid
Version: `5.3.23 (50323)`

### Device
Fingerprint: `samsung/p3qsqw/p3q:12/SP1A.210812.016/G998USQU5CVG4:user/release-keys`

### Comment
`how to fix desirable remnant `

**Comment by d4rken** [comment]
1.
