### ISSUE TITLE
Clutterreport: /storage/emulated/0/CleanMyAndroid (new)

### ISSUE THREAD

**Issue by mlw91154** [d4rken/sdmaid-public#569]
### Target
Target: `/storage/emulated/0/CleanMyAndroid`
Prefix-free: `CleanMyAndroid`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `CleanMyAndroid`
Packagename: `com.clean.security.memory.booster.battery`
Version: `1.1.5.1 (1151)`

### Current owners
None
### SD Maid
Version: `4.3.6 (40306)`

### Device
Fingerprint: `lge/m1_trf_us_vzw/m1:5.1.1/LMY47V/153552140b64e:user/release-keys`

**Comment by d4rken** [comment]
Thanks.
