### ISSUE TITLE
Improve statistics behavior

### ISSUE THREAD

**Issue by marksjc** [d4rken/sdmaid-public#572]
Was adjusting statistics timespan and history limits trying to understand units and interaction between settings.  Timespan apparently in calendar (not use, on, etc) hours.  Wanting one year of statistics shown in (resizable,cool!) graph and also noting that even 1000 entry limit (set by History, appearently cleanup action at event level, somewhat confusing) displayed less than one full Quick access clean, I set history to 0, but 1000 items still displayed (did reset stats/close app/open; reset not required for correct timeframe mods).  Then changed history to -1 per instructions (<0) (reset, etc) graph changed to range negative 700000.00 B to positive 684 KB.  Modification of History to positive number(1000) did not return graph to normal range.  Since - savings is hopefully impossible to achieve through program, some graph display glitch?  Find that History shows as above, but unclear how history and timeframe limit each other (I'm guessing they don't, but confusing if not clearly stated.  This is obviously a minor bug (if not user error or otherwise) but wanted to flag. Notice my assumption the settings don't interact appears negated by my observed negative graph range resulting solely fom my history change from 0 (yet 1000 events listed) then history change to -1. With zero history items showing, history set to 1000, second run after reset resulted in 1000 listings, incremented graph (second quick run, no settings changed.  And graph mysteriously repaired. Can't spend the time to re-reproduce, but mysterious.  For Quick Access, I run Corpse, System, Apps and experience approx 0% corpse clean up, 99+% app, <1% system by space saved per run and over time averages.

**Comment by d4rken** [comment]
I did not yet understand every issue you pointed out, but lets break this down into sepperate points.

> Was adjusting statistics timespan and history limits trying to understand units and interaction between settings. Timespan apparently in calendar (not use, on, etc) hours. Wanting one year of statistics shown in (resizable,cool!) graph 

The statistics (graph) use a timespan in hours backwards. `currentime - limit` anything older than that is discarded when the statistics are updated the next time.

> and also noting that even 1000 entry limit (set by History, appearently cleanup action at event level, somewhat confusing) displayed less than one full Quick access clean, 

As SD Maid logs every single file deletion (so you can search for a specific file and see if SD Maid modified it), the 1000 file limit can be quickly exceeded. Changing this to being time based can let the history quick very large very quickly though...

> I set history to 0, but 1000 items still displayed (did reset stats/close app/open; reset not required for correct timeframe mods).

Because statistics are only updated when new items are added to stats. But changing the value from 1000 to 0(unlimited) would not delete or add anything.

> Then changed history to -1 per instructions (<0) (reset, etc) graph changed to range negative 700000.00 B to positive 684 KB. Modification of History to positive number(1000) did not return graph to normal range. Since - savings is hopefully impossible to achieve through program, some graph display glitch?

Not sure what happened here.

> Find that History shows as above, but unclear how history and timeframe limit each other (I'm guessing they don't, but confusing if not clearly stated.

Size limit only affects history, and timeframe only affects statistics (graph).

This is obviously a minor bug (if not user error or otherwise) but wanted to flag. Notice my assumption the settings don't interact appears negated by my observed negative graph range resulting solely fom my history change from 0 (yet 1000 events listed) then history change to -1. With zero history items showing, history set to 1000, second run after reset resulted in 1000 listings, incremented graph (second quick run, no settings changed. And graph mysteriously repaired. Can't spend the time to re-reproduce, but mysterious. For Quick Access, I run Corpse, System, Apps and experience approx 0% corpse clean up, 99+% app, <1% system by space saved per run and over time averages.

I've got these points so far from your text:

- [ ] Update statistics when the setting is changed (currently settings only take effect when statistics are updated the next time
- [ ] Improve descriptions regarding what settings effects what widget
- [ ] Evaluate whether both History and Statistics should use a time instead of item limit.

**Comment by marksjc** [comment]
I'm sorry, I know my writing can be not clear.  When I re-read it, even I can get confused.

Thank you for clarifying and separating points:

I noted the statistics section but am somewhat confused by how it is designed to work.

UI at the end.  

I have Stat. Timespan (ST) set: 8620

I have History Limit (HL) set: 1000.

When I run, the ST numbers appear to correctly increment up, I don't know if the ST properly re-alligns be based on current date, but I assume yes.  If I run more than once in a day, ST appears to increment up.

HL appears to be a fully independent setting which controls the listed and available event database for the maximum set events.  This, however does not add/subtract/hide data from ST graph.  That implies ST is counting from a summary database number, not the database HL displays.  

To your point, databases can get huge very quickly, one thing I'm trying to avoid.  However, for me, one run as previously described always exceeds 1000 events, therefore the event list isn't comprehensive unless I set to an unknown guessed maximum per run events.  Since I probably wouldn't be able to act to reverse any SD Maid event on my own, I'm trusting SD to work well and not delete important data.  Conclusion, to save space set very low number HL or zero.

But, there are settings as described for <0 meaning disabled.  But it's unclear what disabled means, especially when 0 means unlimited.  When I put -1 in one of the settings, the graph began in a new place, as described before, at Negative 7000000.00 B (from memory).  The graph shifted position to accommodate the Y axis as it moved right.  Something became disabled, perhaps, but the graph whacked out.

So, my request is not to change function, such as modification of displayed data upon setting change.  Changing only when app run makes sense, if it us stated in the UI to avoid confusion.  

But the results of entering negative numbers (as stated are allowed to disable) results in unpredictable and very confusing results.  As I think I now understand, ST and HL are fully independent, however appearing as they do, and given common software practice where one sets a time limit for database storage and/or numeric limit, users are likely to think that there is programmatic integration of these settings.  That's why I started changing them to try to understand.

Additionally, UI if graph hard to use and understand.  Just because by "pulling" the graph left, I'm seeing higher precision for the quantity in MB for the graph, while the actual precise number listed for that type is abandoned.  Graph precision, in this case is unimportant if the very precise number represented is obscured, especially since other categories show such small quantity, that they "disappear" while I'm dragging to the very precise maximum (graph point) for the largest category.  While this scaling us cool the value if the graph as visual comparison tool becomes zero.

Now, I pull graph right to return to original state.  Rather than stop at Y=0, where I began, graph now goes to Y= negative, with two labels at top overlapping but represented as many 0 with a likely decimal.  The data labels are hard to read (date range is very small and dim) but the start date/time no appears left of Y axis.  This must be related to Y-axis lower limit at negative 70000000.00 as described above.

Sorry, I'm not entering exact zeros since likely not important.  The 7 does appear, as noted in first note.  The pull right overlapping 0's here show no other numbers.  Both indicate units of "B".

To your last 3 points:
1) No, I don't suggest redesigning how statistics field updates, of very limited real value. Saying they update only after next run will clarify and resolve completely, but only if behavior us consistent (I didn't test).

2) Yes!  Also, some indication that settings are fully independent needed.  

3) Not requested by me.  However, suggest warning dumb user (me) to take care as database can become huge would be helpful.

Now for clarification on UI:

A) The use of <0> choices is very confusing.  A choice of 0 in ST sets a start date in the 1980s.  The choice of -1 created unexpected graph.

B) The graph stretching along X is confusing and removes information (precise numbers and "non most" category bars.  Remove.  Quantity along X axis and Type along Y feels reverse if logic as well.  Suggest modify graph to simple, intuitive design.  Stretching only helpful if additional data or visual comparison becomes visible while no other data or visual aspect is obscured.  Additionally, graph must be constrained to only positive areas showing (or used for labels).  Allowing the graph to suggest negative values could be valid seems bizarre (unless they are possible, but that if true causes user to quickly uninstall app :-).

I question the value of any arbitrary number for HL.  Setting to "number of runs" makes more sense to me.  Setting it to be able to show only issues or possible problems and reserving a full xaction database for smart programmers to debug us great, but dumb users (me) will set too high and waste unlimited? space.

Back to <0> I understand the logic, but to any but most technical it is very confusing.  Questions like: How is -1 different from -99?  And what happens when I enter 3.87 in either field come up.  And 0=unlimited is logical to me, but confusing to many.  I suggest button: on/off to en- or dis-able.
Time is more nuanced and no universal intuitive choice.  My intuition matched your intent, but "days" or even number of iterations (runs) shown in a time graph also could be guessed.  Hours more precise, except runs over specific dates.  But then you need at least one or maybe two calendar fields to handle  selection and selecting a time slice ending before right now may be if little value.  Suggest simply stating "number if actual calendar hours (term sounds wrong, sorry) prior to "right now" which really means next run "now" is simplest, with only clarification and no function change.

Similar comments for <0> HL.  Disabled chosen some other way.  Number if events unpredictable, see above suggestions.

I find this excruciating to write,  I'm sorry.  While documenting is important, maybe a phone or video call would be faster and easier to communicate and you could ask me to clarify in real time.  I'm unfortunately limited to English but want to be respectful of your time and my own. And these are FYI problems/bugs to polish and do not cause any functional issues I can see.  It's just the VC statidtical comminication is confusing and has limited utility, yet needs limited real work to dramatically improve, I think.

Email to my registered address if phone or vid helpful. I have Zoom, Skype (ugh), inexpensive voice calling over PSTN to Europe for most calls (landlines always less) but I can initiate and talk an hour before $$.  Would prefer PC to PC or phone to phone for quality and connection stability.  I do have a universal SIP type number I can give if that helps you (in theory rings my home phone, but untested).....

⁣​

**Comment by d4rken** [comment]
Should be enough info for now. If I need more info I'll let you know.

**Comment by d4rken** [comment]
Next update will have completely new statistics that should be far more useful to read and manage.

Data is now saved by a top level "event" type which may reference many "extradata" types that could be affected apps or files.

Database size is now shown in the settings and a single timespan limit in days used for all statistics data.
