### ISSUE TITLE
[Feature Request] App Control: Sort by 

### ISSUE THREAD

**Issue by NeoBeum** [d4rken/sdmaid-public#573]
Add drop down list to enable sort by name, size, package name

**Comment by d4rken** [comment]
Where would you put the drop down list and how would it look?

**Comment by Gitoffthelawn** [comment]
Perhaps also sort by installation date/time and package last updated date/time.

**Comment by NeoBeum** [comment]
![screenshot_20161023-191130](https://cloud.githubusercontent.com/assets/12646422/19625053/79a29aea-9955-11e6-89b0-d5be9d0541d8.png)
![screenshot_20161023-191436](https://cloud.githubusercontent.com/assets/12646422/19625054/79a3dc2a-9955-11e6-802d-0bf490cf93cf.png)
![screenshot_20161023-191458](https://cloud.githubusercontent.com/assets/12646422/19625055/79a48f62-9955-11e6-9a1d-1f83d2c91b9a.png)

Maybe like this?

![screenshot_20161023-191259](https://cloud.githubusercontent.com/assets/12646422/19625101/8fd885d0-9956-11e6-9e05-dcca9a364666.png)

**Comment by d4rken** [comment]
Yeah good idea.

So we have:

- [ ] Name
- [ ] Size
- [ ] Packagename
- [ ] Install-date
- [ ] Update-date

Do we also need to deal with reverse sorting? If so how should we do that UI wise?

**Comment by NeoBeum** [comment]
Did my reply get sent via email? doesn't look like it...

I said instead of just radio, could have Up/Down arrow toggle.

Also had an idea - but this filter is more luxury - "Favourites" or something like "Monitored" Applications
