### ISSUE TITLE
Statistics Graph is malformed on medium-density and low-density screens

### ISSUE THREAD

**Issue by AndreaCioccarelli** [d4rken/sdmaid-public#574]
### Malformed graphic

On the Statistics Activity, When getting data from "history.db" > "spacechange" the render is calculated and showed on left. if the textviews are too big (It happens with very long languages) the risk is to find a malformed graph.

Fix it creating a `medium` and `small` screen variant  variation with only cleaner icons and an large-screens variant with both text and icons

Try with something like this: 

``` xml
<icon
  android:src="@drawable/corpose_finder"
  <!-- ... -->
  />
```

![screenshot_20161022-203235](https://cloud.githubusercontent.com/assets/23010471/19627840/b233b3a8-9950-11e6-8d4c-0d3528d8fbf6.png)

**Comment by d4rken** [comment]
Next update will try a new graph.
