### ISSUE TITLE
Add /cache partition at the Storage Analyzer Activity

### ISSUE THREAD

**Issue by AndreaCioccarelli** [d4rken/sdmaid-public#575]
### Add /cache and dalvik-cache partitions at the available mountpoints 
The available mountpoints are useful to explore /system, /data or /sdcard.
Also **/cache** and **dalvik-cache** app partitions are useful and not-include them into this section is a feature that isn't used

![screenshot_20161022-202802](https://cloud.githubusercontent.com/assets/23010471/19627874/8b363658-9951-11e6-8ff7-4fe076e5c919.png)

**Comment by d4rken** [comment]
Dalvik-Cache can either be in `/data` or in `/cache` (mostly older ROMs), as we already have `/data` just adding cache would make viewing dalvik-cache also possible on any ROM.

I'll add a setting similar to the one for `/system`, does that sound good @AndreaCioccarelli ?

**Comment by AndreaCioccarelli** [comment]
Yes, very good idea 👍
