### ISSUE TITLE
Chrome custom tabs aren't in AppTheme style

### ISSUE THREAD

**Issue by AndreaCioccarelli** [d4rken/sdmaid-public#576]
The SD-maid dark material theme is very good, but it isn't adapted at the chrome custom tabs module: It isn't according to the google material guidelines.
to fix this "Graphical Bug" simply retrive the Custom Tabs Code and rewrite it applying these code patches:

```java
String url = ¨https://sdmaid.darken.eu/¨;
CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
//Before builder construction edit object proprieties
builder.setToolbarColor(getResources().getColor(R.colors.colorPrimaryDark));
builder.setStartAnimations(this, R.anim.slide_in_right, R.anim.slide_out_left);
builder.setExitAnimations(this, R.anim.slide_in_left, R.anim.slide_out_right);
CustomTabsIntent customTabsIntent = builder.build();
customTabsIntent.launchUrl(this, Uri.parse(url));
```
![screenshot_20161022-202543](https://cloud.githubusercontent.com/assets/23010471/19627938/0c67ea18-9953-11e6-9401-696c4f0adb34.png)

**Comment by d4rken** [comment]
What would happen if the user doesn't have Chrome?

**Comment by AndreaCioccarelli** [comment]
The Chrome Custom Tabs library normally start an Intent to respond at HTTPS:// protocol if it bot detect chrome installed. You have only to write this code, the Chrome class craft automatically the Intent
