### ISSUE TITLE
Toolbar exception

### ISSUE THREAD

**Issue by AndreaCioccarelli** [d4rken/sdmaid-public#577]
### Error while handling Toolbar multi-selection
Null exception is caused by multi-selecting these views. It can be patched by adding a filter that forbid at the multiview to be showed
![screenshot_20161023-194704](https://cloud.githubusercontent.com/assets/23010471/19628611/45058772-9962-11e6-92ef-af37d8df9d2d.png)

**Comment by d4rken** [comment]
I fixed being able to select items and have an empty actionmode, but I could not reproduce any nullpointerexception.
