### ISSUE TITLE
Explorer: Show which directories are mountpoints

### ISSUE THREAD

**Issue by NeoBeum** [d4rken/sdmaid-public#579]
Can the explorer detect linked directories on External?

Internal to External
External to Internal

Like on Device Root "/" directories appear as chainlink

**Comment by d4rken** [comment]
Yes, the Explorer should be able to detect symlinks independent of location.
Note though that most external storages whether emulated or physical don't support symlinking.

**Comment by NeoBeum** [comment]
Ah, OK.

Binding is different then? I'm using another app to bind directories from Internal to External SD

**Comment by d4rken** [comment]
I don't know if it is different. There is no procedure in linux called "binding" afaik.
"Binding" is likely just a name the app author has choosen.

**Comment by NeoBeum** [comment]
It has something to do with FUSE, because on the XPeria phones Sony has disabled SD Storage mounting as Internal storage. If I turn the SD in to a EXT4 partition, the phone won't see it as extra storage.

**Comment by d4rken** [comment]
Then "binding" likely means "mounting" in that apps context. Currently SD Maid does not mark folders in the Explorer that are mountpoints but that information is available to SD Maid.
 
Do you want SD Maid to display in the explorer if a directory is a mountpoint?

FUSE, refers to _Filesystem in Userspace_, see:
https://en.wikipedia.org/wiki/Filesystem_in_Userspace

**Comment by NeoBeum** [comment]
It would be useful I think

**Comment by NeoBeum** [comment]
So on scanning system and cleanup you can see which directories to pin

**Comment by d4rken** [comment]
> So on scanning system and cleanup you can see which directories to pin

What do you mean by that?

**Comment by NeoBeum** [comment]
When SD Maid does system and app cleaning, you can see which empty directories are linked so that if you forget which directories are linked, you can Pin it so SD Maid can ignore and not delete

**Comment by d4rken** [comment]
Neither tool should (or should be able to) delete mountpoints though, did that happen?

**Comment by d4rken** [comment]
Got a good idea how we could highlight the "mountpoint" status of a folder in the explorer?

**Comment by NeoBeum** [comment]
I was going to suggest the eject icon. But that might get confusing

**Comment by d4rken** [comment]
What about an sdcard?
https://materialdesignicons.com/icon/sd

**Comment by d4rken** [comment]
It can be deactivated by disabling "Research owner" in the tools settings.

**Comment by NeoBeum** [comment]
Does disabling or assigning an owner let SD Maid know that it is a mount directory? Theres a few directories on the SD card that were mounted, but the SD Card icon isn't displayed

**Comment by d4rken** [comment]
No it's just grouped under the same option for on/off toggeling. The mount information comes directly from the system (shell: `mount`).

Can you show me an example of something that should have a sdcard icon, but doesn't?
