### ISSUE TITLE
Clutterreport: /storage/2551-16FF/Llama

### ISSUE THREAD

**Issue by 1024mb** [d4rken/sdmaid-public#580]
### Target
Target: `/storage/2551-16FF/Llama`
Prefix-free: `Llama`
Path-prefix: `/storage/2551-16FF/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
None
### SD Maid
Version: `4.3.8 (40308)`

### Device
Fingerprint: `Xiaomi/kenzo/kenzo:6.0.1/MMB29M/6.9.29:user/release-keys`

### Comment
`It's llama's backup, exported data. `

**Comment by d4rken** [comment]
Can you give me a link to the app?

**Comment by 1024mb** [comment]
Sure, here it is: https://play.google.com/store/apps/details?id=com.kebab.Llama
