### ISSUE TITLE
[Feature Request] LAN explorer

### ISSUE THREAD

**Issue by franco999** [d4rken/sdmaid-public#581]
It would be great if you could add the files explorer, navigate function on the LAN. This is among other uses, to transfer files from the PC to phone with a browser LAN.

**Comment by d4rken** [comment]
Can you elaborate how you would imagine this to be integrated into the SD Maid?

**Comment by franco999** [comment]
The truth, I have no idea about programming Android, but you could add a section in the sliding menu on the right in the browser using Samba (?). Separate between local and network files. 

If this is not feasible, from the programmer view, discard it. Currently, i have no clear idea as it could be this function.

**Comment by d4rken** [comment]
Out of SD Maids scope.
