### ISSUE TITLE
Clutterreport: /storage/emulated/0/Telegram/Telegram Images

### ISSUE THREAD

**Issue by alena88** [d4rken/sdmaid-public#582]
### Target

Target: `/storage/emulated/0/Telegram/Telegram Images`
Prefix-free: `Telegram/Telegram Images`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`
### Suggested owners

Appname: `AT&T Mail`
Packagename: `com.yahoo.mobile.client.android.mail.att`
Version: `1.0 (1)`
### Current owners

None
### SD Maid

Version: `4.3.6 (40306)`
### Device

Fingerprint: `lge/t8lte_att_us/t8lte:6.0/MRA58K/1619616488abd:user/release-keys`

**Comment by d4rken** [comment]
Isn't `Telegram` owned by https://play.google.com/store/apps/details?id=org.telegram.messenger ?
