### ISSUE TITLE
Clutterreport: /storage/emulated/0/.SPenSDK30/.nomedia

### ISSUE THREAD

**Issue by taraf399** [d4rken/sdmaid-public#596]
### Target
Target: `/storage/emulated/0/.SPenSDK30/.nomedia`
Prefix-free: `.SPenSDK30/.nomedia`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Current owners
None
### SD Maid
Version: `4.3.8 (40308)`

### Device
Fingerprint: `samsung/nobleltedv/noblelte:6.0.1/MMB29K/N920IDVU2BPH2:user/release-keys`

### Comment
`this app is unauthorised

**Comment by taraf399** [comment]
Hi, I'm a very new beginner I guess you could say. Ive got a couple of unauthorised apk popping up on my android and some .nomedia files which I cannot seem to remove. Please help

**Comment by d4rken** [comment]
The reporting functionality (or even SD Maid at all), does not have anything to do with whether something is "authorized" to be there. Use a security related app for this.

**Comment by taraf399** [comment]
Sorry I may have been miss understood. My phone and tablet and PC have had really strange things happening to them now for months. my partner and I have lost a lot of devices potentially from being hacked. my only reason for reporting to you was because we are at a dead end and starting to get worried as the large companies and providers have not been able to help us. I thought an administrator or developer may be able to help.
I'm sorry for the confusion.
Kind Regards
Tara


Sent from my SAMSUNG Galaxy Note5 on the Telstra Mobile Network
-------- Original message --------From: Matthias Urhahn <notifications@github.com> Date: 9/11/2016  2:30 PM  (GMT+10:00) To: d4rken/sdmaid-public <sdmaid-public@noreply.github.com> Cc: taraf399 <mstaralee84@gmail.com>, Author <author@noreply.github.com> Subject: Re: [d4rken/sdmaid-public] Clutterreport: /storage/emulated/0/.SPenSDK30/.nomedia (#596) 
The reporting functionality (or even SD Maid at all), does not have anything to do with whether something is "authorized" to be there. Use a security related app for this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/d4rken/sdmaid-public","title":"d4rken/sdmaid-public","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/d4rken/sdmaid-public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@d4rken in #596: The reporting functionality (or even SD Maid at all), does not have anything to do with whether something is \"authorized\" to be there. Use a security related app for this."}],"action":{"name":"View Issue","url":"https://github.com/d4rken/sdmaid-public/issues/596#issuecomment-259331856"}}}
