### ISSUE TITLE
[Feature request] Sort exclusions by path and type

### ISSUE THREAD

**Issue by lisandrocarmona** [d4rken/sdmaid-public#600]
When we see the exclusion list, it's difficult to view/review the paths as they are not listed in a particular order. Also, the exclusions cannot be sorted by type (duplicates, databases, etc.) and this will help to use and manage such a great and powerful cleaning tool.

**Comment by d4rken** [comment]
So in what way to sort them?

Am 09.11.2016 11:53 vorm. schrieb "lisandrocarmona" <
notifications@github.com>:

**Comment by lisandrocarmona** [comment]
CorpseFinder: by appname (although I never exclude anything here, it's one of the most useful cleaning).
SystemCleaner: by appname
AppCleaner: by appname (and not by packagename)
Duplicates: by path
Databases: by appname

Anyway, a way to sort by "type" or group (Global, Corpse...) is also missed, i.e., all the exclusions for Corpse or for AppCleaner.

**Comment by d4rken** [comment]
So sort the list first by tool and then each tool by something like you listed?

Maybe a pager with multiple tabs would be suited better for this, have an "All" tab and then one for each tool?

Thinking about it, sort by date added would be cool, but the current exclusions don't contain timestamps.. damn, something something 20/20...

**Comment by lisandrocarmona** [comment]
Tabs will be awesome! Each tab could have its own sort type.
Yeah, timestamps will allow to follow the timeline of the exclusion addition.

**Comment by d4rken** [comment]
I've added filtering by exclusion type. You can now pull out a drawer from the right screenside and select which type of exclusions to show.

The tab approach was too confusing in the end.
