### ISSUE TITLE
Scheduler does not run if "Skip on low battery"

### ISSUE THREAD

**Issue by Casm82** [d4rken/sdmaid-public#603]
SD Maid 4.4.1 Pro
If i select "Skip on low battery", scheduler does not run by timer or manually. Minimum battery percentage setting is less than current battery level.
Android 5.1.1, root SuperSU 2.78

![screenshot_2016-11-16-21-18-27](https://cloud.githubusercontent.com/assets/5138436/20357845/0ae62a8a-ac43-11e6-8f0f-f566b2c4fab8.png)

**Comment by d4rken** [comment]
Can you record this on a log? I couldn't reproduce it.

**Comment by Casm82** [comment]
I reinstalled application, wiped data. All settings lost, but now scheduler works fine. You may close issue. Thank you.

**Comment by d4rken** [comment]
Glad to hear it's working.
