### ISSUE TITLE
[Feature request] add Telegram clean up

### ISSUE THREAD

**Issue by kantjer** [d4rken/sdmaid-public#609]
Clean up Telegram/Plus Messenger

Telegram and unofficial mods like Plus Messenger leave a lot of cached files on the SD
Would it be possible to ad a Telegram cleaner to the AppCleaner like the WhatsApp cleaner that's already there.

Telegram uses these paths:
sdcard/Telegram/Telegram Audio
sdcard/Telegram/Telegram Documents
sdcard/Telegram/Telegram Images
sdcard/Telegram/Telegram Video

stock Telegram package: org.telgram.messenger
package name for Plus: org.telegram.plus

**Comment by d4rken** [comment]
Could you use the Explorer function "save directory structure" on the telegram folder and upload that?

**Comment by kantjer** [comment]
Uploaded the pathdump to dropbox

https://dl.dropboxusercontent.com/u/19838045/pathdump%23_storage_emulated_0_Telegram.txt

**Comment by d4rken** [comment]
Thanks.
What exactly should be deleted? Whole folder? All files except nomedia?
There seems to be no distinction between send&receive, are these all send files?

**Comment by kantjer** [comment]
All files can be deleted except .nomedia
Files are send and received combined

Themes folder should be excluded from deleting

**Comment by d4rken** [comment]
Description suggestion:

> Files received or send through Telegram.

**Comment by kantjer** [comment]
Sounds perfect
Thanks for looking into this

**Comment by d4rken** [comment]
Would you be willing to test it? If so send a mail to support and I'll make you a test build.

**Comment by kantjer** [comment]
mail send
Thanks

**Comment by d4rken** [comment]
Confirmed to work by @kantjer , next update.
