### ISSUE TITLE
Error when folder not found in Explorer

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#612]
Error displayed when folder not found in Explorer
------

**To reproduce:**

 1. Open SDMaid's Explorer.
 1. Go to a folder.
 1. Terminate SDMaid.
 1. Open another file manager.
 1. Use another file manager to delete the folder from Step 2.
 1. Go back to SDMaid.
 1. The following error is issued: `java.io.IOException: Can't access: [folder]`

**Recommendation:**

Indicate that the folder is not present without having a code exception.
For example: *"Folder [folder] no longer present."*

***Tested with SDMaid v4.4.1.***

**Comment by d4rken** [comment]
We don't know though whether the folder is "not present", it could just have permissions that don't allow us to read it.

**Comment by Gitoffthelawn** [comment]
Hmmm.... good point.  The folder (and error) was:
`java.io.IOException: Can't access: /data/app-lib/pxlib.android.defaultappset`

**Comment by d4rken** [comment]
The (on purpose) vague description of "Can't access" is displayed whenever SD Maid tries to read something that returns empty results. So I think we can keep it this way as there is no good alternative?

**Comment by Gitoffthelawn** [comment]
I agree.  I think instead of issuing:
`java.io.IOException: Can't access: [folder]`

issue:

`Can't access: [folder]`

And, if possible, indicate *why* (missing folder, lack of permissions, etc.).
