### ISSUE TITLE
Can you add android tv support to sd maid app?

### ISSUE THREAD

**Issue by naju10** [d4rken/sdmaid-public#613]
Hi,

Can you add native android tv support for the sd maid pro app?

I have sideloaded it on my nexus player and it works fine. It just needs a few changes like.. When I am scrolling up and down with the remote, it is hard to know where you are at. Like the scan button doesn't get highlighted at all. Other then that the app works absolutely fine.

Adding native android tv support would make the app appear in the lean back icons on the main home page. 

Kindly consider adding this.
Thanks

**Comment by d4rken** [comment]
Linking to existing tickets.

https://github.com/d4rken/sdmaid-public/issues/389

https://github.com/d4rken/sdmaid-public/issues/342
