### ISSUE TITLE
v4.5.0 BETA: ""Move to SD Card" not working

### ISSUE THREAD

**Issue by noc-jfcbs** [d4rken/sdmaid-public#614]
Despite certainly having root "Move to SD Card" didn't work (yet) for me.
Catlog and screenshots attached.
[2016-12-13-20-55-55.txt](https://github.com/d4rken/sdmaid-public/files/651986/2016-12-13-20-55-55.txt)
![screenshot_20161213-205410](https://cloud.githubusercontent.com/assets/21972717/21185852/9efe67f2-c212-11e6-8a34-2f338e9f9bc4.png)
![screenshot_20161213-205441](https://cloud.githubusercontent.com/assets/21972717/21185851/9efe5f96-c212-11e6-9ed0-dc7cfd379c6a.png)

**Comment by d4rken** [comment]
Interesting bits from catlog:

```
12-13 20:52:36.718 D/AndroidRuntime(4240): Calling main entry com.android.commands.pm.Pm
12-13 20:52:36.738 V/PackageManager(3419): Move 1 created Bundle[{android.intent.extra.PACKAGE_NAME=de.apptiv.business.android.aldi_de, android.intent.extra.TITLE=ALDI SÜD}]
12-13 20:52:36.738 I/ActivityManager(3419): Force stopping de.apptiv.business.android.aldi_de appid=10162 user=-1: move pkg
12-13 20:52:36.738 W/PackageManager(3419): Failed to move de.apptiv.business.android.aldi_de
12-13 20:52:36.738 W/PackageManager(3419): com.android.server.pm.PackageManagerException: Move location not mounted private volume
12-13 20:52:36.738 W/PackageManager(3419): 	at com.android.server.pm.PackageManagerService.movePackageInternal(PackageManagerService.java:17204)
12-13 20:52:36.738 W/PackageManager(3419): 	at com.android.server.pm.PackageManagerService.-wrap33(PackageManagerService.java)
12-13 20:52:36.738 W/PackageManager(3419): 	at com.android.server.pm.PackageManagerService$24.run(PackageManagerService.java:17098)
12-13 20:52:36.738 W/PackageManager(3419): 	at android.os.Handler.handleCallback(Handler.java:739)
12-13 20:52:36.738 W/PackageManager(3419): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-13 20:52:36.738 W/PackageManager(3419): 	at android.os.Looper.loop(Looper.java:148)
12-13 20:52:36.738 W/PackageManager(3419): 	at android.os.HandlerThread.run(HandlerThread.java:61)
12-13 20:52:36.738 W/PackageManager(3419): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-13 20:52:36.738 V/PackageManager(3419): Move 1 status -6
```

Second attempt i presume?
```
12-13 20:54:23.943 D/AndroidRuntime(5715): Calling main entry com.android.commands.pm.Pm
12-13 20:54:23.963 V/PackageManager(3419): Move 2 created Bundle[{android.intent.extra.PACKAGE_NAME=de.apptiv.business.android.aldi_de, android.intent.extra.TITLE=ALDI SÜD}]
12-13 20:54:23.963 I/ActivityManager(3419): Force stopping de.apptiv.business.android.aldi_de appid=10162 user=-1: move pkg
12-13 20:54:23.963 W/PackageManager(3419): Failed to move de.apptiv.business.android.aldi_de
12-13 20:54:23.963 W/PackageManager(3419): com.android.server.pm.PackageManagerException: Move location not mounted private volume
12-13 20:54:23.963 W/PackageManager(3419): 	at com.android.server.pm.PackageManagerService.movePackageInternal(PackageManagerService.java:17204)
12-13 20:54:23.963 W/PackageManager(3419): 	at com.android.server.pm.PackageManagerService.-wrap33(PackageManagerService.java)
12-13 20:54:23.963 W/PackageManager(3419): 	at com.android.server.pm.PackageManagerService$24.run(PackageManagerService.java:17098)
12-13 20:54:23.963 W/PackageManager(3419): 	at android.os.Handler.handleCallback(Handler.java:739)
12-13 20:54:23.963 W/PackageManager(3419): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-13 20:54:23.963 W/PackageManager(3419): 	at android.os.Looper.loop(Looper.java:148)
12-13 20:54:23.963 W/PackageManager(3419): 	at android.os.HandlerThread.run(HandlerThread.java:61)
12-13 20:54:23.963 W/PackageManager(3419): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-13 20:54:23.963 V/PackageManager(3419): Move 2 status -6
```

**Comment by d4rken** [comment]
```
Move location not mounted private volume
```

Could you tell me more about your devices storage setup?

If possible please still provide a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by noc-jfcbs** [comment]
Please find attached the SD Maid logfile. Please advise unless it's sufficient.
Does the attached screenshot provides sufficient information regarding the external storage?
In a moment, I'm going to try to move an app to extSD on another Samsung GT-i9305; however, that one is running on Resurrection Remix v5.8.0-1 i.e. Nougat 7.1.1.
![screenshot_20161215-070954](https://cloud.githubusercontent.com/assets/21972717/21213869/7f5c4038-c297-11e6-9491-f96e21ceab63.png)

**Comment by noc-jfcbs** [comment]
Move to SD Card also failed on our other device but this one running Resurrection Remix v5.8.0-1 i.e. Nougat 7.1.1.
SD Maid log file attached, as well as some information regarding storage.
![screenshot_20161215-082325](https://cloud.githubusercontent.com/assets/21972717/21215421/74584d80-c2a1-11e6-9b9a-33c60156f73a.png)
[sdmaid_logfile_1481785954640.txt](https://github.com/d4rken/sdmaid-public/files/653996/sdmaid_logfile_1481785954640.txt)

**Comment by d4rken** [comment]
SD Maid fails to determine the target storage and tries to use `null` as target.

RR_i9305-rodman01 6.0.1 MOB31E
```
1481782287452 V/SDM:InteractiveShell: Input : su --context u:r:system_app:s0 -c 'LD_LIBRARY_PATH=/vendor/lib:/system/lib:$LD_LIBRARY_PATH pm move-package de.apptiv.business.android.aldi_de null' < /dev/null
1481782289680 V/SDM:InteractiveShell: Error : Failure [-6]
```

cm_i9305-userdebug 7.1.1 NMF26O 76ae938843 test-keys
```
1481786478604 V/SDM:InteractiveShell: Input : su --context u:r:system_app:s0 -c 'LD_LIBRARY_PATH=/vendor/lib:/system/lib:$LD_LIBRARY_PATH pm move-package com.ptvag.android.adacgasprices null' < /dev/null
1481786478764 V/SDM:InteractiveShell: Error : WARNING: linker: Warning: unable to normalize ""
1481786478788 V/SDM:InteractiveShell: Error : WARNING: linker: Warning: unable to normalize ""
1481786481544 V/SDM:InteractiveShell: Error : Failure [-6]
```

**Comment by d4rken** [comment]
@noc-jfcbs Could you run `sm list-volumes all` from a root console on either device?

**Comment by d4rken** [comment]
On neither device, the external sdcard is adopted part/full, correct?
Hm and without adopting an sdcard on Android 6.0+, apps can't be moved to external storage...?

So we would have to detect this not offer the move function...

Kinda overlooked this requirement, seems obvious now...

On my Moto G3 test device I have split the external sdcard into an adopted and non adopted volume...
```
root@osprey_umts:/ # sm list-volumes all
private:179,67 mounted 04b29f89-2e63-48c8-8704-3e341478f307
private mounted null
public:179,65 mounted 0325-13E7
emulated mounted null
emulated:179,67 unmounted null
```

**Comment by noc-jfcbs** [comment]
Affirmative, external storage isn't adopted on any device. This is intentionally, and I didn't or won't adopt my cards or parts of them. I've sufficient internal storage available to run my applications from there, and I was just going to test the new features of v4.5.0 BETA.
Great that you could isolate the reason so easily. Actually, non-adopted storage was one of my initial thoughts... :-)
Do you still require me to run "sm list-volumes all" from a root console?

**Comment by d4rken** [comment]
> Do you still require me to run "sm list-volumes all" from a root console?

Would be good to confirm my suspicions.

Currently SD Maid looks up the "storage target" when trying to do the move. To fix this i think we should create a `MoveData` object which exists if moving is possible, and includes viable storage targets, then if an AppObject has no `MoveData` the options are hidden.

A bit complicated for just this case, but then in the future we could better decide for each app whether we allow moving (and it would better utilize the cool new module system i wrote for v4.5.0 😄 )

If you would like to test my fix, send mail me (support@...) and I'll give you an apk when it's done.

**Comment by noc-jfcbs** [comment]
Obviously while you were typing I amended my comment by the console above. Please check, and I apologise for the big screenshots, which are easier to handle for me (Github on PC, cell phone "stand-alone").
Happy to test - email's coming.

**Comment by noc-jfcbs** [comment]
Here it is for the "cm_i9305-userdebug 7.1.1 NMF26O 76ae938843 test-keys":
![screenshot_20161215-134108](https://cloud.githubusercontent.com/assets/21972717/21224432/7e7ade4c-c2cc-11e6-8ee2-3bd603043554.png)
