### ISSUE TITLE
v4.4.1: Root not accessible on Android Nougat 7.0 

### ISSUE THREAD

**Issue by packjpg** [d4rken/sdmaid-public#616]
Although SD Maid detects root in my device (see screenshot), it can't be enabled, I don't get any SuperSU prompt. For example, I can't stop apps from booting on startup with SD Maid (works in Rom Toolbox Pro).
http://i.imgur.com/Ax30vai.png

I think this issue is similar to one I had earlier with AdAway, as shown here:
https://github.com/AdAway/AdAway/issues/770

This is on a Nexus 6, with PureNexus Nougat rom (current stable), if it helps. Let me know if you need more info.

**Comment by d4rken** [comment]
It's not the adaway issue, SD Maid can deal with different binaries busybox/toybox and mount issues.
If something would break though it would go:
Get Root -> Try binary -> Doesn't work -> Try without root -> Binary Works -> Give up root.
Then you would read "Error" in the overview section.

Try removing SD Maid from SuperSu and reboot your device, sometimes it just gets wonky, not sure why, but it does.

If that doesn't help, please get me a debug log, see:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

Just loading the overview section while logging should suffice.

**Comment by packjpg** [comment]
Okay, guess what? I initialized the debug run, and afterwards it seems to have solved itself. Problem before was that i did not get a SuperSU prompt, and SD Maid was not already in SuperSUs list either. If you want to, you can close this issue.

**Comment by d4rken** [comment]
If you figure out it's reproduceable, just reopen and go for the debug log again.
