### ISSUE TITLE
save directory structure error

### ISSUE THREAD

**Issue by jawz101** [d4rken/sdmaid-public#618]
I emailed support ^a^t darken d0t eu my log files.

**Comment by d4rken** [comment]
```
12-16 12:12:46.062 V/SDM:InteractiveShell( 6839): Input : SDMBOX=/data/user/0/eu.thedarken.sdm/files/toybox_sdm
12-16 12:12:46.062 D/SDM:InteractiveShell( 6839): Opened(root:true)
12-16 12:12:46.064 D/SDM:InteractiveShell( 6839): runCommand(Command(commands=[$SDMBOX find -L '/data/data/com.amazon.mShop.android' -exec ls -lahd {} + >> /storage/emulated/0/pathdump#_data_data_com.amazon.mShop.android.txt]))
12-16 12:12:46.065 V/SDM:InteractiveShell( 6839): Input : $SDMBOX find -L '/data/data/com.amazon.mShop.android' -exec ls -lahd {} + >> /storage/emulated/0/pathdump#_data_data_com.amazon.mShop.android.txt
12-16 12:12:46.065 V/SDM:InteractiveShell( 6839): Input : echo 837446d0-1a23-4a1f-bf50-d600d5ffa1d1 $?
12-16 12:12:46.066 V/SDM:InteractiveShell( 6839): Input : echo 837446d0-1a23-4a1f-bf50-d600d5ffa1d1 >&2
12-16 12:12:46.066 V/SDM:InteractiveShell( 6839): Waiting for callback
```

Ah fuck. Well I removed the ls applet from SD Maids toybox but it's still used here and while SD Maid falls back to the default `ls` it doesn't support the human readable flag. k... So either add the applet again or print the data another way, e.g. `stat`.

**Comment by jawz101** [comment]
which version of Toybox do you use?  I just looked and maybe there was a bug that got fixed with ls -sh in 0.7.2

https://github.com/landley/toybox/commit/409a8e093a4ea8e0892ab302b4fd433d08f435eb

**Comment by d4rken** [comment]
This one:
https://github.com/d4rken/toybox/tree/sdmaid

You could check SD Maids binary, i think it doesn#t have the `ls` applet at the moment, so the one used is from /system somewhere.

**Comment by jawz101** [comment]
ah.  And since I have CyanogenMod which has their own version of Toybox, who knows what version they're on or what they've stripped out

**Comment by d4rken** [comment]
yeah which is why SD Maid has to ship its own binaries.
I think I'll use SD Maids main file reader tool (which uses `stat`) and then format it nicely in java before writing it back to a file.

I don't like readding LS just to use it here, especially as the ls >> txt wasn't that nice in comparison to SD Maids other routines.

**Comment by d4rken** [comment]
```
DIRECTORY  770 10078: 9997    8,00 KB   05/11/16 03:40:55 /storage/emulated/0/Android/data/com.google.android.music
DIRECTORY  770 10078: 9997    8,00 KB   05/11/16 03:40:55 /storage/emulated/0/Android/data/com.google.android.music/cache
DIRECTORY  770 10078: 9997    8,00 KB   21/01/70 04:01:31 /storage/emulated/0/Android/data/com.google.android.music/files
FILE       660 10078: 9997    8,00 KB   21/01/70 04:01:32 /storage/emulated/0/Android/data/com.google.android.music/files/._playmusicid
DIRECTORY  770 10077: 9997    8,00 KB   02/11/16 19:39:20 /storage/emulated/0/Android/data/com.google.android.apps.maps
DIRECTORY  770 10077: 9997    8,00 KB   20/10/16 21:52:03 /storage/emulated/0/Android/data/com.google.android.apps.maps/files
```

**Comment by jawz101** [comment]
Emailed another log file.  Getting another error

**Comment by d4rken** [comment]
Hm I think it's because the file already exists. Can you check?
Should we change this behavior and let SD Maid overwrite the file?

**Comment by jawz101** [comment]
Looks like that was it.  I would say overwrite or append a timestamp to the name.

**Comment by d4rken** [comment]
Timestamp is a good idea! Done.
