### ISSUE TITLE
[Feature request] Ability to access Manage Apps from within AppControl

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#620]
Every version of Android has a Manage Apps interface where the user can uninstall apps, clear their data and cache, and more.  Can you add, within AppControl, the ability to go to the appropriate page within Manage Apps for the currently selected app?

It's definitely possible, because several *lesser apps* have this functionality. :)

This will be very useful when freezing an app, because it is often desirable to clear the cache and data of an app before freezing it.  As it is currently, the user has to manually go into Manage Apps to perform that task.

**Comment by d4rken** [comment]
It's possible, but a bit hidden, long pressing the app icon will take you there.

**Comment by Gitoffthelawn** [comment]
Thanks.  At first I thought, "well, that just selects it"... then I tried long pressing on the actual icon instead of the row, and voila, it worked!

What do you think about changing it to regular press instead of long press?  Currently, regular press has no function.

**Comment by d4rken** [comment]
As of v4.5.2 regular press should start the app.

**Comment by Gitoffthelawn** [comment]
It sounds like there are 4 possible user-input scenarios:

  1. Regular press the app name
  2. Long press the app name
  3. Regular press the app icon
  4. Long press the app icon

And here are the correlating actions:
  1. Open AppControl page for the app
  2. Select the app
  3. Open Manage App for the app
  4. Run the app

It's definitely a bit confounding.  I think it may be better to have action # 3 and action # 4 reversed, although an argument could be made either way.

Also, a gray line between the icon and the app name (and package name) would make it a *little* more clear that pressing the icon itself has functions, although the cost of doing so would be a noticeable decline in appearance.

**Comment by d4rken** [comment]
It's not the app name but that whole list entry, except for the icon, that reacts.

Why would you switch 3 and 4?

**Comment by Gitoffthelawn** [comment]
> It's not the app name but that whole list entry, except for the icon, that reacts.

Yes, sorry.  It would have been better if I used "list entry" instead of "app name".

> Why would you switch 3 and 4?

Without running a usability study, I can only hypothesize that opening Manage App is a more common action than running the app.  My rationale is that the user went into AppControl to perform management tasks.  From personal experience *(n=1)*, I can report that, within AppControl, opening Manage App is a far greater need than running the app.

**Comment by d4rken** [comment]
I agree, but! other tools like Duplicates, Searcher etc. already use the "single tap on icon" action to launch (or view) the file, so we would break consistency...

Let's leave it ❓

**Comment by Gitoffthelawn** [comment]
Hmmm... I don't use those tools very often (at all?), so I was not aware.  Yes, consistency is good.  Does it make any sense to change the function in those tools, or is it important that "single tap on icon" launch (or view) the file.

If it is important, I vote to leave it, so everything is consistent.

If it is not important, then I vote to change them all, so more common action is a single tap.

There is no wrong, only good. :)
