### ISSUE TITLE
AppCleaner behave different when on root

### ISSUE THREAD

**Issue by antonio-gil** [d4rken/sdmaid-public#622]
Recently, I've started to notice that some cache files aren't being deleted, starting by Firefox's cache, actually it was after an update of SD Maid that I noticed that. Why after the update? Because the root grants are revoked after an app update (not sure if that is a common "post update effect", but it's something that happens on my device every once in a while).

Anyway, I was running SD Maid without root grants (I forgot to give it them again) and, and while I was running the AppCleaner section I noticed that some of the caches weren't being deleted. At first I thought that it was because I was running without root, so I enabled the root access to the app and run again the AppCleaner and, to my surprise, some of the apps previously listed now were absent.

So, after view which apps were absent, I noticed that they were the only ones which are on the SD (I use Apps2SD to send them to a second partition of the SD and Link them). The most peculiar thing is that, even if they are detected while "unrooted", SD Maid apparently is unable to delete the cache files (I've tried a couple of times to no avail).

As comparison: I used to use CCleaner and even if on the automatic cleanup it was unable to delete the cache of such apps, while I do the process manually, the files were deleted as expected. So, I'm not quite sure what can be causing the described issues.

Thanks in advance.

Best regards.

P.S./Edit I moved the screenshots to the lover part of the post, to avoid disrupting the text. And, by the way, the ones with "18:29" as hour are the ones without the root permissions, the ones with "18:31" are the ones with root permissions.

![AppCleaner without root](https://cloud.githubusercontent.com/assets/9835489/21300509/2a0d3436-c56a-11e6-8bb0-4cb4950e4ab6.png)

![Overview without root](https://cloud.githubusercontent.com/assets/9835489/21300510/2a0f34de-c56a-11e6-9bc3-e5040262a432.png)

![AppCleaner with root](https://cloud.githubusercontent.com/assets/9835489/21300507/2a09d7b4-c56a-11e6-9d9d-2015d5ba8be0.png)

![Overview with root](https://cloud.githubusercontent.com/assets/9835489/21300508/2a0bcc68-c56a-11e6-9d00-5ca8890e1432.png)

**Comment by d4rken** [comment]
The data from Firefox that's missing is likely private cache. Without root SD Maid can only indirectly query the system for the size of Firefox's cache. The same for deletion, SD Maid tries to indirectly force the system to delete the cache. The systems filereader does follow symbolic links by default which is why App2SD works in general.

SD Maid does not follow symbolic links in all tools. I checked and the AppCleaner and it does not follow symbolic links in all cases. It follows symlink when determining the initial parent directories , i.e. `/data/data/com.example.app`, but not for `/data/data/com.example.app/cache` (SD Maid reads files in several steps).

I just tested it and if I symlink the cache dir, the AppCleaner no longer picks it up.

Could you tell me how, e.g. Firefox, is linked in the filesystem on your device?

If you send me a mail (support@...), I could also give you a test version so we could confirm that this is indeed the cause.

**Comment by antonio-gil** [comment]
Hi!

Sorry, I was very busy these past days... I'll be posting the required information on the following couple of days.

Regards!

**Comment by antonio-gil** [comment]
Hi! Good evening.

First, sorry for the delay, I was really busy in the last week and I didn't had the time to properly give you an answer.

Secondly, well I am afraid that I can give you a proper answer to your question, I'm don't know the very exact details on how the app that I use to link the apps, and despite my effort, I can't find such details on the official website/XDA thread, but as far as I can investigate, but, on the XDA thread says that


> "Apps2SD uses a secondary partition on your SD card and uses it as another segment of internal storage. Apps2SD moves apk files, odex files, dalvik-cache (.dex) files, lib files and internal data files into this partition, which the OS mounts on boot, and creates a symbolic link in the original location. This retains the file structure that the system expects but with the bulk of the data moved to the SD card."


Besides, that information, I can tell that I'm using a secondary EXT4 partition where the data is stored as you can see [here](https://dl.dropboxusercontent.com/u/18577244/SDM/Screenshot_2016-12-19-16-23-53.png) (this link, and the following are stored on Dropbox, I fount it more convenient), where the seconary partition is mounted on `/data/sdext2` (in [this another](https://dl.dropboxusercontent.com/u/18577244/SDM/Screenshot_2016-12-19-16-29-41.png) you can see how the SD Card is partitioned).

Aditionally, in [this another](https://dl.dropboxusercontent.com/u/18577244/SDM/Screenshot_2016-12-23-10-43-25.png) is displayed which elements are linked/stored on the SD (I'm taking as example Firefox, but the other 3 apps have a  very similar configuration), and [this ones](https://dl.dropboxusercontent.com/u/18577244/SDM/Screenshot_2016-12-23-10-41-42.png)  are the paths where the data is linked (or that is what I deducted).

I hope this helps.

Best regards.

**Comment by d4rken** [comment]
Please try v4.5.5:
http://sdmaid.darken.eu/download/production/
I've made some changes to address this issue (as far as I understood it).

2016-12-24 6:24 GMT+01:00 Antonio Gil <notifications@github.com>:

**Comment by antonio-gil** [comment]
Hi!

I already updated the app and now it works as intended 😄

Thanks for such awesome work!

Best regards!
