### ISSUE TITLE
[Scheduler] [4.5.x Beta] Reboot Failing

### ISSUE THREAD

**Issue by Yowlen** [d4rken/sdmaid-public#662]
The new automatic reboot option in the scheduler isn't working. It results in a "1 Failed" notification. I'm running Android 5.1.1 on an LG Leon LTE (H345), fully rooted, w/ busybox installed, and I know the reboot terminal command works just fine. I should be able to fetch a logcat or whatever if needed.

**Comment by d4rken** [comment]
Hot or full reboot?
The full reboot option asks the system to reboot like to does after OTAs,
meaning via intent.

If you can get me a debug log from SD Maid, we might be able to add reboot
via BusyBox as fallback option.

Alternatively SD Maid in debug mode 2 and a logcat would be good too, to
see if the system complains about something.

For testing, if you turn on experimental features, the scheduler gets a
"run now" option.


Am 24.12.2016 4:59 nachm. schrieb "Yowlen" <notifications@github.com>:

The new automatic reboot option in the scheduler isn't working. It results
in a "1 Failed" notification. I'm running Android 5.1.1 on an LG Leon LTE
(H345), fully rooted, w/ busybox installed, and I know the reboot terminal
command works just fine. I should be able to fetch a logcat or whatever if
needed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/d4rken/sdmaid-public/issues/662>, or mute the thread

**Comment by Yowlen** [comment]
Full reboot. Given your explanation, I suppose it's worth noting I'm using an unofficial XenonHD ROM for my device, which is somewhat incomplete (Camera2 API not working, for example), so it's entirely possible certain internal routines such as the reboot handler you use aren't working, either. Logcat isn't spitting out anything from SD Maid as far as I can see. I enabled the Experimental Features option for the instant Scheduler thing, but I'm not sure how to enable debug mode in SD Maid or find the debug logs.

**Comment by d4rken** [comment]
Long Press the settings button for the debug menu. To set the debug mode to
2.
Also see:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug

Am 24.12.2016 5:44 nachm. schrieb "Yowlen" <notifications@github.com>:

**Comment by Yowlen** [comment]
Heh. Must've missed that when I checked the wiki. Anyway, I did that & it doesn't seem to be outputting anything. The first time I did it, the "/storage/emulated/0/Android/eu.thedarken.sdm/cache/logfiles"

**Comment by d4rken** [comment]
You open SD Maid, go into debug, press the trigger button, then kill SD Maid (force stop).
Then on next start a log should be written.

Or you set debug mode to "2" and do a normal logcat recording.

**Comment by Yowlen** [comment]
Sorry for all the trouble. I've never done a logcat before. Here ya go.
[2016-12-24-18-20-19.txt](https://github.com/d4rken/sdmaid-public/files/671994/2016-12-24-18-20-19.txt)

**Comment by d4rken** [comment]
You did well, good log.
So the system throws the error, not SD Maid.
It could be related to your ROM, but we can rule out a config issue from SD Maid by manually executing it. Try running `am start -a android.intent.action.REBOOT` in the terminal emulator app as root.

```
I/SDM:MiscWorker(13280): Initiating hard reboot (android.intent.action.REBOOT
V/SDM:InteractiveShell(13280): Input : SDMBOX=/data/data/eu.thedarken.sdm/files/toybox_sdm
D/SDM:InteractiveShell(13280): Opened(root:true)
D/SDM:InteractiveShell(13280): runCommand(Command(commands=[su --context u:r:system_app:s0 -c 'LD_LIBRARY_PATH=/vendor/lib:/system/lib:$LD_LIBRARY_PATH am start -a android.intent.action.REBOOT' < /dev/null]))
V/SDM:InteractiveShell(13280): Input : su --context u:r:system_app:s0 -c 'LD_LIBRARY_PATH=/vendor/lib:/system/lib:$LD_LIBRARY_PATH am start -a android.intent.action.REBOOT' < /dev/null
V/SDM:InteractiveShell(13280): Input : echo 592c3368-8268-457b-a8ac-56f9a7d5cf81 $?
V/SDM:InteractiveShell(13280): Input : echo 592c3368-8268-457b-a8ac-56f9a7d5cf81 >&2
W/PackageManager( 1073): Failure retrieving resources for eu.thedarken.sdm: Resource ID #0x0
V/SDM:InteractiveShell(13280): Output: Starting: Intent { act=android.intent.action.REBOOT }
V/SDM:InteractiveShell(13280): Error : java.lang.NullPointerException: storage == null
V/SDM:InteractiveShell(13280): Error : 	at android.os.Parcel.readException(Parcel.java:1552)
V/SDM:InteractiveShell(13280): Error : 	at android.os.Parcel.readException(Parcel.java:1499)
V/SDM:InteractiveShell(13280): Error : 	at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2495)
V/SDM:InteractiveShell(13280): Error : 	at com.android.commands.am.Am.runStart(Am.java:766)
V/SDM:InteractiveShell(13280): Error : 	at com.android.commands.am.Am.onRun(Am.java:305)
V/SDM:InteractiveShell(13280): Error : 	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
V/SDM:InteractiveShell(13280): Error : 	at com.android.commands.am.Am.main(Am.java:97)
V/SDM:InteractiveShell(13280): Error : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
V/SDM:InteractiveShell(13280): Error : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
V/SDM:InteractiveShell(13280): Output: 592c3368-8268-457b-a8ac-56f9a7d5cf81 1
V/SDM:InteractiveShell(13280): Error : 592c3368-8268-457b-a8ac-56f9a7d5cf81
D/SDM:InteractiveShell(13280): runCommand(...): Command.Result(exitcode=1)
```

**Comment by Yowlen** [comment]
Yep. Same error as the logcat. Definitely a ROM issue.

**Comment by d4rken** [comment]
and typing "reboot" into the terminal as root works?

**Comment by d4rken** [comment]
Does the HOT reboot option work?

**Comment by Yowlen** [comment]
Yes, reboot terminal command works. The Hot Reboot in SD Maid also works.

**Comment by d4rken** [comment]
So you would agree that it's not a bug in SD Maid?
Then lets add the reboot binary as "fallback" option to try if this error happens, and make this an enhancement 😀 ?

**Comment by Yowlen** [comment]
Yep. Agreed. Buggy ROM is buggy. The fallback option would be great. lol

**Comment by d4rken** [comment]
If you'd like to test this, send me a mail.
