### ISSUE TITLE
False positive in CorpseFinder: ulmon

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#664]
CorpseFinder is recommending the deletion of `/storage/emulated/0/Android/data/com.ulmon.android/files` and `/storage/emulated/0/Android/data/com.ulmon.android/files/deviceToken` even though *CityMaps2Go* by Ulmon is installed.

**Comment by d4rken** [comment]
This app?
https://play.google.com/store/apps/details?id=com.ulmon.android.citymaps2go

It would seem the dev is naming the folder wrong, files are `Android/data` should be put in a folder named after the packagename, only then can the system remove them on uninstall.

Maybe an attempt to share app data between multiple versions of CityMaps2Go?
Should we add a database entry for all versions from that developer?

https://play.google.com/store/apps/dev?id=8207497077477903171

**Comment by Gitoffthelawn** [comment]
Yes, that is the correct app.

I agree it is most probable that it is an attempt to share app data between multiple apps by the same developer.  If you like, send them an email and ask.  Otherwise, probably want to keep that folder if any of their related apps are installed.

**Comment by d4rken** [comment]
I installed it and can't get it to create this file, are you sure it's that app?

**Comment by Gitoffthelawn** [comment]
I have the paid version, so likely that is why it saves a deviceToken.

**Comment by d4rken** [comment]
Added the free version too, just in case (I didn't use it very much).
