### ISSUE TITLE
No App found, to open this file type

### ISSUE THREAD

**Issue by Joly0** [d4rken/sdmaid-public#667]
Everytime i try to open a file, i get the error message above. I already tried to change the default app for open jpg or mp3 but nothing helps. I am on android 7.1.1

**Comment by d4rken** [comment]
What apps do you have installed? On my Pixel I have VLC installed and it used to open `*.mp3` successfully.

**Comment by Joly0** [comment]
I have Poweramp for my Music, MxPlayer for Videos and Piktures for all my Photos. I tried to do it with Vlc but it doesnt work, it still says the same as above

**Comment by d4rken** [comment]
Hm can reproduce on a Nexus9@7.0.0.
What device do you have?

**Comment by Joly0** [comment]
I have a oneplus 2 with aicp rom

**Comment by d4rken** [comment]
I think I've got a solution. If you would like to help me test it, send me a short mail to support@darken.eu

**Comment by d4rken** [comment]
https://www.google.de/search?q=Android+N+FileProvider

https://www.google.de/search?q=Android+File+Uri+exposed
