### ISSUE TITLE
Clutterreport: /storage/external_SD/Android/data/com.maxmpz.audioplayer (FP)

### ISSUE THREAD

**Issue by brokenguy1** [d4rken/sdmaid-public#669]
### Target
Target: `/storage/external_SD/Android/data/com.maxmpz.audioplayer`
Prefix-free: `com.maxmpz.audioplayer`
Path-prefix: `/storage/external_SD/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
~~Appname: `Poweramp`~~
~~Packagename: `com.maxmpz.audioplayer`~~
~~Version: `alpha-build-703-play (703)`~~

### SD Maid
Version: `4.5.5 (40505)`

### Device
Fingerprint: `lge/x10_pp_vzw/x10:5.1.1/LMY47V/153011324cc94:user/release-keys`

**Comment by d4rken** [comment]
Ownership is correct tho?
