### ISSUE TITLE
[KitKat/4.4.2] Scheduler not executing.

### ISSUE THREAD

**Issue by JORGETECH** [d4rken/sdmaid-public#672]
I was trying the scheduler feature which is quite nise, the first days it ran correctly in the correct time but recently for unkown reasons it is not executing, I even tried making the app resident in memory using Xposed App Settings but I still have no luck.

It surprised me that when I see the SD Maid app on the running apps it does not have a service running for the scheduler, I don't know if that is the issue, I need some help here.

My device:
-----------------
Huawei Ascend G6
Android 4.4.2 (EMUI 3.0)
Rooted?: Yes (KingRoot binary 3.4.0)

**Comment by d4rken** [comment]
The scheduler works by setting an alarm. When the alarm is triggered, it will send and intent containing the specified tasks. This intent will then start SD Maids main service which executes the tasks.

The alarm is canceled on reboot and has to be restored by SD Maids on boot receiver. The alarm may also be canceled if SD Maid is force-stopped. It will then be only restored after starting SD Maid again or after a reboot.

The only known issues I'm aware of is related to SD Maid being moved to the sdcard.

https://github.com/d4rken/sdmaid-public/wiki/Scheduler#error-scheduler-loosing-its-settings

**Comment by JORGETECH** [comment]
I actually had SD Maid moved to the SD card, it would not surprise me that is the issue since Android KitKat really broke SD card access. I will report after testing.

**Comment by JORGETECH** [comment]
Moved to internal storage and updating it to the las version fixed it.

**Comment by d4rken** [comment]
Good to hear it's working. I'll assume it was the issue I linked above and close this.
