### ISSUE TITLE
Clutterreport: /storage/self (new)

### ISSUE THREAD

**Issue by seandrea** [d4rken/sdmaid-public#677]
### Target
Target: `/storage/self`
Prefix-free: `/storage/self`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `SD Maid`
Packagename: `eu.thedarken.sdm`
Version: `4.5.7 (40507)`

### Current owners
None

### SD Maid
Version: `4.5.7 (40507)`

### Device
Fingerprint: `samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CPJ6:user/release-keys`

**Comment by seandrea** [comment]
I need to know if i can access this directory and config r/w

**Comment by d4rken** [comment]
The clutter reports are for updating SD Maids database, not file help. Also SD Maid does not own the file `/storage/self`
