### ISSUE TITLE
Root for unrooted device + SU link

### ISSUE THREAD

**Issue by seandrea** [d4rken/sdmaid-public#678]
Add support for user to root an unrooted device.
Change mount/remount properties to inc. format utility - change owner/take ownership of directory path up to top level (*/) poss partition mngr. Support SU privelidges and enable link.

**Comment by seandrea** [comment]
With ability for user to make changes with poss result of bricking device, include sys image in recovery partition by default.

**Comment by d4rken** [comment]
Rooting a device is outside of SD Maids scope and also not allowed on Google Play.
