### ISSUE TITLE
Clutterreport: /init.usb.configfs.rc (new)

### ISSUE THREAD

**Issue by renownprodigy** [d4rken/sdmaid-public#679]
### Target
Target: `/init.usb.configfs.rc`
Prefix-free: `/init.usb.configfs.rc`
Path-prefix: ``
Type: `FILE`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `AudioConnectionService`
Packagename: `com.samsung.android.sdk.professionalaudio.app.audioconnectionservice`
Version: `2.1.00 (210000000)`

### Current owners
None

### SD Maid
Version: `4.5.7 (40507)`

### Device
Fingerprint: `Verizon/hero2qltevzw/hero2qltevzw:6.0.1/MMB29M/G935VVRU4API3:user/release-keys`

**Comment by d4rken** [comment]
The root location is currently not yet supported, but I also doubt that that app owns the file.
