### ISSUE TITLE
Clutterreport: /storage/emulated/0/CartoonHD/SAVE/mfav_save.bin (new)

### ISSUE THREAD

**Issue by ddsigvertsen** [d4rken/sdmaid-public#681]
### Target
Target: `/storage/emulated/0/CartoonHD/SAVE/mfav_save.bin`
Prefix-free: `CartoonHD/SAVE/mfav_save.bin`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Cartoon HD`
Packagename: `com.rogercar.comboplay`
Version: `3.0.2 (302)`

### Current owners
None

### SD Maid
Version: `4.5.7 (40507)`

### Device
Fingerprint: `lge/z_tmo_us/zee:4.4.2/KOT49I.D95920t/D95920t.1439786314:user/release-keys`

**Comment by ddsigvertsen** [comment]
I am not sure what to do with this? Am I making a new path direct to the data source?

**Comment by d4rken** [comment]
@ddsigvertsen No need to do anything from your end. I'll add this to SD Maids database with the update and SD Maid will be able to include this in the scans.

For future reference, reporting the base folder is recommended, i.e. `/storage/emulated/0/CartoonHD`.
