### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/com.bel.android.dspmanager-1.0.apk (FP)

### ISSUE THREAD

**Issue by Donovan1974** [d4rken/sdmaid-public#692]
### Target
Target: `/storage/emulated/0/Download/com.bel.android.dspmanager-1.0.apk`
Prefix-free: `Download/com.bel.android.dspmanager-1.0.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
~~Appname: `Downloads`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `null (0)`~~

~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `6.0.1 (23)`~~

### SD Maid
Version: `4.5.9 (40509)`

### Device
Fingerprint: `ZTE/P895T20_MPCS/urd:6.0.1/MMB29M/20161030.150238:user/release-keys`

**Comment by pticon76** [comment]
5c616c8
