### ISSUE TITLE
Don't vibrate when double tapping back to exit if 'Vibrate on touch' is disabled

### ISSUE THREAD

**Issue by FatOrangutan** [d4rken/sdmaid-public#693]
I am on Xperia XA, Android v6.0, SD Maid v4.5.9.

STR:

1) In SD Maid, make sure 'Press twice to exit' is checked. (Off-topic, but maybe this should be called 'Press back twice to exit'?)
2) Go to (Phone / System) Settings > Sound and Notification > Other sounds and disable 'Vibrate on touch.'
3) Switch back to SD Maid, and then try and exit it by double tapping back.

ER: Phone shouldn't vibrate. Solid Explorer has double-tap-to-exit too, but it doesn't make any vibrations.

AR: it vibrates.

This seems a little like it is overriding user's system-wide settings. Could you confirm if this is intentional? 

Thanks.

**Comment by d4rken** [comment]
No intential overriding, the code just doesn't use any "vibrate on touch" routines, just the normal vibrate methods, which is why it's unaffected by the systems settings.

I'll look into either using different system routines, or if we can manually check the system setting.

**Comment by FatOrangutan** [comment]
Hi, could you tell me if the 4.6.0 update was pulled or something? It has been ~10 days since the changelog update, but Play Store still says that 4.5.9 is the latest, across all my devices.

Thanks.

**Comment by d4rken** [comment]
> https://github.com/d4rken/sdmaid-public/blob/master/CHANGELOG.md

Not pulled but v4.6.0 is a beta only release. It's stable from what I can see but I still need to make a few changes. Just swamped with work at the moment. I think I'll get v4.6.1 done this week which can then go into production.

**Comment by FatOrangutan** [comment]
>v4.6.0 is a beta only release

Damn, I have no idea how I managed to miss that in the changelog. Sorry for the bother.

>swamped with work at the moment

No worries, take your time :)
