### ISSUE TITLE
Should we show "/data" without root?

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#700]
We could show the base size of "/data" in the StorageAnalyzer, even without root.

Would this be useful? When pressing it we would have to show something like "Requires root".

Currently it's just omitted on unrooted devices.

**Comment by d4rken** [comment]
![2017-01-14 13 57 02](https://cloud.githubusercontent.com/assets/1439229/21995916/cedf0a06-dc27-11e6-908b-08dbe20fef69.png)
![screenshot_20170113-062129](https://cloud.githubusercontent.com/assets/1439229/21995915/ceddfc42-dc27-11e6-9b11-3b38b954132f.png)

**Comment by Gitoffthelawn** [comment]
If available/used is shown, that is useful information even on unrooted devices.

**Comment by d4rken** [comment]
Done.
![2017-01-28 02 12 35](https://cloud.githubusercontent.com/assets/1439229/22393488/cd68aaf4-e507-11e6-988c-6a065ed1cbd1.png)
![2017-01-28 02 12 28](https://cloud.githubusercontent.com/assets/1439229/22393489/cd6d82e0-e507-11e6-9ca7-649ea3d47bf7.png)
