### ISSUE TITLE
Clutterreport: /storage/2A84-0BFA/.Hnc/AFonts/.HANSymbol.ttf.cached.TFM-7-0-140912-samsung.160523(R322302) (FP)

### ISSUE THREAD

**Issue by sethbergman** [d4rken/sdmaid-public#714]
### Target
Target: `/storage/2A84-0BFA/.Hnc/AFonts/.HANSymbol.ttf.cached.TFM-7-0-140912-samsung.160523(R322302)`
Prefix-free: `.Hnc/AFonts/.HANSymbol.ttf.cached.TFM-7-0-140912-samsung.160523(R322302)`
Path-prefix: `/storage/2A84-0BFA/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `HTML Viewer`
Packagename: `com.android.htmlviewer`
Version: `1.1.10 (111000000)`

### Current owners
~~Appname: `Hancom Office Viewer`~~
~~Packagename: `com.hancom.office.viewer`~~
~~Version: `7.0.160523 (322302)`~~

### SD Maid
Version: `4.5.9 (40509)`

### Device
Fingerprint: `samsung/j1xqltetfnvzw/j1xqltetfnvzw:6.0.1/MMB29M/S120VLUDU1APFA:user/release-keys`

**Comment by d4rken** [comment]
The folder is not owned by th HTML Viewer app.
