### ISSUE TITLE
Clutterreport: /storage/emulated/0/OniUpdateSoftware (new)

### ISSUE THREAD

**Issue by Thefurdazamadafur** [d4rken/sdmaid-public#716]
### Target
Target: `/storage/emulated/0/OniUpdateSoftware`
Prefix-free: `OniUpdateSoftware`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `AutoEmodeTest`
Packagename: `com.android.zte.AutoEmodeTest`
Version: `1.0 (1)`

### Current owners
None

### SD Maid
Version: `4.5.9 (40509)`

### Device
Fingerprint: `ZTE/P895T20_MPCS/urd:6.0.1/MMB29M/20160622.141326:user/release-keys`

**Comment by d4rken** [comment]
Can't confirm. Got any more info?
