### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/org.videolan.vlc (FP)

### ISSUE THREAD

**Issue by kiulkiel** [d4rken/sdmaid-public#720]
### Target
Target: `/storage/emulated/0/Android/data/org.videolan.vlc`
Prefix-free: `org.videolan.vlc`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Video Player`
Packagename: `com.samsung.android.video`
Version: `7.0.62 (706201100)`

### Current owners
None

### SD Maid
Version: `4.5.9 (40509)`

### Device
Fingerprint: `Verizon/heroqltevzw/heroqltevzw:6.0.1/MMB29M/G930VVRU4API3:user/release-keys`

**Comment by d4rken** [comment]
Nope.

**Comment by kiulkiel** [comment]
Previous files such as this were on a sd card that someone remotely gained a dim rights to my phone and computer. I didn't notice right away but all my new saves and data were being redirected into a file that I couldn't access. All my passwords were changed and I couldn't unlock phone screen. Had to reboot phone and now I have found these files but not sure how to save or get them back. I have around 200 files not sure what all of them are and don't want to send them all here so if you can help I would highly appreciate it. Thanks

**Comment by kiulkiel** [comment]
Nope what? Can't help or any suggestions

**Comment by d4rken** [comment]
Nope everything.

The clutter reporter tool is for[ false positives when detecting owner ship](https://github.com/d4rken/sdmaid-public/wiki/CorpseFinder#reporting-false-positives), i.e. when SD Maid got it wrong.
The data dir of the VLC player app has nothing to do with the samsung video player.

> Previous files such as this were on a sd card that someone remotely gained a dim rights to my phone and computer.

It's highly unlikely that someone remotely gained access to your phone. Almost all devices are compromised by running malicious code knowingly or unknowingly.

>  I didn't notice right away but all my new saves and data were being redirected into a file that I couldn't access. All my passwords were changed and I couldn't unlock phone screen. Had to reboot phone and now I have found these files but not sure how to save or get them back.

Sounds remotely like a cryptolocker type of malware, but I'm just guessing here.

> I have around 200 files not sure what all of them are and don't want to send them all here so if you can help I would highly appreciate it. Thanks

The clutter reporter tool is used to help SD Maid figure out stuff, not to help users figure out stuff. You use when when you already know who owns what and SD Maid doesn't, not vice versa.

Nothing of this sounds like it's within SD Maids scope or job description. SD Maid is neither an anti-malware tool, nor a file recovery tool.
