### ISSUE TITLE
Latest release does not always delete orphaned apk files ... or left over empty folders.

### ISSUE THREAD

**Issue by HerborenInVlammen** [d4rken/sdmaid-public#725]
Hello:

I have noticed that the latest release does not always delete orphaned apk files left over from uninstalled apps.  It is also occasionally leaving empty folders left over from uninstalled apps even though it is set to do so. My device is rooted.

For example, I tried out mobisystems Office suite, did not like it and so uninstalled it.  I ran Sdmaid pro, and then viewed the "/root/data/app" folder and there were several folders w/ apks left from the install that Sdmaid did not remove.  The same goes for the ""/root/data/data" folders.

So, I then reinstalled and then uninstalled to confirm, and this time Sdmaid deleted them all. So.... I repeated the process and again it did not delete them.  The process was identical each time, but the results of running Sdmaid were not.

I notice this is very prevalent with manually installed apps, and less so from the play store.  With manually installed apks, it is almost fully replicable.  I.e., it happens every time on my device, but I manually install very rarely and so do not want to say it is a constant.  

Note again that I only began noticing this with the latest release.

Thanks :)

**Comment by d4rken** [comment]
* What's the latest release for you, v4.5.9?
* What device?
* What ROM?

> For example, I tried out mobisystems Office suite, did not like it and so uninstalled it. 

Uninstalled how? Through the system or through SD Maid's AppControl?

> I ran Sdmaid pro, and then viewed the "/root/data/app" folder and there were several folders w/ apks left from the install that Sdmaid did not remove. The same goes for the ""/root/data/data" folders.

Ran which tools? "SD Maid Pro" is a collection of tools.

Please elaborate.

**Comment by HerborenInVlammen** [comment]
Sorry :)  That was a little vague.

Yes, Sdmaid Pro version 4.5.9
ASUS Zenphone2 ASUS_Z00AD
Android 5
Uninstalled via system (googleplay store) for all apps including the manually installed apks.  Note that the manually installed apps were cloned apks, though that should not make a difference to Sdmaid should it?

Ran via quick access w/ "scan and clean in single pass" enabled:
Corpsefinder
SystemCleaner
AppCleaner

Also, is it normal to have to restart Sdmaid Pro in order to have items in quickaccess removed?  You do not have to restart to add them, but you do have to restart to have them removed from quickaccess after unchecking them.

**Comment by d4rken** [comment]
Ok, now we are getting somewhere 👍 

> Uninstalled via system (googleplay store) for all apps including the manually installed apks. Note that the manually installed apps were cloned apks, though that should not make a difference to Sdmaid should it?

If the files are left behind when using the system uninstaller, then this is either a bug in the ROM or caused by them being "cloned" apps. But you are right, the CorpseFinder should be able to pick them up in either case.

> Ran via quick access w/ "scan and clean in single pass" enabled:
> Corpsefinder
> SystemCleaner
> AppCleaner

For further testing you will just need to run the CorpseFinder, the other tools are not responsible for these cases.

> Also, is it normal to have to restart Sdmaid Pro in order to have items in quickaccess removed or added? You do have to restart to have them enabled or removed from quickaccess after checking/unchecking them in quick access settings.

It's normal, the page only checks these settings when being created, I can look into this at some point, feel free to make an enhancement ticket for this if you want.

> Finally, may one use your support email to report bugs, or must it be done through git? It would be a lot easier to just email bug reports from within SDmaid.

You may, as I'd rather have any bug report than no bug report, but GitHub is much easier to manage. Important information tends to get drowned in my inbox.

Anyways to further troubleshoot this issue, lets start with some details on the corpses. Can you make a few screenshots or a use the explorers [save directory structure](https://github.com/d4rken/sdmaid-public/wiki/Explorer#save-directory-structure) to show me the corpses that should be detected? I'm mainly interested in pathes+names and permissions.

On a side note, you did enable the CorpseFinder filters for those locations in the settings right?

**Comment by HerborenInVlammen** [comment]
I will do the screen shots next time I enounter it.  
It may take a few days (or a week or two) as I have to go to work (I work in the oilpatch and go for two week stints and almost never turn on my phone... no reception).  Yes, I did enable the filters.

Thank you for such excellent support, and for the best cleaning app BY FAR!!!  It was the best $2.29 CA bucks I have spent for an app.  :)

I am going to update my review (which is pretty good and 5*) to mention how quick you reply and so on.  It is rare.

**Comment by d4rken** [comment]
When it occurs again, also consider recording the corpsefinder scan in a log, it's a bit more work but if the screenshots don't 💡 me, then we will need a log anyways 😉 .

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by HerborenInVlammen** [comment]
Hi Again:

I have been watching this issue carefully, and to be honest, I have not had a repeat of the issue.  I have gone as far as to purposely install a load of apks manually, use them and then uninstall them.  Only once did sdmaid not clean a corpse under /data/data, and it could not be cleaned manually either, but a reboot made it go away. 

So, I will keep watching, but as it stands it seems like a one-off during one very long session, as sdmaid seems to be doing its job.

Cheers

**Comment by d4rken** [comment]
Ok, just reopen this ticket if anything comes up again.
