### ISSUE TITLE
Clutterreport: /storage/3A45-0800/ScanWritrPro/.thumbs/1452160352738-original.crop (new)

### ISSUE THREAD

**Issue by cavess71** [d4rken/sdmaid-public#729]
### Target
Target: `/storage/3A45-0800/ScanWritrPro/.thumbs/1452160352738-original.crop`
Prefix-free: `ScanWritrPro/.thumbs/1452160352738-original.crop`
Path-prefix: `/storage/3A45-0800/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `ScanWritr`
Packagename: `com.vanaia.scanwritr`
Version: `2.7.3 (56)`

### Current owners
None

### SD Maid
Version: `4.5.9 (40509)`

### Device
Fingerprint: `lge/ph1_spr_us/ph1:6.0.1/MMB29M/1629312202df9:user/release-keys`

**Comment by d4rken** [comment]
@cavess71 What else is in the `ScanWritrPro` folder? Does it contain stuff the user might want to keep without the app?

**Comment by d4rken** [comment]
Added & flagged as keeper.
