### ISSUE TITLE
cleaning empty directory

### ISSUE THREAD

**Issue by igoivo** [d4rken/sdmaid-public#731]
Please, add a possibility to remove empty directories one by one (I.e. when one need to clean only few empty directories, but not all of them as it is now).

**Comment by d4rken** [comment]
You can already remove any file individually.
Just click the info icon on the empty directories filter in the SystemCleaner tool and then press the directories you want to delete.

Also see:
https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner

**Comment by d4rken** [comment]
I think this is solved?
