### ISSUE TITLE
Clutterreport: /storage/emulated/legacy/cabotEL.log (new)

### ISSUE THREAD

**Issue by MarkBurchard** [d4rken/sdmaid-public#747]
### Target
Target: `/storage/emulated/legacy/cabotEL.log`
Prefix-free: `cabotEL.log`
Path-prefix: `/storage/emulated/legacy/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Find MyHeadset™`
Packagename: `com.plantronics.findmyheadset`
Version: `1.3 (4)`

### Current owners
None

### SD Maid
Version: `4.6.2 (40602)`

### Device
Fingerprint: `Verizon/d2vzw/d2vzw:4.4.2/KOT49H/I535VRUDNE1:user/release-keys`

### Comment
`seems to be the GPS log for the find by last known connected location function (BackTrack).  it seems to max out at ~30MB so Find MyHeadset must be trimming it. 30MB is a bit large for a text log file though.  mine has entries dating back nearly a year, much longer than can be seen in the BackTrack function of the app.  Even worse, you can manually delete location history in the application settings which will clear the list in the application GUI but does not actually trim the physical log file at all. it would be really nice to be able to either cat have no into this file or trim it back to a reasonable date or number of entries or size but I'm not sure how complicated it would be to figure out exactly where to truncate it. deleting a log is not the best solution either because there is possibly data in the log file that the user might need the app to have available. I guess I should really file a bug with Plantronics about this but I thought I'd go ahead and report the ownership of the file to you. thanks!`

**Comment by MarkBurchard** [comment]
s/"cat have no"/"cat /dev/null >"/g

**Comment by d4rken** [comment]
Thanks for the report @MarkBurchard. You marked this one a "keeper" is that a missclick? As I would say this is not a file that the user is interested in keeping after the "FindMyHeadset" app has been uninstalled.

>but I'm not sure how complicated it would be to figure out exactly where to truncate it.

Not overly complicated but doing such specific work as trimming to log files of specific apps to specific lengths is outside of SD Maids scope. I agree that this likely warrants a bug ticket for the plantronic devs.

> deleting a log is not the best solution either because there is possibly data in the log file that the user might need the app to have available.

Are you certain of that? From an app developers perspectiv, putting data my app needs in a `.log` file on the sdcard seems insane. I would wager that this is just debug output and could likely be safely deleted. If you agree or could confirm somehow that deleting the file has no negative impact on the app then this is something that could be added under the AppCleaners "Hidden Cache" filter.

**Comment by d4rken** [comment]
Did some googeling and found sample data from that file. I'm pretty sure it's just log data. I'll add this to the AppCleaners hidden-caches filter too.

Nice find, thanks!
