### ISSUE TITLE
Clutterreport: /storage/emulated/0/obb (new)

### ISSUE THREAD

**Issue by sithsupersu** [d4rken/sdmaid-public#749]
### Target
Target: `/storage/emulated/0/obb`
Prefix-free: `obb`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `6.0.1 (23)`

### Current owners
None

### SD Maid
Version: `4.6.2 (40602)`

### Device
Fingerprint: `samsung/on5ltemtr/on5ltemtr:6.0.1/MMB29K/G550T1UVS2APL1:user/release-keys`

**Comment by d4rken** [comment]
`/storage/emulated/0/Android/obb` would have been made by the system. This folder is made by some app.
