### ISSUE TITLE
Clutterreport: /storage/emulated/0/xbrowser

### ISSUE THREAD

**Issue by Crystal-RainSlide** [d4rken/sdmaid-public#751]
### Target
Target: `/storage/emulated/0/xbrowser`
Prefix-free: `xbrowser`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `X浏览器`
Packagename: `com.mmbox.xbrowser`
Version: `2.0.6 (199)`

### Current owners
None

### SD Maid
Version: `4.6.2 (40602)`

### Device
Fingerprint: `Xiaomi/cm_markw/markw:6.0.1/MOB31K/b3586e376a:userdebug/test-keys`

### Comment
`There are useful items inside , which belongs to this app .`

**Comment by Crystal-RainSlide** [comment]
Thanks~

**Comment by d4rken** [comment]
Thanks for the report.
Improving SD Maid one report at a time 👍 

Teaching SD Maid owner ship improves actions in all tools!
