### ISSUE TITLE
Manually performing each action in SystemCleaner confuses it

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#753]
**SDMaid 4.5.9**

Steps to reproduce:
 1. Run SystemCleaner.
 2. Manually delete each category in the results.
 3. Notice that SystemCleaner still thinks there is more to clean.

This issue may be present in the other modules as well.

**Comment by d4rken** [comment]
Hm can't reproduce.

We are on the SystemCleaner page.
So I let it scan, then I go through the main list (not details), I click each list item (e.g. empty dirs) until all items in the list are gone.
Then the list is empty and the button switches.

![2017-02-20 11 31 31](https://cloud.githubusercontent.com/assets/1439229/23123500/e9167402-f768-11e6-98d8-29561fe58226.png)
![2017-02-20 11 30 47](https://cloud.githubusercontent.com/assets/1439229/23123502/e91b91da-f768-11e6-9315-a706a087a905.png)
![2017-02-20 11 30 41](https://cloud.githubusercontent.com/assets/1439229/23123501/e91aebe0-f768-11e6-86f2-1f2414a81a43.png)

**Comment by Gitoffthelawn** [comment]
Hmmm....

Sounds like you are doing everything right, my friend. :)

Did SystemCleaner report more than a single category of items to clean?

When the issue happened for me, there were about 6 or 7 categories that required cleaning, IIRC.

**Comment by d4rken** [comment]
Yeah tried it when there were ~5 entries (just forgot to make the screenshots then 😉 ).
Maybe this is a race condition? Is it reproducable on your device?

**Comment by Gitoffthelawn** [comment]
I just tried it again on the same device.  It did *not* reproduce.  I also wonder if it is a race condition.

**Comment by d4rken** [comment]
Had a quick look at the code, but can't see anything obvious. Without a way to reproduce...

On a side note, CorpseFinder,SystemCleaner, AppCleaner share the same code to update the FAB, so if there is a racecondition issue here, all 3 UIs should experience it.

**Comment by Gitoffthelawn** [comment]
I'll keep an eye on it and see if it happens again.  I don't recall it happening in the past.
