### ISSUE TITLE
Question: Any need to reboot device after running any of the SDMaid modules?

### ISSUE THREAD

**Issue by Gitoffthelawn** [d4rken/sdmaid-public#754]
Self explanatory question.

Your answer may be worthy of inclusion in SDMaid's help.

**Comment by d4rken** [comment]
Like device reboot? A few in AppControl tasks, from the top of my head:

* freezing apps (if the normal way doesn't work)
* uninstalling system apps

SD Maid should display a popup if reboot is necessary... not sure if this happens with system uninstall... but then again this is usually only needed with system uninstalls if we remove the apk from `/system` not a potential update apk from `/data`...

**Comment by Gitoffthelawn** [comment]
Thanks.

Correct, I was referring to device reboot.  I updated the title to make it more clear.

Outside of AppControl, can you think of any SDMaid modules that might require a device reboot?

**Comment by d4rken** [comment]
Nope.

**Comment by axeker11** [comment]
d4rken

**Comment by Gitoffthelawn** [comment]
Great.  Thanks.

Based on your statements, here's a summary you may find helpful to add to the wiki/help/docs:

*"There is no need to reboot your device after cleaning it with SDMaid's CorpseFinder, SystemCleaner, or AppCleaner modules.  The only exceptions are when using AppCleaner to (1) uninstall system apps or (2) freeze regular apps using the non-traditional method."*

That leaves one other case we didn't cover: is rebooting the device necessary when **freezing** a system app?

**Comment by d4rken** [comment]
> That leaves one other case we didn't cover: is rebooting the device necessary when freezing a system app?

Not just because it's a system app, only when the normal freeze method didn't work any SD Maid had to use a fallback option (same as with user apps). Fallback option works by not setting the state through a command, but changing the app state file  (which normally would be done my command, not via direct edits).

**Comment by d4rken** [comment]
Where do you think this statement should be added?

**Comment by Gitoffthelawn** [comment]
This would be a good location: https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions

**Comment by d4rken** [comment]
It's not a frequently asked question though 😉

**Comment by Gitoffthelawn** [comment]
LOL... I was thinking the same thing. 😏  But I still feel like it's an appropriate place.  Technically, it's more of a "miscellaneous asked question by an inquisitive user". 😃

**Comment by d4rken** [comment]
Need to keep the FAQs short and sweet though so people can still browse through it.
But lets take this ticket as task to check whether SD Maid displays a "Reboot necessary" when it's necessary.
