### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.flurvApp.android (FP)

### ISSUE THREAD

**Issue by jpzex** [d4rken/sdmaid-public#755]
### Target
Target: `/storage/emulated/0/Android/data/com.flurvApp.android`
Prefix-free: `com.flurvApp.android`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Flurv`
Packagename: `com.flurv.android`
Version: `4.23.2 (435)`

### Current owners
None

### SD Maid
Version: `4.6.3 (40603)`

### Device
Fingerprint: `motorola/falcon_retuglb/falcon_umts:5.1/LPB23.13-58/58:user/release-keys`

### Comment
`this is in /storage/emulated/0/Android/data and belongs to Flurv`

**Comment by d4rken** [comment]
Thanks, false positive, due to not matching the package name. Seems the dev manually specified the name?

Anyways, easyfix, next update 👍

**Comment by jpzex** [comment]
Okay (: 👌
