### ISSUE TITLE
Clutterreport: /storage/extSdCard/混蛋/none/惡作劇的貓🐱.mp4 (new)

### ISSUE THREAD

**Issue by chungshing1949** [d4rken/sdmaid-public#756]
### Target
Target: `/storage/extSdCard/混蛋/none/惡作劇的貓🐱.mp4`
Prefix-free: `混蛋/none/惡作劇的貓🐱.mp4`
Path-prefix: `/storage/extSdCard/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `ADM`
Packagename: `com.dv.adm`
Version: `5.1.2 (51268)`

### Current owners
None

### SD Maid
Version: `4.6.3 (40603)`

### Device
Fingerprint: `samsung/gtesltezt/gtesltetw:5.1.1/LMY47X/T3777ZTU1APL1:user/release-keys`

**Comment by d4rken** [comment]
This is too specific file and it doesn't have anything to do with the suggested owner either.
