### ISSUE TITLE
Clutterreport: /storage/emulated/0/Smart AudioBook Player Backup (new)

### ISSUE THREAD

**Issue by RedMaxKr** [d4rken/sdmaid-public#767]
### Target
Target: `/storage/emulated/0/Smart AudioBook Player Backup`
Prefix-free: `Smart AudioBook Player Backup`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Smart AudioBook Player`
Packagename: `ak.alizandro.smartaudiobookplayer`
Version: `3.2.2 (14252)`

### Current owners
None

### SD Maid
Version: `4.6.3 (40603)`

### Device
Fingerprint: `google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys`

**Comment by kiulkiel** [comment]
that might be mine. I had messed up phone and it got rebooted. I think
there might be more just haven't had a chance to see what all I've lost.
Thanks :)

**Comment by kiulkiel** [comment]
On 2nd look that device name doesn't match mine but product does. And a
tmobile contract maybe was mine but hadn't even looked yet. Let me know.
Thanks again

**Comment by d4rken** [comment]
@kiulkiel What are you talking about?
