### ISSUE TITLE
Clutterreport: /storage/emulated/0/RedditEmotes

### ISSUE THREAD

**Issue by hasnogames** [d4rken/sdmaid-public#778]
### Target
Target: `/storage/emulated/0/RedditEmotes`
Prefix-free: `RedditEmotes`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `PonyMotes`
Packagename: `com.dinsfire.ponymotes`
Version: `1.50 (150)`

### Current owners
None

### SD Maid
Version: `4.6.3 (40603)`

### Device
Fingerprint: `lge/g2_open_com/g2:5.0.2/LRX22G/151061918340a:user/release-keys`

**Comment by d4rken** [comment]
Are you sure? Filedir is `RedditEmotes` and the app name is `PonyMotes`. Possibly, just counter intuitive.

**Comment by d4rken** [comment]
Can't confirm this one.
