### ISSUE TITLE
Clutterreport: /storage/B434-9EDE/UCDownloads

### ISSUE THREAD

**Issue by kprkpr** [d4rken/sdmaid-public#781]
### Target
Target: `/storage/B434-9EDE/UCDownloads`
Prefix-free: `UCDownloads`
Path-prefix: `/storage/B434-9EDE/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
None

### SD Maid
Version: `4.6.3 (40603)`

### Device
Fingerprint: `mediatek/cm_mt6582/mt6582:6.0.1/MOB31E/829a960df6:userdebug/test-keys`

### Comment
`Downloads folder `

**Comment by d4rken** [comment]
Need a target app for mapping.

**Comment by d4rken** [comment]
Improved mapping for all the different UC apps.
