### ISSUE TITLE
Receiver Manager failed

### ISSUE THREAD

**Issue by JonnyTech** [d4rken/sdmaid-public#785]
Running SD Maid on rooted lineageos 14.1 device. When disabling items for freedompop app (com.freedompop.phone) then "1 failed" is displayed at the bottom. What logs can be looked at to identify problem?

**Comment by d4rken** [comment]
SD Maids internal  debugrun log should show what issue is:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

alternatively you could set SD Maids debug level to `2` and record a normal logcat.

**Comment by JonnyTech** [comment]
Thanks. Pressing the "CREATE DEBUG TRIGGER" button displays "Couldn't create trigger!". I shall do it manually..

**Comment by JonnyTech** [comment]
File created but no log exists after force quitting SD Maid and reproducing the error. In settings it shows that the file exists and is deleted at the next run.

Cannot do a logcat as I am away from a computer now. What is the adb command to pull the logcat data?

**Comment by JonnyTech** [comment]
I missed the last paragraph where it said that the location of the log file had changed.

Here is the file (renamed to .text as github does not allow .log):

[sdmaid_logfile_1489230025547.log.txt](https://github.com/d4rken/sdmaid-public/files/835691/sdmaid_logfile_1489230025547.log.txt)

**Comment by d4rken** [comment]
The system throws an error.

What happens if you manually run

`pm disable 'com.freedompop.phone/com.freedompop.phone.NetworkManager'` 

from a root console?

```
1489230056383 D/WorkerHub:Processor:AppControlWorker: Processing task: ReceiverTask(app=AppObject(packageInfo=PackageInfo{2aff187 com.freedompop.phone}), receiver=[Receiver(package=com.freedompop.phone, receiver=com.freedompop.phone.NetworkManager, enabled=true, intentTypes=[android.net.conn.CONNECTIVITY_CHANGE])])
1489230056557 D/ReceiverFactory:  pm disable com.freedompop.phone/com.freedompop.phone.NetworkManager
1489230056566 D/StaticShell: timeout is 30000
1489230056566 V/Shell:StaticExecutor: SHELLDELAY:100
1489230056578 V/Shell:StaticExecutor: trying to execute as root
1489230056686 V/Shell:StaticExecutor: LD_LIBRARY_PATH=/vendor/lib64:/system/lib64:/vendor/lib:/system/lib:$LD_LIBRARY_PATH pm disable 'com.freedompop.phone/com.freedompop.phone.NetworkManager'
1489230056788 V/Shell:StaticExecutor: Error: WARNING: linker: Warning: unable to normalize ""
1489230056797 V/Shell:StaticExecutor: Error: WARNING: linker: Warning: unable to normalize ""
1489230057234 V/Shell:StaticExecutor: Error: CANNOT LINK EXECUTABLE "app_process": cannot locate symbol "__xlog_buf_printf" referenced by "/system/lib64/libdpframework.so"...
1489230057400 V/Shell:StaticExecutor: Error: Aborted 
1489230057418 V/Shell:StaticExecutor: Exitcode: 0
1489230057418 V/Shell:StaticExecutor: Destroying Executor
1489230057419 V/Shell:StaticExecutor: Destroying Executor
1489230057419 D/ReceiverFactory: WARNING: linker: Warning: unable to normalize ""
1489230057419 D/ReceiverFactory: WARNING: linker: Warning: unable to normalize ""
1489230057420 D/ReceiverFactory: CANNOT LINK EXECUTABLE "app_process": cannot locate symbol "__xlog_buf_printf" referenced by "/system/lib64/libdpframework.so"...
1489230057420 D/ReceiverFactory: Aborted 
```

**Comment by JonnyTech** [comment]
See screenshot (can't cut or paste to it):

![screenshot_20170311-144014](https://cloud.githubusercontent.com/assets/3584732/23824113/b447bace-0668-11e7-9ed2-a0738a25d4ac.png)

**Comment by d4rken** [comment]
It's a ROM bug. I would suggest to contact your ROM dev about it.

I'm unaware of any workaround for this. Do other apps with similar functionality work?

**Comment by JonnyTech** [comment]
Will do, thanks for your time. I should have provided more details: Its LineageOS 14.1 without any GApps, patched with [tingle](http://github.com/ale5000-git/tingle) for signature spoofing to enable [MicroG](https://github.com/microg/android_packages_apps_GmsCore). Everything on the phone works perfectly apart from this issue. What other similar app do you recommend?

**Comment by JonnyTech** [comment]
Reopening due to update:

I reflashed my ROM and tried the command that you suggested:

```
user@computer:/$ adb shell
spark:/ # pm disable 'com.freedompop.phone/com.freedompop.phone.NetworkManager'
Component {com.freedompop.phone/com.freedompop.phone.NetworkManager} new state: disabled
spark:/ #
```

Refreshing SD Maid App Control shows the item is indeed disabled.

But trying to get it to work from the app still fails and produces the failed message.

Attached is a new log file in case it helps.


[sdmaid_logfile_1489413948269.log.txt](https://github.com/d4rken/sdmaid-public/files/838431/sdmaid_logfile_1489413948269.log.txt)

**Comment by d4rken** [comment]
Can you also try it from the terminal emulator app? ADB is always a special
case.

Am 13.03.2017 3:12 nachm. schrieb "JonnyTech" <notifications@github.com>:

**Comment by JonnyTech** [comment]
Ah, I did not realise that. The terminal emulator app still displays the error message..

**Comment by d4rken** [comment]
There are similar error messages that are fixed by making sure the correct libraries are used, which is why SD Maids command looks like this:

```
LD_LIBRARY_PATH=/vendor/lib64:/system/lib64:/vendor/lib:/system/lib:$LD_LIBRARY_PATH pm disable 'com.freedompop.phone/com.freedompop.phone.NetworkManager'
```

You can try that from terminal emulator too. 
To see if something is a bug in SD Maid you should compare it with the behavior of another app using root shells, e.g. `su` through the terminal emulator app.
There are subtle differences between apps and adb shell, e.g. environment differences (different paths to sdcard accessible), or that they are subject to different SELinux restrictions.

**Comment by d4rken** [comment]
Any update on this?

If something points back to SD Maid being at fault or there is something SD Maid can do to make this work, just reopen the ticket.

**Comment by gilcu3** [comment]
I'm getting this in my debug file, is this a ROM related error too?

```
1496148435231 V/Shell:Static:Executor: LD_LIBRARY_PATH=/vendor/lib:/system/lib:$LD_LIBRARY_PATH pm disable 'cn.xender/cn.xender.basicservice.NetworkChangeReceiver'
1496148436382 V/Shell:Static:Executor: Error: android.os.TransactionTooLargeException
1496148436383 V/Shell:Static:Executor: Error: Error: Could not access the Package Manager.  Is the system running?
1496148437336 V/Shell:Static:Executor: Exitcode: 0
1496148437337 V/Shell:Static:Executor: Destroying Executor
1496148437338 V/Shell:Static:Executor: Destroying Executor
1496148437339 D/ReceiverFactory: android.os.TransactionTooLargeException
1496148437339 D/ReceiverFactory: Error: Could not access the Package Manager.  Is the system running?
```

full log [here](https://pastebin.com/3Si8G4NA)

**Comment by d4rken** [comment]
@gilcu3 Possibly, it's different from the issue in this ticket though, lets look into your issue here:
https://github.com/d4rken/sdmaid-public/issues/947

**Comment by JonnyTech** [comment]
The original issue was, as @d4rken correctly assumed, a ROM issue. I never did find a workaround and have now changed ROM. This issue can be closed permanently.
