### ISSUE TITLE
Clutterreport: /storage/emulated/0/aquery/temp

### ISSUE THREAD

**Issue by Valudonox** [d4rken/sdmaid-public#787]
### Target
Target: `/storage/emulated/0/aquery/temp`
Prefix-free: `aquery/temp`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Lucky Patcher`
Packagename: `com.android.vending.billing.InAppBillingService.LOCK`
Version: `6.4.5 (1403)`

### Current owners
Appname: `?`
Packagename: `com.androidquery`
Version: `null (0)`

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `Verizon/kltevzw/kltevzw:6.0.1/MMB29M/G900VVRS2DQB2:user/release-keys`

**Comment by d4rken** [comment]
Can't find anything about Lucky Patcher creating the folder `aquery.
