### ISSUE TITLE
Clutterreport: /storage/sdcard1 (FP)

### ISSUE THREAD

**Issue by casanya** [d4rken/sdmaid-public#790]
### Target
Target: `/storage/sdcard1`
Prefix-free: `/storage/sdcard1`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `External Storage`
Packagename: `com.android.externalstorage`
Version: `4.4.4-20161108.114005.23039 (19)`

### Current owners
None

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `ZTE/ZTE_WELLINGTON/wellington:4.4.4/KTU84P/20161108.114005.23039:user/release-keys`

Can't access my external micro sd

**Comment by d4rken** [comment]
Not the right place for this, and the cause is Android 4.4. Upgrade/Downgrade Android or root the device are the only solutions.
