### ISSUE TITLE
Clutterreport: /storage/sdcard1/WhatsApp

### ISSUE THREAD

**Issue by Sprax2013** [d4rken/sdmaid-public#793]
### Target
Target: `/storage/sdcard1/WhatsApp`
Prefix-free: `WhatsApp`
Path-prefix: `/storage/sdcard1/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.whatsapp`
Version: `null (0)`

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `motorola/peregrine_retde/peregrine:5.1/LPBS23.13-17.3-1/1:user/release-keys`

### Comment
`WhatsApp saves only on local storage. this is a copy of it on sdcard`

**Comment by d4rken** [comment]
Technically correct, but SD Maid doesn't distingiush internal and external public storage in terms of ownership and location type, it's both "public storage". Treatment of public storage is too chaotic across all Android devices.
