### ISSUE TITLE
Android O: Notification channel

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#804]
Not 100% sure but I think we need to create a notification channel now?

https://developer.android.com/preview/features/notification-channels.html

**Comment by Honey2504** [comment]
What exactly NotificationChannel is? What is the effect for users in using the notifications?

**Comment by d4rken** [comment]
Notifications can be treated as a notification "feed" on a per app basis. For SD Maid this won't change anything at the moment, but theoretically we could use it to show more notifications in a cleaner way.

**Comment by d4rken** [comment]
https://blog.aritraroy.in/android-o-developer-preview-teardown-for-the-developers-db9f86b825fb
