### ISSUE TITLE
ticket ?

### ISSUE THREAD

**Issue by laiceps-nonrut** [d4rken/sdmaid-public#806]
hope to be right place here 
also mal sehen mit dem permission entfernen bei sys apps und konsequenzen
asso bei den lib deps geht prog glaube noch nicht bei preinstalled aber ich schreib wenns klappt oder abstuerzt

ist das ein ticket :) ?

**Comment by d4rken** [comment]
Ja das ist ein Ticket, wenns geht in english (damit andere zum Thema beitragen können) und bitte mit aussagekräftigem Titel ;).

**Comment by d4rken** [comment]
Any news?
