### ISSUE TITLE
Clutterreport: /charger (FP)

### ISSUE THREAD

**Issue by ruseykin2** [d4rken/sdmaid-public#807]
### Target
Target: `/charger`
Prefix-free: `/charger`
Path-prefix: ``
Type: `SYMBOLIC LINK`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `ADI`
Packagename: `com.sagrcasm.pixelADI`
Version: `0.5.3 (35)`

### Current owners
None

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `HighScreen/PowerRage/PowerRage:5.1/LMY47I/1452719278:user/release-keys`

**Comment by ruseykin2** [comment]
В телефоне жопа одна реклама

**Comment by d4rken** [comment]
Thanks for your report, but this not a correct match, `/charger` likely belongs to the kernel/system.

> В телефоне жопа одна реклама

I don't know what that means, sorry 😦 .
