### ISSUE TITLE
Migrate update check to encryption

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#808]
The update check is currently done over http. This isn't critical because it contains problematic information. It certainly doesn't hurt to use https though! The more encryption the merrier.

**Comment by d4rken** [comment]
* http://sdmaid.darken.eu:3000 (Legacy)
* https://sdmaid.darken.eu:3022 (New for all v4.11.4+)

TIL the older code does not support redirection to HTTPS ☹️

**Comment by SuperSandro2000** [comment]
Hopefully you didn't use a 301 in public environment

**Comment by d4rken** [comment]
@SuperSandro2000 What do you mean by that?

**Comment by SuperSandro2000** [comment]
I thought that you could maybe have used a redirect on the server to https

**Comment by d4rken** [comment]
Sorry but I still don't understand what you mean :(

**Comment by SuperSandro2000** [comment]
> TIL the older code does not support redirection to HTTPS ☹️

My first thought was you used a 301 redirect from http to https on your public server. Don't think you did that now but earlier I assumed that you may did that

**Comment by d4rken** [comment]
That was my idea until I found out that won't work. For the future I know know that in hindsight it is better to make the code able to follow redirect specifically for these cases.
