### ISSUE TITLE
Searcher exclusions have no effect.

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#809]
It's possible to create exclusions and specify a `Searcher` tag, but the searcher has no routine to process and apply exclusions !?

It's definitely unwanted behavior, but I'm not sure about the solution.

* Add exclusion processing to the searcher, so the exclusions work as expected.
* Remove the searcher exclusion option because it's a bit weird to exclude items from a search. (Just like it would be weird to exclude entries from the explorer or storage analyzer)

**Comment by d4rken** [comment]
Removed the exclusion type alltoegether and added a "path doesn't contain" field to the searcher options.
Currently allows for only one string. I'll change this to a list in a future update when I redo the search options dialog.

**Comment by boyka100** [comment]
Can you Help Me ?!
SD Mida apk 
Delete My Photo and Music I want to restore photo plz
