### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/Message contents share/IMG_5826.jpg (FP)

### ISSUE THREAD

**Issue by trezcrossbat** [d4rken/sdmaid-public#811]
### Target
Target: `/storage/emulated/0/Download/Message contents share/IMG_5826.jpg`
Prefix-free: `Download/Message contents share/IMG_5826.jpg`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `Android System WebView`
Packagename: `com.google.android.webview`
Version: `49.0.2623.105 (262310500)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `6.0.1 (23)`

Appname: `?`
Packagename: `com.android.providers.downloads.ui`
Version: `null (0)`

Appname: `Download manager`
Packagename: `com.android.providers.downloads`
Version: `6.0.1 (23)`

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `samsung/on5ltemtr/on5ltemtr:6.0.1/MMB29K/G550T1UVS2APL1:user/release-keys`

**Comment by d4rken** [comment]
Why the webview?
