### ISSUE TITLE
Custom filter ignored by System Cleaner if run via Quick Access

### ISSUE THREAD

**Issue by HerborenInVlammen** [d4rken/sdmaid-public#814]
I find that a custom filter is ignored by System Cleaner when running System Cleaner via Quick Access, but is not ignored if running System Cleaner by itself.

For example:  I created a filter to delete an empty folder that is ignored by default (ignored because it is created by an app).  Running System Cleaner by itself runs the filter appropriately and the folder is deleted.  Running System Cleaner via Quick Access ignores the custom filter and does not delete the folder.

**Comment by d4rken** [comment]
Hm, there should be no difference, both start points create a `ScanTask` and submit it.

From looking at the code, I don't see how this would be possible.

Can you record the SystemCleaner scan (started from QuickAccess) on a debug log?

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by HerborenInVlammen** [comment]
How do I initiate the debug log.  Also, where can I find my custom
filters to edit?

**Comment by d4rken** [comment]
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

https://github.com/d4rken/sdmaid-public/wiki/SystemCleaner#userfilter

**Comment by HerborenInVlammen** [comment]
OK, I was unaware you could export the filter to edit and then import
it.  That is awesome.  I should read more.

However, before I knew that, I deleted the filter, and then recreated an
identical filter which now works as expected.  I have no idea why as
both filters were simple "default" filters.  I.e., Highlight the folder,
choose Filter, and then Save.  Then enable under USER in System Cleaner. 

I went as far as making a screencast of the issue that plainly shows
that it worked only under the one condition... but it was 56 MB and so I
did not email it.

Apologies for wasting your time.  Again :)

**Comment by d4rken** [comment]
> OK, I was unaware you could export the filter to edit and then import it. That is awesome. I should read more.

Please do 😉 I put a lot of effort into the wiki. If there is no answer to something in the wiki, just make a new issue ticket so i can add an answer 👍 .

>However, before I knew that, I deleted the filter, and then recreated an identical filter which now works as expected. I have no idea why as both filters were simple "default" filters. I.e., Highlight the folder, choose Filter, and then Save. Then enable under USER in System Cleaner.

Creating the filter via Explorer has a few caveats, it's sometimes difficult to do matching here because in Android multiple pathes can lead to the same destination and which paths lead where again depends on root vs non-root etc.... complicated 😁 .

> Apologies for wasting your time. Again :)

No worries, rather a few more tickets instead of a bug going unnoticed.
