### ISSUE TITLE
Clutterreport: /storage/emulated/0/bcr (FP)

### ISSUE THREAD

**Issue by erikuitenbroek** [d4rken/sdmaid-public#821]
### Target
Target: `/storage/emulated/0/bcr`
Prefix-free: `bcr`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `false`

### Suggested owners
Appname: `CamCard`
Packagename: `com.intsig.BCRLite`
Version: `7.8.9.20170320 (7890)`

### Current owners
Appname: `CamCard`
Packagename: `com.intsig.BizCardReader`
Version: `7.8.9.20170320 (7890)`

Appname: `CamCard`
Packagename: `com.intsig.BCRLite`
Version: `7.8.9.20170320 (7890)`

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU1DQB3:user/release-keys`

### Comment
`?`

**Comment by d4rken** [comment]
`com.intsig.BCRLite` is already an owner?
