### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android (FP)

### ISSUE THREAD

**Issue by Hawkmorgan101** [d4rken/sdmaid-public#825]
### Target
Target: `/storage/emulated/0/Android`
Prefix-free: `Android`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Android System`
Packagename: `android`
Version: `6.0-170761654ea2e (23)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `6.0-170761654ea2e (23)`

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `lge/m1v_crk_us/m1v:6.0/MRA58K/170761654ea2e:user/release-keys`

### Comment
`great`

**Comment by Hawkmorgan101** [comment]
Do i do anything

**Comment by d4rken** [comment]
Android is already the designated owner of that folder. Why did you report it?
