### ISSUE TITLE
Make internal toybox worldreadable again?

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#835]
Current SD Maid does not explicitly set the permission of it's internal toybox `/data/data/eu.thedarken.sdm/files/toybox_sdm` to 555, but rather 500.

For debugging it would be helpful if the user could use SD Maids toybox direct from commands run through termux/terminal emulator.

Upside:
* Easier debugging

Downside
* A few miliseconds during initial launch (java doesn't seem to allow direct checks for group permission, so we either check via shell or set them each time)
* Security? Android shows the LINT "Setting file permissions to world-readable can be risky, review carefully" but i don't see how this would apply here.

**Comment by tswitcher** [comment]
I'm not sure how this work I would like some help if you
Will thanks

**Comment by d4rken** [comment]
@tswitcher Send a mail to support@darken.eu or [create a new ticket](https://github.com/d4rken/sdmaid-public/issues/new) to discuss for your issue.

**Comment by d4rken** [comment]
Debugging with this wouldn't work like I thought.
