### ISSUE TITLE
Clutterreport: /system/container/SharedDeviceKeyguard/SharedDeviceKeyguard.apk (FP)

### ISSUE THREAD

**Issue by StussyJenny** [d4rken/sdmaid-public#836]
### Target
Target: `/system/container/SharedDeviceKeyguard/SharedDeviceKeyguard.apk`
Prefix-free: `container/SharedDeviceKeyguard/SharedDeviceKeyguard.apk`
Path-prefix: `/system/`
Type: `FILE`
Location: `SYSTEM`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Android-System`
Packagename: `android`
Version: `5.1.1-J120FNXXU1APL3 (22)`

### Current owners
None

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `samsung/j1xltexx/j1xlte:5.1.1/LMY47X/J120FNXXU1APL3:user/release-keys`

**Comment by d4rken** [comment]
Thanks for the report, but SD Maid currently does not support matching in `/system` like this.
