### ISSUE TITLE
Dates in Explorer not shown according to system settings.

### ISSUE THREAD

**Issue by FlyingHorseGA** [d4rken/sdmaid-public#838]
Using version 4.6.5 Pro of SD Maid the title states the ptoblem that I am seeing. I'm using U.S. settings for the date display but I am getting dates shown in European (and the rest of the world?) format. For instance I am seeing 10/4/17 instead of 4/10/17 for the date April 10th, 2017.

I'm running stock Lollipop 5.0.2 on a Samsung Galaxy Note Pro 12.2 SM-P900. I'm rooted with SuperSU 2.79 SR3 and have Xposed framework dkcldark 87.1.

**Comment by d4rken** [comment]
Yeah, the date format is currently hardcoded. I'll look into respecting system settings.
