### ISSUE TITLE
Clutterreport: /storage/emulated/0/romtoolbox/downloads/download.chainfire.eu/382/SuperSU/UPDATE-SuperSU-v1.93.zip?retrieve_file=1-(1)/arm/su (FP)

### ISSUE THREAD

**Issue by Mrhession83** [d4rken/sdmaid-public#839]
### Target
Target: `/storage/emulated/0/romtoolbox/downloads/download.chainfire.eu/382/SuperSU/UPDATE-SuperSU-v1.93.zip?retrieve_file=1-(1)/arm/su`
Prefix-free: `romtoolbox/downloads/download.chainfire.eu/382/SuperSU/UPDATE-SuperSU-v1.93.zip?retrieve_file=1-(1)/arm/su`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `BusyBox`
Packagename: `com.jrummy.busybox.installer`
Version: `6.7.3.0 (67300)`

Appname: `BuildProp`
Packagename: `com.jrummy.apps.build.prop.editor`
Version: `2.2.4.0 (22400)`

Appname: `BusyBox X`
Packagename: `com.bitcubate.root.busybox.complete`
Version: `X 100 (100)`

Appname: `BusyBox Free`
Packagename: `stericson.busybox`
Version: `49 (199)`

### Current owners
Appname: `?`
Packagename: `com.jrummy.root.browser`
Version: `null (0)`

Appname: `ROM Installer`
Packagename: `com.jrummy.apps.rom.installer`
Version: `1.3.0.0 (13000)`

Appname: `?`
Packagename: `com.jrummy.root.browserfree`
Version: `null (0)`

Appname: `?`
Packagename: `com.jrummy.apps.boot.animations`
Version: `null (0)`

Appname: `?`
Packagename: `com.jrummy.liberty.toolboxpro`
Version: `null (0)`

Appname: `?`
Packagename: `com.jrummy.liberty.toolbox`
Version: `null (0)`

Appname: `BuildProp`
Packagename: `com.jrummy.apps.build.prop.editor`
Version: `2.2.4.0 (22400)`

### SD Maid
Version: `4.6.5 (40605)`

### Device
Fingerprint: `samsung/on5ltemtr/on5ltemtr:6.0.1/MMB29K/G550T1UVU2AQC4:user/release-keys`

**Comment by d4rken** [comment]
What exactly are you reporting?
