### ISSUE TITLE
Google Play Certification & Download issue

### ISSUE THREAD

**Issue by BilboDaddins** [d4rken/sdmaid-public#845]
After I ran SD Maid my device certification status changed to "uncertified" and I couldn't download any of my apps that I purchased on the play store. It asks me to buy the app but on my order history it shows that I purchased it. 

Is it because of something that SD Maid deleted from the Play Store that is causing this issue? Just letting the developer know because I had this problem right after I ran SD Maid.

**Comment by d4rken** [comment]
> After I ran SD Maid my device certification status changed to "uncertified" and I couldn't download any of my apps that I purchased on the play store. It asks me to buy the app but on my order history it shows that I purchased it.

Those two things are unrelated. Not seeing an already purchased app as "purchased" is a common bug in Google Play, it's just out of sync with your account, [see here](https://github.com/d4rken/sdmaid-public/wiki/Frequently-Asked-Questions#google-play-is-not-showing-the-purchase).

> Is it because of something that SD Maid deleted from the Play Store that is causing this issue? Just letting the developer know because I had this problem right after I ran SD Maid.

If you are not rooted, then no. If you are rooted, _maybe_, but then again, just being rooted can change this. The most common reason for this to be "not certified" is to just have an unlocked bootloader.

What device / ROM?
