### ISSUE TITLE
Clutterreport: /storage/emulated/0/.adslib (new)

### ISSUE THREAD

**Issue by Laxussien** [d4rken/sdmaid-public#852]
### Target
Target: `/storage/emulated/0/.adslib`
Prefix-free: `.adslib`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
None

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `DOOGEE/X5max_PRO/X5max_PRO:6.0/MRA58K/20170116.183802:user/release-keys`

### Comment
`There is a storage of a virus 'removed apps' which will auto download apk such as(Turbo cleaner,Super b cleaner,Alibaba express,Traveloka book and else).It it a unknown cause it doesn't show the process of downloading .Please help to fix it`

**Comment by d4rken** [comment]
SD Maid needs to know the package name of the app that uses/creates the folder, otherwise it's not possible to create relation for this folder in the database.

**Comment by d4rken** [comment]
Not enough information to act on this.
