### ISSUE TITLE
Clutterreport: /storage/emulated/0/com.kingroot.kinguser/e_config (new)

### ISSUE THREAD

**Issue by EliteGreyIT67** [d4rken/sdmaid-public#862]
### Target
Target: `/storage/emulated/0/com.kingroot.kinguser/e_config`
Prefix-free: `com.kingroot.kinguser/e_config`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `KingRoot`
Packagename: `com.kingroot.kinguser`
Version: `5.0.5 (172)`

### Current owners
None

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `samsung/j7eltetmo/j7eltetmo:6.0.1/MMB29K/J700TUVU2APJ3:user/release-keys`

**Comment by d4rken** [comment]
Sure about this one? Couldn't find anything on a quick google search.
What's this `e_config` file?

**Comment by EliteGreyIT67** [comment]
Yes, i uninstall kingroot with sd maid to cleanup all the clutter it leaves behind, like empty folders and other things it created including that file, but that file stays there. I want to crave it up and see whats inside, but i wanted to know if ya came across it before. 
Thanks

**Comment by d4rken** [comment]
Nope, didn't know this. Let me know what's inside the file when you have time.
