### ISSUE TITLE
SystemCleaner user filters don't act on root-only paths

### ISSUE THREAD

**Issue by blackwind** [d4rken/sdmaid-public#866]
I have root, and I've granted SD Maid root permission, but creating a filter to clear out `/data/data/com.android.providers.downloads/cache/` has no effect. Filters on paths accessible without root function as expected, so it doesn't appear I'm doing anything wrong. Can we get a fix?

Side note: "Basepath" could really, really use a file picker.

**Comment by d4rken** [comment]
> Filters on paths accessible without root function as expected, so it doesn't appear I'm doing anything wrong. Can we get a fix?

Can't reproduce this, can you export the filter and post it here?

This one works for me.

```
{
  "version": 4,
  "label": "Downloads Provider",
  "identifier": "39d51b462a3f.scuf.sdm",
  "color": "#03a9f4",
  "rootOnly": false,
  "locations": [
    "PRIVATE_DATA"
  ],
  "mainPath": [
    "/data/data/com.android.providers.downloads/cache"
  ]
}
```
(Save that into a `.json` file to import in SD Maid)

https://cloud.githubusercontent.com/assets/1439229/25479755/43a4b396-2b46-11e7-88f4-b9bd5e53d693.png

> Side note: "Basepath" could really, really use a file picker.

You can start new filters from the explorer which will fill in the basepath. Or long press the path in the explorer to copy it to clipboard. I can look into a file picker though, SD Maids file picker is a bit complicated atm and I need to rewrite that.

**Comment by d4rken** [comment]
What device, what ROM, what superuser? What SD Maid update?

**Comment by blackwind** [comment]
I don't get it. I imported your filter, and it worked. I exported mine, and it was exactly the same as yours, except it didn't include `PRIVATE_DATA`. I added `PRIVATE_DATA` to mine, and it still didn't work. I created a new filter from scratch, without `PRIVATE_DATA`, and it worked. I exported it, and it was exactly the same as my original filter. Doesn't make any sense whatsoever.

I guess we can go ahead and close this, but if it helps, it occurred on a Galaxy S3, CM13, CM superuser, SELinux enforcing, v4.6.5.

> You can start new filters from the explorer which will fill in the basepath. Or long press the path in the explorer to copy it to clipboard.

I actually have Explorer hidden since I use another file manager, but good to know.

> I can look into a file picker though, SD Maids file picker is a bit complicated atm and I need to rewrite that.

I was totally satisfied with the import/export experience. Transplanting that into the filter editor with whichver changes would be required to select a folder would be more than sufficient.

**Comment by d4rken** [comment]
> I don't get it. I imported your filter, and it worked. I exported mine

In a similar case the other user had accidentally input a trailing space or new-line. If you can send me the not working filter, then I can have a look (run a diff).

> , and it was exactly the same as yours, except it didn't include PRIVATE_DATA.

It should not make a difference here. The idea is that by specifying the location we can make cross device compatible filters (and it never hurts to make a filter more specific, to avoid suprises).

One device might have `/sdcard/SomeFolder` another might have `/storage/emulated/0/SomeFolder` and another one `/storage/sdcard1/SomeFolder`, then we could match all 3 folders by making a filter with `/SomeFolder/` + `SDCARD`.

Though theoretically the same could be acchieved with a regular expression, I guess "All Roads Lead to Rome" 😉
