### ISSUE TITLE
Clutterreport: /storage/emulated/0/Android/data/com.hanista.mobogram/cache/-2147483648_-213803.jpg (FP)

### ISSUE THREAD

**Issue by mehdi1568** [d4rken/sdmaid-public#882]
### Target
Target: `/storage/emulated/0/Android/data/com.hanista.mobogram/cache/-2147483648_-213803.jpg`
Prefix-free: `com.hanista.mobogram/cache/-2147483648_-213803.jpg`
Path-prefix: `/storage/emulated/0/Android/data/`
Type: `FILE`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Plus`
Packagename: `org.telegram.plus`
Version: `3.13.1.9 (8803)`

### Current owners
Appname: `موبوگرام`
Packagename: `com.hanista.mobogram`
Version: `T3.18.0-M9.7.1 (95760)`

### SD Maid
Version: `4.6.4 (40604)`

### Device
Fingerprint: `Honor/Che2-L11/hwChe2:4.4.2/HonorChe2-L11/C185B067:user/ota-rel-keys,release-keys`

**Comment by d4rken** [comment]
What does this have to do with telegram?
