### ISSUE TITLE
CorpseFinder not detecting leftover files

### ISSUE THREAD

**Issue by siennk** [d4rken/sdmaid-public#887]
I recently noticed in my files that a file from an app I deleted was still there. 

I ran sdmaid several times, with every search setting possible picked, and it didn't catch it during any of the scans. 

After that, I went through my files again and noticed several files that sdmaid never caught. Some are small files, othera are large files. 

I don't have root on my phone. And the files I am talking about don't need root to be accessed.

**Comment by JonnyTech** [comment]
Please provide specific examples including the app name and details of the remaining files.

**Comment by siennk** [comment]
There are several more files like this that CorpseFinder didn't catch. 

![20170514_121651](https://cloud.githubusercontent.com/assets/25418911/26035795/318c0328-38a0-11e7-9060-602db6664ede.jpg)

![20170514_121758](https://cloud.githubusercontent.com/assets/25418911/26035797/38edf428-38a0-11e7-99f3-e31895b53867.jpg)

![20170514_121855](https://cloud.githubusercontent.com/assets/25418911/26035799/4328d1a6-38a0-11e7-81c8-7e342cd6035d.jpg)

![20170514_122138](https://cloud.githubusercontent.com/assets/25418911/26035803/6922765a-38a0-11e7-9793-84a855e560b7.jpg)

**Comment by d4rken** [comment]
Any file that is marked with a "?" in the explorer is unknown to SD Maid and thus can't be marked as corpse (if we don't know who owns a file we can't know if it's a corpse).

This is easily fixable though, just need to know the path and the app that created them.
The "?" should be clickable and take you to a UI that helps report these, or you post it here, what ever is easier.

[See here](https://github.com/d4rken/sdmaid-public/issues?utf8=%E2%9C%93&q=label%3A%22c%3A%20Definitions%22%20) for reports from the in app UI.

On a side note: The path  `/storage/emulated/0` is the same for everyone and file size/date is not really sensitive either.

**Comment by siennk** [comment]
How about for the files I no longer have the app for? I tried typing it in the comment section, but couldn't send it.

**Comment by d4rken** [comment]
It requires a certain amount of text before you can send it.

**Comment by d4rken** [comment]
Seems you got the hang of the report tools, awesome!

Once they are added in the next update, all users will benefit from your reports 👍 

Reports improve SD Maid in more ways than just corpse detection.
AppControl will consider new directories for size calculation, the AppCleaner will check them for expendable files and the Databases tool will pick up sql databases from them (as it needs to consider running/not running apps, it doesn't process databases from unknown apps).
