### ISSUE TITLE
Export action missing for all apps

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#888]
Seems the previous changes caused the export action to be missing for all apps.

**Comment by NeoBeum** [comment]
What's the fix for beta?

**Comment by d4rken** [comment]
It was a code copy/paste error from my side. The module responsible for freeze (enabled/disabled) data was removing the export data for each app.

No user side fix available, you'll have to wait for update v4.7.3. I'll see that I get it ready it this evening.
