### ISSUE TITLE
Filter for old WhatsApp backups

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#904]
Since SD Maid beta v4.7.2 we have an "age" filter. This finally allows us to make a filter that deletes old WhatsApp backups.

@antonio-gil was so awesome to provide a first filter, [see here](https://github.com/d4rken/sdmaid-public/issues/333#issuecomment-302756799).

I've made a more tweaks and the current version is this:
[OldWhatsAppDatabaseBackups.scuf.sdm.zip](https://github.com/d4rken/sdmaid-public/files/1015517/OldWhatsAppDatabaseBackups.scuf.sdm.zip)
To import it, extract the zip file and import the `.json` file into the SystemCleaner.

**What we need to test:** 
* Does it match the correct files on all devices?
* Using this filter, is the scan performance acceptable?

This is how it works

* All targets must be a file.
* All files we want to delete end in `db.crypt12`.
* The target must begin with `msgstore-`, note the trailing slash as the current backup also doesn't have that.
* We use `pathContains` and `locations` instead of `mainPath` so that it's also possible to match pathes like `/storage/sdcard0/WhatsApp/...` as well as `/storage/emulated/0/WhatsApp/...` etc.
* The file must be a minimum of 1 day old (24 * 60 * 60 * 1000).

The filter looks like this
```
{
  "version": 4,
  "label": "Old WhatsApp Backups",
  "description": "Message backups older than 1 day.",
  "identifier": "61d71937f87c.scuf.sdm",
  "color": "#075E54",
  "targetType": "FILE",
  "possibleNameEndings": [
    ".db.crypt12"
  ],
  "possibleNameInits": [
    "msgstore-"
  ],
  "pathContains": [
    "/WhatsApp/Databases/"
  ],
  "locations": [
    "SDCARD"
  ],
  "minimumAge": 86400000
}
```

**Comment by antonio-gil** [comment]
Awesome!

Thanks for the tweaks and the explanation!

And, perhaps, for improve the UX, it could be a good idea to use an alternative to the milliseconds. Specially with lapses bigger than a day or two.

Using the WhatsApp example, there can be backups made on weekly or monthly basis, and at least IMHO, calculate the ms of such time span is not so accessible... Of course! I can be wrong, and it's just an "issue" for me.

So, what do you think?

**Comment by d4rken** [comment]
> And, perhaps, for improve the UX, it could be a good idea to use an alternative to the milliseconds. Specially with lapses bigger than a day or two.

Miliseconds is the finest resolution that is possible. Of course I can change that to hours or days, but maybe someone else needs this kind of accuracy. So we would probably need a few additional UI elements to allow entering different time spans days/hours etc. It would be nice to have, but would it be worth the effort? Maybe something for the lower end of the TODO list 😉

**Comment by antonio-gil** [comment]
Yeah, I totally agree.
