### ISSUE TITLE
Clutterreport: /storage/emulated (FP)

### ISSUE THREAD

**Issue by Maniano925** [d4rken/sdmaid-public#906]
### Target
Target: `/storage/emulated`
Prefix-free: `/storage/emulated`
Path-prefix: ``
Type: `DIRECTORY`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `SD Maid Pro`
Packagename: `eu.thedarken.sdm.unlocker`
Version: `4.0.13 (40013)`

### Current owners
None

### SD Maid
Version: `4.6.5 (40605)`

### Device
Fingerprint: `samsung/j7eltetmo/j7eltetmo:6.0.1/MMB29K/J700TUVU3AQC3:user/release-keys`

### Comment
`I can't undo the permissions`

**Comment by d4rken** [comment]
I have no idea what you mean and this isn't a clutter report.

The permissions on `/storage/emulated` don't need to be changed.

**Comment by Maniano925** [comment]
Ok thank for your time

On May 22, 2017 2:08 AM, "Matthias Urhahn" <notifications@github.com> wrote:

I have no idea what you mean and this isn't a clutter report.

The permissions on /storage/emulated don't need to be changed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/d4rken/sdmaid-public/issues/906#issuecomment-303043280>,
or mute the thread
