### ISSUE TITLE
Add option to chose and force a specific language resource

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#916]
If a ROM is *not* translated into language XY, but SD Maid has a language specific resource for that locale, then there is no way for SD Maid to display in that language.

The solution would be a dialog with a list of all available locales in SD Maid and then enforcing that.

There is already code in SD Maid that can enforce locales which is used to force SD Maid to display in english which could be adapted for this.

Do we need to add an extra translation string for this that shows the locale name in a translated form?
Probably not right? If someone doesn't understand english there is almost no way for them to navigate to the language setting. So just translating the available locales wouldn't bring much benefit.

**Comment by Antine93** [comment]
I think that it's a good feature, in example i spoke sardinian but there aren't android ROMs that support this language. Including this feature a lot of people can be able to use their native language.

> Do we need to add an extra translation string for this that shows the locale name in a translated form?
Probably not right? If someone doesn't understand english there is almost no way for them to navigate to the language setting. So just translating the available locales wouldn't bring much benefit.

Generally who spokes a "regional" language knows an other language that is between the languages of the system so this problem doesn't exist.
