### ISSUE TITLE
Clutterreport: /storage/emulated/0/DCIM/.OCRTemp (FP)

### ISSUE THREAD

**Issue by mellorealestate** [d4rken/sdmaid-public#924]
### Target
Target: `/storage/emulated/0/DCIM/.OCRTemp`
Prefix-free: `DCIM/.OCRTemp`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Android System`~~
~~Packagename: `android`~~
~~Version: `7.0 (24)`~~

### SD Maid
Version: `4.6.5 (40605)`

### Device
Fingerprint: `Verizon/nobleltevzw/nobleltevzw:7.0/NRD90M/N920VVRS3CQD1:user/release-keys`

**Comment by d4rken** [comment]
What app created the dir `.OCRTemp`?

**Comment by d4rken** [comment]
Lack of info.
