### ISSUE TITLE
Clutterreport: /storage/emulated/0/Download/com.pas.ipwebcamftp-44.0.apk (FP)

### ISSUE THREAD

**Issue by macgyver88chan** [d4rken/sdmaid-public#925]
### Target
Target: `/storage/emulated/0/Download/com.pas.ipwebcamftp-44.0.apk`
Prefix-free: `Download/com.pas.ipwebcamftp-44.0.apk`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Filoader`
Packagename: `com.pas.ipwebcamftp`
Version: `44.0 (44)`

### Current owners
Appname: `Android System`
Packagename: `android`
Version: `1.1 (22)`

~~Appname: `?`~~
~~Packagename: `com.android.providers.downloads.ui`~~
~~Version: `null (0)`~~

~~Appname: `Download manager`~~
~~Packagename: `com.android.providers.downloads`~~
~~Version: `1.4.1 (141113)`~~

### SD Maid
Version: `4.7.3 (40703)`

### Device
Fingerprint: `OPPO/A1601/A1601:5.1/LMY47I/1493384427:user/release-keys`

**Comment by d4rken** [comment]
While that may be the apk file of that app, the app itself unlikely created or owns this downloaded file.
