### ISSUE TITLE
Settings fragment overlap/racecondition

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#932]
> Install ID: db02ed5e-46ec-4b4f-98b4-c8e3dfbb7aee
> ROM: samsung/gts210ltexx/gts210lte:6.0.1/MMB29K/T815XXU2BPK4:user/release-keys/ca_ES
> SD Maid: 4.6.5[40605]
> Unlocker: 4.0.13[40013]
> Root: false
> Storage: /storage/3366-84D9 (SAF-match=true)
> Storage: /storage/emulated/0 (SAF-match=false)

Looks like an issue with the fragment transaction. I think there was a bug in older Android versions if the fragments had a transparent background? Though `6.0.1` isn't that old...

![screenshot_20170528-182024](https://cloud.githubusercontent.com/assets/1439229/26546890/9377f79a-446c-11e7-9468-7d14b8b2dda7.png)
![98c4080c-1534-4bea-9690-cd71c4922aaa](https://cloud.githubusercontent.com/assets/1439229/26546891/937b5e80-446c-11e7-82fd-3b36374723e6.png)

**Comment by sguss2024** [comment]
JoinZTE

**Comment by d4rken** [comment]
stale
