### ISSUE TITLE
Clutterreport: /storage/emulated/0/Snapchat (FP)

### ISSUE THREAD

**Issue by SpecialKayy** [d4rken/sdmaid-public#949]
### Target
Target: `/storage/emulated/0/Snapchat`
Prefix-free: `Snapchat`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
~~Appname: `Snapchat`~~
~~Packagename: `com.snapchat.android`~~
~~Version: `10.9.3.0 Beta (1122)`~~

### SD Maid
Version: `4.6.5 (40605)`

### Device
Fingerprint: `ZTE/P895T20_MPCS/urd:6.0.1/MMB29M/20170418.111425:user/release-keys`

**Comment by d4rken** [comment]
Why would the snapshot folder not belong to the snapchat app?
