### ISSUE TITLE
Clutterreport: /storage/351F-8B3D/Mega (new)

### ISSUE THREAD

**Issue by Nunai** [d4rken/sdmaid-public#952]
### Target
Target: `/storage/351F-8B3D/Mega`
Prefix-free: `Mega`
Path-prefix: `/storage/351F-8B3D/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `MEGA`
Packagename: `mega.privacy.android.app`
Version: `3.1.5 (134) (134)`

### Current owners
None

### SD Maid
Version: `4.6.5 (40605)`

### Device
Fingerprint: `asus/WW_Z00A/Z00A:6.0.1/MMB29P/4.21.40.223_20161216_7766_user:user/release-keys`

**Comment by d4rken** [comment]
@Nunai What's in the folder? Downloads?
