### ISSUE TITLE
Emulated storage can lead to duplicate results

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#961]
Not a new issue, just one that hasn't been solved yet.

Solution idea:
Try to dynamically detect `/data/media/0` (or what ever is correct on that ROM) and set it as an alias for `/storage/emulated/0` or vice versa. Then for each SystemCleaner default filter on instantition dynamically generate exclusions (or "path doesn't contain") for the aliases.

![geebiaac](https://cloud.githubusercontent.com/assets/1439229/26752683/24ecb462-4856-11e7-9d36-ddcc2ea5191f.png)

**Comment by bege10** [comment]
Opened 2 years ago. Can you, please, fix it?
Thank you very much.

**Comment by d4rken** [comment]
Open for so long because it's a high cost, low benefit change. A clean fix is not easy and has impact on scan speed.

This bug should only lead to a few select files being counted twice in the statistics, or do you see any other downside? I think it only affects the .Log filter too as most other filters are restricted to either public or private storage.

**Comment by bege10** [comment]
I came across this issue because adding an exception on /storage/emulated/0 would still have delete the file/folder because it was listed twice (also with /data/media/0). Is /data/media/0 necessary at all? It is just the same as /storage/emulated/0, isn't it? Couldn't you just exclude /data/media/0 completely from SD-Maid?

**Comment by d4rken** [comment]
`/data/media/0` is the actual location, `/storage/emulated/0` is just a user accessible fuse? mount to it.
If you have multiple users and change accounts, some ROMs can change what is mounted, e.g. `/storage/emulated/0` could point to `/data/media/1` :thinking: 

Such setups are rare though, very rare...

> Couldn't you just exclude /data/media/0 completely from SD-Maid?

That'd be too heavy handed, or at least I'm not sure what side effects that could have as it's (this aside) working fine atm. But it's not a bad idea. I could exclude `/data/media/0` just from the .log filter, this would only work for those ROMs using this pattern. Yeah that's a low cost but effective fix :+1:

**Comment by d4rken** [comment]
I'll make that `/data/media/` to be safe.

**Comment by d4rken** [comment]
Sometimes it just needs someone else throwing in some ideas, I tend to overthink solutions :grin:.
