### ISSUE TITLE
Clutterreport: /storage/emulated/0/.Hnc

### ISSUE THREAD

**Issue by earthsound** [d4rken/sdmaid-public#968]
### Target
Target: `/storage/emulated/0/.Hnc`
Prefix-free: `.Hnc`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Current owners
Appname: `?`
Packagename: `com.hancom.office.viewer`
Version: `null (0)`

Appname: `?`
Packagename: `com.hancom.office.hcell.viewer.hcell_viewer_apk`
Version: `null (0)`

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `Verizon/hero2qltevzw/hero2qltevzw:6.0.1/MMB29M/G935VVRS4APH1:user/release-keys`

### Comment
`Hancom Office 2014 was preloaded on the phone. Strangely, it doesn't show up in app drawer but it's an option when opening a number of office type files`

**Comment by d4rken** [comment]
Do you have a packagename for Hancom Office 2014?

Also why is this a folder that should be kept after uninstall?

**Comment by earthsound** [comment]
According to the data folder name, com.hancom.office.editor.

That's just it: it hasn't been uninstalled (and can't be, unless you're rooted).

**Comment by d4rken** [comment]
Can you check?
If you enable system apps in AppControl, you should be able to find (and the packagename).

**Comment by earthsound** [comment]
The Application Manager on this phone doesn't show the package name for most apps, but I used the app System Info for Android to confirm that the package name is com.hancom.office.editor.

It's SharedUserId is com.hancom.office.lite.sec.

Location is /system/priv-app/HancomOfficeEditor_Hidden/HancomOfficeEditor_Hidden.apk

**Comment by d4rken** [comment]
`com.hancom.office.editor` ok 👍 

> The Application Manager on this phone doesn't show the package name for most apps, but I used the app System Info for Android

Why not use SD Maids AppControl tool for that?

**Comment by d4rken** [comment]
I didn't see any reason why this should be treated like backups or pictures, so I'll not mark this as "keeper".

If the app is not installed `.hnc` can be deleted.

**Comment by earthsound** [comment]
Could you clarify (are you making a change as to how SD Maid will treat this)? Is SD Maid suggesting to remove it because it doesn't think it's installed? 

The typical user won't be able to uninstall it and may not even know it's installed due to it being a hidden, system app. 

I'm not aware of a way to find/install this app if SD Maid removed this folder (which contains fonts, etc., not available on the phone).

**Comment by d4rken** [comment]
> Could you clarify (are you making a change as to how SD Maid will treat this)?

Adding a directory<>pkgname relation allows SD Maid to recognize who owns the dir which affects multiple of SD Maids tools.

>  Is SD Maid suggesting to remove it because it doesn't think it's installed?

The CorpseFinder will suggest to remove it, IF it is not installed. SD Maid can check this easily via the packagename you provided.

> The typical user won't be able to uninstall it and may not even know it's installed due to it being a hidden, system app.

Users with root can uninstall it though. And telling SD Maid who owns that dir allows SD Maid to check it for caches, databases or include it when determining app sizes.

> I'm not aware of a way to find/install this app if SD Maid removed this folder (which contains fonts, etc., not available on the phone).

You mean a way to restore this data? A factory reset would also delete it, so this will likely be recreated by the hancom app if it's still installed.

**Comment by earthsound** [comment]
Thanks! Will this thread get a notification once that change is live?

**Comment by d4rken** [comment]
You will get a notification when I close this issue and then you can see the assigned milestone, i.e. which SD Maid update will contain the change.

Like this https://github.com/d4rken/sdmaid-public/issues/943
