### ISSUE TITLE
Clutterreport: /storage/emulated/0/Pictures/Simple Pro (FP)

### ISSUE THREAD

**Issue by cocobelgica** [d4rken/sdmaid-public#970]
### Target
Target: `/storage/emulated/0/Pictures/Simple Pro`
Prefix-free: `Pictures/Simple Pro`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `true`
Suggested keeper state: `true`

### Suggested owners
Appname: `Simple Pro`
Packagename: `com.creativetrends.simple.app.pro`
Version: `2.9.9 (199)`

### Current owners
Appname: `?`
Packagename: `com.sec.android.gallery3d`
Version: `null (0)`

Appname: `Android System`
Packagename: `android`
Version: `7.1.1 (25)`

Appname: `?`
Packagename: `com.google.android.gallery3d`
Version: `null (0)`

Appname: `Photos`
Packagename: `com.google.android.apps.photos`
Version: `2.16.0.157775819 (1047442)`

Appname: `?`
Packagename: `com.android.gallery3d`
Version: `null (0)`

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `Jiayu/full_s3_h560/s3_h560:7.1.1/NMF26X/cm02131818:user/release-keys`

**Comment by d4rken** [comment]
Nice
