### ISSUE TITLE
Clutterreport: /storage/emulated/0/Genie (new)

### ISSUE THREAD

**Issue by isac322** [d4rken/sdmaid-public#972]
### Target
Target: `/storage/emulated/0/Genie`
Prefix-free: `Genie`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `지니 뮤직`
Packagename: `com.ktmusic.geniemusic`
Version: `04.02.00 (4020000)`

### Current owners
None

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `Xiaomi/capricorn/capricorn:7.0/NRD90M/7.6.8:user/release-keys`

**Comment by d4rken** [comment]
What's inside this directory?

**Comment by isac322** [comment]
Sorry for late. Genie music (지니 뮤직 in korean pronounciation) is a korean music streaming app and saves temporal files in that directory.
