### ISSUE TITLE
System Cleaner: Default tmp filter does not find files which starts with dot(.)       

### ISSUE THREAD

**Issue by ya8sa** [d4rken/sdmaid-public#974]
I found empty  files, .escheck.tmp.
But the Temporary filter can not detect.

**Comment by d4rken** [comment]
What's the full path?

**Comment by ya8sa** [comment]
i found 3 files below.
All File name was same.

/storage/emulated/0/Pictures/Screenshots

/storage/emulated/0/DCIM/100ANDRO

/storage/emulated/0/DCIM/Camera

**Comment by d4rken** [comment]
What do those 3 paths have to do with `.escheck.tmp.`?

**Comment by ya8sa** [comment]
I do not know. File is empty, it may be corpse file. I will delete and watch status if something change or generated again.

**Comment by d4rken** [comment]
My question was: What's the full path of the file `.escheck.tmp` which you said is not detected by the temporary files filter?

Your answers seem unrelated to my question. Please only bring up one issue per ticket.

**Comment by ya8sa** [comment]
Full path are:
/storage/emulated/0/Pictures/Screenshots/.escheck.tmp.
/storage/emulated/0/DCIM/100ANDRO/.escheck.tmp.
/storage/emulated/0/DCIM/Camera/.escheck.tmp.
Since temporary files filter could not find,  I have defined  user filter to search for file name beginning with
 ".escheck".

**Comment by d4rken** [comment]
Thanks for the details, I'll look into it and update this ticket then.

**Comment by d4rken** [comment]
Can't reproduce this. Please provide a [debug log](https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log) of the SystemCleaner scan.

![2017-06-13 06 23 11](https://user-images.githubusercontent.com/1439229/27068709-95fac19a-5011-11e7-9675-0c4ada2aea61.png)

**Comment by ya8sa** [comment]
I tried System Cleaner again today.
Temporary filter could find this file. It is very strange. I would like to close this issue. Thanks.

**Comment by thenickdude** [comment]
I think these files are created by the app "ES File Explorer". It seems to create them periodically for some internal housekeeping task, then removes them shortly afterwards.

**Comment by d4rken** [comment]
I've added detection of these.
