### ISSUE TITLE
Clutterreport: /storage/emulated/0/.torque/vehicles/1480004723924.tdv (FP)

### ISSUE THREAD

**Issue by cu071362** [d4rken/sdmaid-public#978]
### Target
Target: `/storage/emulated/0/.torque/vehicles/1480004723924.tdv`
Prefix-free: `.torque/vehicles/1480004723924.tdv`
Path-prefix: `/storage/emulated/0/`
Type: `FILE`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `false`

### Suggested owners
Appname: `Torque`
Packagename: `org.prowl.torque`
Version: `1.8.158 (958)`

### Current owners
Appname: `?`
Packagename: `org.prowl.torquefree`
Version: `null (0)`

Appname: `Torque`
Packagename: `org.prowl.torque`
Version: `1.8.158 (958)`

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `samsung/poseidonlteuc/poseidonlteatt:7.0/NRD90M/G891AUCS2BQE1:user/release-keys`

**Comment by d4rken** [comment]
That app is already a known owner?
