### ISSUE TITLE
Clutterreport: /storage/emulated/0/.ddc (new)

### ISSUE THREAD

**Issue by ddsigvertsen** [d4rken/sdmaid-public#986]
### Target
Target: `/storage/emulated/0/.ddc`
Prefix-free: `.ddc`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Download Manager`
Packagename: `com.android.providers.downloads`
Version: `5.0.42101 (1)`

### Current owners
None

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `lge/z_tmo_us/zee:4.4.2/KOT49I.D95920t/D95920t.1439786314:user/release-keys`

**Comment by d4rken** [comment]
What indicates that the download manager owns that directory?
