### ISSUE TITLE
Clutterreport: /file_contexts (FP)

### ISSUE THREAD

**Issue by lokosyanomas** [d4rken/sdmaid-public#987]
### Target
Target: `/file_contexts`
Prefix-free: `/file_contexts`
Path-prefix: ``
Type: `FILE`
Location: `UNKNOWN`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `Shell`
Packagename: `com.android.shell`
Version: `6.0-1627809043518 (23)`

### Current owners
None

### SD Maid
Version: `4.7.4 (40704)`

### Device
Fingerprint: `lge/pplus_tmo_us/pplus:6.0/MRA58K/1627809043518:user/release-keys`

### Comment
`please delete
`

**Comment by d4rken** [comment]
What indicates this?
