### ISSUE TITLE
LG Themes

### ISSUE THREAD

**Issue by porcelainedrose** [d4rken/sdmaid-public#989]
I have to weed through all the themes I download. Every new one I have to individually exclude each theme for every app.

_Sent from my LGE VS995 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by d4rken** [comment]
Please provide details if you want something to be done about it.

**Comment by porcelainedrose** [comment]
Figured it out through debug log, thank you.

_Sent from my LGE VS995 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by d4rken** [comment]
So this isn't something we should look into for users users too?

**Comment by porcelainedrose** [comment]
No, just needed to put them on the exceptions list properly. Apologies!

_Sent from my LGE VS995 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
