### ISSUE TITLE
SystemCleaner: Empty folders have size

### ISSUE THREAD

**Issue by Sreeni6304** [d4rken/sdmaid-public#995]
Hello there! I've noticed that when I'm using the SystemCleaner, a size is also shown for the Empty directories item! For example, recently I saw 13 empty directories and 108 KB shown next to it… which didn't make sense. Please try fixing this issue! I love SDMaid totally!

**Comment by d4rken** [comment]
Thanks for the report but this is working as expected. On most Android devices the filesystems sector size is ~4KB, so the minimum space anything (even empty files / folders) has to take up is 1 sector. If you view an empty file in SD Maids explorer you'll see 4KB (0B) = takes up 1 sector with 0 size.

**Comment by peeps27ster** [comment]
Thank you.

Regards,
Matthew A. Peoples, A.A.S
Mechanical Design Engineer IV

**Comment by Sreeni6304** [comment]
Oh I didn't know that! Thanks for informing!
